# The reason for repeated failure: slack in cleansing the mind

I’ve seen many cases of failure during my years in the rebooting community. Many brothers vow to reboot and not long afterward they fail in their attempt. People that relapse become despondent, self-doubting and even decadent. Some people may also give up. Many brothers choose to flee, believing that rebooting is not possible for them.

The reason for rebooting is almost always due to deteriorating health. However, the attraction towards masturbation is strong and it binds us firmly. We are the puppet controlled by a puppet master. Masturbation is like the enemy to which we suffer great casualties every time we fight him.

After a relapse, many brothers blame it on their lack of willpower and self-restraint. This reveals an inadequacy in our understanding. According to my experiences, relying solely on willpower and perseverance is extremely difficult. Unless the person is some kind of rebooting hero who would rather die than masturbate, these people are very few in number.

Seeing people failing time and again, I’d like to point out a clear way for everyone. This method has helped me to free myself of the control that masturbation had over my life. There is a good saying: *“Success has its ways, lest you have not yet found one”*. When you fail, it’s important to consider in depth on why we fail and not to carelessly blame it on lack of willpower. If we act this way, we will fail again in the future, and will thus, be unable to free ourselves from this vicious cycle.

I would now like to introduce a very important concept for everybody: **brainwashing!** Everybody has probably heard of this term before. Those brothers who managed to stay clean were all thoroughly brainwashed.

Many people may be biased towards the term brainwash and think that it’s not good. Actually, brainwashing is a neutral term that is impartial by itself, what matters is it's correct application. Depending on your own understanding, brainwashing can be understood as the purification of thoughts or the rewiring of thoughts. Many people have been looking at lots of porn, some people have been doing this for over a decade. These people are actually brainwashing themselves with filthy material and turning their minds into x-rated minds. Many people have read about the harmlessness theories with regards to masturbation. This is also a form of brainwashing where we allow erroneous beliefs to occupy our brain and render ourselves unable to distinguish right from wrong.

Through brainwashing, a person may be totally transformed to another person. We need to make good use of this *“brainwashing”* tool in order to systematically cleanse the dirt from our minds and restore purity. People may have questions as to how to brainwash and with what. In our daily lives, we are subjected to many forms of brainwashing regularly, only this happens without us being aware of it; where we are fed with notions and values.

According to principles in psychology, when we are being fed a notion for long enough, we will naturally come to accept it. This is seen in advertising where we might dislike a certain advertisement in the beginning but as time passes we come to dislike it less and then slowly accept it over time. This process is the process of brainwashing.

We need to apply brainwashing upon ourselves. As for materials, we need to look no further than the rebooting material posted by myself and other brothers. This will serve the basis for the material used for brainwashing. We must purposely engage in brainwashing by constant repetition, again and again until our brain is completely filled with rebooting-brainwash material. We need to do this from the moment we wake up in the morning, during our spare time during the day and in the evening. After a while, you will notice that your thoughts and ideology will undergo certain changes where the old filthy version of you has already vanished and it has been replaced by a brand new sense of you.

Having only *“brainwashing awareness”* is not enough, we also need the intensity. Many brothers are aware of rebooting knowledge, what they lack is *“brainwashing intensity”*. If the intensity is inadequate, the dosage will come out short and the results cannot be guaranteed. The reason why the author is able to stay clean is because he is collecting rebooting material daily and thinking about rebooting everyday. His mind is saturated with rebooting material and this material acts as a firewall which separates PMO from himself.

Everybody has washed their clothes before. The principle of clothes washing and brain washing is very similar. When our thoughts are dirty, our actions become tainted. Since the brain controls the hands, we therefore need not chop off our hands, we only need to recognize that our thoughts have become contaminated. The only way to become clean again is through brainwashing. **High dosage brainwashing, repeated brainwashing, and thorough brainwashing!** We must thoroughly rinse away the x-rated material and return the brain to its former state as we would to a filthy shirt that needs washing. To achieve a thorough result, we must increase the intensity through repeated efforts. When the intensity has been reached, the results will surely follow. By then, we will have conquered PMO and reached a stage of complete transformation, forever departing from that vile self.

For those brothers who repeatedly fail, I hope that you can pick up the psychological weapon of *“brainwashing”* to thoroughly cleanse your minds. When your minds are clean your patterns of behavior will change naturally and victory will be assured. After you have used rebooting material to brainwash yourselves, you should also take what you have learned and impart it to other brothers. In doing this, your own process of brainwashing will strengthen. The more you repeat this process the clearer will the results become and with time PMO will naturally disappear.
