# The misconception in repeated failure lies in incorrect motives of restoring one’s sexual performance

Here we will talk about motives behind rebooting. When I logged on today to answer questions, I met two brothers that are unable to escape from their vicious cycles due to incorrect motives in rebooting. Previously, I would run into similar cases everyday. This is a serious question that deserves its own topic.

## Incorrect motives {-}

To reboot in order to recover one’s sexual performance seems quite natural when first hearing about it. Many brothers have suffered a decline in their sexual function due to long-term masturbation. Some even have developed premature ejaculation symptoms and impotence, others are on their way to the said symptoms. The worst part is that these people have not realized the seriousness of the problem and act like those frogs in a boiling pot, swimming at ease in a slowly heating up pot.

According to the [Inner Canon of the Yellow Emperor]: *“Illness is due to overuse!”*. Our body is like a piece of machinery, if we only use it and ignore maintenance, the parts will quickly wear out and even become useless. Our body is capable of a certain degree of self-repair. This is why after a period of rebooting we will experience certain improvement in our sexual functions. This is the stage that is most susceptible to breaking our reboot. As our kidney essence recovers, there will certainly be reactions down there, evil thoughts will begin to flourish. Those brothers undergoing reboot with the desire to recover their sexual function will begin to feel restless. The thought to *“test”* will arise in wanting to see the degree of recovery. It is this thought that sinks them once again into the vicious cycle of PMO. Once released it’s released and we may even see a deterioration in our condition.

This is a typical case of incorrect motives. The root is incorrect and therefore the fruit is also incorrect. This motive is incorrect from the very beginning and must result in failure. This is because the reason for rebooting is to enjoy further indulgences in the future, to further satisfy their own cravings. This motive is wrong from the very beginning. The wrong cause will surely result in the wrong result. This will aggravate the vicious cycle making us incapable of escaping from it.

## Correct motives {-}

Therefore, to establish the correct rebooting motive is the key and also the foundation. This is comparable to the foundations of a skyscraper. The foundations must be solid and correct or else we are building castles of sand, prone to collapse at any moment.

I advocate the following motives:

1. **To restore health to the body and mind**: This is the very first motive for many brothers due to the deterioration of their health.

2. **To maintain a healthy way of living according to TCM**: In TCM, it is recommended to protect and cherish the essence. Studying a little TCM will further benefit our rebooting process.

3. **Religious beliefs**: For example, Buddhism is against sexual debauchery and premarital sex as well as moderation of sex post marriage.

Naturally, there are other commendable motives, such as **to not let one’s family down** and **to realize one’s dreams in life**.

We must not adopt the motive of *“reboot in order to recovery sexual functions”*. Once we have adopted the correct motive our sexual function will naturally recover. But if your motive is to merely improve the sexual functions, you will once again fall into the trap. This will happen by default and has been made known from the experiences of thousands of brothers.

Hopefully, through these writings I have brought everybody beneficial food for thought, and also a clearer understanding towards rebooting.

Feel free to contact me for any questions and I will answer them with the backing of extensive experiences. I hope to have helped brothers to overcome their vicious cycles and in rediscovering that bright and healthy self.
