# How to get rid of frequent nocturnal emissions

In this article, we will discuss the topic of nocturnal emission in depth in hopes to point out a clear path for everyone. For those readers with a keen understanding, I believe they will no longer be bothered with the worry of nocturnal emission after reading this article. Please read the following passages thoroughly.

## The problem

Out of all the hundreds of questions that I have answered, the topic of nocturnal emission makes up a big share of the count. As long as you have begun to reboot, you will likely have been troubled by nocturnal emissions. I come across this topic daily from fellow brothers, no fewer than 3 per day, the most I have received 10 per day on this issue. It could even be said that large portions of brothers are deeply troubled by nocturnal emissions. They have searched far and wide to no avail and are unable to reduce the frequency of nocturnal emissions. To have built up the kidney essence only to have them dispelled one night via nocturnal emissions is very disheartening and troubling.

Like everyone else, I’ve once made up my mind to reboot, yet I was deeply troubled by nocturnal emission. Nocturnal emission itself does not count as breaking the reboot, but my body would noticeably feel weakened. This especially applies to those brothers whose had their kidney essences greatly weakened. If you add nocturnal emission to their already weakened state is like adding frost on top of the snow. The day after nocturnal emission is when the body will feel not up to par. Some people even describes the experience of their bodies falling apart.

Although the manner that we lose our essences and qi through nocturnal emission differs from that of masturbation, the results are more or less the same. Once essences and qi have been lost the body will feel weakened. If your body is very healthy and your kidney qi is plentiful, an occasional nocturnal emission will not be felt. However, if the kidney qi has already been weakened, once we have a nocturnal emission, the effect will become very apparent. As we age, the discomfort we feel following nocturnal emission will become more apparent. Furthermore, nocturnal emission will adversely impact our determination in rebooting, although it does not count as breaking the reboot. Following nocturnal emission our stamina will noticeably decrease like an inflated ball. TCM (Chinese Traditional Medicine) advocates “accumulation of essence and qi” where the leakage of essence and qi is frowned upon.

In Taoism, the leakage of essence is called “the leaving of the pellet”. If we take away the essence how are we to transform it into qi? There is a saying that it takes 100 days in order to build up the foundation during which time there can be no leakage of essences. 100 day without leakage is a feat that is achieved by extremely few people, only those that have acquired the way of the Tao is able to achieve this feat. Actually, breaking the 100 days is like breaking the paper on papered tapered windows. If you know the method it is very easy, but if you don’t know the method, it’s very hard to decrease the frequency of essence leakage, let alone the excessive expectation of breaking the 100-day barrier.

According to my research, many people due to that they have masturbated long-term suffers from a great deficiency in their kidney qi. It would take from half a year to 8 months before they experience nocturnal emission during their reboot. The 100-day barrier that I had mentioned is addressed towards the second stage of the reboot.

I was once troubled by nocturnal emission for the better part of a year. During that time, I would experience nocturnal emission about 3-5 times each month. Sometimes, I would experience it two nights in a row. Although the number of times is not that great, it is, however, a great deal for an already weakened body where we simply cannot afford to leak so to speak.

I remember a time when I had been recovering very well only to experience a marked decline in my physical well being after a nocturnal emission. During this time period, I took care to record the times of my leakages, the dates, the time, whether or not dreams were present, I had it recorded down in detail. After a nocturnal emission, I would go on the internet to look for ways to combat it. I’ve come across a countless number of articles and posts; medicine was mentioned as well as different forms of physical exercise, also suggestive healing was mentioned. However, there were no ways to decrease the frequency of the leakage.

There was a time when I perplexed over the question of whether or not the leakage is due to the “overflowing of essences”. This was then dismissed after I discovered that there are people who are able to greatly decrease or even to halt altogether, nocturnal emission through meditation. At the time, I was thinking of how wonderful it would be to have a master to guide me into this matter. According to my understanding, those who have opened their small circulatory cycles according to Qigong are able to stop the leakage. However, this requires the guidance of a proper tutor. One should not attempt this on their own due to the risk running into issues, therefore I didn’t attempt this exercise on my own. In Qigong, by holding the horse stance one is also able to decrease the frequency of nocturnal emissions, but to achieve 100 days of no leakage is very difficult.

Nocturnal emission in Taoism is a “hard threshold”, many people have difficulty in passing this barrier. If this barrier cannot be passed, a substantial improvement (Translator’s note: I believe the author isn’t referring to a normal improvement upon an already weakened body. Instead, it is the total transformation above and beyond a normal constitution, like becoming a superman in terms of health. Therefore, the 100 days threshold should not be viewed as a prerequisite to improving one’s health. It’s the threshold towards unlocking one’s latent powers) in one’s constitution is very difficult, because whatever we put in is leaked away like a leaking water tank where the tank is never to be full.

I’ve now finally fumbled my way to the method, one can also say that I’ve reached an understanding (Translator’s note: in Chinese, understanding literally translates to “knowing the Tao”. In this context, understanding should be interpreted as having the defining “aha moment” and piercing into the truth) . Previously, I came across articles dealing with similar topics but was unable to comprehend them. This is also owing the complexity of the articles where the contents becomes more difficult the more you read them. And if I did what was prescribed in those articles it was easy to miss the essence and not hit the mark, and so the issue of nocturnal emission was not resolved. An article with several thousands of words in it can often be summarized in the last sentence. The saying goes “Falseness may spread across a thousand books, the truth is contained in one sentence”. If we are able to truly comprehend this then there is no need to read many articles lest we become even more confused. If we are not able to reach the understanding then the paper thin veil becomes like a mountain, if understanding is reached, breaking the veil is like breaking through a sheet of paper.

Ever since I have arrived at the understanding, I have not had a nocturnal emission for 3 months. I could feel that my kidney qi is becoming ever more abundant and my overall vitality is very good. Today, I will pierce this paper thin veil. Hopefully, everybody could pay close attention to the below writings. Listen, understand, and you will save money, there will be no need to take medicine and hospital expenses could be saved.

## The solution

First of all, let’s familiarize us with the concept of the “essence gate”. The essence gate is like a dam. If the dam is sturdy enough, it will not become overwhelmed by the flood of water. If not, nocturnal emissions will be frequent. If your gate is very sturdy, even if you have Ying deficiency in the kidney & liver, the dam will still hold firm. The relationship can be described the analogy of the spear and the shield. If your shield is strong, the spear will not be able to penetrate it despite its sharpness. Therefore, the question of how to reinforce the essence gate, to reinforce the “shield” is the problem that we must solve.

I was able to cast off the trouble of nocturnal emission thanks to a rhyme that I have discovered which originated from the Eight Brocade exercise, called “Hands climbing feet sturdies the kidney and the waist”. This movement has a very simple form, stand with both legs straight and use the hands to touch the ground. In broadcast gymnastics (Translator’s note: kids in Chinese schools do simple gymnastics movements during school, these movements are basically like stretching and is guided by broadcasts from loud speakers) there is a similar movement. Actually, these movements are born out of the traditional Chinese Eight Brocade Qigong exercises.

Whatever you do, do not underestimate these movements as they contain “great mysterious principles”. The said movement, through stretching the bladder meridian line found at the backside of the thighs have the function of strengthening the essence gates. The principle is the following: the kidney meridian line and the bladder meridian line is reflected off each other, their functions are connected together, qi and blood are interconnected. Therefore, by stretching the bladder meridian line, we are also working the kidney meridian line. Thus we are able to reinforce our essence gate. Executing the said movement is like tightening screws to the gate. Once the gate is secured, the issue of nocturnal emission is resolved.

In the past, I’ve encountered numerous articles, the Eight Brocade is also mentioned in them. But at the time, the contents did not stick in my mind due to my lack of understanding, I didn’t comprehend the essence of the teachings and hence did not fully grasp the power of the movement. Now I’ve come to fully understand the battle-tested effectiveness of the movement which far surpasses the efficiency of any medicine! Furthermore, the exercise is very easy to execute and to repeat over time. Those with an adequate understanding will come to treasure the movement as the most valuable asset while those with an inadequate understanding will tend to ignore and dismiss it.

## Detailed how-to

The method that I would teach everyone is: just do one of the movement from the Eight Brocade exercises, the one that targets nocturnal emissions “Hands climbing feet sturdies the kidney and the waist”. Persist in executing this movement properly, which means to find that stretchy feeling, it’s important to have that correct feeling. When we are doing this movement, we should feel the bladder meridian line being stretched tighter, straightened and lengthened like a rubber band. Once we have found this feeling, we need to intensify it like tightening the screws of the essence gate.

Every day, I would perform this movement 500 times, before I go to bed I would do it 200 times. I would strongly recommend doing this exercise before bed which is likened to putting a lock on the essence gate. If you do not do this before going to bed then we might experience nocturnal emissions. This is because the essence gate might not be properly secured which can only be secured by performing this movement.

However, we must take care to not overstrain ourselves while doing this exercise. Otherwise, the overtraining may lead to nocturnal emission, we should pay close attention to this. In the beginning, many people lack the foundations, other people may have a poor physical condition, therefore we do not need to do many repetitions in the beginning. We could, for example, start from 30 repetitions, or do them in sets, 60 repetitions may be divided into 3 sets with 20 per set and a minute of rest between the sets. The second day we do this, we may experience pain or discomfort in the body. We only need to rest for a couple days to return to normal and then continue from where we left off and we will not experience further discomfort in the body.

## Essence

Lastly, I would like to elaborate on the characteristics of the essence. Essence is a mysterious substance, if given is able to grant life and if saved is able to preserve life. There is one characteristic of the essence and that is essence is able to become “internalized”. Through meditational practices the essence may be transformed into qi, essence can then be returned to nourish the brain. (Translator’s note: in English, this may be called sexual transmutation and has been expounded upon by authors such as Napoleon Hill).

The saying that “Once essences are full it will overflow” is a theory that is only applicable to the layman. Because the layman is not cultivated in meditational practices, he will be limited on the plane of “Once essences are full, it will overflow”. This is like a person believing there are only white swans in the world just because he has only seen white swans. In reality, there are black swans as well only that they have not yet been seen by that person.

## Afterword

Once a brother has reached a certain stage in the rebooting process, he will likely be bothered with the issue of nocturnal emissions. We must learn to control the frequency of these leakages and try to limit the frequency to no more than 3 times per month. Hopefully, I have been able to provide guidance for those who are deeply troubled by nocturnal emissions. I hope one day the issue will no longer come to bother you.

## Success cases feedback

Case 1: Previously, I saw in your thread the “Hands climbing feet sturdies the kidney and the waist” movement, this is truly a remarkable move! I have kept doing this exercise for 200 times before bed every day and I have not experienced nocturnal emission for over 40 days. Before I learned about this exercise, I would experience nocturnal emission twice a week, what a powerful exercise this is. However, I did fall short and broke the reboot after 44 days. I can now guarantee to quit PMO completely and I’m full confidence.

Case 2: The first month of reboot, I had nocturnal emissions 8 times which almost frightened me to death. After reading Soaring Eagle’s article my determination is renewed. In addition, I’ve started to practice the Eight Brocade exercises. In the second month, I’ve yet to experience a single nocturnal emission. My state of mind is pretty good now! I’m very grateful for Soaring Eagle and the rebooting forums. I hope everybody can do as I did and walk on the path of righteousness. Together, we will build a bright future.

Case 3: Masturbated for 8 years! Short, ugly and poor (Translator’s note: Chinese slang for loser basically). The girl of my dreams sleeps in the arms of another man, very hurtful indeed. After having read Soaring Eagle’s posts, I’ve come to realize that I have wasted valuable years. Today is the 31st day of my reboot. At day 7, I had a nocturnal emission. Afterward, I did in according to Soaring Eagle’s methods and successfully controlled by leakage. Ever since the 7th day until today I have yet to have another nocturnal emission, my dreams are peaceful and I no longer have erotic dreams. My body clearly feels more vital, my legs are no longer soft, waist and back ache have disappeared. My appearance has become clearer and no longer carry the wretched look! My thoughts are clear now and my courage has returned. Now I do the things I enjoy doing and make money towards my freedom. I finally understand this is what is called real living. The sad and inferior days of self-rubbing is now forever behind me.

Case 4: I began rebooting after reading in rebooting forums. Afterwards, I often had nocturnal emissions which irritated me a lot. I remember when it was the most serious, I leaked 7 times within a month. When it was cold during the night, I would have an emission. My body was very irritated and felt weak overall. Even during my midday naps, I experienced emission.

At that time, I just wanted to die. But the will to live was very strong, so I gathered my courage and told my mom about rebooting and the frequent nocturnal emissions. I told her that I felt very weak so my mom took me to see an old traditional Chinese doctor. I knew that doctor from a very young age, now he is maybe 80 years old but is still working. The head of the clinic told him to come by and sit for a while and treat some patients everyday until noon. I told the old doctor about my condition and was given medicine, the doctor told me not to be nervous and that I would recover. Just like that, after taking his medicine I felt much better. I would have nocturnal emission twice every month and so I no longer felt the need to do any kidney strengthening exercises and stopped taking the medicine. After stopping the medicine the symptoms rebounded and once again I experienced frequent nocturnal emissions.

At the time, I was thinking to myself how nice it would be to no longer take any medicine and so I continued to do the exercises provided by Soaring Eagle. Now I do it everyday whereas before I was not persistent and would have nocturnal emission every couple of days. Now I do them everyday and have not leaked for about a month or two. Hehe. Though I feel that I have a small advantage which allowed my body to start recovering and that is ever since I started rebooting I have not broken the reboot. The physical as well as the mental act of masturbation no longer exist in my head. To those brother who experience frequent nocturnal emissions, please hold out, your bodies will be able to sense it. If you are good to your body, it will know it. Please continue with the kidney strengthening exercise forever.

----

Editor’s notes:

More on nocturnal emissions is discussed in Season 7, Season 16, and Season 41.

The “hands climbing feet” movement mentioned in this season is a simplified version of this movement in Eight Brocade Qigong showed in this video (from 4:54) https://youtu.be/3HMLtN7BOlY?t=294

I made a video on how to do the “hands climbing feet” movement as I learned in “broadcast gymnastics” in middle school: https://youtu.be/-xrnNS6ZXA4
When doing the movement, you can keep your legs straight instead of stepping aside. The important thing is the stretchy feeling.
