# Be vigilant during the flatline period and of the 'fed up' mood

Everyday, we have many brothers breaking their reboot. The annoyance and the disappointment that we experience following a relapse is not hard to understand. I believe every brother has had this experience repeatedly. From vowing to stay clean to being defeated time and again to finally staying clean for good is a long and slow process. To change our awareness is a process of learning, it’s a process of ever-increasing our level of awareness. In this season, we will elaborate on the flatlining period and of the 'fed up' mood during the rebooting process.

## Be vigilant during the flatline period

For the brothers that repeatedly relapse, if you are familiar with TCM you will notice that there is a pattern to the relapses. The pattern of the relapse and the *“value of kidney qi”* is intricately interconnected. When you feel that your body is weak, you will instinctively want to reboot. Once you have been rebooting for a while and kidney qi has started to recover somewhat, this is when it’s very easy to relapse.

In the beginning of the reboot, we will experience a period of flatlining with regards to our desires. Many people during this stage do not experience strong cravings and are able to control themselves. But during the flatlining period, it’s very easy to let our guard down and think that we have succeeded. In reality, our desires are only temporarily dormant. Once our kidney qi has recovered to a certain degree, that is when the desires are awakened. During this stage, the relapse is often accompanied by vigorous masturbation. All our previous efforts have gone down the drain.

The period of flatline varies from person to person. For some people, that period is 3 days. For others, it can be 20 days or 60 days. According to my understanding, the average duration of the flatline period is around 3 weeks or 21 days. Following the flatlining period is the peak period for relapses. After the relapse is the period of regret, the feeling of doubt and regret will be quite strong at this stage.

The purpose of this article is to let everyone become aware of the flatline period. During this period, we need to increase our alertness and maintain our vigilance. We must not slack in our rebooting studies. Only through the unceasing study of rebooting material can we increase our understanding and our level of determination. The level of determination is comparable to when we grind for levels in an internet game. In the beginning, our level is low and we succumb to the temptations of the heart. Once we have continuously studied rebooting material and our level of determination has risen, the heart can no longer tempt us.

If you don’t study rebooting knowledge, no understanding will take place, the level of determination will forever remain at a low level. And when we encounter a temptation the result is obvious; every encounter will result in failure. When we see x-rated material, we will not have any determination. Once we see it, our heart begins to flutter and we click on the material. Without immunity and resistance, we are finished.

**[vow to reboot] -> [flatline period] -> [kidney qi recovers somewhat] -> [peak period for relapse] -> [period for regret]**

This is the process of relapse, also known as the vicious circle. Many people cannot escape from this circle for years or even decades. Once I was stuck in this vicious circle for well over a decade because at the time I didn’t reach understanding, I didn’t study rebooting material nor was I aware of how to maintain a healthy lifestyle. I only knew the brute force way and the blind way. With regards to the brute force way, I thought that I will be able to quit masturbation by relying on willpower. In reality, the brute force way will surely result in failure because we have not raised our state of awareness. The blind way is trying to reboot without the knowledge of rebooting. The blind way will also surely fail for the same reason.

The contamination of the brain by x-rated material is similar to when a computer is infected by a virus. When a computer is struck by a virus, it will affect how the systems operate. Similarly, when the human brain is contaminated our health will have problems. Normally, the areas where problems first appear is in the urinary system, mainly in the form of prostatitis. Afterwards, once the kidneys are weakened, many illnesses will result from weakened kidneys, any illness might appear. The decrease in our mental faculties is also very common. TCM: *in the above, kidneys are connected to the brain*. Masturbation injures the kidneys and hence must also injure our mental power, memory and concentration will both decrease. If our mental power is lacking our studies and career will invariably suffer.

## Fed up mood during rebooting

Let’s now talk about the fed up mood with regards to rebooting.

The mood of being fed up is very common during reboot. This is like being fed up with a piece of clothing, a food dish or a cellphone. Studying rebooting material a lot can also make us feel fed up. Once we experience this state, our rebooting efforts will be halved. This is why it’s important to learn to adjust our attitude and state of mind. We need to manage our mood well.

As soon as we begin to feel fed up, we need to make adjustments. Cultivate the habit of reading and studying, study rebooting material daily without slacking. Once the habit is established, we will not easily become fed up anymore. This is like a toothbrush, once a habit forms, it becomes natural. If we don’t brush our teeth one day, we might feel uncomfortable. Similarly, we need to find this state of mind with our rebooting studies.

Of course, we don’t have to study the topic of rebooting exclusively. Cultivating a healthy lifestyle can also be a good topic due to the similarity it shares with rebooting. In addition, a rebooting article can be read numerous times. Through reinforcement comes new learning, the more you read, the deeper the understanding will become as opposed to dabbling into something and then stopping and forgetting.

## Concluding remarks

>“If you know the enemy and know yourself, you need not fear the result of a hundred battles”

>— Sun Tzu

To reboot we need to understand how to the reboot is broken and why we cannot escape the vicious cycle. Every brother should think deeply about these questions. When you have understood, our state of awareness will be raised. If we remain in our initial level of understanding, the brute force way and the blind way will both lead to failure. Only through continuous efforts in our studies can we arrive at that “aha moment”. Once there our state of awareness will be different, our level of determination will be raised, the distance to ridding PMO for good will be within reach. Keep on fighting brothers!
