# How to supplement the health the right way

Today, let’s discuss the topic of “supplementing” *(Translator’s note: the word supplementation in this context can also be interpreted as to repair or to mend)*. Just like the question of how to quit PMO, supplementing is a popular question that many brothers pay a great deal of attention to. There is a good deal of misconception surrounding this topic. This article will now dig into the issue in detail. Hopefully, it will help everyone.

Supplementing is a big topic with a deep depth of knowledge, it is not as simple as one would think it to be. Many brothers due to their long-term habit of PMO, have had their bodies greatly weakened. Their first reaction is naturally to take supplements. They tend to want to ingest something as a supplement but because they do not know what to ingest. They will go to a traditional Chinese doctor and then take herbal medicine to supplement their kidney qi. To supplement is necessary, but one has to learn how to supplement with high efficiency and not with low efficiency, it requires careful attention.

## Heart/mind cultivation

Regardless of whether we look for dietary or medical supplementation on our own, or have a doctor prescribe medicine for us, the foremost prerequisite to supplementing is this: the cultivation of heart/mind must be in place. This is because once you have taken the supplements, your kidney qi will start to recover. Once it has recovered then desires will appear, this is when it’s very easy to relapse. Relapsing is equivalent to losing kidney qi, this will greater hamper the results of the supplements. Therefore, if you are not aware of the importance in cultivating the heart/mind and go ahead with the supplements anyway, the result will be sporadic with a mix of both good and bad periods, the body will not have greatly recovered. We may even experience adverse side effects due to the large number of supplements we have taken, making us worse off.

Furthermore, there will be diminishing returns in taking supplements. This is apparent once we have taken lots of supplements where the effect is most noticeable in the beginning. And so this is the first misconception of the topic of the supplement: only knowing how to supplement but not the cultivation of heart/mind. Everyone should, therefore, emphasize the cultivation of the heart/mind and the study of rebooting material. Raise the effort in heart/mind cultivation. Only through reboot studies, may we increase the level of determination. With the determination, we will naturally fantasize less and even achieve no fantasizing. If we apply supplements on top of this state of mind, we will multiply the efficiency. Otherwise, what we put in from above will only be leaked from below thus preventing kidney qi from ever becoming full.

## The importance of rice

The second misconception regarding supplementation: ignoring the importance of rice in the diet.

Actually, the most beneficial supplements for the essence and qi is not ginseng, deer antlers, yam, black beans or any of the supplemental medicines. Instead, we find it in rice! If we imagine the supplementation process to building a house, rice is the foundation. If you don’t properly eat your rice, then no matter how many other supplements you take, you will not see great results. This is because the foundation is not solid.

There are many ways to prepare rice, I would approve congee.

A masterpiece within the topic of health maintenance [Lao Lao Heng Yan] states: *“Ingesting a diluted bowl of congee everyday on empty stomach is able to rejuvenate, give birth to saliva and quicken digestion, the benefits is not trifling”*. In [Shi Zhou], the great Song dynasty poet Lou You (1125-1210) wrote: *“People far and wide studies longevity, not knowing what they study lies right before their eyes, to obtain longevity one has only to offer congee to the Gods”*. The benefit of congee is clearly observed in the fact that Lou You lived for over 80 years. Traditional Chinese medicine believes that congee is able to make semen flourish, cultivate the stomach qi, help with the digestion and nourish the entire existence.

The Tang dynasty doctor Sun Simiao (581−682) suffered from many ailments as a child and hence took up to study medicine, combined Buddhism and Taoism wisdom in health maintenance and lived to be over 100 years. He also advocated the intake of congee in the morning. In addition, use Chinese medicine in making congee, using the *“rice qi”* and water moisture as *“medicine enhancers”* and administer according to the *“biological timing”* of the five viscera and six bowels to nurse one’s body and cure diseases.

Therefore, do not focus on the trees and lose sight of the forest. In other words, do not ignore the importance of congee as the most effective means of supplementing the essence. Eating your rice is more important than anything else.

## Consulting doctors

The third error regarding supplementation: blindly supplementing without consulting a traditional Chinese doctor.

This error is very common among brothers. Some people think it’s a hassle to go to the doctor, others are afraid of embarrassment and so on and so forth. These people may end up looking up supplements on the internet by comparing their own symptoms against a suitable supplement. They then go to the drugstore to buy the supplement. In reality, this method is biased. Kidney deficiency is not like catching the flu where one can just solve the problem by picking up flu medicine at the drugstore. Kidney deficiency requires correct diagnosis.

According to TCM: *“Same disease, different treatment. Different treatment, same disease.”* Even with the same symptoms, because we all have different physiologies, the recipe might not be the same. Only after the four diagnostic methods *(Translator’s note: as in looking, listening, asking and feeling the pulse)* may a correct judgment be made. Therefore, the preferred way is to go to a well-known clinic and seek an old and experienced Chinese traditional doctor.

Also, do not put all hope in the doctor and the medicine. 30% treatment, 70% maintenance *(Translator’s note: 70% of the recovery consists of maintaining a proper diet and healthy lifestyle. This is much more gradual compared to taking medicines)*. If you do not study how to maintain a good health and have not mastered the way of good health maintenance, the effectiveness of medicine will be severely limited. For example, if you are taking supplemental medicine but at the same time stays up at night and have a long period of sitting, the effectiveness of the medicine will be very low.

In addition, strong supplementation is not suitable for many people in the weakened state. This is because a weakened body cannot handle a strong tonic. For example, if we administer a strong tonic for kidney and spleen yang deficiency, the body will not be able to absorb the tonic which will result in extra burden for the stomach and intestines. Therefore, it is best to seek an experienced traditional Chinese doctor for diagnosis and not blindly supplement on one’s own initiative.

## Exercise

The fourth misconception regarding the supplementation: no exercise.

When talking about supplementing the first reaction is what to ingest. Actually, the most brilliant supplement is not in eating but in moving! A medicinal supplement is not as good as a dietary supplement, and a dietary supplement is not as good as a moving supplement. Moving supplement is a very good word. Exercise may help your body to recover which surpasses the healing effect of a medicine.

Traditional Chinese medicine states that 3 Yang opens up good fortune: kindness, delight, and exercise. Also stated is that strong Yang leads to longevity: *“The one strong with Yang energy is like the sky and the sun, to lose it results in discounted longevity and brightness is lost”*. Therefore, exercise as a supplement is very effective. As long as we do not overstrain ourselves, exercise is very beneficial for the recovery of the body.

The misconception that people have is not to exercise. People complain about the slow pace of their recovery, you only need to ask yourself if you are exercising and whether or not you have learned how to maintain the health? To cut out PMO alone is far from enough, exercise must be added. We must learn the way to maintain good health. If we do all this recovery will be quick.

The 3 Yang includes “kindness raises Yang” in this is contained deep health maintaining philosophy. By doing deeds of kindness including the release of wild animals according to Buddhism, is very beneficial to the body’s recovery. Do kind deeds and have a merciful heart, the Yang energy will naturally supplement itself to fullness.

The optimal supplemental method that I recommend: to sit in meditation and doing standing exercise.

I have previously tried out many supplemental medicines, none of them equal sitting in meditation and doing standing exercises. Sitting meditation and standing exercises not only replenish vital energy but also benefit the cultivation of the heart, two birds in one stone. They don't cost money nor have any side effects. Many people may think that one can run into issues *(Translator’s notes: by issues the author is referring to the adverse side effects that a Qigong practitioner may encounter during meditation. These side effects may manifest physically or psychologically and are not a part of the normal manifestations that occur with regards to Qigong practice)* by practicing Qigong, this does indeed occur. However, the form that I advocate is not the form that is likely to run into issues. I’m talking about the sitting meditation and standing exercise that is related to health maintenance. In doing these, no issues will occur.

## The best supplementation

The best supplemental medicine: no PMO! This is the best way of supplementation. If you take strong tonics for a few fortnights, two consecutive nights of nocturnal emissions will bring you back to square one. Therefore, having the proper supplement in place involves working towards reducing the number of nocturnal emissions to a minimum. Put an end to all factors that may contribute towards having these emissions. Combine this with proactive physical exercises and the body will enjoy a rather quick recovery. For brothers with a long history of PMO, whose kidney qi has been overdrafted and are showing many physical symptoms, the question of how to reduce the frequency of nocturnal emission is of paramount importance. One must take this question into consideration and research into it.

Lastly, I would like to touch upon the problem of prostatitis. This is one of the most commonly occurring issues with brothers. Almost everyone has encountered it. Many brothers carry misconceptions in their minds thinking that having prostatitis is like catching a cold, that one can simply take some medicine and hope to get well. In reality, this is completely false. There are many brothers who have visited countless doctors and spent tens of thousands in medical bills but are still not cured. What is the reason?

In fact, if one is familiar with TCM then it is understood that masturbation hurts kidney qi and when kidney qi has been injured then prostatitis will appear. The doctor may heal you and help you to recover your kidney qi, prostatitis might go away temporarily, but when you continue to masturbate you hurt your kidney qi once more. Therefore, prostatitis is very likely to return. The relapse rate for prostatitis is over 90%.

This happens because we have not grasped medical knowledge, the problem is in our understanding. Only if we cut off PMO completely is there the hope of making a full recovery from prostatitis. This form of full recovery corresponds to a leap in understanding where the root of the problem has been understood. In paying attention to maintaining a healthy lifestyle and using the kidney qi sparingly, prostatitis is unlikely to relapse. If we have not deeply understood the problem we will have to visit the hospital frequently and spend ever more money in diagnosing and medical expenses.
