# Prostatitis, varicocele, premature ejaculation and impotence recovery

Prostatitis and varicocele are relatively common illnesses for brothers, especially prostatitis. Plenty of brothers suffer from frequent urination due to the fact that PMO damages the kidneys qi. Today, we will discuss prostatitis and varicocele according to my experiences and research. Do not underestimate these two illnesses by any means.

## Prostatitis

### My expriences with protatitis

I contracted prostatitis very early on, within a year of when I started to masturbate. The symptoms of frequent and urgent urination appeared. At most, I would go to the toilet over 10 times during the span of a night. During the day, I would need to pee shortly after drinking water, holding it back was impossible.

Later on, I learned that the inability to hold back urine is very common among elderly people. This is because elderly people have greatly weakened kidney qi and hence they have lost the ability to withhold urine. Children, by contrast, have an abundance of kidney qi, enabling them to withhold peeing even on a full bladder for over an hour.

Therefore, frequent urination is a sign that your kidney qi is on the decline and that PMO needs to cease. This is your body sending you warnings. If you do not heed the warning and continue what you are doing, this will result in the more serious form of prostatitis. The problem does not stop at prostatitis, the whole body might experience symptoms. Many diseases arise from weakened kidneys, prostatitis is only one of the earliest appearing symptoms.

Normally, when we encounter the symptom of frequent urination, we should know that it is caused by PMO. This is because before we engaged in PMO the symptoms were absent. During this time, most people would rein in the horse at the edge of the precipice so to speak and start to curb masturbation on their own initiative. After a couple weeks, kidney qi will have started to recover, masturbation resumes and frequent urination again makes its presence known.

Usually, we are given two forms of medicine at the hospital, one specifically treats prostatitis and the other treats inflammation. The more ethical doctors will advise you to stop masturbation and long sittings. The actual situation is that many doctors have not realized the danger of masturbation. Many doctors subscribe by the harmlessness theory of masturbation, this is very sad indeed.

Now that I have completely cut out PMO, frequent urination has not resurfaced. After studying TCM, I came to realize that abundant kidney qi wards off many forms of unhealthy influences, weak kidney qi will invite onto itself any possible illness. Many brothers have spent tens of thousands on medical expenses in order to treat prostatitis but the illness remains and is not cured over an extended period of time. Often, prostatitis will temporarily heal only to reappear again after masturbation is resumed, the relapse rate is very high.

## The cure for prostatitis

Actually, the root reason for relapses is due to lack of understanding. Many brothers treat prostatitis like a cold, they think that by eating a few pills the problem will resolve itself and never appear again. This is a grave misunderstanding. The outbreak of prostatitis is precisely due to that fact that kidney qi has been weakened as a result of masturbation. The purpose of taking medicine is to recover kidney qi. If you continue to masturbate once kidney qi has recovered, you will injure it again and prostatitis will reappear. If you still have not recognized the seriousness of kidney qi and treat prostatitis like a common flu, then you will never treat the illness from its roots in your lifetime. After the age of 40, the illness may proliferate or develop into more serious forms.

**Therefore, there is only one way to completely cure prostatitis, and that is to completely quit PMO and also sexual fantasizing, exercise proactively, not staying up late during the nights and not sitting in long periods at a time. Cultivate favorable lifestyle and dietary habits**. For those married brothers, if your prostatitis is serious, I would advise you to exercise self-restraint for a while until you have accumulated abundant kidney qi. Once kidney qi is plentiful, use it sparingly which means to practice moderation in married sex life. In this way, relapses in prostatitis can be avoided. [Inner Canon of the Yellow Emperor]: *illness is due to overuse!* Therefore, the practice of moderation is a learning in itself, to overdo is the same as to underdo.

## Is asceticism harmful?

Many people ask the question of whether asceticism is harmful. Rookies will especially would this question. My answer is that asceticism is harmless, if it was harmful then wouldn’t that mean all monks are unhealthy? The reality is that many monks live up to 100 years and beyond. Master Hsu Yun lived 120 years, Master Benhuan reached the age of 106 years. In the Buddhist school, there are many cases of longevity. Therefore, the notion that asceticism is harmful to the body is sheer nonsense. There is only one scenario that would make asceticism harmful, and that is when the cultivation of heart/mind is inadequate and sexual fantasizing occurs daily with the urge to masturbate but one does not dare to act upon it. The continuous restraint in this manner would possibly give rise to problems. If cultivation is adequate then self-restraint is harmless.

## The harmfulness of sexual fantasizing

I would like to add a point and that is the harmfulness of sexual fantasizing. Many rookies ask: if fantasizing without masturbation counts as breaking the reboot and whether or not it’s harmful? Actually, sexual fantasizing seriously depletes the body, even more serious than masturbation itself. This is clearly treated in TCM. Many brothers discover that their spirit/manner is depressed after looking at themselves in the mirror following sexual fantasies. In TCM this is called: *essence leaves when the mind wanders*. As long as we engage in sexual fantasizing, essence will automatically leave us. Masturbation is the visible form of depletion while sexual fantasizing is the invisible form, the invisible being the more serious form.

Hopefully all brothers would deeply recognize what has been said and increase their rebooting studies, intensify the heart/mind cultivation and cut out all sexual fantasies. Cut out the thought once it has arisen. An arisen thought should not be followed. The mind being immediately aware of new thoughts and the ceasing of the thought once the mind is aware of it.

## Prostatitis may lead to infertility

Every person with prostatitis will of course not become infertile, specifically, it will depend on the seriousness of your condition. Prostatitis will also result in the decline of sperm quality. If the quality is poor, offspring will not live up to an excellent standard. It’s possible that your future child will suffer from health problems the moment it is born, with inadequate prenatal conditions.

Many brothers are skeptical of the notion of karma because they have indulged themselves in ignorance during their youthful years, it is very possible that fertility will be lost in the future. This, in reality, is karma. During this day and age of indulgence, infertility is ever more common and troubles many people. In this stage, you are possibly troubled by the symptoms caused by masturbation. Once you are married, the worry will be on the inadequate sperm quality which is unable to cause pregnancy.

Moreover, according to TCM: *kidneys are connected to the brain in the above!* Masturbation hurts the kidney and brain power. A decrease in the brain power will adversely affect studies and career to a large degree. Therefore, it would be wise to put a stop to pre-marital sex and take good care in building up the kidney qi so that in the future, one might give birth to a healthy child.

Everyday, I answer questions in the forums. Up until now, I estimate to have answered a thousand questions. Among those that have engaged in premarital sex and let loose their indulgence, many brothers have lost their sexual function. The emergence of pre-ejaculation and impotence among brothers is incredibly many. Suppose that your body is not working properly when you are single. After marriage, how do you suppose to keep a healthy sex life? If your wife is not understanding then divorce is a big possibility. To discard one's health before marriage, how will one cope with the future? This is a very serious and realistic question. Therefore, the recommendation to abolishing pre-marital sex is very very important. Not only does it affect the quality of your married life but also the future generation.

## Varicocele

Many people suffer from varicocele but they are unaware of it. Varicocele may not have any uncomfortable symptoms. One can find out if one has the illness by taking an ultrasonic test in the hospital.

Normally, varicocele will occur on the left side in 99% of the cases, in other words above the left testicles. In serious cases, the varicose veins clump together in an earthworm-like shape and can be felt by the fingers with the addition of a bulging feeling. In lighter cases, there may not be any uncomfortable symptoms present which is the form that I had. I have had it for over a decade without knowing it myself. I found out by taking an ultrasonic test at the hospital. Some people may have it on the left side, others may have it on both sides with the left side taking up the majority of the cases.

Varicocele is also one of the main culprits behind infertility. Varicocele greatly affects the quality of the sperm. The basic reason for developing this illness is due to long-term masturbating and long-term sitting, this is also karma.

Many brothers are unaware that they have caught varicocele which is why it’s easily neglected. I have had it for over a decade without being aware of it. This is because my illness was not serious and feelings of discomfort were absent. I discovered that I had varicocele when I went to the hospital for a checkup. During the time, I was suffering from prostatitis and varicocele simultaneously. One could imagine the low sperm quality at the time which was not up to the standard required for pregnancy. Now that I have cut out masturbation for good and accumulated plenty of kidney qi, sperm quality has returned to normal.

Although my case of varicocele was mild, the doctor still advised me to undergo an operation. He said something that was very discouraging; even if I had an operation, it would not guarantee that I would regain my fertility, luck is also involved! Afterwards, from studying TCM I came to understood that an operation would only help to resolve ligation and not the recovery of kidney qi. If your kidney qi is weakened, even an operation would not help. Therefore, taking care in accumulating kidney qi is the key to recovery, or else you might undergo an operation and recover temporarily, only to masturbate again and deplete the kidney qi which will  cause to varicocele relapse and all the crying in the world will be of no use.

## Premature ejaculation and impotence

Lastly, let’s talk about the tendency of premature ejaculation and impotence and their recovery. Actually, I have already discussed this in detail [Chapter 1](https://eagle3y3s.github.io/rebootedit/the-reason-for-repeated-failure-slack-in-cleansing-the-mind.html). The tendency of premature ejaculation and impotence are manifestations of the body’s own protection mechanism. The concept is similar to the closing of skin pores when exposed to cold air. Premature ejaculation and impotence occur when the body is self-preserving. Many brothers are unaware of this fact. They instead go on to look for filthy material and overdraft their kidney qi. In this way, the tendency of premature ejaculation and impotence becomes more severe.

When many brothers encounter premature ejaculation and impotence for the first time, their initial reaction is not to quit masturbation but to supplement the body via diet, or to visit the doctor in hopes to recover. Dietary supplements do indeed help in the recovery of kidney qi, but once kidney qi is recovered and you continue to masturbate and deplete it, the aforementioned tendencies will return. By taking the same supplements again the effects will not be very apparent because the effect of medicines tends to diminish over time.

Therefore, dietary supplements are incapable of solving the root issue. One must cut out PMO, exercise proactively and have the correct lifestyle habits in place to assist the accumulation of kidney qi. Once the kidney qi is abundant, do not engage in testing *(Translator’s note: we have talked about this in Season 2, masturbating in order to find out if one has recovered is called testing)*. By testing, we again fall into the trap of PMO and into the vicious circle.

Furthermore, the recovery of premature ejaculation and impotence is very slow, 3 months in the fast cases and over a year or more for slower cases. Therefore, make preparations for a long and drawn out battle, slowly accumulate kidney qi little by little and do not resort to doing anything that will injure kidney qi.

Many people only know of sex as the sole cause to deplete kidney qi. In reality there are many ways of depletion: indulgences, staying up during the night, anger, long sittings, cold beverages, overly fatigue, over-strenuous exertion, exposure to AC, all of the mentioned will have a wear on the kidney qi. When your kidney qi is plentiful, you will not feel much discomfort, just like we won’t feel poor if we spend a little money out of a bulging wallet. But when your kidney qi is not plentiful, this will be like adding frost on top of snow. TCM treats kidney qi like currency for the health. During normal times, we need to save it and not blindly waste it. We need to understand how to cultivate the health and kidney qi and to nurture it. This way, we will be able to keep a healthy spirit.

## The problem in understanding

After having answered so many questions, I feel that many brothers are not only inflicted with physical symptoms. More importantly, there is a problem in their understanding. When misconceptions exist in the understanding, it is very difficult to cut out PMO. As long as the misconceptions are present, one can forget about recovering from prostatitis, premature ejaculation, and impotence.

Therefore, we must all study rebooting knowledge, including health maintenance knowledge from TCM, in order to correct the misconceptions in our thoughts. When the correct understanding and thoughts have been formed in your brain, you will know what to do instead of putting all hope on medicine and on doctors, which would be equivalent to seeking fish on a tree.

Diseases that arise from kidney qi deficiency cannot be cured by medicine or doctors alone, it is a process of 30% treatment and 70% maintenance. Importance is placed on maintenance. Once we’ve learned how to cultivate kidney qi and it becomes plentiful, evil of all shapes and forms is warded off. Whatever you do, do not treat kidney qi deficiency as mere flu and hope to resolve it with medicine. Kidney deficiency requires maintenance and not only medication.

## Conclusion

Nowadays, the younger generation is walking the same winding path of falseness that I have once trodden. This is because Chinese education is lacking in this area. This knowledge cannot be learned in schools, therefore there is much misunderstanding in the thoughts of brothers. Misconceptions in understanding will cause one to sink ever deeper into the trap of PMO unable extricate oneself from it.

Many people, once addicted, resemble walking zombies, the power of the pink opium is not to be underestimated. Plenty of brothers that I have conversed with wanted to take their lives. Because masturbation in combination with staying up during the night has brought upon them even more serious forms of mental and anxiety disorder; autonomic disorders, OCD, depression. These disorders are unimaginable among those that suffer from frequent urination. I now write this article in hopes that the younger generation does not have to repeat my mistakes. I hope that this article has brought everybody beneficial inspiration. Comrades in the trenches of rebooting, keep on fighting!
