# 3 stages of rebooting and a deep analysis regarding staying up during the night and long sittings

## Revisit the issue of nocturnal emissions

Before we head over to the main texts, let’s revisit the issue of nocturnal emissions once again. I have written an article about this in Season 3 where I had recommended a movement from the Eight Brocade qigong. Many brothers have tried this exercise and I have received two types of feedback: The first type is from people who had not experienced any noticeable benefit and the other type is from people who have benefited greatly from the said exercise. Many people have broken their records in the number of days without nocturnal emissions. Some have gone on for 20 days without any emissions while others have only had one emission in well over a month, which is a vast improvement compared to their previous 3 times per month.

Why have some people not noticed much of a difference after practicing the Eight Brocade movement? Actually, the reason lies with the individual. Many people have not found the feeling while doing this movement. They sloppily get it over with and after having performed 200 of them without finding the strong stretching sensation they then head to bed. How can the benefit be guaranteed in this case? One must find the correct sensation by finding the stretching feeling and intensifying the feeling of stretching, elongating and straightening. One must carry this strong sensation to bed and in doing so there will be results.

Moreover, there are many other causes that may bring about nocturnal emission: sexual fantasizing during the day, fatigue during the day, alcohol consumption, too much meat consumption, sleeping facing down, sleeping nude, sun drying blankets, overly thick blankets, meditation prior to bed, too tight underwear. One must try to avoid all these factors.

Reducing the number of nocturnal emissions to a minimum is very beneficial for the recovery of the body. Otherwise, it doesn’t matter how many supplements you take because they will all leak away during those frequent episodes of nocturnal emissions. Therefore, the question of how to reduce the number of emissions is something that all brothers must face and consider.

The movement I have recommended from the Eight Brocade exercise, if done correctly is very effective for securing the essence gate. The key is to find the correct sensation. I cannot guarantee that you will not experience nocturnal emissions by doing the said exercise. I can guarantee, however, given that you have found the correct sensation and have avoided the aforementioned contributing factors towards nocturnal emissions, that one is able to bring down the number of emissions to 1 per month or 12 times/year. By bringing down the number of emissions to these figures it will greatly benefit the recovery of the body.

When one first starts to perform this movement, there will be soreness in the muscles. In physiology, this is called *“delayed muscle soreness”*. Normally, the soreness will automatically vanish after 1-3 weeks. If we then repeat the same movement there will be no more soreness. This process requires time. As long as one is persistent, the soreness will disappear by itself, so do not worry if the soreness appears.

Additionally, those people who have practiced ligament exercises and are able to touch the ground with their palms, can try to increase the intensity. For example, by raising the tip of the foot, touching one foot with both hands or by doing the exercise while standing on a small bench. Take care to not perform the movement too quickly or else one will be prone to feel dizzy. Try to find your own pace and rhythm and combine it with the right sensation, this will form the correct exercise.

The above kidney strengthening exercise is the distillation of my own experiences and experiments. I am able to, therefore, share my most direct experience with everybody and hope that everyone will have ample opportunities to try it out. Persist in doing this movement and in time one will find the sensation. For some talented people, they will find the sensation very quickly. For others, it will take longer until they find the feeling.

Below we will enter the main topic of Season 7

## 3 stages of rebooting

I have talked about the 3 stages of rebooting in Season 4, these are:

**Beginner’s stage**: blind way and the brute force way of rebooting, no studies.
**Intermediate stage**: studies rebooting, one begins to understand the importance of learning about rebooting.
**Advanced stage**: understands, studies combined with realization, the possibility of successful reboot becomes a reality.

Everybody can compare their own progress with the above stages. Many brothers have been rebooting for many years but still remain in the beginner’s stage. When they break their reboot the blame is placed on the lack of willpower. In fact, by relying on willpower in the brute force manner will surely result in failure. To be successful, one must study rebooting knowledge and read articles about rebooting in order to raise one’s awareness and the level of determination. With determination, we are able to defeat the temptations of the mind. Without it, we will lack the resistance and surrender ourselves to it.

Rebooting and failing for numerous years is likened to you going to school. If you do not study you will forever remain in grade 1. But if you study constantly, you will be able to progress into middle school, high school and onto college. Rebooting works in the same way. One must constantly study in order to raise the determination. When your determination is like a little tree sapling, heavy winds are able to topple it. But when your determination is sturdy as a mountain, not even typhoons or hurricanes will be able to shift you, not even a nuclear blast will move you. Do not blame, therefore, on external circumstances when we break our reboot although it is true that the temptation in this indulgence grounded society is very great. However, if your determination is strong enough, no amount of temptation will be able to sway you. Seeing is as not seeing, thoughts fail to enter our intention.

In order to raise the level of determination, we must study vast amounts of rebooting articles and knowledge. The more we read and study the more we will understand. These studies are the kind that we must carry out everyday and not one of those articles about the harmfulness of masturbation where you read through once and then stop studying. One must study rebooting articles everyday. If you have religious beliefs then all the better because having a belief will greatly aid your rebooting efforts. People with religious beliefs have an easier time to successfully reboot.

Once you have realized the importance of studying rebooting knowledge, you will then search for rebooting articles on your own initiative. The more effort we put in studying, the higher the level of our determination until we reach a stage of natural understanding. Once there, our level of awareness vastly increases and the record of rebooting days will greatly increase. Naturally, the speed of progress will depend on the perception of the reader. Readers with keen perceptions will be able to skip grades, while others will have to remain in grades.

Some people are able to reboot for over 200 days and still fail. This is owing to slack in studying or being weary of studying. As soon as we relax, our vigilance the temptations will seize the opportunity to enter our mind. If your understanding hasn’t reached a masterly level, it is very easy to slip and before we know it, we have relapsed. Actually, we don’t need to look for new articles once we have reached a certain stage in our studies and have come to an adequate level of understanding. In this case, it will be enough to find a few articles that we are fond of and re-read them daily. Thus, learning by repetition similar to the morning and evening sessions in Buddhism.

After having answered a thousand questions, I deeply feel that the majority of the brothers are still in the beginner’s stage. This especially applies to newcomers. Without studying, it is hard to avoid failure. This is the reason why I have recommended studying more rebooting knowledge and read reboot articles in my answers. Understanding can only be obtained through learning.

There was a time when I didn’t study and my rebooting record was 28 days, I believe that many brothers would have been able to beat me. However, once when I gained the understanding, my determination greatly increased and success was to be had. Right now, I’m still in the stage of studying and gaining more understanding with newly found insights everyday. I have come to a complete understanding. Once you are there, you will be able to cut out PMO forever.

In my current stage, there is no more sexual fantasizing, because fantasizing is an invisible way of expensing kidney qi. When you have understood this from studying TCM, I believe that many brothers will fantasize as little as possible. Through continuous studies and the accumulation of knowledge, the reboot will become more professional and wider in scope. We will no longer stay on the level of blind and brute force reboot.

## The harmfulness of staying up late and long sitting

Let’s now discuss body recovery following rebooting. This chapter mainly deals with the harmfulness of staying up late and long sitting.

Many brothers comment that they have experienced little improvement or a very slow speed of recovery during their reboot. There are several factors to this: frequent nocturnal emissions, unhealthy lifestyle and also a lack of habitual/consistent exercise.

According to my research, those who frequently exercise while rebooting recover faster and better compared to those who don’t exercise. This is what is mentioned in TCM: *movement raises the Yang energy, strong Yang energy contributes to longevity*. Of course, I’m talking about moderate exercise and not over-exercising. Over-exercising is just as bad as under-exercising.

Although lots of brothers are undergoing rebooting, they are still staying up late at nights and sitting for long stretches of time. Either they lack a deep understanding in these two issues, or they do it out of habit. The power of habit is very strong and is difficult to correct immediately. However difficult, we must still change the habit with the courage that a warrior possesses. We must correct it or the negative consequences will not be light.

## Staying up late

Many brothers think that this means to stay up the entire night. Actually, when I refer to staying up late, I mean sleeping later than 23:00. If you go to bed past 23:00 then the body will have a hard time recovering. This is because what is mentioned in TCM: 23:00 is the time when Yang energy begins to rise. During this time, one must be asleep for the body to recovery better. If past this time, the body will have a harder time to recover.

We can compare this to the analogy of missing the last bus at night. We can only resort to waiting for the bus on the following day. According to TCM, if we staying up during one night, a long period of time is required for us to recover from it. The latent harm in staying up a single night might require 100 days for the body to fully recover. Many brothers don’t understand this medical knowledge and treat staying up as regular snacks.

Oftentimes, it is the combination of staying up, long sitting and masturbation that quickly wrecks the health and they may see the onset of neurasthenia and psychological problems. This is a vicious circle and the necessary karma that the mentioned bad habits will surely result. While on reboot, one must also cut out staying up during the night since it is very damaging to our essences. We must be aware of this medical knowledge. If your understanding is not deep enough then you will continue to stay up during the night. Do not, under any circumstance, underestimate the effect of this habit. It’s like the frog in the boiling pot where slowly and surely we are making our bodies useless.

Optimally, one should go to bed at around 21:30. Many brothers have difficulty in doing this. What I want to say is to avoid staying up late at all cost, or else the damage will be on you. Of the brothers that I have conversed with, those that do not stay up late recover faster than those that do.

## Long sitting

Let’s talk about long sitting. This is maybe the first time that many brothers have heard about the harmfulness in long sitting. In reality, long sitting is very harmful to the body and may cause lumbar spondylosis and cervical spondylosis. Sitting for long periods at a time hurts the kidney as well as the spleen. It injures the transportation function of the spleen and affects the digestion. The bladder meridian is also being compressed, the damage is substantial. One will also more easily catch prostatitis and varicocele.

Furthermore, the Yang energy is found in movement while the Ying energy is in stillness. Long sitting belongs to the Ying. The place that we as living people inhabit is called the Yang room. Long sitting causes the Ying energy to proliferate in the body. It is mentioned in the classic TCM texts that long sitting discounts longevity. As the Ying energy grows, this will ultimately lead to the belonging of Ying which means moving towards the Ying room, to death. Therefore, we need to get moving. Every 40 minutes of sitting should be accompanied by 10 minutes of exercising. Don’t sit down for hours at a time, this is very harmful.

The harm from long sitting and staying up during the night are the kind of harm that slowly accumulate over time. We might not feel it all at once, but once the time is ripe the negative karma will take on an apparent form. Therefore, everyone must gain proper understanding with regards to the aforementioned issues, or else it will be very hurtful towards our recovery. Remember this at all costs!

Concluding words: the recovery status for those that love to exercise, do not stay up during the night nor sit for long periods at a time is quite optimistic. Merely rebooting is not enough, one must also adopt a healthy lifestyle. I hope to have brought about positive inspiration through this article. Keep on fighting everyone!
