# The issue of height growth, going bald, acne and reactions to rebooting

In this season we will talk about the four topics of height growth, baldness, acne, and reactions to rebooting. The first three questions are regarded with interest among brothers while the last question is a common one among brothers who have been rebooting for some time. Let us discuss them in detail below:

## Height growth

Many brothers would ask if masturbation would affect one’s growth in height. My answer is: masturbation indeed affects height. It will affect the development of the bones. TCM: “kidneys govern the bone”. Those that are born after the 90s would inquire on the issue of height, this is because these group of people is still growing. Those are born in the 80s would inquire less about this question due to that their bodies have basically already matured.

Many people would wonder about the question: since everyone masturbates, why is it that some people still grow to become tall? Actually, this is an easy question to answers because of the number of factors that affects growth, masturbation being among one of them. Although many people masturbate frequently, they have managed to avoid the other factors that would negatively affect their growth. For these people the effect of masturbation on growth is not very obvious.

Let’s take myself as an example, both my parents are not tall, my mother and dad being 160 cm and 170 cm tall respectively, but my height is 186cm despite that I frequently masturbated during puberty. Although my genetic conditions were not favorable, I did well in other areas so I was still able to reach a height of 186 cm.

Though I managed to grow to 186cm, I can clearly feel that my bone density is not up to par and having a bit of osteoporosis. I would easily spring my ankle or break my bones during exercise. After studying TCM, I came to understand insufficient kidney qi will lead to osteoporosis. Once injured, full recovery is not easily made.

According to my understanding, after a period of careful cultivation, although not apparent on the outside, many people would measure themselves to weigh heavier on the scale. Where does this extra weight come from? It actually comes from bone density. Previously the bones were porous but through cultivation bone density increases and so weight increases. On the outside, there are no visible changes.

I have summarized the following factors that would affect the growth of height:

Genetics
Exercise
Staying up and long sitting
Nutrition
Sleep quality
Digestion function
Masturbation
Psychological reasons
The factors that influence height growth would typically be found in the above eight factors. A lot of articles only mentions 5 factors, some places genetics as the main driver while others put the emphasis on genetics at 30%. I lean more towards the 30% argument because I’m a living example of it. Although I have masturbated frequently during puberty, I did well in other areas. I scored low on the 1st and 7th factor, in other words on genetics and masturbation, but I did well in the other 6 areas.

During puberty, I often played basketball outside and under the sun. More exposure to sunshine does help with growth because sunshine helps with the synthesis of vitamin D which favors the accumulation and settlement of calcium within the bones. This allows the bones to grow quickly and the body to rapidly gain in length. Frequent exercise is very beneficial for the development of bones which helps the bones to grow.

I have never stayed up nor sat for long periods of time. I loved to move around and seldom sat for hours at a time. Normally, I would sleep at 9 pm with a high quality of sleep. My digestion function was strong which enabled me to eat and sleep well. Many people are able to eat but their digestion cannot keep up, the nutrients would not be absorbed. This is why the digestion function is very important.

In addition, psychological health is also very important. TCM states: “Seven emotional states causes illness. Emotions will cause sickness and disorder of internal secretions”. This will also affect height growth. For those of you that are born in the 90s and want to grow taller, it’s advised to put efforts into the aforementioned 8 factors. Naturally, one should cut out masturbation as this will further benefit height growth. By cutting out masturbation, bone density will be high.

## Going bald

Brothers with a PMO history of over 10 years tend to run into the problem of going bald. Those that were born in the 80s have a higher chance of running into this issue. Many factors lead to hair loss, the common reason is due to kidney deficiency induced by masturbation. Going bald causes much anxiety among people because hair is important to one’s physical appearance. The impression that baldness gives out is that of premature aging and the lack of spirit.

Many brothers would lose 100 strands of hair or more each day. Looking at the hair in the comb and in the basin gives one the feeling of panic, the panic towards going bald is disconcerting and leads one to become abnormally sensitive towards hair loss, the loss of a strand of hair would cause nervousness for hours. Living in a state of constant worry and panic causes additional hair loss. According to TCM: “Fear hurts the kidneys. The splendor of the hair lies in the kidneys.”

Therefore, it is easy to fall into the vicious circle, one looks everywhere for an antidote. But no matter what the medicine is, the effect will not be satisfactory. Thus, the psychological pressure becomes greater and one cares a great deal about the opinions of other people. One may also be afraid to look into the mirror for fear of seeing diminished hair count, even the thought of suicide would crop up. The issue of going bald places a person in a predicament that the person is incapable of escaping from. Many people would channel this frustration into acts of masturbation which would cause even more hair loss. In the end, one may end up with a “Mediterranean” style bald spot.

The hairline of many brothers have already begun to recede upwards. Some people would begin to go bald from the crown of the head which is what happened to me. Some days, I would lose several hundred strands of hair. After having combed my hair, I would see all those hair on my shoulders, that is too scary! This went on for several months and the scalp at the crown of head started to become more visible.

Fortunately at the time, I already recognized the true face of the harmlessness theories in masturbation. Moreover, I had gained a relatively deep understanding about TCM. Consequently, I rebooted with haste, exercised regularly, slept early and slowly accumulated the kidney qi. Roughly half a year later I would lose around 5 strands of hair daily. If I comb my hair nowadays, I would not see any hairs on the comb and very few hairs on the pillow.

I wouldn’t dare to masturbate anymore because I have realized the bitterness of its harm. Many brothers are still in the ignorance stage. Ignorant people are not fearful, they have not fully comprehended the evil fruit brought forth by masturbation. Some brothers are even still mesmerized by the harmlessness theories. After losing hair, they still don’t know the real reason and continues to masturbate, channeling the psychological pressure into the act of masturbation. In doing so, one sinks ever deeper into the trap of the vicious circle which makes hair loss even more difficult to recover from.

Because there are blind spots and misconceptions in the understanding, no matter what medicine we take, we will not be able to solve the problem from its root. If kidney qi is not cultivated into abundance then the issue of losing hair will not find a solution.

This is analogous with a pot of plant. When the leaves have withered, we think there’s a problem with the leaves and we thus remove them. But after a while, all leaves would wither away and the plant dies. An expert would spot the problem right away and would dig out the soil and apply for medicine onto the roots which enable the plant to live on.

The hair follows the same principle, we must recognize the reason from its roots and not become mesmerized by outer appearances, relying on some overpromoted products in hopes to treat hair loss is not a realistic approach. Even if you have hair transplanted, as long as the kidney qi is not abundant the hair would still fall out unless you repeatedly undergo the same procedure which would be far too expensive for the average person.

The following factors lead to hair loss:

Genetics (parents)
Too high androgen production (male baldness)
Staying up and long sitting (hurts the essences and kidneys)
Overindulgence (kidney deficiency induced hair loss)
Dietary habits (too much salt in the diet will induce hair loss)
Psychological reasons (pressure-induced hair loss)
Illness (many illnesses cause hair loss)
Hygienic reasons (dandruff blocks off the hair pores)
Seasonal hair loss (hair loss is more common during the summer season)
Nutritious reasons (severe malnutrition induced hair loss)
Physicochemical hair loss (hair loss under stimulant conditions)

## Acne

Many people think that acne would naturally vanish after puberty, actually, this view is incorrect. I have seen many 30 and 40-year-olds still with acne on their faces. In these cases, we are no longer dealing with acne but a disorder in the internal secretions. Normal acne would heal very quickly given the conditions of being well rested and a light diet. However, the stubborn cases of acne brought upon by masturbation are difficult to heal from. This acne is very stubborn, the only hope of recovery is through cutting out masturbation, proactive exercise and through the accumulation of kidney qi.

Otherwise, the disorder in the five internal organs may last indefinitely and accompany us throughout life. The result being a destroyed appearance, degraded spirit, feelings of self-inferiority, a face full of acne like an abomination, truly appalling. The contrast in skin texture compared to pre-puberty times is night and day. When one masturbates, the face becomes oily. In the hospital, they say it is acne seborrheic dermatitis and prescribes medicine which gives mixed results. As long as we continue to masturbate, medicine will have limited effect and only works in the short run, unable to solve the problem from its root.

The majority of brothers have become uglier. This is the result of damaged kidney qi induced by masturbation. Lost kidney qi makes it more likely for the functions of the five internal organs to become disorderly. When the five internal organs are thrown off balance this is reflected in the face because the face is a reflection of the organs. We feel dispirited and decadent which only aggravates our chances of getting acne.

In short, in order to completely cure the stubborn kind of acne, one must cut out masturbation and cultivate a good habit in working, resting, eating and active exercising. Only through these means is there the hope of restoring healthy skin. Otherwise, all discussions are pointless.

Additionally, although some people may not have stubborn acne, their complexion resembles that of a ghost, without sunshine and completely dull. There may even be a hollowness look to their faces as if a layer of skin wrapped around a skeleton. Their complexion lacks any form of liveliness and vitality and reminds one of premature aging. An overindulgent young person resembles neither man nor ghost, like that of a deflated ball. Such a person is like an opium addict from the old society that is addicted to smoking and sex. How can such a body be good?

Therefore, to cut out the addiction is the best way going forward. Fail to cut it out will only harm the person himself. Some people may have a strong body and so the karmic consequences may appear late. But as long as one indulgence in debauchery, sooner or later the results will show, nobody can escape from it.

By not maintaining the body, issues will easily arise. The human body is like a machine that requires maintenance, without maintenance it will depreciate rapidly. Like a new bike that manages to retain 90% of its value one year after purchase if properly maintained. If maintenance is neglected there will only be 50% value remaining if not already useless. This is the importance of maintenance awareness. By neglecting maintenance there will not be longevity.

## The reactions towards rebooting

Lastly, let’s talk about the reactions towards rebooting.

I have studied many forms of addictions, which includes drinking, smoking, drugs, internet, sex, shopping, ..etc. In every case of addiction, there will be withdrawal symptoms when we try to quit. The symptoms may vary in severity from person to person. Masturbation induced sexual addiction will also have its withdrawal symptoms. The majority of brothers will encounter symptoms when they are undergoing a reboot. However, during the period when they masturbate there will be no such symptoms present. From the messages that I have received, the majority of the symptoms are found in issues with the urinary system, with prostatitis being the main culprit. This is followed by sleeping difficulties, irritated mood and so on.

The reactions from cutting out an addiction can be understood in the TCM point of view, which is similar to when the body is shedding itself from a disease. Much traditional Chinese medicine once ingested, will lead to the reaction of shedding illnesses. When the reactions are severe this is, in fact, a good sign, battle between good and evil is taking place. As long as we continue to take the medicine, vital energy will win the upper hand and the illness will slowly heal.

Many people do not understand these reactions. When the reactions are severe, they think that they have taken the wrong medicine and stops taking it. This is, in fact, delaying the healing process. The ancients said: For the sake of the younger generation, one has to understand medicine. Because if you understand it, you are in a better position to cooperate with the physician.

The mechanism to withdrawal symptoms according to Western medicine: due to long time masturbation, a sudden stop brings about an adaptive rebounding reaction. For instance, when alcohol addiction is cut, the following symptoms may appear excitement, insomnia or even epilepsy syndromes. Smokers quitting cold turkey may also experience restlessness, insomnia, increase in appetite, coughing up black/greyish phlegm, increase in blood pressure and arrhythmia reactions. Lots of pain will result from the mentioned reactions, but the frequency of the symptoms will slowly decrease following the recovery of the constitution.

Normally, after cutting out masturbation, withdrawal symptoms will appear within a month. For some, it might only take several days. When symptoms appear do not be frightened. By actively exercising and maintaining a healthy lifestyle, the symptoms will automatically disappear.

