# The issue of tinnitus, rebooting mentality, the importance of searching for study materials

## Tinnitus

Tinnitus is a common problem among brothers. Naturally, there are many factors that may cause tinnitus. But normally, the kind of tinnitus that many brothers encounter arises out of kidney deficiency, due to overindulgence in debauchery, poor lifestyle habits, frequent staying up late, long sittings. All of the mentioned factors make it easier for the appearance of tinnitus.

TCM: “kidneys enlightens the ears”. When kidneys are weak, tinnitus will come knocking on the door. Many brothers are deeply troubled by tinnitus, their condition would not heal in the long term and so they put their hopes in medicines. As everyone knows by now, cutting out the addiction of masturbation is the basic prerequisite. How can you expect to get better if you continue to masturbate and engage in sexual fantasies?

I was once a victim of tinnitus. Of course, I was relatively ignorant at the time. Afterwards, as I learned to cultivate my health and having actively exercised for half a year, my kidney qi became abundant and my tinnitus vanished without needing to take any medicines! The best supplement is to not leak.

In addition, nocturnal emissions do count as leakages and it will have adverse impacts on the body. If your kidney qi is in the abundance, an occasional emission will not be felt. However, if your kidney qi has sustained damage, further leakages will make things worse. Among the question that I have answered, numerous brothers are troubled by the issue of nocturnal emissions. Their bodies get worse by the day through frequent emissions. TCM touches on the point: long-term emissions injures the eight extra meridians. (Translator’s note: a detailed explanation of the eight extra meridians is beyond the scope of this article, for those that are interested may consult Google using the terminology).

Therefore, to recover from tinnitus, one should reduce the number of nocturnal emissions. I hope that everyone continues to perform the Eight Brocade kidney strengthening exercise from Season 3. Many brothers have reported excellent benefits from the exercise and have managed to greatly reduce the number of emissions. Of course, the precondition is that one has found the correct feeling when doing the exercise, as well as putting a stop to other factors that contribute towards nocturnal emissions.

The sound that one typically hears from kidney deficiency induced tinnitus sounds like the cicadas, a whistling or a hissing sound. The sound that I heard is the cicadas as if I had one living in my ears. The sound was sharp, drawn out and it was very irritating. Sometimes, it would make it difficult for me to sleep. I had this trouble since high school but it was not serious at the time. It becomes more serious after I started to stay up during the nights and sat for long periods at a time. Normally, when kidney deficiency induced tinnitus first makes its appearance it is accompanied by other symptoms. The 6 most commonly occurring symptoms can be found below:

Brainpower aspect: decreased memory, lack of focus, lack of energy, low efficiency in working.

Emotional aspect: poor emotions that are hard to control, dizziness, easily angered, irritability, anxiety, depression and so on.

Willpower aspect: lack of self-confidence, lack of passion in work, lack of passion in life, lack of goal and direction.

Sexual function aspect: lack of sexual appetite, impotence or softness, nocturnal emissions, semen leakage, premature ejaculation, decreased sperm count and less lively sperm activity, infertility.

Urinary function aspect: frequent urination, delay in urination, frequent urination in combination with greater volume, white dripping, prostatitis, varicocele.

Other aspects: premature aging, forgetfulness, insomnia, poor appetite, bone and joint pains, waist and knee soreness, easily fatigued, fatigue, a decrease in eyesight, hair loss, premature greying, loosening of teeth.

Masturbation causes the weakening of the kidneys. When kidneys weaken many physical and psychological symptoms will appear. This is because masturbation destroys the body and the mind. Tinnitus is but one of the symptoms of weakened kidneys. To completely heal tinnitus, one must completely quit masturbation and sexual fantasization, actively exercise, regularize eating and resting habits and accumulate kidney qi. Abundant kidney qi wards off evil in all shapes and forms. Otherwise, all the medicine in the world is of no use, one might be fed up with taking all the medicine without curing tinnitus.

Many brothers report that after 2-3 month of rebooting there is still no visible improvements in their health. What I want to say is that cutting out masturbation alone is not enough. One must learn to cultivate the health, actively exercise. Only in this way will there be a quick recovery in the kidney qi.

Furthermore, many brothers have sustained heavy injuries to their essences, subsequently, the recovery will be gradual. My feeling is that the pace of recovery is like the speed of hair growth, it is very slow indeed. But if you do not cut your hair for half a year, you will notice your hair has become very long. 2-3 months is relatively short in comparison. Therefore, to recover from kidney deficiency one must make the mental preparation to engage in long-term battle and persist each and everyday. In addition, effort must also be placed in reducing the frequency of nocturnal emissions, because night emissions are very unfavorable to the recovery process.

## The regulation of the rebooting mentality

Let’s talk about the regulation of the rebooting mentality.

Because of masturbation, many brothers have developed psychological problems such as a pessimistic view towards life and to give up on themselves, both are common occurrences. Once I had also experienced these mental disturbances: the loss of hope, lack of motivation, lack of self-confidence, feeling inferior and even self-mutilation.

To encounter the aforementioned issues is very normal because masturbation destroys the body and the mind. When the body runs into issues, the mind will also face problems. If the body runs into issues, we regulate the body. If the mind encounters problems, we also need to learn to make timely adjustments.

Everybody should know that in this world there is always two side of ourselves, one side is the passive self and the other the active self. When the passive self-appears, we must make haste in adjusting the self into the active self. This is like when a clock is showing the wrong time, we must immediately correct it.

The ability to adjust the mental state can be categorized as EQ in Western psychology, or emotional intelligence. EQ is a rather new measure that psychologist has proposed that is the counterpart to IQ. Emotional intelligence mainly refers to our characteristics in the areas of mood, emotion, willpower, and how to handle setbacks. Overall, great differences in EQ is not significant between individuals but is more related to postnatal cultivation. In other words, EQ is a prenatal “acquisition”, through studying it we may increase our emotional intelligence.

A while back, the book “The Secret” which was recommended by the host of Tudou forums is a very good book with regards to how to increase EQ. In it the concept of the law of attraction deals with positive and proactive thinking, and by doing so increase the chance of success. If one always have pessimistic and dark thinking then it is the same as hypnotizing oneself and suggesting failure for oneself. In doing so, the chances for failure becomes greater. This is similar to going to battle with a low morale which would greatly increase the chances of defeat.

EQ includes 5 main areas:

To be aware of our own feelings, only through knowing ourselves are we able to take control of our lives.

Capable to properly manage our feelings, able to regulate ourselves.

Self-encouragement, which allows a person to walk away from the low ebbs in life and to begin anew.

Able to recognize other people’s emotion, this is the basis for a normal exchange and the realization of successful communication.

The management of personal relationships, leadership and management abilities.

All of the above abilities are obtainable through the effort of constant studying. I would recommend reading more books in this area as books are like the steps to which humanity may take in order to ascend upwards. Without studying, there will be no understanding. Without studying, rebooting there will be no success.

## The importance of collecting first-hand material

Lastly, let’s talk about the importance of collecting first-hand material.

First hand refers to the experience and symptoms of brothers. These material and cases are very very valuable. Many cases are very typical of their nature. Everybody would do well by establishing a folder and gather those typical cases within. This will help us to more thoroughly understand the harmfulness of masturbation.

Many brothers collect porn videos, of course, I’ve also done it where I have gathered a few dozens of them. The more we collect, the more opportunities we have to indulge ourselves. On the other hand, the more case material we collect, the more warnings we will receive. The warning to not indulge or else we will end up like the people in the cases. By indulging, we are harming ourselves. Everyday, when I log into the rebooting forums and run into good cases, I would collect them. I have reviewed countless cases and seen all kinds of symptoms, many of which I have personally experienced. The more cases we review the deeper will our understanding become.

Regardless the area of study, it is important to deepen the understanding. The first-hand material is matchless in its importance, whether masturbation is harmful does not require a debate. There was a sentence: “Live battle produces real understanding”. Whether or not there is harm and if a picture represents reality, one only need to look at what the brothers with ruined health have to say. From the mouth of these victims is the most real of the truths.

The theory on the harmlessness in moderation is utter nonsense. From all the case material that I have reviewed, there are very few people who are able to practice moderation. Most of the cases resemble “once you pop you can’t stop”. Just like the opening of Pandora’s box, once you open it there is no going back.

People that love to exercise and have healthy lifestyle habits experience mild symptoms. Those people that dislike exercise, stay up and sits for a long time have serious symptoms. One can say that as long as one has begun to indulge, there is no escape, all methods are rendered useless. Karma is not empty. Masturbation plants an evil cause, evil cause leads to evil fruit. Whatever is sown will determine what will be reaped. Whatever comes out from masturbation is an evil fruit.

No matter how healthy the body is, as the age increases, symptoms will become more apparent. Brothers that have suffered a collapse in health may see it as a blessing in disguise. How is that so? Because the symptoms are the best teacher. When symptoms emerge we know to quit PMO and we have recognized the reality. Otherwise, it will be more difficult to recover when one suffers a collapse in health at the age of 50. When the health collapses in the 20s, one may sooner recognize the seriousness of the harm. A young age allows for an easier recovery. If one suffers a great decline in health at the age of 50+, recovery will be very difficult.

I have talked with a brother that is 50 years old, his has regular lifestyle habits with no staying up nor long sittings. Every morning, he would jog and has kept up with this regime for decades. He also had a very strong and able body. There was one weakness however and it’s his failure to recognize the harm in sexual indulgence. Everyday, he would engage in sex 2 times which he kept on for several decades. According to him, after the age of 40, he clearly felt that his body was not what it used to be. He did not pay too much attention and continued to indulge. At the age of 50, many bodily symptoms suddenly emerged. Diagnosis revealed autonomic disorders and anxiety. Everyday was like living in hell with those symptoms, the suffering was immense.

This case clearly shows that as long as one indulges, sooner or later the body will face issues. Even if you have a healthy lifestyle, even if you love to exercise, symptoms will still show up. With the increase in age, the number of symptoms with only grow. Therefore, one must cut the evil habit of masturbation. Even after marriage one needs to understand the importance of essence preservation, moderate the sex life or the body may still face problems.

To learn from the mistakes of our predecessors, these cases serve as the best warning, reality, and tutors. I hope that everybody lives as mindful people, by transforming their old vile interests in collecting porn movies to collection case materials. Every case serves as a reminder and warning: do not masturbate, do not indulge, or you will end up like the people in the cases.

In addition, 75 party (Translator’s note: most likely an internet user by the name of “75 party”) is constantly spreading the theory of harmlessness. Because adolescents are lacking adequate discriminating power and are easily confused by harmlessness theories, unable to separate truth from falsehood, therefore, adolescents have even a greater need to look into the case material and learn from the mistakes of the predecessors. It is vital that they cleanse the harmlessness theories from their brains because those are toxic thoughts and must be cleared out.
