# A detailed discussion on masturbation induced ugliness, and recovery from neurasthenia, anxiety and social fear

## Masturbation induced ugliness {-}

If you have been hanging around in the rebooting forums for awhile, you will notice that the phenomenon of turning ugly due to masturbation is extremely common. Basically, everybody has turned uglier but the severity of the ugliness differs between individuals.

The following factors affect the process of turning ugly:

1. Prenatal constitution *(under good conditions, the degradation of appearance is mild)*
2. Exercise factor *(those who do not love to exercise will be more severely affected)*
3. Staying up and long sitting *(those without healthy life habits will be more severely affected)*
4. PMO addiction level *(those that are heavily addicted will be more severely affected)*
5. The absorption of nutrients *(inadequate nutrients, inability to absorb nutrients all lead to more severe ugliness)*
6. Other addictions *(for example internet addiction, smoking addiction or alcohol addiction all leads to more severe ugliness)*

Many people are unable to find the reason for why they have become uglier. Actually, if one masturbates, turning ugly is inevitable. Masturbation sheds the most valuable Spirit *(Translator’s note: Spirit is the fusion of the “three treasures” in TCM; these are jing - essence, qi - energy and shen - spirit)* from our bodies. Without Spirit, we are listless. Everybody is familiar with beauty pageants. In these pageants they first compare body features, secondly the Spirit *(Translator’s note: in this context, Spirit may be understood as the aura of the person)* and thirdly cultivation in speech. If a contestant has dark circles under their eyes, dull complexion and acne, will the judges pick this person as the winner? A person doesn’t have to look pretty, what’s more important is the Spirit.

Many people have a good constitution, love to exercise and live a life free from unhealthy habits, these people will not turn very ugly. But if you observe closely, you will still be able to spot problems. I had a friend who was very healthy but would masturbate regularly, although he did not turn ugly to a severe degree, you could spot a problem if you looked at his eyes; they were always sluggish and dull. TCM: *The essence and qi in the five viscera and six bowels are all registered in the eyes*. Essence resides in the kidneys which are where the most important qi is stored. After essence and qi have been expelled through masturbation, the eyes will easily dim and lack spirit.

After masturbation, the skin is prone to run into problems. Masturbation disrupts the internal secretions, the skin becomes very oily and outbreaks of acne are frequent. The acne will be of the stubborn form that will persist for years and even for over a decade, this is due to the habit of masturbation. Consulting the doctor and taking medicine cannot cure the problem of its root, this is because essence and qi are being leaked through the evil habit of masturbation. Skin pores also tend to enlarge. Skin texture will change from that smooth, clear and oil-free state to looking filthy, with the skin pores enlarged and disgusting looking.

The facial complexion will also become very poor, without a hint of sunshine and always tinted with darkness, as if unable to be washed clean. Actually, one cannot wash such a face clean, because the filth comes from within. One might temporarily remove the dirt from the outside but is left unable to do any cleaning on the inside. Masturbation injures the kidney qi and kidneys have an important function: filtering the blood. More commonly we may call it the *“washing of blood”*. People suffering from uremia have failed kidneys, they require blood dialysis. Each day, the kidneys will filter through all the blood in the body over a couple dozen times in order to keep the blood clean and fresh. When you are sleeping, the kidneys are still cleaning the blood for you. The evil habit of masturbation also has an impact on the kidneys abilities to cleanse the blood. If the cleaning is not thorough enough, the effect will be visible on the face as uncleanliness and dullness.

Many people disagree that they have turned uglier. Actually, the damage is already done. One can simply make a comparison with a photo that was taken several years in the past. The ugliness that is induced by masturbation does not come from a significant change in the facial features, instead, it is a subtle change in the Spirit.

Let me illustrate this with an example: suppose you go to the superstore to buy apples, you would typically pick your apples and go for lustrous and full apples while leaving alone dull and shrunken apples, because you know that the latter are not fresh and will not taste good. Similarly, after masturbation you are like that *“expired apple”*. Although your main features look more or less the same, one glance is enough to tell the difference. It is incomparable to that former spirited you. Naturally, when the Spirit has been depleted to a certain level, there will also be changes in the facial features. Many brothers report sunken eye sockets, more pronounced cheekbones, smaller eyes and similar conditions.

Modern makeup is truly magical. Makeup is able to transform an ugly lady into a beautiful lady. It truly is the 8th wonder of the world. Besides altering the contours of the eyes, lips and the eyebrows, makeup is even able to alter the shape of the face, it is very deceptive. Many women take on a whole new appearance after applying makeup.

Besides altering the form, makeup has another very important function and that is *“brightness raising”*. What is brightness raising? It is actually *“supplementing blood”* and *“supplementing Spirit”*. Many women have sluggish Spirit and a poor complexion, after applying makeup, however, the Spirit is immediately uplifted. The dull and rough skin texture transformed into a smooth and bright texture like that of a newborn child. But upon removing the makeup, the woman is restored to her former state. Therefore, we sometimes hear the story about women after marriage sleeping with their makeup on, for fear of their husbands seeing their true face.

The best makeup for men is actually through rebooting and exercising, cultivating the health, not staying up nor sitting for long durations. In 3 months time, the Spirit will have recovered considerably. The effect of which far surpasses the application of powders on the face, this is the real Spirit and not some phony makeup.

I have already talked about the issue of balding in a previous chapter. Balding has a very big impact on the physical appearance of a person. When balding appears a person will appear to be old. The recovery from balding is a relatively slow process. Furthermore, there are serious misconceptions in the understanding among brothers, this will make recovery even more difficult.

Girls, in general, are not fond of bald men unless they are rich. In such cases, it’s uncertain whether the female likes the man or his money, the question merits investigation. Also, after one is together with a woman, recovering from balding is a far-fetched dream. Sex life is a constant process of exhausting the kidney essence. Without kidney essence, the hair will not return to its former lush state. Of course, besides balding, the issue of greying is also a troublesome one. Lots of grey hair will also affect a person’s self-esteem.

All in all, ugliness is a sure byproduct of masturbation. As we age, this tendency of becoming ugly will become ever more apparent. Therefore, it’s important to avoid masturbation as much as possible, actively exercise, have timely daily schedules, learn to cultivate the health and accumulate the kidney qi. The cultivation of health and beauty is interconnected. Always remember that beauty is not only a product of outer efforts, it is a projection from the inside. TCM: *Face is a mirror to the five internal organs*. Different areas on the face have their corresponding internal organs.

In this season, I will share 2 charts on TCM facial mapping, everybody may take a look. In TCM there are specialized areas of facial and color diagnosis. TCM: *“Through gazing the illness can be known, through listening the illness can be separated, through asking the cause can be determined, through feeling the organ can be traced.”* The truly brilliant TCM physician may understand the state of your five internal organs by just looking at your face. The physician from the story of “Bian Que sees Cai Huan” is such a story. By looking at the face, the latent illnesses are made known.

## Case studies

Below I have gathered real cases pertaining to masturbation induced ugliness. Due to the vast number of cases I have selected 10 of them for your reference:

**Case 1**: Yes, masturbation induced ugliness is something I have deeply experienced. Physical appearance is not the most important thing to a man but it’s the Spirit of the man. I have average looks at best but I didn’t masturbate during my middle school years and so I looked very vital, my clear face had a brilliance to it and I never thought myself to be ugly. Since the third grade of middle school, I started to masturbate all the way through high school and until today, I have in fact become ugly gradually. My facial complexion is dull, my demeanor is wretched. I feel a bit more handsome after a period of rebooting only to return to ugliness when I break the reboot.

**Case 2**: Started to masturbate since middle school and have done it for 4-5 years up until today. I masturbate almost everyday, it is very harmful indeed! I had a very healthy body before. At home, during the winter, I would walk around without wearing sleeves. Now my hands and feet are always ice cold, soaking in hot water helps very little.

During middle school, I was already 180 cm tall. Now I’m a senior in high school but still haven’t gained much in height. I didn’t use to have acne but these years, I’ve had a lot of acne. Long-term masturbation will turn one ugly. Many people have commented that my appearance has changed. Back in high school, there were a couple of girls that were interested in me. Nobody is interested in me today. Masturbation also causes one to lose confidence and makes one lean towards darkness. After prolonged masturbation, eyesight will decrease, the brain will become sluggish, ears will be unable to clearly hear sounds. It’s not the fault of the ears but the weakness of the kidneys.

**Case 3**: I’m an 18-year-old 2nd-grade high school student and started to masturbate since the 1st grade of middle school for 4 years. I have the following symptoms: low energy level, sleepy during class, poor concentration, feeling of IQ slipping lower, black eye circles, dull eyes, dully yellow and rough skin, feeling of turning ugly *(I was very handsome before)*, rhinitis, lack of willpower in normal activities, easily angered, hesitant *(previously I was outgoing, clever and filled with sunshine)*. Now I’m absent-minded, perform activities with hesitation. May I please ask all people who are my senior, can I still recover my old “self”? Please give me some advice, thanks.

**Case 4**: I’m only 18 and already I have masturbated for over 2 years. Previously, I did it once every day and even 3-4 in a day. Not only am I less healthy now but my appearance has also changed, there is no doubt that masturbation leads to ugliness! In the past, everyone commented on how adorable I was. Now my head is big but my body is small and I look like I haven’t slept. My skin has turned yellow, memory has decreased and I have an ever increasing sense of self-inferiority.

**Case 5**: I have turned ugly because of masturbation, also I have developed psychological barriers, resentment!!! Instead of experiencing a bright lifestyle I have self-degenerate sadness. I vow to change!

**Case 6**: Somebody once asked in the forums if masturbation would cause one to turn ugly? Regarding this question I have intentionally made a comparison, I took the photos of myself from when I was 15, 16 and compared to my recent photos, it’s as if looking at two different people! One is handsome, innocent and beautiful, the other with a swollen, lifeless face. Compare for yourself if you don’t believe me *(don’t look in the mirror, it is most obvious in the photos)*. From the evaluation of other people, the best description is that I have *“grown handicapped”*.

**Case 7**: When I was young I was considered handsome. But since middle school, I have always masturbated, now I’m turning uglier by the day! Those that were less handsome but didn’t masturbate have become ever more handsome, I’m depressed!

**Case 8**: I really have lots of acne on my face nowadays, also I have a lot of grey hair. The first is from before I started to masturbate, the second is from after. There is no doubt I have turned uglier! *(Translator’s note: it is possible that I’m lacking photos in this PDF version of the author’s book. “The first” should be referring to the first photo that I assume is attached to another version of the book)*. It is all too late now! I regret being ignorant, I long to return to the past and become a new person. Now I’m a murky juvenile, masturbation has destroyed my life. The promising old self with a bright future has turned out like this.

**Case 9**: I have masturbated for 10 years, already a walking zombie and haven’t accomplished anything. All this is a consequence of masturbation. I have never had a girlfriend and no girls like me. I’m cowardly without a backbone, not manly, this is also caused by masturbation!

**Case 10**: Since opening my previous thread, it has been more than 90 days. Although I haven’t completely cut out masturbation during this time, I did manage to greatly reduce the frequency which I consider to be a small success. However, my body continues to decay. The previous handsome self-continues to become uglier. Every time I think about it, it breaks my heart. Once again, I open a thread with the vow to stay clean for 100 days. I have no way back and need to persist at all cost. I believe that my body will slowly recover, my appearance will slowly become solemn, my studies and career will bear fruit, I will find a girlfriend. I also welcome all brothers to join me in this struggle.

## 23 forms of ugliness {-}

The 23 forms of ugliness that are linked to masturbation:

1. Acne
2. Balding and grey hair
3. Decadent and full complexion
4. Black eye circles
5. Sunken eye sockets, raised cheekbones
6. Spiritless eyes, messy eyebrow
7. Disorderly teeth, easily loosened
8. Yellowing and frizzing of hair, oily skin
9. Large skin pores, poor complexion, loose skin
10. Lots of wrinkles, thickening of lips
11. Wretched expression, eyes becoming smaller
12. Hunched back, asymmetrical body
13. Change in facial shape (swollen or skinny look)
14. Change in eyelids (double eyelids turning into single eyelids or multiple eyelids)
15. Turbid eyeballs, the appearance of blood vessels
16. Greyish tint to facial color (a ghostly look)
17. Apparently aged look
18. Thin and small bones (issues in development)
19. An evil glint in the eyes, unsteady in the gaze
20. Depression in the solar plexus and in the Adam’s apple
21. Specks on the face, moles
22. Dirty look on the face (very difficult to clean)
23. Marked decline in the aura of the person

## Neurasthenia, anxiety, autonomic disorders and social fear {-}

Let’s discuss neurasthenia, anxiety, autonomic disorders and social fear.

These 4 illnesses are similar to one another, only the emphasis differs. What they have in common is the number of bodily symptoms that repeatedly bother you, this makes living hell on earth. Those that haven’t experienced the symptoms will have a hard time imagining the feelings. This is like describing an elephant to somebody who has never seen an elephant, no matter how thoroughly it is described, it is useless. Having deeply experienced the symptoms as a patient and as a recovered patient, I would like to share my recovery experiences and research with everyone.

Regarding anxiety and autonomic disorders, I have studied these for over 2 years. At the time, I was suffering from severe social fear and didn’t set my foot outside the house. Everyday, I would chat in over a dozen QQ circles *(Translator’s note: QQ is basically the equivalent of the old MSN Messenger)* simultaneously. I have chatted with over a thousand fellow patients, the majority of them being men, over 1000 of them in total. Women were in a minority with them totaling at around 100. Without a single exception, all of the causes are listed below:

- Male patients: staying up, long sittings, sexual indulgence
- Female patients: anger, high stress, long sittings. (Also included is family misfortunes such as the passing of relatives)

After a period of indulgence, the men would suddenly fall ill. There is usually a trigger, a stimulant, the fundamental reason is due to a weakened body. The women would fall ill after getting angry, once angry their autonomic nervous systems would become disordered. Female patients go through special physiological cycles to start with. Their qi and blood are prone to deterioration and if angered on top of it, problems may easily arise.

For the male patients, if they wish to recover they must learn to cultivate the health, preferably by cutting out PMO completely, or else recovery will be difficult. For the female patients, emphasis needs to be on the cultivation of the mind. TCM states that the 7 emotions bring about illness, negative emotions have the potential to induce illnesses. Therefore, it is important to properly manage one’s emotions, refrain from becoming angry and learn to peacefully deal with people and matters.

Normally, those afflicted with the mentioned illnesses lean towards two areas:

- Hypochondria
- Hostility

Incredibly many brothers fall under the orientation of hypochondria. Many have spent over ten thousand yuan in medical diagnosis, in some cases over a hundred thousand yuan. After a round of checkups nothing would be found. However, the symptoms are very serious and cause one to fall apart and to panic. Under these conditions, even through repeated checkups, one wish to go through every medical equipment in the hospital multiple times, one is still not content. This is because the symptoms are very obvious. But why is it that no illness can be traced? This kind of doubt will surface. Actually, this is still a misconception in the understanding. Neurasthenia, anxiety, autonomic disorders are all basic issues in functionality. A medical screening will not be able to detect anything, any amount of diagnosis is of no use.

The orientation towards hostility is even more common. When chatting among brothers, one would often see quarrels. The reason being that kidney water is insufficient which enlarges the liver fire. One will become angry without a reason. One is prone to bickering and making a fuss out of things. Many people after having calmed down feel regret. In reality, anger injures the self more than it injures others. Anger injures the liver. Therefore, I recommend the affected patients to learn to cultivate the mind, control the emotions and manage one’s emotions. This will benefit the recovery process.

In addition, many people in these chat circles will talk about symptoms but not the causes. This is very sad. If one does not adequately understand the causes then recovery will be very difficult. Having recognized the causes one need to go the opposite way which will enable healing to take place. Many brothers only talk about symptoms. Talking about symptoms helps to alleviate the nervous emotions but it does not tangibly contribute towards recovery. To recover, one must learn about the cause!

In the past 2 days, I have just chatted with a fellow patient suffering from neurasthenia. Nowadays, I do very few neurasthenia consultations, my main focus is on the rebooting forums consultations. That patient happened to add me and we started chatting. During the time, he was studying for the graduate exam, he would stay up late and combine it with masturbation. It was like wearing a tightening hat. His sleep was greatly affected as there was constant insomnia. However, this patient did not realize the cause and still wanted to talk about the symptoms with me. Afterwards, I told him about the cause and that’s when he had a sudden realization. If one doesn’t understand the cause and doesn’t change life habits and cut out masturbation, recovery is really very very difficult.

Many people have been stuck in the vicious circle for over a decade. During this time, they would rely on daily medication to maintain themselves. This is very hard to imagine, at one time, I had taken medication for half a year on a daily basis and had developed a dependency on the medicines. It was too scary of an experience  to relive when I took medicines as if having a bowl of rice. Without medicine, I would feel unwell. In fact, I didn’t feel much better after taking the medicine. That was the state of my mental makeup which resembled a vicious circle.

Afterwards, I completely lost faith in all medicines and stopped taking them. Upon quitting PMO, I actively exercised and learned the way of cultivating health. I recovered 50% after half a year and after a year all symptoms disappeared. Up until now, I have completely recovered, both mind and heart have returned to a normal state. To recover, the understanding must be correct. Having a blind spot or a misconception in understanding will make recovery many magnitudes harder.

Actually, neurasthenia, anxiety, autonomic disorders, and social fear can be considered as one and the same illness; issues with the nerves. The expression is more or less the same. In TCM they would call it the weakening shedding of the body or the stasis of blood and qi.

Normally the symptoms ar expressed as:

- Head symptoms, including insomnia
- Heart symptoms, serious illness with the function of the heart
- Intestine and lungs symptom, the disorderly function of the lungs and intestines
- Skin symptoms, includes rashes, muscle ticks, stabbing pain, crawling ant feeling, etc
- Full body symptoms, nowhere is comfortable

## Premarital sex {-}

Lastly, I would like to supplement the topic of the hardness of premarital sex. When replying to questions these days, I stumbled upon a few brothers. Because they had sexually indulged themselves before marriage, their health had already suffered a collapse with the onset of impotence and premature ejaculation. Their families would urge them to get married which would create considerable psychological issues for them. These kind of brothers are *“weakened before marriage”*. That is, unmarried with a failing body, kidney qi heavily depleted.

By entering marriage with this type of body condition, how can the quality of a normal sex life be guaranteed? Many brothers have developed problems with their reproductive functions, infertility has emerged, besides the issue of impotence, the whole body is affected by symptoms and is a total mess. During the state of *“excessive desire following depletion”* *(Translator’s note: by this is meant the aroused state of desire which arises as we are rebooting, this is the result of recovering kidney qi, depletion is the weakening of the kidney qi following PMO)* one might not be alerted. Following this state is the onset of impotence and premature ejaculation. Many brothers during this *“excessive desire following depletion”* stage masturbate everyday, sometimes multiple times a day and think their bodies are very strong and able.

Actually, this is an expression of a weakened body and mind, Lao Tzu said: *“To know eternity means enlightenment. Not knowing eternity is to do evil things blindly.”* Eternity here means patterns. Many brothers do not understand this principle and indulge madly, and the result? Not long afterward the body collapses, weakened before marriage if married or meeting a girl, the result is “weakening upon the weakened”, more serious illnesses might show up in the future.

Therefore, one must put an end to premarital sexual behaviors, or else the consequences will be very grave. Look into the cases where brothers have run into issues and draw lessons from them and take preventive measures, this is a smart move!
