# The adjustment of mentality after relapse, non-liquidation of semen, and the penis length issue

## The adjustment of mentality after relapse {-}

Everyday in the rebooting forums, we can see brothers that have relapsed. The posts that they make following a relapse are always marked with great remorse. Some brothers call a relapse a *“battlefield casualty”*, I think this is a very good description. Rebooting is like waging a battle, we are all brothers in the same trench. We are saddened by the sight of another brother becoming a casualty. This should, of course, spur us into rebooting and to maintain our vigilance. The enemy camp is constantly shelling us with pink shells. The rebooting articles are our bulletproof armor. We must increase our efforts in studying rebooting articles and in doing so increase our awareness and the level of our determination.

If you should let down your guard, the next battlefield casualty might be you. When we see inappropriate pictures or videos we must immediately dodge them. We must exercise the same caution to porn as we do towards tigers and incoming arrows. We must be equipped with this kind of awareness. To reboot for good, the awareness must be strong which is obtained through studies. Awareness and vigilance give us the hope to successfully reboot.

For those brothers that have relapsed, there is no need to be discouraged. Nobody can manage to reboot in one try and there will be many failures before success. Before I successfully rebooted, I had also failed many times, so many times that I have lost count. I was unable to get out of the vicious circle for well over a decade. Because at the time, I was in a state of ignorance with nobody to guide me and nobody to tell me what to do. Afterwards, having taken up rebooting studies, my determination increased. Roughly after a year of studying rebooting articles and health cultivation, my awareness increased by leaps and bounds. Through it, I gained deeper thinking and understanding. It is under these circumstances that I successfully rebooted.

### Errors during reboot {-}

There are 2 types of errors that are easy to make during reboot:

- Rebooting without studying about rebooting
- Rebooting without cultivating the health

#### Rebooting without studying {-}

Rebooting without studying is the same as brute force and blindly rebooting which both guarantee failure. This is because the level of determination has not been raised. After the hibernation period for desire is over, we arrive at the peak period for relapse. Once there the urge to relapse is irresistible which is often followed by multiple relapses, all previous efforts have been washed away. I have mentioned the importance of rebooting studies countless times in the previous articles. If you don’t study you won’t be in the knowing, your awareness will not increase and expand.

Once you have reached a certain stage in your studies, your determination will rise. With the determination, you are able to defeat the temptation demon, or else every encounter with the temptation demon will result in defeat. It is hard to avoid starting off from a low level when we first begin our reboot. Suppose that the temptation demon is at level 100 but your determination is only at level 15, how do you resist the temptation? Only through studying about reboot can we raise the level of our determination. Once the level has been raised, the temptation demon can no longer budge us. To relapse is not scary. The scary thing is to not study because the result from that is continuous relapses and our inability to escape from the vicious circle.

#### Rebooting without cultivating the health {-}

Rebooting without cultivating the health is also commonly seen among brothers. Awareness about health cultivation is precisely what many brothers lack. The awareness is also obtained through studying about rebooting. Studying video lectures given by famous gurus and reading health cultivation literature is very helpful towards the recovery of the body. Many people reboot but neglect in maintaining a healthy lifestyle. They still stay up late, sit for long durations and smoke. They do not emphasize the management of emotions, for these people the prospect for recovery is not optimistic.

Other brothers while rebooting, exercise actively, live a healthy lifestyle and do not stay up nor engage in long sittings, this is the quick route towards recovery. Indulgence is to cut down the health, rebooting is to maintain the health. However, rebooting is only the first step towards cultivating the health. Rebooting alone is not enough, it is far from enough. This is because there is more than one way to injure the kidney qi; staying up, long sittings, anger, cold beverages, exposure to AC and etc all hurts the kidney qi.

TCM specifically talks about the 5 strains and 7 impairments.

**5 strains**:

- prolonged gazing strains the blood
- prolonged lying strains the qi
- prolonged sitting strains the muscles
- prolonged standing strains the bones
- prolonged moving strains the tendons

**7 impairments**:

- overeating impairs the spleen
- anger impairs the liver
- intensive weightlifting, long-term sitting, and moisture impairs the kidneys
- cold beverages impair the lungs
- worrying and overthinking impairs the heart
- wind, rain cold and heat impairs the appearance
- fear injures the mind

The 5 strains and 7 impairments should be avoided. Health cultivation is a deep discipline and the effort is made little by little, one must take care of all aspects. Once your awareness in health cultivation has been increased, this will be very beneficial for a better recovery of the body. Because you will know what to do and what not to do, all actions that hurt the kidney qi will be avoided at all costs.

### Types of relapse {-}

The different types of relapse are:

1. Courage increases with each failure, the will to fight is still strong
2. Self-esteem takes a blow, motivation is decreased
3. The thought to flee comes up, becomes a deserter

Brothers following a relapse should properly repent. But don’t be too hard on yourself, don’t take on too much pressure, everything may begin anew. Although you have relapsed, it’s still possible to pick up and read rebooting articles. As long as we persist in our effort to study, we will finally come to that one day where the determination is sufficient, the habit of PMO is naturally shrugged off. This is like climbing a mountain. As long as we persist, we will reach the top, many people due to fatigue will quit halfway. Those that really carry the courage and determination will persist into the end, they will never quit rebooting.

Through my research, many brothers give up because they are not sufficiently aware of recurring symptoms *(Translator’s note: recurring symptoms are the symptoms that we had experienced before rebooting)* following quitting PMO. Once an addiction is laid aside there will always be symptoms, this especially applies to PMO. By persisting in rebooting, taking care of one’s schedules, actively exercising, recurring symptoms will disappear.

Although many people have rebooted for 6 months to a year, there could still be recurring symptoms. When they do appear, this is very normal and there is no need to worry. Even healthy people will have times when they are not feeling well. This is related to external factors and is also related to the changing of the seasons. The level of yang energy in the body is different in every season. It’s also easy to experience recurring symptoms following nocturnal emissions. This why it’s important to try to decrease their frequency.

In addition, those that have wives or girlfriends will waiver more easily. This is because having a woman is an obstacle towards rebooting. With a woman, bodily symptoms will have difficulty in recovering. There is also a group of brothers whose understanding towards the bad fruit of masturbation is not yet deep enough, they still subscribe to the moderation theory. These people will throw in the towel more easily.

## Non-liquidation of semen {-}

Below let’s talk about the issue of the non-liquidation of semen.

This issue appears relatively often and is also relatively common. The ejaculated substance resembles jello or some kind of crystallized substance. When spotted it will give many brothers a scare and cause them to panic. Actually, this non-liquidation phenomenon of semen is very common. Everyday in the rebooting forums, similar questions are raised. The main illness that causes the non-liquidation of semen is prostatitis. This will affect the fertility function and the quality of the sperm. Upon medical examinations, many brothers encounter weak sperm, dead sperm, deformed sperm or even no sperm.

According to TCM, the non-liquidation of semen is mainly induced by the following illnesses:

1. Insufficient prenatal kidney yang energy, or a loss of postnatal kidney yang energy, severe and prolonged illness, damaged kidney yang energy

2. External pathogenic cold and damaged kidney yang energy both causes the semen to congeal

3. Overindulgence in alcohol and sex, overuse of the mind, the fire manifestation of the five emotions

4. Regular spicy diet, sweet, greasy, alcohol, the inner accumulation and heat and moist, exogenous dampness

5. Excessive intake of cold beverages injures the yang energy of the spleen, or the injuring of yang energy of the spleen by other illnesses, weakened spleen reaches to the kidneys

6. Weakened qi and blood stasis or the constitution of blood stasis, blockage in the essence chamber causes the the semen to congeal

The type that is normally encountered is number 3: sexual overindulgence. Overindulgence will easily lead to these type of issues. Once we have begun to masturbate, it is nearly impossible to stop. Seldom is there a person that is able to practice moderation. This *“moderation”* is also unknown to most people *(Translator’s note: unknown not as unheard of but as not knowing how much is too much)*.

So one must completely cut out the evil habit of masturbation, or else it will be exceedingly difficult to heal the body, fertility functions will all become affected. During my time in the rebooting forums, I have come across countless cases of masturbation induced infertility. Only through quitting masturbation, cultivating the health and the kidney qi will there be hope to recover sperm quality. Otherwise, we are totally wasted, what can be done about it!?

## Penis length issue {-}

Below let’s talk about the issue of penis length, this is a sensitive topic. Men are very conscious of penis length, the common perception is that the bigger the better. Men with big penises feel self-pride, those with small penises feel inferior. I use to think like this. After I came to a certain understanding, I no longer think this way. There are mysterious principles behind the length of the penis and it is not as simple as one would imagine. If the understanding has not arrived, few people will be able to understand this principle and its inner workings. Today I will discuss this topic.

The penis has an orientation towards the liver because the liver governs the muscles. Many brothers report a smaller penis after they have started to masturbate and a lack of self-confidence. In reality, masturbation does affect the development of the penis, because the liver and kidney share the same source and masturbation hurts both organs. The penis is oriented towards the liver and it, therefore, affects the length of the penis. Though there are other factors such as genetics that plays a role in the length of the penis. If you have good genes then the effect of masturbation will not be great. If you have poor genes and you combine it with the evil habit of masturbation, then the chance to encounter a smaller penis will be relatively high.

12 cm is normally an adequate length of the penis, 10 cm will also do. There is no need to have an oversized penis. An oversized penis will incur evil more easily. It is mentioned in the book “Liu Zhuang Shen Xiang”: “the owner of a big penis is lowly, he provokes viciousness and thus must be lowly”. *(Translator’s note: the reader should also take the cultural aspect into consideration as the average length of penises differ between countries)*.

This is in contradiction to everyone’s perceptions that bigger is better, bigger is cooler, bigger is strong and good. This is, in fact, a relatively shallow understanding. Why is it that an oversized penis is not good? Why is it that the man with a large penis is lowly? This touches upon TCM. Without understanding the medical principles, misunderstandings will be propagated, one may enter the grave without knowing the principles.

I once compared masturbation to shopping, I would spend kidney qi in exchange for fleeting moments of vile pleasure. Normally, the man with the big penis will have a relatively strong *“purchasing power”*, his sexual desire will be relatively strong. On the surface, this might appear to be a good thing, but misfortune is disguised in blessing. The more vile pleasure that is purchased, the more kidney qi is spent. In this way, the probability of a collapse in health is greater. Although the person may look strong today, due to overindulgence, he will meet his fate; the chance of premature ejaculation, impotence, and various bodily symptoms.

Therefore the saying goes, desire should not be strong, the stronger the desire the more the damage. He with a big penis incurs evil, this evil points to the evil in sexual indulgence. The first chapter [Ancient Innocence Theory] of the TCM classic [Inner Canon of the Yellow Emperor] specifically mentions about the harm of sexual indulgence. Famous doctors from the past have had over a thousand years of experience to draw upon, they deeply understood the danger of sexual debauchery. I have seen many medical cases both written in the past and in the present, there are too many cases of collapsed health as a result of sexual indulgence, as many as there are strands of hair on a cow.

If you thoroughly understood the danger of sexual debauchery, then comparing that to the danger from severe flood and wild beasts would not be an exaggeration. When your kidney qi is in abundance, you will not feel very much. But when your kidney qi has been depleted to a certain level, the evil fruits will become ever more apparent. And with an increase in age, illnesses of different forms will come knocking on the door. Abundant kidney qi wards off evil, depleted kidney qi is the source of a multitude of illnesses!

How is it that *“he with the large penis lords over the lowly”*? Because in TCM: *to the above, kidneys are connected to the brain*. Masturbation hurts the kidneys and so it must also injure the brain. Concentration, memory, and willpower will all deteriorate in different degrees. When a person is deficient in the brain then success will be hard to come by in all areas of life. Being lord of the lowly is then inevitable. Those that are really successful are often strictly self-disciplined. Those that lack discipline may enjoy success for a while but the success will not be long-lived. *(Translator’s note: the translation of this chapter was not without discomfort. My apologies if you were offended by the contents.)*

Those that have acquired the Tao will in no circumstances think that a strong sexual desire is a good thing. In TCM: *excessive desire follows depletion*. When this is allowed to develop, we have premature ejaculation and impotence and all forms of sicknesses, this is then called “the mighty dragon in shame” *(Translator’s note: the mighty dragon is the excessive desire)*. The one that has received the Tao will absolutely not think that a big penis is a good thing. In the contrary, he will think that it’s a bad thing, as to why that is, I believe the reader will have understood after reading this article.
