# Adding to the issue of balding, how to recover faster and better during rebooting

I have mentioned the issue of balding in chapter 8. This is indeed quite a thorny issue. The speed of recovery is relatively slow. From some websites related to balding, we are able to see that although some brothers have been rebooting for 8 months, their balding has not been improved. Not only that but the symptoms are showing signs of getting worse. Seeing such cases, those brothers that are suffering from balding will invariably take a hit in their self-confidence and think that it’s all hopeless, or that hair recovery will not be possible through rebooting and all recovery talk a lie. To this, I can say with 100% certainty that one can recover from balding. However, if your balding is very severe then the difficulty in the recovery will be relatively high.

There are mysterious principles behind recovery from balding. Many people think that rebooting is sufficient but it is not so!

Those that have truly recovered from balding are relatively few, but not non-existent. Although many people have not been able to recover completely, they have nevertheless seen substantial improvements. You see the recovery progress of some people is not up to your expectations, therefore, you feel that there is no way to recover and your confidence will waiver. As to why some people are not able to recover despite having rebooted for 8 months, reasons can be found.

To recover from balding through mere rebooting is far from enough. It is important to learn the way of cultivating a good health. There is more than one way to injure the kidney qi. Many people are rebooting but what I want to ask is, is your reboot thorough enough? Do you still fantasize? Fantasizing is the invisible way of depleting the kidney qi and is extremely unfavorable for the recovery process. In addition, do you stay up late, sit for long periods at a time or tend to get angry? These three factors also greatly damage the essence. Also, living under high pressure, taking cold beverages and exposure to AC all damage the kidney qi and impede the recovery of the hair.

If we compare the human body to a bottle filled with kidney qi, masturbation is only one hole in this bottle. Rebooting only blocks one of the holes while the kidney qi continues to leak through the other holes, how do we expect to recover from balding? If the adequate amount of health cultivating awareness is lacking, then recovery from balding will be very difficult. Many people are obsessed with medicines, this is why the hair growth industry is booming. But the efficacy of these products if very limited. After all, they only target the symptoms and not the cause, the root cause being a weakened kidney qi.

Suppose that in order to restore hair, a kidney qi value of 5000 is required. I only used this number as an example in order to facilitate everyone’s’ understanding.

“-” signifies a minus sign

- Masturbation (-600)
- Long sitting (-300)
- Staying up (-300)
- Anger (-300)
- Cold beverages (-100)
- Exposure to AC (-100)
- Fatigue (-100)
- Long gazing (-200)
- Sexual fantasizing (-500)
- Internet addiction (-300)
- Smoking addiction (-300)
- Alcohol addiction (-300)
- Overstraining (-200)
- Nocturnal emission (-500)
- High pressure (-300)
- Salty diet (-200)

These are the 16 points we can look at. Many people are currently refraining from masturbation, but the error is that of *“rebooting without cultivation”* with ignorance towards cultivation. Some brother only reboot and place all hope in rebooting and medicines. In this fashion, the recovery from balding is truly quite difficult due to the number of ways to leak the kidney qi. One mishap and kidney qi is leaked.

Staying up does not mean staying up the entire night. Being awake after 11 pm counts as staying up and is very damaging to the essence. Despite this, many people still go to bed past 11 pm. This is very unfavorable to the recovery of the body. The work and rest schedule must be adjusted or else recovery from balding is difficult to achieve. Long sitting can be remedied by moving about for 10 min following every 40 min of sitting. Avoid sitting for hours in one stretch. As everyone is able to see, the recovery from balding requires the fulfillment of many harsh criteria. It can, therefore, be said that only a few people are truly able to recover from balding but this number is not zero.

Knowing the ways that can damage the kidney qi, we need to learn to how to adjust and to avoid these ways. In addition, we need to learn to the way of cultivating the health. Health cultivation is a learning and can not be explained by one or two sentences. Friends that are suffering from balding tend to pay close attention to what they eat, what products to use, but very few people ask the question of how to cultivate the health, this is because they lack the awareness of health cultivation.

Therefore, to recover one must learn the way of health cultivation, such as Eight Brocade exercises, standing exercises, acupressure massage, moxibustion, meridian exercises, Chinese herbal medicine, meditation, aerobic exercises, etc.., watching video lectures by famous gurus and health cultivation articles. Study more health cultivation know-how, with a deep understanding and awareness of health cultivation you will know what to do and what not to do. In this way, one can reduce the exhaustion of kidney qi to a minimum.

Persist for one year and the chances of recovering from balding will be very high. Otherwise, if you only reboot but lose kidney qi through all the other methods, how can you expect to recover!? Hair recovery is a gradual process, one must have patience and confidence. Otherwise, if there are misconceptions about the understanding and the position is not solid, recovery will be very difficult.

One thing should be mentioned here and that is management of the mood. TCM states that fright injures the kidneys. Many people are faced with losing hair, they are stricken with fear and anxiety, food and sleep no longer have any appeal to them. This kind of mood is detrimental to the recovery of the hair. One must learn to adjust the mood, not to worry excessively, to not take things so seriously sometimes, calm down a bit, this mood will benefit the recovery process.

In the above, I have listed the examples that are damaging to the kidney qi, in their respective negative kidney qi values. After you have mastered the way of cultivating the health, we then have positive kidney qi values. When the kidney qi value has reached 5000 the hair will be recovered, this process cannot be hastened. I have spent half a year in trying to control the trend of my balding. Only after a year did my hair start to become dense again. At the time my mood was very good. Moreover, I rebooted quite thoroughly, without much sexual fantasization.

I also put in a lot of effort in reducing the number of nocturnal emissions. Everyday before bed I did the kidney strengthening exercises and managed to limit the number of nocturnal emissions to once every month or so. At most I went through 3 months without a single nocturnal emission. Frequent emissions are also very bad for the recovery of the hair. Rebooting for 8 months without experiencing hair recovery is also related to nocturnal emissions. After all, kidney qi is leaked through emissions, so one should take care to reduce its frequency.

**My health cultivation practices**

Some brothers have asked me about my health cultivation practices. In this chapter, I have laid them out as a way of sharing with everybody:

- Meditation *(I meditate for 1h each day, meditation is the no.1 way to supplement the original essence)*

- Standing exercise *(standing exercise is not performed daily, sitting meditation is performed daily)*

- Eight Brocade exercise and the Six Healing Sounds *(I perform the kidney strengthening exercises of the Eight Brocade daily and occasionally practice the Six Healing Sounds)*

- Soaking of feet in Chinese traditional herbs *(once/week, mugwort leafs)*

- Meridian tapping exercise *(performed regularly)*

- Moxibustion on meridians *(health cultivating moxibustion is performed regularly)*

- Aerobic exercises *(slow jog and ball sports, 1-3 times/week)*

- Acupressure massage *(performed regularly)*

- Yam, black beans and red dates *(eat regularly)*

- Keeping a light diet

- Rest early, sleep before 11 pm

These are basically the things that I do to cultivate my health. I try to avoid activities that would lead to a leakage of kidney qi in order to minimize its exhaustion. It’s the above mentioned 16 activities that I try to avoid, while the health cultivation practices are used to add points to the kidney qi. In this way, there is a chance to recover the hair.

For the recovery of the hair, the 3 below criteria must be fulfilled:

1. Thoroughly rebooting *(sexual fantasization must also cease)*

2. Health cultivation practices *(these will add points to the kidney qi)*

3. Health cultivation awareness *(try to avoid activities that draws points from the kidney qi)*

The above 3 points must be fulfilled in order to recover hair. This goes especially for those that are experiencing a medium level of balding. Those that are experiencing a high level of balding must take extra care to cultivate the health, recovery will otherwise be extremely difficult.

Speaking from my own experience, I have seen brothers that have managed to recover from balding, but they are relatively few in number. One reason as to why the number is so low is the long rebooting time it takes to recover, 1 year in the minimum. People that have managed to thoroughly reboot for 1 year are very few. On top of this, those that are able to control the number of nocturnal emissions are even fewer.

The second reason is the lack of effort in health cultivation. Many people only reboot without cultivating health, which makes recovery even harder. Why has my hair recovered? Because I have put in tremendous effort into health cultivation. I have studied TCM literature nonstop and so came to understand more and deeper than the average person, knowing what to do and not to do and accumulating kidney qi as I went along, preserve the kidney qi as much as possible, and so my hair has recovered. If you don’t study you will never be in the knowing. This is why I emphasize the importance of studying.

My recommendations for literature and videos in health cultivation are listed below:
*(Translator’s note: Obviously the literature is geared towards a Chinese audience. On the other hand, there are lots of English material that the author may not have had access to, we should study whatever is available to us)*

- Qu Limin’s book and videos
- Wu Guozhong’s book and videos
- Zhong Li Ba Ren’s book and videos
- Dan Guimin’s [Jiu Chu Bai Bing]
- The [Yang Sheng Tang] show, many famous gurus in this show

Health cultivation is a discipline that has a knowledge spillover effect. Once you have understood a book or a video of one person, you will have an easier time understanding the material from another person. It is possible to become quite specialized once one has stepped through the door.

Everyone has seen and understood by now that the recovery methods that I have mentioned do not only apply to balding. Any problems that we encounter as a result of masturbation, any symptoms which include psychological issues, must be treated from two perspectives in order for recovery to take place. **The first is to reboot, the second is to learn how to cultivate the health**. By doing this, the body will be able to recover relatively quickly. Otherwise, we might end up with the case where many people barely notice any improvements after half a year of rebooting and/or unsatisfactory results after 1 year of rebooting. This is because there are too many channels of leakages; knowing one but not the other, knowing rebooting but not of cultivation.

I’m very fond of a sentence in the [Inner Canons of the Yellow Emperor]: *“Knowledge leads to strength, ignorance leads to aging”*. You knowing this mysterious principle will become strong, others know not and continue to leak. But since you know you are able to avoid it, therefore, you become strong, others are shedding their kidney qi value in ignorance and yet are oblivious to the fact. The result is that your body and hair have recovered but the other person has a hard time recovering because he is not in the knowing!

I believe that those brothers who are troubled by balding will gain a deeper and clearer understanding towards recovery from balding after reading this article. I am not against the usage of hair products, but one must pay attention to rebooting and health cultivation or the hair will have no chance to truly recover.
