# The harm of premarital sexual behavior

Long-term reboot forum brothers sure know that many people have already exhausted themselves before being married. This is due to the deep addiction of the evil habit of masturbation. After having masturbated furiously over a decade alone, the body is already severely overdrafted like an overextended credit card. Chronic prostatitis and varicocele are both commonly seen. Some brothers have even contracted neurosis and live a painful day-to-day life. Others are suffering from a very low sperm quality, if not weak sperm then the lack of sperm where fertility has been lost.

Premarital indulgence also induces the decline in sexual function. Many brothers are very attentive on the level of their own sexual function. When they have discovered the onset of premature ejaculation and impotence owing to the evil habit of masturbation, they feel worried and hope for a quick recovery. The inadequate function of sex and fertility constitute the hidden danger in marriage inharmonies. Previously, there are a couple brothers who have had divorces due to these issues.

Premarital sexual behavior belongs to the category of nefarious wantonness, which in itself is an evil conduct that injures the body. It is particularly harmful. Many people put their bodies into an eggshell precarious state before they even get married. Sex during the marriage will be adding upon the injury.

Countries have gold reserves, the body has kidney essence reserves, don’t fool around before marriage. The kidneys roots itself in the five internal organs. Sexual debauchery depletes the essences of the five internal organs. When the kidneys are weak, diseases of every kind are born! In the beginning, the physical constitution is still strong, depletions are not felt. But through the depletion accumulated through days and months, one inevitably ends up with a symptom-ridden body. During our reboot, we must have clarity in what is nefarious wantonness behavior. By having a concrete definition can we better avoid it.

## Nefarious wantonness

Nefarious wantonness definition:

Examples include wrong time, wrong place, wrong woman, virgin woman, his woman, belonging to self.
Wrong time: dates and time that falls outside the no-sex time window rules for the reboot.
Wrong place: points to the rules of sex free places of the “3 channels” (oral, urinal, anal)
Wrong woman: any sex that is not of the female sex, different sexual signs including livestock
Virgin woman: unmarried women (premarital sexual behavior)
His woman: women with a husband
Belonging to self: self-sexual act such as masturbation, sexual fantasizing all fall into the category of nefarious wantonness
Besides lawful sex between husband and wife, all sexual behavior between the man and woman that is not recognized by the laws or the moral views of the society, these are all nefarious wantonness.
Even between spouses, there are limits:

Wrong time nefarious wantonness: Buddha’s memorial date, the six-day fast of the Buddhist tradition, birthdays of the parents, the passing day of close relatives (father, mother, sisters and brothers, etc..), menstruation period, pregnancy period, shortly before and after giving birth
Wrong place nefarious wantonness: no sex outside of the bedroom, besides the sexual genitals, no sexual acts (example include the mouth, butt, other parts of the body)
Wrong amount nefarious wantonness: indulgence after marriage without limitations
There are many specific categories of nefarious wantonness. For example extramarital affairs, premarital sexual behavior, living together as unmarried, masturbation, grinding against bed and between legs, telling sexual jokes, addicted to sexual fantasization, looking at pornographic videos and images, homosexuality, incest, having mistress, one-night-stand, selling and buying sex, sexual fetishes, producing and spreading of pornographic material, introducing nefarious wantonness to other people or spreading of such material, etc..

“There are three things of which the superior man stands in awe. He stands in awe of the ordinances of Heaven. He stands in awe of great men. He stands in awe of the words of sages.”

— Confucius

Saintly teachings have taught us what is nefarious wantonness, what is accepted wantonness, what to do and what not to do. All of these have been laid out in a clear way to us. For the man of honor, he will surely fear the words of the holy man. This is because saintly words are the truths that are borne out from extensive experiences and will never fade with time. If one disobeys the principles that are taught by the saintly person, then one will surely taste the evil fruit of karma. The saying goes that by not listening to the elderly, the damage is just ahead.

Being able to receive the instructions of the saintly is a great blessing. How many people in today’s society are lacking in such a blessing? Often they find themselves in violation of moral conduct in both the body and the mind while being oblivious to the fact, thinking that this is all normal. In reality, their thinking are complete upside down and in total opposition to the saintly teachings. Under the natural law, virtue is blessed, wantonness is a calamity, the retribution is not kind in the slightest. Those who commit nefarious wantonness will, in the end, receive painful retribution.

Those that are able to cut out nefarious wantonness are men of virtue and thus should obey the way of morality. If one is able to stay clear of nefarious wantonness in this day and age, then one is able to safeguard one’s bodily and mental health from the very root, as well as safeguarding the calm order and harmony of the family.

## Premarital sexual behavior

Premarital sexual behavior has long since been a common occurrence in today’s society, many young people are already doing it. Recall in the 70s and the 80s of the previous century, premarital sexual behavior was still regarded to be taboo. In the 90s, pornographic films went on a rampage. Adding to it, the poison that is being taught by the harmful teachings of the sexologists, the atmosphere in the society steadily deteriorated. Arriving at today, the premarital sexual behavior is already very common. Moreover, the youth of today do not feel any shame towards premarital sex, thinking that it’s very normal. Some people even regard the lack of premarital sex as something that’s shameful, these are truly different times.

When it comes to sex, the youth of today’s society have completely been misleading. They have been brainwashed by the nefarious wantonness culture. They are no longer shamed by it and instead claims it to be honorable, in the process bragging about their history of nefarious wantonness while looking up to the celebrities who exhibit such behavior. One night stand is regarded as fashionable! This is truly an ignorant and sad generation.

One can also say that this generation has been corrupted by the nefarious wantonness culture. A generation of degenerates, lacking in virtue and positive energy. Young people of today, just go out and observe, there are very few who still carry the imposing righteousness look in their eyes. Many youths carry an empty look in their eyes, a face belonging to someone that has been depleted of the essence. Many youths carry the look of vile tendencies with a degenerative quality. One cannot tarry to give them a second look.

Premarital sexual behavior is actually not a kind of responsible behavior. Many people begin their relationship in a state of disorder and end up in abandon. When feelings fade the relationship is ended, all of it is just a fleeting play. The goal from the very start has been to have some fun and not with marriage as the goal.

Premarital sexual behavior will induce serious consequences in many fronts. It will bring misfortune for the individual, the family and the society, the consequences are long in their duration, the retribution from nefarious wantonness will sooner or later become apparent. In the majority of cultures and countries, the premarital sexual behavior is not approved by public opinion, religious beliefs, moral ethics and the court of law. Avoiding premarital sexual behavior is not only required by the law and the code of mortality. It is needed for the future establishment of a stable family and a blissful marriage.

## The harm of premarital sexual behavior

The harm of premarital sexual behavior towards life takes 6 main forms:

### Depleting oneself before getting married

Depleting oneself before getting married, body with a myriad of symptoms, cannot bear to put into words. As the age increases the family will urge one to get married, but unfortunately one’s health is not up to par, sexual function is lacking with even infertility, therefore one is placed in an awkward situation.

In the rebooting forums, many brothers are currently in the mentioned situation; family urges one to get married but the body is occupied with a variety of symptoms. In addition, there is the early emergence of premature ejaculation and impotence, the quality of the sperm is very poor, this is a difficult situation indeed. The previous frenzy in masturbation has led to the depletion of the body. Now that one is to face marriage one suddenly discovers that one is inadequate, this is indeed a very miserable life.

Furthermore, the inadequate sexual function and the poor quality of the sperm is kept hidden from the spouse, or else one might get looked down upon or face a possible divorce because the other party thinks one is a disposed of person! There is no hope and future with a disposed of person whatsoever, better to let the wife file a divorce and marry somebody else. Previously there was a brother who underwent divorce due to the poor quality of his sperm, there was no way to get the woman pregnant, the end result was a divorce, that brother is very hurt and regrettable.

Many brothers are still students. Due to the addiction to the evil habit of masturbation, they soon find their mental faculties in a steep decline. After the steep decline, topics, where they have previous understood, are no longer comprehensible, the results are foreseeable, grades drop by a thousand leagues. When the brain power is no longer capable, life as a whole becomes very dull. When the brain power is present, the mind is nimble in every undertaking. When the brain power has been ejaculated, everything one does lack power, the brain always feels like a pile of paste, the reaction is very sluggish and slow.

For some brothers, following the diagnosis of neurasthenia, the brain feels dizzy the whole day. The feeling of reality is absent as if one is living inside a dream, one has indeed transformed into the walking dead. Brain power is the battle strength, the kidney is connected to the brain, the battle between men lies in the kidneys! When the kidneys are deficient illnesses in all shapes and forms arises. No matter if one is a student or a worker, one should cherish the sexual energy. Premarital sexual behavior should be avoided at all cost. One should apply the previous sexual energy on proper endeavors and transmute the sexual energy into strong support and motivation for one’s academic or working career.

### Facilitate the breaking of a relationship

Premarital sexual behavior will facilitate the breaking of a relationship. Many younger people lack any concept for responsibility, they seek the novelty of love. Once premarital sex has occurred, they naturally grow tired with each other in time. Arguments cannot be avoided, many relationships have ended following arguments. Love without a sense of responsibility is like a fast meal, it is discarded after the meal. The thought of tying up a man by using sex is not realistic because men easily grow bored. In a mutually loving relationship, responsibility must serve as the foundation, feelings are second to that. Otherwise when feelings are absent then breaking up is inevitable.

Nowadays the values regarding love in many youths are problematic, responsibility is completely neglected, due to its absence relationships are formed disorderly and end up in abandonment. The feeling of love is very unreliable. There is also an expiration date for love, past the date it is inevitable to enter into the period of weariness. Just like when you grow weary of a cell phone. In the beginning one is very fond of a certain cell phone. When time as elapsed, all feelings have disappeared. Actually love is similar to this.

Therefore, stable marriages should rest on the foundation of responsibility, after that comes the mutual feeling of affection. Responsibility leads to stability and longevity and is the prerequisite for mutual exchanges. Without this prerequisite, the end result is often not too blissful. Many people are lost in the feelings and are constantly in the pursuit of feeling. In the end, they discover that feeling is such an illusory and intangible a thing. Once being so fond of the other person ended up with the frequent argument, to go so far as breaking up as a conclusion. The feeling will fade sooner or later, only with the addition of responsibility can feelings be kept alive.

### Affect the quality of the post-marriage life

The overuse of sex before marriage will affect the quality of the post-marriage life. When a person has depleted himself before marriage, what do you think the result will be? This is like a broken car, swaying left to right while heading towards marriage, not long afterward breaks down. Many people are deeply entrenched in predicaments, the whole life seems dull and decadent. After well over a decade of frenziedly consuming pornographic material combined with masturbation, the five viscera and six bowels have long since been depleted. One enters marriage and faces the married sex life in this critical stage, many peoples’ bodies throw in the towel, autonomic disorders are erupted and aggravated, or one suffers complete impotence or another form of chronic illness. When the physical and psychological health is down, marriage will be threatened from all sides. Previously there were a couple brothers who underwent divorce due to inadequate sexual functions. When your sexual function is depleted, the wife might cheat on you, great bitterness awaits.

### Increase the chances of unexpected pregnancies

Premarital sexual behavior will also increase the chances of unexpected pregnancies. Suppose that the woman has experienced multiple abortions, this increases the likelihood of puncturing the womb causing hemorrhage which is life-threatening. Abortion is very harmful to women and will likely cause physical and psychological damage:

Bacterial infection
Habitual abortion in the future
Unable to become pregnant
Surgical mishaps, life threatening
Waist pain, fragile body, catches chronic gynecological illnesses
Inharmonies within the family and in the career
Causing psychological damage such as guilt, regret, blaming, fidgety, depression and various psychological illnesses, even the thought of suicide
Sometimes one might even dream of wailing children or of being followed by unfamiliar children
Doctors use to warn: do not take abortions lightly or one will pay a heavy price such as hemorrhage, gynecological inflammation, infertility and even death. Following the procedure of artificial abortion, the monthly menstruation may be thrown out of balance, uterine cavity adhesions and endometriosis like consequences might negatively impact future pregnancies.

Even worse, artificial abortion might cause life-long infertility, especially for those who have had repeated abortions are more likely to suffer from such conditions. Due to repeated scraping of the inner membranes of the uterus, the uterus linings become thinner and the inner membranes ever fewer in quantity. This causes fewer menstruations or even the cessation of menstruation. Oocyte implantation due to inadequate quality of the “soil”, making the embryo enable to develop and hence life-long infertility. Scraping often causes inflammation in the reproductive organs, causing damage to the uterus and other internal organs or hemorrhage, even causing life-threatening danger.

Many brothers have allowed their girlfriends to undergo an abortion, some even under multiple times. Abortion is, in reality, a form of killing and incurs very negative karma for the future. Therefore, take measures in avoiding premarital sexual behavior, do plentiful repentance and avoid making similar mistakes in the future.

### Increase the likelihood of STD transmission

The likelihood of STD transmission is also increased via premarital sexual behavior. Some brothers not only engages in masturbation but also purchases sex, the contraction of various sexual diseases is then made possible. Some time ago a brother due to sexual debauchery has contracted genital warts. Having genital warts is indeed to endure various pains and unspeakable awkwardness. He spent lots of money in medical expenses but was unable to completely cure the disease. The possibility of relapse is always around the corner, this has caused him suicidal thoughts and the loss of hope towards life.

Some people have contracted gonorrhea, syphilis, even the contraction of HIV. Although some people have not contracted HIV they have contracted the fear of HIV, life for these people is exceedingly painful and torturous. It can be said that fear never ceases, life is merely being dragged on.

The phenomenon of hookup-cannon (a.k.a. One-night stand) has become popular in recent years. This kind of chaotic sexual behavior will inevitably shoot one off into the hospital, turn one into the ashes of nefarious wantonness and finally end up in hell. This is actually very frightening! The sexually disorderly generation has not the face to confront the ancestors, this kind of behavior puts one even lower than livestock! On the contrary many young people today carry this kind of behavior with pride, there is no limit to the stupidity! There is no limit to the degeneration! The HIV situation in China today is already showing an explosive trend. Those who fool around everywhere will contract HIV if they are not careful when that happens one is truly dumbstruck.

### Higher divorce rates

Premarital sexual behavior from the first appearance looks like personal freedom. The reality of the consequences are endless, according to research statistics: married couples that have had premarital sexual behavior, divorce rates for this group far exceeds that of the chaste couple. Those that had premarital sexual behavior have a far easier time to neglect responsibility. What they seek is more “feeling”, with feelings they will remain together, without feeling it is time to separate. However, the feeling of love will fade as time goes on. When that time comes, if responsibility fails to enter into the picture then quarrels and divorce will be inevitable. The foundation for marriage is a responsibility which is like the foundation for a skyscraper. Those who sexually indulge before marriage often lack the required responsibility. Many people are only in for the high in the short term. Even after entering marriage they will still abide by their old model of indulgence. Not only are they still addicted to masturbation but might even have extramarital affairs, visiting prostitutes and similar behavior, the final play of divorce awaits them.

### Related documents

[Life Times] magazine reported in 2006, November the 8th: The ever-increasing rampant cases of STD and the number of single parents are causing the American government headache. In order to guarantee the health and to improve the quality of its citizens, the government granted 50 million USD to the project of “self-restraint education” which promotes premarital self-restriction. The government required that young people wait until they have past 30 years of age before starting their sex lives. Recently, the American federal government notified the various states the approval of utilizing dedicated subsidy in order to encourage young people in their 20s, to life a self-restrained life before getting married.

In the recent 10 years, Americans which were originally seen as sexually liberated, have begun to promote “self-restraint education”, with the purpose of changing the concepts of the youth to slowly return to be more traditional. According to understanding, in recent years, the Ministry of Health and Welfare have allocated 5 million USD in federal education funds for the self-restraining educational project. This is the education project that has been awarded a prize.

The American self-restraint educational group NAEA mainly aids the stately federal government in the promotion of sexual education, answering questions related to sex from the youth, and then analyzing these questions using statistics and in doing so helping the youth to form a healthy view towards sex. At the moment, the self-restraint educational group mainly touches on 13 topics, statistical data have shown, within the American high schools today, at least 70% of the schools have addressed 8 of the 13 topics: self-restraint is the most effective means of preventing pregnancy (87%), withstanding peer pressure (83%), the risk of having multiple sexual partners (81%), students making sexual behavior decisions in order to affect others (80%), at least 3/5 of the high schools also talks about marriage and vows (69%), the safety of condoms (65%). In primary school, the most talked about the topic by teachers is the development of the human body.

The self-restraint educational group will also visit various American cities, and to provide curriculum based on the demand from the schools and on the age of the students. These curricula are largely short-term based, not exceeding 2 months in length. The requirement for the curriculum teachers is a postgraduate degree in psychology. The teachers would form groups and then go out to different schools in order to give lectures. Individual schools may also apply for their teachers to join the educational programme. In 2011, the teachers have undertaken a lesson in college called “human-based sexual behavior”. A questionnaire was then conducted on the entire class of 150 students (with roughly 50% being female), the finding was that 80% of the female students were virgins with the majority of them being born in the 90s. This number is significantly higher than the ones posted in the previous years. The teachers were very shocked by this, one teacher stated: this number increases every year, perhaps as a result of the self-restraining education.

### Afterword

“There are three things which the superior man guards against. In youth, when the physical powers are not yet settled, he guards against lust. When he is strong and the physical powers are full of vigor, he guards against quarrelsomeness. When he is old, and the animal powers are decayed, he guards against covetousness.”

— Confucius

Cutting out of all sexual thoughts and material is the first cultivation. It is also the first challenge for the youthful, this challenge must be passed.

“Lust is the common problem in the world. Not only the low and the middle class are obsessed by lust, even the upper class, if not vigilant in their guard, also easily become obsessed by lust. Try and see how many of the heroes from the ancient and modern times, firm-footed as the holy man, only because they cannot conquer lust, becomes fools and unworthy. He who treads the evil path, difficult it is to secure many victories.”

— Master Yin Guang

“There are ten kinds of karma related to the repeated evil indulgence. Why 10 kinds? First, a desirous heart burns vigorously. Two, the wife is not chaste. Three, poor for growth. Four, the elimination of a good way. Five, leisurely indulgence of both sexes. Six, the dispersion of assets. Seven, doubting heart. Eight, separation from virtuous friends. Nine, mistrust from relatives. Ten, life is ended with three strokes.”

— (The Distinction between Good and Evil Karma)

We must learn to control our desire and not become slaves to desire. We need to learn to transmute our sexual energies and apply it onto our careers, excessive masturbation must be avoided at all cost. Otherwise, our five viscera and six organs are depleted along with our brain power, such would be miserable. Let us say no to premarital sexual behavior and guard our last line in the sand. Let us be chaste and save it until after we are married, avoiding depleting ourselves before marriage.

