# Black eye rings and eye bags, grey hair, hemorrhoids and rhinitis issues in detail

## Foreword {-}

Lately, while browsing the rebooting forums, I’ve discovered an interesting phenomenon, that the understanding of many brothers has cleared risen, this is evident from answering their questions. In reality, as these brothers study, they *“grow in understanding”*. In the game Go, when the players skill increase it is called *“grow in qi”* *(Translator’s note: qi = game, not to be confused with the energy qi)*. In reboot, this can be called *“growth in understanding”*. When understanding has been raised then determination will also naturally increase. Through the constant study of rebooting articles and health cultivation, the level of awareness will clearly exceed that of a rebooting rookie. By ever persisting and increasing one’s understanding, remaining clean forever is not far away.

What we cultivate in rebooting is the level of our determination. When determination has risen then rebooting will be successful. The thing we need to be aware of is when we don’t study and when we let our guard down, else we will not be successful in our reboot.

The biggest issue that rookies have is the existence of misconceptions, all forms of doubts and hesitation must be overcome. Through raising questions doubts can be erased. By doing so we are able to solidify our belief. Otherwise, the unresolved questions will impede our rebooting progress. For example, when many people run into withdrawal symptoms, their first thought is the harmfulness of self-restraint, thinking that such restraint will give rise to problems. If we have not properly understood this issue then relapse will happen easily. There are many other misconceptions in thought and they must receive correction. To reboot one must recondition the thoughts, or else we cannot be successful in rebooting.

Below we will enter the main topic:

## Black eye rings and eye bags {-}

Black eye ring and eye bags are two problems that I have experienced. The eye bags started to appear when I was 19 years old while black eye rings had already shown up during middle school. Because I loved to exercise, the black eye rings were not that serious. According to my careful observation and experience, among those people who love to exercise, the issue of the black eye rings will occur relatively infrequently. Even when they should appear, by actively exercising and taking care to be well rested, the problem will subside very quickly.

But for those who do not love to exercise, stay up late and sit for long sessions, the black eye rings will be quite stubborn. The way of exercising that I recommend should ideally be done outdoors and under the sun. TCM believes, sunbathing will warm up the yang energy of the body, it is an indispensable component in health cultivation. Sunbathing allows the body to gain vitamin D and increase the resistance of the body and prevent all sorts of illnesses.

There is skill involved in sunbathing. It is appropriate to open up both palms *(Laogong acupuncture point)* towards the sun when it is rising during the morning, breathe deeply. In this way, we are able to nurture the heart and the lungs. The most precious time for sunbathing is when the sun is overhead during noon time, especially during winter noons. It’s appropriate to remove the hat and allow the sun qi to be absorbed by the crown of the head *(Baihui acupuncture point)*. In this way, the heart and the brain are nurtured. Afterwards, lower the head and allow the sunshine to be absorbed in the back of the neck *(Fengchi acupuncture point)*, Fengchi point is the source point in the body’s defense against external negative qi.

Of course, one needs to take care of the degree in sunbathing and to not overdo it. 1h per day is enough. Also don’t sit all day in front of the computer screen, this is very unfavorable to the recovery of the body. It’s good to increase contact with nature, increase sunbathing and exercise.

In TCM, black eye rings arise mostly due to deficient kidney qi, inadequacy in essence and qi, impeded arteries and veins and the loss of nutrients to the eyes. Therefore, to recovery from black eye rings, one needs to pay attention to health cultivation and active exercising. In this way, the black eye rings will recover relatively quickly.

I remember that I had masturbated quite frequently in the summer holiday following my national higher education entrance exam. When I looked at myself in the mirror after the holiday, I saw eye bags! Once eye bags start to appear, a person looks several years older. This gives out a decadent look which lacked vitality. Although I didn’t know much about health cultivation at the time, I knew that exercise would help my body to recover. Therefore, I would often go for a slow jog and run for 20 laps during each session at a very slow pace. After jogging for 20 days and then looking into the mirror, the eye bags disappeared, the quality of the skin improved a lot and improvement in complexion was apparent.

However, my determination was low at the time, I was still in the brute force and blind stage, so not long afterward, I started to masturbate again. When I looked in the mirror again, the eye bags had returned. And so I was quite troubled during those years and battled against eye bags for a long time, but I was still unable to solve the problem, this is because I was still masturbating.

Originally, I made the eye bags vanish due to great efforts made in exercising and resting well. But as soon as I let down my guard, eye bags would return and not only that, my facial complexion would become a lot worse, like expired fruit, the feeling of being all dried up and decaying. At the time, I had looked into eye bag removing surgical procedures. There are external cut and internal cut procedures. It also came to my understanding that the procedures will not help one to remove eye bags completely, there will be a chance of relapse. If you continue to masturbate, eye bags will return.

The emergence of eye bags is largely due to the lungs’ diminishing ability to dry up water, the inferior function of the lungs, the block of Chengqi and Sibai acupoints. TCM believes: *“kidney is the gate of the stomach”*. *(Translator’s note: in a healthy person, when we intake water it is passed onto the kidneys from the stomach, as if through a doorway. When the kidneys are sick, that doorway does not function properly, the result is swelling in various areas of the body)*. [Suwen] states: *“Kidney is the gate of the stomach, when the gate is malfunctioning, it induces the accumulation of water, swelling in the skin. Patient suffers from edema, due to the accumulation of water”*.

Kidneys are not only the gates of the stomach but also store the essences of the five viscera and the six bowels. Masturbation causes the weakening of the kidneys, once that happens, the whole body is prone to run into issues. The issue of eye bags is but one of the expressions from weakened kidneys. Although eye bags are located above the stomach meridian, located at the Chengqi acupoint, the root cause is still the kidneys. When the kidneys are weakened, the function of the internal organs becomes disorderly.

Now that I have completely cut off PMO and sexual fantasizing, the issue of eye bags is nowhere to be seen, although not completely eradicated, it is in level with a person in my age. With the onset of eye bags, the prerequisite for recovery is to abstain from masturbation and fantasizing completely, else recovery will be very difficult.

## Grey hair {-}

The issue of grey hair will be discussed below:

I have also been troubled by greying, although it was not a genetic condition. During my youth, I had masturbated frequently. Though I did manage to take good care of my rest and nutrition, there were grey hairs but not that many. Afterwards, I masturbated and also stayed up at night. My eating habits were irregular, sometimes having only one meal per day. Not long afterward, many grey hairs sprouted up. I had several strands of grey hair on every side of the head. In addition, a vast amount of hair was falling out, over 100 strands of hair daily. At the time, I almost capitulated. I knew that it was self-inflicted karma and I could not blame anybody else, I could only blame my own indulgence.

Factors which induce grey hair:

1. Psychological factors: stress, sad feelings, anxiety, fright, etc. will all cause premature greying. It is the belief of modern medicine that negative psychological factors will cause spasms in the blood vessels responsible for providing nutrients to the hair. This causes a decline in the function within the pigment cells around the hairballs and follicles, which in turn affects the formation and transportation of the melanin particles.

2. Experimental evidence on nutritional imbalance has shown that if black lab rats are denied folic acid, pantothenic acid and vitamins in their diet, their hair will turn into a greyish color. In addition, the color of the hair pigment particles is related to its metal content. The black hair pigment particles contain copper, cobalt and iron elements. If some of these elements are missing then the appearance of grey hair will become likely. Moreover, grey hair will also appear under the condition of lack of proteins and serious malnutrition.

3. Sufferers of chronic illnesses. Some people suffer from autonomic nervous disorders, hyperthyroidism, tuberculosis, typhoid fever, internal secretion obstacles, etc., the emergence of grey hair will also be present in these situations. This is because the illnesses have damaged or disrupted the follicles, the growth and maturation of the hairball color pigment cells, causing them to lose the ability to secrete black color pigments and hindering the formation of melanin particles.

4. Inheritable factor. Premature greying is also affected by prenatal factors to a certain degree, where premature greying has previously occurred with parents or in the family tree.

5. Evil life habits: staying up late, long sitting, sexual indulgence, all of these habits injure the kidney qi. TCM: *“The splendor of the hair is rooted in the kidneys.”* People with these evil habits will encounter grey hair with more ease.

My hair has now recovered, after rebooting for half a year, I can see that the root of the new hair is black. I’m very attentive about health cultivation, this has been a beneficial factor in my recovery. Many people reboot without cultivating the health, recovery will be relatively more difficult. I have also eaten black colored food but have not taken them intentionally, included is black sesame, black beans and black mushrooms, which I ate often. My rebooting process was very thorough, combined with health cultivation, this is the root cause of my recovery.

On the psychological level, I didn’t pressure myself too much, I managed my mood very well and didn’t have many negative emotions. No anger, no complaining, no jealousy, each day went by in a state of calmness. Many brothers will become agitated and easily angered, this is very normal because kidney qi is not abundant, the emotional expression of being easily irritated and angered will take place. And so it’s important to properly manage the mood, keeping one’s emotions stable. Negative emotions are like earthquakes and have very adverse impacts on the body and mind. The harm of which cannot be underestimated and is very negative for the recovery of the body.

I remember that my neighbor next door was a boy that was a couple years older than I, he had premature greying. It was not inherited, he ate well, but the family was not in harmony, the parents would often quarrel which caused him a large amount of pressure. To constantly live under the shadow of domestic violence is, in fact, a grey hair inducing psychological factor. When the family is not harmonious, psychological pressure will be huge.

The principle of recovering from greying is very simple but is hard to do, it is through doing things the opposite way! Put a stop to the greying inducing factors, thoroughly reboot, learn about health cultivation, through this the issue of greying will gradually recover. There is a process involved, you must increase and deepen your understanding of health cultivation in order to increase the chances of recovery. Otherwise, rebooting without health cultivation is far from enough. I have mentioned specific ways to cultivate the health in chapter 12, everybody can go and have a look.

## Hemorrhoids {-}

The problem of hemorrhoids will be discussed below:

Hemorrhoids are also a very common problem, as the saying goes, 9 out of 10 men will encounter hemorrhoids! There is another saying: out of 10 women 10 will have hemorrhoids. The chances for women to catch hemorrhoids is also very high. This is because women have special physiological periods and are more prone to suffer injuries in both blood and qi. Combined with long sitting, hemorrhoids will come knocking at the door.

I had my first hemorrhoids at around the age of 20, at the time I masturbated frequently. During a period of time I used to sit on a sagging sofa and after a while I would feel something below, that’s when I had caught hemorrhoids. The hospital determined the hemorrhoids to be internal. By applying the subscribed medicine the hemorrhoids would subside, but the root of the issue would remain. Hemorrhoids brought much trouble to my life, I was unable to eat cold or spicy food. So at the time, I took extra care when eating instant noodles. Spicy food would induce the return of the hemorrhoids, stools tended to contain traces of blood.

Afterwards, when I studied TCM I understood, masturbation would induce a deficiency in the qi. When your qi is abundant, there will be no issues when sitting on the sofa because qi pushes the blood around. Sitting on a sofa while having adequate qi will not cause stasis in the qi and blood. But once qi is deficient and you sit on a sofa, it will cause qi and blood stasis and hemorrhoids will easily emerge.

The anatomical cause of hemorrhoids: When a person is standing or sitting, the rectum is situated at the bottom. Due to heavy exertion and restriction in the internal organs, the backward flow of blood through the veins becomes blocked.

As of now, my hemorrhoids have completely healed, I did not expect it to go according to my plan. The recovery process for my hemorrhoids was very peculiar. At first, I thought that hemorrhoids will not heal without an operation. Of course, hemorrhoids might relapse following the operation. Because, from a medical perspective, hemorrhoids arise due to obstructions of blood reflux in the veins. Therefore, operations will only help to eliminate the hemorrhoids but cannot guarantee the recovery of the obstruction issue.

I remember 2 years ago, I started to soak my feet with traditional Chinese medicine. I used mugwort leaves purchased from Taobao. At the time, I read from Dan GuiMin’s blog on curing hemorrhoid from its root by using moxibustion. The method was to sit on a hollowed out chair, using moxibustion to smoke hemorrhoid from the below. After approximately a week, the hemorrhoid core would fall off and the hemorrhoid was cured.

Naturally, this process is a bit painful, not everybody is able to withstand it. After seeing it, I didn’t dare to try it, so I used mugworts to soak my feet. Unexpectedly, after 3 days of treatment, I felt that the hemorrhoid was turning outward and becoming bigger. That’s when I knew that the warming and activation of the meridian function of the mugwort leaves were working. It was very painful when the hemorrhoid was turning outwards and I could not sit down. Sitting down was painful, I could only sit at an angle.

At that time, I already started with moxibustion treatment. Of course, I didn’t dare to apply moxibustion directly on the hemorrhoids. I applied moxibustion on the Shenque acupoint, it is also the navel point. After soaking my feet for 3 days, the hemorrhoid turned outwards. On the 4th day, I applied moxibustion on my navel for 40 minutes, I felt that the hemorrhoid was about to break. I immediately pulled the anus inwards and the hemorrhoid indeed broke, the core fell out. After that incident my hemorrhoid has healed completely without further relapses.

Those brothers that are suffering from hemorrhoid may try my method. Naturally, there are many ways to treat hemorrhoids. I have only shared my own experience with everyone which I hope will be helpful.

## Rhinitis {-}

Lastly let’s talk about the issue of rhinitis:

I have a hypersensitive constitution and suffer from allergic rhinitis. When I sneeze, I sometimes sneeze a dozen times in a row. I remember that my nose was not very healthy ever since childhood. Although I didn’t masturbate at the time, due to inadequate prenatal conditions, I would easily catch a cold due to exogenous cold. And so I often caught a cold as a child and later I got asthma. However, the rhinitis I had back then was not that serious. When entering puberty, I masturbated frequently, rhinitis suddenly became more serious. Throughout the entire year, my nose would be stuffy, it was very painful. I tried many curing methods to no avail. Afterward, I underwent an operation to remove the inferior nasal conchae which did alleviate my symptoms a lot, but it was still not good enough. Whenever there was a change of season, I would run into issues.

At the time, I was in a state of ignorance and was totally unaware that masturbation was exacerbating my symptoms. After studying TCM, I understood. TCM: *“essence deficiency, nasosinusitis”*. When there is an essence deficiency, it will induce rhinitis, because kidneys govern inhalation while the lungs mainly govern exhalation. If those with a weak constitution masturbate, rhinitis will become more serious. Because a weak constitution emphasizes the point that the body is unable to handle further depletions.

Everybody has a different constitution. Some people are born with a naturally strong constitution. If a level of depletion is not reached, there will be no symptoms. But for me, I have a weak constitution, symptoms appear with the slightest depletion. I remember a brother once mentioned that he had a naturally strong constitution and would not feel cold, even leaving arms exposed during winter. Afterward, due to frequent masturbation, he has injured the kidney yang. The four limbs feel cold even during the summer, the kidney yang has become deficient.

If you masturbate for a year a two, the body will not have problems. But if you keep going and have injured your body to a certain extent, then symptoms will surely appear. Some people love to exercise and have well-ordered schedules. In those cases, symptoms will be mild. But no matter how strong the body is, after 40 years of age, the body will start to decline. By then, many latent illnesses will all erupt at once, this is all caused by overindulgence in youth. When we are young, our yang qi is abundant and so we will not notice anything. As we age, many issues will become more apparent.

I still have rhinitis to this day, but compared to before, it is a big improvement. Previously, I would feel bad everyday and now I very seldom feel bad. Moreover, I have learned moxibustion. When the nose is feeling uncomfortable, by applying moxibustion on the Hegu and Zusanli acupoints, the obstructions clear up very quickly.

In reality, many people suffer from aggravated rhinitis as a result of masturbation. In my vicinity, several friends have it. My cousin didn’t have rhinitis before, but then he learned how to masturbate, and a few years later he also had rhinitis. Masturbation induces kidney qi deficiency, the resistance of the body vastly decreases. When an inner deficiency is present, outer evil will enter more easily. In this way, the chances of catching many illnesses is increased. Therefore, one must cut out masturbation and cultivate the kidney qi. Otherwise many illnesses will come knocking! Remember this at all costs.