# The issue of soft legs, secretion of oil, tension disorder and scrotum dampness

## Soft legs

The phenomenon of soft legs is very common among brothers. It is a common sight in the forums to see brothers relating to soft legs that are lacking in strength. In TCM, this is easy to explain. Because kidneys govern the bones, also that the kidney meridian starts from the Yongquan acupoint at the bottom of the legs and continues upwards. Therefore, following masturbation or even nocturnal emission, the phenomenon of soft legs easily occur. This phenomenon has also been verified in TCM, masturbation induces porosity in the bones and a decrease in bone density.

TCM also mentions the waist houses the kidneys, the kidneys runs through the knees. A common symptom of kidney deficiency is soreness in the waist and knees, many brothers suffer from waist pains. Many people would experience lots of pain when bending their waist. This, in reality, is the typical expression of inadequate kidney essence, a signal from the body to not indulge any further.

I masturbated frequently during middle and high school. When playing basketball, I would often sprain my ankle. Many times when it happened, there was no body contact involved. After having masturbated, I would always feel weakness in the legs, my footing not being firm. But I didn’t know it was caused by masturbation and I didn’t know about medical principles. Now that I have studied TCM theory, I came to understand the underlying reasons.

These days, I’m watching NBA and happened to see Roosevelt from the Buffalo Bulls injure his knees. The situation was that the overlapping ligament of the left knees was torn, the next season is forfeited. Roosevelt’s injury was very peculiar, no body contact took place. He was holding the ball and made a forward leap, the knee was injured. Seeing such an injury, I dare to say that the night before the match, Roosevelt either had a nocturnal emission or was indulging. Combined with the accumulation of wear and fatigue from the frequent matches, this strange kind of injury then happened.

To this day, I still remember a scene from Stallone’s Rocky 1. Rocky’s coach told him to not touch women. Touching women makes one’s legs weak and would affect the performance during a match. In competitive sports, it is taboo to touch women before a match. Touching women weakens the legs and makes one unable to properly perform many movements, injuries also occur more easily. I have seen the boxing king Tyson’s documentary. When commenting about his loss versus Douglas in Japan, Tyson said that he lost the match due to his indulgences and entered the match in a bad physical state. The consequence is easy to imagine; defeated by a vastly inferior Douglas.

Following masturbation or nocturnal emission, one must take care to rest well, abstain from heavy exercises in order to avoid injuries.

## Oil secretion

Below we will discuss the oil secretion issue:

Many brothers experience the secretion of oil following masturbation. This is because masturbation causes hormonal imbalance and so the secretion of oil will occur. Of course, it is not only limited to the secretion of oil, some brothers experience dryness in the skin. Hormonal imbalance can be grouped into 2 categories. In the first category, there is the secretion of oil. In the second category, we have dryness of the skin. In summary, there are more cases of oil secretions. This has to do with the different constitutions of our bodies.

There 2 categories of oil secretion:

Secretion of oil from the face
Secretion of oil from the scalp
Oil secretion in the face easily lead to acne and pimples. Furthermore, the acne that is caused by masturbation is often very stubborn and belongs to the stubborn form of acne. It is very difficult to recover from if one does not cut out masturbation. When the face is always oily, it will also affect the looks of a person. When the scalp is secreting oil, it will easily lead to seborrheic alopecia. Sufferers often have thin and soft hair, sometimes it is also accompanied by scalp dermatitis symptoms.

I have specifically talked about the issue of hair loss in an earlier chapter. Normally, mild to medium degree of hair loss is relatively easy to recover from. Heavy hair loss is relatively more difficult to recover from. There is a saying that “accumulation is hard to retrace”. Those that have the financial means can try hair implantation. After quitting masturbation, I clearly noticed a decline in the oiliness of the skin, the same goes for the scalp. This is a sign that the hormonal imbalance has been corrected. Therefore, in order to reduce the secretion of oil, one must cut out masturbation. Do not only expend effort on surface issues, make adjustments from the root of the issue.

Some brothers would ask, could one use oil removing products? My answer is, one certainly can, but rebooting must be emphasized. Otherwise, one is only treating the symptoms and not the cause. Only through persistent rebooting can the hormonal imbalance return to normal. Otherwise, all the product in the world can only ease the issue but not cure it.

## Tension disorder

Let’s continue towards the issue of tension disorder:

Tension disorder can be categorized as:

Urinating obstacles
Obstacles during sex
Many brothers have provided the feedback: being unable to urinate when other people are around, returned to normal when nobody is around. Other brothers have reported that when it comes sex, there are problems with erection. This kind of nervousness obstacles is, in reality, an expression of weakened kidney qi. When the kidney qi has been damaged to a certain degree then this kind of phenomenon will appear. I have experienced these two phenomena myself. Normally, after a period of rebooting while actively exercising, rhythmic lifestyle habits, abundant kidney qi, nervousness obstacles will diminish substantially and even self-heal. Therefore, those brothers with this kind of conditions should not fret too much. Reboot and accumulate the kidney qi and recovery is possible.

## Scrotum dampness

Lastly, let’s talk about the issue of scrotum dampness:

This is also a very common problem, the majority of brothers will have experienced this phenomenon. With scrotum dampness one feels uncomfortable, it is a disturbing annoyance. Scrotum dampness points to scrotum erosion, moist, itching that are due to deficiencies in the spleen, allergy to medicines, deficiency in vitamins, fungus breeding among other factors. It is mostly a male-specific skin disease.

Scrotum dampness is the typical clinical expression of chronic prostatitis. It is often caused by disorders in the autonomic nerves as a result of chronic prostatitis. As one recovers from prostatitis, scrotum dampness will appear intermittently until it disappears. Scrotum dampness is one of the typical symptoms of chronic prostatitis which is related to frequent long sittings, working in a hot environment and varicocele. If you are suffering from prostatitis, then your scrotum dampness is related to prostatitis.

Previously, I have had scrotum dampness with even the appearance of eczema. It is extremely uncomfortable, always damp like water and with the scrotum hanging loose. Normally, those with prostatitis will all have scrotum dampness. Naturally, if you have scrotum dampness, you can go check if you also have prostatitis. After I have cut out masturbation, exercised actively, took care of my rest, accumulated enough kidney qi, scrotum dampness slowly disappeared. The scrotum was also pulled upwards, prostatitis was healed. Therefore, those brothers that have encountered scrotum dampness, the best way would be to keep rebooting. By doing so, there will be the hope of solving this trouble.
