# Complementary info on nocturnal emission, harmlessness theories, theory of harmfulness from restraining and the frequency of sex during marriage

## More on nocturnal emission {-}

I have treated the issue of nocturnal emission in chapter 3 and 7, it is a big issue. Frequent emissions harm the body greatly. In addition, relapses are made very easy following emissions, thoughts will become swayed. This is why it’s important to decrease the number of emissions in order to benefit the recovery process.

Regarding nocturnal emissions, I have recommended a kidney strengthening exercise. Its result according to feedback can be divided into 2 categories. In the first category, the result is very good, many brothers really achieved having onlyone nocturnal emission over a month, usually 30+ days, some have achieved 40+ days, where previously it had been 8 times/month. Therefore, there is no doubt around the effectiveness of the kidney strengthening exercise. In the other category, there is not much improvement which is troubling. Why is it that other people have achieved 30+ days but not these brothers? Those who have not made it must ask themselves this question.

In this season, I will once more discuss this issue in depth. I hope it can help everyone to deepen their understanding of the issue of nocturnal emissions.

Those brothers who have not achieved the desired results reminded me of my gym lessons from school. The gym teacher would demonstrate a movement to everyone. Those with a talent in exercising would grasp the essentials very quickly and be able to do the move accurately. On the other hand, there are a lot of people who have practiced the move many times without mastering it. The content of the instruction from the teacher is the same, but the absorbing ability and the degree of absorption are different for different students. But if you persist in your practice, there will come a day when you have found the feeling. People with high talent might find the correct feeling very quickly. People with lower talent might need to spend a week, even a month to find the correct feeling. This is the first point.

The second point, many people already possess flexible ligaments and are able to touch the ground. However, being able to touch the ground is not enough, one must find the tightening feeling from the stretch and increase the tightness. Many people stop short after they have touched the ground, thinking that they have done their part. In reality, this is only the beginning, one must thrust towards the limit and then repeat the exercise for at least 10 times under such circumstance. Once this has been achieved then they are doing their part, do not stop just short of reaching one’s limit. After touching the ground, touch it with the palms. After that stand on a chair and try to touch the ground, one step at a time.

Many brothers mention that they are not flexible and are unable to touch the ground, this is quite OK. The important thing is the tightening feeling from the stretch. Although you may not be flexible, if you are able to find that tightening feeling and are able to intensify it, over time, you will naturally be able to touch the ground. Not only that, when you become skilled, you will have an easy time to touch the ground with the palms. The difficulty lies in persistence, this is a gradual process. Few people are able to touch the ground with their palms on their first try.

Point three, there are many factors that would induce nocturnal emissions. The kidney strengthening exercise is not a panacea, if you trip over one of those factors, you will still have an emission. 2 days ago, I answered a question from a brother, his situation is the following. He persists in doing kidney strengthening exercise and was able to reduce the frequency of nocturnal emissions, but in recent days, he has had frequent emissions and is very troubled by it. He wonders what the problem is? I then helped him to analyze and let him try to recall what he has done in recent days. Then he replied that he has recently caught a cold and has besides been playing basketball. Then I told him: the answer has been found, your case on nocturnal emission has been solved. The reason for his frequent emissions is very simple, but if you don’t understand the principle behind it, one might not figure it out during their entire lifetime. He caught a cold, the body, in this case, is already weakened, then he goes off to play basketball and sweat profusely.

TCM: *“Profuse sweating hurts the yang qi, labor hurts the yang qi”*. When he played basketball after catching a cold, he acted in accordance with the saying in TCM *“double weakness leads to disaster”*. Fatigue is a reason for nocturnal emissions during the night. Many people over-exercise during the day. After sweating they become very tired, in the night they then have a nocturnal emission. This kind of fatigue followed by emission is very very common, there are many such cases among those that I have collected.

The mistakes that younger people tend to make is: over-exercising, only knowing how to release but not to restrain. When the body is weakened, care must be taken in resting, TCM has stated: *“He who sweats loses essence”*. Playing basketball makes one sweat a lot. When the essence is suddenly injured, nocturnal emission will easily occur at night. I have also had experiences regarding the damaging effect of fatigue on the essences. When my body is weakened and I went for a few sets of deep squats, during the night I had an emission.

Therefore, when the body is weakened, try to refrain from heavy exercises and avoid those exercises that would cause one to sweat heavily. Otherwise, nocturnal emission will easily occur during the night. One needs to take care of the degree of intensity when playing basketball and also pay attention to timing. Don’t go playing when the body is weakened or is feeling unwell, emphasize convalescence. One may perform low-intensity exercises such as taking a walk.

Factors that induce nocturnal emission:

1. Sexual fantasizing during the day
2. Fatigue during the day
3. Alcohol intake
4. Heavy meat consumption
5. Intake of supplementary medicine
6. Sleeping facing down
7. Sleeping naked
8. Sunbathing the blankets
9. Thick blankets
10. Meditation before bed
11. Tight underwear
12. Pushing against or sandwiching the blankets
13. Improper use of moxibustion
14. Guarding the dantian while meditating
15. Staying up late and long sitting
16. Drinking too much water before bed
17. Over exercising
18. Illness
19. Weakened kidneys, dreamlessness
20. Spicy diet, heavy diet
21. Nervousness *(including nightmare)*
22. Pressing *(including sleeping facing down)*
23. Anger *(causes disorders in blood and qi)*

Regarding the issue of nocturnal emissions, I have already replied to several hundred questions. The main causes that I have summarized are the 23 points above. As a senior rebooter, the things learned are from *“trial and error”*. Using what one has learned through experience and passing these on to brothers, especially to newcomers. The misconceptions among newcomers are many. The correct understanding must be established for newcomers, or else they might never understand.

Many brothers take notes after having a nocturnal emission, they will note down the time of the occurrence. But what they are lacking is a thorough understanding of nocturnal emissions. If you do not clearly recognize the causes, then there is no way to truly avoid nocturnal emissions. The same mistakes will be repeated without knowing what has transpired.

I will name an example: to not be robbed by the thief, one must outsmart the thief. The thief is already very smart, yet you must outsmart him as well as keep improving upon yourself. Through this way can the frequency of the emissions be reduced to the maximum degree. If you are able to control the frequency of the emissions to once per month, then this will be very favorable to your recovery process. Or else, no matter how much Chinese medicine you take, the efficiency will be reduced, because you are leaking too much!

Every emission is like solving a case, looking for clues and the triggering factor. Of course, there is no need to deliberately look for clues if the frequency is once per month. This is because, for ordinary people, the theory of essence overflowing is applicable. But if the frequency exceeds 3 times/month, for sure this is not due to the overflowing of the essence, but it is due to an abnormal state of emissions. Only when the cause has been found can we avoid it in the future, or else if you fail to consider and summarize following an episode of emission, the result will still be frequent emissions. According to my understanding, there are plenty of brothers who have been bothered by the issue of nocturnal emissions for over a decade. They experience aching waist and knees, strengthless body, tinnitus, decreased brain power, the symptoms are plentiful.

I will share 2 more cases. The first is about eating too many pig kidneys, followed by nocturnal emission. The other is about eating too much sesame, followed by nocturnal emission. Sesame is very good, but health cultivators in ancient times only eat 2 pellets per day, why don’t they eat more? Because eating more makes it harder to digest and to absorb, also that it induces nocturnal emissions.

Therefore, it is permitted to intake sesame, but one must pay attention to the quantity. Don’t intake a full bowl at a time as that will easily lead to nocturnal emission. When it comes to supplementary things one has to pay attention to the quantity. In addition, one should also eat less meat, or else frequent emissions will easily occur. It will also promote desire, remember at all costs!

Below let’s talk about harmlessness theory and the theory of harm from restraining:

## The harmlessness theory {-}

Harmlessness theories tend to be very confusing and misleading because everybody knows that after marriage there will be sexual activities, why shouldn’t there be any such activities before marriage? Many people carry misconceptions in their thoughts and will ask such questions. They also agree on the idea of harmlessness from moderation. Back in the days, I was also confused by the harmlessness theory and was deeply misled by it. These seemingly correct theories are highly damaging to teenagers and inexperienced brothers. These theories will allow the masturbators to sink deeper into the trap. When the body is displaying symptoms, it is past the time for regrets.

In the many cases that I’ve seen, brothers always criticize the harmlessness theory as they think that it has harmed them from the very start. Therefore, with regards to the harmlessness theory, one’s position must be firm and resolute. There is no room for doubts, or else it is impossible to become clean. One will only wander aimlessly in the vicious circle.

The hole in the theory of moderation is ignoring the addictive quality of masturbation as it is highly addictive. Once hooked, you are no longer in control, like a breached dam. Many brothers will do it twice once they have relapsed, even indulging in several days at a time finding it impossible to hold back.

Why is it that after marriage, it is allowed to have a sex life? In post-marriage sex life, one must, of course, pay attention to *“moderation”*. Records since ancient times have it noted that sexual excess weakens the body and induces illnesses. Many brothers in the rebooting forums are already married, yet they still want to reboot, why? Because the body is greatly weakened and is stricken with many symptoms, one must reboot or it is all finished.

Normally, I would advise those brothers with wives to have a good talk together in order to arrive at an understanding. This is a good approach to rebooting, or else the wife might misunderstand you and this will easily lead to conflicts. Once you have practiced restraint for a while and have accumulated enough kidney qi, by then it will not be too late to have a sex life. As long as the health is intact, we can endure temporary setbacks. Suppose that you overdrafted your health in advance, in the future one becomes completely impotent, that, unfortunately, will not be the worst news because by then countless symptoms will have come knocking on the door.

The guideline to post marital sex life: accumulate abundant kidney qi, use it sparingly. If symptoms have already appeared, abstain for a while, accumulate till abundance, use again.

To put a stop to premarital sexual behavior: the purpose is to let your kidney qi go unscathed as much as possible. Otherwise, many brothers fool around before marriage and waste away their health, what will they resort to after marriage?

Regarding harmlessness theories, I will name an example. After seeing this everyone will know how to treat harmlessness theories. It goes like this: Two people come up to you to talk, one says that elephants are grey, the other says elephants are blue. The first person supports his claim with good arguments while the latter comes up with even better arguments. This is when you start to hesitate and don’t know who to trust because both sides have good arguments.

At this juncture the best way to find the truth is to go see yourself what color the elephant is! Reality trumps rhetoric! Similarly, when it comes to rebooting, you can directly look for cases from brothers in suffering and study them. Let them speak for themselves and discover the truth in them. Cases are the foremost precious resource, the reported conditions are the most real.

## The harmfulness from restraining theory {-}

Regarding harmfulness from restraining theories, many brothers have asked about this. I can definitely say to everyone, restraining is not harmful but with one condition, one must put an end to sexual fantizing as much as possible. Otherwise, fire meets fire while one tries to hold it back and problems will arise.

In the TCM medical records, I have seen quite a few similar cases, induced by sexual fantizing. If the cultivation of the heart is in place, then this problem will not exist. Many monks have lived for beyond 100 years when the heart is properly cultivated, restraining poses no damage to the body. Many brothers run into symptoms after they start to reboot, then they think about the articles on the harm from abstaining, they immediately start to masturbate. In this case, they have actually not realized the withdrawal symptoms.

According to my experiences, almost every brother will encounter withdrawal symptoms after they start to reboot, some are mild while others are severe, this is all very normal. When the vital energy is being replenished, latent illnesses will naturally express themselves. Persist in rebooting, the withdrawal symptoms will vanish and the body will become successively better.

## The frequency of sex post-marriage {-}

Lastly, let’s talk about the frequency of sex post-marriage.

The frequency of sex following marriage is a closely followed topic. Everyone may refer to the essay from Sun Simiao, the king of Chinese medicine.

>The way to manage a woman: 
If one is able to ejaculate twice in a month, 24 times in a year, one will surely live to be 200 years old, with healthy color and no illnesses. If medicine is applied, longevity is made possible. 
He who is in his 20s, one ejaculation every 4 days. 
In his 30s, once every 8 days. 
In his 40s, once every 16 days. 
In his 50s, once every 20 days. 
In his 60s, cease ejaculation, if the body is still strong, one ejaculation every 30 days.

This paragraph from the medicine king is reserved for married couples. Because people in the past married early, people in their 20s were generally all married. Those people at the time did not advocate premarital sexual behavior. This is because they had a deep understanding of this area. They knew that premarital behavior results in bad karma.

The mentioned frequency of sexual behavior has a condition and that is that the condition of your kidney qi is abundant. Otherwise, if your kidney qi is already depleted, if you carry on like you are it will only become more depleted, the recovery will be made endlessly more difficult.

My personal recommendation is 2 times/month under the condition that the kidney qi is abundant, this frequency will have little damaging effect on the body.

