# How to conquer sexual fantasizing, repeated phenomenon, sleepiness, pressure induced masturbation

Having started to reboot, sexual fantasizing is an issue that everyone will normally run into. Many people are able to abstain from masturbation, but sexual fantasizing is like a loosened wild horse, repeating itself every couple minutes. In TCM: *“the moving of the mind is followed by the walking away from the essence”*. Sexual fantasizing belongs to the invisible form of exhausting the Spirit. It is also very damaging to the body, therefore one must overcome it.

If your head is filled with fantasizing but you are constantly withholding masturbation, this will easily give rise to problems. To overcome sexual fantasizing, one must deeply recognize what it is. Sexual fantasizing is a thought, a thought of evil debauchery. This thought is a thing and that thing is *“fire”*!

With this knowledge in place, everybody’s understanding will increase a step. Below, let’s again consider a question: under what situations is fire easily extinguished? Everyone with a bit of common knowledge would know, fire, in the beginning, is easiest to put out, not requiring big efforts to do so. Otherwise, when the sparks have become big embers, then there is no way to control it.

Chairman Mao used to say: *“sparks becomes fire, able to alight prairie”*. Once the fire is greatly developed, you are no longer in control. But from the very beginning, you still have full control. Our sexual fantasizing follows the same principle. When the thought first arises, we discard it right away, this is called *“arisen thought is promptly cut off”*, strangle the fire in its cradle while it’s still undeveloped. Otherwise, by letting it develop the final result will be burning with desire, leading to the extreme likelihood of breaking the reboot.

Therefore, there are tricks to overcome sexual fantasizing. The trick lies in the timing. When the fantasizing first appears, cut it out immediately, or else it will *“flourish as it burns”*. Put the thought out while it’s still a spark. Do not hesitate, do not compromise, don’t miss this golden timing at all cost, remember!

Rhyme for stopping sexual fantasizing: **“Thought arises, cut out. Thought arise, follow not. Thought arise, be aware. Once aware, it is naught.”**

When everyone has memorized this rhyme then a conditional reflex can be formed, whenever a fantasy arises it is automatically discarded. Naturally, the condition is to be able to memorize it inside and out by constantly repeating it. Let it sink into the subconscious. In this way, the conditional reflex for discarding sexual fantasies can be formed. We need to uphold a high level of vigilance and sensitivity. We cannot afford to wait until the fantasy has been developed and then try to cut it off, it will be extremely difficult to control it in such a state. The problem is not with the initial formation of the thought but in the late awareness of it.

Below I will introduce two kinds of Buddhist heart cultivation methods:

The first method was instructed by Master Empty Cloud, it is to not pay attention to unwanted thoughts. When the thought comes, do not mind it. This is the same as not following the thought we have discussed earlier. Do not follow the unwarranted thought. By following it we are strengthening it. Not following is the same as severing it! Many brothers have been following vile thoughts for a long time, this is when they suddenly discover that they are fantasizing sexual thoughts. It is already too late at this stage, the vile thought has already taken shape like when a small spark has become a big ember. We no longer hold the initiative when trying to sever the thought at this time, the optimal timing has been missed.

The other method is called diverting thought. When the sexual fantasy appears, immediately transform it into a Buddha’s name. It does not, of course, have to be limited to sexual fantasies but may also include thoughts of the foolish, greedy and angry orientation. Once it appears, transform it into a Buddha’s name, a phrase of *“Amituofo”* *(Translator’s note: “Amituofo” is simply the name of the Amitabha Buddha’s name in Chinese)* will transform it. This is a very good method and I use it quite a lot. As a person of Buddhist beliefs, this method works very well for me. Those brothers with a natural disposition towards Buddhism may try this method.

All in all, to be successful in rebooting, the level of sexual fantasizing must be surpassed.

To be able to recover the health, frequent nocturnal emissions must be surpassed.

Rebooting is indeed not that simple, I cannot succeed simply by saying that I have a strong willpower. To be successful, one must study rebooting articles in order to increase understanding and the level of determination. In doing so, there is a hope to completely reboot. Once we pause our studies or relax our vigilance, relapses will come very easily.

Rebooting must become professional. What do we mean by professional? Everyone knows the classification of professional players and amateur players. In basketball, there is professional basketball and amateur basketball. The same goes for rebooting, one must allow the rebooting process to become more professional and proper through studying. Neglecting to study, you will never turn professional and forever remain a rookie, to make a complete reboot is indeed a very difficult task.

Those with a genuine understanding and a kind disposition are certainly the kind of people who study persistently everyday. Everyday will be a day of insights. In this manner, these people will rapidly gain understanding and determination.

During my long presence in the rebooting forums, I have indeed come across many brothers who are progressing rapidly with a high level of insight. There are also some brothers, who have rebooted for a long time but have not reached the desired results. They still have a fuzzy understanding about rebooting and with many unresolved questions, how can one succeed under such circumstances? If you still harbor doubts with regards to rebooting, with your footing still not firm, to be able to successfully reboot is no different than a pipe dream. Only through reforming the thoughts through studying and allowing the understanding to leap forward will there be the possibility to stay clean for good and to never look back!

## Repeated phenomenon {-}

Below let’s talk about the repeated phenomenon:

Some brothers ask, what is the difference between withdrawal symptoms and repeated phenomenon. What these two have in common is that the bodily symptoms are present in both cases, but there are still differences:

Withdrawal symptoms normally appear after a month of rebooting. Some brothers will not have any issues before rebooting but will run into symptoms after having started to reboot. After rebooting the righteous qi of the body is starting to recover, latent illnesses will naturally make an appearance, persist in rebooting and the symptoms will slowly vanish.

Some brothers don’t understand withdrawal symptoms and will panic when they appear. They think that it is due to refraining too much, the result is to sink back into the trap of masturbation and unable to pull oneself out. Therefore, to be successful in rebooting, one must establish the correct understanding, otherwise, only failure awaits.

The lag of repeated phenomenon, on the other hand, is very large. Some people will experience it 3 months into rebooting. For some, it will occur half a year after rebooting. For others, repeated phenomenon will show up a year later. The occurrence of repeated symptom is very normal.

According to my research, many brothers will encounter them after having a nocturnal emission, or following staying up at night, fatigue, long sitting, anger, unhealthy diet patterns, having a cold etc. would all induce repeated phenomenon. This principle is in reality very easy to understand. When your kidney qi has not yet been cultivated into abundance, nocturnal emission and other poor living habits will all have a damaging effect on the kidney qi. The repeated phenomenon will then occur very easily. Another reason is the turn of the seasons, this is because the level of yang qi in the body differs in every season. Normally, the turning of the seasons is the time prone for repeated phenomenon. When the phenomenon appears, do not worry. Take care to rest for a couple of days, sleep early, keep a light diet and symptoms will slowly disappear.

## Sleepiness {-}

Let’s now talk about the symptom of sleepiness:

The expression of kidney deficiency has a noun and its called *“fond of crouching, lazy to move”*. This does not only happen after masturbation. Even
after a nocturnal emission, people will exhibit this kind of behavior; turning lazy, desiring to sleep and finding it hard to awaken. When many brothers are unable to sleep, they will masturbate to allow themselves to feel tired, this then makes it easier to fall asleep. This kind of method is in reality very bad. When kidney qi has been depleted to a certain degree, sleeping difficulties will arise. When that time comes, even if you masturbate before bed you will still have a hard time sleeping. Therefore, one must change this habit of masturbation before bed, correct it immediately. This is like a tree that is not growing straight, one must straighten it and not allow it to follow its crooked growth.

I would like to share a case:

>I started to masturbate when I was 14, I did it very frequently. Later when I found out that masturbation is harmful to the body I stopped. Then I would often have insomnia during the night. During the days, I would have a headache and the brain would feel swollen, waist aches, urine yellow. Is this due to over masturbation induced kidney deficiency? What should I do, I have not slept properly for quite a few years!

Brothers with a habit of masturbating before bed, this habit must be corrected. The power of habit is very strong, one must learn to overcome it, otherwise what awaits you are symptoms. After masturbation one becomes lazy, this, in reality, is the expression of qi deficiency. Some people are not satisfied masturbating once but do it twice. These kinds of people will for sure encounter premature ejaculation and impotence in the future. This is because *“desire should not be strong, strong desire destroys”*. One must understand this principle.

## Pressure-induced masturbation {-}

Lastly, let’s discuss the issue of pressure-induced masturbation.

According to my research and summaries, normally among brothers, there will be the emergence of two negative orientations:

- Masturbation before bed: with the purpose of masturbating in order to fall asleep easier, this habit greatly injures the kidney qi, once accumulated to a certain degree the result is insomnia.

- Pressure-induced masturbation: turning pressure into masturbation behavior, this kind of situation is also very common.

I have mentioned masturbation before bed above. Below, let’s discuss pressure induced masturbation.

Pressure-induced masturbation can be divided into several groups. There is the pressure from seeking employment, academic pressure, pressure from parents, social relationship pressure. Living in this world one will receive different forms of pressure. Therefore there is a saying: *it is easy to be born, living is not easy, life is not easy*.

Among the brothers that I have met, some have failed to find a job, some have been scolded by their wives, by parents, they lose control of their mood/emotions and have huge mental pressure. Under these circumstances, one seeks the comfort of masturbation and through it hopes to get rid of the negative emotions. To be honest, I used to be like this all the time, either being scolded or not doing well on an exam. The same evening, I would for sure masturbate. Masturbation was like an outlet for relief, hoping to empty me via masturbation and then to think of nothing, a day would simply pass in this way.

This way of relieving oneself is not worth having because it is harmful to the body. Although it may have an alleviating effect for releasing mental pressure, in the end, the harm outweighs the benefit. Therefore, one must overcome this kind of tendency. There are other ways to clear out the pressures of life, one does not have to rely on masturbation. A good way is through exercising. Of course, one needs to pay attention to its intensity. The way that I advocate is to adjust the mind, pressure dislodges your psychological balance. You need to learn to adjust it back to a state of equilibrium, allowing oneself to remain in the state of tranquility. The ability to regulate the mind is a mood managing ability. Everyone may read more emotional intelligence related books, which will help in better managing one’s mood.

Among the brothers that I have consulted, many people relapse due to problems in mood. Life not turning out according to expectations, pressure from life, these lead to the loss of mood control. Under these psychological conditions, it is relatively easy to break the reboot when we are not feeling too high and have no outlets, why not masturbate, just like that we have unconsciously relapsed.

In writing this article, the purpose is to let everyone see clearly the importance of mood management. Only with a stable emotional state, will there be the hope of making a complete reboot and never looking back!
