# Complementary info on prostatitis, insomnia, relapse while dawdling in bed, weekend relapse

## More on prostatitis {-}

Recently, when answering questions from brothers, I discovered an issue: many brothers due to masturbation have contracted prostatitis. Therefore, they pay closer attention to this issue. They go to prostate forums and prostate discussion platforms in order to study. Regarding prostatitis forums, there is no need to pay a visit due to the amount of false information and advertisement. Prostate discussion boards could be worth a visit, but they are full of a kind of incorrect thinking. This kind of thinking has a very strong confusing tendency. When a normal patient reads it, one is prone to become brainwashed and will greatly sympathize with that way of thinking, not only sympathizing but also help to spread the thinking. This kind of thinking is about the harm to the prostate due to restraining, the need to ejaculate regularly for fear of aggravating prostatitis.

I believe the more experienced rebooters have all witnessed that I once fell prey to similar points of view. At the time I was rebooting and indeed my prostatitis had gotten worse. But during that time, I was unaware of the effects from withdrawal symptoms, and those symptoms would show up as the righteous qi being recovered, that the effect was only temporary and would gradually disappear if I kept rebooting and actively exercising. When many brothers start to reboot and then discover the emergence of symptoms, they right away think about the harm from restraining and then immediately start to masturbate. The result is to once again fall into the trap of masturbation and the inability to pull out.

Furthermore, they have no qualms about it, because it is stated in the articles that regular emission is healthy, they think that such indulgences are not wrong. Actually, this is a grave error. I’m certain that the person who wrote the article has a blind spot in their understanding. They are certainly not aware of withdrawal symptoms during rebooting, neither have they persisted in rebooting and have only become mislead by certain immature theories, the result is the writing of such articles. The falsehood is then spread from one to ten and from ten to a hundred, indeed confirming the saying that falseness spreads through ten thousand books. Nowadays, prostatitis patients, in general, believe in the theory of harm from restraining. What I want to say is that this kind of thinking is completely false and creates great harm among people.

Why have these kinds of wrong theories become so popular?

Of course, some people have raised the point that it is a conspiracy theory. I think this is a possibility, what do male clinics rely on to make money? Prostatitis patients are their number one source of income. Once the patient has been admitted, a whole spectrum of checks awaits. The screening bills of many patients will amount to the thousands, many treatment fees cost up to five-figure amounts, what is the result? The result is that prostatitis is still not cured of the root. After spending five-figure sums on treatment it is still not healed, what is the reason? Many people are still prostatitis patients their entire life up until they die, they have not been cured during an entire lifetime.

A kind of thought has the ability to harm generations of people. If it is not corrected, it may harm several dozen generations, this is very scary. Who is pushing this? I think there are 3 possibilities:

- Information spread by “75 parties” *(a self-proclaimed expert)*
- Intentional spreading of information by male clinics
- People with blind spots in understanding take it for granted

Below is my criticism to point 11 of that article:

>“11. Both indulgence and restraint will cause blood congestion of prostatitis. Therefore, one must control the degree themselves: do not engage in sexual activities in the absence of biological need. Go with the flow when there is a biological need and allow for reasonable dissipation of the sexual energy. Ensure regular sexual activity with sexual partner, unmarried friends may masturbate, normally have one release every 4-7 days”

Many articles on the internet have problems in their arguments. Of course, many harmlessness theories also take up these seemingly correct arguments. These arguments have a high tendency to confuse the rookies and those without ample experience.

How to discriminate between truth and falsehood? There is only one way, find a person that has been through all of this, find a realistic case.

As a person that has gone through all of this, my disposition can be found below:

*“Both indulgence and restraint would cause the blood congestion of prostatitis.”*: I do not dare blindly agree with this line. So far there is no research to prove this, that restraining will induce blood congestion.

*“Go with the flow when there is a biological need”*: There is also a problem with this line. After many people have become addicted, every day they would have a biological need, should they masturbate daily? A person must learn to overcome his desires, or else it will lead to self-destruction. Countless cases from brothers have already proven this point.

*“unmarried friends may masturbate”*: I have even more reasons to not dare endorse this point. Many people have had their kidney qi weakened, they cannot sustain further injuries. Should masturbation still continue under such cases? This would only form a vicious cycle, prostatitis patients may never hope to recover. Think for yourself, did you have prostatitis before you started to masturbate? Certainly not. Now that due to masturbation, prostatitis has emerged, and one still harbors the excessive expectation to cure prostatitis through masturbation. Is this not absurd?

*“he must control the degree himself”*: He who wrote this line has for sure not recognized the highly addictive quality of masturbation. Once addicted, one cannot control it but is controlled by the addiction, the choice does not belong to oneself.

I used to have serious prostatitis with seriously frequent urination. I have undergone examinations where inflammation had been found. Now I have rebooted for more than 2 years, frequent urination has completely disappeared, my waist no longer aches and my underbelly no longer swells. If I had believed in these unfounded falsehoods, I would still have frequent urination today and could have never hoped to get well. To be honest, I previously believed in the harm of restraining. What was the result? Over a decade of unhealed prostatitis, countless visits to the hospital, ingested a load of medicine, still not healed, only alleviated, unable to get rid of the root issue!

Many people feel better but it is only temporary recovery, it is not complete healing. If they indulge again, the illness relapses. This is why the relapse rate of prostatitis is over 90% because many people bear misconceptions and still agree with the absurd theory of *“one emission every 4-7 days”*.

Can healing be achieved by eating medicine? No, I trust that there are prostatitis patients with experience in undergoing treatment. Eating
medicine will in no way achieve healing, only temporarily dampen the inflammation, not get rid of the root cause.

Nowadays, there have been new inventions of all sorts of strange devices and terminologies, such as body type treatment, the newly sourced peptide pass procedure, STQ high-efficiency lipid permeation repair factor, and all the yet to come new inventions and terminologies that I believe will take place. All of these have one goal in common: to make the patient reach for their wallet. And the treatment fee from these advanced instruments is often tremendous, with one course of treatment normally costing tens of thousands. If they could truly heal the ailment, then one would be willing to pay any price, but what is the result? No cure of the illness with recurrent relapses.

Actually, to cure one must reform the thoughts. 30% comes from treatment while 70% is from maintenance. Prostatitis should be actively treated but the emphasis is on maintaining a healthy lifestyle which includes rebooting, you must accumulate enough kidney qi. Of course, there is a lot of attention required in cultivating good health. In season 12, I have specifically talked about cultivating the health, everybody may have a look.

Whether or not there is harm from restraining, I have already elaborated on in season 16, everybody can have a look.

To restrain, one must learn to adjust the mind. If sexual fantasizing is serious, a problem will easily occur. If your heart is properly cultivated, restraining will not have any harm. Cultivate enough kidney qi and prostatitis will heal by itself.

For chronic prostatitis patients that have read this article, I hope that you have gained certain insights. After gaining these insights, one is able to save medical expenses, or else the urology department will keep waving its hands at you. Before I started to reboot, I frequently visited the urology department. After having rebooted for 2 years, I have not returned once. Just like this, I have saved countless medical expenses. Many brothers report their inability to keep money after they start to masturbate. Precisely because masturbation hurts the kidney qi, then spending on medical bills runs like the water. Keep this in mind!

## Insomnia {-}

Below let’s talk about the sleeping issue:

Many brothers run into obstacles when it comes to sleep, mainly in the below categories:

- Insomnia
- Difficult falling asleep, difficulty in entering sleep
- Excessive dreams
- Early awakening, including waking up in the middle of the night
- Shallow sleep, poor quality sleep

Sleep is indeed a big issue. If your sleep quality is poor, then recovery of the body will become relatively difficult. Yet there are many factors which cause sleeping difficulties. Normally among brothers, the main reason is masturbation induced loss of coordination between heart and kidneys. Besides that, it is long gazing which injures the liver qi, heavy pressure is also a reason.

People that are prone to staying up late and sitting for long periods will easily encounter sleeping difficulties. Staying up late is an important factor because it tends to be accompanied by long staring and long sitting. The body will suffer relatively heavy damage in this way. So in order to restore the quality of sleep, one must make an adjustment in the working and resting schedule. Try to go to bed before 11 pm, simply close the eyes and rest if one is unable to fall asleep. Take care to establish normal working and resting habits, staying up late does too much damage to the Spirit.

Some brothers are unable to sleep at night. When asked it turns out that they like to take naps at noon. When somebody takes noon naps they will have a hard time falling asleep at night, I have had this experience. Afterwards, I stopped taking naps at noon, if I’m not too fatigued then there is no need to take a nap, or else falling asleep in the evening will become difficult.

Do not worry too much if sleeping difficulty shows up once occasionally. I would advise adjusting your schedules, do not become too fatigued, learn to regulate the mood, don’t take on too much pressure. In this way, sleeping difficulties will self-correct.

If the obstacle of sleeping is stubborn, such as serious insomnia or continuous early awakenings and excessive dreaming, this points to more serious injuries. The best way is to look for a traditional Chinese doctor for treatment in combination with traditional Chinese medicine. Afterwards, one should pay attention to work and rest schedules, refrain from staying up late and sitting for long periods at a time, exercise actively, learn to cultivate the health. Persist like this for half a year in order to adjust back to normal.

Back in the day, I suffered quite seriously from excessive dreams and insomnia. Dreams were on a daily basis. Sometimes, I would have insomnia, it was very frustrating. Afterwards, I adjusted my working and resting schedule and learned to cultivate the health. It took more than a year before I could recover. The reason as to why it took over a year was because my damage was quite severe. This current year is marked by abstinence and health cultivation, I didn’t take any medicines and relied on myself. Of course, if the condition is serious, it is still best to seek out a relatively capable TCM doctor in combination with treatment of Chinese herbal medicine. The recovery may be speedier this way.

In order to allow for better recovery, it is a must to improve the quality of sleep. Many people are quite capable of eating, sleeping, and exercise and so they recover quickly. Some people are unable to sleep or sleep poorly, to recover will be comparably more difficult for these people. Sleep is like charging a cell phone. If the electricity cannot enter, how can recovery take place?

## Reboot while dawdling in bed and weekend relapse {-}

Lastly, let’s talk about breaking the reboot while dawdling in bed and weekend relapse:

Many brothers report that relapsing is made easier when one is procrastinating in bed. Also that whenever it’s the weekend there is a higher chance of relapse, while during weekdays everything is fine. Actually, I experienced both cases in prior years. This kind of problem is normally relatively common among students.

Through my years of research and case analysis, I’ve come to discover that relapses happen particularly often during a psychological state, this state is boredom.

While procrastinating in bed, it is very boring. Thoughts run wild while laying in bed, many people during this time like to sexually fantasize. Or during morning erection, one gazes at the length and the firmness of the penis, under this condition it is particularly easy to relapse. The correct approach is to not gaze at the morning wood. Let the thought rise and fall by itself, don’t gaze and don’t assist the thought, it will subside by itself.

When it comes to the weekend, people have relatively more free time, boredom will also appear more easily. Once parents have left the house or when we are shut inside our rooms, the devious mind comes online. Students do not yet have a strong determination, the understanding being not very deep. During boredom, the temptation demon jumps out, this is when it’s easy to relapse. Therefore, one must study rebooting articles and increase awareness and determination. Keep a high level of alertness at all times and do not let your guard down.

Once you have obtained enough determination through studying, you will no longer relapse during boredom. An upright and radiant character will be achieved and one will not commit any act alone which one will not commit in public. When the body is upright, we are not afraid of a skewed shadow. When the heart is upright, we will not be afraid of relapse due to boredom. Otherwise, when you are doing fine normally during class but become bored during the weekend, relapses will easily take place.

My advice is: Do not wander away from rebooting articles. Of course, we may develop a tiresome attitude towards studying these articles. I have mentioned this in my previous article: when you are fed up with rebooting articles, one must learn to overcome this attitude and maintain the enthusiastic attitude. You don’t have to look for new articles, it is adequate to repeatedly browse some of your favorite articles everyday. There is another choice, and that is to look at the cases from sufferers, these articles will serve as an alarm bell, it is the best warning. By looking at these cases everyday it will allow you to maintain the state of vigilance. Otherwise, whenever you grow tired of reading rebooting articles or become lax in your attitude, relapses will become easy. Remember at all cost!

In addition, those brothers who have a habit to procrastinate in bed must overcome this habit. To overcome it, one must be determined. Tell yourself that tomorrow morning I will get out of bed as soon as I wake up, under no circumstances will I dawdle in bed. The determination must be in proper place. When the mood of boredom comes up, one must learn to adjust the mentality. Allow one’s life to become enriched, the best form of enrichment is studying. The ancients have said that studying will cure *“stupidity”*, I think this is very reasonable. Not knowing comes from not studying. You can study rebooting articles, cases from sufferers, or topics of your interest. All in all, the goal is to enrich yourself.

## Concluding remarks {-}

Today I paid a visit to the D forums for roughly a minute, that place is indeed quite messy. Many youngsters are brainwashed by indulgence ideologies, really becoming trapped within. They are like the *“frog in the boiling pot”*, totally unaware of the might of nefarious wantonness. Wrong is taken to be right, very scary. Symptoms will sooner or later sort them out, I hope they will soon come to see the truth. Here I would like to pay my deepest respect towards brothers who are spreading the message of rebooting. Perhaps your dissemination may cause misunderstanding among people who don’t understand the truth. But for sure there will be people who will gain certain insights after reading your post, for sure some people will return.

The reason why many people do not understand rebooting is that they have not realized the seriousness of the harm. They take indulgence as granted because everybody is doing the same. In reality, everybody is incorrect, the error is boundless. Propagating rebooting is the same as telling the truth to everybody, letting them realize the harm and establishing the correct understanding. Otherwise, what awaits them is symptoms and the hospital. Furthermore, the entire quality of life will become greatly affected, this is because masturbation destroys the body and the mind.

The impression that D forum left me is like a polluted river. Rebooting, on the other hand, is like a clear spring. We are the product of our environment. Many people on the D forums are unaware that they have already been polluted. Like entering a room filled with irises and orchids, after a while, the scent cannot be smelled. Like entering a shop selling abalone, after a while the stink cannot be smelled. When a person has become comfortable in an environment, sensitivity and vigilance are lost. This is like living in a city for a long time and then going into the mountains for a while, one discovers that air can have such freshness and purity.

Many people say that we are living in a peaceful time, I do not agree with this assessment. There are 2 kinds of invasions, one occurs via waging wars and the other is a cultural invasion. Even a Western island nation can have a big impact in invading the Chinese culture while propagating restraint in their own country, vast quantities of degenerative material are being produced. This material is then being viewed by the young of other countries, weakening their bodily and mental strength.

At the same time, young people in China today lack beliefs, not to mention being totally incapable of self-control. Once masturbation has started, both the body and the mind easily run into issues. A country is made up of people, and so youth is where the hope lies. If we cannot resist the invasion of indulgent ideology, the fate of China is indeed worrying. Being descendants of the Yellow Emperor, we should propagate more virtue, help to awaken the people beside us. Sometimes a few sentences from you may have a life-changing effect on another person.
