# The issue of morning erection, leakiness, bowel movement and small testicle

## Morning erection {-}

In general, many brothers will pay attention to the issue of morning wood and take it as a sign of kidney qi recovery. Morning wood will be met with happiness while the lack of it will result in a heavy mood that lingers for the rest of the day. In reality, whether or not the body has recovered can be expressed through many different aspects. Take a look in the mirror, is there more spirit in the eyes? How is the complexion? How is the Spirit? The strength of the grip? Is there strength in the legs? Or if other uncomfortable symptoms are alleviated or have disappeared. These can all be taken as signs of recovery for the body. Morning wood is but one of many recovery signs.

As long as rebooting is persistent, morning wood will recover by itself. If you are only a teenager, then morning erection will be relatively quick to recover. If above 25 years old or the damage has been severe, then the recovery of morning erection will be relatively slow. Some brothers have been rebooting while doing health cultivation for over 200 days before experiencing the recovery of morning wood.

In my case, it took me over a year before morning erection was recovered because at the time I was already 27 years old. Over a decade of sexual debauchery had severely damaged my kidney qi, therefore it took over a year to recover. Although my morning wood is recovered, it is impossible to be on the same level compared to when I was a teenager. During which time my body was still developing, my appetite was strong and I ate good food. Back then the quality of the morning wood was high. If masturbation was not frequent, in a week there would be 5 morning erections. But this frequency only lasted for about 2 years or so during puberty. Afterwards, masturbation became frequent and morning wood less frequent.

Nowadays, I would have roughly 3 morning woods per week, sometimes with high quality, sometimes with normal quality. Now I eat a vegetarian diet 5 days each week, therefore, 3 morning woods per week is not so bad. Previously, I had a slight orientation towards premature ejaculation and impotence. Normally, people with these two orientations will have a difficult time to recover their morning erections, needing at least half a year or more.

Now I don’t really pay attention to morning wood, it is all for the best. If it is absent that is fine because the degree of recovery is not expressed through morning erection alone. In other areas I’m recovering very well, there are also many factors that affect morning wood, such as:

-   Dietary factor: the amount of kidney supplement food intake
    
-   Exercise factor: moderate aerobic and strength exercise is helpful towards the recovery of morning woods
    
-   Mood factor: negative mood will affect morning wood, such as anger and pressure
    
-   Age factor: morning wood comes easier during puberty, as the age increases, morning wood becomes less frequent
    
-   Constitutional factor: people with a naturally good constitution will experience morning wood more easily
    
-   Illness factor: people free from latent illnesses will experience morning wood more easily
    
-   Indulgence duration factor: normally, morning erection will disappear for those people with 5+ years of indulgence history
    
-   Seasonal factor: the frequency and intensity of morning wood varies with the seasons
    
-   Monthly timing factor: the yang qi in the body differs during different times within a given month, the quality of the morning wood will also vary
    
-   Withholding urine factor: sometimes the withholding of urine will induce the onset of morning wood
    
-   Fatigue factor: fatigue will damage the kidney qi, morning wood will disappear more easily
    
-   Sleep factor: people with a high quality of sleep will experience morning wood more easily
    
-   Frequent emission factor: following frequent nocturnal emission, morning wood will vanish more easily
    
-   Withdrawal symptom factor: there will be a flatline period following the onset of rebooting, morning wood will easily become absent, by persisting with rebooting it will then return
    
-   Whether or not there are other unhealthy lifestyle habits, such as staying up late, sitting for long durations, smoking. These will all take a toll on the kidney qi and affect morning wood.
    

Morning wood refers to an erection without fantasizing. If fantasizing is involved then it is not morning wood, it is induced by your thoughts. Morning erection is really quite dangerous, why is it dangerous? Ordinary people are not aware of this principle. This is because many people have a shallow level of determination, they become very excited when they have morning wood and use the opportunity to touch the penis. This touching seals the fate, one unconsciously starts to masturbate again.

Breaking the reboot due to morning wood during the weekend is very common. When I have a morning wood nowadays, I do not care, nor do I look or touch it, letting it rise and fall by itself. If you care a great deal about morning erection and if you are not careful, one will tread onto the evil path. When you don’t pay attention to it, it will subside by itself and will not lead to breaking the reboot. Many people have the habit of procrastinating in bed. If in addition to procrastination there is morning wood, then it is very easy to break the reboot. Remember at all cost!

Many people mention that their morning erection shows up sporadically, this, in reality, is very normal. Did you think that you would remain in puberty forever? Even if you are in puberty, to have morning wood daily is also very difficult. This is due to the many factors that affect it. It is impossible to have a morning erection everyday, 365 days of the year, that is not realistic. The reason why morning wood shows up sporadically has an intricate relationship with factors such as seasonality, lifestyle habits, diet, and age.

Normally, people living on a nutritious diet with a strong ability for digestion and absorption have an easier time achieving morning erections. Previously when I was on a meat-heavy diet, morning wood was more frequent during that period. Now I eat a vegetable-based diet for 5 days a week, morning wood has become lesser in comparison. But my mind has quieted down a lot, evil thoughts do not easily arise. It is good to eat a vegetarian diet while rebooting, this is beneficial to control the desires. Eating lots of meat will help to fuel the desire, if the determination is shallow then relapse will come very easily. It is a personal choice to eat a vegetarian diet, it will depend on the acceptance level of the individual. I would recommend all brothers to start with reducing the meat in the diet, I’m also very much in favor of a purely vegetarian diet.

## Leakiness {-}

Below let’s discuss the issue of leakiness:

Leakiness is characterized as the leakage of semen - due to long term indulgence and weakened kidney qi - and can occur under many circumstances such as:

-   Leakage after urination
    
-   Leakage after bowel movement
    
-   Leakage while on the phone with the girlfriend
    
-   Semen slippage  _(Translator’s note: semen slippage is the leaking of semen while awake as opposed to nocturnal emission which occurs during sleep)_
    

Everyone will better understand the kind of leakage issues if I illustrate them with an example: It is essentially a worn out water tap, it is no longer possible  to keep it shut, it will always leak. The situation of leakage following urination is in fact very common. This, in reality, is a sign that the kidney qi is not consolidated. Leakage following bowel movement is even more common especially at the beginning of a reboot.

Furthermore, quite a few brothers have reported that leakage during a phone conversation with the girlfriend, even when the topic of the conversation was not sensitive. This, in fact, is related to latent conditional reflexes. Brothers with girlfriends have a harder time rebooting. Therefore, it is best to have a talk with her, try to avoid having premarital sex while at the same time increase one’s own heart cultivation, have a good handle on the degree of association.

Many brothers also suffer from semen slippage. If you have a slippage occasionally that is not a cause to worry, but if it happens continuously then one needs to make haste to seek treatment.

In addition, I recommend doing more kidney strengthening exercise. Normally, by persisting in rebooting, health cultivation and active exercising, leakage following urination and bowel movement will cease by itself. I have previously encountered leakage following urination and bowel movement. Afterwards, I persisted in performing kidney strengthening exercises, this kind of situation will now show up extremely rarely.

Of course, the issue of leakages is not limited to the above 4 categories, sexual fantasizing and nervousness will, for example, induce leakages. Even if your kidney qi is abundant but you are deeply immersed in sexual fantasizing, leakages will also occur. Therefore, one needs to resolutely put a stop to sexual fantasizing and achieve a state of cutting out a thought as it arises. In addition, study more rebooting articles to increase one’s realization and determination. Only by doing this do we have the hope of truly ridding ourselves of the evil habit of masturbation.

## Bowel movement

Let’s talk about the bowel movement issue:

The bowel movement issue will frequently make an appearance on the rebooting forums, because according to TCM: 
*the kidneys govern both urination and bowel movement*. Weakened kidneys give rise to problems in both areas. We do not need to mention more regarding urination issues, brothers with prostatitis have ample experience in this I believe.

Kidney deficiency induced issues can be grouped into 2 categories:

-   Diarrhea or unshaped stool
-   Frequent bowel movements

Many factors play a role in causing diarrhea and frequent bowel movements, kidney deficiency being one factor among them. You may remember that stool quality was very good when we were children, firstly the color was good and secondly, the shape was good. Children have an abundance of yang qi, their child body has not yet been damaged. In the absence of other illnesses, the digestion and absorption ability is often very good.

Things are different once we become older. Firstly we indulge via masturbation, secondly, we intake more cold beverages and spicy food, or the dietary habits may be poor, pigging out on food and drink and so on. All of these lead to obstacles for the smooth functioning of the digestive system, screenings in the hospital will not reveal anything, only the functioning has become disorderly. Children will not have issues with taking some cold beverages because they have an abundance of yang qi which enables transformation. After sexual indulgences it is no longer the same. Upon taking cold beverages, disorders may easily appear in the stomach and intestines. Therefore, it is important to mind the diet and not yearn for cold and spicy food.

If you are troubled by diarrhea or frequent bowel movements, the best way would be to seek medical treatment and then to combine it with rebooting, health cultivation, active exercises, keeping a mindful diet, and slowly recuperate. I have experienced both the issue of diarrhea and frequent bowel movement. My frequent bowel movements started after I turned 19 and it troubled me for over 2 years. It was induced precisely due to sexual indulgence and cold beverages. After I turned 26, my diarrhea started again which was induced by exposure to AC, pigging out on food and drinks and sexual indulgences. After I started to reboot, I frequently employed moxibustion and applied it on the Zusanli and the Shenque acupoints and slowly recuperated, it took over 1 year of time.

## Small testicle

Lastly let’s talk about the issue of a small testicle:

The small testicle and the shrunken testicle issue appears commonly among brothers, testicle issues induced by masturbation are normally found to be:

-   Drooping testicles, not shrunken
-   Shrunken testicles, testicles have become smaller
-   Moist testicles
-   Spermatic cord
-   Scrotum eczema
-   Swollen scrotum
-   Itching scrotum
-   Painful testicles
-   Testicle inflammation
-   Testicle cyst
-   Cryptorchidism
-   Other illnesses

Brothers suffering from shrunken testicles should seek treatment at the hospital in order to diagnose the seriousness of the condition.

Shrunken testicles point to the condition of shrunken and atrophied testicles, it is either on one side or on both sides of the testicles. The characteristic is the symptom of small and soft testicles. In the majority of the cases, it will lead to infertility. It is often aggravated by mumps or external injuries, some may arise from prenatal conditions. Oftentimes, it is caused by a deficiency in the kidneys or caused by damage from pathogeny (TCM). Maldevelopment of the testicles due to prenatal conditions is difficult to heal from. Shrunken testicles from postnatal causes also require patience to heal, certain results can be achieved via TCM treatment.

The evil habit of masturbation induces kidney deficiency, continued abuse leads to shrunken testicles, this is a common phenomenon among brothers. Therefore, as soon as the symptom of shrunken testicles appears, treat it without delay. Secondly, one should complement the treatment with rebooting and health cultivation. Once kidney qi has been cultivated into abundance there is hope of returning to normal.

Some brothers will inquire about the size issue of one’s testicles not being identical in size. Normally among ordinary people, the size of the testicles are not identical, but if the size difference is very large then it is best to check up on it. If the difference is small then there is no need to worry.
