# Different types of relapse, the mystery of shooting distance, the evil fruit of masturbating twice in a row

## Foreword

Recently there has been a thread in the forums:  _[merely rebooting is not enough, herein lies the only road towards recovery for the essence injured]_. Quite a few brothers asked me whether or not the words of the Silent Sun  _(Translator’s note: pen name of the thread starter)_  were true. After they read the article they became anxious about the statement therein that recovery isn’t possible without silent meditation. I have looked at the comment by Silent Sun, his recommendation of “Yinshizi silent meditation method” is very good. Meditation is indeed a wonderful way of replenishing the original qi. Of course, there are many ways to meditate and many things to pay attention to. I meditate everyday but the method that I learned is the Nan Huai-Chin silent meditation. Meditation is indeed very helpful towards the recovery of the body during rebooting, but it is not the only way and it is not suitable for everyone. I have talked with numerous anxiety patients, and they will have a headache whenever  they sit down for meditation. To them I recommended the standing horse-stance health cultivation method and the improvement of their health followed.

Some people like to meditate while others like to hold the horse-stance while standing, the Eight Brocade and the Six-Character Formula exercises, some people would practice Taiji boxing or the Yijin Jing. There are many Chinese health cultivation methods, one may find a method that suits oneself. As to  _“exercising is nonsense”_  by the Silent Sun, I dare not blindly agree.

Although, it is mentioned in TCM that fatigue exhausts the qi it is also mentioned that movement raises the yang qi. TCM does not at all oppose exercising but advocates exercising in moderation. Blindly meditating is not necessarily the best road towards recovery, the movement should be combined with stillness. Huatuo’s  _(Translator’s note: the legendary physician from the Three Kingdoms era)_  Five Animal Play has the purpose of setting the person in motion, but he didn’t tell everyone to lift stone locks  _(Translator’s note: basically dumbbells made of stone which made their appearance in the army camps of Tang dynasty)_. The intensity and the style of movement in Huatuo’s Five Animal Play are beneficial to the bodily health.

Huatuo’s famous remark:  _“The human body desires to labor, but should be kept in moderation. When the blood circulates in the blood vessels, illnesses will not be born. Like that of the door hinge which becomes aged when it is frozen”_.

This remark by Huatuo is telling us that there are rules governing exercise: to exercise, but not overexert. When the body has been weakened, extra attention should be placed on the intensity of the exercise. I believe that any famous Chinese traditional physician will not be against exercising,  but what they will oppose is over-exercising. Even for a Taoist priest, health cultivation is not solely based on meditation. Many well known Taoist priests practice martial arts in order to combine stillness and movement, which is more advantageous to the way of health cultivation.

Silent Sun said  _“merely rebooting is useless”_, I’m rather inclined to agree with this statement because rebooting is the foundation, but health cultivation is the building of the house. To only reboot is indeed far from enough, one must learn the way of health cultivation and establish one’s own awareness around it. The process of recovery will benefit from adopting this approach. The silent meditation method recommended by Silent Sun is, in reality, one of the ways of health cultivation. This way isn’t bad, everyone may try to practice it. After having practiced it you will know its results and whether or not it suits you. Of course, beware of the methods which are prone to lead the practitioner off course, or else problems may arise as a result of practicing.

How to improve the quality and the speed of recovery is indeed an important question, but more important is the need to reboot thoroughly. This is the key. Otherwise all talk about recovery results in nothing. This is like taking about Chinese traditional medicine while still masturbating, *"replenishment in the above is met with leakage in the below"*, there is no way to truly recover.

There are many ways to recover the body, silent meditation is but one of those ways. A while ago, the Tudou forum owner recommended the method of repenting which was very good. It is through repentance that he has recovered his health. There are many ways to do it, one may choose a suitable method. Those with an inclination towards Buddhism may try repentance. In addition, besides the mentioned health cultivation practices, active aerobic exercises are extremely beneficial to the recovery process, such as slow jogs or fast walks.

I believe that the original intention of Silent Sun is good. Most of his views are without faults. Only that his attitude was a little overbearing, many people may have a hard time accepting it due to this. He wants the best for everyone. By switching to a more peaceful approach, perhaps more people will have an easier time accepting his words.

Towards  Silent Sun, I express my gratitude, his heart is pure and I hope that he will continue to help everyone. The atmosphere here is not hostile but is conducive to exchanges, and through it, everyone may be promoted.

Let’s return to the main topic below:

This season is about the types of relapses, the mystery regarding shooting distance, the evil fruit from consecutive masturbation sessions. We will be discussing these topics thoroughly below:

## Types of relapse

Relapses happen daily. After a relapse, one is often very disheartened, this is not hard to see. In the beginning, one is full of ambition with a tremendous amount of determination. After awhile, this determination starts to sway. After numerous relapses, we start to lose confidence in ourselves. Body symptoms tell you to stop indulging, by indulging further the body is finished, but the addiction tells you to keep masturbating. The vast majority of brothers are firmly controlled by the addiction, like a stringed doll and become a slave to desires, losing their free will, aware of the error but unable to stop, struggling bitterly in the vicious cycle.

It is not scary to relapse, but it is scarier to not study. Without it, the level of awareness and determination will not increase. Brute force rebooting without studying will surely result in failure! Some brothers will ask, is anyone able to completely reboot on the first try? To tell the truth, out of the thousands of brothers that I came across, I have yet to see anyone succeeding on their first try. Everybody has repeatedly relapsed, constantly learning from their past mistakes, constantly studying rebooting articles to increase their awareness and determination, and slowly succeeding in this fashion.

Some people have claimed to have seen people succeeding on their first try, actually, the definition of rebooting in one go is a bit vague. Is it to have completely rebooted once awareness has been attained or managing to completely reboot in the first attempt? I belong to the former category and I have not relapsed since that attempt. However, it was not my first attempt, previously I have relapsed countless times.

The first time I thought to reboot was back in middle school. At the time, I thought the act of masturbation was very filthy. My constitution would clearly take a hit after masturbation. I wanted to reboot during my teenage years but didn’t have any materials to read from or people to guide me, neither did I have the awareness to study rebooting articles. I only forced myself to reboot in a brute force fashion with the result being endless relapses. I think that most people have tried to reboot during their teenage years. This is because humans have a natural rebooting instinct, the body will advise you not to indulge any further.

When trying to reboot for the first time, there was a lack of experience in many areas. One belongs to the rookie stage. First of all, one lacks the knowledge. Secondly, one lacks the awareness. Under such circumstances, wanting to succeed on the first try is a fantasy story. Let me illustrate with an example: Have a person who has never driven a car, drive a car for the first time, what is the result? The result is surely swivelling left and right and maybe even crashing the car.

Rebooting is like learning to drive a car, one must master a complete set of theory and methodologies, the rest relies on experience. In this way, one may succeed in rebooting. You will ask if there is anyone in this world who is able to successfully reboot on the first try, even though that person may exist, he will be one in a thousand. The person must also have a great accumulation of virtue with the condition of coming in to contact with a vast number of rebooting articles, good aptitude in studying, exceedingly high level of awareness. Like skipping a grade in school while others have trouble to understand given a decade of time, he reaches understanding in a month. This kind of person appears seldom and is a rebooting genius. One in a thousand is not an overstatement, even one in ten thousand.

Rebooting must be professional. In this season, I have summarized a few relapse categories, everyone may refer to them in order to alert oneself. The saying that  _“knowing yourself and your enemy, one hundred battles will result in one hundred victories”_ will be true in this case. Once you know about the types of relapses, you will then try to maintain vigilance. It is like knowing the trick of the swindler, you will not fall for the trick easily because you are aware of the trick. Only in this case, it is not a trick for your money, but your essence.

-   **Mood relapse**: boredom mood, anger or depressed mood, agitated mood, fed up mood, etc..  
    
-   **Doubting relapse**: doubt sways the thoughts, the result is a relapse
-   **Enticing relapse**: pictures or videos, even pornographic videos
-   **Procrastination in bed relapse**: very commonly seen, must be corrected
-   **Pressure relapse**: pressures from different sources
-   **Sexual fantasizing relapse**: normally, fantasizing is the prelude to relapse, this includes recalling memories and illusions
-   **Letting down the guard relapse**: thinking that one has succeeded, in actuality relapse comes once the guard is down
-   **Ecstatic relapse**: when one is ecstatic it is easy to relapse, being beside oneself with joy
-   **Testing determination relapse**: do not test your determination at all cost
-   **Morning wood relapse**: touching the penis when having morning wood and relapsing from there
-   **Testing sexual function relapse**: especially for premature ejaculation and impotent patients, relapse follows trying
-   **Agitated relapse**: negatively influenced by people, going to filthy places
-   **Alcohol relapse**: alcohol is the matchmaker for sex
-   **Nocturnal emission relapse**: nocturnal emissions give rise to swayings of the thought, relapses occur from there
-   **Weekend relapse**: bored while being alone over the weekend, the temptation demon will easily spring out
-   **Tonic relapse**: taking too much tonic, does not emphasize heart cultivation, relapses will be easy
-   **Eating meat relapse**: eating too much meat without emphasizing heart cultivation, desires are promoted and is followed by relapse
-   **Harmlessness theory relapse**: after looking at harmlessness theories one is prone to relapse
-   **Girlfriend relapse**: having a girlfriend places a higher requirement on one’s determination, relapse is made easy
-   **Wife relapse**: having a wife also places a high requirement on one’s determination
-   **Habitual relapse**: when relapses become a habit, the resulting momentum is strong with fearful consequences
-   **Holiday relapse**: such as summer or winter holiday with more free time, it is easier to lose control
-   **Evil ways relapse**: no matter if it is PC muscle restriction or so-called penis enlargement methods, these easily lead to relapses

## The mystery of shooting distance

Below let’s talk about the mystery of shooting distance:

Shooting distance is the distance of ejaculation. Many brothers have reported that when they first started to masturbate, the shooting distance was very far. Afterwards, the distance became shorter and shorter, semen would run down along the penis, clearly indicating the lack of strength and inadequate pressure. This, in reality, is an expression of weakened kidney qi.

In semen, we should first look for the color, the quantity, the concentration and the shooting distance. The further the shooting distance the more abundant is the kidney qi. Without power behind the arrow, its flight will naturally not be very far. Only by accumulating enough kidney qi will the shooting distance increase. Whenever the shooting distance is shortened or the semen is flowing downwards, this is your body giving you a signal, telling you that your kidney qi is inadequate and to stop indulgences. If you are unable to interpret the signal and instead stubbornly persist, it is like the saying of not shedding tears until seeing the coffin.

Many people only see the semen but they miss the  _“archer”_  behind the shot, who is no longer capable. Semen replenishes relatively quickly, rest for a few days, eat well and it will recover. But for the  _“archer”_  to recover, that is a very slow process. It may require several months and even longer to recover the original qi. Therefore, do not restrict your line of sight on semen alone, but look to the  _“archer”_. If the *'archer'* is already incapable and cannot shoot far, it is pointing to the need to reboot and to cease indulgence, to cultivate the health. Otherwise, the only thing that awaits you is symptoms and the hospital.

That  _“archer”_  is the kidney qi. Since it is already incapable of shooting long distances and is tired, let it shoot no more, let it have a rest, or else the accumulation will give rise to illnesses. Remember at all cost!

## Masturbating twice in a row

Lastly, let’s talk about the evil karma from masturbating twice in a row:

If you go visit the forums for autonomic disorders, then you will know the patient called sg552. His illness was induced by long-term sitting for long durations and masturbating twice consecutively, that’s when the feeling of nearing death appeared. Masturbating 2 times consecutively is really too damaging to the body. It has been stated in TCM long ago:  _desire should not be strong_. In [Thousand Golden Prescriptions] it is mentioned:  _strong force bestows leakage, becoming a strain_. Especially for consecutive masturbation sessions, this is truly a taboo. The emergence of orientation towards prostatitis and premature ejaculation easily arises following 2 in a row masturbation sessions. This is actually induced by the human weakness of greed towards desire. In the pursuit to satisfy oneself, the results are to actually harm oneself!

The reason as to why many people masturbate twice in a row is because: the first time went too quick and was not intense enough. It is precisely this greed of desire that enables their self-destruction. These kinds of examples of self-destruction are too many. We must keep in mind the lessons from TCM on the destructiveness of a strong desire, refrain from doing stupid things. If you are unaware of this principle then you are both ignorant and fearless, the result being making yourself miserable. If you know this principle but still indulge, then you are seeking annihilation! Many people are unable to conquer their addictions and so they commit these kinds of errors, like wrapped under a spell, repeating only after they have relapsed. Therefore, we must nip it in the bud by properly managing our thoughts and puttin an end to sexual fantasizing. Otherwise when the flame has sprung up, it will no longer be within your control.

## Concluding remarks

Summer approaches and quite a few brothers are reporting increased hair loss, they are anxious over this. In reality, the factors that induce hair loss are many, seasonal changes being one of them. Lately, I lose up to 20 strands of hair per day compared to up to 5 strands of hair previously. This is actually caused by the change of the seasons and not by masturbation. So in this case, everybody should have a clear understanding, or else the confidence is prone to be swayed and will turn into the act of masturbation. Among those factors that induce relapse I have talked about the  _“doubt factor of relapse”_. If you have doubt in your heart, the chances of relapse will be great.

Normally during summer, the secretion of sweat and oil is exuberant. This combined with stronger UV rays will cause damage to the hair. In this way, we may see more cases of hair loss, this is not only limited to humans. If you observe animals such as pet dogs, they also go undergo heavy hair loss during summer.

One brother puts it very neatly, rebooting is a process of system engineering. One must carry out rebooting as professionally as able, increase one’s knowledge to the maximum, becoming an insider in rebooting. By neglecting to study, one is always an outsider, remaining on the level of a rookie, to successfully reboot will then become very difficult. When everybody has gained the requisite awareness for studying, after a while, you will notice that your awareness and determination have both increased. As long as one continues to study, complete understanding will not be far away. Complete understanding together with maintained vigilance equals a completely successful reboot. Fight on!
