# Stomach pain following masturbation, fantization induced illnesses, drooping testicles

## Foreword

Recently I saw a report by a brother, his relapse was due to looking at material with suggestive content.

In reality, this kind of relapse is due to temptation. Many brothers have previously reported similar circumstances. Although some brothers have already started to reboot, when they see written material regarding the sexes on the magazines, suddenly their interests are aroused. The result is that their vigilance is relaxed as they keep reading leading to breaking the reboot. Some other brothers claim that they do not search for pornographic images but only innocent looking girls. They search for girls with nice figures without going into nudity. These kinds of brothers actually relapse very easily, because they are still addicted to women, although they search for innocent pictures. How can a person not get his shoes wet if he often takes a stroll along the river banks. Like the Buddhist saying goes:  _“by clinging to outer appearances one is prone to be obsessed”_.

Moreover, there are issues with both the avatar and the signature of many brothers. Half the battle is already lost before they try to reboot because they are not determined enough! To reboot thoroughly, one must cut out thoroughly, not only should one abstain from looking at pornographic content, but even all suggestive material which turns out to be even more dangerous in this regard because of its subtlety. The level of vigilance must be raised. The vigilance is maintained every day during the reboot, manage your heart well and conquer the obsession.

We enter into the main material below:

In this season, we will talk about belly ache following masturbation, illnesses induced by sexual fantasizing and drooping testicles in detail:

## Stomach pain following masturbation

Threads regarding stomach pain following masturbation do not appear everyday, but do show up from time to time. I have experienced stomach pain following masturbation previously. When it appears, it is usually a sign of prostatitis or varicocele. The pain will usually arrive following masturbation or the next day. If the pain is serious and does not subside, one is advised to seek treatment immediately. If the pain is not that serious but bearable, I still recommend to get it checked out at the hospital, checking the prostatic fluid and doing a supersonic scan on the testicles in order to gauge the seriousness of the condition, while at the same time providing a warning to oneself.

Although many people suffer from stomach pain because they are able to bear it, they postpone the visit to the hospital for many years. Because post-ejaculation symptoms tend to slowly subside after a couple days of rest, these people take it lightly and not worry about it, only to visit the hospital when symptoms have become serious. According to my knowledge, many brothers can already feel the worm-shaped lumps on their testicles but are unwilling to go to the hospital. Students especially are often afraid of letting their parents finding out.

With the onset of symptoms, one should become more aware. Besides the human weakness of  _“not shedding tears before seeing the coffin”_, there is the weakness of  _“forgetting the pain after healed injury”_. Many people, after encountering symptoms, take it easy for a while. After a dozen days they think they are fine and then continue to masturbate. On return of the symptoms, they again start to reboot, constantly going back and forth in this vicious cycle. What is the result? Bodily symptoms grows ever numerous, a young person with a body full of symptoms, feeling uncomfortable from place to place and turning uglier in the process.

Even when there are no problems, the expression one gives out to other people is one of decadent demeanor, a decadent look where the gaze lacks vitality. I remember that one brother went to an interview and failed it. He blamed the cause on masturbation which I think makes some sense. If he was full of energy, went to the interview feeling confident and radiant, it’s very possible that he would have landed the job. The interviewer, besides looking at your abilities, automatically perceives other things, which is why first impressions are very very important. A person going to an interview lacking Spirit and confidence is prone to suffer disappointment from failure. It is already an undisputed reality that masturbation causes feelings of inferiority because one lacks confidence while under kidney deficiency, there is no way to put forth your best face. When carrying around a decadent and strengthless look, it is very easy to leave an unfavorable impression on the interviewer, the impression metric will then suffer a big hit.

I have mentioned prostatitis and varicocele in my previous articles. Both of these diseases will induce infertility and the quality of the sperm. Therefore, one should pay attention to these illnesses early on, otherwise in the future, it will be too late for regrets. I remember that another brother had varicocele and lost his fertility, all his expenses in diagnosing, medication and surgeries cost more than 50,000 yuan. If he had woken up early and became aware of the evil fruits of masturbation, the consequences would not have been as serious. These are all live cases, live lessons, everybody should commit these lessons to heart in order to take preventive measures and to prevent making the same mistake.

## Illnesses caused by sexual fantization

Below we will talk about illnesses that are caused by sexual fantasizing:

Sexual fantasizing can definitely cause illnesses, maybe this is the first time that many brothers are hearing this. Actually, it has been recorded long ago in the TCM medical cases:  _“when the heart sways, essence leaves”_. Sexual fantasizing is, in reality, injuring the essence invisibly, it is very damaging to the body. Some brothers say that the expelled liquid during fantasizing is from the prostate and is not semen.

Here I will correct many brothers in their misconception:

Prostatic fluid is actually an important constituent of the seminal fluid, taking up 15-30% of its share. By losing prostatic fluid, one is losing semen, only that you are not losing the semen in all of its constituents, only part of the total. Although you have not ejaculated during fantasizing, essence is still being lost. The damage to the body from the loss of prostatic fluid should therefore not be underestimated.

Some brothers have reported that by looking but not touching and then looking in the mirror, they find out that their Spirit has immediately become sluggish. Some brothers even report belly aches following watching but not masturbating. Other brothers report feeling unwell the day after they have lost prostatic fluid, legs become soft and the body feels out of strength, even the feeling of soreness or pain in the waist.

It is therefore important that everybody keep an eye on fantasies while undergoing rebooting, one must keep it under control. Sexual fantasizing is a big checkpoint in rebooting. Many people are unable to pass this checkpoint, although they have managed to not masturbate, they cannot put a stop to fantasizing. Engaging in fantasizing is very unfavorable to the recovery process and easily leads to breaking the reboot.

As to how to put a stop to fantization, I have treated this topic specifically in season 17, those brothers who are unable to put a stop to fantasizing may go and have a look. One must learn to cease fantasizing. Once fantasizing has been conquered, the number of your PMO free days will multiply in number, reaching the 100 day mark will be an easy task. But if fantasizing cannot be kept under check, perhaps even 1 month will be hard to reach.

There is another situation of prostatic fluid leaking which is relatively serious, and that is leaking towards the end of urination or a bowel movement. This can be resolved by persistently practising kidney strengthening exercises. The result of which will be quite good. After having practised for a while, you will notice that leakage will no longer occur in conjunction with passing stool or urination.

## Drooping testicles

Let’s talk about the issue of drooping testicles:

Drooping testis are commonly seen among brothers, and easily arise when there has been overindulgence. Usually, two kinds of problems occur following overindulgence: the first is excessive drooping of the testis, the other is abnormal tightening of the testis, able to shrink to the size of a quail egg, or even shrink into the abdomen. The latter is rare, the more common problem that most brothers run into is the drooping testis issue.

There’s a saying called  _“shrink like a child”_. If a young boy is healthy then his testis will be very tight while looking very full. This is actually an expression of abundant kidney qi. His boy body has not been stained, nor does he engage in sexual fantasies. In this way, the quality of his testis is very good. Many brothers say  _“heat expands, cold shrinks”_. In reality, this change on the testis is induced by outside stimuli and has little to do with kidney qi. Of course, if the drooping is caused by severe depletion of kidney qi, then even cold stimuli from the outside will not cause shrinkage of the testis.

Drooping of the testicles will normally occur for all adult men. The body has after all suffered leakages, this is fine as long as the droopiness is not excessive. According to my own practices, lowering the head doing kidney strengthening exercises while consciously lifting the anus and the testis, will have a tightening effect on the testis and will have a meaningful healing effect for excessive testis droopiness. Of course, one does not have to combine the above exercises, lifting of the anus may be performed while standing or sitting. It so happens that I have combined kidney strengthening exercises with the anus lifting exercise because by doing so I felt an improvement in the results, the shrinkage will be more proper so to speak.

Nowadays, my testis are relatively tight most of the time on given day, they no longer droop the way they used to when I was sexually indulging. During those times, the testis would be exposed outside of the underwear and now it is relatively tight shrunken and full.

## Afterword

In the forums, there are many brothers reporting a slow recovery while rebooting. Some brothers have been rebooting for 7 months and still, their health is bad, some have even been rebooting for 1 year with the same results. Today, I’ve seen somebody who’s been rebooting for 2 years without much improvement in their health. This brother suffers from frequent nocturnal emissions, 8 times per month. How can the body recover given such frequent emissions? TCM:  _“long-term emissions injure all the Eight extra meridians”_. Nocturnal emissions are also very damaging to the body. During reboot the number of emissions are controlled. Try to keep them within 3 times/month but preferably once/month, this will be beneficial to the recovery process.

During reboot we must pass through 2 big levels:  
- The frequent emission level  
- The sexual fantasizing level, fantasizing also greatly damages kidney essence

In addition, pay attention to health cultivation. Merely rebooting is not enough, rebooting is the foundation, health cultivation is building the house on top. The contents of health cultivation are quite broad, one needs to study them constantly. During reboot, one must establish healthy living habits, do not stay up late, do not sit for long periods at a time or gaze for long periods at a time, do not overexert, sleep and eat early, exercise actively etc. All of these together form health cultivation. By constantly studying health cultivation knowledge, the awareness of cultivating the health will  increase, this then will be beneficial to the recovery process. Otherwise, to only reboot and ignore health cultivation, recovery will be truly very difficult, this especially applies to heavily depleted brothers.
