# Be a owner of pure frequency

## Sending out the waves of thought

The 6th Patriarch Huineng (Translator’s note: Huineng is the 6th Patriarch of the Chinese Chan school of Buddhism, the predecessor of Zen Buddhism) took up the mantle from the 5th Patriarch Hongren, came to the Buddhist temple Faxing in Guangzhou in order to spread Buddhist teachings. Master Yinzong, the abbot in charge at the Faxing temple was reading the Buddhist texts at the time. The banners moved as the wind blew, and so he asked: “Is it the wind or the banner that is moving?” Among the disciples, some answered it was the wind that is moving, others said that the banner is moving. Huineng approached, closed his palms and said: “It is not the wind nor the banner that moves, but the heart of the benevolent one”.

“All matter is a phenomenon of vibration, everything is illusion. In the universe, there is only field and matter. Actually, there is the only field. Matter is but a place with a particularly intense field.”

— Albert Einstein (Translator’s note: If the original English quotations from Einstein to the above text is to be found somewhere, I have yet to find them. This quote does not seem to be among the more popular ones circulating on the internet)

“All things and their produced effects is made of vibration, there is no existence of matter, all material include vibration.”

— Max Planck

“This world is the hologram of the consciousness, the reality is an illusion, it exists in our mind as a holographic mirage.”

— David Icke

“Objective reality does not really exist. Despite that the universe looks concrete and solid, the universe is actually an illusion, a gigantic and richly detailed hologram.”

— David Bohm

All appearances is false.

[Diamond Sutra]

(Translator’s note: Please allow for errors in the translation of the above quotes. If something feels or sounds off to you, consider consulting the source for a more accurate communication)

A thought is a vibration of energy. The foundation of the universe is a vibrating wave-like information field, while thoughts are the vibrating wave-like information. As long as there is vibration, there will be the product of illusion. You giving rise to a thought is the same as sending out a wave of information. Every kind of thought will carry with it its own determined vibration. The universe is a world of frequencies. As children we were all holders of pure frequencies, our hearts were pure and beautiful, clean and clear. Before puberty, thoughts of nefarious wantonness will rarely arise. Everyday during those times, we were enjoying the happiness of purity, only that we didn’t know to treasure it. That kind of great joy was fleeting, once lost it is hard to regain it.

Ever since becoming addicted to the evil habit of masturbation, we have changed. Our spirit become vile and dirty, we are broadcasting thoughts of nefarious wantonness daily. We have already come to be polluted, becoming unbearably dirty, as if going from a clear stream to a stinking river. Not only are other people disgusted by us, we disgust ourselves. Is this our previous pure selves? As the spirit loses its degree of purity, what follows is sorrow and decadence. Once the level of purity has been restored, the great beautiful joy of purity can be regained once again.

If we are to cast a stone into the water, outwards ripples will form on the surface of the water. Big stones will form big ripples, small stones form small ripples. No matter the size of the ripples, both can be simultaneously carried out on the surface of the water. Our thought ripple is also like that, everyone is sending out their own waveform of information. If you are sending out information waves of nefarious wantonness, then the decoded reality thereof will be distorted and painful. Scientists say everything is vibrating. The 6th Patriarch, Master Huineng said, the heart of the benevolent one moves! In reality, the fundament is that your thought is moving, as long as it’s moving, the holographic mirage of the material world will manifest. Just like when you are sleeping, as long as thoughts are moving, there will be dream scenes. The essence is the thought that you broadcast, the condition is born of the mind. The frequency of your broadcast thought determines the scenery of your life.

Master Empty Cloud once returned to his thatched hut from the monastery, halfway towards the destination the day becomes dark. However, no thoughts arose from him, he was not aware of the darkness, to him it was still day and the road is seen clearly. On the way he ran into two monks, one of the monks held a lantern, the monk walked up to him and said: “Empty Master, it is so dark, why do you not carry a light?” When the old monk heard this, the day immediately become dark. For the person without a distracting thought, the day is light. Once the discriminating tendency arises, one returns to ignorance, darkness fills everything in an instant.

This case sheds light on a fact, that is: all ways arises from the mind!

The holy person: All dharma comes from the mind, all dharma is extinguished by the mind. All follow from your mind, kindness and wickedness also follow from your mind, so does heaven and hell follow from your mind.

## Changing your frequency

“Thought or mentality is a magnet, like attracts like is the rule. Indeed it is so, a mentality will attract the quality of nature that correlate to that of its own.”

— Charles Haanel

A string of intentions form a thought, a thought is magnetic and carries with it a certain frequency. When you are thinking, those thoughts will be broadcasted out into space. They will act like magnets and attract towards it all things of similar frequency. So the saying goes that birds of the same feather flock together, the same applies to objects. Our thoughts will attract contents of similar frequency, just like when we watch the TV where every channel has its own frequency. When switched to a particular frequency, we will be able to see images on the image screen. We select frequencies by changing channels, then we are able to see the images that belong to that channel. If we want to see different TV images, then we will need to switch the channel, tuning into a new frequency. Radios works in a similar fashion, whatever channel we want to listen to can be achieved by tuning into the channel, different frequencies correspond to different contents.

Everyone give this a thought: if a person is constantly broadcasting thoughts of nefarious wantonness, what would the result be? The evil intentions will attract contents that correspond to its frequency, the nature of such thoughts is often filled with pain and horror. The originator of all evil practices starts with the thought that you send out! The human body is a broadcasting station while at the same time functions as a receiver. Different thoughts correspond to different frequencies. You create worlds of life by the frequencies that you send out. The frequencies you send out transcends cities, countries and this world. It will echo in the entire universe, and you are using your thoughts to broadcast the frequencies! You are the fountainhead of the broadcasted frequencies.

Your thoughts give rise to frequencies, and yet thoughts will attract towards it things of similar frequencies. By the reactionary force, it then returns to your body and through it becomes a part of your life. If you want to change the circumstances of your life, you will only need to change your thoughts and through it change the channel and the frequency. In this way, your life circumstance will greatly change, as the saying that conditions changes with the mind.

## Good and evil thoughts all carry frequencies

Tibetan scriptures: “Jambudvipa mentions the arising of thought of the masses, not one is without karma, not one is without sin”. [Treatise On the Response of the Tao]: “One harbors lustful thoughts after seeing a beautiful woman”. As soon as you think the thought then it counts as engaging in nefarious wantonness. In between forming a thought, high and low is clearly distinguished.

Real reboot is mind reboot! One needs to cultivate the arising of thoughts. In rebooting, one needs to learn to control one’s thoughts. In other words, cultivate the mind! Although many brothers are persistently rebooting, they are unable to conquer their sexual fantization. Fantization is often the prelude to relapse. If the cutting out of new thoughts cannot be achieved, then breaking the reboot will easily occur. Actuality, being addicted in sexual fantization counts as relapse. Also that fantization is a form of invisible leakage, when the heart sways the essence leaves. Addiction to sexual fantization will also induce the outbreak of symptoms. If one can strictly achieve cutting out of thoughts once they arise, then the body will not be harmed.

The key is to find the proper timing for cutting out thoughts, speed is of the essence, try to cut out the fantization within 1 second. The real adepts are basically able to cut out the new thoughts immediately, more or less within 0.1 seconds. Many rebooting rookies are unable to cut out the sexual fantasy within 1 second. Oftentimes, it is not until several minutes afterward that they discover they have fantasizing. By this time, it is already too late. The evil thoughts have already taken hold just like when a little sparks turn into a huge forest blaze, control will be hard at this point.

Rookies lack watchfulness and awareness towards their inner states, therefore they are defeated by their temptation daemons time and again. During rebooting, we must learn to watch our minds and cut out thoughts. We must keep a firm eye on our thoughts and know when a thought has arisen. With an awe-striking awareness, when the time comes, the thought is no more. The saying that once a thought arises, cut it out immediately, once one is aware, the thought is naught! Do not be led along by the thought, remember at all cost!

Dharma Master Dazhao: “As long as you give rise to a thought, this thought will act as a net in the Ten Realms and capture your entire Realm within it. When giving rise to a kind thought, the manifestation from your realm will be a kind Realm; give rise to an evil thought, the manifestation of your realm will be an evil Realm. We are ordinary and foolish, we are not aware that the thought born out our heart will have such an enormous impact on our Realm. But all the Buddhas in the ten directions, great virtuous founders of past dynasties, all friends on the same journey, those who are diligently forging ahead, those with a sensitive heart, all will immediately sense it. Just like wireless radio waves that are immediately received, intercepting your signal. As long as the mind moves, karma is born, there will be consequences. This consequence will then change our future direction and path. Every thought, as long as it is born, its signal will spread to the entire Realm. Even if you are alone in the room and feeling angry, very angry, smashing the cup onto the ground, you think that nobody is watching you in the room, in reality, all Buddhas in the ten directions as well as your own life reality, will manifest an angry and complete Realm, neglecting nothing. Every thought possesses this universality in the Ten Dharma Realms. In other words, the signal from our mind will at any time cover the entire world. The degree of this coverage is very high.”

According to the holographic universe theory, the universe is an integrated whole where every part of it shares a holographic association with one another. Within this wholeness of the universe, between all its systems and subsystems, a holographic correspondence exists between the systems and the universe. When it comes to latent information, subsystems contain all the information of the systems, systems contain all the information of the universe. When it comes to explicit information, the subsystem is a miniature version of the system, the system is a miniature version of the universe.

The basic principle behind the holographic universe theory: looking at the latent and explicit information as a whole, any part contains the information found in the whole. The holographic universe theory has been applied in TCM relatively early, this is known thousands of years ago. Many people have probably seen the TCM hologram, for instances the palms, ears, face and different parts of the body all correspond to the internal organs, every tiny part contains all the information found in the whole. The universe is fundamentally information! Thoughts are information! All evil and kind thoughts have frequencies, kind thoughts correspond to high frequency, evil thoughts correspond to low frequency, you are sending out thoughts everyday (namely vibrating the wave-like information).

Professor David Hawkins stated clearly after more than 20 years of research, the strength of the human body will fluctuate along with the state of the mind. He has mapped the human consciousness in the range between 1-1000 (Translator’s note: the unit of the frequency was not mentioned). Any state that induces a frequency below 200 will drain the body, anything between 200-1000 will cause the body to strengthen.
s Physicists have already proven that all matter in this world is made up of swirling particles. All these particles have a different rate of vibration. The vibration of the particles is what causes the world to express itself as it is. Our bodies behave in the same way, scientists have already measured that the vibrational rate of the body differs under different mental states. This result was an eye-opener for everybody. Kindness, honesty, compassion, love, these positive qualities allow the rise of bodily vibrational rates, the bodily health may then be improved.

The highest frequency that professor Hawkins has encountered is 700, it occurred when he was studying the nun Teresa during 1997 when she has received the Nobel peace prize. (Translator’s note: There may be an error in the dating as Mother Teresa received her Nobel Prize in 1979, she died in the year 1997). The moment that Teresa entered the room, everybody’s heart was filled with joy, her appearance made it almost impossible for people to harbor distracting thoughts or hatred. 1000 is named the as the state under total enlightenment, this it the frequency of absolute power!

Professor David Hawkins said: “Many people become sick due to the lack of love, there is only pain and dismay. One is prone to become sick when the rate of vibration is below 200.” The doctor would come in contact with a large number of patients everyday. He found out later that as long as a person is sick, that person always carries lots of negative thoughts. If a person’s vibrational rate is above 200 then that person will not become sick easily. His patients would often have a vibrational rate below 200, what kind of thoughts did they send out? Thoughts such as sexual fantization, blaming, anger, inflicting injury upon others, etc.. In the process of sending out these negative thoughts, much energy is lost, therefore, when the rate of vibration goes below 200, these people are prone to catch different illnesses.

## Evil thoughts will drag down your rate of vibration

Evil thoughts will induce the lowest of frequencies, the quality of these thoughts is one of a twisted nature, of harm. When you are thinking about degenerative thoughts, when you are addicted to sexual fantization, the reality is that you are weakening yourself. This is not limited to sexual fantization, also included are evil thoughts such as greed and injuring others in order to get ahead, these will all pull your frequency lower. On the other hand, gentleness, optimism, forgiveness, gratefulness, love, respectfulness, sereneness, calmness and joy, etc.., all of these will raise your vibration. The higher the rate of frequency, the easier it is to feel the great joy of pureness, the lower the vibration, then one is surrounded by pain. The vibration of kind thoughts is higher than evil thoughts. By lifting more kind thoughts, our bodily energy vibration will increase accordingly.

When a person’s vibration is relatively high, he already possesses various positive qualities. His thoughts are pure, his character is noble and actions selfless, these are all reflected in his every word and action. He will like to come into contact with contents that share a similar vibration, choosing to associate with people with similar frequencies. Whenever we create a thought, a certain frequency is born. Noble thoughts produce higher frequencies, degenerative thoughts produce lower frequencies. Many sexual fantasizers, their rate of vibration is very low because they are constantly producing evil thoughts and have done many things of nefarious wantonness. This, in reality, is sabotaging and injuring the self. Evil thoughts will drag a person’s frequency lower, the lower the frequency then the more painful it becomes. Every form of psychological and bodily symptom will then follow from it and manifest itself.

## The Creator’s secret: frequency determines the physical form

“If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.”

— Nikola Tesla

Every physical substance in our world is a manifestation of vibration.
If the vibration is changed then the structure of the physical substance also changes.

Thoughts, feelings, moods all have a determined rate of vibration. We possess these frequencies at all times and so come into resonance with our surroundings.

The famous experience of vibrational frequency on sand pattern has shown the relationship between frequency and physical substance. Different frequencies correspond to different forms of shapes. Thoughts are a form of vibrating wave-like information. Thinking a thought gives rise to a certain frequency. This frequency will directly influence a person’s appearance and temperament. The saying that looks is grown by the heart. Many people who masturbate have become ugly, this is widely reflected in the narratives of brothers. In the beginning, the process of ugliness is not very apparent. With the increased time one spends in masturbation and with the deepening of injury upon the essences, many previously handsome people have turned beyond recognition, showing abnormal ugliness and wretchedness, even developing towards the direction of monstrostrous deformity.

Why is it like this? It is actually very easy to understand from the perspective of frequencies. Because he is sending out evil thoughts of nefarious wantonness, and the frequency of nefarious wantonness corresponds to the appearance and ugliness and wretchedness. Therefore, people addicted to nefarious wantonness will inevitably turn wretched and ugly, this is a certainty.

After rebooting, the soul receives purification, the frequency will then rise. During which time, the appearance and temperance will again develop towards the positive direction. The thoughts that a person produces will affect his physical appearance and temperance because thoughts produce frequency, frequencies will affect the physical form, it is this mysterious. Many people have previously heard the saying that looks is grown from the heart, but they do not understand the underlying principles of physics. After having read this paragraph of description, I believe that more people will gain a deeper understanding and awareness. The thought waves that you are producing is affecting your physical appearance at this very moment, this is subtle. After a few years of nefarious wantonness, the appearance and temperament will decline, because your vibrational frequency has decreased. Evil thoughts will induce low frequency while low frequency corresponds to ugliness and wretchedness.

## Methods for raising the rates of vibration

Kind deeds and the accumulation of virtue, do more to help people. In this way, your vibrational frequency may be vastly increased.
Emit more thoughts of repentance, correct and change to the better, straighten the self in order to change the person.
Read more vibrational uplifting books, study more traditional culture.
Emit more intention of respectfulness, read more teachings on great virtue.
Maintain a grateful heart, practice more filial piety.
Learn to not complain, practice tolerance, learn to forgive others.
Keep calmness, inner calmness is a form of high vibration.
Attempt to find the Truth of life and the universe, find the belief that belongs to the self.
Do not look at nudity, especially in border pictures and news.
Maintain modesty, modesty allows increasing the rate of vibration.
Learn to meditate, actively exercise, learn the way of health cultivation.
Be among children, be as pure as children without a trace of evil.
Reboot, cut out smoking, alcohol, internet addiction and various bad habits.
Do not blame, don’t be jealous, encourage more, praise more.
Study Buddhist Dharma, read Buddhist sutras, chant the name of the Buddha. One’s vibrational frequency may be vastly increased through this way.
Learn to cultivate the heart, control the thoughts, this is the most basic method of raising the vibrational frequency.

## Afterword

We should all return purity to our soul and become a keeper of pure frequencies. Say no to the nefarious wantonness and pollution from these troubled times. The modern society is flooded with nefarious wantonness, also the evil notion of harmlessness theories is rampant, keeping a frequency of pureness is extremely difficult. Everyone has their own rate of vibration just like they have their own fingerprints. Yet the vibrational frequency is able to be raised when you have cut off the addiction of nefarious wantonness and try your best to practice kindness, in this way your vibrational frequency will increase by leaps and bounds. The higher the rate of vibration, the easier it is to experience the vast joy of pureness. In contrast, a low rate of vibration will sink one into boundness fear and pain.
