# The issue of waist pain, puffiness, emancipation and the importance of keeping vigilance

## Foreword {-}

### Greying issue {-}

Recently, many brothers have asked about the issue of greying hair. To recover from greying will require approximately 1 year of time. Those that often browse my case-related posts should have seen a particular case: one brother after having rebooted for 200 days had all his hair turn black. I, on the other hand, took about 1 year of time. Nowadays I have very few grey hairs, around 1-2 strands, this is entirely within the normal range. Only persistence is needed in order to recover from greying. In addition, one must:

1.  Strictly control the number of nocturnal emissions
2.  Make all efforts to cease sexual fantasizing
3.  Emphasize the way of health cultivation

When enough effort has been made in all 3 areas, greying will naturally recover. Many people are rebooting but are unable to control their nightly emissions and sexual fantasies and do not understand health cultivation while at the same time relapse often. To recover from greying under these conditions will be quite difficult.

### Why do some brothers have many symptoms?

Some brothers, especially those who are yet to experience serious symptoms think that it is incredible for a brother to experience a dozen symptoms. To these brothers, I can only comment on the shallow level of experience. Up until today, I have seen several thousand cases and have personally communicated with a thousand brothers. The majority of these people have very many bodily symptoms. They have only picked out the most apparent symptoms and inquired about them with me. One will only understand this by going through lots of cases. There are many brothers with a dozen and even several dozen different bodily discomforts. Some brothers are exquisite and sensitive and are able to describe all the discomfort symptoms, while some brothers come to late realizations and have limited abilities in expressing themselves, thus making them unable to give a description of all the uncomfortable symptoms. Those brothers that are yet to sustain serious injury or have come to late realizations will think that all of this is unbelievable. This is in fact very easy to understand. When you have been injured to a certain degree then you will naturally understand the truth that I speak. People that lack the experience will have no way to understand the agonies involved. If you have never tasted salt, you will never know about its specific flavor. All the descriptions that others relay to you mean nothing.

In addition, I would like to stress a point, I did not successfully reboot on my first try. I made my first attempt while in middle school, I was totally oblivious at the time, I did not have the awareness to study rebooting material nor did I have a guide. At the time, I only relied on blindly and forcefully rebooting and knew nothing about the way of professional rebooting, the result was repeated defeats. I have failed countless times and have struggled in the vicious circle for many years, my entire body became ridden with symptoms. If I had succeeded in my first attempt then I would not have had so many symptoms later on. It’s a pity that it took me well over a decade to realize the importance of studying reboot articles. Fortunately, it is still not too late. After a couple years of bodily recovery I have been restored to normal. Of course, it is still incomparable to when I was a teen because now I’m already 30 years old.

### About my motivations

Let me elaborate further on my motivations. When writing about my experiences, I seek not fame nor any gains. It is entirely for the welfare of the public. I do not seek any rewards and I don’t need anybody to worship me. Some brothers have called me Grandmaster but I have never paid attention to it. I sit on the same level with every brother. I’m just the person pointing directions which puts me on the same level as the person asking for directions. One does not tower above the other, I’m but an ordinary waypoint. If you ask me how to reboot I can point you towards the right direction. I only wish to help everyone.

We enter into the main topic below.

This season is about the issue of waist pain, puffiness, emancipation and the importance of maintaining vigilance, I will go through these topics in detail below.

## Waist pain

TCM:  _“waist is the residence of the kidney”_.

The issue of waist pain is common among brothers. I believe that the majority of brothers have had the experience of sore and aching waist. One bodily expression following masturbation is: soreness and softness of the waist and knees. In more serious cases, pain is involved. Of course, many factors contribute toward waist pains. Normally, masturbation induced waist ache will slowly alleviate itself following a period of rebooting and health cultivation. If your waist ache is persistently bothering you, I would recommend you to go get it checked out in order to rule out any organically related illnesses, such as issues with the lumbar disc or kidney stones. In everyday life, many people suffer from the issue of protruding lumbar disc. The seed of this problem could be sowed when one, for instance, is not careful with the body posture when carrying heavy objects.

There is another expression for post masturbation waist ache and that is the inability to straighten the waist after having bent it for long periods of time. The feeling is extreme soreness.

Previously, when I used to wash clothes after masturbating. Upon finishing washing, my waist would be very sore, it would require a while of rest until it recovered. Therefore, masturbation will cause the waist to become very soft and weak. Under normal circumstances, bending the waist will not cause soreness issues, but because you have the evil habit of masturbation, soreness will easily appear after bending the waist for a long time. This kind of issue, where soreness or pain follows the bending of the waist has been reported by many brothers, I have had such experiences myself.

In addition, after masturbation, one becomes very soft. One should take extra care when exercising under such conditions. Because while partaking in a heavy exercise under this soft bodily state one is prone to get injured, something that I have deeply experienced. Previously, when I went to play basketball after masturbation, I broke my bones on 3 occasions and sprained my ankles countless times. Furthermore, those injuries happened under strange circumstances and were all self-inflicted.

With regards to waist pains, this problem is very easy to solve given that one is without organic illnesses, normally. After a period of rebooting while cultivating the health, waist pains will heal by themselves without the use of medicines. If soreness and pain in the waist persist, it is recommended to get it checked out. If organic issues are absent then one may use Chinese herbal medicine for treatment, if organic issues are present then one should undergo active treatment while persisting in rebooting and cultivating the health, in this way the recovery will be fairly rapid. For men, the waist is really very important, one should properly take care of the waist.

## Puffiness

Following masturbation the condition of being out of tune will appear. This is reflected in the body weight, either in puffiness or being emaciated. Of course, although some people masturbate, they still practice good exercise and dietary habits and thus they might not run into the mentioned problems. Although I have frequently masturbated before, I loved to exercise and would keep relatively rhythmic rest and eating schedules and so the issue of weight imbalance did not show up.

In TCM, puffiness is due to 2 reasons:

-   Spleen deficiency with moist obstruction
-   Spleen plus kidney yang deficiency

If a person loves to exercise, he will not become puffy. Although fat, he will still look very strong and not have a loose muscles type of puffiness look. Why is it that people who love to exercise will not normally encounter puffiness? Because according to TCM: spleen governs the 4 limbs. [Suwen]:  _“Spleen governs the muscles of the body”_. If the spleen qi is moving healthily, then the muscles will be plump and vigorous. If the spleen is sick, then the muscles shrink and become useless. A person that loves to exercise may achieve a spleen strengthening effect, the possibility of running into puffiness will be relatively low. The spleen qi strengthens the movement, muscles will then become elastic and vigorous. Many people think that puffiness is due to fat, this is actually not correct. puffiness indicates that both fat and muscles have become soft and sagging, the feeling is one of being without elasticity and very loose.

How to treat puffiness? Taking Chinese traditional herbals is one way, this will adjust your internal organs. More important, however, is to establish healthy exercise and dietary habits, this is very important! You can forego the herbs, if you only manage to make the other two points, weight can still be shed, you can even become a fit and muscular guy.

I have previously been a personal trainer and have accumulated vast experiences in losing fat, in addition, to going through the fat shedding process myself. If you have some general knowledge with regards to working out, then you’ll know for sure the saying: 30% comes from training, 70% comes from eating. Merely training is not enough if one wants to gain muscle. The key is to eat the right amount of food, muscle gain will be relatively quick in this way. Fat loss works in the same way. Many people will have an intense workout but when they return home they’re unable to control their appetites and end up eating too much. By doing this they have regained all the energy that they have lost through training. In addition, the spleen governs the 4 limbs. Normally after working out, the appetite will increase and this enables one to eat a lot. The result being that no matter how hard one works out one is unable to shed weight. In reality, if one is able to strictly control the food input, even without training intensely, the weight will still decrease.

For brothers experiencing puffiness, my advice is:

-   Actively exercise, emphasize aerobic exercises. One may also combine it with strength exercises.  
    
-   Strictly control food intake, highly energetic food, midnight meals and snacks should all be restricted.

If the above points can be met, your weight will for sure decrease. If after a period of time your weight is still unchanged, then you should reflect on which of the above points you need to improve upon.

In addition, strength exercises will help you to shape the muscles. Many brothers become addicted to strength exercises as they would like to become stronger, more manly, this is a very common form of thinking. A strong body indeed gives one the feeling of assurance and makes one feel more confident. Normally, a stronger man also has a stronger sexual function. But please remember a saying:  _“blessing and misfortune exist side by side”_. TCM advocates that desire should not be too strong. When many people have trained themselves stronger, they become even more prone to fool around, the result is that they become indulgent at a young age. After the age of 40, it is time to pay the bill. The headache will be great when that time arrives.

Being strong is not the same as being healthy or having longevity. Many strong people have numerous issues, even  being unable to make past the age of 50. On the other hand, many people practice health cultivation, their strength indicators are very low but they still live upwards 80 and beyond.

I have another piece of advice for those brothers suffering from puffiness. If you want to lose fat, you will have to increase understanding. This is like rebooting, professionalism is the key. With professional knowledge, one finds the door easier and succeeds easier. No matter in what occupation and on what matters, it is particularly important to study. Ignorance stems from not studying, understanding comes from studying. In addition, combine it with one’s own practices and constantly gaining new awareness, success will then be not far away. The saying goes difficulty does not perplex the Master, the perplexed will experience difficulty, one must study more. Many things will become simple once you have grasped an adequate amount of professional knowledge on fat loss. If your understanding is not deep enough, you will hesitate and be at loss in many choices.

## Emaciation

Another type of brother will encounter the emaciation issue.

Emaciation shares a certain relationship with the physique. Of course, it is also intricately related to the disorderly function of the internal organs caused by masturbation. Emaciated people have poor appetites, are unable to eat much and have poor digestion. No matter how much they eat they will not become fat, this is the first type. There is another type, it’s when one is able to eat a lot but are unable to become fat. This type of person may suffer from poor absorption or have a very high basal metabolism. Some other brothers are suffering from chronic diarrhea, weight loss is made even easier with this condition.

I advise the emaciated people to go seek a traditional Chinese doctor followed by active exercises, emphasize health cultivation and slowly adjusting yourself.

## The importance of keeping vigilance

Lastly, let’s talk about the importance of keeping vigilance.

Quite a few brothers have been on a rebooting streak for over 100 days and then still relapsed, what is the reason? When many brothers have gone through a period of rebooting it is easy to let down the guard. Thinking that the problem is no more and that one has succeeded, one starts to relax. First, the relaxation is with regards to studying rebooting articles. Second, it is the relaxation of vigilance. As soon as one relaxes the vigilance, relapses come easily. Rebooting is like walking on a steel wire, one needs to keep alert everyday because if you are not careful you will fall down. If you are not careful you will relapse, this happens almost supernaturally.

Ever since I started to reboot until the present day, I have still maintained my vigilance. Just like the vigilance of a woodpecker, when a person approaches it flies away, the woodpecker will not allow anybody to come close to it. Rebooting works in the same manner, when one enters a stable period, after some time of rebooting, it does not mean that relapses will not occur again, if you relax your guard you will still relapse. Therefore, we should allow ourselves to maintain our state of alertness and not wander far from rebooting articles, we should look more into cases from sufferers. This process is likened to brushing the teeth everyday. It does not have to take a long time but by looking at rebooting material daily, it is absolutely beneficial to the maintenance of your vigilant state. This is an indispensable awareness towards a successful reboot.

Naturally, some people have an extremely high level of awareness, they don’t look at rebooting articles nor into any cases. Everyday, they go through their suffering once in their heads, this also allows them to keep vigilance. There is another type of person who is able to maintain vigilance and that is the person with a religious belief, rebooting is like a form of a commandment. If the person strictly adheres to the commandment then he will not relapse. Because he knows that relapse is worse than death, this is his consciousness.

## Afterword

### How can some people masturbate but still have good health?

Some brothers ask me, why is it that everybody around me is masturbating but their health is still good?, why is it that only my body is ridden with symptoms? Quite a few brothers have asked me this question and it is not difficult to answer it. The constitution is different for different people, some people are naturally endowed with a good constitution, a thick health foundation. Plus they love to exercise, have fixed resting and eating habits and are absent of any other negative hobbies. These kinds of people can afford of few years of depletion, the fruit from the evil karma will appear relatively late. On the other hand some people have a naturally weak constitution, their physique is inadequate and they don’t like to exercise, they like to sit for long periods of time and have internet or smoking addiction. They often stay up late at night in combination with frequent masturbation. They will encounter symptoms relatively early and these symptoms will be more serious.

Also note that, although some people seem to look fine from the outside, in reality, they also have lots of symptoms, only that you cannot see them from the outside. There is a word called “hidden disease”  _(Translator’s note: hidden disease are those disease that are hard to detect and to cure)_. In everyday life, many people carry with them hidden disease. These are matters of privacy, they will not tell you. You will think that they are healthy but that is not the case.

Just like myself as an example, at a time I had prostatitis but other people didn’t know about it, I hadn't told my friends either. On the sports court, I was vigorous like the tiger and other people thought I was very healthy, that was not the case. Only I knew that I suffered from my discomforts owing to my evil habit of masturbation, only that these symptoms were not that serious and were bearable at the time. After a while of rebooting, all of these symptoms would find relief which is why at the time they were not emphasized that much.

In addition, I had varicocele for over a decade without knowing about it because it was not severe. I did not experience distinct discomforts but I had the disease. Only upon doing an ultrasound did I find out that I had varicocele. I have already written an article regarding this disease. After reading that article, many brothers went to the hospital for a diagnosis. It turned out that quite a few brothers were diagnosed with varicocele, only that they were previously oblivious to it.

Actually, due to the evil habit of masturbation, more often than not there will be symptoms. No matter how good your constitution is and no matter how much you avoid unhealthy hobbies, as you age, many latent issues expose themselves, the debt will sooner or later be paid. It is not necessarily bad that the body deteriorates early because once the body has deteriorated while you are young and you come to the realization to reboot thoroughly, the bodily ability to recover is still strong. What’s worse is when the body deteriorates when one has passed 40, by then the bodily recovery function is not as it used to be, the rate of recovery will be very slow.

### Sweating when doing kidney strengthening exercises

Let’s talk about the sweating issue when doing kidney strengthening exercises during the summer. It is now the scorching summer, the tiniest of movements results in a drench of sweat. Even when we stay stationary, the sweat will pour down like the rain. These days I’m still persisting in practicing the kidney strengthening exercises, I have not stopped for a single day. The way I practice is by going bare to the waist, prepare a towel. After doing a set of movements and having sweated, I immediately wipe myself dry, then repeat the movement. In this fashion, the issue of sweating can be avoided, otherwise, if I practice kidney strengthening exercises following a shower, my clothes get soaked again which is very uncomfortable and makes it hard to sleep. Furthermore, during the summer, try to limit exposure to AC. Exposure to AC and taking cold beverages both damage the yang qi and discourage bodily recovery, remember.

### About keeping track of the days

Lately, some brother reflected the “days record” issue with me. I’m not personally against keeping track of days, but I feel like keeping track of days is like punching an attendance card at work. You cannot just punch the card but not work. It is similar with rebooting, you have kept the day’s record, but what is your goal? The goal of keeping days is to study rebooting articles and sufferers’ cases daily in order to alert oneself. If the goal is only focused on keeping track of the days then your awareness and determination will not have increased, you will still remain in the brute force rebooting stage.

A mistake that newbies tend to make: only keeping track of days and not studying. They see that other people have opened a thread for tracking days and so they do the same, yet they do not emphasize studying rebooting articles. Back when I first started to reboot, I also liked to keep a day count. At the time I kept my record in a notebook and the maximum number of endurable days was 28 days. Afterwards, when I reached a thorough understanding, the thought of keeping track of the days did not even occur to me and it did not feel like an endurance event. Until today, I have not relapsed, because I have reached a thorough understanding. In addition, I maintain a daily awareness vigilance. I don’t remember how many days I have been rebooting, only from which month I started to reboot from. My advice is: don’t pay too much attention to the number of days, put emphasis on studying and increasing rebooting understanding and awareness. This is the true path towards rebooting.
