# Aggravated hair loss following rebooting, complementary info on emaciation and the issue of lower brain power

## Foreword

### How is it that I have experienced every symptom?

Some brothers may wonder, how is it that Soaring Eagle has experienced every symptom? It does not seem possible, out of this question doubt is born. Those who often look into my personal experience related posts will know that I have not said that I have experienced every symptom out there. For instance, I have mentioned in my posts that I had drooping testis, but not shrunken testis, I have not suffered from puffiness either. When writing my articles, I carry a truth-seeking attitude. Things are either experienced or not experienced, I will not make things up. Although I have not experienced some symptoms, I have thoroughly researched and enquired into them. For example, the doctor doesn’t need to have experienced every ailment. The important thing is to have deep knowledge and understanding in the ailments, that is the key.

No matter how weak a person is, it is not possible for the person to have experienced every symptom. Even though two people may both suffer from kidney yang deficiency, the main symptoms are still different. I have had a history of masturbation for over a decade, it could be said that I have experienced the vast majority of symptoms. In addition, I have researched into the habit of masturbation for a couple years and have encountered basically every type of symptom. In addition to this, I have assembled a vast archive of cases, chatted with over a thousand brothers and have gained a deep understanding in this area. The study of TCM theories did not stop either. All of the above mentioned have provided me with the foundations for the articles that I wrote.

Because I have written a huge number of posts and threads, it is impossible to answer all questions arising therein immediately. I hope that everybody understands this.

### On promoting rebooting

A capable group of brothers are on the rise in the rebooting forums. This group of brothers are constantly studying and have increased their understanding a lot. Therefore, everybody may also refer to them for any questions. There is a need for talent everywhere, the same goes for the rebooting forums. There is a need for talented Q&A people, talented promoters, administrators, each person has their own duty to improve the forums and help more people. As to the issue of being scolded at while trying to promote, this has happened on different occasions. Previously, I did some promotional work, although it was not internet-based but based on the QQ-group, where I promoted rebooting and health cultivation among a dozen or so of the anxiety patient groups.

When doing promotional work, first, it is important to let things go their own course when helping people, do not force things. Second, pay attention to the promotional strategy, choose the optimal entry point. Third, one must be in control of their emotions, because in this line of work, it is very easy to run into stubborn people. Just like when the scholar meets the soldier, there is no reasoning. When meeting these kinds of people, making a concise point is enough. There is no need for elaborate explanations. Once the message is heard, the seed has been sown. They might not understand it today but perhaps they will suddenly understand one day and come to regret their old stubborn ways, not having paid heed to your bitter truth.

Helping people, in reality, is helping the previous you. The old you is perhaps reminiscent of the present them: not recognizing the truth until it is placed right in front of them, stubbornly going their own way, controlled by the indulgence mentality, harboring misconceptions towards rebooting along with an attitude of rejection and conflict. Now that you have understood after having clearly seen the truth and you want to help others, this is a very good thought. But one must pay attention to the promotional strategy and method. In this regard, the forum owner Balinhou has extensive experience. Everyone may seek him out, join a promotional team and learn from successful promotional models.

Doing promotional work in the field of rebooting is extremely meaningful. Sometimes, a single sentence from you may change someone's entire life. Due to that single sentence, they become enlightened. In the future, I'll be sure to return to do more promotion for rebooting, but as of now, my main mission is to write more knowledge/experience articles.

Heading into the main topic below.

In this season we will take a closer look at aggravated hair loss following rebooting, complementary info on emaciation and the issue of lower brain power. Details can be found below:

## Hair loss following rebooting {-}

Lately, many brothers have reported aggravated hair loss following rebooting. When this happens one easily thinks about throwing in the towel and not want to reboot anymore, thinking that hair loss did not occur before rebooting but became serious following rebooting, what’s going on? I have mentioned this in previous articles, specifically about relapsing due to doubt. If there are unsolved problems, relapses become easy. When hair loss becomes aggravated during rebooting, it easily causes one to experience panic. Anxiety and the loss of hope, are precisely the type of negative emotions that in turn easily induce an emotional-based relapse. When one wants to vent negative emotions via masturbation, the result is to sink back into the vicious cycle.

Actually, I’m well aware of the thinking process of the brothers who contemplate giving up rebooting due to aggravated hair loss. They think that if they start to masturbate again, their hair loss might cease. This kind of thinking is a bit absurd but it does occur.

Normally, some symptoms will easy appear after one has started to reboot. Many people have not experienced any symptoms before rebooting but as soon as they start to reboot, symptoms appear. When seeing the emergence of symptoms, many rookies start to panic and think that abstaining is harmful, they then immediately sink back into the trap of masturbation. The emergence of symptoms following rebooting is actually a withdrawal reaction, it is very commonly seen. Persist in rebooting and cultivating the health and bodily symptoms will slowly improve and even disappear. The increased severity of hair loss following rebooting can also be seen as a withdrawal symptom. Of course, some people say it is a reaction to shedding illnesses, there is also some truth to this. Due to the build-up of vital qi after rebooting, latent illnesses will naturally make themselves known.

### Aggravated hair loss during summer

I have also discovered that a great number of brothers report aggravated hair loss during the summer season. Why during the summer? Before the arrival of summer, I would lose less than 5 strands of hair on any given day, but now I lose several dozen daily, some days over 30 strands of hair. In fact, this is seasonal hair loss at work. For a normal person, hair loss will  increase during the summer. I have mentioned in the previous article that there are many factors leading to hair loss, one must get to know each one of them or else it will be easy to get into a state of panic. The thought of throwing in the towel is made easier under a state of panic. During the summer there is more sweating and therefore the scalp will itch more frequently, when the scalp itches, hair loss will increase. Recently, when washing my hair, I apply hair shampoo twice yet my scalp would still itch. So I applied a few drops of herbal distillate in clean water and my scalp barely itches now. Since my scalp no longer itches, I have noticed that the amount of hair loss has decreased.

Hair loss during the summer is due to the following reasons:

-   Due to exposure of the head to strong solar rays which break the keratin within the hair and causing the hair to fall off.
-   During the summer the scalp sweats more easily and produces more oil. Plus it gets dustier and thus hair gets negatively affected.
-   Due to walking in and out of AC exposure. This causes poor blood circulation and causes the hair to fall off more easily.
-   The summer heat induces secretion imbalances in the body, inducing hair loss.
-   Consumption of cold beverages. Due to the fact that one consumes more ice sticks, ice cream, and cold beverages hair falls of more easily.
-   A decrease in nutritional input. Protein is an essential nutrient for the hair. But due to the heat of the summer, people like to eat a lighter diet, meat intake becomes relatively less. This results in the hair falling off more easily.
-   Inflammatory stimulation. During the summer there is a higher chance for folliculitis, favus of the scalp, pimple or carbuncle. These cause instability in the hair follicles and induce hair loss more easily.
-   It is scorching during the summer and thus there is a large amount of water evaporation. If the water is not quickly replenished it will lead to a decrease in the sebaceous gland secretions. This induces the drying up and falling off of hair. When the hair loses its moisture it becomes brittle, after some time it will become crisp and break easily making it prone to falling off.
-   Affected by the summer weather. Many people suffer from poorer sleep quality, become more irritable. This is also a contributor to hair loss.

### Repeated symptoms during summer

Summer is a very special season, the common saying goes: although there may be no illnesses, one is 30% weakened during the summer. Because there is a high amount of sweating during the summer, according to TCM:  _“He who sweats, also loses essence”_. When one sweats too much, one is weakened. Lately a brother reported the good progress he was making after a few months of rebooting, but lately, some symptoms have re-emerged even the re-occurrence of frequent nightly emissions. This is, in fact, an expression of the repeating symptoms period.

Many brothers confuse withdrawal symptoms with the period of repeating symptoms, I will again emphasize it here. Withdrawal symptoms normally occur within the first month of rebooting. Repeating symptoms may occur at any time during the reboot. Because some people have not properly cultivated the health, following a half year of rebooting they again experience a repeat of their symptoms. Some people may encounter repeated symptoms after a year due to staying up late, fatigue or frequent nocturnal emissions.

The reason why symptoms tend to recur during the summer is because one sweats profusely during the summer and even without illnesses one becomes partially weakened, add to this exposure to air conditioning, cold beverages, staying up late, long periods of sitting and long staring and its easy to see why repeated symptoms will easily occur. If you go about your day engaging in exercises that have a damaging effect on the yang qi, it would be a surprise if you didn’t catch any symptoms. Therefore, I very much emphasize health cultivation.

The mistake many people make is that they only reboot but do not cultivate the health. They do not know how to do it and have a very low level of health cultivation awareness. Walking into an air conditioned room right after a shower because it feels good sows the seed for future illnesses. Some people love to take cold beverages and they do so daily, this has a very negative impact on the recovery of the body. Once you are aware of these things, you will not repeat these mistakes, because you know that by engaging in those activities you will severely damage your yang qi. When the yang qi has been damaged, repeated symptoms will show up.  _(Translator’s note: Just to clarify, repeated symptoms are a repeat of previous symptoms that we’ve had during the time when we were still masturbating)_

Some brothers ask if it’s OK to use AC during the summer. My recommendation is that one can use the AC but refrain from AC exposure right away  after taking a shower or to set a temperature that is too low, otherwise the cold air will enter the body through the pores. I remember a couple days ago I went into an air-conditioned room to fetch something, the temperature was set very low. I was sweating slightly at the time, so the pores were all open. Suddenly, I was exposed to cold air and later that day I suffered from diarrhea. AC is a great invention but it is a double-edged sword and does not benefit health cultivation. Everybody should be careful when being exposed to AC in order to avoid sowing the seed for future illnesses.

For those brothers who are suffering from aggravated hair loss during the rebooting period, make sure to persist in your efforts and do not panic. Remember this sentence: It is not wrong to reboot. When you panic, it is only because you have not figured out what is going on at the time, it is not that rebooting is hurting your hair.

## Complementary info on emaciation

Let’s talk about the emaciation issue below:

In the previous season, we talked about the issue of puffiness. We did not go through the emaciation issue thoroughly enough. In this season, we will examine it closer.

For the emaciated brothers, if you want to become strong, I would advise doing some moderate strength exercises. Doing strength exercises will increase your appetite. If you have no problems with digestion then you will quickly become stronger. It would be preferable if you had somebody to coach you. In this way, your training will be more systematic and professional as opposed to blindly training by yourself. If you have your eyes set on only push ups and sit ups then it will be difficult to become strong quickly. Being professional is also important in strength exercises. If you train in a professional manner then you will become strong very rapidly and advance very quickly. Therefore, it would be best if somebody in your surrounding is able to show you the way.

When I graduated from college, I was 186 cm tall and weighed 62 kg. After I started to work out my weight surged to 100kg. The impression I gave to people was of being both fat and strong. After that I started to shed fat and did lots of high repetition exercises, the contours of the body then appeared. Nowadays I maintain a weight of about 80 kg without focusing too much on protein heavy food and I keep a normal and light diet.

There is a saying in the bodybuilding sphere: fear eating, not training. As long as we have gotten the hang of training then there won’t be any big issues, the importance is in the diet. In order to become strong, energy intake must be adequate. In the beginning, we gain both fat and muscles, once we start to shed fat after having reached a certain weight the shape starts to appear.

Everyone may take a look at the workout terminology:

-   Chest: sitting bench press, 3 sets
-   Back: rope from neck pulldown, 3 sets
-   Shoulders: sit on the combination machine and do pulling and lifting, 3 sets
-   Triceps: rope pulldown from standing position, 3 sets
-   Biceps: biceps curl lift on a combination machine, 3 sets
-   Thighs: leg lifts, 3 sets
-   Biceps femoris: prone leg curl lift, 3 sets
-   Calves: heel lift while sitting on the combination machine, 3 sets
-   Abs: Sit-ups, 2 sets
-   Heel lift with dumbbells, 2 sets

For the person who has never worked out before, this terminology may seem foreign. This is why I have mentioned it is better to have somebody show you the way. The person may demonstrate the important aspects of the movements and let you in on lots of professional knowledge. In this way, you will quickly learn the ropes. After that, you will progress very quickly. Every month there will be changes, your strength will increase a lot.

Of course, don’t expect prostatitis to heal just because you have become stronger. Reality has proven that no matter how strong the body is, one can still suffer from prostatitis. The key is to reboot and cultivate the health. A person who has become stronger may alleviate the symptoms of prostatitis, but to completely heal requires rebooting and health cultivation. According to my understanding, many bodybuilding champions have illnesses. Some have had a stroke, some are suffering from heart conditions. Therefore, strength does not signify health. One must still rely on the words: reboot and cultivate the health. Instead of increasing one's knowledge in rebooting and health cultivation, becoming strong is unfortunately empahsized instead. This is comparable to martial artists stressing virtue, without virtue one is prone to get into trouble.

Some brothers are emaciated but are free from digestive troubles. As long as these brothers get the hang of how to work out, they will rapidly become stronger. Some emaciated brothers have big issues with digestion, where there is chronic diarrhea or poor absorption function. For these cases, I would advise to first bring the stomach back to normal and then do strength training, gaining weight will then be more reliable. Otherwise, if you have a poor stomach, firstly, your appetite will be poor and secondly, the absorption mechanism will not function properly, to gain muscle and weight will then be relatively more difficult.

For those emaciated brothers who want to become strong, I would advise the below summary:

-   If there are no problems with digestion and absorption, I recommend studying more professional bodybuilding knowledge. The best would be to find somebody to get you started on exercising, combine it with increased eating and the body will become strong rapidly.
-   For brothers that are suffering from digestive or absorption problems, it is advised to adjust digestion and absorption to normal and start to work out from there, body weight will then steadily increase.

## The issue of decreasing brain power

Lastly, let’s talk about the issue of decreasing brain power.

The phenomenon of decreasing brain power following masturbation is extremely widespread. TCM:  _“to the above, kidneys are connected to the brain”_. Masturbation injures the kidneys and so must also injure one's brain power. The main expression of this is that memory, concentration, thinking ability and comprehension all take a downturn in varying degrees, giving the impression that the person has become stupid, slow to react, lacking in patience, restless and easily angered. When brain power decreases, doing anything becomes an issue, this is especially true for students. Students need to take exams which place a high requirement on one's brain power. The reduction of brain power from masturbation is undoubtedly a disaster for students.

Normally, to recover brain power requires at least half a year of rebooting and health cultivation. The recovery of brain power is a gradual process and the below aspects will need to be met:

-   Strict control of the frequency of nocturnal emissions. Nightly emissions greatly injure the body and the brain power.
-   Determine to put a stop to sexual fantasizing. Fantasizing depletes the essence invisibly.
-   Learn to cultivation the health. One needs to put a stop to the various ways of damaging the kidney qi.
-   Actively exercise, emphasize aerobic exercises.
-   One may try silent meditation or standing horse-stance cultivation methods, including kidney strengthening exercises.
-   Nutrients need to be maintained, moderately intake brain nourishing food.

When the above 6 requirements have been met, the brain power will enjoy a substantial recovery after half a year. When the brain power is increased, the person will become like brand new. Previously incomprehensible topics will be suddenly understood when you look at them again, like having an aha moment. Actually, it is the lower brain power which was causing the incomprehension. Now that brain power has been recovered, the topic is understood with a glance. Determination, concentration, memory, and comprehension will all increase.

> “Absorb the mind to relinquish. From relinquishment arises calmness. From calmness, arises wisdom. These are known as the three learnings.”
> 
> — [Avatamsaka Sutra] scroll six

Rebooting has the ability to raise the level of wisdom. Buddhist philosophies are actually connected with TCM, the saying goes that all great paths lead to the same source. Once the brain power has been recovered, a change in destiny can be achieved. When the brain power is inadequate, everything you do will be inadequate. You will feel as if you are unable to get into the zone. When your brain power is good, the things that you previously did poorly become easier, your destiny will then change accordingly. Take an important exam, for instance, when the brain power is good you get one result and when the brain power is poor you get another result. Such an exam may change a person’s entire future. The same goes for job interviews, when the brain power is good one is unhindered in speech and is confident, when the brain power is lacking you may not even understand the question that was directed at you, spewing out an incoherent answer in return. Brain power is truly too important for a person, one must cut out masturbation.

## Afterword

Recently, I read a post made by the well known “Uncle Tom” and was surprised at his speed of advancement in realization. He was able to understand almost all of my posts and besides that was hunting extensively for other rebooting articles. The improvement of his realization also serves as encouragement for other brothers. There are already big changes in Tom’s thought process. I have mentioned this, the first step to rebooting is to reform the thoughts, you must give your awareness a tangible boost through studying. When the understanding has taken on a new level, rebooting will reach success easier. Otherwise, relying on brute force rebooting will only ensure failure.

The reason as to why I’m writing down my experiences is to allow more brothers to really understand it. Once understood, your awareness will increase. When confronting various rebooting issues, you will then have a reliable answer. Just like having to take a stabilizing pill, the mind will no longer easily sway, thoughts of doubts will no longer show up. Of course, there are lots of articles on rebooting and health cultivation, everybody should search for them far and wide, study broadly and without limit, constantly improving. My awareness and understanding come from thorough personal experience and ceaseless studies. To this day, I still take some time each day to study. I read Dharmas daily, read health cultivation articles frequently and study rebooting cases every day, constantly discovering, thinking and understanding.

In sharing the contents of my own insights, I hope that everybody’s’ awareness may constantly increase. Even if you only advance a little every day, a year later your overall progress will be staggering. The only worry is if you do not want to study or are fed up with studying. In that case, you will have a hard time making a thorough reboot. To reboot, the thoughts must be transformed. No matter which internet site you visit or which rebooting article you read, in every case you are importing rebooting thoughts and awareness, it is transforming your thoughts awareness. When you have recognized the importance of studying, you will go look for good rebooting articles on your own in order to constantly study, rehearsing old material while learning new material. Once you have gotten into a study mentality, awareness will increase by leaps and bounds. The more thoroughly your thoughts rewire, the easier it is to successfully reboot.

However, I need to stress a final point; when you have successfully rewired your thoughts and increased your awareness, it’s still important to maintain daily vigilance. The alertful awareness is very important, just like walking on a steel wire do not let go of the vigilance.

In addition, after your thoughts have been rewired, you will notice that you will be out of tune with the people around you because you have fully understood the truth of masturbation. You have seen masturbation for what it really is. While most people are still apathetically indulging themselves, fiercely rubbing themselves towards the road of self-destruction, completely oblivious to the approaching symptoms. Society today has been polluted by ideologies of pornography and sexual debauchery, in addition to harmlessness theories, therefore, the vast majority of the people are bound to not see the truth clearly. This precisely confirms the saying: the truth is controlled by a few people. We are bound to be the minority who know the truth. What we need to do is to find the proper timing and the method to help our brothers, to help our former selves and in the process help ourselves.
