# Impotence, the mystery of time to relapse and different forms of essence damage from masturbation

## Foreword {-}

Many brothers have now gained the awareness to keep studying on the rebooting forums, they are no longer relying on brute force rebooting and have started to tread onto the correct path. Their rebooting efforts have become increasingly professional, this is a very good phenomenon. Once the daily habit of studying rebooting articles has been established, where one is able to both read and understand, rebooting awareness and understanding will take a huge upward leap. This principle is actually comparable to internet gaming. If you play every day, your level will quickly rise. If you do not train, you will not advance and remain a rookie. In the aspect of internet games, one is abused by the opponent. In the aspect of rebooting, one is abused by the temptation demon. Because the level of the temptation demon is higher than your level, your level is too low, every encounter results in defeat. Therefore, one must increase one's level of awareness through constant studying. With awareness and understanding in place, the temptation demon will have a hard time budging you.

I hope more brothers will share their experiences in the rebooting forums. Rookies need guidance from forerunners. The most apparent trait with rookies is a large number of misconceptions that they carry that do not allow them to understand problems clearly. Experience posts will allow them to improve their awareness and lead them to the correct path of rebooting, solidify their confidence and determination, avoid detours and hence improve the rate of successful reboot.

### Only one model for successful rebooting {-}

After having researched into the topic of masturbation, I have come to realize that there is only one model for successful rebooting: increasing the level of awareness through constant study. When there is enough awareness, rebooting becomes natural. Once the awareness is very high, all that’s needed is to maintain vigilance and the reboot will be thorough. Cultivating awareness is like climbing a mountain, many people stop climbing halfway and go back down. Although lots of people are slow in their pace of climb, they persist in climbing and continue studying rebooting articles, constantly increasing their awareness. Although the pace is slow, they are steadily improving. In this way, these people are still able to reach the peak of awareness. When that time arrives and if they also strengthen their level of alertness, a complete reboot can be achieved.

My current level of awareness was accumulated step by step. In the past, I went about studying rebooting articles in the following way: everyday I would extract good rebooting quotes, this also included health cultivation related content because these two topics are interrelated. I had extracted over 6 books worth of contents within a year of time. The demand that I placed upon myself was to improve a little every day, after a month there would be a big improvement. Ever since I started to extract rebooting articles, my awareness soared. Many incomprehensible issues suddenly became clear, my mind gained clarity. Afterwards, I looked into a large amount of TCM cases,  and awareness again advanced forward. Nowadays, I find time every day to read about Buddhist Dharma and TCM, trying to increase my level of thinking. If you dont put any limits on studying there will be no limits on your improvement.

### On reading difficulty {-}

Many brothers claim that they cannot get into reading. As soon as they see a long article, they feel tired. After reading a line of text, they become fed up. There are many brothers like this. This is because brain power decreases when the kidney essence is deficient. Memory, concentration and even comprehension all drop lower. What’s worse is that the mood following debauchery becomes impatient and easily angered.  _“Troubled appearance”_  emerges, one lacks patience and determination when trying to do things and to study.

I have previously experienced this state of mind. Whenever I looked at a screen full of text, I would become annoyed and wanted to look away. After a period of rebooting, the brain power recovered somewhat and my mind was able to quiet down again, slowly I was able to absorb what I was reading. After I absorbed what I was reading, the more I read the more I wanted to read, I extracted what I thought to be the best quotes. Unbeknownst to me, my awareness took off. By often looking at previously read articles and extracted quotes, you will get a reinforcing and refreshing effect and allow the awareness to increase once again. When awareness has been raised to a certain level, you will notice that you now have resistance against pornographic content, you are able to vanquish the temptation demon. This, in reality, is the result of an increase in awareness.

As to the number of daily studies, I have arranged it in the following way: all according to my state, if my mental state is good during a day and the interest is high, I will read more, sometimes a dozen pages, sometimes an entire chapter. When my interest level is very high I read a big portion of a book. But sometimes my state is not that good and my interest is lacking, the amount of studying that I have planned for these times is at least a page every day. It only requires a couple of minutes to read through a page, no matter how impatient, one is able to endure reading through a page. In this manner I’m able to ensure that my daily studies do not halt, my awareness will then constantly increase, finally welcoming great uplifting in awareness. I would advise every brother to at least read a page of rebooting article every day, it does not have to be a new article, reinforcing old articles is also very good. Do not stray away from rebooting articles, you may also repeatedly read the contents that you have extracted, in doing this your awareness will improve very quickly.

Some brothers say that they like to look at pictures and not at long pages of text, they cannot absorb it and find it to be annoying! My recommendation is to wait until you have been rebooting for a while. Once the brain power has recovered somewhat, allow yourself to look at texts. Because the images that I have produced only serve as supplementary material, the most important content is still the text. One needs to professionally and systematically increase the level of awareness. It is necessary to look through a large number of articles. Pictures are only an assistance, articles are the main material, images are secondary, this point must be understood.

Back to the old saying: the extraordinary power of rebooting comes from studying! Without studying there will be no knowing, without studying awareness will not increase. With the progressive increase in awareness, you will conquer masturbation and vanquish the temptation demon.

We will enter into the main topic below.

In this season we will discuss in detail regarding the issue of impotence, the mystery of time to relapse and different forms of essence damage from masturbation, details can be found below:

## Impotence and premature ejaculation {-}

In season 6, I talked about the issue of impotence and premature ejaculation. Now that we are in season 25, we can look into the topic more comprehensively and in more detail.

Among all the questions I have answered, quite a few of them belong to the category of premature ejaculation, soft erections, and impotence. When the essence has been damaged to a certain degree, obstacles in the sexual function will arise. The symptom that I have experienced the earliest is premature ejaculation, this showed up roughly after 2 years of frequent masturbation. Later, I had soft erections, this symptom went on for over a decade. Because I loved sports at the time, had rhythmic resting and eating schedules, didn’t have any internet addictions and nor did I smoke, during those years I was still able to achieve an erection but the firmness was inadequate. Afterwards, when I started to stay up late and sat for long periods at a time, I encountered impotence. My impotence at the time was quite serious, I needed to expend a huge amount of effort. In addition, to apply strong stimulation in order to barely achieve an erection. Moreover, the firmness was lacking and I would quickly go soft, the lack in stamina was apparent.

When premature ejaculation appears, a man becomes panicky, because the sexual function is very important for men. The degree of panic is comparable to panic experienced during hair loss. When the sexual function is lacking, a man feels shame in front of ladies and lacks confidence. In addition, he worries about the wife cheating on him. Therefore, men who suffer from premature ejaculation bear huge psychological pressure, the mood of anxiety is heavy.

### The signals from the body {-}

The worst part is that many people don’t have TCM health cultivation knowledge. When premature ejaculation appears, their first reaction is to take supplements in order to strengthen the yang and become strong once again, not allowing themselves to go soft at all cost. Under this pattern of thinking, they go around looking for all kinds of supplements. Some supplements show a good effect in the beginning, but the body can also grow tired of supplements. When taking them often the beneficial effect is not apparent. When the body has grown weary, one then has to switch to another supplement. The end result is to have ingested many big brand kidney supplementing and yang strengthening medicine, but the body still remains in a weak state. In addition, there is a high chance of other bodily symptoms showing up along with impotence, the suffering is beyond words.

In reality, because these people lack TCM health cultivation know-how, they have misread their bodily signals from the very beginning. The ancient saying goes: the younger generation should not be ignorant of medicine. If you are ignorant of medical knowledge, you will stumble into misconceptions in many areas and make very bad choices, ultimately hurting yourself. When a man encounters impotence, this bodily signal is the body crying for help, telling you to not indulge any further. The principle is similar to when skin pores close when being exposed to cold temperature. Many people are unaware of this principle, once impotent, they instead take supplements and indulge themselves, lacking in rebooting and health cultivation awareness altogether. They do not understand that the best supplement is actually not leaking. Because of this, they have chosen the wrong path, relying on supplements to further indulge, the result as can be imagined is devastating. In the future there will be a chance of becoming completely impotent,  and even getting diabetes or having a stroke.

Because that kidney qi is inadequate, the body chooses impotence for the purpose of self-preservation. If you misread the signal and instead relied on supplements to indulge, the evil fruit will certainly be eaten. This is the price of ignorance.

When a brother encounters premature ejaculation, soft erections, impotence, he needs to learn to reboot and cultivate the health. If the symptoms are serious, it is advised to see a traditional Chinese doctor for treatment, taking herbal medicines will benefit the bodily recovery. But one must emphasize the cultivation of the mind, or else the intake of herbal medicine will likely help to fuel the desires, resulting in taking herbal medicine and indulging happening side by side. The act of supplementing from above while leaking from below is detrimental to the recovery process. If you cannot manage to reboot thoroughly but instead leak and supplement simultaneously, I can be certain that the treatment effect will not be optimal, not long afterwards you will again find yourself with premature ejaculation. We then have a predicament in our hands, as a matter of fact, there is a misunderstanding. If this misunderstanding does not get corrected, the result will be that premature ejaculation will remain after spending loads of money and taking a lot of medicine.

Therefore, to be able to cure a person’s premature ejaculation, one must first enlighten him, speak reason to him and let him understand the principles. Enlightenment will actually cure him, without enlightenment he will be finished in this life. Quite a few brothers have already depleted themselves prior to getting married. They have encountered premature ejaculation, their families are pushing them into getting married, this makes them fear marriage. Knowing the outcome, why did he do as he did?

### Don’t test {-}

Everybody should not lose hope, however, as premature ejaculation, soft erection, and impotence can all be recovered from. I have completely recovered due to the fact that my understanding was in the correct place. There was no misunderstanding in my consciousness, I put effort into health cultivation. Most importantly, I didn't do any testing, because testing will lead one back into the trap of masturbation. Everybody will certainly ask, how does one know that one has recovered? Actually, whether or not one has recovered can be observed from the quality of the morning erections. When the erection is firm and upright, the degree of firmness is high, this is the bodily expression of recovery. If you attempt to test, then it is very possible to relapse repeatedly, throwing away all previous efforts. Many people like to test, the result is that once having attempted, they are unable to stop and have again started to indulge.

### Time to recover {-}

According to my experiences, the recovery time for premature ejaculation and soft erections is approximately at least half a year. Impotence would require at least a year of rebooting and health cultivation. In order to recover, one must do well in all areas. The most important conditions are to control the number of nocturnal emissions and put a stop to sexual fantasizing. Once these two points have been achieved plus efforts are made in health cultivation, the sexual function will slowly recover. I have been through all of this, as long as you have the confidence and patience and constantly study to raise awareness, manage to thoroughly reboot and increase health cultivation awareness, the sexual function will be able to recover for sure. The only thing to be afraid of is misconceptions in thought, recovery will be very difficult in such cases. Premature ejaculation can be grouped as mild, medium or severe. If mild, the recovery time will be relatively fast, if severe, then the recovery time will be even longer and the difficulty great. But as long as one is persistent in rebooting and health cultivation and is doing well in all areas, it is still recoverable.

### Premature ejaculation due to nervousness {-}

In addition, some people suffer from premature ejaculation due to nervousness, when masturbating alone there is no problem. Western medicine blames this condition on psychological issues. Actually, the emergence of nervousness and the depletion of the kidney qi is inseparable, because the body and the mind are one. If the kidney qi has been depleted, corresponding changes will take place in a person’s emotional psychology. Some people have not suffered from nervousness in the past but after they started to masturbate they become nervous, irritated and easily angered. This, in reality, is the expression of depleted kidney essence. One may even become nervous while urinating and only been able to pass urine when nobody else is around. These types of nervousness obstacles may also be overcome through persistent rebooting and health cultivation. Once the kidney qi has been cultivated into abundance, the body and the mind will all return to their normal states.

## The mystery of recovery time if one relapses {-}

Below let’s talk about the mystery of recovery time if one has a relapse.

Very few people know about this field of knowledge. Firstly, one must be familiar with TCM medical principles. In addition, one needs to have consulted cases with feedback, only after thorough research is one able to experience this field of knowledge.

### The constant changes of yang qi {-}

Among the cases that I have researched into, quite a few brothers have remarked; why is it that every time I relapse, the time of recovery is different? Sometimes recovery will take place several days following a relapse, sometimes the symptoms will linger on for several weeks or even several months, why is it like this? To be able to answer this question, one needs to be familiar with the level of yang qi in the human body.

The level of yang qi in the body is different during different periods of the day. It also varies during the times of the month, it again varies with the seasons. If you have relapsed during a time when your yang qi level is low, then it will be relatively difficult to recover. This principle is actually very easy to understand. Suppose that you make a call when your phone balance is very low, it’s very possible that your balance will be reduced to zero after a single call, but if you make a call when the phone balance is very high then there is no problem.

The yang qi level in the human body also undergoes constant change, fluctuating between highs and lows, the overall pattern of change can be found below.

#### Daily changes

Between 11pm-1am the yang starts to become active, at noon the ying starts to become active. Hence in the way of the health cultivation, no sexual activities are to take place between 11pm-1am, in order to avoid the depletion of yang qi. This is because during 11pm-1am the yang qi is just starting to rise, like a tiny spark. Sexual activities during this time will greatly injure the yang qi, giving rise to symptoms more easily. Yang qi grows from 11pm-1am and becomes successively greater, reaching the zenith by noon and then declines. This is followed by the rise of ying starting from noon and its gradual increase towards the maximum at 11 pm. After that ying starts to decline and yang starts to become active, this is the cycle.

When it comes to exercise it is best to do it before noon. Because then the yang qi will be in the rising stage, exercising during this time coincides with the time of the Heaven, and hence the effect will be superior. Normally, towards the evening it is suitable to cultivate quietness, this is because the ying qi is heavy during the evening, exercising and sweating during this time greatly damages the yang qi. When everybody has understood this principle they will be in a better position to choose the time for exercising.

The 12 time periods in the ancient times:

-   Zi: 11pm-1am
-   Chou: 1am-3am
-   Yin: 3am-5am
-   Mao: 5am-7am
-   Chen: 7am-9am
-   Si: 9am-11am
-   Wu: 11am-1pm
-   Wei: 1pm-3pm
-   Shen: 3pm-5pm
-   You: 5pm-7pm
-   Xu: 7pm-9pm
-   Hai: 9pm-11pm

#### Monthly changes

Every month, the moon will have its brightness and dimness, waxing and waning. We can base the monthly changes of the yang qi on the changes in the moon. At the beginning of the month, the crescent moon is barely showing, yang qi is gradually growing and being released. The phase of the moon gradually becomes fuller and turns into the first quarter moon. In this stage of the moon as it steadily becomes rounder, the yang qi is in its most vigorous period of development and release, the vital energy inside the human body is likewise in its most active state. Once the full moon has passed, yang qi has reached its full strength and starts to give room for ying qi. Yang qi slowly goes into the accumulation stage as the phase of the moon gradually moves from fullness to deficiency. During the 22nd or the 23rd day, we have the third quarter of the waning moon. Past the third quarter the luminous surface of the moon gradually diminishes up until the 30th day, the moon vanishes from sight, only a shadow remains, this is the last day of the lunar month. The entire metamorphosis of the lunar phenomenon is in reality example of the change in the yang qi. Therefore, try not to engage in sexual activities when the yang qi is weak and the ying qi is heavy, or else symptoms may easily arise.

#### Yearly changes {-}

Summer solstice gives rise to ying, winter solstice gives rise to yang.

Spring gives birth, summer gives growth, autumn gives restraint, winter gives storage. The word cultivation actually only mentions ¼ of the health cultivation path. In addition, there is growth during the summer, restraint during the autumn and storage during the winter. Therefore, try to refrain from sexual activities during winter. Winter is a season for the accumulation of essence in preparation for the coming year. If indulgence takes place during winter, then the energy available for growth in the coming year will be diminished. Therefore, if you have indulged during winter in this year, then next year your body may experience symptoms. One should not indulge especially during winter. Because winter solstice gives rise to yang, yang qi is right in the middle of a weak state. Relapsing at this stage will easily induce bodily symptoms and is not favorable to the recovery process. Store essence during the winter, once stored, good health in the following year can be ensured.

In ancient times there was an understanding about selecting auspicious dates, nowadays it is no longer widespread. Many young people are unaware of the fact that only a selected few able people are truly able to understand the concept. Doing certain things during certain times is very important because there are deep principles behind it. When brothers relapse during different seasons, the speed of their bodily recovery is different, because the level of yang qi in the human body differs for every season. When you relapse during a time when the yang qi is weak, then you have committed a taboo, the body will have a difficult time recovering. When you relapse when the yang qi is flourishing then it is relatively easier to recover.

### Nine poison days {-}

Regarding times of relapse that are considered to be taboo, I believe that many brothers have knowledge of the  _“Nine Poison Days”_. Nine poison days, according to the Chinese lunar calendar falls on the old calendar date of the 5th, 6th, 7th, 15th, 16th, 17th, 25th, 26th, 27th. These 9 days been called the  _“9 poison days of the intermingling between heaven and earth”_. There are 9 poisonous days in May acting as taboo days for sexual indulgence! Therefore, there are customs in ancient times, in May the wife would go and visit her parents for a month, extra caution is needed during those 9 poisonous days. There is for sure basis behind these 9 poisonous days, it would be better to believe that they exist rather than not. Because according to my research, there is a lag effect to the retribution of relapsing. Sometimes the symptoms will not show up right away, they may show up after ten days or even after a 100 days. Because therein lies a butterfly effect and time is needed for this effect to develop.

We need to understand taboos and try not to violate them, this will benefit our health. Knowledge leads to strength, ignorance leads to aging. If you know to avoid violating taboos, then many dangers may be avoided. For detailed contents into this topic, I will recommend everybody to look into [寿康宝鉴] (**Shou Kang Bao Jian**). There are specific contents on  _“preserving life rebooting period and the taboo of heaven and earth”_. Understanding this area of knowledge is truly very important.

## Different degree of essence injuries

Lastly, we will talk about the different degrees of essence injuries induced by masturbation.

This topic has been suggested by a brother due to the many symptoms that he was suffering from. He doesn’t know how serious his injuries are and so he suggested to me to make a rough classification of the essence damage expressions, this way he may also gain some understanding for himself. If you have extensively researched into cases in essence injured victims, you will for sure discover that many people are exhibiting multiple expressions from damaged essence. There are many categories of injured essence accompanying the collapse in health, the symptoms are not singular. Below is my general categorization on the degrees of essence damage:

1.  **Urinary system illness**: prostatitis, urinary tract inflammation, varicocele, etc..
2.  **Respiratory system illness**: lung illness, including rhinitis, asthma, etc..
3.  **A serious decrease in brain power**: concentration, memory, comprehension decreases in varying degrees
4.  **Stone related**: kidney stone, urinary stones, etc..
5.  **Skin symptoms**: various forms of skin illnesses, including acne, hives, etc..
6.  **Hair issue**: hair loss and greying as the main factors
7.  **Digestive system illness**: enteritis, constipation, diarrhea, weak digestion and absorption, etc..
8.  **Frequent nocturnal emission issue**: frequent nightly emissions is also an illness
9.  **Ugliness issue**: too many forms of ugliness
10.  **Sexual function obstacles**: premature ejaculation, soft erections
11.  **Heart issues**: palpitation, premature beat, etc..
12.  **Waist pain soft legs**: waist pain and soreness, waist and knee soreness
13.  **Cervical spine issue**: different forms of cervical spinal issues
14.  **Tinnitus issue**: kidney deficiency induced tinnitus
15.  **Excessive sweating, excessive oil**: these two forms are quite common
16.  **Sight issue**: decrease in eyesight, eye floater, etc..
17.  **Other illnesses**: roughly over 100 forms, kidney deficiency gives rise to many illnesses

Even if many symptoms are not directly caused by masturbation, they will still be intricately linked to it, because kidney essence is the health currency of the human body.

Points 1-17 do not delve into psychological issues. Although they are not very bothersome for some brothers, they will make one’s life a living hell. Of course, these 17 categories are relatively general and can only be considered as a rough classification. Below are the main psychological issues:

1.  Anxiety  
2.  Depression
3.  Neurasthenia
4.  Autonomous nervous disorders
5.  Obsessive-compulsive disorder
6.  Paranoia
7.  Autism
8.  Phobia
9.  Hypochondria

Of course, the psychological issues that I have mentioned are not purely psychological but also contains some element of physical symptoms. For instance, the mood of anxiety is not the same as having anxiety, anxiety has a range of bodily symptoms. Once these illnesses are caught, many people want to die. Among those people who visit anxiety or depression support groups, many are very desperate. The symptoms of these illnesses are indeed very strange, everything is present. If you are not a victim yourself and talk with these victims, perhaps you will think that they are telling fantasy stories. Only those who have had personal experience will know what the sufferers are going through.

When I had anxiety and neurasthenia, I was in a state of despair and collapse on a daily basis, the thought of suicide came up multiple times. Because the condition was truly like a living hell, you will think that death may be preferable, normal people will not understand that kind of feeling. Some sufferers are afraid to go out or sit in a car, normal people wonder how they can be so timid. Actually, once injured to a certain degree, human courage will really shrink to that of a mouse, because the kidneys govern fright, fright injures the kidneys. When kidneys are deficient to a certain degree, a person will become very timid, as if a totally different person. Previously when I was ill I would not dare to venture outside. Now that I have recovered, I almost feel it to be unbelievable. How could I have been so timid before? I fully understand now, it is the serious depletion of the kidney essence, caused by sexual indulgence and staying up late at night which injured the nerves.

Therefore, if you belong to the 1-17 category, that is good, you will not wish to die that much. If you have additional serious psychological illnesses, the problem is then relatively serious, recovery time will be longer and the difficulty greater. Many anxiety patients are unable to recover in 5 or even over 10 years, they rely on medication all year around. In reality, anxiety and other psychological illnesses must require an awakening in understanding as a condition to recovery, medicines will be able to alleviate but not to cure completely. One must learn to cultivate the health and understand to treasure the kidney essence. Otherwise, although you are temporarily alleviated by medicine, symptoms will still easily relapse, because you have not recognized the true cause of the disease.

## Concluding remarks {-}

Occasionally, some brothers ask whether masturbation will lead to bad luck. From the surface, masturbation and luck are not really connected. In reality, a certain relationship does exist. Because masturbation will induce lower brain power. When the brain power is normal, many things can be managed properly. But when the brain power has decreased, many things that normally would not be a challenge cannot be managed properly. From the surface it seems like one’s luck has become worse. Take an exam, for instance, some people would say, why was I so forgetful at the time, why didn’t I think of it at the time, my luck is so poor. Actually, the root issue of this bad luck is due to decreased brain power. Because the brain power has decreased, you will be in bad shape, at this time our luck will naturally become worse.

Compare again to an interview. The first impression we give out to the interviewer is very important. But a person immersed in masturbation will lack spirit in his eyes, his demeanor will be like a ghost, even with the appearance of black eye rings and eye bags, a look of decadence, without confidence and feeling inferior. When such a person goes for an interview, the success rate will naturally not be high. Many brothers have been interviewed more than a dozen times without a single success, they blame their own bad luck. In reality, it is ugliness induced by masturbation, a lack of Spirit. If your vitality is abundant, looking radiant, full of self-confidence, the impression you give to the interviewer will be completely different. This kind of abundant vitality is able to affect the interviewer, he will think that you are very dynamic, and the company is in need of such dynamic and vigorous youth.
