# Rebooting fed up period, the issue of excessive sweating and the issue of vision

## The fed up period in rebooting {-}

The fed up period associated with rebooting is an issue that cannot be avoided. It is also an issue that must be overcome. Many brothers have already reported this issue to me.

If one frequents the rebooting forums often, then one will discover a phenomenon and that is coming and going of many people. Many people start out with a high level of determination when first starting to reboot, their enthusiasm is at a climax.  _“Mustering up courage during the first battle, courage declines in the second battle, courage is exhausted in the third battle”_  cannot be helped. Before several weeks have passed these people have altogether disappeared, they have returned to the past. Especially for brothers who have relapsed repeatedly. Once relapsed, their determination and enthusiasm will take a big hit. After a while of rebooting, they no longer feel like continuing. They do not see any hope except for despair and helplessness.

### Why do we feel fed up?

In reality, this is the fed up period in rebooting. No matter who you are, there will be a fed up period. This fed up mood is also prevalent in other fields. When you listen to a song for instance, in the beginning you like how it sounds. After listening to it for several weeks, you might get tired of it. The feeling that you once harbored towards the song cannot be found again, what remains is weariness and impatience. The same principle applies to diet. In the beginning, we like to eat a certain delicacy. If you eat it everyday, you may want to throw up after a while. The same with cell phones. In the beginning we really want to own a certain model. After a while of usage, our desire for it wanes. We think that the cell phone is not that special after all. The original feeling of enthusiasm is long gone.

We should put it like this: the human being is an animal that easily finds itself bored.

In the world of rebooting this is no different. Many brothers are tired of studying, tired of rebooting articles. They are too lazy to read and to study and are easily annoyed. Whenever the fed up mood shows up, it easily leads to relapses. This is like a squadron of soldiers having depressed morale. Many people don’t want to go to battle and want to become deserters. This kind of squadron lacks fighting strength altogether.

If you run into the fed up mood, you need to learn to cope with it immediately. Adjust the mood right away in order to allow the fighting spirit to regain its fullness. A squadron without morale is like a plate of loose sand. A squadron with morale will have strong cohesiveness, every soldier will be like a tiger coming down the mountain. Buddhist cultivation also pays particular attention to bravely forging ahead. No room for a slack mind and maintaining perseverance. But people can hardly avoid having a tiresome mood, this is because people have a laziness tendency. Therefore, whenever the fed up mood appears, we need to make immediate adjustments. Just like a watch that is going too slow, we need to readjust it to the correct time.

### Methods of adjustments {-}

Below we will talk about methods of adjustment.

Truth be told, I have also encountered the fed up mood, but I have learned to re-adjusted it rapidly. Herein lies a concept and that is the concept of emotional intelligence  _(EQ)_. EQ is the IQ of emotions, it involves self-control, enthusiasm, perseverance as well as self-propelling and the ability to self-encourage. EQ is different from IQ, EQ can be trained after birth, it can be gained through learning. When you have learned to adjust your mood through studying, then you will be in full control of your mood and not be controlled by it. A person’s mood may dominate one’s actions. Many brothers relapse due to emotions; the emergence of a bored and depressing mood is immediately channeled into masturbation for relief. If you have a high EQ and know how to adjust the mood, then emotional relapse will not take place.

Therefore, we must learn to adjust our mood, this is especially important in the path of rebooting. When the mood of boredom and depression occurs we will need to make immediate adjustments. When the fed up mood appears we will also need to correct it right away. We need to allow our fighting spirit to pull itself together once again, rebooting properly everyday.

Not only does studying rebooting articles lead one to become fed up but the same applies to answering questions. Jia Xing has reported to me that he has become fed up with answering questions, he has contemplated the thought of retiring. During this time, I advised him to emphasize recuperation, to not overstrain himself and to not answer too many questions when he is in a bad mood. Otherwise, if he attempts to answer questions when the mind is tired, he will become even more tired. Under this condition one will easily contemplate retiring, to quit whatever he is doing so to speak.

Studying rebooting articles works in the same way. In the beginning one is full of enthusiasm, you are able to take in a huge quantity of knowledge. But after a certain stage, you may grow tired of studying. When that time comes, you may make some adjustments; decrease the amount of intake, one article per day will suffice or read a couple of cautionary cases everyday. When not studying, take care to maintain a high level of vigilance, do not let the temptation take any advantage i.e. cut all thoughts short and then do not follow them. When this low period has passed you will once again be able to find that optimal rebooting state.

Specific adjustment methods are summarised below:  _(taking jogging as an example, I hope that everybody will have an easier time reaching an understanding)_

-   Whenever the fed up mood comes up, one needs to learn to redistribute the bodily strength, do not overstrain. Just like when running 1500m, when one is unable to run any further, do not stop, run slowly but keep going.
-   Learn to motivate oneself, motivating oneself is a form of mood adjustment, enabling one to pull together the emotions. This is comparable to when running while at the same time telling yourself: I can do it, I can finish it, I can make it.
-   When encountering adverse moods, allow oneself to maintain a positive and optimistic mood. Don’t get entangled in a depressing and decadent mood, cut it short, do not follow it. This is comparable to when one is no longer able to keep running, you want to give up, a voice is telling you that persistence is equivalent to victory.

I have mentioned before that during rebooting, sexual fantasizing is one obstacle. The other obstacle is frequent nocturnal emissions. These are the two tigers on the rebooting path. If you are able to conquer these two obstacles then half the victory is assured. If in addition you are able to assail the mood obstacle, then you will able to reboot more stably and for a longer duration.

## Excessive sweating

Below let’s talk about the issue of excessive sweating.

Brothers have raised the issue of excessive sweating quite frequently in recent days. Although we are in the beginning of Autumn, it is still very hot, the slightest physical movement still leads to sweating. When sweating, it must be established whether it is due to normal physiological reasons or pathological reasons. Pathological sweating is hyperhidrosis and is an expression that the central nervous system is out of tune. According to the TCM point of view, excessive sweating is caused by imbalances in the ying and yang. Excessive sweating at this moment is mainly due to seasonal factors. If you sweat just as easily during the other seasons then it is no longer normal, it is a sign that your body needs adjustment. Best to seek out a traditional Chinese medicine doctor and combine treatment with Chinese herbal medicine. Afterwards, persist in rebooting and health cultivation, the body will then slowly adjust itself.

Actually, when the body has been damaged to a certain degree, 2 conditions will easily appear:

-   Excessive sweating
-   No sweating

Excessive sweating is relatively more common while no sweating is comparatively less common. Illnesses induced by masturbation usually take on 2 extremes, some people secrete more oil, others have dry skin, the former case is relatively more common. Medical science clearly categorizes sweating: self-sweat, night sweat, head sweat, half body sweat, palm and sole sweat, etc.. The most commonly seen is self-sweat and night sweat. When it comes to self-sweat, it is when one sweats involuntarily. It normally takes place during the day when it is not that hot and there is no presence of physical activities. Night sweats according to medical science is sweating while sleeping during the night, upon awakening the sweating stops.

In masturbation induced kidney deficiency, regardless if it’s ying or yang deficiency, there will be the symptom of excessive sweating. Many people sweat in large quantities as if the entire body is being bathed. In TCM it is mentioned:  _“he who sweats, also losses essence”_. A large amount of sweating injures the yang. If the quantity of sweat is very high, it is highly unfavorable to the bodily recovery process. Therefore, brothers suffering from the symptom of excessive sweating would do well to seek timely medical treatment. Match treatment with Chinese herbal medicine in order to solve the issue of excessive sweating. I believe that your recovery process will take on another level and that the recovery will be more thorough and stable than it has been previously.

Some brothers ask, why does it feel good to have sweated during physical exercise as long as there aren't any feelings of discomfort. This only shows that your yang qi has not been damaged to a certain extent. When the injury is serious and you sweat profusely following physical exercises, it is very unfavorable to your health. Therefore, when the body is weak it is recommended to cultivate stillness, exercise will mainly take on the form of walking. The same principle also shares similarities with nocturnal emissions. Many people enjoy good health, one nocturnal emission will not bring about any feelings of discomfort. But some people have sexually indulged in the past, if they have a nocturnal emission, symptoms will immediately appear and they feel uncomfortable. This being the principle, once the damage has been sustained to a certain degree, many things are not as one had previously imagined them to be.

Of course, sweating in moderation is also beneficial to the body, it enables the expulsion of evil toxins, but excessive sweating will be damaging to the body. When people increase their exercise load, they experience nocturnal emission during the night and a return of symptoms. Therefore, when the body is weak, emphasize stillness cultivation. Once the yang qi has gradually become more abundant, moderate exercises may be undertaken, this will be beneficial to the recovery process.

I would recommend everybody to make adjustments according to their bodily reactions following exercising. Some brothers will not experience any discomfort after exercising. In this case, they may continue to exercise while paying attention to the intensity, more is not always better. Other brothers may experience discomfort after having exercised or the re-emergence of symptoms. This condition suggests that you are not yet suited for this type of exercises. One may choose stillness cultivation, decrease the number of physical exercises, do some Eight-Brocade qigong, take walks. Once the kidney qi has been accumulated into abundance, slowly pick up physical exercises from there while paying attention to moderation.

As to the many symptoms induced by masturbation, I recommend actively treating all of them and do not blindly request you to reboot and cultivate the health without treatment. Things that should be treated are to be treated. Combine treatment with rebooting and health cultivation and the recovery process will be relatively speedy. Of course, there are those brothers who do not take any medicines but rely purely on rebooting and health cultivation and have recovered. In this way, these brothers usually have great insight into health cultivation. When one has made the proper efforts into health cultivation, this is also very beneficial to the recovery process.

Although many brothers have undergone active treatment they have not paid attention to rebooting and health cultivation, treatment under this case will not be ideal. Because recovery depends on 30% treatment and 70% cultivation, health cultivation is the real key. Famous physicians in the past have always given advice to their patients such as: stay away from sexual activities, moderation in diet, arise and sleep early, do not overstrain, etc..

The reason why many brothers are unable to recover from chronic prostatitis after a long time of treatment is because they have not understood rebooting and health cultivation. Tens of thousands in treatment fees will not make them better. If you really understood the importance of rebooting and health cultivation then the result would be totally different. Chronic prostatitis that I’ve had for over a decade is completely recovered, tests are all normal and symptoms have disappeared. Therefore, if symptoms are present, treatment is needed but more importantly one needs to cultivate, or else full recovery will be difficult. Many people have temporarily recovered due to the use of medicines, once they indulge, symptoms immediately return.

## The issue of vision

Lastly let’s talk about the issue of vision.

> The eyes contain all the essence of the body. If the body is not healthy then the eyes will not have spirit.
> 
> — [太素脉]

TCM also mentions: The essence of the five viscera and six bowels are all contained in the eyes! And so a person’s eyes are a reflection of the state of one’s five viscera and six bowels. In addition, the kidneys conceal the essence and hold the quintessence of the essence from the five viscera and six bowels. Therefore, when masturbation has injured the kidney qi, the following changes will easily appear with regards to the eye region of a person:

-   Lack of spirit in the eyes
-   Lack of light in the eyes
-   Muddy eyeballs
-   Bloodshot eyes
-   Shrunken eyes
-   Eyelid changes
-   Dark circles and bags under the eyes
-   Sluggish eyes, ineffective eye movements
-   Hollowed eye sockets
-   Decrease in vision
-   Eye floaters
-   Conjunctivitis

Among them, the issue of vision is of relatively more concern among brothers, especially for those who are students. The decrease in vision is indeed a very big disturbance. There are many reasons for decreased vision, details can be found below:

-   Poor viewing habits
-   Overstraining of the eyes
-   Genetics
-   Addicted to masturbation
-   Illnesses with the eyes

Masturbation should not directly cause a decrease in vision but indirectly causes it. Although many people such as elementary school students do not masturbate, they still suffer from impaired vision and wear glasses. This condition is induced by genetics and poor viewing habits. Yet some people start off with excellent vision but suffer from a serious decline in their vision after becoming addicted to masturbation. The indirect reason should be considered in these cases. By also including poor viewing habits and the overstraining of the eyes, vision issues will easily arise. Through rebooting and health cultivation, the state of the vision will hopefully improve, discomfort in the eyes will also be alleviated. If a vision issue is very bothersome for you, laser adjustments in the future may be considered.

Normally, by being persistent in rebooting and cultivating one's health, a person’s eyes will once again regain spirit, determination and brilliance. Brilliance is a very subtle feeling, just like the luminance of a light bulb, some light bulbs are bright while others are dim. While a person has an abundance of yang qi, this is reflected in the brightness and brilliance of the eyes. On the other hand, there is the lack of vitality and dimness.

If you observe children you will notice that not only do they have great skin, an obvious quality, they have bright and spirited eyes as well. This gives out a clear and adorable feeling. But the eyes of grown-ups are much inferior. On one hand, their bodies have already been leaking. On the other hand their bodies have taken injuries due to their lifestyle habits such as smoking, staying up late at night and sitting for long periods at a time. These are naturally reflected in the eyes.

Back when I was addicted to masturbation, my eyes lacked spirit and determination, it was a feeling of lack of self-confidence. Nowadays I’m totally different, my eyes have once again regained spirit through rebooting and health cultivation. I’m more confident now and am able to look people in the eye.

I recommend brothers who suffer from vision issues to establish good viewing habits, limit the time that you spend on the internet, keep a good posture and distance when reading and studying, pay attention to rest. Afterwards, one must cut out masturbation, learn to cultivate the health and increase the intake of nutrients. In this way, the issue of declining vision will become effectively controlled.
