# Directly tackling long sitting, underestimating the enemy, foamy urine issue

## Foreword

### The harmlessness theories

The former big forum legend Mayan has made a post where he introduced his insights on rebooting. He also sorted out the course of development for the rebooting forums. Mayan is among the earliest figures in the rebooting forums and has made outstanding contributions to the community. Mayan’s personal experiences have been a helping force for many people and are worthy of respect. As to the discussions started by 75, it allowed people to see the reason to why harmlessness theories are running so rampant because behind it there are people or groups of people who are purposely spreading the harmlessness theories. Many of such theories are made up, then carefully disguised and labeled as research done by a certain country. Rookies who are ignorant are very easily misled by it. The discourse by Mayan and 75 will help everyone to recognize the true face of the harmlessness theories and the culprit behind them.

Actually, harmlessness theories have existed for a long time. I remember reading a magazine at the end of the 90s, there was an article which promoted the harmlessness theory. At the time, I believe that the harmlessness theories were a result of misconceptions from the author, unlike the theories today, with ever more exaggerated arguments and sensational contents as if one would die if one does not masturbate. Personal computers were not yet widespread during the end of the 90s, harmlessness theories could basically not be found, let alone the propagation of rebooting experiences. I was totally ignorant at the time. I remember seeing an ads for kidney supplementary medicine, there was a line on the product: deficient kidneys, a hundred illness will arise from it. That sentence was my only exposure towards the truth for over a decade of my life. In addition, kidney deficiency was the only thing mentioned, there was no mentioning about masturbation.

Nowadays is the age of the internet, more youth have the chance to come into contact with harmlessness theories via the platform of the internet. One could say the youth of today are fortunate but they are also unfortunate because this age is flooded with pornographic poison. Pornography existed in the 90s but is nowhere as flooded as it is today. Pornography is everywhere on the internet. Web portals are full of suggestive material while it is all too easy to download videos from the internet. Many youths have an internet addiction. Those with such addiction sit for a long time in front of the computer, this already has a damaging effect on the health. Combine it with the ravage of masturbation and the chances to encounter bodily symptoms becomes very high.

To successfully reboot one must clearly recognize harmlessness theories. In reality, this is the first gate of rebooting. Not clearly recognizing harmlessness theories will sooner or later lead one to sway. Many brothers become swayed when viewing harmlessness theories, their rebooting determination is no longer as firm. Therefore, we need to keep away from harmlessness theories, keep away from false wisdom and erroneous views.

### The moderation theory

The biggest flaw in the theory of harmlessness in moderation is this: it totally ignores the highly addictive quality in masturbation. Everybody thinks that they are able to achieve moderation but I can clearly tell you, ordinary people can in no way achieve moderation. Talking about moderation after becoming hooked is ridiculous.

In addition, not a single person knows where the line to moderation lies. Everybody knows that water boils at 100 degrees Celsius, but nobody knows how badly the body is damaged before the onset of the symptoms appears. Because everybody’s constitution is different, some people may not experience any symptoms while masturbating 3 times per week, others may run into symptoms while masturbating once per week. For that same person who masturbates 3 times per week, dare you say that he will not experience any symptoms 3 years down the road? 3 times per week will guarantee that he will not have any symptoms due to his good constitution. He is able to handle 3 years, but symptoms will appear in the 4th year.

Some people may say that they are able to limit the times they masturbate to once per week. What I want to say is, are you able to control sexual fantization? Sexual fantization is the invisible form of depletion. Normally, for people who masturbate, they are also addicted to fantization. He thinks that once per week is not a big deal. In reality, he is shedding more via sexual fantization. Just like that, without being aware of it, the symptoms have come to knock on the door!

### The state of the forum and my experiences

The first time I came to visit the rebooting forums was about a year ago. At the time, the forum only had a couple hundreds of members. Today the number is over 30,000. This is inseparable from the promotional efforts that everybody has put down. The booming of the rebooting forums is the result of everyone’s efforts. I have not communicated with Mayan but have had many exchanges with Potato. Although Potato is not a big poster anymore, he still frequents the forums. To have persisted until this day is not an easy feat for Potato. One needs to have overcome a lot of resistance to make it, it requires great willpower. The overall atmosphere of the rebooting forums has improved a lot since the early days. Already a group of knowledgeable and insightful brothers is on the rise, they are pushing the forums towards a better development. This is unimaginable in the early days when many questions would go unanswered, therefore the rookies of today are fortunate. The seniors of the rebooting forums have already paved the way for you. Upon entering, you are led onto the right path and is able to avoid many detours. Being rookies, you should all treasure the opportunity to study the rebooting articles and allow yourselves to reboot more professionally.

Back when I came to the rebooting forums, I noticed a phenomenon. Many threads were about the discussion of the harm from masturbation. There are also brothers who share their own experiences in order to warn others. But there were very few deep studies on the behavior of masturbation. There were also equally few guidances given on the specifics, many doubtful brothers were unable to gather a satisfactory answer. Everybody should know that once doubt arises one easily contemplates quitting, the arising of doubt also induces relapses. Back then, because I suffered from general anxiety disorder and neurasthenia, I have been researching into neurosis for a very long time. After having been chatting with over a thousand neurosis patients, having gone through a copious amount of comparisons and in-depth analysis on the pathogenic causes, a formula finally came up: staying up at night + indulgence + sitting for a long period at a time = finished. As long as the patient is male, this formula will more or less apply.

My research is based on a large number of cases and is not a result of guesswork. When doing any type of research it is important to collect first-hand case information. Through deep analysis, one may then come up with a certain pattern. Back then, I have chatted with over a thousand anxiety patients from all age groups, the oldest was over 50 and the youngest was 16 years old. Then I realized that indulgence is intricately connected with the said illness. Kidneys is rooted in the original qi, the spleen has its source in the prenatal qi. Indulgence damages the kidneys, long-term sitting damages the kidneys and the spleen, staying up late injuries the essences even more. These three factors are like hatchets hacking away at the tree of life, it would be very strange indeed if no symptoms appeared. Subsequently, I went from researching into anxiety syndrome to studying the behavior of masturbation because there are commonalities between the two. Up until today, I have chatted with over a thousand brothers, gathered in thousands of cases and have seen basically every symptom out there.

I have personally experienced many symptoms and have completely recovered from them. Not long ago, I was still in the state of ignorance and naivety. I thought there was no way to heal from prostatitis and that hair loss would also be difficult to recover from. Today, through the efforts made in rebooting and health cultivation, I have recovered from both prostatitis and hair loss. One sentence, if you want to get well, one must increase interaction with people who have recovered. If you always interact with those who had yet to recover then you will be fed with the thoughts of not being able to recover. My position is that the reboot must be thorough, health cultivation must be proper. Once both of these are in place there is the foundation to make a full recovery. One then combines these with active treatment and many illnesses are curable. If you cannot manage to reboot and cultivate properly, recovery will be difficult no matter what medicine you take. Even if you manage to temporarily recover, relapses will become highly likely.

I emphasize rebooting but I emphasize health cultivation even more. Those brothers who are following my articles know that I place a high importance on health cultivation. Because I have found out that rebooting is not a panacea, on the contrary, rebooting is only the beginning. Many brothers have been rebooting for 8 months and even for a year, their bodily recovery is not ideal, no huge improvements were to be seen. The reality is a lack of understanding in health cultivation. A lack of knowledge in health cultivation, too many leakages in other areas. I have been talking about this issue quite thoroughly in season 12, those friends who haven’t seen it may go and have a look. Quickly learn to cultivate the health as it will be quite beneficial to your recovery process.

Let’s take another example, although a brother has been rebooting for 2 years, he was unable to conquer frequent nocturnal emissions. After 2 years of rebooting his health is unchanged, this is bitterness beyond words. Therefore, following rebooting one must pass both levels of nocturnal emission and sexual fantizations, or else it is too unfavorable to the recovery process. Remember at all cost.

Let’s enter into the main topic below.

This season we will talk in detail about the issue of long-term sitting, underestimating the enemy and foam in the urine, the details can be found below.

## Long-term sitting

I have mentioned the issue of long-term sitting in season 7. Right now I feel the need to emphasize it once again. We may also go into even more details.

Once I found the following text in a book about health cultivation: “Illness takes place in between the moment when one puts and takes off clothes.” The meaning is that when you think it’s hot and removes your clothes, that’s when you catch a cold and become sick. What I would like to say is: sickness is also in between standing and sitting. Long-term sitting damages people in the same manner as the frog in the boiling pot. In the beginning, you may think it’s comfortable, unknowingly you are taking damage. Long-term sitting, just by the simple motion of sitting, the liver, kidneys and the spleen have been damaged.

Long-term sitting is surely accompanied by long-term viewing, otherwise, why do you sit for long periods of time? Long-term sitting injures the kidneys, the bladder channel comes under constriction. Long-term sitting injures the spleen, spleen governs the muscles, therefore long-term sitting also injures movement. Long-term viewing injures the liver because liver opens up in the eyes. Many people disapprove long-term sitting, actually, it was mentioned long ago in TCM that long-term sitting shortens the lifespan.

Furthermore, modern research in Western medicine has also confirmed this point. There are many articles about the harmful effects from long-term sitting from the Western medicine perspective. Many people are rebooting and have effectively controlled their fantasies, but their internet addiction is still very strong. They still have the bad habit of long-term sitting and viewing. The result being that after a half a year to a year of rebooting, the degree of recovery is still not optimal.

And I have noticed, long-term sitting produces a form of inertia. According to the saying of some people; it’s like a pair of invisible hands forcefully pressing oneself against the chair, unable to stand up, unable to stop oneself, before long several hours have passed. Therefore if we want to recover better, we must deeply recognize the harm from long-term sitting:

Obesity: When the caloric intake exceeds the caloric exhaustion, fat will easily accumulate inside the body, the bodily weight will increase. Obesity is a dangerous factor for causing chronic illnesses.

Cervical spondylosis: When a person maintains a long-term sitting position, the entire weight of the body is concentrated on the base of the spine. This combined with the immobility of the shoulders and the neck easily leads to stiffness in the cervical spine. In more serious cases, the cervical spine becomes deformed and induces bone hyperplasia.

Lack of appetite, poor digestion: The whole bodily movement is lacking during long periods of stillness sitting. This will induce weaker wiggle movement in the stomach and intestines, reduced secretion of digestive fluids. In time the appetite will become lackluster, with the appearance of poor digestion and even fullness symptoms.

Muscle shrinkage: Long-term sitting may cause the internal oxy-carrying blood to decrease, lowering of oxygen partial pressure, increase of the carbon-dioxide carrying blood volume, increase in carbon dioxide partial pressure, causing soreness, stiffness and shrinkage in the muscles.

Gynecologic diseases: Many women catch cervicitis not due to poor hygiene habits but is instead related to long-term sitting. Long-term sitting obstructs the generation of immune cells which causes lower immunity. This combined with the obstruction in the blood flow easily induces cervicitis and other related gynecologic diseases.

The lower of memory: Blood circulation slows down when one is sitting and not moving for long periods of time. This induces inadequate blood supply to the brain, damages the spirit as well as the brain, produces mental depression. This is expressed in the body and mental fatigue, dispirited mind, chain-yawns. Long-term sitting in contemplation exhausts the blood and injures the ying. This will induce a decrease in the memory and a lack of concentration.

Prostatitis: Investigation has shown that among patients with chronic prostatitis, office workers, drivers, IT workers etc with special regards to drivers (long distance drivers) make up the majority of the patients. In addition they do not recover easily, because people that do this kind of work needs to sit for long periods of time without moving.

Varicocele: Research has shown that long-term sitting can cause varicocele with the additional possibility of aggravating existing varicocele.

Injures the heart: Sitting for long periods of time without moving places a lower demand on the working capacity of the heart but may cause a decrease in its function, causing shrinkage in the heart muscle, contributing to high blood pressure and giving the opportunity to utilize the coronary thrombosis.

Injures the tendons: Long-term sitting without movement will cause the muscles to lax, impeded blood vessels and the clotting of blood. This will easily cause varicocele, hemorrhoid and sit sore. Because of long-term sitting without movement, almost the entire body weight is pressed against the buttock muscles, causing it to become “pressed to death”, becoming damaged due to impeded blood flow.

Injured muscles: Long-term sitting without movement and impeded blood flow causes the muscles to become stiff, sore, ache, shrink, losing its vigor and elasticity and causing spasms. Once, a person played cards for a whole night without moving, when he stood up he fell towards the ground. It turned out that long period of sitting without movement causes both legs to stiffen and become unresponsive.

Injuring bones: People that work for long stretches of time while sitting, due to the whole weight of the body being pressed against the bottom of the spine, improper posture, long-term immobility of the shoulders and the neck, these cause the top four vertebrae to stiffen. It also causes the drying of the vertebrae and induces various spinal diseases, the most commonly seen is hunched back and bone hyperplasia.

Injuring the brain: Long-term sitting without moving causes inadequate blood supply to the brains. It causes dizziness, blurry vision, the desire to vomit when one suddenly stands up.

Injuring the spirit: Long-term sitting without moving will cause a depressed mind, it causes a person to become listless, worn out, to chain-yawn. Sometimes it may cause weakened heart and excessive internal heat with the appearance of a tooth-ache, throat ache, tinnitus and constipation among other symptoms. In addition, long-term sitting will hinder the generation of immune cells.

Injuring the kidneys: Long-term sitting without moving will put pressure on the hips and the bladder meridian, impeding the flow of qi and blood, obstructing the normal function of the bladders. Since the kidney meridian and the bladder meridian are reflected off one another, the kidney function will also become affected. This is the principle behind “long-term sitting injures the kidneys”. And a deficiency in the kidney qi will slowly induce weakness into both the blood and the qi; with the onset of itchy skin, pale or dark complexion, insomnia, excessive dreams, irritable mood, constipation, a decrease in menstrual blood quantity, etc.. These problems will be reflected on the face as colored stains. The appearance of colored stains is the body trying to tell us: inside the body there are blockages of qi and blood, this is what TCM refers to as qi stagnation.

Long-term sitting causes the volume (circumference) of all the blood veins to decrease. A decrease in the heart function, exasperating the heart issues for the middle-aged and the elderly. Causing in advance arteriosclerosis, coronary heart disease and high blood pressure.

Long term sitting causes inadequate blood flow in the chest cavity, causing a further decline in the function of the heart and the lungs, exasperating heart and lung-related disease such as emphysema infection for the middle ages and the elderly, protracted illnesses, etc..

Long-term sitting will also cause inadequate blood supply to the brains, reducing the oxygen and nutrient supply to the brains, exasperating weariness for the body, insomnia, decrease in memory and increasing the chances of catching dementia.

Long-term sitting without movement will induce soreness in all muscles of the body, stiffness in the neck, headache and dizziness, exasperating lumbar and neck vertebrae illnesses.

Long term sitting will easily induce slower stomach movement, decreased secretion of digestive fluids, decreased appetite, exasperating belly bloating, constipation, indigestion and issues with the digestive system.

Long-term sitting may cause the venous plexus around the rectum to become congested in the long term, increasing the degree of clotted blood and thereafter exasperate the hemorrhoids, causing blood in the stool, anal cracks, etc..

Because that many middle-aged to elderly people often remain in a static state where one is not fond of talking, long-term sitting will speed up the decline of their speech function, as well as causing the reactionary speed of the brain to slow down. This is consistent with the “use and disuse” theory.

Long-term sitting will also induce psychological depression, unprovoked bursts of anger, a poor state of mind, show decreased interest to the outside world or showing no interest altogether.

Long-term sitting easily incurs kidney stones, gallstones and similar problems.

I have extracted and summarized these 24 points. Basically, all the harm from long-term sitting is contained herein, there is a statement: long-term sitting may kill! This statement is not meant to scare people, this boiling the frog way of killing people is without shape and form, unbeknownst to you your health has been weakened. Furthermore, some people are quite clueless and are not aware of where the problem is coming from. Reports from the World Health Organization has found, each year there are over 2 million people whose death is related to long-term sitting.

Long-term sitting will give rise to illnesses. It will bring one closer to the God of death. Is this true? It is, this is absolutely right! However, more and more people are sitting down and for longer durations. Some people have been observing, office workers sit on average for at least 5 hours each day, the duration for continuous sitting is over 2 hours on average. In addition, we should not forget about those who work with IT and driving.

Some brother would ask, I cannot help my working schedule which requires sitting everyday, what can I do? My answer is, every 40 minutes get up a move a bit, set a computer alarm. There is dedicated alarm software online that are available for download, everyone may go and download one. It will remind you to move around when it is time. In addition, I can reveal my own methods. At home I surf the internet while standing up, I just put a chair on the table and in this way I avoid sitting for long durations at a time. However, there would appear a new problem and that is standing for long durations. TCM: long-term standing injures the bones. Therefore, I would normally stand for a while and then sit down for a while. I found this method quite much suits me. Everyone who is interested may give this a try.

Other brothers would ask, does meditation count as long-term sitting? Meditation is a state of practice, there are indeed masters who are able to enter a meditative state for few hours or even for half a day, even for a few days. Because it is a special state of practice, normally it is harmless. I would recommend meditating for 1 hour each day. You may also set up a plan according to your own circumstances. If you have reached that particular statement, entering the meditative state for few hours at a time will not be a problem. Naturally I have also seen an article that dealt with harmful effects from meditating for long durations. In that article, it is said that sitting for long durations in the double lotus position will easily give rise to foot and leg problems during old age. The person who wrote that article was a person who was famous in the Daoist circles. He has profound experiences, everybody may give consideration to his advice. Nowadays, I mainly rely on loose sitting or single lotus as meditation posture.

There is no way to over-exaggerate the problem of sitting for long durations. I hope that everyone may deeply recognize this problem. While rebooting, I recommend to exercise actively, but pay attention to the intensity, more is not always better. Practice has proven: those who often perform aerobic exercises recover relatively more quickly and more optimally.

## Underestimating the enemy

In the below, we will deal with the topic of underestimating the enemy.

Threads about underestimating the enemy appear from time to time on the rebooting forums. An example of the argument would be: rebooting is very easy, rebooting is very easy. The brothers who normally make such a thread are all in the desire-hibernation period. Those who have read season 4 will know after the desire-hibernation period is the high season for relapses. Many brothers during the desire-hibernation period are able to control their addictions. The desire is not strong and sexual fantizations are few. For some people, the hibernation period only lasts for a few days. For others, it lasts for a month or so. During such a period, many people harbor an attitude of underestimating the enemy. They feel that rebooting is not hard at all, that they are rebooting just fine. Their threads reflect this attitude.

If everyone is observant, they will for sure notice that not long after the thread was made the contents have changed to something like: I was too confident, I have relapsed. I was too careless, I have relapsed. The underestimating attitude from the beginning has turned into post-relapse regret. The saying that the arrogant army will surely face defeat. Chairman Mao has once said: underestimate the enemy in strategy, pay attention to the enemy in tactics. We may underestimate our temptation demon when it comes to strategy, but when it comes to tactics we may emphasize the enemy. If rebooting was that easy, why do so many people repeatedly relapse? Moreover, many people are postgraduate students, they all have high IQ. To paraphrase a TV dialogue: You underestimate rebooting! To be successful at rebooting one must systematically study rebooting knowledge in a professional way. Constantly increase rebooting awareness and realization. Only in this way is thorough reboot made possible.

## The foamy urine issue

Let’s talk about the foamy urine issue.

Many brothers have asked about and experienced the issue of foamy urine. The formation of foam in the urine is mainly related to the surface tension of the urine. Normally speaking, the higher the surface tension in a liquid, the easier it is for foams to form. Under different circumstances, changes in the composition of the urine such as protein, mucus, organic material will cause an increase in the surface tension of the urine, foams will then form easily. Is lots of foam in the urine a sign of disease? This requires analysis into different situations.

As to the phenomenon of foamy urine, we will need to analyze if the reason is due to physiological or pathological reasons.

If the reason belongs to the below conditions, then the increase of foam in the urine is not due to diseases.

There are semen substances in the urinary tract: when semen substances are present in the urinary tract for men, this may cause foam in the urine. Retrograde ejaculation (often seen among diabetes and autonomic nervous system disorder patients). Frequent arousal will increase the mucus production in the glands of the urinary tract. Following nocturnal emission, etc..

Over-rapid urination: during rapid urination, the urine forcefully comes into contact with the surface of the water, air and urine are intermixed, foams will form easily but will disperse easily. In addition, by standing at a position that is too high, under the influence of gravity, the force of impact from the urine onto the surface of the water will be relatively high, foams will easily form.

Concentrated urine: under the circumstances of decreased fluid intake, profuse sweating, diarrhea, the inadequate water content of the human body will cause the urine to become concentrated, causing the protein and other contents to increase within the urine. This will easily cause the urinary foam to increase.

Other causes: disinfectant and detergents within the urinal is another reason which would cause the formation of foam in the urine.

When foam appears in the urine from time to time, this often has physiological cause and the cause will be found in most cases, such as over-rapid urination, concentrated urine, etc.. If foamy urine disappears by getting rid of the above causes, and in the absence of abnormal symptoms or illnesses, then there is no need to become too worried.

The below circumstances should give rise to alert:

Proteinuria: the abnormal increase of protein content in the urine is one of the most common causes for foamy urine. It is also a clinical expression for various diseases and especially when it comes to kidney diseases. Various primary kidney illnesses, such as glomerulus, kidney inflammation etc and various kinds of secondary kidney damage, such as diabetes, high blood pressure, gout, hepatitis, etc.. will all cause kidney damage and increased protein in the urine. Although the kidney function is normal under the cases of multiple myeloma, acute hemolysis, leukemia, etc.., due to the emergence of a large amount of abnormal protein in the blood, protein will also leak into the urine and lead to proteinuria. Foamy urine will normally occur during proteinuria. The special characteristics for the foamy urine is a layer of floating foam that are miniscule in size and would not disperse after a long time.

Urinary system infection: Infection in the urinary system may cause increased foam in the urine. Commonly seen cases are urinary tract infection, cystitis, prostatitis, etc.. In the majority of cases, there are accompanying symptoms such as frequent urination, the urgency to urinate, pain during urination, etc..

Increase in urine sugar: The presence of organic substances (glucose) and inorganic substance (various mineral, salts, etc..) may cause increased tension for the urinary fluid and hence the appearance of foam. But the foams in this case are rather big and disappear quickly. Due to an increase in urinary sugar for diabetes patients, secondary urinary sugar increases, foam urine will likely occur.

I have encountered foamy urine myself. Normally, the foam would not go away after a long time, one then considers the possibility of internal inflammation such as prostatitis. Naturally, if the intake of protein is excessive, the foamy urine situation would also appear. If foamy urine occasionally appears then there is no need to worry. If the issue is persistent or occurs often, then it’s best to do a checkup at the hospital.

## Afterword

Frequent nocturnal emission is indeed a watched topic among brothers during the rebooting phase, everybody wants to minimize its frequency. I was once like everybody else, I have searched for countless methods to prevent nocturnal emission. Throughout my personal experiences, I finally chose the kidney strengthening exercise from the Eight Brocade Qigong. The above-mentioned exercise is supported by TCM theories in addition to having undergone many peoples’ experiences, its reliability is quite high. Kidney strengthening exercise is not only effective against nocturnal emissions, it is similarly effective against seminal leakages. I have introduced the kidney strengthening exercise in season 3. There have been many feedbacks from brothers and many people have indeed managed to decrease their number of nocturnal emissions, keeping the number within once per month. This frequency is advantageous to the recovery process.

Naturally, there are many brothers who have tried the exercise with unchanged results. One aspect to consider is not to perform the movement properly, another is the failure to avoid the other factors which give rise to nocturnal emissions. If those other nocturnal emission inducing factors are not avoided, then even if one has been doing the kidney strengthening exercises, one might still encounter nocturnal emissions. For instance, if a brother has done the kidney strengthening exercise but over-exercises and becomes fatigued, then during the night he will still have a nocturnal emission. Some brothers cannot keep sexual fantizations under control, the issue of nocturnal emissions still cannot be resolved.

Recently on the forums, many brothers have shared ways of reducing the frequency of nocturnal emissions, with regards to these ways we may give them a try. But please remember, do not put all hope into one method. Because if you are not careful in avoiding other factors which induce nocturnal emissions, nocturnal emissions will still take place. I have specifically written a season on these other nocturnal emissions inducing factors, everyone may take a look for reference.
