# Withdrawal reactions, curved penis issue, semen changing color

## Withdrawal reactions

I have mentioned withdrawal reactions in my previous article. Lately, many newcomers have come to ask about withdrawal reactions. I get an absent-minded kind of feeling, a feeling of time and space dislocation. The rebooting forums have already experienced turnover, newcomers are constantly entering, the questions they ask have all been asked by the seniors. Previous rookies have turned into rebooting veterans, the situation has already emerged where the old are helping the new. We will thoroughly talk about withdrawal reactions in this season in order to eliminate any concerns from the newcomers, solidify their rebooting determination, I think this is necessary.

While rebooting, the first psychological threshold that one must pass through is the one about harmlessness theories. On the physical level, the first level that one must pass through is withdrawal reactions. The majority of the brothers will encounter withdrawal symptoms within a month of rebooting. Before rebooting, the symptoms are not apparent, instead the symptoms show up during the reboot. Many people panic when the symptoms first appear, they immediately think about harm from self-restraint. They immediately think about the adverse effects that self-restraint has on prostatitis. The result is falling back into the trap of masturbation. This is withdrawal symptom in reality.

Normally by persisting in rebooting, withdrawal symptoms will gradually diminish and even disappear. If rookies are not aware of and do not understand withdrawal symptoms, then they might harbor thoughts about quitting. Because he is nervous and afraid, indeed, it is an unpleasant feeling to be entangled by withdrawal symptoms. But as long as one is persistent, withdrawal symptoms will come to pass. When withdrawal symptoms appear, pay attention to cultivation, don’t overstrain, one may perform some moderate exercises. Normally the recovery of the body will improve ever more once withdrawal symptoms have passed, the condition being of course that you have learned how to cultivate the health, to actively exercise. In this way, there is a guarantee for making a recovery. Don’t always sit down, otherwise the speed of recovery will be very slow.

I have researched into many addictive behaviors. Normally after cutting out an addictive behavior, some symptoms are bound to appear. Withdrawal symptoms are relatively common in the world of addictions.

Take quitting smoking addiction for instance: smokers after having forcefully quit smoking are likely to encounter restlessness, impatience, chest tightness, coughs, short-term forgetfulness, lack of vitality, fat gain, shivers, insomnia, increase in appetite, coughing black-greyish phlegm, higher blood pressure, in addition to arrhythmia, etc.. Withdrawal symptoms resulting in great suffering. But these kinds of symptoms in the majority of cases will gradually diminish as the body recovers.

Take cutting out alcohol addiction as another example: after cutting out alcohol the psychological symptoms are expressed as anxiety, depression, irritability. Heavy users experience hallucinations, illusions, delusions, obstacles in awareness, etc.. Symptoms of the nervous system are expressed as palpitations, chest tightness, profuse sweating, etc.. and autonomous nervous system symptoms. Heavy users may encounter tremors, twitches, an eruption of epilepsy, etc.. Stomach symptoms are expressed as nausea, vomiting, stomach pain and diarrhea, etc..

Withdrawal symptom is a form of adaptive rebound. Normally, by persisting in rebooting, symptoms will gradually disappear. Normally, the symptoms during rebooting are expressed as:

Mood obstacle: poor mood, easily agitated and angered, decadent and pessimistic, loss of interest.
Sleeping obstacle: many brothers report having sleeping problems during rebooting. Problems such as difficulty in falling asleep, insomnia, excessive dreams are relatively common.
Bodily symptom: illnesses with urinary systems are commonly seen, such as aggravation of prostatitis.
Other brothers may encounter soreness and pain in the waist, lack of energy, discomfort feeling over the entire body, disappearance of morning erection, increased hair loss, changes in semen, etc..
Do not panic or be afraid when encountering withdrawal symptoms. Reboot well, emphasize cultivation and the symptoms will quickly pass. This is a threshold, everybody needs to go through it.

## Curved penis

Let’s talk about the issue of a curved penis in the below.

I have chatted with over a thousand brothers, not many of them report having a curved penis, but once in a while a few people would show up. Indeed this problem cannot be underestimated as it will affect a person’s self-esteem. Let’s first take a look at 2 cases:

Case 1: male, 25 years old, unmarried, no sex life, penis curved to the left, the angle of the bend is considerable since a few years back. Due to the embarrassment he is never made a visit the hospital for treatment.

Case 2: Soaring Eagle, my penis bend to the left at about 20 degrees. The urination stream leans towards the left a bit because of masturbating with the right hand in the past. What can be done about it?

Among the brothers that I have come across, some have their penises bending towards the left, some towards the right, some even have an angle of bend of 45 degrees towards the right. There is an article from abroad about rebooting which talked about that masturbation would induce the penis to bend towards the right, but one needs to also look into the specific case.

Many people have the vile habit of masturbation and yet they do not run into this issue. I think masturbation is one of the causes, the appearance of a bending penis should be due to a combination of factors. For example, if you masturbate during development and it is directed towards the left or towards the right, or by applying pressure on one side while rubbing, while the penis is under development this will very much likely influence the direction of its growth. Just like a small tree, by bending it when it’s still small, what will the result be? It will grow along the bend, once big it will still be bent. Yet big trees do not have this problem, because their orientation of growth has basically matured.

How to treat this problem once it has arisen will depend on whether or not it affects your self-esteem. In addition, how it will affect your future sex life. If it is affected, the doctor would normally recommend a correcting procedure. Therefore, for those brothers who suffer from this kind of issue, they should seek immediate treatment and listen to the professional advice of the doctor. At the same time, do not masturbate anymore, make effort in cultivating the health, too many symptoms are caused by masturbation. When symptoms appear it is actually a bit late. TCM advocates curing yet-to-be illnesses, we should work on prevention before it happens!

## Semen color

Lastly, let’s talk about semen color.

Normally after kidney qi has been damaged by masturbation, changes will take place in the semen. Extremely many people report changes in their semen, everybody should have encountered this problem. Normally the below situations will appear:

Change in color, turning very yellow or greenish yellow
Non-liquidation of semen, the appearance of crystal or jello substance
Bloody semen, this is caused by many factors, common reasons are inflammation and stone
Semen becomes thin and less, decrease in stickiness
Seminal discharge becomes greater and more concentrated, this is also a state of illness, pointing to the presence of inflammation
Decrease in the quality of the sperm (no sperm, dead sperm, low vigor, deformity, etc..)
Among the articles that I have read, there was 2 sayings regarding the normal color of semen:

Milky white or light yellow
Greyish white or light yellow
If strictly speaking, milky white is not normal, it points to the possibility of inflammation. From looking at everybody’s question, the appearance of crystal and jello substance are relatively common. Next common is the yellowing of semen. If it is light yellow then it is normal. If it is very yellow or a greenish yellow then attention is required. Some brothers will encounter bloody semen with the semen having red or pink in it. If bloody semen appears, it is recommended to immediately seek to diagnose and treatment at the hospital.

When first starting to reboot, changes will easily take place in the semen, this can be seen as a withdrawal reaction. Following persistent rebooting and cultivation, the quality of the semen will slowly improve. Moreover, if health cultivation is not emphasized then changes will easily take place in the semen, such as heavy drinking, smoking, long-term sitting, staying up late at night, exposure to AC, etc.. Maintaining excellent lifestyle habits is very important, it has a direct impact on the health.

In TCM theories it is mentioned: “Sowing the seed, the man must first cultivate the sperm”. If one wants outstanding offsprings, the man should take good care of the body, cut out whatever is needed to be cut out, cultivate the quality of the sperm. By doing this, will the offspring become quite healthy. Many brothers have had their sperm checked, some brothers have encountered weak spermatosis. There were also cases of azoospermia. Other cases include a lack of vitality in the sperm, dead sperm and quite a few cases of deformed sperm.

Normally the main reasons for a lacking quality of the sperm are prostatitis and varicocele. While masturbation is able to induce these two illnesses, the quality of the sperm will then become affected. Many people are addicted to masturbation, it has resulted in vastly lower sperm quality. Some have encountered infertility. Although some are still fertile, if they continue to masturbate they might unfortunately end up becoming infertile. Therefore, there are a hundred advantages in cutting out masturbation and not a single harm. By not cutting out masturbation, there are a hundred of harms and not a single benefit. If we really try to find benefits in masturbation, masturbation allows you to release emotions and pressure which allows you to relax. But the consequence is to sink into the vicious cycle, the loss outweighs the benefits.

I hope that everybody is able to persist in rebooting and health cultivation, nurture the quality of the sperm, preserve the best of you for marriage. Do not at all cost discard yourself before marriage. Sperm is the seed, with a good seed will your offsprings be healthy. If the seed is not good, your offspring may suffer from a poor constitution with the appearance of many illnesses and even the chance of premature death.

## Afterword

While replying to a thread, I saw a brother mentioning: the marriage between man and woman is the necessary relationship between the sexes. Male and female cannot thrive alone, it’s the way of the nature that they are compatible with one another, this cannot easily be discarded. This brother has cited ancient marriage cultivation theory, there is a certain truth to it. But if one does not have ample experience and lacks own thinking and understanding, one might think why practice self-restraint? Wasn’t it mentioned that male and female cannot thrive alone? Would self-restraint lead to shortened life? By staying away from women and thus not mixing the sexes, wouldn’t the male stop thrive? If I lacked ample experience, this is what I would also think. But I have do thoroughly understand TCM theories and have come to realize that the above quote is not absolute, there are pre-conditions involved.

In TCM it has been mentioned: lack of essence leads to disease. It has also been mentioned: the overuse of kidney essence leads to disease, if kidney essence can be preserved, the penis will be firm! After seeing the above sentence everybody may wonder, doesn’t this contradict “male cannot thrive alone”? I will make an example so that everybody may understand. Master Empty Cloud has never touched a woman during his entire life, he lived to be 120 years old. Not a few Buddhist practitioners have lived to be beyond 100 years old. If the saying goes “Male cannot thrive alone”, then if monks do not touch women, how can they live to be over 100 years old? In Taoist cultivation, total self-restraint was also mentioned. Since ancient times, not a single Taoist immortal has leaked essence. Bai Yuchan has said: “not a single drop of semen is leaked, this is the ladder towards the heavens”.

Therefore, “Man cannot thrive alone” is not the absolute truth. It does not suit the monk. For the ordinary man, it is quite suitable. This is because the heart cultivation is not yet in its proper place for the ordinary man. There is sexual fantization as everybody knows, it is not good to hold in fantization. Sexual fantization is an invisible form of leakage in itself. Many brothers have encountered repeated symptoms following sexual fantization. Monks have properly cultivated their hearts and so do not have this problem.

However, the ordinary man should not go and have sex as soon as the idea pops up, he should look at his own bodily condition. If the body is weak and is wrapped in symptoms, self-restraint is needed in order to cultivate the body. Once the kidney qi has been cultivated into abundance and the health is totally recovered is he able to live out a controlled sex-life. Many famous physicians during ancient times have required patients to keep away from bedroom affairs, or else the body will have a hard time recovery and the efficacy of the medicine will also suffer. Nowadays many Chinese traditional physicians no longer mention these things, it is very regrettable.
