# Rebooting condition adjustment, obstacles in development, emission due to nervousness

## Foreword

### On sexual fantization

Recently when browsing the forums I saw that many brothers have relapsed. The reason being that they couldn’t get past sexual fantization. To be successful in rebooting, sexual fantization must be conquered. Put in another way, if you are able to put a stop to sexual fantizations, then you are halfway there, your record rebooting streak will take a big leap forward! If you are not able to conquer sexual fantizations then what awaits you is repeated failure. It is not scary to fail, what’s scary is to not learn. Only through constant studying in raising the awareness, to ceaselessly summarizing lessons are we able to improve our rebooting efforts. Do not be discouraged after a failure, we need to look at our own progress. In raising the awareness, there is a process. Once your awareness has been cultivated then rebooting will come naturally. Hence the saying: when conditions are right, success naturally follows!

Time is of the essence when cutting out sexual fantizations, it is important to first become aware.

Some brothers have asked me, what to do when the flames of desire are burning? Will do push-ups help in suppressing the desires? My answer is this, you are too late in stopping the fantization. At the beginning the thought is like a tiny spark, it is easy to put a stop to it. Once the spark has turned into a prairie fire, a flame of desire, it is too difficult to put it out if you wanted to. When you notice the fire after it has been greatly developed and you want to put it out, then it is very possible to have the opposite effect: the more you suppress it, the stronger it grows and bounces back.

The new thought need not be feared, late awareness is to be feared. One needs to become aware of the new thought of sexual fantasy during the first 0.01 seconds. End it immediately, do not hesitate, do not compromise, be decisive, be direct and efficient! End it early! End it firmly! End it quickly! If you don’t vanquish the temptation demon, the demon will vanquish you, there is no third option. If vanquished by the demon then symptoms abuse awaits!

With regards to sexual fantizations, my article in season 17 have described it in detail, everybody may look over it again. Among my articles, season 17 is an important one because it deals with how to cut out sexual fantization. By passing through the barrier of sexual fantization will rebooting become more steady by the day. Otherwise, even if one has been rebooting for a long time, failure still remains, one is still unable to vanquish the temptation demon.

An illustration from my previous season have shown, rebooting is like playing chess. The person sitting in front of you is the temptation demon. This is the same as real life chess. When you first play against an expert, there is only room for defeat. No matter what you do you will be defeated. This is because the opponent is an expert and has abundant actual combat experience, while you are a rookie that is ignorant about everything, in addition to harboring many misconceptions. Under this circumstance, how can one defeat the temptation demon? The temptation demon is at a higher level than you while you are only a rookie.

In reality, there is only one way to defeat the temptation demon and that is to ceaselessly study to raise the level of awareness. Once your awareness has been cultivated, your level raised, and you battle the demon once more, then you will notice that the temptation demon is no longer a match. You are able to vanquish and defeat the demon. To be able to successfully reboot is a process of constantly raising your awareness. Once you have the awareness to study and have formed excellent studying habits, you are not far off from successfully rebooting.

### Transparent liquid during erection

There is another issue and that is while the penis is erect, out flows some transparent liquid, what is this? Among the articles that I have researched into, there are 2 sayings; the first is pleiotropic fluid, the other the fluid secretion by the urethral glands with a lubricating property, some brothers call them lubrication. Urethral gland fluid is transparent and sticky, it may be elongated into thin threads. It has the property of lubricating the urinary tract and constitutes the first substance in ejaculated semen as well as being part of the seminal fluid. And pleiotropic fluid is an important part of the seminal fluid.

Therefore, no matter which of the two liquids is flowing out, they will actually both cause harm to the body. Many brothers run into symptoms after fantasizing without masturbation. Sexual fantization is an invisible form of leakage. TCM has mentioned: “when the mind wanders, essence leaves”. Among the TCM medical cases that I have gone through, there have been records of sexual fantization leading to illnesses. Sexual fantization is able to induce illnesses, this is very true! To find out the effects from gazing without masturbating, you can take a look in the mirror and you will notice that your complexion has been decreased. There is a good chance to encounter pain in the testis, swollen feeling in the lower abdomens or frequent urination. These are the consequences of invisible leakages from sexual fantization, it is the conclusion from many brothers. Everybody needs to persevere in putting a stop to sexual fantization and achieve total reboot!

In the below we will enter into the main topic.

In this season we will describe in detail the adjustment of the rebooting condition, development obstacles, and emission to due to nervousness, specifically.

## The adjustment of the rebooting condition

Lately there are many brothers who have been reporting having poor rebooting conditions, such as the emergence of weariness, laziness, low in moods, loss of movement and related phenomena.

I have also encountered these kinds of conditions. The emergence of this type of behavior is intricately connected to the season of the year, “spring weary, autumn tired, summer doze off, winter unable to wake up”. The changing of the seasons deeply affects a person’s psychology and physiology. It is not difficult to understand that we get tired during the day in the summer when the weather is sizzling hot, not allowing a good rest in the evening. But why do we still experience tiredness during the clear and refreshing autumn weather? This is because during the sizzling hot summer, the human body sweats profusely causing an imbalance in the water and salt metabolism, weakening function in the intestines, places a heavier burden on the cardiovascular system. The human body is placed into a state of over-depletion.

Following the end of the summer and the coming of autumn, the climate turns from sizzling hot to be cool and pleasant. Bodily sweating noticeably decreases, the human body enters a resting phase of a cyclical nature. The salt and water metabolism starts to recover towards balance, the burden on the human cardiovascular system also finds a relief, digestive system also improves by the day. Yet during this time there is an unexplainable feeling of weariness in the body. This is what is often referred to us “autumn tiredness”. In reality, this is the natural human physiological response towards the different seasons. After a period of adjustment, the weariness will also naturally disappear.

Therefore, if you are recently in a poor rebooting state, the advice is to emphasize cultivation, don’t over-strain yourself, emphasize mood management. Slowly it will pass, the good rebooting state will return. One must learn to adjust oneself, this is especially important. The rebooting state of a person goes up and down, this is very similar to the up and down of an athlete’s condition. Merritt is now clocked at 12.8 seconds, could he make the same time again next time? Maybe the condition will have fallen back. Rebooting works in the same way. In the beginning many brothers gain a tremendous amount of determination. After having read a few rebooting articles, their determination runs high. But after a dozen days, the enthusiasm is lost, the motivation nowhere to be found. When reading articles one binge reads, when not reading one has not read an article in weeks. There is no persistence in raising the awareness in this way. Like climbing a mountain where one gives up halfway.

Therefore, in order to be successful in our rebooting efforts, one must keep up a stable rebooting condition. When first starting out our enthusiasm is running high, we can take in a higher number of articles. When the enthusiasm has waned, we should not stop reading altogether but to decrease the number of articles. Read some rebooting articles on schedule everyday just like brushing the teeth. Form the habit and the habit will become natural. Given a stable rebooting condition, the steady raising of the awareness can be guaranteed. Just like playing a video game; one doesn’t simply play one day and then rest for a dozen days, but rather one plays everyday in order to level up quickly. Of course, I’m not in favor of being addicted to internet gaming, I only use it as an example.

Main factors that induce a change in the rebooting condition can be found below:

Rebooting fed up period: The season 26 article specifically mentions this.
Seasonal factors: The turning of the season may affect the psychology and physiology of a person and from there influence the rebooting condition. This is easily neglected.
Having read harmlessness theories: Swaying easily forms after reading harmlessness theories. This is followed by doubt and the thought to quit arises.
Planning when doing things: Brothers who plan will be able to reboot more steadily. He will know the number of planned studies for each day.
Trivia in life: If there are many trivialities then they will easily cause a distraction. Or if the mind becomes weary then one no longer wants to read articles.
Pressure from work and studies: When under big pressure a person’s emotions will easily become disorderly and from there affect the rebooting condition.
Have wife or girlfriend: The rebooting condition for these brothers is very difficult to stabilize. Specifically why that is everybody should know without I have to mention it.
Environmental pollution: For example, somebody watching porn in the bedroom, or due to confirmation to social niceties one needs to visit such places, these will all affect the rebooting condition.
Following emission: There are many cases of relapses following emissions. It is easy for the mind to waver following emissions. One needs to maintain vigilance.
Dietary factors: The emergence of wild fantasies is made easier by overconsumption in meat and medicines. The rebooting condition will then become affected.
If we want to be successful in rebooting, we must keep our rebooting condition steady. Just like walking on a tightrope, we need to maintain stable, find the point of balance, there will then be stability and longevity in rebooting.

## Obstacles in development

Below let’s talk about obstacles in development.

Among the thousands of cases I have gathered from sufferers and the thousand of brothers I have chatted with, many have reported development obstacles. These are mainly concentrated in the below points:

Penis development obstacles
Height growth development obstacles
Appearance development obstacles (looking much younger)
I believe that everybody can easily comprehend the first 2 points. On the third point, surely people will ask, isn’t looking younger a good thing? Actually looking younger isn’t necessarily a good thing, many brothers are fretting over this. When looking younger than one’s peers people may not take one seriously. Furthermore, a person in his 20s who looks like a high school or middle school student will encounter difficulty in finding a job in the future. The employer will think that one is not mature enough and not up to the task. When looking younger is mentioned here, it is not looking 1-2 younger but 5+ years. After one has started to masturbate, one’s appearance will take on one of two inclinations, the first is to have aged in an obvious way, the other is delayed development with a young looking appearance. Both outcomes will cause distress, while turning older and uglier following masturbation is the more common outcome.

Development obstacles with the penis are relatively commonly seen. The penis is linked to the liver. While masturbation hurts the liver and the kidneys, this will affect the development of the penis. Some people have a naturally weak constitution, if they are wildly addicted to masturbation, the result will be that the development of the penis will be affected. The phenomenon of smallness and shortness will then emerge, making them feeling self-inferior. Many brothers are under 10 cm, some are even under 8 cm, some are too skinny which is also a very troublesome issue. At the onset of development obstacles with the penis, one should immediately cut out masturbation, pay attention to health cultivation. Things will alleviate this way, at the very least the quality of the erection will improve.

I have specifically talked about height growth obstacles in season 8, those brothers who are worried about height may have a look. Many factors influence height growth, masturbation is among one of them. Being addicted to masturbation have the possibility of affecting bone growth, because according to TCM: kidneys govern the bones. Being addicted to the evil habit of masturbation will induce obstacles to the growth of the bones which will then affect height. But not all people who masturbate will have their height affected. This is because many factors play a role in height, masturbation being one of them. If the other factors are properly managed, such as eating well, exercising properly, sleeping early, excellent genes, one may still reach the optimal height under these circumstances. But what is sure is that masturbation will affect bone density. Masturbation will induce soft legs, during intense exercises, broken bones or bone fractures will easily occur.

Masturbation indeed affects development. But everybody has a different constitution. Different dietary, exercise and living habits after birth led to the difference in how the body is affected. Some people love to exercise, have a lack of bad habits, sleeps and eats properly with proper nutrition. Although he masturbates, the impact on the body is relatively mild. While some people have a naturally poor constitution, this combined with long-term sittings and staying up during the night, lack of exercise, poor diet, serious development obstacles may arise under such circumstance. Therefore, for the guys that are still undergoing development, they need to realize the danger from masturbation as soon as possible in order to avoid tearless sorrow in the future. After the development phase is over things becomes fixed, many things will then be hard to alter.

## Emission due to nervousness

Lastly, let’s talk about emission due to nervousness.

Emission due to nervousness is quite commonly seen. Brothers with this type of problem will often appear.

I know that nervousness will induce emissions. During middle school I remember taking a midterm exam, a student had an emission during the exam because he still had unanswered questions. But the time was already up, he became nervous and had an emission. At the time, this event was talked among the students as an odd story, people thought this was unbelievable. Now that I have done research into masturbation behavior, I have come to realize that emission due to nervousness actually occurs a lot.

Everybody may first take a look at a few cases:

Big brother Soaring Eagle! I would like to inquire: during the night I did not have an erotic dream but the dream was about an unfinished exam. As soon as I started to worry, I couldn’t hold it back and had an emission. Does this count as a nocturnal emission or semen slippage?

Brother Soaring Eagle, I’m a 4th-grade university student and I’m about to take the National Judicial Exam. These past months have been extremely tormenting. I have started to reboot since the beginning of the year until now, there have been many relapses. Due to nervousness before the exam, I have had nocturnal emissions 4 days in a row including last night. I have lost hope for the future, please help me! If I continue to leak my whole being is done for!

Brother Soaring Eagle, I had nocturnal emission last night, I wasn’t able to hold out for 100 days. After my emission, I was very disheartened. The emission occurred during dreaming. I dreamt about being selected by the teacher to sing, I didn’t know what to sing, became nervous and had an emission which woke me up, it was only half past four. I was very disheartened at the time. I no longer hold the same excitement as I previously had. I will still continue to make effort, persist in doing kidney strengthening exercises and fight towards the next 100 days.

The classmate from middle school that I have mentioned would have nervousness induced emissions while being wide awake. Many brothers would have emissions while being nervous in their dreams at night or during intense nervousness in the day. Thoughts fill the day, dreams fill the night, nervousness induced emissions may also occur during the night. When these situations occur, do not panic. One must learn to manage one’s emotions, give oneself plenty of positive suggestions and don’t overthink.

In addition, combined with persistent kidney strengthening exercises and active treatment, these type of nervousness induced emissions can be overcome. I remember there was a brother who would always have emissions due to nightmares, this has always bothered him. Afterward, I advised him to engage in active treatment and persist in practicing kidney strengthening exercises, to manage the mood during normal times, to maintain oneself in a state of tranquility. Subsequently he reported improved emission rates compared to before.

Quite a few people became distracted once they become nervous. With thoughts in turmoil, during this time you should tell yourself: breath deeply, keep calm, maintain serenity in the mental state. Give oneself more suggestions of this nature, with time, nervousness will naturally be overcome. Keeping calm is very important. If you are able to maintain calm and collected, this will slowly affect the subconscious, when that time comes, the occurrence of nervousness induced emission during dreams will slowly decrease and even disappear. This is a knot, you must learn to untie it instead of becoming ever more nervous by it.

## Afterword

Many brothers have the mindset of turning negative emotions into masturbation. In other words, whenever setbacks or worrying matters show up, one immediately finds an outlet through masturbation. Brothers with such inclinations must learn to manage the mood and correct this erroneous attitude of behavior. In the season about types of relapses, I have specifically talked about relapse due to mood. This type of relapse is too common but the harm is really too great, it will let you sink into the evil spiral. Properly managing one’s mood is a necessary factor towards successful rebooting.

Some brothers are scolded by their parents, they then experience great emotional pressure, upon return to their rooms they relapse. Some brothers are scolded by their boss, they lose control of their emotions and are not able to think clearly, they relapse upon returning home. Some brothers relapse due to optimism, such as after the national high school exam, once relaxed they relapse. Or in connection with celebrating success, after a successful celebration, a person will be inclined to relax. Then there is the boredom mood, being alone at home during the weekend, the temptation demon springs forth, relapse happens without one being fully aware. Relapse due to the mood is too common, we must realize the importance of properly managing our mood, manage our mood well in order to make ourselves reboot more steadily.
