# Getting straight to the issue of anxiety, neurosis, digging deep into neurosis

## Foreword

### On prostatitis

In recent days, I came upon a thread. A brother suffering from prostatitis mentioned that he had abdominal pain and that the pain would go away every time he had an ejaculation. My advice is to not place hopes in alleviating inflammation through ejaculation through masturbation. Prostatitis should be promptly treated, the condition should be kept under control followed by persistent health cultivation, this is the way to recover the health. Otherwise, by relying on ejaculation via masturbation in order to alleviate inflammation, it will only cause you to sink into an evil spiral, your body will collapse one step at a time, prostatitis will never be cured.

In treating prostatitis, the guiding ideology must be correct. Treating prostatitis mainly relies on cultivation, after it comes treatment. 30% treatment and 70% cultivation. Treatment will keep the state of the illness under control, after that, one will need to rely on health cultivation. If you lack awareness in rebooting and health cultivation then there is a high chance for prostatitis to relapse.

The reason for the relapse rate of 90% for prostatitis is due to errors in the guiding ideologies, thinking that medicines will be able to cure it. The truth is that the root issue of prostatitis cannot be cured by relying on medicines. Prostatitis is cured through cultivation, one must learn the way to cultivate the health and establish the awareness on rebooting and health cultivation. In this way, prostatitis may slowly be cured. The normal recovery time for prostatitis patients is around one year.

If you take medicine while simultaneously engaging in masturbation, no amount of spending will be able to cure the illness. Many brothers have been spending tens of thousands on treatment, they have employed many different kinds of treatment procedures and advanced equipment but to no avail. They have not understood rebooting and health cultivation and so have spent their money in vain, their bodies still haven’t recovered.

Doctors will not be able to tell you why you are not healed. Partly, it is because they bear misconceptions in their thinking and advocates the harmlessness theories. In the other part, some doctors do not wish you to be healed as this will bring in extra revenue for the hospital. In many hospitals, the doctors would receive kickbacks, do you think that he will tell you about the harmful effects of masturbation? (Translator’s note: the phenomenon where doctors receive kickbacks for medicines sold is a conflict of interest and unfortunately a common occurrence in China).

### On morning erection

Furthermore, everybody is very concerned about the issue of morning erection. Actually, this could also be explained by the secretion of testosterone. Normally around 5 am, the secretion of testosterone reaches a climax, the morning erection phenomenon would then occur. During puberty, the secretion of testosterone is especially abundant, morning erection could possibly take place on a daily basis. I remember when I first entered puberty, for a period of time I indeed had a morning erection everyday. Afterward, I became addicted to masturbation, the occurrence of morning erection become considerably less frequent until it totally disappeared at a later date.

Of course, many factors have an influence on morning erection such as dietary factors, lots of meat consumption, eating lots of kidney replenishing food, morning erections would easily appear in such cases. There are also psychological factors, the mood is intricately connected with the morning erection. This point is easily ignored by many people. The mood may influence the secretion of testosterone and through it affect morning erection.

For example, you run into unhappy circumstances in life, this pessimistic mood will then induce lower testosterone secretion, morning erection could possibly disappear as a result. Mood and hormones affect one another, many times a depressed mood is associated with imbalances in testosterone secretion, hormones will in turn affect a person’s mood and behavior. For example, a person wakes up today and is in a very good mood, there is pleasure in the heart. But a dozen days later the mood suddenly turns depressed, this actually is closely associated with the internal secretion of hormones.

A woman during menopause, along with the steadily declining function of her ovaries, lower estrogen, this will result in changes in both her appearance and mood. Apparent mood changes include sensitivity, doubt, irritation, being easily angered and other negative moods. Males also have menopause, during menopause and along with lower testosterone levels, the mood and the body will also encounter a series of changes. Thus the saying that the mood and the hormones interacts and affects each other.

Another significant factor which affects the secretion of testosterone is exercise habits. Moderate aerobic and strength exercises will promote testosterone secretion. Every morning following doing barbell squats in the previous day, I have had morning erection. Squats are able to promote the secretion of testosterone, aerobic exercises may also raise the level of testosterone secretion. But there is a condition and that is to not over-exercise. Over-exercising will lead to lower testosterone regardless of whether it’s aerobic or strength exercise. All forms of overexertion will induce lower testosterone secretion.

Seasonal factors cannot be ignored either. It is now autumn, the time of the year where testosterone secretion is at its highest, I feel a much greater number of morning erections during this time.

If looking from a physiological point of view, one could say that human nature is based on hormones. The human body will secrete over 75 kinds of hormones, they all have their roles to play in the human body. Women with a higher hormonal concentration in their bodies look much younger than their counterparts with lower hormonal concentration. Males with abundant testosterone secretion also have much higher initiative and aggression compared with ordinary males.

Some brothers would say, will morning erections return after rebooting? He is addicted to masturbation and has not had morning erections for a long time. My answer is that morning erection will recover if there is persistence in rebooting and health cultivation. Previously, I had lost morning erection for a time. Afterward, it returned after I was persistent in rebooting and health cultivation.

Some other brothers would ask, will masturbation lead to an increase or a decrease in the secretion of testosterone? Actually, it is very easy to answer this question. The issue of imbalance caused by masturbation basically takes on two extremes. After some brothers become addicted to masturbation, their testosterone secretion decreases, such as myself. After I started to masturbate, I noticed less beard. While some brothers experience more proliferate growth of beard and body hair after they had started to masturbate.

The reason to why the two extremes exist is related to the individual constitution. TCM classifies people into 9 types of constitutions. The hormonal imbalance following masturbation will be determined by the constitution of the individual. For some people, it is expressed as an increase in testosterone secretion. On some people it is expressed as a decrease in testosterone secretion. An increase in testosterone secretion is actually not a good thing, it would easily lead to the possibility of male baldness.

Among the cases that I have seen, it is more common to see a decrease in testosterone secretion following masturbation, this takes up roughly 70% of the cases. The remaining 30% is when testosterone secretion increases following masturbation.

As to the issue of morning erection, everybody need not place a strong demand on having a morning erection every single day. With the increase in age, you will notice that morning erection will steadily decrease. Morning erection is related to numerous factors, we need to understand to let nature take its course and not to insist upon it.

Nowadays I’m not concerned about the frequency of morning erections but on its quality. A good quality morning erection beats 100 poor quality ones. Persistent and firm morning erections are good erections, it can also be taken as a sign of recovery for premature ejaculation. Premature ejaculation is not to be tested casually, its recovery can be observed from the quality of morning erection. If you attempt to test it then it is very possible to once again sink into the trap of masturbation.

Although many people experience morning erections, their quality is very lacking. Lacking in firmness and in duration with inadequate hardness and stamina. Moreover, the erection that many people experience have a sexual fantization element in them and are not morning erections in its true sense. Furthermore, morning erection while holding back urine is also not morning erection in its true sense.

In the below we will enter the main topic. This season topic: getting straight to the issue of anxiety, neurosis, digging deep into neurosis. The specifics can be found below.

## Regarding neurosis

Neurosis, as it is known, might be foreign to many brothers. This is because many brothers have not yet sustained such degree of damage, they have a difficult time understanding what it is like to have neurosis. Those brothers who have yet to experience neurosis may gather a general understanding from herein, broaden one’s scope of knowledge and alert themselves.

Neurosis is a dividing range for those who suffer from damaged essence. Once the nerves have been damaged, recovery will be a relatively slow process. Mild neurosis is easier to recover from, severe cases will require at least a year for any hopes of recovery. Awareness is required in order to recover from this disease. Complete recovery is extremely difficult by relying on medicine alone. Many people have not understood properly, they have not figured the whys. Just like entering a maze and getting stuck in it for several years and even for over a decade. Relying on daily medications to sustain themselves, their quality of life taking too big of a hit.

Many especially severe cases will give rise to suicidal tendencies. In the media, there is often news about depression and neurosis patients committing suicide. Some have both fame and money, with assets amounting to the billions and still commits suicide. Ordinary people have a hard time figuring out why people resort to suicide? Actually as soon as one has severe neurosis, many people will have the thought of suicide. I have also had such thoughts about suicide. At the time, I lived in a symptom hell everyday. Those who have not experienced it will indeed have a hard time experiencing the feeling. It is a big devastation towards the body and the mind. Many people after having neurosis experience big changes to their personalities, almost as if two separate persons.

At the time, I had separately encountered phobias (social phobia, AIDS phobia, cancer phobia), hypochondria, obsessive-compulsive disorder, anxiety, neurasthenia, gastrointestinal neurosis, cardiac neurosis. My head was also drowsy, had a headache along with wandering stinging pain in the entire body. It simply pained from hell, torture. When lying on the bed I would always feel an earthquake, later I found out that it was a feeling of severe body tremors. My muscles also twitch randomly, I had almost collapsed at the time, not one spot in the body was comfortable. Previously, I had not believed in hell on earth, after having neurosis I believed in it. Bodily symptom hell is indeed a great torment.

A huge emphasis is placed on experience when it comes to neurosis. If you lack the experience you will have no ways to truly understand the feeling. This is like me trying to explain the feeling of bungee to you. You will only hear me describe but have not tried it yourself. Your experience and feeling will not be profound in this way, neither will it be intuitive. Many doctors have not had neurosis, their understanding of neurosis comes from textbooks. I can conscientiously say that many theories found in the textbooks are not complete enough. Western medicine in particular is still in the research stage in this area. Therefore, many people will have inadequate understanding towards neurosis, this includes many doctors. An undeniable fact is that there are many quacks, doctors who truly understand are extremely few in number. Being able to stumble upon one such doctor after having seeing dozen of them can be counted towards your good fortune.

It is common for neurosis patients to be misdiagnosed. Some patients feel discomfort in their heart, they are getting treated for having heart disease and not for having neurosis. After having undergone treatment for the better half of the year and having spent tens of thousands in treatment costs, the illness remains without too much of a change. At last, they realize that they have neurosis while all previously they have been misdiagnosed with heart disease. Therefore, neurosis patients have a thing or two to say about doctors.

With regards to neurosis, my recommendation is to go to see a traditional Chinese doctor. There are too many effects in Western medicine and they easily cause dependency. Many patients become reliant on medicines and become addicted to them, they do not feel at ease when not taking the medicines. In reality, they don’t feel much better after taking the medicine, they are struggling bitterly in a vicious cycle.

The common illnesses induced by neurosis:

Chronic pharyngitis, oral ulcer
Irritable bowel syndrome, colitis, chronic gastritis
Neurological headache, dizziness, insomnia, excessive dreams
Depression, anxiety, fear, compulsion, hypochondria
Excessive sweating, sweating due to weakness/anxiety, night sweat, fear of cold, fear of wind
Cardiac neurosis, gastric neurosis
Stiff neck muscles, joint migratory pain, imagined limb pain
Poor memory, slow reflexes, neurasthenia
Premature ejaculation, catches cold easily, decreased immunity
Some neurosis patients mainly suffer from gastrointestinal neurosis. Some mainly suffer from cardiac neurosis. Some feel severe discomfort in the head region, others have many and all possible symptoms. Among the patients that I have chatted with, many people have over a dozen or even several dozens of symptoms, they come in all shapes and forms. The pattern of the symptoms is that they show up one after the other in innumerable succession, making one very panicky. As a matter of fact, there is only one source: the disorderly function of the autonomic nerve causes the disorderly function of the immunity system.

What is it that causes the disorderly function of the autonomic nerve? I was very perplexed at the time and was constantly looking for answers. At last, after thorough research and having chatted with over a thousand patients, I have come up with the formula: staying up at night + debauchery + long-term sitting = finished.

Debauchery alone would require a certain amount of damage before the emergence of neurosis. After over a decade of masturbation, I only had prostatitis and varicocele. Although I had turned a lot uglier, my nerves were always in good condition. Afterward, I started to sit for long stretches of time, stayed up during the night, ate poorly, that’s when neurosis appeared. One should put it in this way, the emergence of neurosis is the aggregate result of many factors. For female patients, neurosis is induced by anger, big pressure, staying up during the night and psychological stimulation such as family turning hostile.

### Truth or false neurasthenia

Due to addiction to masturbation, many brothers have experienced a large decrease in memory and comprehension. Under these conditions, some brothers feel as if they have neurasthenia. According to my observations, many brothers merely suffer from a decrease in brain power and not from neurasthenia.

I have selected a few typical expressions of neurasthenia, everybody may make a comparison:

Male, 25 years old. Due to a chance encounter at the age of 12, I came into contact with masturbation. After 2 years of masturbation, there appeared symptoms of discomfort: dizziness, tinnitus, exhaustion throughout the entire body, insomnia, dim sight, a feeling that the world in front of the eyes isn’t real as if living inside a dream, soreness in the waist, depressed spirit, tight chest with short breathe, flustered heart and heart palpitations, decreased memory, darkish yellow complexion, drowsiness and worn out, hair loss on both sides of the temples, sweat inside the palms and the soles of the feet, shapeless stool, also urinary diseases such as frequent urination, incontinence.

Hello big brother Soaring Eagle, I have been masturbating for at least 10 years. I’m 21 this year. During the end of May this year, I suddenly felt that my brain power was inadequate, absent-minded, a hollow feeling towards the entire world. Because I was preparing for the postgraduate exam, I felt very helpless at the time. My body has always been healthy where I have often played ball. I have come to realize that I should have neurasthenia. When it was the most severe, I was unable to fall asleep during the night. I slept a little over 2 hours each night, had night sweat. I lost 5-6 pounds in weight, especially from the back region. My stomach was still fine. The lower eyelids suddenly become dark. During the day, I felt that my eyes weren’t working optimally. The eyes were constantly under heavy pressure and made it hard to open them. It was if I was drunk during the daytime. My god! I don’t dare to imagine. At the time, I dared not to go out to the streets for fear of being hit by a car…

I’m 20 this year and my body is turning thin and yellowish. 5 years ago, I started to masturbate without moderation. In the beginning, there were no symptoms, but a year later I experienced a sudden sinking feeling at the back of my head while climbing the stairs, then I started to feel dizzy. At first, I thought it was caused by my fever but the symptoms remained without alleviation until this day. During the last 5 years, I grew old and weak with each passing day, strengthless body, depressed spirit, decreased memory, unable to focus my attention, quality of sleep was abysmal. Slowly, I turned into a useless person. I have also seen many doctors and taken lots of medicines but to no avail.

### Being grateful to anxiety disorder

Although anxiety disorder gave me tremendously painful experiences, I still need to be grateful for it. Because I wouldn’t be the person I am today had it not been for my illness. Anxiety disorder helped my growth, it is because of it that I started to study TCM on my own. It helped me to understand life, to increase my awareness to a new level. It is a blessing in disguise, anxiety disorder has transformed me. I was introduced to this path via illness. According to my knowledge, Master Hong Yi or Li Shutong has also suffered from neurosis. Neurosis was one reason to why he left home, an abstract can be found below:

Today I read about the tale of Master Hong Yi, in Gao Shengjin’s [My Experiences of Becoming a Monk at West Lake]. It is known in the beginning the reason to why he become a monk while fasting: suffering from neurosis. It is said in the text: “The 5th year of the Republic of China has arrived. Because I have seen in a Japanese magazine about the methods of fasting, that fasting may cure various illnesses, my curiosity was raised and I wanted to try it. At the time I was suffering from neurosis, by practicing fasting, whether or not I could recover is yet clear.”

## The experience of nearing death

Neurosis, in serious cases there is a breakout of fright and the experience of impending death. I have chosen 2 cases, everybody may look at the below:

Case 1: During January this year, I was out on the streets alone. Suddenly, I felt chest tightness, flustered heart and palpitation, difficulty in breathing, a feeling of nearing death. I was immediately rushed to the hospital. At the time my blood pressure was diagnosed to be normal, heart rate at 100 beats/min, ECG normal. After that, I did not dare to walk the streets alone. In places with lots of people or when dining with other people, I would easily get nervous. Nowadays, the breakout occurs irregularly. When it happens, I feel as if out of air, heat palpitation, profuse sweat, chill in the entire body, a feeling of near death, a sense of lacking reality, a sense of going nuts or losing control. Every attack would last for around 15 min, it is extremely uncomfortable.

I would also have a headache from time to time and pain in the neck. I have been tested by SCL-90, the fright factor is in the heavy range, anxiety in the medium range and the rest are rising. The traditional Chinese doctor said that my tongue was light in color with a thin white coating, the pulse is heavy and few in number. I have type 2 diabetes, I’m worried about the side effects of taking Western medicine and overburdening the body. But the effect of applying TCM, acupuncture, ear acupuncture beans is so-so. I’m worried about the side effect of Western medicine and the chance to develop addiction and dependency. I hope to apply for medicine according to the guidance given by the doctor and in reducing my worries.

Case 2: I have had anxiety disorder for 4 years and would often suffer from breakouts of fright. When they occur my heart rate accelerates to 140/150. At first, I thought I had heart issues but after having done 5 ultrasonography and coronary artery CT, 2 times cardiac enzyme, 3 times ECG, 100+ times 24-hour dynamic ECG, X-ray hyperthyroidism, all were normal. During the outbreaks, I would feel the veins going cold and then the heart beat increases for no reason, very frightening! It is simply a feeling of going dead!! During the outbreaks, the heartbeats super fast, but on the printed ECG graphs the heart is only moving faster than usual. The doctor diagnosed it as an outbreak of fright. Ack! I wasn’t given any medicines either, after about 20 minutes the heartbeat automatically returned to normal to around 70 beats/min. This is painful!

Some brothers have asked me on whether or not the outbreak of fright would lead to death. It’s actually not easy to answer this question because dead people cannot talk. Those that have survived will basically all say that the outbreak of the sudden death feeling will not lead to death. In the entire country around 550,000 people die suddenly each year. Do you think there are neurosis sufferers among them?

## Masturbation will damage the nerves

Masturbation will indeed damage the nerves but requires a certain degree of damage for that to occur. If staying up late and sitting for long durations is in the equation then the chances of encountering neurosis will be greatly increased. It is very painful once the nerves have been damaged, that is a real symptoms hell, it is an unfathomable abyss. Once one has fallen in it is very hard to climb out. Complete understanding is required for the chance of truly ridding the abyss.

## Illness progress

I have frequently masturbated for over a decade. Due to my love for exercising, early resting habits, reasonable diet, neurosis have therefore never surfaced. Afterward I started to stay up late and sitting for long durations, things started to look bad and my body was deteriorating by the day. I was tormented by neurosis, anxiety and autonomic nervous system disorder, death was preferable to life. The time to become ill was merely a month. In other words, a month after I started to indulge, I encountered neurosis.

What’s even hard to believe is that during the period of indulgence, I have done several hundreds of push-ups each day, benched 120 kg. After taking off my clothes, I seemed very strong and didn’t look like somebody that’s about to fall ill, but still I have encountered neurosis, the kind that made death preferable to life. Along with it came severe fright, anxiety and several dozens of bodily symptoms tormented me repeatedly. Afterward, I understood from studying TCM that being strong does not equate to being healthy. Many strong people are actually sick in various ways. These are so-called hidden illnesses that other people don’t know about. A person who truly understands health cultivation is a healthy person. Strong people are not necessarily healthy, many people only appear strong on the outside.

## Diagnosing experience

I started out with gastrointestinal neurosis. Afterward, I went to gastroenterology where my problems were treated as digestive problems. But the effect was very bad, only afterward did I realize that I have been wrongly diagnosed where the culprit was with the nerves. I have also seeing dermatologists and was treated as having skin issues, the effect was also poor. The categorization of different branches of Western medicine has its pros and cons. The con is that neurosis and related diseases are easily misdiagnosed. Some brothers with cardiac syndromes are misdiagnosed for the better half of a year, their conditions remain after spending tens of thousands in medical bills, just diagnosing fees amounts up to five figures. Afterwards, I started to check for myself, slowly I started to realize the possibility of having neurosis. Things become more certain after having chatted with fellow patients, I then went to Neurology where my anxiety disorder was confirmed.

## Hypochondria orientation

After catching neurosis, extremely many brothers become hypochondriac. Due to this, they constantly pay visits to the hospitals. Their hospital bills will shock people. Hospitals will admit to the fact that hypochondriac patients are generating income for the hospital. These people all believe that they are about to go under, that they have caught some serious illness, hoping to find it through diagnosis. After having received diagnosis all results turn out to be normal, they feel a little better. After a while, they again feel discomfort and once again visits the hospital. Just like that, many people have spent all their money on diagnosis. They actually don’t know that is an issue with the nerves, nothing will be found by checking for organic issues. Of course, what should be checked out should be checked out, there is no need to do frequent checkups. After having done a checkup and having excluded organic issues, there is no need to do frequent checkups. One must recognize the whereabouts of the problem, it is a problem with the nerves.

## Destined to be misdiagnosed

When the body encounters many symptoms of discomfort, the first reaction is certainly to check it out at the hospital. But having gone through many checkups while suffering from neurosis, you will find out that there is basically no serious problems, but the symptoms are apparent and make one collapse, go into a panic and lose hope. When no serious problems are found following a checkup, under these circumstances, family members will think that you are only pretending. Put in other words, it is all in your head and that you are actually not ill. These kinds of misunderstanding towards neurosis are too many. Not only will family members misunderstand you, many doctors will misunderstand you as well. Because that many doctors also think that you are only imagining things, many patients are in the dilemma of not being understood by people.

The good news is that there is internet nowadays, this makes it possible for one to find similar patients. Otherwise, if one is constantly not understood by other people, it is very possible for one to take extreme measures. The reason to why many brothers like to chat about symptoms is to seek comfort for the mind, knowing that many people are just like oneself. In reality, chatting about symptoms alone is not enough. One cannot recover from doing it, one must find the real cause behind the illness. If the cause is not correctly understood then the chances to make a complete recovery is slim to none.

Some brothers have spent five digit or even six-digit sums on diagnosis fees. Some brothers frequently visit the emergency, stays at the hospital overnight. Doctors are at a loss on what to do, nothing shows up in the diagnosis, the body remaining in a weak condition. Some brothers ask me about what is wrong with them. I would then tell them that neurosis is actually a problem with the functionality and not a problem with the organ, basically nothing will show up in the diagnosis.

Take an example: you have had a bike for over a year, it is very used, you feel that it is incomparable with a new bike. It is very tiresome to ride the old bicycle. You send in the old bicycle to the repair shop for diagnosis. All parts are in working order, only that they are worn, they do not function as well as when they were new. Actually, it is a similar situation with neurosis, the function is nowhere near as what it used to be.

There is another kind of misunderstanding which comes from ordinary people. Many people think that depression and anxiety disorder originates from problems in the mind and is unrelated to the physical body. The issue is a product of the mind, this is actually gravely incorrect. Many people are perfectly fine before the illness strikes. They are optimistic, only to be struck down by a sudden case of anxiety disorder. The so-called psychological illnesses are not purely psychological but have a basis in physiology. Constant masturbation injures the kidney qi, staying up during the night and long-term sitting also injures the spleen and the liver, neurosis then appears after that.

If you merely think that psychological illnesses are imagined, this is incorrect. This is the usual belief of today by thinking that psychological illnesses are imagined. This is actually false, this is coming from somebody who happens to be a deep experiencer and has done thorough research. I think that those people who have not been deep experiencers themselves have a lot of biased thoughts. This includes lots of points of argumentation on medical textbooks, all of which is incorrect and is not congruent with reality. This is similar with harmlessness theories, nowadays it has made it into the textbooks, can we say that harmlessness theory is correct? Reality has proven that it is false, completely believing in books is inferior to having no books. Correct points of arguments should be carried on. If it is wrong then we will need to be brave in correcting them.

Reality has proven, psychological illness is not simply a problem with the mind, it is not due to overthinking. Take an example, everybody is familiar with the idiom of the bird which is startled by the twang of the bow. The bird was already injured, upon hearing the sound of the bow, it became nervous and the wound ruptures resulting in the bird falling down. Everybody think for a moment, if this bird is not already injured, will it still fall down? Certainly not. Neurosis is actually also like this. If your kidney qi is abundant, will you catch neurosis? TCM: abundant kidney qi, ten thousand evils is extinguished. Therefore, the break out of psychological illnesses have a physiological foundation, the reason being that your body is weakened, given a stimulant the illness suddenly breaks out.

Psychological illnesses are not that simple either, it is accompanied by a host of bodily symptoms. Having an anxious mood is not representative of having an anxiety disorder, a depressed mood does not represent having depression. Some patients have reported in such a fashion; previously he is a very optimistic person but became anxious following the outbreak of the illness. His anxiety disorder did not come from feeling anxious, rather following the outbreak of the illness did different orientations of anxiety, fear and compulsion appear. I was also like this, I did not overthink and was always optimistic. Following staying up at night, long-term sitting and sexual debauchery, I came to have an anxiety disorder.

If we are to discuss whether or not there are imagined anxiety disorders, I think that if these cases really exist they only take on a tiny portion. For instance, some people have a naturally poor constitution, their kidney qi is severely inadequate, being subject to a little stimulant in such case might also make anxiety disorder appear. Throughout my analysis of thousands of cases, I can say that 99% of the cases have a physiological basis. Yet the physiological foundation under the outbreak of these cases is not due to a naturally poor constitution. Instead, it is caused by self-indulgence and poor lifestyle habits. It is not a product of imagination.

## Medication memories

Taking medication is an experience that I cannot stand to look back. This is because I was severely dependent on medicines and took them as I took in food. I still have a big box of unfinished medicine at home, many have expired. I have kept them as a reminder that I once lived in symptom hell. I don’t want to indulge myself again, I don’t want to return to the symptom hell where death is preferable to life. At the time I had taken several dozen bottles of Oryzanol without much result. I took Deanxit everyday. In the beginning, the effect was quite good. After having taken a good amount of it I developed drug resistance, I then went to see the doctor and was given another medicine, the drug resistance continued. Just taking the drugs themselves made me spend a lot of money. The main issue is that I wasn’t healed from the medicines alone. At most, I felt a little better. That is truly death is preferable to living. Being so young of age but was dependent on medicines to stay alive. When I didn’t take medicine, it is suffering beyond death. Ordinary people have no ways of understanding the feeling, only fellow patients understand.

## Pointing directly to the cause

The cause of the illness was already mentioned in the above articles. For male patients, it is: staying up at night + indulgence + long-term sitting. This is the answer I gathered from chatting with over a thousand fellow patients. The kidneys are rooted in original qi. Staying up during the night, indulgence and long sitting are like the 3 hatches striking at the tree of life. Of course, a few individuals take drugs, drinks excessively, goes into a violent rage, these are also very damaging to the body and also easily leads towards neurosis. In addition, genetics, pressure, changes in the family situation and other factors also might induce neurosis.

## Recovery process

The recovery process of neurosis basically takes 2 aspects:

Curing the mind
Curing the body
The body and the mind are one, curing the body will affect the mind. Similarly, curing the mind will also affect the body. Having a healthy mind is also very important and critical. Therefore, upon having neurosis, many patients start to believe in Buddhism. Buddhism is very good for cultivating the mind. The physical health is affected by cultivating the mind. I am a believer in Buddhism, of course, I do have Buddhist karma. Those fellow patients who lack Buddhism karma may study other forms of traditional cultures. These are also very beneficial to mind cultivation, such as [Di Zi Gui]. When the mind is right the body will also be right (Translator’s note: one good way to determine if one has Buddhist karma is simply by looking at one’s inclination towards Buddhist teaching).

In the aspect of curing the body, I recommend recuperation via TCM and then study health cultivation on one’s own. One may select those health cultivation exercises that are suitable for oneself and persist in practicing them. By curing the body and the mind simultaneously, neurosis will slowly recover. Serious cases will require at least 1 year of rebooting coupled with health cultivation. Many fellow patients do not understand reboot, do not comprehend it, these patients have actually not realized the importance of essence preservation at all. The kidney is determined at birth, the spleen is determined after birth. To recover, one must understand essence preservation as well as understanding spleen cultivation.

By doing a good job on all fronts and making adequate efforts in cultivation, neurosis will then have a chance to recover. Otherwise, many fellow patients have not recovered in 5 years, there are even those who have not recovered in over a decade. The reason being that they do not understand health cultivation, do not emphasize essence preservation! Those patients who continuously leak, masturbate, self-ravage have not come to an understanding. Without understanding, neurosis is too difficult to recover from. Even if neurosis were to recover, it will easily break out again. Many patients upon indulging encounter relapses, this is very commonly seen. Therefore, neurosis patients must recognize the importance of rebooting, or else it will be very difficult for you to recover from neurosis, symptom hell will make death preferable to living. Rebooting and cultivation is the foundation towards recovery, or else no matter the number of medicines you take it will still be leaked away.

## Guidance in seeking medical advice

I recommend going to a TCM doctor, furthermore an aged and good TCM doctor, one in a hundred! Due to the number of charlatans, when you are seeking a doctor it is best to first gather understanding from the internet on which doctor is good, which doctor possesses superb medical expertise. One may go to the hospital’s website or TCM QQ group to gather understanding. Otherwise, by blindly seeking a medical advice, there is a high chance of running into charlatans. Some charlatans are unable to find a solution, some even recommend harmlessness theories to you or tell you that your illness is all imagined. These type of charlatans lack true understanding between their patients, their medical expertise is worthy of doubt. Good TCM doctors are always in the minority, those who have received handed down teachings and possessing good insights are even rarer in number, therefore seek a good TCM doctor at all cost.

Take another example, a Ph.D. student in TCM versus a TCM doctor with middle school education and 40 years of experience, which would you pick? I think that those in the knowing will for sure pick the older doctor. The older doctor has ample experiences and rich experiences in treatment, these are unobtainable from textbooks from the school, only through practice and repeated experience may the true workings be understood. The paper talk will never result in a good TCM doctor. There are many TCM doctors graduating from fields of study, if you were to talk theory with him, he will outmatch you in theoretical knowledge, his memory is strong and he can talk endlessly. What I want to ask is? How much practical experience is there to be had? The handing down of knowledge is important in TCM, being able to receive instructions from great masters and gaining insights through communion with them will allow for a relatively quick progress. Truly skillful TCM doctors are forever in the minority, what he knows is broader and deeper than the ordinary TCM doctor.

## Final summary

I have found the path through sickness and so should belong to the experiencer category, having deeply experienced it and then started to research into TCM. I’m also a recovered person because I have attained understanding I was able to recover. Only when we have understood do we know what to do. I hope the neurosis patients will receive beneficial inspiration from reading this article. I have crawled out from symptom hell, the feeling is all too clear. Hopefully, my article has helped you. Persist in the way that I have pointed out and I believe that you will recover. But recovery is a slow process, it requires patience, keep on fighting!
