# The sharp weapon in recovery, sexual indifference and masturbating while dreaming

## Foreword {-}

### On harmlessness theories {-}

Let’s talk a little again about harmlessness theories. Quite a few brothers are proficient in English due to the fact that they have studied abroad. They often browse English websites, then they tell me that harmlessness theories are not being championed abroad, or to put it another way way, harmlessness theories are outdated. The research results from Western medicine nowadays says that masturbation induces body asymmetry and shortens the lifespan. I think future research results from Western medicine will be in agreement with the conclusions from TCM. Facts have also proven that harmlessness theories will only harm people, it is a great mockery and a wrong form of thinking. Who knows how many people have come to harm due to it, needless to say, hundreds of millions of people have encountered the poison from harmlessness theories. Today it has also made its way into textbooks, one can only imagine how the youth would react upon reading those theories.

People born in the 80s are victims of harmlessness theories, so are people born in the 90s, those who are born after the 2000s are about to enter puberty. If these people have not formed a correct perception towards masturbation, they will very likely fall into its trap. The youngest brothers that I have chatted with nowadays are 13 years of age, there are also many 14-year-olds. A 13-year-old brother has encountered prostatitis but hasn't dared to tell his parents. He fears even more to go to the hospital, how similar he is to my previous self. He told me that he has read a small pamphlet from his school, in it were harmlessness theories. After that he was resolute in his belief and was heavily addicted to masturbation. This resulted in the appearance of frequent urination and swelling in the lower abdomen. I told him to quit masturbation immediately, or else it’s very possible that his development would become affected.

If harmlessness theories are not corrected, then generation upon generation of youth will become victims of its poison. This is poison in the realm of the mind, more covert than poison in the body. It is also more easily ignored by people, harming people in the fashion of a frog in a boiling pot, allowing the majority of the people to lower their guards. If one waits until the sudden realization when the body is ridden with symptoms, recovery will be a slow process from that point. It is said by Jiaxing in the previous season that the recovery time for the body will take at least 1 year. I’m in agreement with his point, after all, many people have had a long history of masturbation. Quite a few are suffering from chronic prostatitis with many different forms of discomfort felt throughout the body. Therefore to recover will really require a year of time. I’m not saying that you will be able to recover with a dozen days of rebooting, nor will you become completely healed within a few months, to truly recover will basically require at least a year.

Of course, by persisting in rebooting and health cultivation for 3 months, you will clearly feel the improvement. If you continue in this way for a year while doing everything correctly; rebooting properly and putting in the proper efforts in cultivation, recovery will be quite optimal. Brothers who know how to cultivate the health will recover relatively quickly, besides a repeat of symptoms is unlikely to appear. In contrast, for the many brothers who don’t know how to cultivate the health, even after a few months of rebooting, recovery will remain subpar. Therefore, we must put in enough effort in health cultivation!

### On overcome lust by looking at disgusting images {-}

Lately, quite a few brothers have reported the issue of unclean viewing to me.  _(Translator’s note: unclean viewing in this context refers to patikulamanasikara, a Buddhist meditational method of overcoming lust by meditating on the foul)_

Some of the unclean images nowadays are very stimulating, looking at them makes one want to throw up. Quite a few brothers have reported to me that they cannot bear to look at the images, it affects their appetite. Although I’m a believer in Buddhism, rarely do I look at these types of unclean images. I have seen them before, it is indeed disgusting and makes one want to throw up. Brothers with a low mental threshold might carry with them lingering images. If these stimulants leave imprints of mental images they will affect married life between couples and I think that the majority of the brothers will choose divorce which is undesirable.

Actually, unclean viewing is a form of visualization. A little bit of imagination is enough, strong stimulants are not needed. To combat sexual fantasizing, it can be halted by constantly studying and raising one’s realization, memorizing the mnemonic chants of stopping sexual fantasizing, one does not need to view those kind of strongly stimulating images. Of course for some brothers, images from unclean viewing are suitable for them as it allows them to quickly raise their realizations and determination. For other brothers, it may be unacceptable. I recommend everybody to choose the level of stimulant intensity according to their own reactions. Normally, I would employ unclean viewing. The importance is in the method of visualization, a little bit of visualization and stimulation is enough, I think that this intensity of simulation is suitable for me. Stronger stimulation is not always better, an intensity which suites oneself is the best!

We will enter into the main topic below.

In this season we will talk in detail about the sharp weapon in recovery, sexual indifference and masturbating while dreaming, the specifics can be found below:

## Sharp weapon in recovery {-}

The body is cultivated through movement, the mind is cultivated through stillness, together they comprise the way of health cultivation. In stillness work, I recommend everyone to choose standing qigong or sitting meditation. As to moving work, there are many choices such as Eight Brocade exercise, Taiji boxing, Liuzijue qigong, stretching, meridian drumming, etc.., these are all very good. But in this season, I’m talking about the sharpest weapon in recovery and not about the aforementioned health cultivation methods but on aerobic exercise. I have previously worked as a personal trainer and I’m quite familiar with all types of exercises. I used to think that strength exercises were the best forms of exercise, it would allow people to feel strengthened. Later after researching into TCM, I found out that strength exercise was not the best form of exercise.

TCM:

-   Forceful lifting to some extent, such as excessive bedroom activities, excessive sweating, injures the kidneys.
-   Due to the use of strong force, kidney qi is thus injured, the Extrapoints therefore becomes bad.

When I caught anxiety disorder, I made a mistake. It’s a mistake that many patients make and that is hoping to gain health through strength exercises. Later I found out that it was an impossible task and doing so was going to have the opposite effect. When the body is weak one should choose still cultivation. Afterward, one may do some moderate exercises. Strength exercise is not the best choice. In bad cases, the body will become worse and worse off. When you kidney qi is still abundant, strength exercise may promote health. When you are weak, strength exercise may bring on the opposite result. Following an exercise session at the time, my muscles would grow, but I clearly felt fatigued in the body, unable to recover and upon waking up I was still very tired.

After researching into TCM I discovered that I was walking on the wrong path, I shouldn’t have chosen strength exercise but instead should have chosen cultivational practices or aerobic exercises. In the beginning, I started out with taking walks, my body then slowly recovered. This is followed by a brisk walk and a slow jog, then I was able to play a little basketball. Once playing basketball felt effortless then was the time to do some strength exercises. Recovery is a process, starting from the basics of taking a walk. I quite emphasize taking a walk, it’s actually the best method of exercise in the world, it suits nearly everybody. For many stroke patients, the doctor will recommend walking a couple thousands of steps each day as this is beneficial to the recovery.

There are lots of benefits to aerobic exercises. Quite a few brothers suffer from eye bags and black eye rings and they won’t go away after a few months of rebooting. But through persisting in aerobic exercises the issue of eye bags and black eye rings will be greatly alleviated. At the time when I was in college, I took up running for a month and then my eye bags and black eye rings disappeared. Sometime back I saw a post made by a brother, his eye bags also disappeared after he took up jogging. Eye bags and black eye rings can be removed via aerobic exercises. Therefore, brothers with these type of problems would do best to establish good exercising habits, this will benefit recovery from eye bags and black eye rings.

In addition, there is prostatitis. Persist in aerobic exercises and prostatitis will be greatly alleviated. Frequent urination and scrotum dampness for instance will also become a lot better. In TCM it is mentioned that movement raises the yang, moderate exercise has the ability to promote bodily recovery. The level of intensity should however be observed in aerobic exercises, this is because profuse sweating damages the yang. At the beginning when the body is weak one may walk briskly and let the body sweat ever so slightly.

At one time, I was jogging everyday and was dripping with sweat. But I didn’t feel any discomfort because I was very young at the time, my kidney qi was still sufficient and was able to take damage. Afterwards, when my body had been severely weakened, I would feel discomfort for several days every time I sweated profusely. Therefore, when the body is weakened, one should adopt a minor sweating exercise intensity. This is my realization through repeated experience, I have also taken many detours in the past.

Exercising is a very deep subject. Everyone knows that life depends on movement. But as to how to exercise, its methods and the quantity all deserves special attention. Inappropriate exercise not only provides no benefit to the health but also brings illnesses to the body. For example, some people engage in intensive exercise when they have a cold, they then catch myocarditis, some even induce sudden death. Some brothers over-exercise, exerting themselves during the day and as a result at night they have an emission. To recover even better we should exercise actively. At the same time, we must have a deep understanding of exercising. In this way, there is a guarantee in recovery, or else in bad cases, it is only counterproductive!

There is another apparent benefit with aerobic exercises and that is the ability to improve the skin complexion. By persisting in exercising for a period, you will notice that your skin has improved. The complexion is a lot better, there is some color in it, the face will become bright and clean, giving out a sunny and refreshing look. Some brothers have severe acne or have very poor complexion, like a ghost. Moderate aerobic exercises will improve things in these situations. Internal secretions can be adjusted through aerobic exercises. Once the adjustment is finely tuned, the skin will naturally improve.

Many brothers have reported that following rebooting and actively exercising, they have become handsome, exercise is the best cosmetic for men! Exercising will also boost a person’s confidence, there is no falsehood in this statement! But many brothers have also reported that upon relapsing, they again turned ugly and wretched as the Spirit was lowered. Therefore we need to raise our vigilance and do our best to not relapse. Study more to increase our realization, reaching the apex of realization as early as possible and permanently ridding ourselves from the evil habit of masturbation.

Below I have extracted some of the benefits of aerobic exercises, everybody may take a look:

1.  Say goodbye to the bloated figure  
    Many people take up jogging in order to lose weight. Jogging is indeed the best way to lose weight, more calories are burned while jogging.
    
2.  Prevent the degradation of your bones and muscles  
    Long-term sitting in front of our computers make our bones ever weaker, while moderate exercises will allow your bones to remain healthy and can slow down the aging process.
    
3.  Resisting illnesses  
    Jogging can decrease the risk of getting a stroke. Frequent jogging has already become a treatment for those who are at risk of a breakout or in the early stages of osteoporosis, diabetes, and high blood pressure.
    
4.  Maintaining or increasing the level of health  
    Jogging can help to train the 50% of the often idle portion of the lungs. Jogging will also help to increase your lymphocyte and thereby increase your immunity.
    
5.  Make you more confident  
    Like other single sports, jogging can increase your self-confidence. Jogging allows you to complete round after round of attempts, making you stronger, surer of yourself, bestowing yourself with a feeling of strength and freedom.
    
6.  Relax, decrease the pressure  
    Slow jogs can divert the attention, one becomes immersed with the surroundings, all trouble will surely vanish.
    
7.  Famous “runner’s peak experience” Jogging, especially outdoors, will enable the body to release a substance which will produce a feeling of happiness and joy  _(runner’s peak experience)_. Jogging is already been used to treat clinical depression, addictions and so on.
    
8.  Exercises your brain  
    Just as it is helpful to your body, jogging is also very helpful to your brain. Through jogging many obstacles have been overcome, you learn focus and determination.
    

The realization that I have now is that aerobic exercises are a form of medicine! It is a form of treatment and it is also free, the benefits are many. But moderation should be adopted. Brothers who are obese may adopt the method of taking a stroll because if the mass is too heavy, more jogging will injure the knees. There is a saying: There are a hundred advantages to jogging except that it injures the knees. Even normal people should pay attention to moderation when jogging. I have tried many ways of exercising, taking a walk is still the best.

Of course, lots of walking will also result in knee pains, therefore the  _“step count”_  should also be monitored. Everyday go out and walk for approximately 5000 steps and then persevere. One may adopt fast walking, the result will be quite good this way. If you feel very fatigued after walking for 5000 steps, change to 3000 steps. The adjustment of the exercising intensity will depend on the reaction of one’s own body. Once you are accustomed to 3000 steps, you may appropriately increase the quantity.

_“Racewalking”_  exercises are popular abroad right now. Racewalking is a form of effective aerobic fat burning exercise, more heat and calories can be burned through it. Racewalking can tighten the contours of the legs, frequent training can raise a person’s Spirit, making one more confident. At the end of the day, walking is actually the best form of exercise, this is something that I have realized after thorough studies. Many sufferers of anxiety disorder experience severe headaches, making exercising impossible. In these circumstances, the path towards health basically all starts from walking. Sufferers of neurosis should not ignore exercise but should choose the form of exercise that suits them.

Taking a walk everyday is actually a very good method of recovery. My health also started recovering from walking, once walking became easy it can be changed into a fast walk or slow jog. When fast walking became easy I went to play basketball. When basketball became easy I started some strength exercises. But my main form of exercise is still fast walking, strength training being a compliment.

Actively exercising is actually the same as  _“recharging vitality”_, just like charging a cell phone. Moderate exercises allow you to maintain a state of radiating vitality. Nowadays I call the basketball court  _“vitality field”_, playing basketball is the same as  _“recharging vitality”_. Of course, now I pay very close attention to exercise intensity. Sometimes, when I’m not playing in a match, I will shoot some hoops and exercise the muscles and the bones, expose myself to some sunshine and sweat in small amounts, that is adequate.

Aerobic exercises are the sharpest weapon for recovery. Brothers with excellent exercising habits will recover doubly fast. Many brothers will sit for long durations facing the computer. People have an inherent laziness, by not moving for a long time you will be more and more inclined to not move. Therefore, if we want to recover better we should get moving, do more moderate aerobic exercises and in this way recovery will be faster.

Let me share with everyone another story. In those years when Deng Xiaoping was asked on what he did during the Long March of the Red Army, he calmly replied:  _“walked along”_. In  _“walked along”_, the main idea of health cultivation is actually contained. When Deng Xiaoping was old, his method of exercising was to walk around a flower bed for a dozen laps, this is the best form of exercise. Those who do squats for several hundreds of kilos will not live to be 90+, but a person who  _“knows to walk”_  with  _“walking cultivation awareness”_  can live to be 90+.

The form of exercise is to be carefully selected, there are over a hundred forms of exercises, walking is still the best among them! I have recovered relatively well, it is inseparable from  _“knows to walk”_. Persisting in aerobic exercises will on one hand promote the functional recovery of the body. On the other hand, it will greatly reduce the chance of illness breakouts. Frequent exercise will increase the interferon levels in the blood. Interferon is the immune enhancer of the body, it has the effect of preventing diseases!

Rebooting is system engineering, it must be done professionally. How to recover and how to cultivate the body are actually also system engineering. Only by doing well on both fronts will the recovery be relatively optimal. As to how to recover, aerobic exercise is the sharpest weapon in your hands. Make sure to employ aerobic exercises to promote the recovery of your health, my advice is to choose a level of intensity that suits you, persist well!

Lastly, a summary: persisting in doing moderate aerobic exercises is a form of medicine, ideally one should take this medicine often. By doing aerobic exercises you will receive all sorts of benefits. By sitting down for long durations, the kidneys, liver and the spleen will be injured, the loss is too great!

## The phenomenon of sexual indifference {-}

Below let’s talk about the phenomenon of sexual indifference.

A while ago I saw some brother posting that he feels nothing towards the opposite sex, a feeling of indifference towards sex. He asked if this is a sign of rebooting success. This situation is one of sexual indifference, when the kidneys are deficient, the phenomenon of hyperactivity in the yang due to toying deficiency will appear. The majority of brothers encounter hyperactivity in the yang while some brothers upon having been damaged to a certain degree will experience sexual indifference. At this time, normal stimulation is useless for them, strong stimulation will not necessarily excite them either. This is when they think the have successfully rebooted, in reality, this is not rebooting success. Real rebooting success will require constantly increasing one’s realization and is not the same as temporarily feeling no desire.

Through persistent rebooting and health cultivation, desire will slowly raise its head. That is when your realization and determination will be tested. Many brothers upon rebooting will enter a period of desire hibernation. Desire during this period will be very cold, sexual fantasizing will also be extremely less. Many people will think that they have succeeded in rebooting. But after the desire hibernation period, one then enters the peak period for relapses. That is when your level of realization and determination will be visible. If your level of realization is very high, the temptation demon can be vanquished. If your realization is not yet there, then only abuse from the temptation demon awaits, relapse will be hard to avoid.

Normally, the onset of severe sexual indifference will require active treatment. There is a certain relationship between what causes sexual indifference and kidney deficiency. It is also intricately connected with many other factors, such as:

-   **Mood:**  when a person is in a poor mood, desire will easily decrease temporarily.
    
-   **Tobacco and alcohol addiction:**  long-term chain smoking will more easily lead to impotence, long-term alcohol addiction can lead to a decrease in sexual function and desire.
    
-   **Medication:**  long-term or large dose use of certain medications can reduce sexual function or even lead to male impotence and sexual indifference.
    
-   **Living conditions:**  living in poorly ventilated, overly cramped environments will induce insufficient oxygen supply to the brain, affecting sexual function and lowering sexual desire.
    
-   **Seasonal temperature:**  many people have relatively strong sexual desire during the low temperatures of winter and spring. But during the drenching peak of the summer, sexual desire often declines temporarily.
    
-   **Age:**  most males reach their sexual peak following adolescence. Decline starts to take place during 30-40 and becomes prevalent from around the age of 50.
    
-   **Incentive:**  monotonous lifestyle or little social interaction causes desire to become inhibited, staying at a rather low level.
    
-   **Feeling:**  cracks appear in one’s feelings towards the spouse, both sides are fed up with each other, desire greatly decreases.
    
-   **Physiological cycles:**  desire will experience cyclical changes, expressions of sexual indifference appears during the troughs.
    
-   **Health condition:**  seriously ill patients are very likely to experience sexual indifference.
    

## The issue of masturbation while dreaming {-}

Lastly, let’s talk about the issue of masturbation while dreaming.

Many brothers masturbate during dreaming. This is the real act of masturbation while in the state of half asleep and half awake. If one dreams about masturbation then that doesn’t count as relapse, because it is only a dream without the act itself. If masturbation takes place during the half-awakened state then it counts as relapsing. There are brothers asking questions like this in almost every season. Some brothers say that during the day they are alert and are in control, but once they sleep they are no longer in control. This phenomenon is intricately related to mind addiction. The degree of addiction is heavy, a familiar road to masturbation has already been formed, one will then masturbate subconsciously, sometimes one is not even aware of it. For instance, some brothers upon awakening discover that their pants have come off, or suddenly wakes up during ejaculation. They have already formed a habit of grabbing hold of the erection, especially during sleep.

When this kind of situation occurs, we will need to study more and increase our level of realization, constantly cleansing our consciousness. On the other hand, we will need to make up our mind and exercise willpower to change this habit. Suggest more to oneself, besides urinating, do not touch with the hand under other circumstances, establish this rule. The determination must be great, by persisting for some time, this kind of masturbation during dreaming can be avoided.

## Books recommendation {-}

In this season, I will recommend 5 books. In martial arts novels, a rookie may become a master by practicing a rare book in the martial arts circles. My realization at this stage is inseparable from reading lots of books. The real masters are all adept at learning. Warren Buffett’s extraordinary powers come from reading! The more studying, the more the knowledge, no knowing without studying. Knowing does not follow from being born but comes from studying, thinking and realizing. Many books are actually interlinked with rebooting, by comprehending these books, your realization will naturally rise a few levels.  _(Translator’s note: the below book recommendations are all in Chinese, I would encourage readers to find and share similar books in English that are worth studying)_

-   (太素脉): this is a wonder book, it integrates the study of the pulse with divinatory art, worth a study.
    
-   (逝去的武林): although the narrative is about the anecdotes from the martial arts circles of the past, practicing martial arts and health cultivation are actually completely interlinked. I have realized many things related to health cultivation from reading this book.
    
-   (圆运动的古中医学): famous doctor Li Ke revision. I like this book very much.
    
-   (太清神鉴]): this is a book which purports to teach physiognomy reading for fortune telling. It is a well sought after and treasured book by all kinds of distinguished people. I have continuously studied physiognomy. Because physiognomy is interlinked with TCM, an indulgent person will undergo changes in both the physique and the face, all of this is mentioned in the book. I have read [麻衣神相] and [柳庄神相] but I like [太清神鉴] the most. If you want to become an able person, understanding more and deeper principles, [太清神鉴] must not be missed.
    
-   (中医火神派三书): I also like this TCM book very much. Good books never bore me, every reading will bring about new rewards, the saying goes review the old to know the new.
    

In this season I have recommended 5 books, my house is full of books. I will share with everyone the books which I think are good. Through practicing these books, your realization will be increased. If you have indeed arrived at certain understandings, this is very helpful for rebooting.
