# The issue of absorption rate, rebooting stabilization period, sperm quality

## Foreword

Recently I saw a post made by a brother on the topic of getting the rookies up to speed. Lots of rookies are pouring into the rebooting forums, they are actually very much in need of guidance from veteran brothers.

Newcomers have 2 notable characteristics:

1.  Many misconceptions, many people still carry remnants of harmlessness theories.
    
2.  Many issues, there are many complicated issues in the rebooting process.
    

I have so far answered several thousand questions in all shapes and forms. The misconceptions with rookies must receive immediate correction, or else their doubting mind will cause relapses. To be successful in rebooting, one must first understand the problems that one has encountered, or else while one is carrying doubt, it will affect self-confidence and determination. Brothers with doubts are extremely easily swayed. Therefore, we veterans should promptly help the rookies, eliminate their doubts, correct their misconceptions. Help them to establish rebooting self-confidence, provide timely guidance in the rebooting process, allow newcomers to soon find the correct path of rebooting and not to reboot in a blind or forceful manner.

I remember when I used to reply to questions, the foremost foundation was on zero reply threads. My thought at the time was to eliminate threads with zero replies, providing rookies with immediate guidance to the best of my ability. Nowadays, I mainly reply to questions within my own threads, rarely will I reply to other threads. My goal these days is to not over-strain myself. Everyday, I reply to around 30 questions, up to 50 at most. Normally, it is limited to within 50. During National Day I will answer more questions. There are several days when I exceed 80 per day because it is a holiday  and I end up replying to more questions. When making more replies I clearly feel that my energy is not enough, easily leading to fatigue in the body and the mind. Therefore, nowadays I limit the number of replies in order to adjust my stamina and better hold fast to the rebooting forums.

Actually I have replied to many questions, some of them I have replied to over several dozen times. But toward every newcomer, I maintain proper patience because I think that newcomers are very much in need of patient guidance. When you are guiding the rookies, you are actually also reinforcing your own positive energy, you are also increasing your determination. At the same time, you also transfer this helping attitude to the rookies. Sooner or later, the rookies will turn into veterans, veterans will guide newcomers. In this way, a pleasant atmosphere will be formed in the rebooting forums, it will grow better and everybody will be able to reboot more and more professionally. I believe that there will be many successful rebooters in the future.

Of course, there is already a batch of successful brothers. They have already entered into the stable period of rebooting, they are also selflessly helping more newcomers. Rookies these days are very fortunate, the seniors have already paved the way for you. As long as you put in the effort, constantly studying in order to increase the awareness, to permanently rid yourself of masturbation is only a matter of time. Rebooting forums also heavily emphasize the importance of health cultivation. In the forums, you will also learn about health cultivation, this will be very helpful towards your recovery. To reboot is one aspect, to cultivate and recover is another aspect. These will need to be grasped tightly by both hands, recovery will be quite optimal in this way.

We must help the rookies, helping others is the equivalent of helping ourselves. Rookies will become veterans, veterans will again help the rookies. Knowledge passes on from teacher to the student, we will need to pass on this helping attitude. Let more people realize the harm from masturbation, help more newcomers to completely quit masturbation and renew their bright health. Everybody fight on!

My advice to the newcomers is to study more, I recommend to read through the quality articles found in the rebooting forums a few more times. Clear answers to many questions will be found in those articles. Through studying these quality articles your awareness will rise quite fast.

We will enter into the main topic below.

In this season we will discuss in detail the issues of the absorption rate, reboot stabilization period and sperm quality.

## The absorption rate {-}

The absorption rate mentioned in this season is not about the rate of food absorption in the stomach, but rather the absorption rate of studying rebooting articles. In my forums and in my private mailbox are reports from brothers who have rebooted for over a year without success. With repeated relapses and unchanged symptoms, they become very discouraged and hopeless. Upon asking if they read rebooting articles, they answer that they read all of them, they understands all of the principles in rebooting. The only problem is that they cannot keep up the reboot. I remember a brother mentioned that he has become immune to rebooting articles. By looking at the topic of the article he would know what the contents are. Some brothers have even developed a fed up mood, they study rebooting articles while being fed up. I have mentioned in previous articles when the fed up mood appears, one must pay attention to immediate adjustment, allowing oneself to regain the excellent rebooting mood.

At the end of the day, to completely reboot is a process of constantly cultivating one’s awareness. The awareness must be constantly raised.

Some people advance very fast in the beginning. After they have studied for a while, they seem to reach a plateau, their awareness ceases to increase any further. Many brothers know all the principles and knowledge about rebooting, but the problem is that their understanding is not deep enough, the rate of absorption is too low. After reading an article, what can be remembered and rehashed isn't a lot, comprehension by one’s own thought processes is also neglected. Just like when I ask you if you have seen a certain movie? You answer that you have seen it. Then I ask you about the contents of the movie and you only remember the big picture, you have no recollection of any detailed contents.

Actually, this is what is meant by too low an absorption rate. Just like when you eat a certain food, you have only absorbed part of its nutrient while missing out on the most important nutrient. I tend to read a good book or article many times, constantly extracting and summarizing, extracting its core thoughts. This is like the process of filtering for gold in sand, you must extract the spirit of the article and then completely absorb it, your awareness will become more powerful this way. You must find the spirit of an article. Actually, the spirit of an article is merely contained in a few sentences. Write down all the important sentences in a notebook, read it frequently, try to memorize the contents on your own initiative until you can freely recall the contents. Once you can do this, you are basically there. If you are able to combine this with your own experiences, with deeper thinking and realization, that is even better.

At the time, the raising of my awareness took over a year. Within this time, I was constantly taking notes. Jotting down what I thought were good sentences and points of view, constantly reviewing the contents, my awareness would steadily increase in this manner.

In the beginning, the distance between me and the temptation demon can be described like this: I was abused by the temptation demon for over a decade, I was always helpless in front of it. Every time I encountered it I would be abused, especially during the weekends when I was alone, that’s when the temptation demon would like to come out and make me miserable. My awareness during that time was too low, I was lacking studying awareness altogether. That is why I have failed to reboot for over a decade. Afterwards, I realized the importance of studying, constantly studying to raise my own awareness. Then I noticed a phenomenon when I ran into the temptation demon again, I was able to defeat it.

This is like playing chess with the temptation demon. Previously you have always lost due to inadequate awareness. Once you have raised the awareness through studying you will notice that you can subdue the demon, you can defeat it and it can no longer touch you. The only way of reaching this stage is through persistent studying and increasing one’s awareness. Otherwise, if you relax your studies and vigilance, relapsing will only be a matter of time. There are people who have relapsed after 200 days, a year.

Therefore, we should not wander away from rebooting articles, not leave the rebooting forums. Try to take some time to visit the forums every day, even for 5 minutes. Help the newcomers while also reinforcing one’s positive energy. If you are unable to go on the internet, you should take out your notebook and review rebooting knowledge. Once one has entered the rebooting stabilization period, a lot of time is not required for everyday studies. It is adequate to learn through repetition and maintaining the vigilance.

**The best method of raising one’s rate of absorption towards rebooting articles is to take notes!**  Note taking is a sharp weapon towards raising the rate of absorption!

Up until today, I still take frequent notes. The process of taking notes is to constantly summarize, deepening the memory and understanding. In your notebook is where the thought essences can be found, thoughts and viewpoints that you think are important should all be summarized in a notebook. Right now, I have a dozen notebooks like this. Through this process of accumulation I was able to gather the level of thought awareness that I now possess. Many brothers are students, students should have the habit of taking notes. Teachers should also have emphasized the importance of note-taking. Therefore, in rebooting we should also make full use of this excellent tradition. Constantly jotting down the essential rebooting sentences and then ceaselessly reviewing them, learning through repetition. From every repetition you will gain new insights, in this way your awareness will constantly be raised.

Below is a paragraph from a brother named “let everything be clear”, everybody may take a look:

> Big brother, I’m here! I have not been on the internet for 4-5 days, I have put all of my energy on working! But each day upon awakening, each day when I’m tired, each day before going to bed I have always thought about rebooting vigilance. When I was free today, I took up the notebook and a pen and wrote down your pictorial quotes! I have not memorized them all because many of them require slow digestion! Let’s fight together, big brother!!

This brother from above has been able to reboot steadily nowadays. For one he is willing to study and has good studying habits, including his note-taking habits. Through extracting the essential thoughts from articles in order to deepen one’s understanding, increasing one’s absorption rate towards the article. Previously, I have observed another brother named Tom who had an inclination towards studying and summarizing. Summarizing is equivalent to repeated studying, understanding and thinking, a new realization can be obtained by making a summary. Actually summarizing is a method for deepening one’s memory. My studying habits also include making constant summaries, constant refinement and then compiling them into a notebook. After that, I would often flip through and review the notebook. This is how I was able to increase my awareness step by step.

In this season, I have summarized an equation for a successful reboot:  
**successful reboot = high awareness + strong vigilance**

Brothers who are able to truly reboot certainly possess these two characteristics. How does one obtain a high level of awareness? There is only one way and that is through constantly studying and increasing the awareness. There are methods of studying, note-taking is a very good weapon that we should pick up. Strictly speaking, vigilance is also a part of the awareness. The reason why I made vigilance a separate topic is to emphasize its importance. There has already been countless feedback showing that once the vigilance is relaxed, there will be a relapse. Once it is relaxed then we will be eaten by the temptation demon. Therefore, we should maintain a high level of vigilance during every day of our reboot. Vigilance is like sand in our hand. As soon as it is relaxed, kidney essence will be lost.

In order to increase awareness, we should absorb the essential thoughts from a wide range of articles, not just my articles. As long as you think it is a good article, you should try to absorb its essences. For instance, health cultivating articles, traditional culture articles and other categories of articles can all be absorbed. You are like a tree, once you have absorbed enough nutrient, your awareness will become greater. By that time, the temptation demon will no longer be your match.

## The rebooting stabilization period {-}

Let’s talk about the rebooting stabilization period below.

The rebooting stabilization period states is one that is yearned by many brothers even in their dreams. Once the state has been reached, you will notice that the  _“tormenting feeling”_  is no more. The number of days in a streak is no longer important. You will notice that time passes very quickly without the feeling of torment. Because the people who enter the rebooting stabilization period can basically already defeat the temptation demon. The demon rarely comes out to harass them. During this stabilizing period, it is adequate to take some time daily to review the rebooting knowledge in addition to maintaining vigilance awareness.

Of course, if your level of awareness is high, you don’t have to study rebooting articles daily, once per week will also do, but one must maintain a high level of vigilance, that is very important. Without the vigilance awareness, one will be eaten by the temptation demon. No matter if you have rebooted for 200 days or for several years, you will relapse without vigilance awareness!

Brothers will then ask, how long does it take before one enters the rebooting stabilizing period?

Some articles have stated 70 days or 3 months. According to my research, the time it takes to enter into the rebooting stabilizing period differs from person to person. This is because the speed of awareness progression is different for everybody. For some people their awareness grows quickly, they might enter the stabilization period within 6 months. For other people, although they have rebooted for half a year, they do not study and so their awareness level is very low, they will still relapse repeatedly. If those people fail to raise their awareness, then they will never enter the stabilization period. The pass to the rebooting stabilization period is the level of awareness! This is comparable to the English requirement of some companies, such as level 4 or level 6. When your level of awareness has reached a certain level will you be able to enter into the stabilization period. Otherwise by not studying, the level of awareness will forever remain low, entering the rebooting stabilization period will be nowhere in sight.

At the time, it took me half a year to enter into the rebooting stabilization period. However, I did not relax my studies during that time, because I thought I had too much to learn. It is still like that today. Although I understand more today my studies have not ceased. I still want to study and understand deeper principles. The life that I live now is one of comprehension, constantly studying and realizing principles.

In determining whether one has entered into the stabilization period, one may observe the following. Normally when one has entered into the stabilization period, the temptation demon rarely makes an appearance, there will be no strong impulse to relapse. As long as vigilance is not relaxed, relapse will normally not occur. Before you have entered into the rebooting stabilization period, you will for instance have thoughts of relapsing over 20 times each day. When you are in the period you will notice that thoughts of relapse will occur no more than 3 times per day, even 0 thoughts. My state at the moment is 0 thoughts, I have not experienced impulses to relapse for a very long time.

I cut out sexual fantasizing when it starts before it is formed into an impulse. I adhere to 2 words when cutting out sexual fantasies these days:  **quick and brutal!**  Sexual fantasizing is not to be tolerated. Towards it, there is a zero-tolerance attitude, no compromises at all costs. Another big characteristic about entering into the rebooting stabilization period is the disappearance of the  _“suffering feeling”_. It is the lack of that enduring feeling, the feeling of not being able to cope. One stops caring about the number of days in a rebooting streak, this is because your rebooting awareness has already completely exceeded the  _“number of days”_  level.

What’s worth paying attention to is that at the beginning of the rebooting process, one will enter into the desire hibernation period. This period will normally last for around a month. During this time many people will experience very little sexual fantasies, the desire to relapse is basically absent. This period is not the rebooting stabilization period, but it is merely a period of desire hibernation, one must be clear on this. Many people during the desire hibernation period become very pleased with themselves, thinking that rebooting is very easy. Once this period has passed it is followed by the peak relapsing period, this is when your awareness and determination will be tested.

Lastly to summarize, the sign of entering the rebooting stabilization period is: awareness must be adequate! If the awareness is not adequate, one will not enter into the stabilization period even if one is rebooting for over a decade.

## The issue of sperm quality {-}

Lastly let’s discuss the issue of sperm quality.

Firstly I would like to bring up a few cases:

**Case 1:**  Before marriage, there was a year long history of intensive masturbation. This caused forceless ejaculations in married life. Attempts to have a kid have failed. I went to do a conventional seminal check and found out that the seminal volume was only 3 ml. There was no sperm, white and red blood cells were present in the semen. Before my history of masturbation, my constitution was good. After masturbation my constitution became weaker, I often experience waist pains.

**Case 2:**  I started to masturbate around 7-8 years ago. I had scrotum dampness, upon later examination, I had no sperm. The results were the same after multiple examinations. Is there hope of gaining sperm? What kind of examinations do I need to do?

**Case 3:**  I have masturbated for 5 years, I have always tried repressing it. Once during ejaculation, a white granule the size of a yellow bean came out. After that I had no sperm upon examination. Can I be cured? My testis are also very small.

**Case 4:**  One day in the spring of 2001, after I had masturbated, I felt as if the sky was suddenly collapsing, shrouded in dizziness. I thought that everything would be okay after a couple of days, but this feeling of dizziness became more serious each day, I had unbearable hot flashes throughout my body. I was not married at the time and also I didn’t dare mention my masturbation and the associated events to my family.

During the spring of 2002, I felt that my health became progressively worse, the hot flashes were also aggravated. I went to the hospital for a diagnosis, the finding said that there was a micro genital wart on the head of my penis. I was extremely afraid and immediately looked for treatment. After the treatment, my body and brain became increasingly worse. Sometimes, my waist aches a lot while standing, my head feels dizzy and I feel like doing nothing, letting my imagination run wild.

Suddenly one day I felt a loss of sensation in my waist, I could not exert any strength. After having arrived at the hospital, nothing showed up in the diagnosis, the medicine that I was prescribed was very expensive. I then went to a street outpatient service, I was prescribed with Renhui Kidney. Before I was able to finish a box of it, I noticed that hot flashes in my body became aggravated. After that, the outpatient doctor prescribed to me his own formula of kidney supplementing TCM capsules and large amounts of Western medicine in the form of vitamins, Liu Wei Di Huang Wan, Qi Ju Di Huang Wan, ..etc. The more medicine I took, the worse I felt, I was even sweating during sleep. My memory seemed to have disappeared, I was increasingly unable to apply my bodily strength. It was a hellish living, I was not interested in anything.

In this condition, I got married in the winter of 2003. During intercourse, I was unable to perform after minimal activity. Again I paid a visit to an old TCM doctor. He told me that all the medicine I previously took was not correct, he prescribed TCM to me for adjustment. Just like that, I could not be parted from TCM. I was constantly taking medicine without seeing any improvement. I could persevere with premature ejaculation by wearing condoms but things were still not good. After intercourse, I felt as if a layer of skin had been peeled off of me. My body and brain felt very fatigued, especially the left side of the head  which felt numb, wrinkled and dull. The same sensations were felt on the back of my neck. Laboratory tests showed grade A and B sperm at 30%, I have been fertile for 3 years.

**Case 5:**  I have always had the habit of masturbation. It has been several years but I haven’t been able to change it. Right now I have been married for around 5 years without being able to produce a child. I still frequently masturbate after marriage, I’m very worried that it is caused by masturbation.

**Case 6:**  I have had a history of heavy masturbation during my teenage years. After marriage, I was diagnosed with weak sperm. There were too few grade A sperm, the live rate is too low. What can I do?

**Case 7:**  I have always satisfied my needs through masturbation before marriage. Previously I didn’t know what the consequences would be. I would masturbate 5 days of the week. Since being married for a year, I have not been able to produce a baby. Afterwards, I went to get a diagnosis and it showed that I had weak sperm, I’m ready to faint.

**Case 8:**  I’m a guy, 34 years old, married for 5 years, I have not been able to get a baby all this time. I went to do a checkup with my spouse and it was found that I had medium grade weak sperm.

**Case 9:**  I’m 20 this year. For half a year, I have been cohabitating with my girlfriend, she was not able to get pregnant. I started to masturbate when I was 13 and did it quite frequently, once a day on average. I have been doing it for 5-6 years. When I was 15, I often had nocturnal emissions. Now my penis is still the same size as when I was 13, only 8 cm. My Adam’s apple is not pronounced either, facial hair sparse. It feels like I’m still owed a period of development time and I haven’t developed fully. In addition, I’m easily fatigued, aches in the back and the waist. Shuddering from the cold during the winters and sweating a lot during the summer. A while ago, I was at the hospital to check my sperm. There were 3 parameters that weren’t normal: A grade sperm 9.78%, B grade 7.68%, PH value 7.0.

**Case 10:**  Masturbating since I was 13 years old, sometimes frequently, sometimes once every couple of weeks. After marriage it was discovered that I had severe premature ejaculation, this didn't improve for 5 years. Last year, since March my morning erections disappeared. Previously my penis would become erect easily but the firmness was not great. Since I have lost my morning erections, erections are more difficult to achieve than before.

Prior to marriage, I always felt lots of heat in my body, I would sweat easily. At the least of movement, I would sweat all over. After marriage, this became a bit better. My memory is poor, I’m easily fatigued and I can't concentrate. Oftentimes, I experience sore waist, aching back and a dull complexion. I caught tuberculosis in 1995. Upon examination in 1998, the doctor told me that I fully recovered. I work in product design, everyday I use the computer quite a lot. Sometimes when drawing I sit for 2-3 hours without moving. Upon multiple diagnoses the results were all dead sperm  _(0%. After treatment and medication, I would sometimes reach 5-10% but never exceeding 10%. After halting medication, I would return to 0%)_. The rate of malformed sperm is especially high at 60-80%. Color Doppler imaging has shown mild varicocele.

Masturbation will damage the quality of the sperm, this has been confirmed by Western medicine. Masturbation may induce urinary tract infection, prostatitis, varicocele, seminal vesicle, impotence, soft erections, habitual premature ejaculation, ..etc. Once one has contracted prostatitis, it will inevitably affect sperm negatively. In addition, varicocele will also negatively affect the quality of the sperm. Of course, infertility does not apply to everyone suffering from prostatitis or varicocele, one needs to look at the seriousness of the condition. Although many people have chronic prostatitis, when they go and examine the quality of the sperm, they are still fertile, only that there are lots of malformed and dead sperm. The diagnosis has shown that the sperm of some brothers is displaying low vitality.

Although some brothers may still be fertile, don’t think that everything is good, because fertility does not translate to healthy offspring. Sperm produced under the environment of chronic prostatitis and varicocele will inevitably be of an inferior quality compared to sperm produced under normal conditions. The Ministry of Health published  _[Birth defect prevention report in China (2012)]_  has shown, the annual average rate of birth defects in China is roughly 5.6%, around 900,000 cases. According to the 2007 published estimation for the number of newborns and rate of birth defects in Chengdu, there were 1200 babies born with defects in Chengdu each year. The main defects are cleft lip and palate, congenital heart disease, hearing impairment, ..etc. Everyone is probably aware that the child of Wang Fei and Li Yapeng was born with a cleft lip.

Sexual indulgence without restraint leads to downcasted vigor, fatigue, heart palpitation, dizziness, sore waist and soft legs. All of these are signs that sexual activities have exceeded the load of the body. Not only does it make one’s will depressed, affecting health, but it also increases the burden on the testis, adversely affects the formation of high-quality sperm, obstructing eugenics.

Although many brothers are still fertile, the quality of their sperm is very ordinary. Famous TCM physicians in the past have mentioned that the offspring of people who indulge in debauchery tend to suffer premature death, the bodily constitution is also poor. Therefore, we should persist in cultivating the health prior to getting married. Cultivate the body well, cultivate the quality of the sperm. In doing so, the conditions of eugenics can be aligned. In doing this, one is being responsible for oneself, towards the family and towards the offspring.

As soon as problems appear with sperm quality, on one hand, one needs to persist in health cultivation. This is the basis for improvement of sperm quality. In addition, one needs active treatment, the quality of the sperm will slowly return to normal in this way. If you take medicine while indulging, whether or not the quality of the sperm is able to recover will be a question mark. Even if one temporarily recovers, if one keeps on indulging, it is difficult to guarantee that one will not fall down once more. The consequences of indulging in debauchery are really too great. Not only will it affect your health but also your offspring's. Therefore, we must properly reboot and cultivate the health, both for ourselves and our offspring.

## Books recommendation {-}

The feedback that I have received from everybody following the recommendation of the 5 books was quite good. But some brothers have mentioned that they cannot understand Classical Chinese writing. Actually of the books that I have recommended, as long as one has a high school level of education, reading will not be of a problem. Of course you may also look at comparable versions that are in plain language. Books on physiognomy will usually have comparable versions in plain language, TCM related books will not have such versions. In order to understand TCM books, one will need to have a certain foundation in Classical Chinese. But there are also exceptions, [Inner Canon of the Yellow Emperor] has versions in plain language. In this season I will continue to recommend 5 books:  _(Translator’s note: due to the unavailability of the English versions to some of the below books, I have chosen to retain the original Chinese titles as listed by Soaring Eagle)_

(九种体质使用手册), Wang Qizhe, Wangqi is a professional at Beijing University of Chinese Medicine and tutor for Ph.D. students. This book is quite good, I understood my own type of physique which allows me to health cultivate myself better.

(The Secret), herein lay buried a secret that has been hidden for 2000 years on wealth, success and health. Ever since the day that humanity has existed, humans have sought after this secret. This book has also been recommended by the Tudou message board moderator. The book deals with the law of attraction, actually it is the principle of suggestion from the field of psychology. If you suggest active contents for yourself, then all of your energy will be directed towards the active direction. If you suggest yourself with negative and pessimistic contents, you will then become very negative, the odds for failure will increase this way.

(名医类案), composed by Jiang Guan in the Ming dynasty. This is a book on medical cases. It is a clinical summary of famous physicians in the Ming dynasty, there is an abundance of cases. I like this book very much. Through reading the cases, one will know how people become sick. When you have learned the causes of the illnesses you will know how to avoid them. Many TCM cases have mentioned case examples on indulgence in debauchery. In some medical record books, an example of indulgence in debauchery will appear in every few pages. Therefore, researching in TCM medical cases is very helpful towards the raising of our rebooting awareness.

(The Talent Code), The Talent Code is about becoming a world expert in a field, you will need roughly 10,000 hours of practice. There are no other ways, if you want to become successful, then you must spend 10,000 hours. The theory in the book has a sense of inspiration. Myelin is the key to communication, reading, study skills, and to how people are formed. The concept of myelin is very interesting, I believe those who have read the book will be familiar to this term.

(灸除百病): When it comes to my physical recovery, moxibustion is indeed the biggest benefactor. Especially towards the improvement of my stomach function and rhinitis, moxibustion has indeed been very effective. In supporting the Yang, moxibustion is number one. It is mentioned in the (Canon of the Yellow Emperor): When the Yang qi is sufficient, there is longevity, the method of moxibustion is the foremost. The famous medical scientist Dou Cai from the Song dynasty in (扁鹊心书) believes there are 3 ways of supporting the Yang since ancient times: moxibustion as the first, pellet medicine as the second, aconite as the third.

Reading thus far, everybody surely thinks that moxibustion is very good. What I want to say is although moxibustion seems very simple, the principle therein is very deep. Therefore if you would like to try moxibustion, you had best first study related knowledge and cases, one could read books or watch a video about moxibustion. Although moxibustion is good, it does produce smoke and easily gives rise to blisters, one needs to pay attention to these aspects. By doing more reading and studying one may harmonize these two problems. By correctly applying moxibustion, your body will recover quicker and better. I have personally experienced moxibustion for over 2 years, my understanding is pretty good in this area.

Rebooting is only one aspect, how to cultivate the health is equally important. Many brothers have still not recovered optimally after having rebooted for over a year. The reality is that they have fared poorly in health cultivation. Many people lack health cultivation awareness altogether. They are still sitting for long durations, staying up during the night and not exercising. Therefore, if everybody wants to recover quicker and better, my advice is to put enough effort into health cultivation, strive to increase one’s health cultivation awareness.
