# Masturbating blood, dizziness and headache following masturbation, relapse after nocturnal emission

## Foreword {-}

### Repeated symptoms during winter {-}

Lately the weather has become cold and more brothers are reporting repeated symptoms. Repeated symptoms in chronic prostatitis are quite common, such as frequent urination during the night, urgent urination and increased wait time to urinate. Other brothers have encountered difficulties in sleeping, increased nocturnal emission, ..etc. These issues are intricately connected with a lower temperature. With a decrease in temperature, the chances of encountering repeated symptoms from various diseases will increase greatly. Due to  _“heaven and man corresponding”_, therefore when changes are taking place in nature, people should also make suitable adjustments in their house and in their diet to maintain their physical strength, reach a balance between Ying & Yang, qi and blood and thus maintain the health. Therefore, I advise everybody to pay attention in keeping warm, health cultivation, forming good resting and dietary habits, avoid over fatigue, allow one’s body to adjust to changes in the weather as soon as possible.

If the repeated symptoms following changes in weather are not serious, there is no need to seek a doctor. Normally by resting for a couple of days, keeping up with nutrition, doing some moderate exercises, the symptoms will slowly disappear, there is no need to worry.

Everybody knows that illnesses are made easier by the winter cold. However, they do not know that if the body is not properly nurtured during winter, illnesses will come easier during the spring. [Inner Canons of the Yellow Emperor]:  _“If essence is not conserved in the winter, sickness in the spring will be inevitable”_  mentions the said principle. TCM believes that exogenous cold most easily injures the kidney Yang. Therefore, to resist the cold, one must cultivate the kidneys. Otherwise, the immunity of the body will be affected by the deficiency of the kidneys, easily giving rise to illnesses.

From the perspective of TCM, essence, qi and spirit are the most important driving forces of life, essence in particular being the foundation. Therefore  _“The person who is good at preserving the essence is prone to lead a long life, the person who excessively damages the essences will meet an early decline”_. When the winter season comes, I advise all brothers to pay attention to kidney cultivation. In particular, do not relapse to the best of your ability. Otherwise, there is a strong chance that it will affect your health in the coming year.

“The 3 months of the winter acts as storage. Water and ground freezes. Do not disturb the yang. Retire early and arise late, wait for the sun to go up. Let emotions barely exist, as if keeping a secret, an own understanding. Keep distance from the cold and approach warmth, do not shed through the skin and thus allow Yang qi to expel. Winter qi is as mentioned, the cultivation of storage; by doing the opposite the kidneys are injured, weakness follows in the spring. There will be nothing for the Yang qi to grow from due to the lack of Yang qi.”  _(Translator’s note: please allow for mistakes in the above translation. As far as I’m concerned there is yet any English translations to the original Chinese texts. I have sought help from 2 capable native Chinese speakers for a more accurate understanding, the above translation has been carried out to the best of my ability, although the quality is still below my satisfaction)_

The above paragraph comes from [黄帝内经四气调神大论], in plain language it means: Winter is the Yang qi storage season.  _(Trees and plants are withering, the seeds are buried under ice and snow. The plants are withering, the animals are hibernating, all the life forms on the ground are nowhere to be seen. Ice is also formed on the water surface, this is “storage”)_. People need to sleep earlier and get up later, i.e. waiting for the sun to have risen before getting up. The will of a person also needs to resemble hibernation, as if tucked away. Pay attention to keeping warm, do not expose the skin and hence let out the Yang qi. This is being compliant to the winter, the way of storage cultivation. Going the opposite direction will injure the kidneys  _(damage to kidney water is the cause of the loss of wood in the liver, liver governs the tendons, if the liver wood is not growing, the tendons lose their support)_. The hands and the feet easily weaken during spring, the growth of the Yang qi will become affected.

In the five internal organs, the kidneys govern water and the corresponding season is winter. The foundation of the kidneys is determined prenatally, it is the root of life. Enough Ying needs to be stored in order to replenish the Yang. The kidneys store the essence. Essence ought to be stored and not to be expelled, it has the characteristic of hibernation and storage.

It is said therefore that when winter arrives, we should to a larger extent to not relapse, desire should be shelved, putting ourselves in a state of hibernation, properly storing the essence, “the person who is adept at health cultivation inevitably believes in storage”. During winter one should pay even closer attention to “the way of storage cultivation”. If you repeatedly relapse during the winter, when spring comes, your spirit will be very decadent, your resistance towards diseases will be lowered and diseases will easily arise.

### Repeat symptoms in the skin {-}

Recently, many brothers have been mentioning repeated symptoms in the skin. The face is the mirror to the five internal organs, repeated symptoms in the skin are quite common. This especially applies to brothers who are not fond of exercising, who sit in front of a computer screen for long stretches of time. Long-term exposure towards the computer monitor will lead to  _“monitor face”_. Even if you have not relapsed, your skin will still be of a poor condition. Due to radiation from the computer, in addition to being in a state of long duration sitting and long duration gazing. It is therefore not favorable to the adjustments of internal secretions, an improvement in the skin will be difficult to come by.

Furthermore, factors which induce repeated symptoms in the skin include nocturnal emission, fatigue, overexposure to sunshine, eating volatile food  _(Translator’s note: this is a Chinese term, volatile foods include fungus, certain types of fish, meat and vegetables. Volatile food has the property of inducing or aggravating certain illnesses)_, staying up during the night, seasonal factors, ..etc. Diet directly affects the skin, eating volatile food, greasy and spicy food all may lead to skin problems. Therefore, when rebooting we should try to keep a light diet and then do more moderate exercises. This will reduce repeated symptoms for the skin.

Back when I had persisted in doing aerobic exercises for a while, I was able to feel clear improvements in the quality of my skin; the facial skin felt smooth. Previously, I sat for long periods of time without moving while facing a computer screen. My face felt rough, the complexion was dull, oil and acne outbreaks were common. Therefore, moderate aerobic exercises are helpful for the improvement of skin quality. Everybody please emphasize  _“moving cultivation”_, this is quite beneficial to the improvement in skin quality.

### Stretched sensation from kidney strengthening exercises {-}

I want to revisit the issue of the stretched sensation from kidney strengthening exercises. If you are unable to find the stretched sensation coming from the rear side of the thighs, then the benefits from the kidney strengthening exercises will be very limited. By doing the movement properly and finding that stretch sensation, the benefits of the exercise be unleashed.

Many brothers have asked about how to find that stretched sensation and where is it really located? Actually the stretch sensation from the kidney strengthening exercises is mainly found at the rear side of the thighs, secondly it is found on the side of the knees, lastly in the calves. The sensation is relatively easily felt on the side of the knees and on the calves. Finding the sensation on the rear side of the thighs is comparatively more difficult.

This feeling can be found in 2 ways. One is through feeling: whether or not the stretch sensation is felt at the rear side of the thighs. The other way is through touching: whether or not there is tension, can be felt. Sometimes one might objectively not feel much, but upon touch it feels tense, feeling elongated and tightened, this will also do. By correctly finding the tightened feeling and intensifying it, the kidney strengthening exercise has been properly performed.

In rebooting, one must pass the level of frequent nocturnal emissions. In this way, the body will have a guarantee towards recovery. Yet there are many factors which induce frequent nocturnal emissions. I have summarized over a dozen such factors, this has been written about in previous articles, everyone may have a look. It is also unusually important to avoid other factors for inducing nocturnal emissions.

We will enter into the main topic below.

In this season we will talk about the issues of masturbating blood, dizziness and headache following masturbation, relapse after nocturnal emission in detail.

## Masturbating blood {-}

Senior brothers who frequent the rebooting forums will know that there are often posts about masturbating blood. Every couple of days, there will be these kinds of posts. Sometimes they even appear consecutively. Masturbating blood easily causes the mind to panic. Some brother have said  _“a major thing has occurred”_, some say that they are  _“genuinely afraid”_. Masturbating blood should be a relatively common occurrence. Many brothers are in the state of ignorance, are controlled by their addictions and masturbate like crazy. This type of crazy indulgence in masturbation has actually already caused latent damage to the body, symptoms will sooner or later appear. Only the circumstance of masturbating blood causes a rather large psychological impact for the sufferer. This in reality is not a bad thing, this will allow him to speedily wake up and give birth to the thought of rebooting. There is a saying in economics:  _“crisis causes restraint, a forced restraint”_. If there is no blood in masturbating, perhaps one would continue to be addicted, running all the way towards the path to self-ruin.

Let’s look at a few cases of masturbating blood:

1.  Yesterday I relapsed and masturbated 3 times. The first ejaculation was very normal, the second time there was little semen, there were threads of blood in it, I became very afraid. Today I wanted to see if there is blood in the semen, after masturbating for a while I could not ejaculate, I didn’t dare to force it, what’s going on here? Requesting urgent help! I’m suffering right now! Truly regretting!
    
2.  While ejaculating during masturbation, the first ejaculation was milky white, the latter 3 drops were slightly red. The day before I had also masturbated! A while ago there was a day when I had a muddled feeling of pain in my belly. When I was a teen I once had epididymitis, it was cured by medicines.
    
3.  Oh my god! I masturbated blood, light red in color. Requesting urgent help! What do I do? I’m not in pain but there is blood!
    
4.  4 days ago, there was a lot of blood during masturbation. 2 days ago, when I ejaculated for the second time, the semen was slightly red. I’m 19 this year, normally I masturbate quite frequently  _(trying to get rid of it now)_. It’s very scary to run into this kind of condition.
    
5.  Genuinely afraid! I haven't dared to masturbate again. There is another chunk of blood in the semen. Am I to be without descendants?! I have really masturbated blood, really afraid. In the beginning, the blood chunk seemed to be solid, I thought it wasn’t blood. I squeezed it with my fingers and it fell apart, it was blood. I don’t ever dare to masturbate again, everyone fend for yourself!
    
6.  I have always resisted ejaculation, previously the semen was transparent, now what comes out is bloody semen. What’s going on here? Anxious!
    
7.  I have masturbated for many years very frequently. But recently, when I masturbated there were threads of blood. I don’t know if this is because I have masturbated and so have contracted some disease, what do I do! What’s causing the threads of blood to appear in the semen? What should I do?
    

According to my research, normally if one masturbates consecutively for a couple of days or masturbates multiple times within the same day, this phenomenon will easily arise, it is over-masturbation. The chances for symptoms to arise following consecutive masturbation is very high. Even if one does not masturbate blood, the possibility of running into other symptoms is extremely high. How much kidney essence is there for you to masturbate? Even if your constitution is very good, long-term addiction to masturbation will give rise to symptoms.

When blood appears in semen, it is called bloody semen. The reason for bloody semen is normally considered to be inflammation or calculus issue such as prostatitis, seminal vesicle, urinary tract infection, epididymitis, varicocele, prostate stone, urethral bladder stones. Of course, there are other causes for bloody semen. Given that everybody is quite young, normally, the possibility of inflammation or calculus are considerably less than the chances of inflammation. If one is still worried, one may go to the hospital for a diagnosis. When bloody semen appears, don’t panic too much but be afraid to injure the kidneys. Bloody semen is the body giving you a signal, telling you to stop masturbating, it is time to pull back. Normally when bloody semen appears, a person will know it is time to exercise restraint and to stop the act. If you continue to go against the wind and masturbate then you are really fed up with living.

## Dizziness and headache following masturbation {-}

Below let’s talk about dizziness and headache following masturbation.

TCM: _the kidneys are connected to the brain in the above_.

The greatest number of acupoints are found on the head and neck region of the human body. A total of 76 which is 21% of the total 361 number of acupoints. The head houses the brain which is transformed from kidney essence, it is governed by the kidneys. The brain is the hub of the nerves, is the highest command in managing the entire bodily movement, feeling, language and the movements of the internal organs. The face is a reflection of the internal organs. It is connected by the meridians and opened by the transformation of qi.

There are 14 meridian nerves in the human body. There are 3 hand yang meridians, 8 meridians from the yang channels of the foot, conception and governing vessels follow an upward path and terminate at the face. Ancient TCM physicians consider:  _“The head is the meeting point of all the Yang, astuteness is housed in the brain, it is also the place of the marrow sea. The essences of the five internal organs reside in the blood. The Yang of the six bowels resides in the qi. All is concentrated in the head.”_

A very obvious truth is: masturbation injures the brain, masturbation damages the head! In this season we will talk about dizziness and headache following masturbation.

I will share a few cases below:

**Case 1:**: Soaring Eagle big brother, hello. I should say that I have already masturbated for 20 years. I remember ever since I became sensible I liked to play with my little penis. Between 2009-2010, I exchanged obscene text messages with a girl daily. In other words, I was constantly sexually fantasizing. And in November of 2010, my body started to experience serious headaches. Up until today, the headache is still very serious. I am taking Chinese herbal medicine during this time. At the same time, it is as you said:  _“in taking in one end while shedding through the other end”_.

Furthermore, up until May of this year, I’m still masturbating. Although I know that the problem was caused by masturbation and sexual fantasizing. After that, I made up my mind to never masturbate again. At the same time I was able to do what I said I would do, but no matter what I have not been able to conquer sexual fantasizing. I noticed that as soon as I’m thinking about my penis, liquid will flow out of it. It will happen when I’m thinking about the words masturbation and sexual fantasizing. I feel that I have already gone mad. Right now my eyes are very dull, my head is very dizzy, the dizziness never gets better, my eyes are constantly drowsy.

Previously following masturbation, my head would often hurt, the head would feel dizzy, the entire body felt light as a feather as if having taken alcohol. In addition, my memory is very poor, I’m forgetting things, my level of comprehension is low and my reaction is slow. Due to this, a while ago I went to the hospital to do brain imaging. They said that I had neurasthenia and autonomic disorders. I have also taken Liu Wei Di Huang Wan, I didn’t feel any effect from taking it. I’m afraid, now I don’t dare to masturbate.

**Case 2:**  I have been masturbating long term. Recently, after a session, I felt dizziness and headache, blurred vision, sleepiness, yellow urine with a heavy odor. When it comes to headache, it is the temple and the back of the neck hurting interchangeably, hurting in one place for a while before switching to the other place. The swelling pain in my eyes doesn’t allow me to look at one place for too long. It is very painful to browse the internet, I feel as if my eyes cannot open and I want to shut them.

**Case 3:**  I have masturbated ever since elementary school. Now I’m in college. My head is always drowsy. I feel as if there is a big iron ball inside my head  _(not exaggerating)_. During midnight, my kidneys would always beat. My four limbs are without strength, I cannot play basketball anymore, ack! It is affecting my studies and it’s also uncomfortable. Somebody come and help me!

**Case 4:**  I’m turning 22 this year and have been masturbating quite frequently for several years. In recent years, after I masturbated, I would immediately feel dryness and thirst in my mouth. My waist aches like crazy and is a bit painful, it has not faded in several days. Since a week ago, the back of the head felt dizzy like crazy. When I’m feeling particularly dizzy, I go and lie down for a while. When I get up, I feel quite awake. After a few hours, I feel dizzy once more. I suffer from a lot of internal heat and during the night, I’m unable to sleep.

Nowadays, I feel dizziness at the back of my head everyday. I don’t have the mood nor the strength, I’m unable to work. I have gone to see the doctor and have taken medicine without reprieve. Save me!!! If I go on like this, I don’t want to live. I always feel as if something is pressing towards the back of my neck. I have not seen any effects from taking Liu Wei Di Huang Wan and from taking soothing and brain supplementing medicine! I’m still feeling dizzy. The doctor has applied scraping  _(TCM)_  on me. My entire body is blackish red, there is a lot of internal heat. I still feel dizzy like crazy, scraping didn’t help. I’m afraid to tell the doctor that it is caused by masturbation. I’m really suffering. What can I do to get better? It’s really uncomfortable. Save me!

The cases that I currently have which show dizziness and headache following masturbating are many. Masturbation hurts the head. At first, it damages the brain power. After a certain degree of damage has been sustained, there may be dizziness and headache. If your condition of dizziness and headache is persistent then go see a doctor. Normally, the diagnosis will be neurasthenia or autonomic disorders. The bottom line is that there are problems with the nerves.

In my article from season 30 I have specifically talked about neurosis. Masturbation will indeed damage the nerves, but a certain degree of damage will need to have been sustained before neurosis appears. If you stay up during the night, sit for long stretches of time and masturbate like crazy, then the chances of getting neurosis will be quite high. In addition, some brothers have a naturally poor constitution, their body can withstand even less masturbation and cannot afford to become injured.

When dizziness and headaches appear, one must be persistent in rebooting followed by active treatment. Slow recovery towards normal will be possible in this way. I have encountered both dizziness and headache, roughly after a half year of rebooting and health cultivation, I slowly got better. During that time I often did standing qigong, Six Letters Formula qigong and moxibustion, it is then followed by active exercise. In the beginning, I was not able to exercise much due to headaches and so I would walk quickly. Slowly, the body recovered. Indeed, the speed to which disease leaves the body is comparable to spinning silk, the recovery is made thread by thread. The normal feeling upon recovery is like crawling back into the world from hell. From there on, I greatly treasured this hard to come by feeling of being healthy.

Health is recovered through cultivation, moral cultivation, Taoist cultivation, health cultivation, in addition to actively exercising. In reality, active treatment is the smaller part of the whole picture. The bigger part is made up of moral cultivation, Taoist cultivation and health cultivation. 30% treatment, 70% maintenance. We need to learn to become qualified patients ourselves, otherwise, wishing to recover while relying on doctor and medicines is not realistic. Neurosis is not like having a cold after all. Shedding on one hand while treating with the other hand. Dare one ask where the path lies towards recovery?

## Relapsing following nocturnal emission {-}

Lastly let’s talk about the issue of relapsing following nocturnal emission.

First I will present a case:

_“I have been rebooting for a year. Lately, the results have been quite good, but following nocturnal emission my desire is very very strong. And in my mind, I’m very distressed, I will masturbate. A while later I have the thought of dying. How can I not relapse following nocturnal emission?”_

Relapsing after having a nocturnal emission is quite common, I have summarized this form of relapse. The following expressions easily appear following nocturnal emissions:

-   The mood becomes worse. When kidney essence is lost, changes will take place in the mood. The behavior of being impatient and easily angered will appear. There will also be the feeling of being defeated and discouraged. Of course, nocturnal emission does not count towards relapse, there is no need to feel defeated. As long as one does not suffer from frequent nocturnal emissions, there is nothing to worry about.
    
-   Returning to the state of hyperactivity in the Yang due to Ying deficiency. Following nocturnal emission, desire will be awakened. It will become  _“restless”_. If one does not raise the level of vigilance at this stage, it will be extremely easy to relapse.
    
-   Repeated symptoms. Nocturnal emission also injures the body. Even greater injuries come from frequent emissions. Normally following nocturnal emissions, symptoms will temporarily repeat themselves. They will be alleviated or even disappear following a few days of rest.
    

We must correctly recognize the phenomenon of relapsing following nocturnal emissions and correctly face the issue. Pay attention at all cost to mood management and raising the vigilance after nocturnal emission in order to avoid relapses. Every time following a nocturnal emission, I immediately repent. This is because every time I feel the emerging desire, repenting during this moment will have the effect of eliminating desire.

Every time I have a nocturnal emission, my vigilance will increase because it is very easy to relapse at this time. I have repeatedly emphasized the importance of emotional management many times. The brother from the case is not managing his emotions sufficiently well. Following relapse he became distressed. At this time, one must immediately adjust the mood. Make more active and positive suggestions to oneself and let oneself remain in the calm state of peace of mind. In addition, one needs to increase the vigilance awareness. Relapses following nocturnal emissions can be avoided this way.

## Books recommendation {-}

In this season I will continue to recommend 5 books:

(‎Śūraṃgama Sūtra): the contents of the Śūraṃgama Sūtra helps people to become enlightened by virtue of knowledge. The ancients have once put in poems:  _“ever since reading Śūraṃgama sūtra, no longer reads garbage books from the world!”_. The saying goes that the Lotus Sutra is the way to Buddhahood, Śūraṃgama Sūtra opens the wisdom. In order to deepen the Buddha wisdom, the Śūraṃgama Sūtra is a must read. I have read the Śūraṃgama Sūtra many times. A new understanding is gained in every reading. In it, continence has also been mentioned in addition to the 4 kinds of tranquility. Brothers with Buddhist karma, do not to miss this book. They may read the corresponding translated version of the book in everyday language.

(黄帝内经二十四节气养生法): authored by Wang Wei. This book guides us in letting nature take its course and teaches us the 24 solar terms health and essence cultivation. This book builds upon the [Inner Canon of the Yellow Emperor]. It incorporates the different characteristics of the 24 solar terms, goes through deep and detailed analysis. It points out the key points and methods in health cultivation that one needs to pay attention to within the 24 solar terms of a year. I like this book very much, from it I have learned much about health cultivation. It has also opened my eyes.

(王晨霞掌纹诊病): Health secrets are hidden in the prints of the palms. The 14 mysterious lines and the 8 different kinds of patterns that you don’t know about reveal the secret source of your body. When thinking about palm prints, everybody surely thinks about fortune telling. Actually, there are similarities between palm print consultation and numerology. Although, the modern study of palm print consultation is more scientific. The Western scientific community has actually since long time ago researched into the relationship between palm prints and the bodily health. Therefore, modern palm print consultation is quite scientific.

Everyone may take a look in this book, it is a wonder book. Youku has 32 episodes on 王晨霞, everyone may take a look, one may also purchase the book. I have watched the videos and read the book. They are very good. Therefore, I’m recommending palm print consultation to everyone. Many brothers regard the fingernail crescent as a sign of bodily health. Actually the 4 lines in the palm prints can also be used to determine the state of the health. This is because the 4 lines are the lines of health. Once everybody has studied it they will understand.

(人体的春夏秋冬), written by 史赞华. 王晨霞 was born into a Chinese medicine family and is a well-known physician from Qilu. He is well read, well versed in the medical classics, good at both TCM and Western medicine, possessing deep knowledge in health cultivation and unique insights.

Liver as spring, emphasize the cultivation of “birth”. Heart as summer, emphasize the cultivation of “growth”. Lung as autumn, emphasize the cultivation of “collection”. Kidneys as winter, emphasize the cultivation of storage. [Inner Canons of the Yellow Emperor]:  _“the person who is adept at health cultivation inevitably believes in storage”_. Cultivating the health is lesser compared to the cultivation of storage. The old TCM doctor has given all in order to teach the cultivation secrets of TCM, helping people to arouse their own power of healing. This book explains health cultivation from the perspective of the four seasons. It is very good, I review this book often.

(志愿军老兵回忆录), written by 袁永生. This book can greatly encourage you. It may provide one with strong psychological motivation. It is about a retired veteran who has lived through many changes, telling you about the smoke and fire from the war that has taken place. Normally, I’m a calm and low-key person, but reading this books still makes me feel very excited. The stories told within is able to pierce the soul. After having read the book, I feel charged with power. It is a strong spiritual tonic and occupies an important place in my heart.
