# 5 case studies, directly looking at premature ejaculation, conclusion on premature ejaculation

## 5 case studies {-}

Let’s analyze 5 cases:

### Case 1 {-}

> Brother Soaring Eagle! I have had the habit of masturbation for several years. Up until now, I have not been able to get rid of it! All of the symptoms except for hair loss are present, ack! What should I do?! Please instruct me, big brother! I have read all of your articles but I’m still unable to get rid of masturbation! I’m almost a wasted person! When winter arrives in particular, the back of my hand and my wrists are especially dry. They are very easily cracked, there’s blood! My record streak is 45 days! After that, I relapse like crazy! I even have thoughts of wanting to die!

**Analysis:**

Up until now, out of the 1000+ brothers that I have chatted with, those who are able to completely reboot upon first coming into contact with rebooting articles are extremely few. Only those brothers with good karma, strong study awareness and high realization were able to do it. The rebooting forums are like a big class with tens of thousands of students, everybody is studying rebooting articles. There is also the classification of good and poor students.  
For the vast majority of the brothers, in order to succeed, one can say that they must walk through the path of relapse. It is not scary to relapse, relapsing is to pay the tuition in essence. One should not pay the essence tuition in vain. After relapsing, one must summarize the lessons learned, repent more, introspect the areas in which one is deficient in. Only by doing this, can one reboot better and smarter. To relapse this time is for a better reboot next time. One needs to constantly perfect oneself, summarize and introspect. Let realization to continuously grow, by persisting in this manner can one completely reboot. The troubles that this brother is experiencing should be quite universal. I have summarized 3 articles why relapses occur even when studying rebooting articles . They are found below:

**(1) There are problems with the method of studying.**

A good study habit allows for a faster increase in studying efficiency. Just like listening to a lecture, I’m asking you have you listened? You say that you have listened. Then I ask you, what did the teacher say? You can’t remember anything clearly. The words enter the left ear and exit from the right ear. When the studying efficiency is low, the absorption rate will be too low. When studying rebooting articles, we must increase the absorption rate.

I recommend taking more notes, write down the experiences and contemplate more. Then make a goal for yourself everyday, such as writing down 10 rebooting notes daily. These 10 rebooting knowledge notes comes from rebooting articles. Whichever sentence you think is good you write it down. Write down 10 sentences everyday, then take the initiatives to memorize these 10 sentences, memorize them for real. There are 30 days in a month, that is 300 lines of rebooting knowledge. Repeatedly read, repeatedly memorize, increase the absorption rate. The increase in realization will be fast this way. Every brother should have their own rebooting notebook. Review the old in order to learn the new. Read repeatedly, in every reading you will have new rewards.

**(2) A decrease in brain power.**

The emergence of decreased brain power among brothers is very commonly seen. Due to decreased brain power, this leads to a low studying efficiency. Many brothers lack determination, their memory and concentration are all very poor, some people even experience drowsiness. The conditions for studying under these circumstances is quite poor. I recommend these brothers to persist in rebooting for a while, exercise actively, keep up with the nutrition, wait until the brain power has recovered somewhat and then start to thoroughly study rebooting articles.

**(3) The level of realization is inadequate.**

Many brothers have gotten the correct general bearing. They put in a lot of effort into studying rebooting articles. But there is a process involved in the increase of realization. One cannot get there in one step, it is a process of unceasing persistence. Your realization is increasing, but if it is not strong enough to withstand the temptation demon then you will still relapse.

Just like when your level of realization rises from level 15 to level 50 through studying rebooting articles, but the temptation demon is at level 100. At this level, there is still the chance of relapsing. Only by constantly studying and gaining true enlightenment can your realization receive a leap in substance. When your realization is powerful, defeating the temptation demon will not be an issue.

### Case 2 {-}

> Brother Soaring Eagle, I’m very depressed. Whenever it’s time to rest during the weekend, the desire for sexual fantasizing is stronger than normal. I’m always relapsing during the weekends! What should I do? How do I get rid of sexual fantasizing from my mind? I have a hard time reflecting on repulsiveness! I’m genuinely seeking help!

**Answer:**

Your current problem is due to shallowness in determination. During the weekend the temptation demon comes out to pick at you. If your realization and determination are not strong then it is very easy to relapse. I recommend studying more in order to increase realization. Summarize more and memorize more rhymes for cutting short sexual fantasizing. Keep on fighting!

**Analysis:**

I have specifically summarized the condition of weekend relapses in the season about the different variants of relapses. This is a very common form of relapse. For students in particular, weekend relapses are as common as everyday food. To change this condition, one must first become aware of weekend relapse and then raise the vigilance during weekends.

In particular, constantly guarding oneself. Pornographic landmines are everywhere on the internet, one needs to be extra careful. Whenever the weekend comes there will be  _“demon tests”_. The temptation demon will come and test you. If the test is passed one may level up, failing the test is to relapse. After relapsing, one needs to summarize more of the lessons learned, study more to increase the level of realization. Gradually, when there is enough determination, weekend relapse will automatically cease to be.

### Case 3 {-}

> Yesterday I switched to a thicker blanket, lying on my back resulted in nocturnal emission… It has only been some 20 days since I had one, my blanket is too thick, I had an ominous hunch before using it

**Analysis:**

> The essence of the five internal organs resides in the kidneys, heat leads to the discharge of essence.
> 
> — (TCM)

Covering oneself with a thick blanket or with a blanket that has been baking under the sun may under both cases lead to nocturnal emission. There are lots of cases like this, many brothers have reported this. Normally there are 2 explanations for the discharge of essence due to heat. The first is that the person suffering from heat will sweat, he who sweats also loses essence qi, the essence is lost through the form of sweat. The other explanation is that over-temperature will stimulate the kidney essence, leading to essence losing its position, nocturnal emission then takes place during the night.

Many people don’t know about the second explanation, only those with deep experience can possibly understand. I very much emphasize experience. If you lack experience, then what you read in the books will only leave a shallow impression in the brain, the impressions are not deep. If you have been bitten by a snake, you will never forget it as long as you live.

What’s important here is that heat leads to the discharge of essence, the heat here means over-heat. Not only being covered by a thick blanket but also by soaking the feet in water that is too hot will also lead to the same result. Everybody should pay more attention in this area. There are several dozen causes to nocturnal emission, I have specifically summarized this in my previous article. Frequent nocturnal emissions is a hard threshold, it must be passed. If it cannot be conquered then recovery will be near impossible. Frequent emission alone by itself may lead to many illnesses. In order for the body to recover better, it needs a stable and even a low rate of emissions.

### Case 4 {-}

> Big brother Soaring Eagle, I’m a high school senior. Because I didn’t know any better I started to masturbate since year 1 of middle school. The 1st of May, I was diagnosed with a mild form of tuberculosis. Today, I’m still taking medicines daily. I faintly sense that it has something to do with masturbation. Unintentionally, I discovered the rebooting forums while surfing on my cell phone and so I started to reboot since 1st of August. Although in between periods, I have often sexually fantasized. Finally, on the 30th of September, I had a relapse.  
> Ever since that date, I readjusted my mentality and sexual fantasies decreased. Maybe it is due to my busy schedule during year 3 of high school, my entire focus was on studying. We had midterm exams yesterday and today. Yesterday I was full of vitality, this lasted up until this morning, when I had a nocturnal emission. During the morning, I clearly felt my head was slowing down in addition to being tired. Moreover, when showering in recent days, the area below my testis and between my legs would always itch, I have the urge to scratch it. I would like to ask big brother Soaring Eagle on what the matter is. Is it normal that I have nocturnal emissions? Be sure to reply once you have read it, I’m still new and don’t know much. I’m eternally grateful!

**Answer:**

If nocturnal emission doesn’t happen frequently, it’s not a big problem. But you have already been injured, one emission can cause repeated symptoms. Although, by resting for 2 days normally, the body will be able to gradually recover.

As to the issue of itchiness, my advice is to pay attention to cleanliness. If the issue persists then one may go to the hospital to obtain some lotion, this is not a big issue. Let me tell you again about the relationship between the kidneys and the lung. TCM:  _“The lungs give birth to water, kidneys are the organs which govern water. The lungs exhale air, the kidneys inhales air.”_  In TCM theory, the lungs and the kidneys operate breathing and fluid metabolism. The interconnectedness of the meridians and the theory of the five elements where  _“the child is affected by the sick mother”_  and  _“the mother is affected by the sick child”_  are intricately connected.

Western medicine has discovered that the lungs and the kidneys are breathing. There is a compensation mechanism between the pH balance of water and electrolytes versus the aspect of the primary and secondary nature of the disease. The importance of the mutually influencing relationship is demonstrated in the occurrence and metamorphosis in obstructive emphysema, uremia, and other illnesses.

**Analysis:**

Masturbation is able to affect the lungs when damage has been sustained to a certain degree and under the combined effect of other factors, sickness with the lungs may appear. The lungs are connected to the nose. Being addicted to masturbation easily leads to rhinitis or aggravates rhinitis. Some brothers have reported pneumothorax in the rebooting forums. If you encounter pneumothorax following masturbation, then this is to some extent related to masturbation. Masturbation leads to a deficiency in the kidneys, kidney deficiency affects the lungs. If other factors are stimulated then pneumothorax may be induced. Masturbation will lead to a vast decline in the immune system, the chances of catching illnesses will be greatly increased.

### Case 5  {-}

> A person on the floor below has been playing squash for an entire noon. I actually relapsed due to an irritable mood, I still have an exam to take! Regretting!

**Analysis:**

The form of relapse that this brother has suffered is relapsing due to emotions. Not only does an irritable mood make relapse easier, but other negative moods will also all easily lead to relapse. An example is following an argument between mom and dad, following a break up with a girlfriend, these all may lead to relapses. Of course, there are other factors that may lead to relapses such as boredom and over-excitement. In the process of researching into the behavior of masturbation, I have from very early on realized the importance of emotional management due to the large number of cases displaying an obvious reality: emotions will induce relapses. I have had a lot of experiences in this area and therefore I have always emphasized emotional management.

When negative emotions arise, I try my best to give myself positive suggestions, allowing myself to keep a calm state of mind, this is exceptionally important. Everybody should also know about the different forms of relapses, I have written a season about it. By familiarizing oneself with different forms of relapses one can avoid relapsing under a particular circumstance. Actually, the issue of nocturnal emissions works in the same way. One should understand dozens of emission inducing factors, after that can relapses be better avoided.

## Premature ejaculation {-}

Below let’s talk about the issue of premature ejaculation.

Premature ejaculation is an issue that many brothers pay attention to. We will talk more about it more in this season. First, let’s take a look at 2 cases:

### Case analysis {-}

**Case 1:**  Previously I had the habit of masturbation, I’ve had it for several years. Right now, I ejaculate within a minute of making love. Sometimes ejaculation happens upon contact.

**Case 2:**  I have prostatitis, the main symptom is difficulty in urinating. Previously, I have also had scrotum dampness, other symptoms are quite mild. Most importantly is premature ejaculation. I feel like I’ve had it since around 20 years old. I’m 28 this year, already married. Prior to marriage I had undergone foreskin surgery. I had the habit of masturbating. My love sessions are very short. I cannot last more than 1-2 minutes. My premature ejaculation is quite serious. I’m unable to control it.

### The classification of premature ejaculation severity {-}

Mild premature ejaculation: 1-3 minutes  
Medium premature ejaculation: less than 1 minute  
Severe premature ejaculation: ejaculation before penetration

### Cause explanation by TCM {-}

Male premature ejaculation, the emergence of impotence is mostly caused by sexual indulgences or mistaken masturbation during youth, leading to a decline of fire from the gate of life and weakened essence. If the thoughts are depressed, the heart and the lungs will be damaged. If the kidneys are damaged due to fright, this also causes damp-heat to flow down to the urinary bladder, resulting in a slackened penis in atrophy. But the main reason of the atrophy is due to kidney yang weakness. The yang in the kidneys is the source to the yang qi of the whole body. It takes shape in warmth, evaporates and transforms fluid, promotes the development and the function of the sexual organ. Kidney yang deficiency leads to the loss of function in keeping warm and in the transformation of qi in the body.

Due to the above, the fear of cold and cold limbs arises as well as the decline of sexual function. Therefore, a man will suffer from impotence and will be unable to get erect or keep firm, further accompanied with a headache, dizziness, sore waist and legs, heart palpitations, insomnia, pale complexion, lack of/depressed vigor and lacking in vitality.

### The danger of premature ejaculation {-}

**Heavy psychological burden:**  after one has premature ejaculation, the male unavoidably takes on an overload of psychological pressure. Simultaneously, one is constantly veiled under the shadow of the disease, work and life are greatly affected.

**Causing a rupture in the relationship between the married couple:**  premature ejaculation doesn’t allow for a normal sex life and causes rupture of emotions. According to incomplete statistics, divorces and breakups due to male premature ejaculation take up a large portion of the total number.

**Disadvantageous to male fertility:**  commonly seen symptom of premature ejaculation is a short erection duration, barely able to finish in bed. The body of the sufferer is in a state of poor health with poor sperm quality and is not able to guarantee healthy offspring.

### Masturbation will damage sexual function {-}

There are many reported symptoms of damaged sexual function due to masturbation such as premature ejaculation, soft erection, short duration erection and impotence as the main examples. When enough damage has been sustained because of masturbation, the evil fruits of this act will naturally become apparent.

### Premature ejaculation inducing factors {-}

Premature ejaculation inducing factors can be grouped into organic  _(mainly caused by prostatitis and similar diseases)_  and non-organic  _(psychological, habitual, too long foreskin and similar reasons leading towards too rapid ejaculation)_. To cure premature ejaculation one may seek out a TCM doctor and then persist in rebooting and health cultivation and active exercises. The issue of premature ejaculation will in this way slowly alleviate itself.

### Dorsal nerve severance treatment {-}

Dorsal nerve severance operation is renowned in the premature ejaculation sphere. Almost everybody who is troubled by premature ejaculation knows about this procedure. There are actually many dangers with this procedure.

**Feedback 1:**  I have undergone dorsal nerve severance operation but still I can only last for a short time, what’s the matter? I’m 24, previously my body was in an excellent condition. I did my operation in Chi Feng Xie He hospital.

**Feedback 2:**  After I did dorsal nerve severance operation, I was not able to achieve an erection, nor do I have morning erection. Is it because they have cut too much? What do I do if it is all cut out?

**Feedback 3:**  Because of masturbation, I have premature ejaculation. A while ago, I did dorsal nerve severance operation in Zheng Gui hospital. Why is it that I still have premature ejaculation? I still have the symptoms, how can I become completely healed? Do I need another operation?

**Feedback 4:**  Hope that you can provide me with some guidance during your busy schedule. My situation is as follows: due to illness in 2012, I randomly sought out doctors. I was tricked into doing the dorsal nerve severance operation by the main doctor of the urological department. Today is the 19th day since the operation. Lately, I have always had the urge to get an erection but I was unable to achieve it. Right now I’m very worried and I don’t know if this situation is normal. What should I do? Prior to the operation, my erection functioned very well. At the slightest stimulation, I was able to have an erection. If the operation has led to impotence, is this curable?

**Feedback 5:**  Now that I have undergone dorsal nerve severance operation, why is it that I still have premature ejaculation? I discovered the symptoms of premature ejaculation 2 years ago. I have since tried to cure it without avail. At the hospital, it was determined that my glans was too sensitive. There was inflammation in my prostatitis and also in the mycoplasma.

Some hospital even promise that the operation will completely cure premature ejaculation, but the reality is not like this. I have found a problem and that is many doctors like to discuss things in terms of sensitivity. They want you to have an operation, they want you to go through different diagnosis. This kind of situation occurs quite a lot in male hospitals.

Behind the scenes, there are personal interests at play. Of course, I have also seen doctors with consciences saying that using dorsal nerve severance operation to cure premature ejaculation is wrong. This is because should the procedure fail, treating premature ejaculation in the future will be more difficult and even has a chance of inducing impotence. I believe these doctors for sure have received vast amounts of kickback related to the surgical patient. This results in many people going through different operations without any effects. This is the hard truth! Therefore, if there are brothers considering this operation, consider it with care at all cost!

### The relationship between sensitivity and kidney deficiency {-}

The degree of glans sensitivity is actually related to kidney deficiency. When masturbation has damaged the essences to a certain degree, the glans will become very sensitive. Many brothers have reported that in the beginning they were able to masturbate just fine. Later on, they became more sensitive with the session becoming shorter and shorter.

### Premature ejaculation in masturbation versus love making {-}

Some brothers ask if they have premature ejaculation during masturbation, will it also happen to me during lovemaking. Many experienced people have said that premature ejaculation during masturbation is not a problem. During love making this would no longer occur. With regards to the issue, the answer should be: it is not certain.

Some people have premature ejaculation during masturbation but it is more severe when they make love. Because one tends to get nervous or is already accustomed to premature ejaculation, this would make it possible to prematurely ejaculate every time during lovemaking. Although some people have the inclination to prematurely ejaculate during masturbation, this is not necessarily the real form of premature ejaculation. Because some people like stimulation during masturbation, they prefer to get it done with quickly. Their constitution is still good and have not sustained enough damage to warrant true premature ejaculation.

Therefore the correct answer is: it is not certain! Because people are different, one needs to look at the degree of essence damage.

### Misconception 1: taking supplements and using spray medicine {-}

Impotence and premature ejaculation are actually self-preserving signals of the body. If one relies on taking medicines in order to indulge sexually, then the body will become progressively worse, the body will truly collapse. When the time arrives, even taking supplements will have no effect. Brothers who have taken supplemental medicines will know that in the beginning, the effect is quite good. Upon increasing the dosage there will be no effect, abusing yang strengthening medicine is not desirable. In addition, some brothers like to use spray medicine to delay the time. This will make the penis numb and prolong the time, this very much drains the body. Indulging like this will leave great hidden damage to the health.

### Misconception 2: use the second time to prolong the time {-}

Some brothers like to first masturbate for a release, this will then prolong the time for the second time. A certain prolonging effect can be obtained this way but consecutively ejaculating for 2 times seriously damages the body. The chance of running into symptoms will be very high, this is not desirable.

### Rebooting is the foundation for curing premature ejaculation {-}

The recovery from premature ejaculation is a slow process. One cannot expect to get better by taking a few medicines. If you do not know how to reboot and cultivate kidney qi, then premature ejaculation will cause huge troubles for you. By wasting yourself before marriage, future relationship with the wife will be affected. One’s self-confidence will also be severely affected. Therefore, we must persist in ridding ourselves from the evil habit of masturbation, properly cultivate until the body is fully well. Avoid at all costs, leaking while simultaneously taking supplemental medicine, one can never get well that way.

### Premature ejaculation recovery {-}

-   Get rid of smoking and alcohol to the greatest extent, avoid spicy stimulants.
    
-   Moderation in diet, rhythmic resting schedules, pay attention to emotional management.
    
-   Active treatment may induce various illnesses that are related to premature ejaculation such as prostatitis, ..etc.
    
-   Eat lots of fruits and vegetables, do lots of aerobic exercises, do not stay up during the night and sit for a long duration at a time.
    
-   Moderate strength exercises may promote the recovery of premature ejaculation.
    
-   Choose a method of health cultivates that suits oneself such as standing qigong, Eight Brocade qigong, ..etc.
    
-   No leakage as the supplement, conquer masturbation and sexual fantasizing, strictly control the frequency of nocturnal emissions.
    

### Premature ejaculation recovery time {-}

Many people have a long history of damaging their essence and thus to recover from premature ejaculation will be very slow. Normally, the recovery time will take at least half a year given that one is rebooting and health cultivating. Severe cases will require over a year of time. According to the experiences of the veteran brothers in the forums, they all say that it takes at least a year to recover. One needs to do well in rebooting, health cultivation, active treatment and exercises in order to recover optimally.

### Conclusion {-}

There is a term called  _“financial management”_, there is a type of role called  _“financial management consultant”_. Actually the kidney essences in our body will also require management. You will need to study the way to cultivate the health and rebooting knowledge and become your own  _“essence management consultant”_. One must completely get rid of the evil habit of masturbation, properly manage one’s kidney essence. Kidney essence is the body’s great energy, one must properly care for it. We should save the best of us for after marriage. One must by all means not be blind, ignorant, impulsive, overdraft our essence like crazy before getting married, becoming wasted after marriage. It is mutually embarrassing when premature ejaculation occurs. Some women will even cheat on you, affecting the harmony of the family.

## Book recommendation {-}

In this season I will continue to recommend 5 books:

[宽心], written by Master Hsing Yun. In seclusion from the society, one ought to have the correct mindset. In living within the society, one ought to act correctly. Master Hsing Yun uses the essential Buddhist teachings as the foundation. He expounds upon worldly and societal matters and people, namely on life outlook, wealth outlook, love and marriage, household education, interpersonal relationships and success motivation. Hsing Yun pierces through troubles and points towards the happiness in the unrestrained life of introspection, cleansing like the clear morning dew, able to see the world accurately, allowing beautiful kindness into people’s hearts. This book has been recommended to me by a brother. After reading it I also liked it very much, there is also an audio version available online. A very good book with lots of inspiration.

[Inner Canon of the Yellow Emperor], many brothers should be familiar with this book. This equivalent to the Bible in the field of TCM, it is a work that cannot be studied enough during a lifetime. The damaging effects on the body from the indulgence in sexual debauchery and premature aging due to indulgence is mentioned in the first chapter of the Inner Canon of the Yellow Emperor. I have discovered that every TCM book mentions cases on the damaging effects of indulgences in sexual debauchery. Ancestors will not trick their own offspring. In studying the experiences from our predecessors can we see more clearly and reboot better.

[临证指南医案], written by the famous doctor 叶天士. I like this book very much. The doctor 叶天士 is also very legendary and has a special character. I have seen movies about him, his medical cases are worth a look. In addition, his [秘本种子金丹] is also very good, everyone may have a look. Those brothers who have gone through sperm diagnosis should know the concept of grade A sperm. We must learn to cultivate the sperm, allowing the quality of our sperm to maintain at a high level. The standard of prenatal and postnatal care may be reached in this way.

[彻底把经络穴位说清楚], written by 萧言生. In the aspect of meridian and acupoint cultivation, this book has great benefits to impart. I have read this book relatively early. Until today I still browse in it often, I like it very much. Benefiting from educating, reviewing the old in order to learn the new.

[王鸿谟自诊祛病法], complexion diagnosis in TCM is profound without end. If you observe carefully, the facial complexion of a person is constantly undergoing subtle changes, the face is the mirror of the five viscera. These subtle changes reflect changes in your internal organs. Following masturbation, the face easily becomes dull and without luster, oil easily breaks out. Lots of information is reflected by the face. I recommend everybody research this book.

This book is the popular version of the first method  _“complexion observation”_  in the four diagnostic methods in TCM. The diagnostic method of complexion observation has died out long ago and is on the verge of extinction. 王鸿谟 has over 40 years of experience in systematic exploring and clinical practice, rebuilding and reaching towards perfection. He has invented the 3 levels of complexion determination in order to accurate self-diagnose symptoms for the entire body.

TCM has created four different methods of observing illnesses which are looking, listening, asking and feeling the pulse. Looking uses the eyes to look, listening uses the ears to listen, asking uses the mouth to ask, feeling the pulse uses the fingers to feel. In combination they are called looking, listening, asking and feeling the pulse. The method that is praised the most amongst the 4 methods is “looking”. Therefore, the 4 diagnostic methods have been appraised in the very early TCM book [难经] where it is said  _“looking and thereby understanding the cause of the illness, one is a divine doctor”_, knowing by simply looking is the highest level of TCM diagnosis.
