# The recovery pattern, medical fees, guide for recovery from chronic prostatitis

## Foreword {-}

### Avoid alcohol {-}

The formula for rebooting success = higher awareness + strong vigilance. I hope that everyone is persistent in studying rebooting articles in addition to raising vigilance. Try to avoid alcohol at all costs for alcohol invites lust. After drinking, the level of determination will be non-existent which easily leads to relapses. In TCM, it is mentioned that sexual debauchery combined with alcohol consumption greatly damages the body. Therefore, avoid alcohol at all costs.

Many brothers have relapsed due to drinking alcohol. I will again emphasize it here in order to capture everybody’s attention. In addition, one also needs to raise vigilance after taking traditional Chinese medicine. This is because many medicines have the property of inducing desire which leads to relapses.

### Types of people in rebooting {-}

I have discovered a pattern when reading through cases as of late. Many brothers are not seriously damaged and therefore they are not rebooting firmly enough. Small crisis in the body induces small efforts of restraint, big crisis induces big efforts of restraint. Many brothers’ determination is not big enough. This is actually intricately connected with their experience of symptoms. A brother whose essences are seriously damaged will have an easier time of being greatly determined to reboot because he knows that if he does not reboot he is finished. Many symptoms that are induced by masturbation cannot be treated in hospitals. Only by being persistent in rebooting is there any hope of making a true recovery.

A brother who has sustained heavy damage has an easier time of entering the state of quietude in order to study rebooting articles. Because he has deep experiences before studying rebooting articles, his level of comprehension will be greater.

In addition, brothers who have sustained heavy damage regard rebooting articles as a _“life-saving straw”_. Therefore, they are in a better position compared to regular brothers.

In contrast, many brothers have not sustained a heavy injury, they have not experienced many symptoms and have never really become afraid following masturbation. They are only seeking a balance between relapses and masturbation and so are not ruthless in rebooting. These brothers are like frogs in the boiling pot, swimming comfortably in the lukewarm waters. What awaits them is nothing but calamity, only that they have not realized that symptoms are waiting not far away. As long as they indulge, they will approach that critical point of symptom eruption. Once past that critical point, the symptoms will come out to harass them.

If this person has a certain level of awareness and good karma, he will surely awaken immediately, just like the frog who has been awakened by the hot water. When the water is still lukewarm, explaining the harmful effects is like casting pearls before the swine. The ignorant person does not fear, he will not retrace his steps until he has hit the wall. This is perhaps the weakness of human nature.

I frequent the rebooting forums, indeed I have seen many cases of  _“sudden awakening”_. One could say that they appear once every couple of days, sometimes they appear daily. In a nutshell, one can say that they have become afraid to masturbate. Upon continuing indulgence and after passing that critical point, all symptoms will come out, frightening one to death, life will be under deep distress. Only then will they be determined to reboot because they have realized that if they do not stop now they will be finished. He has already been pushed to the edge of the cliff by the symptoms, if he does not stop now he will reach self-destruction.

People who are truly wise will realize the danger of masturbation through ceaseless studying. They are not forced to the realization by the emergence of symptoms. However, wise people are always few in number. I admit that I was not wise when I started to reboot. Only after becoming miserable by the symptoms did I become greatly determined to reboot. The saying goes to learn from one’s mistakes. Wise people will be able to learn from other people’s mistakes. Therefore, I advocate reading more cases, by looking at more cases will one foresee the consequences from self-indulgence, from there one is in a better position to alert oneself.

In rebooting, there are 3 types of people:

-   Determined to reboot before the appearance of symptoms: people of high realization.
    
-   Start to reboot once symptoms start to appear: people of medium realization.
    
-   Still not awake even though symptoms have already appeared: people of low realization.
    

In terms of rebooting, we should all be people of high realization, be a wise person. We should foresee the serious symptoms before they appear, seeking luck and avoiding calamity in the process.

If a wise person tells you that you will have neurosis if you masturbate 10 more times, would you still dare masturbate? Look at more cases and you will become your own wise person.

### Case studies {-}

Below I share 2 cases:

#### Case 1 {-}

> Teacher, during the past weeks, I suddenly wake up in the middle of the night. I’m totally helpless, I would like to ask what is wrong. Previously, this has never happened to me. I lean towards a vegetarian diet and prioritize slow jog as exercise. I go to bed at around 11. Before I do so I drink some milk and eat some bread and biscuits. What has gone wrong?

**Answer:**

There are many reasons which contribute to sleeping problems. I would advise you to sleep earlier during the evening. Try to avoid sweating a lot when you are jogging, he who sweats loses essence. Too much sweating injures the body and will also affect the quality of sleep. Of course, when these kinds of problem appear, it is also related to the season. I advise you to cultivate quietness during the evening. You may do health cultivation qigong. Keep on fighting!

**Analysis:**

Health cultivation advocates  _“no leaking through the skin”_  during the winter season. Avoid excessive sweating, minor sweating is fine for young people. Many brothers have not realized the importance of sweating. They know that exercise is beneficial to the recovery of the body and so they exercise and sweat a lot everyday. In doing so, the body will also gradually weaken. It is also not advised to sweat a lot by soaking the feet in hot water everyday. TCM talks about the slowing of decay through movement and the raising of yang through movement, but specifically, on how to move and how much to move. There are things to be particular about in these topics.

The saying goes that too much is as bad as not enough. If too much exercise is at hand, the body will also become negatively affected. The specific intensity of the exercise may be adjusted based upon the reaction of the body. The intensity is not fixed and may be adjusted according to one’s own physical reactions. If you feel very tired after exercising and the body does not recover well, it means that the intensity is a bit high. If the next day you feel the Spirit to be very good, then the intensity is about right. The intensity may be adjusted at any time according to one’s own physical reactions. Slowly, through trial and error, you will gradually get to know how much exercise is suitable for yourself and what is most suitable to one’s health.

Since ancient times, medicines have been passed on but not the level of intensity. Few people are aware of the intensity, it can only be known through many experiments by oneself. Let us become sensitive exercisers and not blind ones.

#### Case 2 {-}

> Hello, I’m 31 years old, I have been masturbating for over a decade. Although married, I continue to masturbate. Previously, I suffered from poor memory, poor concentration, very oily head and hair, easily fatigued, hesitation in doing things, hunchback, easily anxious, engaging in fantasies, premature ejaculation, serious sexual fantization.
> 
> But I was not aware of the danger from masturbation, I have even purchased sex. A month ago, I started to get a severe headache, tinnitus and a feeling of disgust. This was followed by dryness in the eyes, discomfort in the throat, heavy chest with shortness of breath, pain in the hands and the feet. I even quit my job. These symptoms are more pronounced during the evenings. Afterwards, the symptoms became better. I found a TCM doctor for treatment. Now I’m eating reasonably, I jog daily in the morning. In the evenings, I take a walk. I take TCM medicine and eat fruits, my diet is also quite light!
> 
> But in recent days, my stomach is not firm with the presence of light pain. Sometimes to the left side and sometimes to the right side. Sometimes at the navel, all in the same general vicinity. Everyday, the pain occurs several times and then disappears on its own. Not sure what causes this. How long will it take for my body to recover? How should I live my sex life? I’m married after all! Thanks!

**Answer:**

Yes, one can consider that your symptoms are showing signs of neurosis, autonomic disorders can also be considered. Masturbation will injure the nerves, you may take a look at season 30, it talks about neurosis. The pain that you are experiencing is moving pain, I have also experienced this. Normally, it will take over a year of rebooting and health cultivation to recover from neurosis. I recommend you to properly repent and then vow to reboot. Otherwise, it will be very difficult to recover from the symptoms. Taking TCM medicine alone is not sufficient.

Now that you have been injured to such a degree, I recommend you to talk it over with your wife and then begin to reboot and cultivate the health. Cultivate the health until you are completely well and then live out a moderate sex life. Otherwise, going after quick pleasure will lead to suffering. Because many brothers are not aware of rebooting and health cultivation, their neurosis does not recover after 5 years or even a decade or more. Keep on fighting!

**Analysis:**

This is a typical case. When neurosis appears, it is basically like being tormented by ghosts. Many people become fearful and develop hypochondria, the personality will also undergo big changes. People in the surrounding will have a hard time understanding your feelings, only fellow patients may understand. You can imagine, a dozen or several dozen symptoms takings turns tormenting you, that feeling is not humane. Neurosis is a dividing range for those suffering from essence damage. It is very destructive towards the body and the mind. Many neurosis sufferers opt for suicide. Many patients use the following words to describe neurosis  _“death is preferable to living”_. Only those people with deep experiences will understand that kind of feeling. Death is indeed preferable to living, it is symptom hell.

This week, I have seen 5 brothers who have encountered neurosis due to masturbation. I think there are more people since that I do not read every post. Among the illnesses that are induced by masturbation, neurosis is one of the more serious ones. Brothers who have not had neurosis should get to know this disease. They should remind themselves from time to time that if you continue to indulge yourself, one day you will end up suffering like this person. It is critical to alert oneself through the lessons of other people. One should learn lessons from the mistakes of one’s predecessors. To wait until the emergence of symptoms is great suffering. It is a very slow recovery from neurosis.

We will enter into the main topic below.

In this season we will talk about the recovery pattern, medical fees and guide for recovery from chronic prostatitis in detail, the specifics can be found below:

## Recovery pattern {-}

If you want to recover better, you should know about the recovery pattern. In the recovery process of the body, there will emerge symptoms of withdrawal, repeated symptoms and other forms of issues. You should know these through experiences and studies.  _(Translator’s note: recall that repeated symptoms are a repeat of earlier symptoms that one had previously encountered as a result of masturbation. This is different from withdrawal symptoms which only occur when one has stopped PMO)_. Otherwise, many brothers will relapse as soon as repeated symptoms show up. This is because they are still relatively ignorant, they are unsure of themselves when it comes to issues that show up during reboot. Once in panic and in doubt, it is immediately followed by relapse.

Recovery pattern:

Starts to reboot -> withdrawal symptoms  _(appear within a month)_  -> period for repeated symptoms  _(appear after a few months of rebooting)_  -> persists in rebooting and health cultivation  _(including active treatment)_  -> reduced frequency in repeated symptoms -> approaching recovery -> recovery.

I have specifically talked about withdrawal symptoms in my previous article. The emergence of withdrawal symptoms may cause rookies to doubt. But as long as they are given the reasons behind them, they will regain their confidence and properly reboot. Rebooting veterans should therefore let the rookies know about withdrawal reactions and eliminate their doubt.

Repeating symptoms, on the other hand, have been experienced by nearly every brother in their recovery process. It can be said that repeated symptoms cannot be avoided in the path towards recovery, especially for brothers with a long history of damaging their essences. With a history of damaging the essences for many years, to achieve complete recovery within a few months of time is not realistic. The emergence of repeated symptoms during rebooting is also very normal. This happens for instance after staying up late during the night, sitting down for long periods of time, after being fatigued, after being angry, over-exercising, not paying attention to the diet, following nocturnal emission, seasonal factors, ..etc, all of the mentioned may induce repeated symptoms.

When these symptoms appear, do not be worried. Take care to rest and cultivate for a few days and they will normally pass. I very much emphasize health cultivation, the more properly the health is cultivated the less chance there is of encountering repeated symptoms. Slowly, you will realize that your health is becoming ever better. Repeated symptoms become ever fewer, you are nearing recovery in this way. Keep reinforcing the results in recovery and you will be able to completely heal. Of course, once healed you may not become careless, one must still persist in health cultivation. The human body will need frequent maintenance, otherwise, it will depreciate very rapidly.

Many brothers are very troubled by repeated symptoms. What we need to do is to summarize the causes. Why do repeated symptoms occur? One must find the cause and take care to avoid it in the future. This is actually a process of repeated trials. Constantly making mistakes, constantly summarizing, constantly avoiding mistakes, constantly improving in this manner and greatly reducing the chance of encountering repeated symptoms. Do fewer things which reduce the health and do more of those things which boost it. Do more health cultivating things and less health-damaging things. Slowly, the state of health will become stabilized, the occurrence of repeated symptoms will naturally decrease by a lot.

Knowing the pattern for recovery, one will then not panic in the recovery process. Especially when symptoms repeat themselves, many brothers go into disarray which is followed by relapse. Correctly recognizing the pattern of recovery, correctly recognizing withdrawal symptoms and the period for repeated symptoms, properly reboot and cultivate the health, avoid factors that would induce repeated symptoms. Slowly, the state of the health will become ever more stable, the emergence of repeated symptoms will become ever less.

Those brothers who do not understand health cultivation share 2 characteristics in the recovery process:

-   The rate of recovery is very slow. The recovery fails to meet expectations after more than a year of rebooting.
-   The chances of encountering repeated symptoms is high. Symptoms always come back, this makes us lose a lot of confidence.

I advise our numerous brothers to make sure to put in enough effort in health cultivation. When the awareness for cultivation is raised, recovery will naturally be guaranteed, the number of repeated symptom recurrences will also greatly decrease.

Another sentence that I would like to share with everybody is this:  **during rebooting, do not break the reboot no matter what happens!**  I have told brother 小龙, during the rebooting process we will run into all kinds of problems. They will make us doubt, but no matter what, do not break the reboot! When doubts arise, it is only that we have not figured something out temporarily. Having a person of understanding to help us rid the doubt will enable our confidence to rise once again.

## Medical expenses {-}

Below we will talk about medical expenses.

When symptoms appear, it is all about money. Masturbation leads directly to the hospital, rebooting is to save medical expenses.

I will first share 15 cases with everybody:

**Case 1:**  I’m 21 this year and in my 4th year of university. Currently, I’m battling with my postgraduate exam which is due in less than 90 days. In the past 2 months, I have become weak and am ridden with illnesses. I’m severely kidney deficient, hair is falling out, all sorts of chronic illnesses, chronic gastritis and cervical spondylosis, all have come to knock on the door. Every month, my medical bill costs are over a thousand RMB. I’m suffering from the abuse of illness pains everyday. After determining to reboot I relapse again and again, my mind is extremely dark and depressed…

**Case 2:**  I asked the doctor how much longer I will need to take medication, he said another 2-3 weeks! This week my medical fees have risen to 700 RMB! Out of that, 160 is registering fees and the rest is in medicines, really expensive!

**Case 3:**  Look for yourselves whether or not taking medicine make the body worse off. Medicines have side effects, doing different check-ups wounds the body. Doctors nowadays often lack morality, medical fees are expensive. I have spent at least 30,000 RMB on medical fees but the effect is less than from reading a few pages of articles from Soaring Eagle.

**Case 4:**  I have gotten a month worth of medicine for 1,000 RMB, it is truly using the money to buy lessons. The consequences of masturbation are to enter the hospital. When essence is depleted, people are no more. These are not some painless moans from bored people. Too much masturbation will induce mental illnesses! Insomnia, depression, anxiety, all sorts of symptoms and ending in schizophrenia! So far, my medical expenses in treating insomnia, including loss of working time are already over 20,000 RMB!

A youth of only 22 years, going to the mental hospital in order to fetch medicine, without even a girlfriend! It really is a huge sadness! I have nearly died due to insomnia depression! I hope that this great ordeal of an illness will alert myself and change my life! Control destiny with one’s own hands! Keep on fighting! One way is death! The other way is to cut out masturbation! Let oneself choose wisely!

**Case 5:**  All in all, I have spent 10,000 RMB in medical fees. I have taken Chinese traditional medicine for half a year. All in all, I have gone through 2 TCM clinics and have seen 4-5 TCM doctors, old TCM experts charge 100 RMB per visit. The doctor felt my pulse and right away said I had kidney deficiency, qi deficiency, spleen deficit and a whole bunch of deficiencies. The doctor warned me that I must go to bed at 10 pm. However, I did not improve all this time, although I now have timely meals, my weight has gone up almost 10 kilos. But my body is not able to recover to its normal state, I feel very helpless. I don’t know when I will get well. I’m almost at the age where I should be considering marriage. My body is still in such a bad state. To be honest, I have let my parents down.

**Case 6:**  First of all, my memory has markedly deteriorated. If things were like they were before, all it took is one glance or to hear once before I could remember everything. But now things need to be repeated several times for even a small chance for me to remember it. Another thing is that frequent masturbation will increase the chances of catching chronic prostatitis! This is the thread owner’s own experience… It is because the inability of the thread owner to withstand temptations that he frequently masturbated. And so one day when he was doing a check-up at the hospital, they diagnosed him with prostatitis! And so he had to spend over 10,000 RMB in treatment fees.

**Case 7:**  I masturbated for 10 years when I got married. You can say that my married life was harmonious. Only that there was a slight problem of premature ejaculation and sore waist following ejaculation, but the conditions were not serious, although there was no change as to their frequency. Following the widespread use of computers and the internet nowadays, it is easy to be tempted by pictures and videos and so I frequently sexually fantasize. I masturbate once every 10 days. After having masturbated for 13 years, I wanted to have a child. When I checked myself at the hospital it was discovered that the vitality of my sperm was low. After having spent nearly 2 years in TCM treatment and 20 000 RMB, I had a healthy and lively daughter at last.

**Case 8:**  After having masturbated for 5 months, I started to get breakouts on my face. After the 6th month the breakouts were all over my face, on my chest, on my back, and on my forearms. Moreover, I employed all forms of treatments. All in all, I have spent over 20 000 RMB in treatment fees.

**Case 9:**  Reboot early, get well early, reboot late, difficult to recover, poor life with many diseases and early demise! Since a few years old, I was affected by pornographic movies and learned to masturbate. But at the time, I did not masturbate frequently. When I entered puberty, I started to use computers and started to masturbate frequently. Nowadays, I have hair loss, easily sweat, have cold limbs and I’m very afraid of cold! My concentration is poor, my kidney deficiency is severe! I have prostatitis, inflammation in the throat, lungs and stomach, frequent urination, delayed urination, insomnia and depression. I have even thought about suicide.

When I turned 19, I determined to reboot. During these periods, I have spent 20,000 RMB in treating prostatitis. Whenever it is autumn and winter my hands and feet turn ice cold, masturbation lethally harms! Both my dad and my granddad are warm all over their bodies except for me. I’m not even on par with an elderly person. How can the eager me endure such difficulty?

**Case 10:**  My history of masturbation stretches back 10 years, I even masturbated up to 5 times a day. I have had 7 years of frequent urination, urgent urination, incomplete urination. I urinate 3-5 times during the night. I’m only 23 years old, I have never undergone apparatus inspection, only having had my pulse checked. Now it has been diagnosed at the 民营 hospital in Chongqing that I had chronic bacterial prostatitis. I have done the form of operation where they stick a tube into the penis several times. Each time it costs 2400 RMB for a total of 5 times in addition to taking some medicine. I have spent 15,000 RMB without much effect.

**Case 11:**  Is premature ejaculation easy to treat? Is prostatitis not easily treatable? I have spent 20,000 - 30,000 RMB without getting well. There is no cure right now.

**Case 12:**  I have prostatitis since 3 years. At the time I went to 仁济 for treatment. I spent almost 10,000 RMB from doing prostate ablation in addition to red light therapy. I underwent over 10 days of intravenous drip. This was repeated time and time again, I was never cured of the root. Lately, I had lower abdominal pains. I went to the hospital for a color ultrasound, the result was that I had chronic prostatitis.

**Case 13:**  Which male hospitals are good at Chaozhou? I have spent over 10,000 RMB in treating prostatitis at 人民 hospital. It has been a month and I’m still not well. Getting emotional here!

**Case 14:**  My chronic prostatitis was induced by masturbation. 2 years ago, I almost recovered after spending 20,000 RMB at the male hospital in treatment fees. Now it has relapsed! If I only rely on inflammatory drugs and Chinese medicine, will I get well? Im only 22, unmarried. Yesterday, I went to the male hospital and the doctor again told me that it was very serious. He said something about white blood cells with 3 + and a lack of lecithin.

**Case 15:**  I have had prostatitis for quite a few years now. I have been to Xian, Beijing and many hospitals and have spent over 100 000 RMB! But nothing could cure me, I want to try Shanghai. Not sure if there are any good foreign-invested hospitals over there?

There is a very classical statement when it comes to treating chronic prostatitis: the money is gone but the illness remains. This is simply too big of an insult. Doctors nowadays only cure the body but not the mind. Good doctors should let the patient become aware of the dangers of masturbation. Or else by letting you take medicine and become better temporarily, the illness relapses after masturbation. In this way, the hospital is making money but it is too painful from the perspective of the patient.

In addition, I recommend not to visit male hospitals. Prostatitis is their main source of income. Once you enter, you might be diagnosed with an illness despite being healthy. Minor illnesses might be exaggerated into something very serious. The way that male hospitals make income is to first scare the patient. Once you are scared then it easy to extract the money. A whole bunch of diagnosis fees and treatment fees.

One thing worth mentioning is all the new types of treatment devices. They have all sorts of names and they are all high tech. One treatment costs several thousands of RMB, squeezing money out of the patient. Several thousand is a small sum, normally they will squeeze for over 10,000 RMB. It’s a pity that many patients don’t know what has happened to their bodies, nor do they know what is causing prostatitis. They are purely lambs to the slaughter. I recommend prostatitis patients to turn to the big standard hospitals if they want treatment. Otherwise, the money is being spent in vain. Remember at all costs!

After reading the cases, everybody should know that masturbation induces many forms of illnesses. Money does not have to be spent on prostatitis alone. After masturbation, immune system decreases. Symptoms may appear with digestive, respiratory and nervous systems. Even if you go to the big standard hospitals, treatment fees will be substantial. Several thousand to tens of thousands RMB is very common. Rubbing the penis is not for free. One will know after having visited the hospital, what is being rubbed is not the penis but medical bills.

The latter of the 15 cases are about prostatitis, this should be apparent. These patients are still in a state of ignorance. They have no idea of what’s going on. Only that they should go to the hospital for treatment but they are not aware of the root of the issue. In reality, prostatitis cannot be treated. It will only temporarily heal, prostatitis can only be healed through cultivation. When the symptoms emerge, one must learn how to reboot and cultivate the health. Rebooting and health cultivation is the foundation of complete recovery, or else it is like building a house on sand, there is no foundation whatsoever, it will collapse at any time. Sadly, many prostatitis patients are not aware of this principle.

I have summarized an experience: to truly recover from prostatitis, one must first come to reason. Failure to understand the reason, one could expect temporary recovery at the most. If one does not pay attention to health cultivation and does not understand the importance of rebooting and essence conservation, prostatitis is very likely to relapse. The relapse rate for prostatitis is over 90%. Everyone should know the reason behind it. It is because the vast majority of the people have not come to reason whatsoever, without a shred of rebooting and health cultivation awareness.

Quite a few brothers have reported the outbreak of symptoms following masturbation and the inability to save money, opening up the money flow like opening a tap. Ordinary brothers spend at least several hundred to several thousand in treatment fees, some spend over ten thousand. I have also seen quite a few cases of spending over a hundred thousand. Especially for neurosis patients, it is very common for medical bills to end up in the tens of thousands. For some brothers, diagnosis fees alone are in the tens of thousands, not including registering fees and medical fees.

The money has already been spent, it is fine if the illness has been cured. But the reality is that after spending the money and taking the medicine, recovery is not guaranteed. Why is that? Because one is still indulging, still masturbating, still leaking, not paying attention to health cultivation. The efficiency of treatment via medicine is vastly discounted. The efficiency can in no way be guaranteed. Unfortunately, many brothers still don’t understand this principle. Their way of thinking is to seek the doctor when there is illness followed by medication and recovery. They have placed all hope on the doctor, relying on medicine for everything, relying on the doctor for everything, this way of thinking is completely wrong.

Without rebooting and health cultivation awareness, it is very difficult for symptoms to truly go away, the chance of relapses will be very high. Many brothers have become return guests of hospitals. They frequently visit hospitals but with all of their symptoms still intact. If one is able to come to reason, the result will not be like this. Ignorance is very scary, it will induce foolish actions. If you have come to reason, you will discover how outrageously wrong you have been.

> “People worry about the many diseases out there. Doctors worry about the few methods of treating diseases.”
> 
> — from [扁鹊仓公列传]

I think this is a very good sentence by 扁鹊. The doctor needs to understand a lot, being superb in his craft, high in medical ethics. Only this way will he bring good news to the patient. I think the  _“few methods of treating”_  is also applicable for the patient. 30% is treatment and 70% is cultivation.

Nowadays, when patients become sick, all they know is to go to the hospital for treatment. But the important part is oneself, the key is 70% cultivation. After all, many diseases are chronic and are not a mere cold. They cannot be cured by a few pills. Yet many patients are in a mental state of ignorance, knowing and understanding too little about health cultivation. If symptoms are to disappear under these circumstances it is very difficult. We should not put all our expectations on the doctor. We need to become qualified patients ourselves, a patient who understands health cultivation. God helps he who helps himself!

In health cultivation, the foremost principle is  _“treasuring essence, conserving essence”_, TCM mentions: “_when the kidney qi is abundant, a hundred illness are eliminated, when the kidney qi is deficient, a hundred illnesses acts as bullies_”. To cultivate the health, one must cultivate the kidneys. To cultivate the kidneys, one must cultivate the essence. The person who is well adapted to health cultivation must esteem conservation! It is very sad when one does not understand essence conservation! Taking in medicine on the one hand while shedding on the other hand, this is a great taboo in treating diseases.

## Guide to recovery from chronic prostatitis {-}

Lastly, let’s talk about a guide to recovery from chronic prostatitis.

Due to a request from a brother, we will again talk about recovering from prostatitis in this season.

If chronic prostatitis is serious, one needs to combine active treatment while keeping the condition under check with medicine. Do not under any circumstances expect a complete recovery from taking medicine, one may temporarily recover at the most. It has been said in the rebooting forums that Chinese herbal medicine will be able to cure prostatitis. The cure that was mentioned is only a temporary cure. If you do not understand rebooting and health cultivation, there is a high chance for relapses.

Taking medicine in treating prostatitis is very important but it is not crucial. The crucial part is  _“treating the mind”_. Let the patient come to reason, let the patient realize the importance of rebooting and health cultivation. Or else by temporarily healing him, he will still relapse. This way of healing is actually a failure as it ignores the transformation of thoughts with the patients.

### Keys to recovery {-}

Below I will expound on the keys to recovery:

**1. Exercise**

There are lots of benefits to moderate aerobic exercises. It may raise the body’s immunity, promote blood circulation in the body, it is very favorable for the alleviation of prostatitis symptoms. Brothers who have a habit of exercising will recover much more quickly compared to those brothers who stay up during the night and sit for long durations at a time. Naturally, over-exercising is not to be desired as it will induce a weakening in the body’s immunity. Therefore, one must manage the intensity of exercise. Just like cooking a meal, when the fire is too high, the food gets burned or becomes too tough, it no longer tastes good. Exercising too much will have the opposite of the intended effect.

**2. Excellent working and resting habits**

Do not over-fatigue on a regular basis. Pay attention to cultivating the Spirit. Do your best to go to bed before 11 pm. My recommended bedtime is around 10 pm.

**3. Excellent dietary habits**

Do not smoke, drink alcohol, eat spicy food. Eat lots of fruits and vegetables, keep a light diet.

**4. Avoid sitting for long durations**

Research has shown, due to occupational reasons, taxi drivers are the group with the highest rate of prostatitis. There are many harms to sitting for long durations. Therefore, try to get up and move around every 40 minutes.

**5. Avoid coming in contact with cold and catching a cold as much as possible**

Coming in contact with cold allows for the emergence of prostatitis relapse. When the body is cold, many brothers have frequent urination.

**6. Do not hold in the urine**

By doing this, it is very possible to cause an aggravation of prostatitis. Some patient experience a sudden aggravation to their prostatitis because they had previously held in the urine for a few hours while sitting in a vehicle.

**7. Mood management**

It is crucial to keep a good mental state. TCM mentions that the 7 emotions lead to illness. Adverse emotions may cause an aggravation of prostatitis symptoms.

**8. Moderate water intake**

Moderate intake of water may alleviate prostatitis symptoms. I believe that many brothers have such an experience.

**9. Health cultivation practice**

Health cultivation practices have a positive meaning for the recovery of chronic prostatitis. One may choose a suitable practice and do it regularly. Kidney strengthening exercises, standing Qigong, ..etc are all very good.

**10. Keep away from the theory of needing to discharge semen at regular intervals**

This theory has confused many people, it has also harmed many people, even many doctors advocate this theory. This shakes many peoples’ positions. In the sphere of prostatitis, this theory has received approval from many patients but I’m absolutely opposed to it. How is the semen to be discharged? Through masturbation or lovemaking. The patient already has a weakened body and yet is to still discharge semen, is this not making matters worse? Moreover, to glorify discharging poison  _(Translator’s note: discharging poison here is synonymous to discharging semen)_, this is actually an excuse for indulgence. Have you really got so much poison? If the prostate has that much poison then how are monks to survive?

According to my research, the reason why so many people think that it is not good to hold it in and expelling is comfortable is due to inadequate cultivation of the mind. If the cultivation of the mind is adequate then there will be no issue of holding it in. Holding it in is indeed not good, it easily induces inflammations, sexual fantasization alone will induce repeated symptoms with the prostate. Therefore, when rebooting, we must pay attention to mind cultivation. Otherwise, issues will easily arise due to sexual fantasization. Sexual fantasization is the invisible form of leaking. *Essence leaves when the mind wanders*. We must put a stop to the attacks from sexual fantasization.

Of course, the bacterial form of prostatitis should be actively treated and not alleviated through the discharge of semen. The temporary alleviation that you receive from discharging semen will only sink you into the vicious spiral of a evil habit. In this aspect, it is similar to taking drugs. Taking drugs temporarily offers alleviation from uncomfortable feelings, but it will only continuously hook you. At last, you are unable to extricate yourself and it will induce more serious forms of prostatitis.

Therefore, everybody should have the correct understanding when it comes to the issue of discharging semen, otherwise, the stance towards rebooting will be easily swayed. Our rebooting efforts must be firm, determined and complete! Abstinence without sexual fantasization is harmless to the body, everybody must recognize this clearly.

### Summary {-}

Properly reboot and cultivate the health today, cultivate the body until it has fully recovered, live out a moderate sex life post marriage, this is the correct path. Otherwise, by going through treatment on one side while leaking essence on the other side, at most it will only bring you temporary recovery. As long as you continue to indulge, prostatitis might relapse not long afterward. Many people say that they have been cured, this is actually false. Look at how long they have been cured. As long as they have not clearly understood the issue of discharging essence, sooner or later the disease will return. One must understand the importance of essence conservation. *Low essence precedes diseases* is true, it is not false! It is possible for prostatitis to fully recover, the prerequisite is to come to reason. One must understand the principle, there can be no error in the guiding thought!

## Book recommendations {-}

I will recommend 5 books:

[觉海慈航], the reach of this book among Buddhist books is quite broad these days. It is very good when it comes to instructing beginners. Inside there are answers to various kinds of common questions. If you have Buddhist karma and want to learn about Buddhism, I recommend this book to you.

[犹太人为什么聪明], this is a book that I've started recently reading. As everyone knows, the group of people that wins the most Nobel prizes are the Jews. The Jews are an ethnic group with an extremely strong desire for knowledge and strongly emphasize a life with belief. Their everyday actions are patterned by 613 monastic disciplinary rules. Among the rules are also strict commandments towards sex. The high IQ among Jewish people has a biological basis. TCM: *to the above, the kidneys are connected to the brain*. Brothers with a bit of common sense should know that masturbation or other forms of indulgence will lead to a great decline in brain power. If there are lots of people who indulge in an ethnic group, then the average IQ of that group will decrease.

[大道显隐：李经梧太极人生], with skills approaching the Dao, Taichi boxing is cultural boxing. It is a form of boxing with a very deep level of cultural substance. I have studied the theory of Taichi boxing and have found out that the famous Tachi boxers are all very knowledgeable in the way of health cultivation. Basically, all of them have read I Ching and the Inner Canons of the Yellow Emperor. They have basically mastered the health cultivation theories. The three energies of Chinese medicine, health cultivators call them the 3 treasures of the human body. These 3 treasures are particularly treasured among the famous Taichi boxers.

In comprehending this book, one may learn about the principles of human conduct as well as the principles of health cultivation. Of course, one may also learn about the essential theory of Taichi boxing. Then you will discover that all of this is interconnected with rebooting. It will also act as a good guide for your rebooting process.

[思考中医], authored by 刘力红. Due to the author’s passion and persistence towards TCM, he has committed himself to the interpretation and research of [伤寒杂病论] as well as to the research into hard-to-treat illnesses. In order to avoid crypticism, the author has strived to combine scholarship with interest. The scope of the book goes beyond the research of [伤寒杂病论]. It is an example of the integration between case features and academic discipline. I have read the book several times. In every read, there is something to learn. I recommend everybody to have a look, opening this book will be beneficial.

[中医火神派医案全解], 张存悌 as editor in chief, the school of Vulcan is an important school of medicine founded by the famous Sichuan doctor 郑钦安 at the end of the Qing dynasty. Vulcanism is well known for its expertise in monkshood. It possesses a very distinctive academic quality. Medical cases from 20 famous doctors are included in this book and are very much worse a read. I have read this book relatively early and have come to like to personally, brothers with an interest may take a look.
