# Reiteration of the harmful effects of masturbation

## About the forums {-}

These days the Jiese forums have been developing very fast. There are about 500 members joining everyday. We have more than fifty thousand members now  _(Now the forums have over four million members)_. It’s fantastic that we have now grown to such a huge scale. Thinking back to the beginning, there were only about five hundred users, I felt like it hasn’t been easy. We couldn’t have gotten this far without having our fellow brothers spreading awareness and our moderators working diligently. Everything we do is our responsibility. The Jiese forum is filled with positive energy, a stream of overwhelming righteousness.

On Jiese forums, you can obtain lots of knowledge in a positive rebooting environment and get lots of emotional support. Experienced brothers will tell you that breaking the reboot is not the end of the world, one must realize the importance of studying to raise one's level of awareness. Only when our level of awareness is adequate can we defeat the temptation demon. One has many things to study during the reboot, therefore it is not easy.

Many brothers tend to become prideful and conceited during the flatline period; they may think rebooting is easy. After the flatline period follows the peak relapse period, that’s when the temptation demon will rise. Many experienced members have suffered from such events. They’ve seen how regretful one can feel after breaking the reboot. Therefore, they will always tell the new members to raise awareness and don’t celebrate too early. We must maintain a high level of awareness everyday of the reboot. Otherwise, a relapse is imminent even after hundreds of days of rebooting.

### Case studies {-}

Below are two case studies:

#### Case 1 {-}

> “Big brother Soaring Eagle, my erection was fine before the reboot. After the reboot, I experienced erectile dysfunction. Now I’m scared.”

**Analysis:**

I have mentioned the problem of recurring symptoms during a previous season. New members must create the habit of studying rebooting material. Without studying one won’t be aware. Only through studying can one raise their level of awareness. Just like driving; if one doesn’t study and apply, how will one know the rules of the road and hone one’s skills behind the wheel?

Brothers will run into many problems after rebooting. I have answered several thousand questions and I must say that many brother’s problems are similar. Such as the issue of recurring symptoms, lack of erection in the morning and low sex drive. Such symptoms are common when it comes to brothers who are just starting rebooting. Such symptoms all belong to the category of recurring symptoms. Most doctors don’t understand recurring symptoms during reboot, therefore if you go to them, they will treat it as an illness and give you prescription medicine.

Stay calm when recurring symptoms occur. Pay attention to health cultivation and do the right amount of exercise. Only then can sexual functions be restored. Some brothers will get frightened when they realize they no longer have desire. Once fear arises, one will tend to panic and look for suggestive material in order to restore a strong desire! This is one way to get trapped in the vicious cycle. Many brothers lose control and relapse consecutively; self-regret soon follows.

After a relapse, one must get into the habit of analyzing the reason and learn from the loss, also write and share the experience. A more successful reboot will be insured in this way. Also, keep up with the study of rebooting materials so one can have a more thorough understanding of the problems and symptoms that will occur during rebooting. This is to keep misunderstandings to a minimum and have a solid foundation of rebooting. Otherwise, one’s belief will be unstable and therefore the chance of a relapse will increase.

Just to reiterate, rebooting is not easy, one must keep up the study of rebooting material to reboot more professionally. Rebooting blindly or using the brute force method will result in failure!

#### Case 2 {-}

> I’ve seen many cases about negative emotions causing physical symptoms in someone. In season 30, you mentioned that neurosis is not simply  _“created”_  in the mind. So am I able to recover from my mental handicaps from rebooting? Since these mental issues started to appear due to PMO, I can stop further development by rebooting, but can rebooting completely cure my mental issues? My determination is not strong. I easily relapse when I’m in a bad mood.

**Reply:**

In the past, I’ve systematically studied neurosis. I have also felt what it's like to have neurosis, therefore the chances of having neurosis just by  _“thinking”_  about it is slim. Most people who develop neurosis have an extremely weak body, bodily symptoms are aggravated after PMO, hence neurosis occurs. That is to say, neurosis patients already have a weak body, which is caused by staying up at night, sitting down for long periods of time and evil debauchery.

Traditional Chinese Medicine mentioned that one’s emotions will lead to sickness, but if one’s body is healthy, symptoms will not arise. For instance, if one’s body is perfectly healthy, major problems won’t arise if one goes into a rage. If one’s body is weak, a session of rage will give rise to problems. Relapse due to bad mood, is included in my list of different causes of breaking the reboot. We must learn to manage and control our emotions during our reboot. One cannot afford to relapse due to bad mood, otherwise it will be easy to fall back into the vicious cycle.

Wise people in history once said: *No weakness, wind and cold will be repelled*. That is to say, a strong immune system will protect one from illness. Let’s just say a group of people stand together in a blizzard, some of them will catch a cold while others remain healthy. Once the body is weakened, symptoms will be aggravated with negative stimulation. The issue of neurosis follows the same principle. Those who are healthy will not develop neurosis. Only when we continue to deplete ourselves while the kidney essence is weak, are symptoms more likely to occur. Fight on!

**Analysis:**

Neurosis is generally categorized as a mental illness, such a classification could easily lead to misunderstandings. Not only does it create misunderstanding among the masses, it also causes misunderstandings among patients. When we hear the term mental illness, we might think that the illness is only created in the our heads.

I had the exact same thoughts before I developed neurosis. After developing neurosis, I did plenty of research and talked to thousands of patients. I came to the conclusion that neurosis cannot simply be made up in the mind. Instead, our mind and body are interconnected. Those who have depleted their kidney essence will undergo changes in psychology and mood. They will tend to become irritable, lack patience, self loath, and become cowardly. *Kidneys govern fear*; when the kidney is weak people tend to become more cowardly. At the time I felt constrained, paranoid and fearful. If I didn’t realize that such conditions were the consequence of a weakened kidney, I would still be trapped in the vicious circle.

Those who believe the misconception that mental illness is only  _“created”_  in the mind will take prescription medicine their whole life. Neurosis can be cured only when we realize the truth. Therefore we must realize the importance of health cultivation. We must also realize the significance of preserving and protecting kidney essence. The phrase  _“illnesses arise from lack of essence”_  was said by the king of medicine Sun SiMiao from decades of experience.

In fact, we can see this happening when we have a weak kidney. We will tend to develop anxiety, depression, paranoia and distress. One will tend to think such emotions are created in the head, but in reality such psychological changes are caused by a lack of kidney essence. The lack of kidney essence is the root of negative changes. On the other hand, if we have an abundance of kidney essence, all evil will be repelled.

Since many brothers don’t realize the truth, they will never fully recover. Even when they temporarily recover, symptoms will come back after indulgence. Neurosis patients will have hope of recovery in about a year if they understand the importance of health cultivation and rebooting. Otherwise, taking medicine alone cannot cure neurosis. Many brothers who have experienced neurosis will know that medicine merely mitigates the symptoms. Rebooting and practising health cultivation is the foundation of recovery. Only when we continue to persevere, is there hope for complete recovery. This is comparable to the construction of a house. Only when the foundation is stable can the house can be built.

Essence, energy and spirit are the three treasures of the human body. If we don’t take care of our three treasures with health cultivation, recovery will be difficult. When your essence, energy, and spirit are fully preserved, many illness will go away themselves, mental disorders will also disappear. Just like when a thick layer of ice is not easily broken, but if you let it sit in the burning sun, it will melt by itself, it’s that simple. A thorough understanding and treatment can give us complete recovery. In contrast, a lack of understanding combined with treatment will lead to a difficult recovery.

Now that I have recovered, my anxiety, fear, constriction, and paranoia have completely disappeared. Moreover, my body is restored to a healthy state. To recap, I was able to achieve complete recovery from having a thorough understanding of the illness and walked out of the maze and found the key to recovery. I wish to share my experience to inform fellow brothers about various misconceptions in order for us to minimize detours in our journey of rebooting. I hope everyone can recover as fast as possible, and free ourselves from the pit of misery.

Going into the main article:

## The harms of masturbation {-}

Till now, I have written more than a dozen articles. In such articles, I have talked about various harms in regards to masturbation. In this season, I want to summarize them and explain them systematically. I will include many cases from sufferers so the harms can be better understood. I hope to enlighten more brothers about the harmful effects of masturbation.

There are dozens of articles out there talking about the harm of PMO, many articles have made very good points. But my article is derived from reading thousands of real cases and answering thousands of questions from sufferers of PMO addiction. This article will be extremely specific and systematic since it’s written by someone who has been through the process of rebooting with knowledge developed by a deep and thorough research on rebooting. In this article, I will also include mindsets and thoughts I gathered from my personal rebooting journey.

Generally speaking, there are two major ways someone can get hurt. The first one would be a direct trauma such as a car crash, falling, fighting and various other accidents. Another way is the *boiling the frog in the pot* method. One will be crippled before they even realize. This way of crippling can often feel somewhat comfortable. Let’s take eating sweets for instance. As kids, our parents told us to eat less candy. Now we know our teeth will erode before we realize if we eat too much candy.

But there is a difference between eating sweets and masturbation. Eating candy is not addictive while masturbation is highly addictive. Almost as if  _“once you pop, you can’t stop”_, one will be hooked right away. A brief sensation will cause us to lose control, it will cause us to get deeply attached to such a feeling. Then, we will pursue such a sensation but will never be satisfied, always wanting more.

Almost every brother has been mislead by harmlessness theories in the past. The flaw in harmlessness theories is that it disregards the highly addictive nature of masturbation. This type of addiction is not only limited to the physical act, but also becomes embedded in the mind as one becomes unable to control sexual fantasization, and fantasization is like a deranged wild horse. Many experienced brothers will know that sexual fantasization is an invisible form of leakage, which is also extremely damaging to the body.

Under such conditions, those with a weak constitution will run into problems in about 2 years, serious problems in some cases. For those with good health, symptoms won’t be too severe but if one continues to indulge, a collapse in health is eminent. Especially, after 40 the evil fruit of masturbation will seem ever so apparent. Many brothers have said  _“I’ve run into symptoms, I’ve tasted the bitterness of the evil fruit!”_. Now they realize the harm of masturbation and only then they see the truth in the harmfulness of PMO. Sadly, many brothers see the harm in masturbation, yet they still stay in the boiling water like the frog in the boiling pot. As if they are possessed and unable to see the truth. Until these people develop severe health issues, they won’t ever wake up and face the truth.

The harm in masturbation is done to both the mind and the body. It will sabotage our health and destroy the mind. As our body starts to suffer, our temperament will turn unpleasant, even to the point of developing many mental illnesses.

## Harm done to the urinary system {-}

The first system masturbation will harm is the urinary system. Frequent urination, urination urgency, slow urination, urination delay, urinary retention and many other issues. Once prostatitis develops, life will be frustrating and difficult. Many brothers who contract prostatitis often complain about things like  _“frequent urination is driving me crazy!”_. At night, frequent urination will affect the quality of sleep. Some brothers are unable to urinate in the bathroom while standing with their classmates. Such symptoms can easily cause many frustrations and headaches in our lives, but only the sufferer will know.

A lot of students are afraid to tell their parents, so they keep it to themselves. Due to frustration, they walk down the wrong path by indulging further. Soon they will feel regret and decide to reboot in order to find balance. Other people will go seek medical treatment to cure prostatitis but soon they will realize symptoms will persist if they PMO. Soon they go back to the hospital, but continue to PMO as symptoms reappear. Eventually, they feel despair since they spent all their money and yet their symptoms still persist. Why do the symptoms keep coming back?! Since they don’t understand, they will be mislead by the idea that prostatitis is lifelong.

What’s more tragic is when they choose to accept harmlessness in moderation as an excuse to indulge. Just like that some people sink deeper and deeper in the vicious cycle. In the end they are unable to pull themselves out. Therefore, misconceptions are dangerous, because wrong thoughts can easily mislead people into wrong actions. In the case above, a  _“lifelong”_  illness can be avoided by having the correct understanding. In reality, such a disease can be cured. To know that we must have the correct understanding.

All the organs that belong to the urinary system  _(such as kidneys, ureter, bladder, urethra, prostate, epididymis, vas deferens, seminal pouch, testicles and so on)_  can all run into problems and negatively affect the entire system. Many brothers develop varicocele. Other urinary system illnesses such as testicular inflammation, urethritis, kidney stones, urinary tract stones are also commonly seen. It’s frightening how devastating masturbation can be for our urinary system.

Masturbation can give us a variety of illness. One evil habit and hundreds of illness will arise. If we understand TCM, we will realize that most illnesses are closely related to kidney damage from PMO. When kidney essence and positive energy is present, all evil will be repelled. Illnesses will enter our body if the kidney essence is drained. When we add the effects of environment and other factors, illnesses will easily arise. Such illnesses will make brothers feel pain beyond explanation. What’s worse is that it will be shameful if our friends and family find out, so many brothers keep it a secret and seek help online.

Moreover, prostatitis and varicocele decrease the quality of the sperm. Many brothers have run into problems such as infertility. In previous articles, I mentioned such cases and gave various examples of the harm of PMO. If you care about your life, you must pay attention to the study of essence preservation. Taking care of the quality of our sperm is taking responsibility for our descendants. Studies have found that those who indulge in PMO have poor sperm quality, which can lead to infertility. Moreover, those who indulge are more likely to give birth to unhealthy children.

**Related cases:**

**Case 1:**

Due to long exposure to PMO, I’ve contracted varicocele. My urinary problems include: frequent urination, urination urgency, urination blockage. Other problems such as perineum and rectum soreness and inflammation, mild porn induced erectile dysfunction, severe premature ejaculation  _(around 2 minutes)_. I’m afraid of the cold, my hands and feet are always ice cold. My spirit is not very good, my temper is not good either. I am easily nervous, and my emotions are erratic.

**Case 2:**

I’ve been indulging in the bad habit of masturbation ever since middle school. Ever since middle school, I feel like I can’t completely empty my bladder. Because of that, I’m afraid to go to the bathroom with a group of people, therefore I often hold back my urine. During my sophomore year of high school, I felt difficulty in urination. I always feel I can’t empty my bladder. Junior year, I went to a doctor and took some medicine but it was not optimal. Then I took other medicines for over a month with no luck so I stopped taking medicine.

After a year and a half, freshman year of college, I got diagnosed with chronic prostatitis. Symptoms persisted after taking prescription drugs and herbal medicine. During this time, I did not stop PMO. Sometimes, I would do it several times a day, other times once every two or three days. During the second semester of my sophomore year, I went for microwave therapy for my conditions. Although my final test results were basically satisfactory, I was given prescription medicine. Unfortunately, I still have symptoms of frequent urination, urination urgency, scrotum dampness, itchy urethra. I still feel the need for urination after going to the bathroom. I also suffer from penile discomfort.

**Case 3:**

I’ve had symptoms ever since 2004 but was oblivious. At that time, my hair got dirty easily and was very oily. Also, I had a hard time focusing deeply on a subject. I wanted to sleep all the time and I thought it was due to the pressure of college and the lack of sleep. I didn’t recognize the real problem at the time. By 2005, frequent urination happened to me. I was diagnosed with prostate congestion. Since I continued to PMO, my illness developed into prostatitis. The doctor prescribed me prostate Antong tablets, I recovered a lot after taking them, so now I no longer need diagnosis.

Due to essence depletion, my face is shriveled, thin and skinny with a yellow tint. Grey and yellow hair popped up, the texture of the hair turned messy, dirty and wilted. Physically, I can’t grow past 170cm. I developed a slight hunchback. I have a smaller testicles than people my age. My urine is bright yellow.

Mentally, I feel self loathing. I shut myself in, I am easily angered. My head feels like it’s in a vacuum. I am unable to focus my attention on anything, and I have slow reaction speeds. I feel too lazy to think, I yawn immediately after reading a book. I also have low self control, low motivation. I don’t follow through with my plans, I prefer to be by myself and I’m uncomfortable when blown by a slight draft.

Sexually, my back feels sore when I’m about to get an erection. My erection is soft. If I see or fantasize sexual content, my back will feel sore. In the winter, my hands and feet are ice cold, unable to be warmed up.

## Damaging effects of PMO to sexual functions {-}

There is no doubt that masturbation will weaken sexual functions. Some brothers want an example, so here it is. Let’s say you and I both buy a bicycle, you ride it very often so the condition of your bike drops from a 10/10 to a 3/10 with various rusted components that have been repaired many times. On the other hand, I barely ride my bike. I also take good care of the bike so the condition of my bike is a 9/10! Would you say that this is an example of the use and disuse theory? The Inner Canons of the Yellow Emperor states:  _“Illnesses arise from overuse!”_  Most young people are very impulsive and ignorant, therefore overuse is very common. There is no such thing as moderation once we become addicted to PMO. Any form ofself control will be non-existent and no  _“enjoyment”_  will result from PMO. Such a person is a slave to his desires. Just like this, many brothers indulge for several years to several decades.

Next, one’s sexual function will suffer: soft erections, porn induced erectile dysfunction, premature ejaculation will come knocking on the door. At the same time, family is rushing us to get married, which will cause more headaches in life. On the Jiese forums, I see lots of brothers who are depleted before marriage. After marriage, sexual functions are barely working under medication. Erectile dysfunction is a way for the body to preserve itself. It is when our body is telling us we cannot keep indulging anymore, we must start preserving kidney essence. If we keep indulging and taking medicine our bodies will run into lots of problems. Lots of emperors in ancient times died from wasting essence. Once the body has been depleted to a certain point, no supplement will help because it’s unable to be broken down and absorbed (*the kidneys are needed for this process!*). Instead, the supplement will become a burden to the digestive system.

Therefore, I want to put the word out there, I want to emphasize the importance of rebooting and health cultivation. Preserve your essence and take care of your bodies before marriage, otherwise life will be a living hell once all the symptoms arise. I’ve seen several cases of brothers who divorced due to a dysfunctional sex life. We must learn from other people’s mistakes, everyone must understand the harm of PMO! We can not afford to harm ourselves!

In addition, many more brothers suffer from premature ejaculation and soft erections. When we are young, we are ignorant and do stupid things. Many brothers cripple themselves for a brief moment of numbness. It’s ludicrous how many ignorant people show off their sexual functions by ejaculating more than ten times a day, seven times per night, **keep going for over two hours at a time**. Meanwhile, they are unaware of the consequences of their actions. Symptoms that arise will bring them overwhelming pain down the line. One will always act disorderly before total collapse.

The more one indulges, the more deranged fetishes will become, and the closer one will be towards total health collapse. Symptoms will appear sooner or later, forcing one’s mind and body to rot in the hole of misery. Symptoms will force one to take prescription medicines and visit the hospital. It will make one regret one’s ignorant indulgence. Premature ejaculation and erectile dysfunction will completely kill a man’s confidence in front of a woman. Unhinged indulgence before marriage is a ticking time bomb waiting to blow one’s life out of proportion.

**Related cases:**

**Case 1:**

I’ve been indulging since age 15. At first, I felt blockage during urination, my prostate and kidney were both healthy; no issues were found during check up. However, I felt swelling in my abdomen, it was very uncomfortable. Eventually, symptoms got worse, now I am unable to get an erection. I am leaking semen even thinking about obscene material. Everytime I ejaculate, I feel discomfort in my leg area. I just came back from the hospital and got diagnosed with prostatitis. My male hormones are 20 while the normal range is 40  _(The scale in which this was measured was not mentioned)_. My male hormone secretion is inadequate, the doctor said this is caused by PMO.

**Case 2:**

I’ve been masturbating since 16 years of age. I feel severe symptoms of erectile dysfunction. I cannot last more than two minutes. My symptoms of premature ejaculation are also severe. I rarely have morning wood. Ever since I started PMO, I feel soulless. I have no confidence when doing anything. I forget things very easily. I feel bored to be alive.

**Case 3:**

I’ve been jerking off since age 19. I’ve run into issues such as premature ejaculation and erectile dysfunction. Symptoms persisted for six or seven years. Sometimes, I feel like ejaculating in less than a minute of PMO. Every time I get the feeling in less than a minute. I got diagnosed with prostatitis. I took prescription medicine and underwent treatment procedures to no avail. May I please ask how can I get out of this troublesome situation?

## The destruction of appearance {-}

I wrote an entire season regarding the issue of masturbation induced ugliness. I believe many brothers have seen it. Everyone appreciates beauty. Not all men have to be extremely handsome, but one must have essence, energy and spirit. PMO will cause a man’s appearance to decay and demeanor to turn wretched. Such a person lacks energy and will have no spirit in his eyes. Issues such as ghostly skin, black eye rings, eye bags, pimples and excessive oil secretions will arise. One look is enough to give an impression of filth and disgust. This is exactly how masturbation destroy self confidence. PMO will result in one’s appearance to transform to wretchedness and slaughter one’s inner spirit. One’s demeanor will turn quite wretched, it’s essentially self destruction.

With one’s appearance decayed, inner spirit crippled; such an individual is comparable to a deflated ball; unable to function properly. Such a demeanor will negatively effect one’s social relations, it will also affect employment opportunities. Having a positive first impression is crucial during an interview, the first impression is a manifestation of one’s inner spirit. Those who indulge in PMO have a lack of brain power,  inferior demeanor, some people resemble walking zombies, so there is no need to put on makeup to act as an extra for the walking dead. That is to say, such a wretched demeanor will disgust anyone who sees it. Having such shameful and self inflicted deformity will be especially troublesome during interviews.

I’ve seen before and after PMO photos of brothers; It’s sad to see that many handsome, bright, brothers with clear eyes full of vigor and positive energy turned into ugly subhumans. Some brothers would be confused and will ask if both photos are pictures of the same person. I vividly remember the thread a brother posted with a comparison of himself before and after indulging in PMO: the change in his appearance can be compared to falling out of heaven and crashing in hell.  _(Here is the link:  [https://tieba.baidu.com/p/2572592705?red_tag=0961329430](https://tieba.baidu.com/p/2572592705?red_tag=0961329430))_. The change in his appearance is quite tragic. It is not an exaggeration to say it is  _“the difference between heaven and hell”_. Many girls are attracted to these brothers before they are addicted to PMO. After the addiction, girls start to get annoyed due to the wretched demeanor. The degradation of spirit will have a huge impact on self confidence.

PMO will turn our appearance ugly; which includes the degradation of complexion and cause facial feature deformities. Of course, the injury will need to reach a certain level before deformity takes place. This is comparable to a picture of a person from when he was 20 versus 50 years old, you will notice apparent changes. Certain parts of the face will undergo subtle changes after masturbation, this kind of change is gradual. Once it has accumulated to a certain level, it will become very apparent.

In the cases that I have come into contact with, a lot of them are about a sunkenness in the face. For some brothers, their eyes have turned smaller, their eye socket will drop lower. Everybody should know, as a person ages, his facial features will undergo changes, a tight and fine face will become loose and slack. Skin quality will also deteriorate, in addition, the shape of the face will also change subtly. Although one is still able to recognize the person, you will notice that many parts of the person have changed. This facial change is brought on by aging. But masturbation will induce premature aging. The pulse of many young people resembles that of a 60 year old man. Their face has a dead look to it and is lacking the vigor and spirit of a young person. This is the gift from the worship of masturbation.

**Related cases:**

**Case 1:**

I remember masturbating for a year during the 3rd year of junior high, sometimes once a day, sometimes once a week. At the time, I prioritized my studies and noticed much harm from masturbation. My urine was yellow, I sweated easily, was impotent, felt weak, was extremely introvert, not saying a word to another person. At the time, I already noticed that masturbation wasn’t good for me.

In the holiday period prior to high school, I masturbated like crazy. The few weeks after school started, my appearance changed rapidly. My skin pores were large, blackheads on the nose. Lots of oil secretion, extreme dandruff on the scalp. I contracted skin disease, whenever it was summer the skin would itch like crazy. My face was old and nothing like the face of a 16-17 year old. No matter how I combed my hair at the front of the head it would always remain looking unkempt. My hair was thick and sticky just like my skin pores. My body odored and scared me into washing my clothes everyday. The scariest part was the torment on the psyche. I turned into a person without any social abilities, not uttering a word to another person. I was afraid of facing another person. We don’t even need to mention my appearance, the change was overwhelming, like somebody who had been stolen of essences.

**Case 2:**

I will turn 12 towards the end of the year. At first, I didn’t want to do it but I wasn’t careful and so… I had been studying away from home for several years. Now I have returned to the village and people all say that they don’t recognize me. My face has changed, to put it positively, I have grown and matured. What else can I do, I have become ugly! And my body is ridden with illnesses. There is a body odor that cannot be washed away. I’m the most vile, don’t compare anything with me, I have nothing.

**Case 3:**

Previously, I was fair and a little chubby, everybody loved me. Now I am the enemy of all, beyond ugly, a retarded look has spread across my entire face. I’m not skinny, 169 cm tall and weigh 66 kg, but it is very strange, all the muscles in the face are concentrated on my chin. The muscles on my cheek and on the sides of the nose are lacking. The same goes for my eye sockets which is why my eyelids are drooping. The muscles on my face do not fit together, I look 15 years older than my actual age. Let’s not mention age, that wretched impotent look is no small matter. I look like the remaining trash from somebody who has been sucked dry of essence by some witch. If I step onto a bus, I will for sure get the cold shoulder. When running into a kind person, they will at most think that I’m a sick person and offer me their seat. I assume that if I’m going to act in a horror movie, I will for sure be able to act the zombie without makeup, with the potential to become the leading actor. Or let me play the mental patient or the drug addict, I will for sure stand out and be outstanding.

**Case 4:**

Looking at the stupid and disgusting image of myself in the mirror makes me want to puke. Thank God for giving me the one chance I have to redeem myself, I will treasure it. I have already masturbated for 4 years, today is the second rebooting day. I’m a 2nd grader in high school, I cannot afford to lag behind in studies.

**Case 5:**

I’m 24 years old, I have over a decade of history behind me. When it comes to spiritless eyes and poor skin… I have everything that you've mentioned. The thing that I absolutely cannot accept is my cheek bones becoming seriously raised, they protrude outward and towards the side. My eye sockets are clearly hollowed and look deformed. This is why I am rebooting. Those who have yet to become like me should hurry up and reboot. No matter what, one should become a real man.

## The devastation to the legs

In the movie [洛奇] it is mentioned:  _“women makes men’s legs soft”_. This sentence is a famous saying in the boxing world, this should come from practical experience. For instance, some boxers would sexually indulge themselves before a fight, during the fight they would be entirely out of shape, their legs lacking strength and feeling unstable.

This phenomenon of soft legs after indulgence is very common. It is entirely explainable in TCM medical theory. TCM:  _the kidneys govern the bones_. The kidney meridian starts from the bottom of the feet and goes upwards passing the Yongquan point. The waist houses the kidneys, the knees are a path for the kidneys. Therefore, kidney deficiency will result in soreness and softness in the waist and the knees. In serious cases, there will be pain in the legs and waist.

I have seen it stated in the book on Xingyi boxing that the true strength of a person comes from the bones, it originates from the kidneys. It is mentioned in TCM:  _the kidneys are the source of strength_. Many brothers have had such an experience where after a relapse, the legs go soft and even the entire body is without strength, one becomes lazy and tends to yawn. TCM has also mentioned:  _the kidneys sneeze via the yawn_! This comes from [素问宣明五气]. It has been insightfully pointed out that the tendency to yawn and to sneeze is one proof of kidney qi deficiency. Many brothers yawn all day long, this is not normal. Too much yawning is actually an expression of kidney deficiency.

The leg power of men is unusually important. When people become old, the legs become old first. When gauging whether or not a man is strong, do not look at his upper body, look at his legs. These legs are like tree branches, they need to be strong enough and possess power, in this way, the whole body will become stronger.

When I was a personal trainer, many people had a misunderstanding in working out. They made their upper bodies very strong but left their legs very thin. This is really not well-proportioned, they have got it backwards. The principles of force projection by a person start from the feet, send out from the legs, ruled by the waists and formed by the fingers. Without power in the feet and legs, your fists will not pack a punch. Without power in the feet and legs, a person walking will seem unstable and give a floating feeling to him.

There is a famous saying in the world of weight lifting: deep squats are the king of strength exercise. When there is power in the feet and the legs, the whole body then becomes stronger. Of course, being strong is not a sign of health. Too much is as bad as not enough, the result will turn worse. This is the same as the string of a musical instrument. It shouldn’t be too loose nor too tight. It needs to be just right for the sound to come out. When the body is weak, my advice is to combine aerobic exercise with stillness cultivation as the main focus points. When one has almost recovered, one may do some moderate strength exercises.

**Related cases:**

**Case 1:**

Ack! I envy those who have been masturbating for under 10 years, I’m a big brother in this respect. When I was 17 people thought that I’m 26/27 years old. 5% of my hair has turned grey, I have varicocele, infertility, loose teeth, ..etc. I have all the symptoms that you guys have been talking about especially the part about the strengthless legs. I feel very fatigued when walking, I regret not finding out about this earlier. I will need to reboot for a minimum of 3 years to get well. The good thing is that I have already been rebooting for 16 days, one symptom has improved and that is my urinary stream no longer divides itself.

**Case 2:**

I have been masturbating for over 8 years. During winter, all of my limbs are ice cold, my hands are freezing. I’m afraid of cold, both hands and feet are sweating, sometimes my hands and feet feel parched. When sleeping at night, I always sweat and have excessive dreams. All four of my limbs lack power, ears are ringing, eyes are dry, I’m impotent and suffer from premature ejaculation. I have scrotum dampness, sore waist, weak legs following ejaculation, sweating all over the body. I’d like to ask if this is due to both Ying and Yang deficiency? How do I treat it?

**Case 3:**

I have a 2-year history of masturbation. Maybe because I masturbated frequently during the holidays do I now have waist pain. The entire body hurts whenever I turn it. When sitting down on a sofa in a bad posture I also experience a lot of pain, the pain reaches a peak in the morning when I wake up. My left leg is soft and I cannot straighten it, I have waist and leg pain when doing sit-ups, what can I do? I have not masturbated for a month already, moreover, I have taken half a bottle of Liu Wei Di Huang Wan, there is no effect, the pain remains. When I walk nowadays, it does not feel natural. All of my colleagues tell me that I walk awkwardly and that my waist is not straight.

## The devastation towards the nervous system {-}

I have specifically talked about neurosis in season 30. Masturbation will indeed injure the nerves because the kidneys are connected to the brain to the above. Masturbation not only injures the brain power but also the nervous system. A lot of brothers run into neurasthenia, autonomous disorder, anxiety disorder, phobia, and related neurosis.

Neurosis is a dividing range for the people suffering from essence damage. After having tasted the pain from neurosis, one then truly understands what is hell on earth. It is truly ravaging for the body and the mind, a very scary experience. Scary in this context is not at all exaggerated. Only those people who have had the experience themselves will be able to understand those type of feelings. For those brothers who have yet to masturbate their way to neurosis, thoroughly absorb the lessons from the forefathers, properly reboot and cultivate the health, don’t let oneself repeat the mistakes of the predecessors.

I remember warning in an article that masturbation would induce neurosis, but at the time not many people heeded my words. The result was that many brothers really did run into neurosis. Everybody cannot be blamed because they have not had personal experiences, their understanding of neurosis is on a white sheet of paper (or computer monitor in this case). With personal experience, the understanding will be deeper. But, for those people who have had the experience, almost every one of them cannot wait to crawl out of symptom hell. This is because symptom hell is not a place for people to dwell in. It is a world that is flooded with fear and despair.

For those people suffering from neurosis and who find themselves in the devastation of symptoms, the path that I’m pointing to is one where one must persist in rebooting and in health cultivation. One must recognize the importance of rebooting and health cultivation. After having gone through the feedback from many brothers, after a while of persistent rebooting and health cultivation, many bodily discomforts will automatically disappear. The effect is superior to taking medicines.

When taking medicine, one may be unfortunate and run into side effects. Persistent rebooting and health cultivation, on the other hand, will start the self-healing function of the body. There is great medicine in the human body, do not leak this away due to masturbation, that would be most pitiful. Kidney essence is the battery of your body. It is the recovery weapon of your body, the trump card of your body and the currency of health. Once the kidney essence has been cultivated to abundance, healing will take place without medicine!

**Related cases:**

**Case 1:**

I’m on my knees begging for the TCM doctor, masturbation has induced neurasthenia. Previously due to pressure, I have often resorted to masturbation for a release. The result was severe neurasthenia. Right now, my memory is extremely poor, my waist is often hurting. After running for a while my feet cramp up, I’m unable to concentrate. Even after getting plenty of sleep my concentration is still very poor. My head feels empty and I often feel fatigued. Can somebody help me!?

**Case 2:**

I have got neurasthenia, I’m unwilling to admit that I have neurosis. Previously, death was preferable to life. Although things are a bit better now, there is still no hope in my life. Before I had neurasthenia, I was already addicted to vile habit of masturbation. I must quit it! I hope the heavens would bless me! I must quit it!!! Due to the discomforts from neurasthenia, I’m unable to work, I have been home for more than a year. My social skills and many other societal skills are far from what they used to be, ack! If I hadn’t come into contact with masturbation back then, perhaps things wouldn’t be like they are today. I hope that I’m able to get well, return to the normal, confident and brave me.

**Case 3:**

Due to young age and not knowing any better, I contracted the evil habit of masturbation 4 years ago. I’m basically in control now but I feel a decline in my memory, comprehension and concentration. I’m unable to stand firmly, I feel dizziness, headache, insomnia, agitated, night sweats. My stomach has not been feeling well for over a year. There is stomach pain and my stools are not properly formed. Also, I do not pass stool regularly. Through gastroscopy, it was confirmed that I had superficial antral sinusitis along with a large number of helicobacter pylori. I have previously undergone psychological treatment in accordance with the treatment of anxiety disorder. Nowadays my mood is not stable, my hands and feet are numb and I have insomnia.

## The devastation towards the respiratory system {-}

TCM:  _the kidneys govern the inhalation of qi, the lungs govern exhalation_. It is also mentioned:  _essence deficiency leads to nasosinusitis_. When the kidneys are deficient, the immune system's resistance will decline, there will be a higher chance of catching rhinitis. People that are already suffering from rhinitis will easily see an aggravation of their symptoms following an addiction to masturbation. In my cases, quite a few brothers have also encountered pneumothorax. Masturbation increases the chance of encountering issues with the respiratory system especially when the natural constitution is poor. Adding to this external factors such as cold winds, one will easily be troubled by respiratory system related illnesses.

_“The kidneys govern the inhalation of qi”_  in TCM points to the relationship between the kidneys and the inhalation functions of people. Although the lungs govern the breathing, the kidneys have the function of ingesting the qi  _(namely “inhale the qi”)_  of the lungs. Clinically, when it comes to chronic coughing, especially for the elderly who are suffering from kidney deficiency, many of them have difficulty in qi inhalation. Inhalation has the meaning of receiving and absorbing. The kidneys govern the inhalation of qi, what it is meant by this is that the kidneys absorb the clear air that has been inhaled by the lungs. They have the function of preventing shallow breathing.

Although the breathing of the body is mainly governed by the lungs, TCM posits that the work or the non-working of the breathing function is intimately connected with the kidneys. This is specifically expressed when clear air that is inhaled by the lungs is transmitted down to the kidneys, it is absorbed by the kidneys. The stability and depth of the breathing movement are maintained in this way.

Accordingly, the normal gas interchange within and without the body is guaranteed. The expelled air, although it mainly resides in the lungs, finds it's root in the kidneys. When the kidney qi is abundant, the qi in the lungs will be plentiful. Reversely, when the kidney is deficient it will no longer aid the lungs to inhale air, and the sufferer would then exhale more while inhaling less with the accompanying feeling that the inhaled air is not reaching the Dantian region (*a 'not enough' feeling*).

Regardless of whether one is suffering from a weakening of kidney qi, powerlessness in absorption, suspension of air in the upper region, qi deficiency in the lungs or long term illness in which the kidneys are affected, all of these will induce the abnormal qi absorbing function of the kidney qi. Shallow breathing will then emerge, or the situation where one inhales a lot but absorbs little, the expression of asthma, ..etc. These are all called  _“kidney not absorbing qi”_.  _(Translator’s note: the above paragraph goes deep into TCM theory and goes beyond the knowledge scope of the translator. Please use caution when trying to interpret the translation)_

**Related cases:**

**Case 1:**

Since childhood, I had a poor constitution. Once addicted to masturbation, I was not able to pull back. I masturbated in secret from the adults, sometimes twice per day. In my teens, I gradually noticed that I had rhinitis. Later I experienced a headache, decreased memory and a gradual decline in my school grades. At the age of 18, I started to experience swelling pain in the perineum, waist soreness. At the hospital, I was diagnosed with prostatitis. I was infertile after having gotten married. Through treatment I was able to produce a child, I also spent a lot of money and took on a lot of liabilities. Nowadays, my head is dizzy everyday and I’m extremely easily fatigued. I do not have the mood to work. My life is also severely affected. These last two days my throat is uncomfortable, the lymph node behind my ears is very large and swollen. The cruelty of the disease has made me lose confidence in life. I’m filled with confusion and fear.

**Case 2:**

Ever since I was 15 years old I have had the habit of masturbation. 2 years ago, after a sneeze, I caught lumbar disc herniation. After conservative TCM treatment, I got a lot better. I have also had rhinitis since middle school. Last year, I took a few rounds of Chinese herbal medicine for rhinitis. After the first round, the effect was really good but afterwards, there was no effect no matter how much medicine I took. So then I went and got operated for rhinitis. Last year I had appendicitis.

## The devastation towards the digestive system {-}

TCM: The kidneys direct the passing of stool and urine. When the kidneys are deficient, frequent urination easily appears. There will also be issues in passing stool and the digestive system will also weaken. The source of the kidneys is prenatal, the source of the spleen is postnatal. The kidneys store essence and the essential qi of the five viscera and six bowels.

Deficient kidneys will affect the spleen. Put another way, the kidneys and the spleen affect one another. Problems with the spleen will likewise also affect the kidneys. Following masturbation, common problems with the stool include: diarrhea, frequent stool, shapeless stool, incomplete stool. Many brothers have gone to the TCM doctor and have been diagnosed with kidneys and spleen Yang deficiency. This will require recuperation by Chinese herbal medicine. One must also pay attention to the diet and try to make light food as the main diet. Try to avoid irritable food as much as possible. Cold and spicy food should be avoided.

The kidneys, stomach and the spleen mutually support and are dependent on one another. The qi and the essence of the kidneys is dependent on the replenishment and the nourishment of food essences. This allows the qi and the essence of the kidneys to become plentiful and mature. At the same time, the transformation of the food essences in the spleen and the stomach must borrow the warmth from the kidney Yang. The saying goes  _“Without blood and essence, there is nothing to form the foundation of the body. Without food, the body cannot become strong”_.

In terms of pathogenesis: if the kidney Yang is deficient, the spleen Yang cannot be warmed and cold pain in the abdomen will appear. Other syndromes of spleen Yang deficiency include watery stools or morning diarrhea and edema etc. If the spleen Yang is deficient, in time, kidney Yang deficiency will be induced. A deficiency in the spleen and the kidneys will induce powerlessness in the transportation function of the intestines, making the stool hard, hard to pass stool. The accompanying symptom of pain in the abdomen, cold limbs and cold soreness in the waist and knees.

**Related cases:**

**Case 1:**

I have a 10 year history of masturbation, my symptoms are as follows: insomnia and excessive dreams, oily hair, moist ears, strengthless limbs, premature ejaculation, still OK erection, fear of cold, hot feeling in the feet, arms and the heart, dislike talking, crying during happiness, unformed stool  _(sometimes diarrhea, sometimes frequent stool)_, quite skinny, yellow urine which forks out during urination, a lump the size of 0.4x0.4 cm in the bile duct of the liver. I hope that Big Brother can save me, thanks.

**Case 2:**

I count 7 years of masturbation history. During high school, I masturbated quite frequently. During the high school exam, I suddenly had diarrhea. At the time, I didn’t go see a TCM doctor, I went to see a Western medicine doctor, took a lot of medicine but to no effect. Later when I went to see a TCM doctor, they told me that I had spleen Yang deficiency. I took Chinese herbal medicine. Whenever I took the medicine I was fine and vice versa. During 4 years at university, I didn’t masturbate that frequently. My body also didn’t have much trouble, only that my stool was formless. Therefore, I’m very troubled. During the summer holiday, I came into contact with the rebooting forums. I’m determined to quit, now I’m in my 2nd month.

## The devastation to the hair {-}

Masturbation will affect the quality of the hair and will also induce grey hair and hair loss. Although some brothers have not encountered hair loss, however, the quality of their hair has already seen big changes. The hair is dry and frizzy, some brothers used to have straight hair, after being addicted to masturbation for several years, their hair has become curly. I have read from the book about appearances that curly hair is a sign of the love for lust, this goes to show that people from ancient times had deep insight and research into this area.  _(Translator’s note: Its worth a note that the majority of Han Chinese have straight hair, it is a rare occurrence for a Han Chinese to have curly hair. Also worth noting is the common interchangeable use of curly hair and wavy hair in the Chinese language)_.

Extremely many brothers are troubled by the occurrence of hair loss. I was previously troubled by severe hair loss, losing over 200 hairs per day, even losing 300 hairs per day which had been going on for a long time. On my cheeks and shoulders was hair that was terrible to look at. At the time, I was very much in panic and was nearing collapse. Because I had been experiencing hair loss for a period of time, the top of my head was starting to show, also I was not yet 30 years old at the time.

The good thing is that from then on I started to reboot and cultivate my health, it took half a year before the hair loss trend could be halted, it took over a year of time before hair slowly grew back, it is truly a slow process of recovery. The hair loss that I suffered from was due to kidney deficiency.

If my case had been a combination of male balding and kidney deficiency, then recovery would have been quite difficult. Some brothers have hair loss due to hereditary factors, recovery is even harder in those cases. However, if you persist in rebooting and in health cultivation, some alleviation and recovery will for certain take place. At the very least, the quality of the hair will improve by a lot.

TCM: *The splendor of the hair is found in the kidneys, its growth is based on the liver blood*. The kidneys, together with the liver and the spleen share an intricate connection with one another.

It is the view of TCM that the below factors are related to the greying of the hair.

First, it is the deficiency of essence and the weakening of the blood: when the kidney essence is inadequate, blood cannot be transformed, when blood is deficient, this leads to the loss of nourishment for the hair, making it grey.  
Second, it is the hotness of the blood which approaches excess: mood excitement leads to the inability of the water to contain wood. If the liver is vigorous then the blood is dry, hotness of the blood approaches excessiveness, the root of the hair loses its support, premature greying therefore takes place.

Third, it is the sluggish liver and the moist spleen: when the kidney qi is sluggish and stagnant, it damages the heart and the spleen. When the spleen is damaged, transmutation of food ceases to function properly. The transmutation of blood and qi thus lose their source resulting in the greying of the hair.

Many brothers are troubled by greying hairs, I also had a lot previously. After rebooting for over a year, they turned black. I didn’t take any particular dietary supplements, although sometimes I did take black sesame and yam. Yam I took often. Some brothers have been rebooting for 100 days and their grey hairs have reduced a lot. Others have been rebooting for 200 days and there are very few grey hairs remaining.

There is hope of recovering from greying through rebooting and health cultivation. As long as you have put in the necessary efforts in both areas, there is hope of restoring black hair. Of course, if your greying is very serious, it would be best to incorporate Chinese herbal medicine in the treatment. One also needs to do well in dietary supplements and actively exercise. Health cultivation practices can be trained, one needs to put a lot of effort in the way of health cultivation.

**Related cases:**

**Case 1:**

Before when I didn’t know any better, I masturbated frequently. Later on, a lot of grey hair grew out. May I ask if I start to cultivate now is it possible to turn grey hairs into black ones? What should I eat?

**Case 2:**

I was born in 1993 and I will turn 19 this year. I started to masturbate when I was 16. At the time, I just graduated from middle school and went to a garbage technical school. I learned how to masturbate from there. Up until now, it has been 3 years! For 2 years, I masturbated once everyday! Sinful masturbation, if I didn’t masturbate during these 3 years, I would have grown 3 cm taller for sure! Ever since I started to masturbate, I had grey hair, black eye rings, rhinitis, fear of cold, acne, skinny and weak, wretched look, bad luck, ..etc and I hadn’t thought about the consequences. They have all arrived, just now I relapsed! Ack! Blind rebooting!

**Case 3:**

This year I turned 21, I have been masturbating for 5 years. Now I’m bald, please I ask you guys to save me. My dad is also bald, but I’m only 21 and have already inherited it? Can I still recover? Right now all my hair has fallen from the sides of my temples. There are only a few strands of hair remaining, what should I do? In addition, there is a lot of oil, will hair still grow out? I’m always up late, only sleeping at 3 am. Can somebody save me? I’m begging you guys! Please save me!

**Case 4:**

I’m 18 this year. Due to frequent masturbation for 2 years, I have encountered heavy hair loss. Whenever I exercise, I’m tired. Sometimes my waist will feel sore and my back will hurt. My memory has also decreased. The quality of my sleep is not very good. Sometimes there is blood in my stool. I want my body to recover and to put a stop to the hair loss.

**Case 5:**

I started the habit of masturbation since I was 18. I would masturbate almost everyday. Previously, my hair was tough and wouldn’t come off even after pulling it hard. Nowadays the hair root is very fragile, and easily falls after light pulls. Everyday I lose over 200 strands of hair. During winter, my hands and feet are ice cold, my waist is sore and I’m scared of the cold. I had this condition for 3 years. Yesterday, I experienced constant tinnitus in my left ear, I’m extremely worried. I have searched for similar states of illnesses and I know that this condition is induced by excessive masturbation.

## The devastation to the internal secretion system {-}

Masturbation will induce disorderly internal secretions. I remember when I used to go to get a check up for my acne, the doctors at the 上海华山医院 hospital said that I had disorderly internal secretions. I was quite ignorant at the time and had no idea that it was caused by masturbation. I only knew that if I rebooted for a period of time, my skin would become clearer. Masturbation is very damaging to the skin, it will induce poorer skin quality, oily and rough skin. I think many brothers have ample experience in this area.

Many people are approaching facial disfigurement. The person in the mirror has turned ugly and wretched beyond bearing, looking  neither like a person nor a ghost, one just wants to smash the mirror. Many brothers who previously liked to look at themselves in the mirror now avoid it. They dare not face the wretched and wasted person in the mirror. By persisting in rebooting and cultivating the health, internal secretions will slowly adjust themselves. Normally, by persisting for 3 months and combining with active exercising they will stabilize. Active exercise is very important and is crucial to the adjustment of internal secretions. Rebooting alone is not enough, one must moderately exercise.

The classic concept of internal secretions points to internal secretion glands that have formed by a cluster of specialized cells. They include pituitary, thyroid, parathyroid, adrenal, gonad, pancreas, thymus and pineal glands. These glands secrete highly efficient organic chemicals  _(hormones)_. Through the circulation of the blood, chemical signals are transmitted to the target cells, target issues or the target organs, they have the function of either stimulation or suppression.

The substances that are been secreted by the internal secretion glands are called hormones. Hormones include estrogen, androgen, lutein and growth hormone, ..etc. When the internal secretion becomes disorderly, the quality of the skin will deteriorate and acne easily arises. The temperament will also become impatient and one will be easily angered. Subtle changes will also take place with respect to body hair, either manifesting as an overabundance of body hair or lack of body hair.

To adjust internal secretions, we should properly reboot and cultivate the health. We must form excellent resting and dietary habits. Avoid staying up late at all costs as it will also induce disorderly internal secretions. Many people experience worse skin after having stayed up late.

**Related cases:**

**Case 1:**

My facial skin frequently produces oil and there is acne. The doctor said that my internal secretions are out of tune. It looks like it is certainly caused by many years of masturbation. I have had acne ever since middle school and still have it to this day. I also happened to start masturbation at that time.

**Case 2:**

Due to long term masturbation, my internal secretions are abnormal. In addition I stay up late, drink alcohol, smoke and have other bad life habits, they have caused acne to form on both sides of my lower jaws. Moreover, they will not reduce after a long period.

## The devastation to brain power

I have written about declining brain power in one season, declining brainpower is indeed very common. Many students are out of luck. Their reactions are slow, unable to concentrate. Their memory is extremely poor, their grades have started to decline. Naturally, decreasing brain power is a tragedy for any group of people. It is the same for the working professionals. When doing things while the brain power is inadequate, one is unable to perform them well. One lacks focus and persistence, oftentimes giving up halfway. Whatever one does it is not successful. Without power, the entire outlook on life becomes grey and dark.

It will take approximately over half a year of time for the brainpower to recover. Exercise actively, moderately ingest brain supplementing food and maintain sleep quality. In this way, brainpower will slowly recover. Use reboot to gain determination, use determination to sprout wisdom. Rebooting and cultivating virtue will indeed open up wisdom. As wisdom increases, many questions that had previously escaped your comprehension will suddenly become clear, the feeling is like a flash of insight. When brainpower is decreasing, even if the teacher has lectured 10 times, one might not understand for certain. When brainpower is good, one will be able to completely understand after the teacher has been lecturing once.

TCM: *Kidney essence transforms into the brain*. When essence is lost, the brain is empty! The ravage that masturbation has on the brain is quite serious. It is a pity that I didn’t know about this in the past. I blindly masturbated and urged myself to self-destruction. Being absorbed in masturbation at the time, I noticed that the previously clever me became very slow, my memory and concentration all went down drastically. Once known, one becomes strong, by not knowing, one grows old. Although some people don’t know about the harm of masturbation, they start to masturbate quite late and in this way, one can say that they have dodged a bullet.

**Related cases:**

**Case 1:**

I started to masturbate in the second semester of the last year of middle school  _(15 years old)_  and have done so up until today. I have already have had a history of masturbation of 10 years. During class, I could in no way concentrate. I would be lucky if I was able to listen to 4 minutes of lecture, my comprehension ability has become extremely poor and my reaction slow.

On average, I masturbated once a day during high school. I started to experience sharp pain when urinating. My urination stream split into a fork. There is delayed urination and other symptoms. During university, I masturbated on average once every 2-3 days, neurasthenia started to appear along with dizziness, headache, swelling brain, insomnia, excessive dreams, decline of short term memory, poor concentration, low efficiency, irritableness and easily angered, fatigue without strength, afraid of light, afraid of sound, tinnitus, blurred vision, decadent spirit, ..etc. In everyday life, I have all forms of physical discomforts such as heart jumps, out of breath, decreased appetite, frequent urination, nocturnal emissions, ..etc.

**Case 2:**

I started to masturbate at 18. Because I liked to exercise and felt that I had good enough physical strength, whenever given the opportunity I was not able to control myself. After 2 years, I discovered that my memory clearly decreased. I was not able to memorize things skillfully. Now I’m 22, I have not had nocturnal emission for 4 years. Today, I still don’t have morning erections.

**Case 3:**

I started to masturbate since 1st year of high school. It has been 5 years up until today but I was not able to quit it. I masturbate twice a week on average, sometimes 3-4 times. This has made my memory very poor today. Everyday, my head is heavy and without energy, my head is very dizzy. Now I’m in my 2nd year at the university, I’m not able to memorize textbooks, my memory is abysmal. Now I have reduced the frequency of masturbation but my head is still heavy. My head is very very dizzy and unclear. What should I do? I’m extremely distressed.

## The spending of money {-}

I have specifically talked about the issue of medical expenses in season 35. When symptoms show up following masturbation, medical expenses skyrocket. Many people toss out money in the thousands and even in the tens of thousands, but they have all been tossed out in vain. Some brothers even encounter quacks, their body becomes progressively worse after treatment. They have become medicine jars, sick men from masturbation. One is disappointed at oneself and his family is also disappointed in him.

Not masturbating is saving money, this is the maxim from those who have already walked the road. Remember this saying, it will truly help you to save unnecessary expenses. Many brothers are students and cannot afford to go to the hospital. Even if one is a working professional, the few thousands or even the tens of thousands that one spends every year is not a small sum. Most importantly, ill health is not cured after spending the money. If one continues to immerse oneself in masturbation, the chance of relapse is extremely high.

**Related cases:**

**Case 1:**

Previously, my health condition was excellent. The scores from the hospital on white blood cells were ++ and +++ for the phospholipid bodies. My state of illness:

1.  Frequent urination: I need to go to the WC every half an hour. Sometimes, I feel that I have to go after a few minutes.
    
2.  An urgency to urinate.
    
3.  Incontinence.
    
4.  Sore waist and aching back.
    
5.  Lack of strength in the 4 limbs.
    
6.  Decrease in memory.
    
7.  Slow reaction.
    

I have undergone treatments at the 金陵 male hospital, 新安 TCM hospital, 弋矶山 hospital and have taken a lot of medicine, mostly in the form of prostatitis related Western medicine. However, there was no improvement after having spent all of my savings and half a year on treatment.

**Case 2:**

I have had prostatitis for several years. I have been to several hospitals and have spent tens of thousands of RMB but my illness remains, I’m almost crumbling! I had been to the 广慈 male division at the 陕西生殖医学 hospital in the city of 韩城 and 博爱 county. I have frequent urination, urgent urination, incontinence, nocturnal emissions, premature ejaculation, and abnormal sweating.

## The devastation to the quality of sleep {-}

Although some brothers don’t have other symptoms, their quality of sleep is extremely poor. Some brothers are only able to sleep for 2-3 hours, some dream a lot and are easily awakened, some cannot sleep altogether, others tend to have nightmares. When kidney deficiency reaches a certain degree and when combined with irregular work and rest times, there is a high chance of encountering sleeping obstacles. Serious sleeping obstacles require active treatment. Serious insomnia will require at least half a year of recuperation. With a night of good sleep, the body will be able to recover quicker, or else the body will have a hard time recovering. A brother has said that as long as he is given a good night's sleep, he will be able to endure, but he is currently deeply troubled by insomnia.

In order to improve the quality of sleep, excellent working and resting habits must first be formed. One cannot continue to stay up late, that is too damaging to the body. One must form excellent working and resting habits, try to fall asleep before 11 pm as much as possible. Even if you are unable to sleep after entering the bed, don’t sit and stay up, but close your eyes and rest on the bed. One must learn to slowly adjust the habit of staying up late.

If you do not try to change, then you will only make repeated mistakes, accumulating the small mistakes into a big disaster! Once this type of destruction and drainage towards the body and the health has accumulated to a certain degree, life may be sacrificed if one is not careful. Examples of sudden death while staying up late is very common, one must be vigilant in this area.  _(Translator’s note: Readers should be not frightened upon reading this, to my knowledge, these cases of sudden death are very rare and often occur in combination with being intensely concentrated on some activities while having a lack of sleep over an extended period of time)_

In addition, to improve the quality of sleep, one is advised to do more aerobic exercises. Persist for a while, and you will notice yourself falling asleep more easily, there will also be more deep sleep. I remember a book by 曲黎敏 that mentioned the issue of sleep. It mentioned why migrant workers have such good quality of sleep and are able to fall asleep instantly upon hitting the bed because they carry out a certain amount of labor each day. Migrant workers also do not stay up late or sit for long durations to stay on the internet. In this area, we should really learn from the migrant workers.

**Related cases:**

**Case 1:**

I started to masturbate 12 years ago. In the 6 years since middle school, I masturbated almost everyday. This lasting and excessive masturbation made me suffer such harms: sore and soft waist, mild impotence with accompanying premature ejaculation, forgetful, declining memory, a short circuit in thinking from time to time, lack of vitality, hair loss, thick hair turning into dried yellow hair.

The most serious issue is that because I’m newly married, my sex life has become frequent again. Nowadays, besides the above symptoms, I have encountered difficulty in falling asleep after making love. Insomnia to the degree that I almost don’t sleep during the entire night, constantly in a state of half dreaming and half awake. This has led to a very low level of energy the next day, soft waist, slow reactions, agitation and don't want to do anything. I have recently been to the TCM doctor. She doesn’t seem to believe that I suffer from kidney deficiency at such a young age, ack! Save me.

**Case 2:**

I have masturbated for a long time. Now I have insomnia, my energy level is very poor. During the day, I urinate quite frequently. At night, I sweat easily. I don’t have an obvious fear for either coldness or hotness, self-felt middle qi  _(Translator’s note: middle qi is associated with the spleen and the stomach)_, inadequate health energy, lack of Spirit. Currently, I’m in the process of ridding myself of the evil habit of masturbation. Most of all I want to heal insomnia and recover the Spirit.

## Obstacles in development {-}

Obstacles in development are commonly seen in youth who are addicted to masturbation. It is mainly reflected in the slow development of the bones. Some brothers have encountered development obstacles with the penis. The penis belongs to the liver, the liver and the kidneys share a common source. If one is addicted in masturbation during the first two years of development, combined with a poor bodily constitution and inadequate intake of nutrients, then there is a high chance of encountering development obstacles with the penis.

The kidneys govern the bones. Masturbation will affect the growth of the bones. This is one factor which affects the growth of height. In addition, it will affect the quality of the bones. Although many people have reached their optimal height, their bone quality is very poor. Sprained ankles and broken bones occur easily. The bones of some brothers are thin and soft, lacking in strength. Some brothers have even encountered deformity in the bones.

Some brothers will ask, is there still the hope for recovery past puberty? The bones have basically matured past puberty, but the quality of the bones may be improved through rebooting and health cultivation. Growing in height will be quite difficult but improving the quality of the bones is still possible. The penis is also basically matured past puberty, to grow it will also be quite difficult. But if the quality of your erection is very good then that is a good thing.

**Related cases:**

**Case 1:**

I’m 18 now, I have been masturbating for roughly 4-5 years and very frequently. Sometimes, I masturbate 1-3 times every day, it has lead to a very short and small penis to this day. When it is erect it is only larger than the thumb by a small margin. I also have premature ejaculation. Sometimes the stem under the testicles is very painful.

**Case 2:**

This year I will turn 20. I started to masturbate when I was 14, that is quite a few years. Right now, I don’t have hair in my armpits, I don’t have facial hair, my penis is short and small, my urine is very yellow and forks out when urinating, my entire body is lacking strength, my memory is very poor. What should I do?

**Case 3:**

I started to masturbate when I was 10 years old. It has been 9 years up until today. This has induced a small and thin bone frame. I’m already rebooting now. Can my bone frame still become thick and strong?

**Case 4:**

Masturbation has induced a small and thin bone frame, my body is thin and weak. I have been masturbating for 4 years. Now I don’t masturbate as often anymore but my weight is only 50 kg. I’m 18, is there still hope for me?

In this season, I have made a summary of the harms from masturbation, these are nothing more than the commonly seen symptoms. In the final phases of sustaining damage from masturbation, combined with the total effect from other factors, more serious illnesses might arise, such as the possibility for diabetes and stroke. It is absolutely wise to reboot early, especially taking the opportunity while one is still young. Cut out this evil habit for good, the initiative can be maintained in this way. Do not wait to reboot until the body cannot keep up any longer, that would be quite late. This is like when somebody is addicted to smoking and is unable to quit. Suddenly one day there is serious discomfort in his heart and it is found that an operation will need to take place. Isn’t it a bit late now to cut out smoking?

People with high realization will always draw lessons from others while rebooting, from which one is able to foresee the future and the symptoms. Then the foundation from which one is rebooting will become extremely firm. These kind of people have a high chance of succeeding. We should learn from people of high realization and strive to successfully reboot early.

## Concluding remarks {-}

While rebooting, we should allow ourselves to reboot as professionally as possible. It is not enough to only know about the harms. There are many medical students in the rebooting forums, they should be quite familiar with regards to the harms. But merely knowing about the harms does not translate to rebooting success. To take an example, many doctors know about the harms from smoking, one can say that they know it better than anybody. Everyday they come into contact with many sufferers, but the doctor himself has a strong addiction to smoking and is unable to quit on his own. Therefore, knowing about the harms alone is not enough. Rebooting is learning, one must reboot professionally, of course, one should be successful in rebooting, one must have a sufficiently deep understanding of the harms.

In addition, a person who knows about the harm is second to the person who has personally experienced the harm. The saying goes *long illnesses give rise to an excellent doctor*. With close personal experience, one’s understanding will take a leap forward in addition to being deeper and more accurate. Many people know about the harms of smoking, it is printed on the cigarette boxes  _“smoking harms the health”_, but one is already addicted and continues to smoke with the hope of luck. In the world of smoking, this is called  _“selective blindness”_. They see the danger but miss it. Then towards the end when an operation is required, one no longer dares to smoke. By continuing to smoke one is seeking death.

People truly act after being forced to, many people are rebooting because they are forced to do so by the symptoms! The truly wise person with high enlightenment will cease to masturbate immediately upon seeing the danger. But people of medium and low realization will certainly wait until the emergence of symptoms before contemplating rebooting.

There are a lot of contents to study if one is to reboot professionally. Such as the first level, how to put a stop to sexual fantasizing. Many people have been rebooting for a long time, they still do not know how to guard themselves against sexual fantasizing, they are still helpless towards it. To be successful in rebooting is impossible under such a circumstance.

After having passed the level of sexual fantasizing, one still needs to have a correct interpretation and understanding of the various issues that arise during the rebooting process. One must also understand how to control one’s own mood. After having entered the rebooting stabilization period, one still needs to maintain a high degree of vigilance and alertness at all times. Only in this way is there hope for a successful reboot.

Below I have summarized 15 key points for rebooting success:

1.  Deeply understand the harm.
    
2.  Deeply experience the harm  _(It is even easier to succeed with experience, the determination will also be greater)_.
    
3.  Mood management  _(This is unusually important, relapse due to moodiness is a very commonly seen phenomenon)_.
    
4.  Read more cases from sufferers  _(This will provide oneself with sufficient warning, allowing you to foresee into the future)_.
    
5.  Stopping sexual fantasizing  _(This is the first level of rebooting. One must memorize the rhyme for ceasing sexual fantization, putting a stop to it)_.
    
6.  Vigilant awareness  _(This is also very important. Losing the vigilance will make it easier to break the reboot)_.
    
7.  Understanding of the different forms of relapses  _(I have specifically written a season about it)_.
    
8.  Understanding the different factors which cause nocturnal emissions  _(I have also written a season about it. It is very important to control the frequency of nocturnal emissions)_.
    
9.  TCM health cultivation knowledge  _(To cultivate the health, one must cultivate the kidneys. Through studying health cultivation, one may improve the realization further. This is very favorable for the rebooting process)_.
    
10.  Understanding of the withdrawal symptoms  _(Many rookies have fallen to the withdrawal stage)_.
    
11.  Awareness of studying  _(The divine power from rebooting comes from studying. Studying raises the realization. Realization slays the temptation demon)_.
    
12.  Acts of kindness and the accumulation of virtue  _(To succeed in rebooting, one’s own spiritual nature must be raised. Pursue acts of goodness, shun acts of evil)_.
    
13.  The size of the determination, the strength of the motivation for rebooting and the length of the reboot.
    
14.  Studying habit  _(The rebooting enthusiasm will wane. It is exceedingly important to form excellent studying habits in order to allow for the constant ascension of realization, just like climbing a mountain)_.
    
15.  Rebooting notebook  _(Every brother should have a rebooting notebook. I have 10 notebooks. In them, I have noted good rebooting phrases. Note down your rebooting determination and experiences, review and learn. Increase the absorption rate from rebooting articles. Be diligent in thinking, the growth in realization will be fast in this way)_.
    

**Rebooting success = high realization + strong vigilance.**

Strictly speaking, the awareness for vigilance also belongs to realization. It is mentioned separately in order to emphasize its importance. One sentence, in order to be successful at rebooting, one must constantly raise realization. Once realization has reached its mark, the demon can naturally be slain. It is more important than anything to allow for the continuous increase of realization. All of the 15 points that I have summarized can all be encapsulated in the said formula.

Having been with the rebooting forums for so long, the realization of many brothers has risen during this time. Many people have passed the 100 days barrier, quite a few have passed the half year barrier. Many brothers have persisted in rebooting and in health cultivation. The state of their health has seen big changes, their Spirit has recovered a great deal. However, the recovery of the body is a systematic process because many brothers have had a long history of sustaining injuries to their essences. There will, therefore, be a procedure for complete recovery, one must be patient.

With an essence damaging history of over 10 years, the time for recovery is basically counted by the year. Of course, many people have naturally weak constitutions and cannot afford to masturbate. For these people, masturbating for 2 years will result in a whole host of symptoms. The recovery time for this group will also be quite long. Normally, however, by rebooting and cultivating the health for 3 months, adverse bodily symptoms will reduce quite a lot. If one is adept at health cultivation, the time for recovery will be even faster.

Lastly, I will again emphasize on putting a stop to sexual fantasizing. If a person is able to conquer sexual fantasizing, then his rebooting streak will greatly increase. Sexual fantasizing is like a tiger that is blocking the path. It more closely resembles a hard question on an exam. If the rebooting exam has a total of 100 points, then the hard question of sexual fantasizing will take up 50 points. Because many people are not able to conquer sexual fantasizing, it has to lead to their repeated failures to reboot. Memory has failed them and they are helpless against sexual fantasizing.

To win over sexual fantasizing, on one hand, one needs to constantly increase the realization through studying. On the other hand, one needs to have good methods. The method is rhymes to stopping sexual fantizations, one must memorize them by heart: Thought arise, follow not. Thought arise, be aware. Once aware, it is naught.

Firmly control one’s thoughts, guard against the assault from sexual fantasizing, enabling real-time protection for one’s brain. When a fantasy arises, immediately seek and destroy, never compromise, never hesitate. Speed, brutalness and ruthlessness are treasured here. Men should be a bit harsher towards themselves. If you are not ruthless towards yourself, then you are pampering yourself, you are destroying yourself! Fate will then be very cruel to you.
