# Sexual fantization terminator, conquering the love for fetishes, phobia

## Foreword

### Fight the temptation demon

The rebooting forums are progressing faster. Lots of newcomers are pouring in, this is a good thing. The rebooting forums are in need of new blood as this will propel more people to reboot. But when I look at the posts made by many newcomers, many of them have actually not gotten into rebooting. They are still remaining on the stage of brute force rebooting. When they relapse they blame on their lack of willpower. If one places the cause of relapse on the lack of willpower, then one cannot ever get rid of the addiction. One must recognize the importance of studying. Studying raises the realization, realization conquers the temptation demon. Relying on willpower alone will surely result in failure.

To be successful in rebooting one must be persistent in studying and in raising the level of realization. Pick up the mental weapon of rebooting articles and properly arm the brain. Do not attribute everything to willpower when relapse takes place, one cannot successfully reboot in 100 years by acting that way.

Some brothers may say, why do I still relapse despite having studied? My answer is this: the realization has yet to arrive. Raising the realization is a continuous process, you will not successfully reboot by just having read a couple of rebooting articles. As rebooting is a learning, you must constantly study all aspects of it. One needs to combine study with practical experience, learn from the mistakes in relapses, write down more experiences, rehearse what you have learned in order to learn new things. The realization will continue to increase in this way and in time you will have the strength to prevail against the big boss temptation demon. If you don’t study, on the other hand, you will forever remain a rebooting rookie, forever abused by the temptation demon without any strength to fight back.

When rebooting, you must be clear on who your enemy is! Many people have rebooted for a long time without knowing who the enemy is! In reality, the enemy is your own temptation demon. Some people will ask, what is the temptation demon? Actually, it is very easy to explain the temptation demon. In plain words, it is the thought to indulge and the impulse to be depraved. People have this inclination for self-destruction due to the ignorance belonging to a tender age. In the beginning, many people will not think that this is something bad, but when the symptoms appear they start to regret.

Rebooting is for one goal only: defeat the temptation demon! The temptation demon is like an animal, the wild horse. You must learn how to tame this wild horse and not let it pull you around. If you are unable to conquer the temptation demon, then you are the slave to desire. Sooner or later you will be tangled up in symptoms. To conquer the temptation demon there is but one path, and that is to increase the realization through studying. A high level of realization is able to vanquish the temptation demon.

Many senior brothers have already deeply realized the importance of studying. You will see that when senior brothers are replying to rookies, they will all mention studying more classical articles. To give an example, you don’t study and you will forever remain at grade 1 elementary school level. If you constantly persist in studying, then your level and realization will continuously rise, you will be able to reach the university or the PhD level. If you don’t study, in the area of rebooting you will forever be at the beginner’s level, forever unable to contend with the big boss temptation demon.

My advice to rookies is: study more, summarize more, take more notes, level properly! Many brothers have relied on studying to break the 100 days barrier, even for half a year and over 1 year. There is no other way than to rely on studying to raise the level of realization. No matter the strength of determination, without the awareness to study it is still a heap of garbage. 3 minutes of enthusiasm will not make a successful reboot. One must form an excellent habit to study, allowing the realization to sustain its ascend is the way of the king.

## The importance of maintaining vigilance after relapse

Lastly, some brothers have told me after they have relapsed, they have only thought about the importance of maintaining vigilance after relapse. Some other brothers relapse due to their emotions following an argument with the parents. The rebooting forum nowadays is very open-minded, relapse is not at all a taboo subject. At the same time, it is the hope of the rebooting forums that after relapses, brothers properly summarize and introspect in order to increase their level of the reboot. The saying goes; learn from one’s own mistakes. The tuition fee for relapsing in terms of essence is not to be paid in vain. After a relapse, one needs to properly summarize the lessons, you will reboot better in this way!

Maintaining vigilance is unusually important, successful reboot = high realization + high vigilance. The antelope that loses vigilance will be eaten by the leopard. In the same principle, the brother who loses vigilance will be eaten by the temptation demon. In every day of the reboot, one needs to maintain a high level of vigilance, constantly guarding oneself, especially with regards to sexual fantization. Because many brothers lack personal experience, they may not deeply comprehend my articles after having read them.
I have since repeatedly mentioned the importance of maintaining vigilance. Although many people have read it, it does not resonate with them. Until he has relapsed will he suddenly realize the importance of staying vigilant. After that, his level of vigilance awareness will go up by a lot, because he has personally experienced it, he has tasted the loss.

Experience is emphasized in the rebooting process. Without the experience and the awareness to introspect, it is very difficult to reboot successfully. Due to adverse emotions, it has induced relapse for some brothers, I have specifically summarized this type of relapse in a previous article. It is critical to properly manage one’s mood. Once you have learned to properly manage your mood, you will be able to reboot for longer and in a more stable fashion.

There is a saying in the stock market that says: “Because you are a first class loser, therefore you are a first class winner.” What does first class loser mean? The first class loser will be able to summarize lessons from failures, constantly improving oneself. It works the same way in the arena of rebooting, you are a first class relapser, therefore you’ll be able to become a first-class rebooting winner.

One should not remain idle after relapsing, you must be able to obtain lessons from this relapse in order to reboot better next time. Constantly summarizing, studying and the realization will increase rapidly, a successful reboot will not be far away. There are only 2 results in rebooting, either you conquer the temptation demon or it conquers you!!!

## About the rebooting forum promotion

I will again talk about the rebooting forum promotion. Promotional efforts are indispensable in the constant growth of a rebooting forum. Compared to before, the rebooting forum is developing at a faster pace. Of course, it is inseparable from the self-initiated promotional effort displayed by the brothers. After becoming a person of realization in the rebooting forums, many brothers would go out there and spread the word. They would promote in their own social circles. For instance, some brothers would promote on Mop, Tianya Club and Renren. By spreading the word in this fashion you are actually doing an act of kindness and accumulating virtue while reinforcing your own positive energy. You are also changing the fate of other people.

Quite a few brothers who have come to the rebooting forums would all silently thank “that person”. That person is actually a person who has been promoting on other forums. Promotion may very well lead to misunderstanding but it would also save a bunch of people. The people who are able to become awakened all have a thick abundance of good karma. Do not argue back with the people who curse at you or misunderstands you, it is enough to stop there. Those who understand will understand, those who do not understand will repent in the future.

The method to which some brothers promote is even more extreme. They would only post for the purpose of promotion, they would never follow threads. In this way, they are able to avoid arguments with other people. Benevolent threads are posted for the eyes of those who have been brought together by fate. Other people would not understand the post even if they have read them.

Just like Master Hsuan Hua’s saying: “Those with great virtue and kindness will able to meet, those without will not comprehend.” To not understand is fine, in the practical work of promotion it is very common to get cursed at. We should pay attention to strategy when promoting, one need to learn to steer clear and that argument is not necessary. Learning to steer clear and that arguing is not necessary, this in order so that our hearts do not become disturbed. The previous thread owner Mayan has a good way of promoting through posting flyers. One may post flyers in everyday life or in discussion forums. I think bulletin board at universities is a good option. By printing out a few flyers and posting them yourself, there is the chance of awakening many people. This is an act of kindness. In the future, there will be many people thanking you quietly.

## Health cultivation during winter

It is winter right now, quite many brothers are reporting repeating of symptoms or discomforts in the body. Winter is tinted by cold winds of snow and rain, the weather itself easily causes illnesses. If it is combined with relapses or nocturnal emissions, then repeated symptoms will easily appear on the body. Ma Junren has once said, when Tibetan mastiffs mate once, they are unable to recuperate for a couple of months. Actually, humans are the same, especially when ejaculating during the winter is even harder to recover from.

According to my research, the chances of emerging symptoms due to relapses in the winter is vastly higher compared to other seasons. The plants are withered during the winter, insects are frozen, it is the season for concealment for the many species in nature. TCM considers winter to be the time for the inner concealment of the Yang qi. Health cultivation during the winter advocates “maintaining the Yang qi”, “cultivating the kidneys and avoiding cold”.

During winter, we cannot afford any injuries. I advise everybody to emphasize cultivation, to practice health cultivation exercises regularly, one may also increase the efforts in treating the diet. Exercise moderately, avoid excessive sweating. Movement raises Yang and is favorable towards raising Yang qi. Maintain an optimistic and a cheerful mood, happiness raises the Yang. However, do not become overly happy, laugh excessively or it will damage the heart qi. In addition, kindness raises the Yang. Do more good things, come in contact with more active and positive news will be favorable towards raising the level of the Yang qi. The aforementioned is what TCM calls the 3 Yang that opens up longevity.

Lately, a brother has shared the status of his hair recovery, the thread is called [hair has become denser, there is a picture to prove it]. Those brothers who are troubled by the loss of hair may make a search in the forums and increase their self-confidence. I have mentioned the issue of hair loss on numerous occasions. Hair loss due to purely kidney deficiency has the chance to recover to normal through persistent rebooting and health cultivation. If you have male balding or it runs in the family, then it will be more difficult to recover. But no matter the case, the quality of the hair will improve by properly persisting in rebooting and cultivating the health. At the very least, it will be much better compared to before.

We will enter the main topic in the below:

In this season we will talk about the sexual fantization terminator, conquering an addiction to fetishes and phobia in detail:

## The sexual fantization terminator

I have already covered how to stop sexual fantization in season 17 in detail. However, many people are still unable to stop sexual fantization, they are still unable to control themselves. In chatting with many brothers, they have all mentioned: “I have no ways in controlling my thoughts”. To become successful in rebooting, however, one must be able to cut out sexual fantization, one must learn to control it. If you are able to properly do the thought work of stopping sexual fantization, then you have succeeded halfway. You must monitor your thoughts at all times, when the thought of sexual fantasy comes up you must immediately put a stop to it.

All successful rebooters are able to harshly and quickly put a stop to sexual fantasies, it is entirely overwhelming and strictly impartial. The thought is not to be feared, a late realization is to be feared. Some brothers react too slowly, they have already been fantasizing for over 10 seconds before they suddenly realize what they are doing. At this time, the spark of sexual fantization has already been burning and it is increasingly difficult to put it out. Sexual fantization is like fire, the earlier it is extinguished, the easier it is to control it. Otherwise, by waiting until the prairie fire becomes powerful, then it is very difficult to control it. Therefore, in cutting out sexual fantization, earliness, promptness, and harshness are qualities to be treasured.

The pattern to stop sexual fantization: the longer sexual fantization has been going on, the more difficult it is to put a stop to it; the shorter the time of sexual fantization, the easier it is to cut it out.

My recommended time to cut out sexual fantization is 1 second. If the time is exceeded, then you are already late in trying to cut it out. You must realize it first and ruthlessly get rid of sexual fantization just when it is showing its head.

The 3 principles in stopping sexual fantization:

No hesitation
No indulgence
No compromise
The attitude in treating sexual fantization: zero tolerance! You stand, I fall. I stand, you fall!

The rhyme for cutting out sexual fantization: Thought arises, cut out. Thought arise, follow not. Thought arise, be aware. Once aware, it is naught. Memorize this rhyme for stopping sexual fantization and one is able to conquer it. Many brothers know about this rhyme but doesn’t know how to use it. Many brothers think that there are other ways of cutting out sexual fantasies, actually, this rhyme is the best method. By fully grasping this rhyme, one is able to completely conquer sexual fantization. (Translator’s note: for obvious reasons, this rhyme will have a better flow in its original language. The reader is encouraged to come up with own rhymes for the purpose of stopping sexual fantization)

Many people are aware of the above rhyme but don’t know how to use it. In this season, I will talk about the method of its usage with everybody. Once the rhyme is at hand, my advice is to recite it several hundred times or even over a thousand times, whenever there is time, recite this rhyme. To what degree should one recite the rhyme? One needs to constantly repeat it until it becomes a conditional reflex.

When sexual fantasies arise, one does not need to think, the thought is directly cut off. This principle is like the anti-virus program found on computers. When the virus appears, it is automatically killed without the brain needs to think, it is done entirely automatically. And to achieve this state, one must go through a large number of repetitions, repeat and repeat again. Once a certain amount of repetitions is met, you will notice that it is actually this easy to stop sexual fantization, a mental struggle is not needed at all. This is how I have achieved it, this is how I have conquered sexual fantization. As your skill in stopping sexual fantization is being perfected, you will notice that you are fantasizing less because sexual fantasies fear you.

Stopping sexual fantization is like a skill. Mastery of this skill and the correct application of it will make stopping sexual fantization an easy task. The so-called thousand tricks are inferior to a skilled trick. The person who has perfected the use of the sexual fantization stopping rhyme will no longer be bothered by it. This is because he can already complete conquering sexual fantazation.

I recommend brothers to repeat the aforementioned rhyme for at least 500 times per day. When you feel that it has become a conditional reflex, then you have arrived at your destination.

Now that conditional reflex has been mentioned, I think that many brothers should have had a bit of experience. Because many people have constantly been exposed to the contents of evil debauchery, the result is that they have already formed strong conditional reflexes where the least bit of stimulation will excite their automatic reaction. For example, some brother has told me that he would leak while reading a post. Upon reading the word “masturbate” he would leak, he has already arrived at such a place. Actually, when he is looking at evil debauchery contents, he is constantly repeating, at last, the repetitions would lead to the formation of automatic response, he has no way of controlling himself.

When a person’s debauchery has formed into a conditional response, the reality is that the poison already sits very deeply, the psychological addiction is already very heavy. In order to escape from this monstrous psychological cycle, one must make more repentance, make a big determination to quit. Lastly, the person needs to constantly and repeatedly infuse righteousness. Study more rebooting articles to raise the realization and slowly turn the awareness around. In this way, rebooting success can be attained.

There are 2 types of temptation demons:

Sexual fantization form.
The inciting form, inciting you to try it out.
As for the sexual fantization form, many senior brothers have a high level of vigilance awareness. But many people have their guards down with respect to the inciting form. This is especially true after one has read harmlessness theories. When their rebooting foundation has been shaken. During this time, the incitement by the temptation demon will easily succeed.

For example, some people would have the following thought: it is fine to masturbate once, one last time. The temptation demon wouldn’t at times tempt you directly, instead, it will incite you to indulge, just like a criminal boss, changing ways to make you break the reboot. If you are very conscious of your sexual ability, then the temptation demon will incite you to test. If you have the thought to test your determination, this is actually the temptation demon inciting you to relapse.

As to the various problems that one encounters during the rebooting process, we should hold a correct understanding and then constantly guard ourselves against the temptation demon at all times. No matter if it applies to sexual fantization or the inciting form, the vigilance mindset should be maintained at all times. The rebooting position must be firm and immovable! Immovable like the mountain! No matter what the heart temptation is saying, I won’t listen, I will not relapse! Just like when the traitor is tempting the revolutionary martyr to surrender, the reply from the martyr is a spit of saliva! Our rebooting efforts should have the same spirit and determination as the martyr!

Actually, our rhyme for stopping sexual fantization is not only effective against sexual fantization, but it is also effective against other forms of improper thoughts. Although many brothers have basically ceased to sexual fantasize, they are unable to control improper thoughts. In this case, one may also control improper thoughts through the use of the mentioned rhyme.

Rebooting is about control versus to be controlled. One cannot hope to succeed if the temptation demon is in control, you must allow yourself to be a person of control and then firmly control your thoughts! Watch your own thoughts! Every day in the rebooting process should be like treading on thin ice, one cannot be careless or relax the guard.

Everybody should emphasize the rhyme for stopping sexual fantazation, use it properly, constantly repeat it in order to form the conditioned reflex! Conditioned reflex needs to be constantly reinforced, if it is not reinforced during a period, then it will start to recede. Therefore, we should frequently commit this rhyme into memory and keep it in the level of conditioned reflex.

This rhyme is a treasure, hopefully, you are somebody who recognizes treasures. For heaven’s sake, do not beg for food when you are already holding a bowl made of gold, do not mistake diamonds for glass.

## About the love for fetishes

In the below let’s talk about the love for fetishes.

Some brother hoped that I would talk about the love towards fetishes, he told me that it is the reason for all his relapses. For instance, the love for women’s things, a particular body part of women. When one develops the love for fetishes, addiction has taken place. Such an inclination is similar to addiction to alcohol, smoking, medicine, drugs, the internet, and gambling etc. All of the mentioned is a form of addictive behavior. Of course, masturbation is in itself a behavior of addiction.

People with these forms of fetishes may use patikulamanasikara to pull oneself back to the course of normalcy. Otherwise, having been subjected to poisons of such a degree, it will be tremendously difficult to reboot successfully. Previously, a brother told me that he liked to collect videos. He said that he has several hundred GB of them, he later determined to delete them because he knows that these videos are the very rocks that are tied to his body, sinking him to hell, they must be cast away. Other brothers have serious fetishes towards stockings, they have arrived at the stage where they are no longer able to pull themselves out and take control of their acts. Rebooting for these brothers are also more difficult compared to ordinary brothers.

In reality, everybody has their own inclinations of fondness, only that some are lightly addicted, some medium addicted and others are heavily addicted. While deeply trapped into these kinds of behavior, they would even collect things or steal female items, they have in no ways of controlling themselves. If one is heavy inflicted, I advise to go see a psychologist and listen to professional advice, this will make the process of adjustment easier.

The person who loves fetishes must have the determination and confidence to correct their own abnormal behavior. make more repentances, intensify the cultivation of virtue, study more traditional culture in order to raise one’s level of virtue. Proactively participate in social activities which would benefit the body and the mind. Public welfare activities are even better.

Do not come into contact with adverse stimulation. In this internet day of age, there are adverse stimulations everywhere. Therefore, one must learn how to control one’s thoughts, watch one’s thoughts. Rhymes for ceasing sexual fantization can also be used to control thoughts about fetishes. Once you are able to control your thoughts, correcting the love for fetishes will no longer be difficult. The only problem is the inability to control one’s thoughts and instead falling into the control of the temptation demon. The adjustment will surely be a difficult task under such cases.

The psychological aspect of curing the love for fetishes normally includes:

Becoming aware of the treatment methods, undergoing systematic education (studying the correct view towards sex)
The disgust treatment method, target repulsion towards an object (establishing the feel of disgust)
Rubber band treatment method (giving out light punishment)
Social treatment method (changing one’s personality)
“Stimulation - Reaction”. In reality, in rebooting we are cultivating our reaction. When facing temptatious stimulation, our reaction should not be of fondness and addiction. On the other hand, we should deeply realize the harm that evil debauchery brings to the body and mind. We then should employ an attitude of exclusion, refusal or disgust and through the constant studies of rebooting articles, enabling us to adjust our thought awareness. In this way, will there be the hope of making a successful reboot. As for the people who have a love for fetishes, studying is the prerequisite to correction. Only by deeply realizing the harm can one make a big determination to quit.

Some brothers might worry that the so-called disgust treatment method will affect their post-marital sex life, worrying that they would lose interest towards the opposite sex, developing sexual indifference and thus affecting the relationship with their wife. Actually, one does not have to worry the least bit, this is only a method of treatment which allows you to return to the path of normalcy. The final goal is to let you establish a correct view towards sex, in learning to control one’s thoughts and desires.

## About phobia

Lastly, let’s talk about phobia.

After having read cases from countless brothers, many of them have had the inclination of becoming timider. This is actually intricately connected with the kidneys. In serious cases, brothers would develop phobias. Examples are social phobia, cancer phobia, claustrophobia, agoraphobia, ..etc. Some brothers are afraid of the light, living like a pitiful bug in a dark corner. Many brothers would lament that they were not like this previously. The previous selves were very confident and optimistic. Ever since becoming addicted to masturbation, they have step by step become more afraid.

“A person has 5 organs which correspond to the 5 emotions, these are happiness, sadness, worry, fear and thought.”

— [Inner Canons of the Yellow Emperor]

The corresponding relationship between emotions and the 5 organs are: happiness to the heart, worry to the liver, thought to the spleen, sadness to the lungs and fear to the kidneys. The kidneys govern fright. Fright, in turn, will again damage the kidneys. It is a common phenomenon for kidney deficient people to become more fearful.

I used to be like this, I had severe social phobia and a heavy tendency towards hypochondria. Those days were a period of complete darkness, I would fear out of no reason. Thinking about it now it seems unbelievable. Afterward, through rebooting and health cultivation, my confidence has returned, I no longer fear the least bit, the feeling is completely different. Last time when replying to a thread, a brother had similar experiences, following a period of rebooting, he was immediately valiant and full of vigor. His confidence has returned along with his impulse, the previously wretched and scared self-had all but disappeared.

When one has a phobia and visits the Western medicine doctor, it is often treated as neurosis or psychological illness. Naturally, it will be effective to some degree. If you go to the traditional Chinese doctor, it will be treated as disordered functioning of the internal organs. Through treatment of the internal organs by Chinese herbal medicine, fright will then disappear. One should say that each way of treatment has its own merits. But as sufferers, we must recognize the importance in rebooting and health cultivation. Otherwise, by undergoing treatment and masturbating simultaneously, even the best doctor will have a hard time curing you.

If your condition is not serious, there is certainly a chance to get well without using medicines given at least half a year of rebooting and health cultivation. When the kidney qi is abundant, ten thousand evils are extinguished. Though I need to remind everybody that during the recovery period, repeated symptoms will easily arise. Therefore, we should emphasize health cultivation in order to reduce the worries that have been brought forth by these symptoms.

Many people become confused when phobias arise, they wonder if it is a problem with the mind or the body. If you understand topics of health cultivation, then you will know that kidney deficiency precedes the tendency of feeling frightened, in serious cases, there will be phobias. When you undergo active treatment through rebooting and health cultivation, phobias will naturally disappear when your confidence returns.

If you do not understand this concept, then it is like entering a maze. The sufferer most likely will think like this: what is the problem, is the problem really with my mind? Since it is a problem of the mind, why am I not cured? He has never considered that the phobia is connected with masturbation. This is because he is ignorant of medical knowledge. Therefore, in order to completely recover from phobias, one must first be reasonable, understand the principle, find the right cause and then make efforts and one will succeed. Otherwise, while unable to understand the cause, one will spend a lifetime wandering and struggling in the maze of phobias.

What is more of a pity is that family members have no ways of understanding his fears, they all think that the problem is with his mind. Actually, the source of the problem is with masturbation. Masturbation causes the five internal organs to function disorderly. Continued masturbation will cause changes in the mood and the psyche. Kidney deficiency not only gives rise to symptoms in the body, many people have actually ignored its psychological symptoms. When the kidneys are deficient, a person easily becomes agitated and easy to anger, there is also a high chance of developing cowardly tendencies.

Once this principle is understood, recovering from phobias will be easy to handle. One phrase: walk in the opposite direction! Don’t do things which would result in injuries to the kidneys, masturbation must be cut out with determination. Do not stay up late and sit for long durations, one should actively exercise. One may also take up health cultivation practices. In summary, one should do more activities that are oriented towards health cultivation and reduce kidney damaging activities to zero. By persisting this way for at least half a year, phobias will be completely cured.

I have been cured after having understood the principles. At the time, I had taken a lot of medicines without effect. Medicines would only provide temporary alleviation, one may easily become dependent on medicines after a period of medication. Therefore, I have placed the emphasis to recovery onto rebooting and health cultivation, especially on health cultivation. I have practiced standing and sitting meditation, Eight Brocade exercise, Six Healing Sounds, I went to bed before 11 pm, got up and moved about for every 40 minutes of sitting down and avoided sitting for long durations. The illness disappeared slowly like threads of silk.

On the other hand, I’m a sensible person who is persistent, this is why I was able to finally recover completely. As long as you are sensible, have the awareness towards rebooting and health cultivation, is perseverant, then you will be able to recover fully.

Do not think that you cannot recover from a phobia, I have recovered from it. I have conveyed my experiences to brothers in sickness, as long as you have truly obtained understanding, you will be able to recover. One needs to look to hope, give oneself more of positive and active suggestions, as long as you keep persevering, symptoms will gradually disappear. That optimistic and confidence feeling will once again enter your body, you will reclaim that lost beauty.

## Books recommendation

In this season I will continue to recommend 3 books:

[How To See & Read The Aura], this book allowed me to find out what is aura and the mystery of an aura. Aura does indeed exist, but it is very subtle. Through rebooting and cultivation, the aura of a person can undoubtedly become strengthened. When the aura is great in strength, the fate of a person will slowly change. Being addicted to masturbation will weaken a person’s aura, giving out a filthy feeling, wretchedness, strengthlessness, optimistic and unhealthy. The feeling of aura will at first glance leave a lasting impression for the other person. Auras have varying degrees of intensities, different colors and clarities.

Through studying this book, you will understand the mystery of aura and from there be in a better position to maintain and strengthen your aura. Aura is intimately connected with the health as well as with the actions. The kind of actions will determine the kind of aura. By masturbating, you will have the wretched aura of a masturbator. By rebooting, you will have the righteous aura of a rebooter. I recommend that everyone may take a read at this book. Although it is not a thick book, it is very inspirational.

[遵生八笺], this is a great work in the science of ancient Chinese health cultivation, the number one classic of the famous scholar of the Ming dynasty named 高濂撰. The version that I bought is the translated text into everyday language. The health cultivation knowledge contained in this book is very vast. When first reading this book opened my eyes. The level of essence preservation in health cultivation that has been achieved by our ancestors is extremely advanced. It can be said that it is an accumulation of experiences through thousands of years. We should absorb the knowledge of our forefathers and master the path of health cultivation.

Brothers who only reboot without cultivating the health will recover very slowly, repeated symptoms will be likely. It is crucial to understand health cultivation, I have always stressed the importance of health cultivation. The books that I have read about health cultivation nowadays are already very numerous, included among them are professional books on TCM. Basically in every book, the importance of cutting out sexual debauchery and the preservation of essences is emphasized. If you are deeply versed in TCM health cultivation, it will be very beneficial towards the rebooting process. It is a major helping force towards rebooting!

[张锡纯医案], 张锡纯, one of the representative individuals who is well learned in both TCM and Western medicine, a leading scholar in TCM close to the modern time. I like this book a great deal. A person who indulges in sexual debauchery will suffer many illnesses. There are many inducing factors, the seven emotional states lead to sickness, the six desires damages the body. “wind, cold, heat, moist, dry, fire” will induce a person to become sick. Fatigue and dietary factors will also induce sickness. Reading more medical cases will benefit the advancement of realization in TCM health cultivation. Once you have a strong realization in health cultivation, then the chances of catching illnesses will decrease. Health cultivation is a learning, maintain yourself well. One may also share knowledge with friends and family.
