# Refuting the harmlessness in moderation theory by sexologists

## Fluid during sexual excitement {-}

Recently, a friend told me that the fluid that flows out during sexual excitement is not the prostatic fluid, but the urethral gland fluid.

In fact, a question concerning this was mentioned to me six months ago. As to whether it is the prostate fluid or the urethral gland fluid, it is controversial. Some brothers think that it is prostatic fluid, while others think it is urethral gland fluid. Some doctors think it is a mixture of prostatic fluid and urethral gland fluid. I myself agree with the view of the mixture. Because the prostate is filled with blood during sexual excitement, it will secrete a small amount of prostatic fluid which then enters the urethra, this gets mixed with the urethra glandular fluid and the mixture is formed.

When I wrote articles before, I used to write prostatic fluid. Later I changed it to  _“prostatic fluid or urethral gland fluid”_. Brothers who often read my articles know about this. I will not mention this issue again in the future. When you see the urethral gland fluid being mentioned in one article, you will think that the person who says it is prostatic fluid is wrong. However, if you come across an article that mentions that it is prostatic fluid, you may assume that person is correct.

Actually, it is not important whether it is the prostatic fluid or the urethral gland fluid that is following out, repeated symptoms will be caused by the outflow regardless of which fluid it is. Therefore, we must control sexual fantasizing and try to avoid such a situation. In addition, when answering a question I will normally refer to it as prostatic fluid. I’m used to this expression and so I will stick to it, I ask for everybody’s understanding.

We will enter into the main topic below.

## The harmlessness theory in moderation by sexologists {-}

Regarding the harmlessness theory in moderation, I have already criticized it many times in my article. This time, based on the advice of a certain brother, I once again talk about it thoroughly and in detail. This time, I will quote from some well-known sexologists to use as a reference. I will also quote from some cases to explain my point of view. I will not resort to personal attacks in this article but I will just talk about my point of view, judging the matter where it stands in order to set the record straight. I respect these sexologists but my views differ from theirs. In writing this article, I take the position of an in-depth researcher in the topic of masturbation and a person who has thoroughly experienced the symptoms first hand.

I don’t want to get involved in battles of debate. He who is innocent has no need to prove his innocence. My only hope is that this article will bring positive inspiration to the vast majority of brothers. It is not my intention to incite an argument between everyone. As rebooters, we should be quality individuals. I do not advocate personal attacks. As rebooters, we need to pay even closer attention to doing good deeds and in the accumulation of virtue.

I will begin by quoting from the famous sexologist Ma Xiaonian:

> The so-called masturbation is a way of self-satisfaction. He can use his hands or use some bedding material. The ultimate goal is mainly to stimulate the genitals, whereby sexual satisfaction is achieved. Differences may be found in the specific approaches, a clear boundary does not necessarily need to exist. First of all, teenagers and even adults all may have very normal sexual behavior. Many people may have many misunderstandings about masturbation, thinking that masturbation will hurt the body and leave repercussions for the future. Such problems do not exist in actuality.
> 
> — Ma Xiaonian

Here is another sexologist Peng Xiaohui:

Peng Xiaohui said in a lecture at the South Normal University that if a woman resists or through the use of other means is unable to withstand the sexual assault, the last barrier is to hand over a condom in order to protect oneself to the greatest extent possible. Since then, a nickname has been added to him as the  _“Handed Professor”_. In February of this year, as a personal friend, he invited a former AV actress into the classroom to interact with the students, another nickname  _“Sex Worker”_  was added to him.

**Comment**:

These are two famous sexologists, one is a doctor and the other a teacher. I have read their articles, in particular, their attitude towards masturbation is that of harmlessness or harmless in moderation. To have such views as university professors, and then to spread these views through books and opinions to their students who do not possess much judgement, is terrible. Whatever the teacher says the student accepts. And the argument of harmlessness in moderation is indeed very confusing and has the potential to confuse a group of people. As a guide, he is really a misguider. In the area of sex education, both of these people are authoritative figures, but we should not blindly trust in authority. It is necessary to reason whether or not the authoritative ways of thinking are aligned with facts, if not, then they are wrong. Wrong is wrong, whether you are a professor or not.

The ideology that these two people harbor with regards to sex education comes from foreign research in fact. There are many misconceptions and blind spots in those foreign studies, and it does not explain the stark ground reality. Especially on the issue of masturbation, the mistakes are outrageous. They are very sure about the benefits of masturbation. They even think that masturbation has a certain therapeutic effect. Not only are there no downside but the upside is great, the approval of pleasure is very high.

But what is the actual situation? How many people have had their health ruined due to masturbation? I dare ask, have these two experts investigated? Have they seen it? Have you seen the cases made by the victims? Are all the symptoms of a masturbator only a product of imagination? Without having investigated, one does not have the right to voice opinions. Such opinions have a high chance to be subjective speculation, completely ungrounded in reality.

The previous me used to be the same as many ignorant brothers, blindly believing in the opinions of experts. Later on, I discovered during my research that many people did not think much after masturbation, nor did they feel guilty, but they ran into many symptoms regardless. The so-called imagined symptoms postulated by the experts is an extremely misleading opinion. Who knows how many youths have been harmed by this view. If a person has a little bit of TCM health cultivation knowledge, he will know that masturbation will damage the kidneys. It is after the kidneys have been injured that symptoms come out, the symptoms are not a product of imagination. It is very incredible that dignified professors would actually say that masturbation is harmless, not only harmless but also positive.

Later, I understood why the professor said this. It is because they have been brainwashed by the Western harmlessness theories, completely ignoring basic TCM health cultivation knowledge, believing completely in the Western point of view  _(Translator’s note: While Soaring Eagle often makes the distinction between East and West, it is my sincere belief that he is not attempting to alienate one camp from the other. The reader should keep in mind the issue at hand which is PMO, energy should not be wasted on the debate over which school of medicine is superior to the other)_. This is a kind of tragedy; directly convinced by the Western point of view without having gone through thorough investigation and research. What is more sorrowful is the spreading of these false theories to the younger generation by the experts. I would like to say something with a slight undertone of mockery: I hope these expert professors would quickly wake up and not mislead another generation of youth, they cannot afford to get injured!

If the experts are still misleading the youth in this way, should I suspect you are supported by private hospitals? Masturbation causes prostatitis and then private hospitals generate income. It would seem that Mr. Ma Xiaonian is a consultant for private hospitals.

Let me talk about my argument below:

My views are based on my own in-depth research. I have read more than 5000 cases. To this day, I am still reading cases in the rebooting forums. I have chatted with over a thousand patients, and I’m a sufferer and have experienced the symptoms first hand. I think it is necessary for me to tell the truth. In addition, I have to say something very responsible. That is: the truth is in the rebooting forums. The truth is in the various discussion forums dedicated to quitting PMO. The truth is found in the minds of conscience doctors. The truth is absolutely not found in the hands of the so-called experts.

**Case 1:**

I am 19 years old, I started to masturbate during the 2nd year of middle school. Until last year, my sexual desire had been very strong, I basically masturbated once every day. On several occasions I masturbated 5-6 times in a row. Recently, I felt that my energy level was extremely low, I have insomnia, frequent urination, and incontinence. Recently I came upon the rebooting forums and had an epiphany. I rebooted for 5 days, the dark circles around my eyes were alleviated and the frequent urination was cured. But when going to bed today, while looking at the wallpaper on my computer, I couldn’t hold it and so I masturbated twice. It feels like all my previous efforts have gone into the drain. What I want to ask is, can I recover if I quit for a long time?

**Analysis:**

Everyone pay attention to the 2 words: *until recently*. The desire was still very strong last year, it was actually an expression of hyperactivity in the Yang due to Ying deficiency. This has been going on for over a year, then the symptoms appeared this year. Do you know what the experts will say when they see this case? You have imagined the symptoms, it’s OK to continue masturbation. Experts have a tendency: they like to talk about sexual liberation, they think that the the past is too confined and feudal. That society should be as open as Western society. What they don’t know is that foreign countries have realized the evil fruits of sexual liberation, they have begun to advocate ascetic education. Chinese people always think that everything foreign is good, actually, lots of these are Western garbage thoughts.

Some sexologists would even say: When there is desire it should be released, this is human instinct. Don’t hold it in as it is bad for the body and the mind. When first listening to this argument, one would think that it is very reasonable and correct. But if one is a senior brother, one would definitely feel that this is ridiculous. This case is a good rebuttal. Once you are addicted, or have entered the state of hyperactivity in the Yang due to Ying deficiency, many people have a high rate of masturbation, multiple times every day even. Should desire really be liberated once it is present? Shouldn’t we learn to control our own desires? When masturbation is so highly addictive, sexologists still argue that we should masturbation whenever we have a desire, this is simply pushing people into the fire pit.

**Case 2:**

It is like this. It is difficult to fall asleep for N days in a row. I used to have this situation when I was 14 or 15 years old. I used to be a masturbation madman. Now I realize the seriousness of the situation. I started to quit. I guess that insomnia is caused by masturbation. Lately, I’m constantly thinking about ways to make up for the deficit. Last night, I just wanted to hit the wall with my head in order to pass out! At least this also counts as falling asleep…

**Analysis:**

This case is actually neurasthenia caused by masturbation. Chinese medicine: *the kidneys are connected to the brain*. Masturbation will damage the brain and the nerves.

You can understand this principle by reading more cases or by direct experiences.

**Case 3:**

Graduated with a Master’s degree, originally with a bright future but stopped in my tracks while climbing towards the peak of my career. It’s not that I don’t work hard, but the symptoms are too serious, like a pair of shackles holding me firm, leaving me without any means to move forward. Now I can but live on in degradation! The person that I loved the most has left me, my career has stagnated due to symptoms as a result of illnesses. I have been asking for medical advice everywhere without seeing any improvements. The vile habit of masturbation from previous times refuses to go away. Every day I live in this world like the walking dead! The average person will not understand how tormenting the disease is.

First of all, frequent urination will make you want to commit suicide. When it was the most severe, there was an urge to urinate every 5 minutes. The lower abdomen is restrained and swollen. The urge to urinate will arise by applying the least amount of force. One can also say that there is always a thought to urinate, it will swell and I’m unable to sit. Secondarily, there is discomfort in the urinary tract, like something stuck in the urethra. The urinary tract feels swollen, it burns when urinating, the urine stream is flat and there is incontinence, ..etc. Soreness in the waist is a small problem in comparison!

**Analysis:**

Only when symptoms appear on the body does one know how painful they are. Lots of people who masturbate suffer from prostatitis and varicocele, premature ejaculation and impotence are also common. Can the experts still say that they are all imagined? Expert theory can only fool the masses who are not aware of the truth. Once you understand the truth, there will be a feeling of being cheated by the experts.

Among the thousands of victim cases, I have collected, they are all undoubtedly explaining one fact: the harm from masturbation is very great, it is hugely destructive towards the mind and the body. Why do sexologists avoid talking about the dangers of masturbation? Why is it that everybody knows that masturbation injures the kidneys, that many diseases are born out of weak kidneys, but sexologists do not know this rudimental health cultivation common sense?

I remember there was a sexologist who went to lecture at a university and then some students asked directly: Will masturbation lead to premature ejaculation? The sexologist answers: early leakage may also be caused by the woman. Take a look at the cleverness of the answer, he just avoids talking about the dangers of masturbation. Could it be that premature ejaculation and impotence are both  _“imagined”_? People who have a little bit of knowledge in Chinese medicine will know that when kidneys are damaged by masturbation up to a certain degree, there will be premature ejaculation and impotence. Why don’t the experts know about this principle? Why do experts blindly emphasize the many benefits to masturbation?

Even Confucius has emphasized the need to quit lust. Many famous Chinese medicine practitioners have emphasized the importance of quitting lust and the importance of essence preservation. Why do sexologists want to sing the opposite tune? Where are their hearts? You so-called expert professors, your speeches and articles are ending up in the media, you also host lectures at universities. Have you thought about when you are promoting your fallacies, what results will it have on those students who are not aware of the truth upon hearing these arguments? They will think that masturbation is very normal and continue to indulge in it. Until the body is broken, they will not necessarily know what’s going on, are you expert professors not harming people? You are killing the younger generation! You are very cunning, avoid talking about the dangers of masturbation. You really should read more victims’ cases and see what the truth in masturbation looks like. Don’t instill the foreign garbage indulgence thinking into the younger generation, here I want to say to you: expert professors, pay attention to propriety in speech! Thank you all!

Attaching a little poem:

[Truth]

I used to believe in you  
Because you are the expert  
Representing authority

Later, I came to hate you bitterly  
Because you are the expert  
Pushing me into the fire pit

At last, I’m grateful to you  
Because I came to believe in the Buddha  
Living in a grateful world

But, I must tell the truth  
This is for the younger generation  
So they are no longer harmed by you

Related literature:

Asceticism sweeps the United States

[Beijing Youth Daily]

Teaching young people in the United States how to abstain from sex, would have sounded unbelievable to people several years ago. But now it is actually on the agenda of the federal and state governments. With the support of a $500 million of public fund, hundreds of new plans are being implemented. The agenda carefully educates and warns young people to not engage in premarital sexual relations, which may cause  _“harmful consequences to the mind and the body”_, while condoms and other contraceptives are not reliable.

With the promotion of these abstinence programs, they are moving to challenge the firmly rooted American traditional education trinity - human sexuality, safe sex, and birth control. This new concept of sex causing some traditional conservatives to gladly profess that they are in the process of conquering the corrosion of the American youth caused by the sexual revolution of the 60s.

Over the past two years, the US government has funded 6,988 new  _“only abstinence”_  programs and 21 new media campaign activities. In Chicago, where teenage pregnancy rates are as high as 40%, a new course was added to schools last year where the students were taught that abstinence is the best choice.

Although formal sex education may be more effective than informal education, the long-term effects are still unclear. The latest investigations show that the previously persistently high rate of sexual activity among adolescents in the United States has begun to decline. Yet, on the other hand, up to 3 million adolescents are diagnosed with new cases of sexually transmitted diseases! Half of the new AIDS patients are under 25 years old.

Dr. Pinsky, the host of the radio program  _“Love Hotline”_  believes that abstinence is the optimal choice in maintaining the emotional health of young people. He said that most girls under the age of 18 are not prepared to accept strong emotional integration if they engage in sexual activity too early, they risk depression, pregnancy, and illness. If young people are  _“not fully developed and holders of their own autonomy”_  and sexual relationships occur, they may become emotionally attached to relationships.

## Final summary {-}

When sex is liberated and indulged in foreign countries, our country is still very conservative. When we start calling for sexual liberation and sexual indulgence, foreign countries are once again advocating asceticism. In fact, it is still better to be a bit conservative, the evil fruits of indulgences are too terrible, not to mention ruining your body but it also leads to various social problems. Our country should have its own ideas and not follow behind the developed countries, like a follower, and finally ending up with nothing. We should stick to our own route, listen to the teachings of the ancient sages, and become a Chinese person full of positive energy.

An expert is such a person; when you masturbate and your body is deteriorating by the day and you want to climb out of the masturbation trap. The expert who is standing on top of the trap kicks you back while shouting: Keep on masturbating, it’s harmless, there are even many benefits!

All these experts have overlooked one point: masturbation is highly addictive! The biggest feature is once you have popped you can’t stop! These six words are the most incisive summary of masturbation!

I will list several forms of addictions: drug addiction, addiction, internet addiction, and smoking addiction. Out of these four kinds of addictions, which one does everyone think is easiest to become hooked too. I can tell you that masturbation will never lose to drug addiction, it’s basically a one-time addiction, once you pop you can’t stop. It is hard to quit it once you have caught it!.

Why are experts not talking about the highly addictive nature of masturbation? In a phrase: the experts are too cunning! It is not ignorance but the avoidance of the topic. The expert used a very cunning word: moderation! The meaning of the word moderation is too vague because everybody has a different constitution. Therefore, no one knows where the degree for moderation is. And having become addicted, talking about moderation is absurd! Once addicted, you no longer have control. Many people have had experiences of masturbating for several days consecutively, even many times a day when evil thoughts enter the brain. A person is like a puppet under the temptation demon, it is a state of involuntariness. Many of the predecessors have wasted themselves via masturbation while subscribing to harmlessness theories. Moderation is self-deception as well as the deception of other people, one is simply looking for an excuse for indulgence.

Although some people have masturbated relatively few times, by going at it for 3-5 years, there will still be a high chance of running into symptoms. Some people are born with a poor constitution, even if the frequency is very low, there will still be lots of bodily symptoms within 2 years. The harm from masturbation is the process of a change in quantity to that of quality, the damaging effect is like a frog being slowly boiled in a pot.

Seniors friends know that sexual fantasizing is an invisible form of leakage, it is also very damaging. One is also prone to encounter symptoms by being addicted to sexual fantasizing. Do the so-called experts know these principles? What I want to ask is, do these experts have rudimentary knowledge about TCM? Have they done any in-depth research? Experts copy the Western view of harmlessness while maintaining a negative attitude towards traditional Chinese medicine. How much credibility do these experts have?

In addition, everyone can observe that many so-called experts actually have the face of an essence-wounded person, their complexion is very poor. The experts have problems with their own bodies while saying that masturbation is harmless, is this not laughable? There are so many hazards in masturbation, why can’t the experts see it? Are they trying to dodge the issue by simply stating that the symptoms are only in your imagination!?

Many brothers have all eventually said a sentence along these lines: I was harmed by harmlessness theories, and I was gravely harmed by the experts! The misleading articles make one sink ever deeper, at last, the body is full of symptoms, the suffering is beyond words.

When you read harmlessness theories, you are the laughing stock! When you believe in the experts, you are the great laughing stock.

When I write this article, it is not intended for the experts but for the majority of brothers. I hope that brothers are able to wipe open their eyes. It is extremely difficult for experts to change their opinions, do you know why? Asking them to change their opinions is tantamount to letting them slap themselves, it is tantamount to letting them smash their own billboards. Even if they realize the true issues with their views, it is not certain that they will admit fault. A brother said once that the theory of harmlessness in moderation is a conspiracy for poisoning more teenagers, I don’t want to rule out this possibility.

By listening to the voices of the victims, you will be awakened a lot. One needs to learn to speak with the help of cases, speak with the facts, the so-called experts can go meet the devil! Without rebooting, one is finished! Lack of essence precedes illnesses!
