# Revisiting the topic of relapsing and the revealed profundities of blackjack

## Foreword {-}

### 6 aspects of professional rebooting {-}

The standard for a successful reboot should be a consistent reboot for more than one year. Strict control of sexual fantasizing with little to no fantasizing and the maintenance of a high degree of vigilance. If you can enter the rebooting stabilization period within about half a year with little to no sexual fantasizing, then that also counts as a successful reboot. Although many senior brothers have been rebooting for a long time, when they at last relax their vigilance by the least bit, they immediately relapse. Even if they have been rebooting for over 2 years, a relapse can still happen. Therefore, we must remain vigilant.  **Successful reboot = high realization + strong vigilance.**  Vigilance is very important. When you relax your vigilance, you will be eaten by the temptation demon.

Traditional culture talk about the importance of quitting lust. TCM health cultivation also talks about the same topic together with essence preservation. Raising the realization in these two areas is favorable towards rebooting. But what’s more important is to reboot professionally. Some brothers are studying Chinese medicine, they are deeply aware of the harm of masturbation but still, they are unable to quit. In reality, what they are lacking is professional rebooting knowledge. Merely knowing about the harms of masturbation is far from enough. One must learn how to reboot professionally. Professional rebooting may be achieved through the 6 aspects of self-improvement stated below:

1.  Method of breaking sexual fantasizing
2.  Emotional management
3.  Controlling the frequency of nocturnal emissions
4.  Vigilance awareness
5.  Health awareness
6.  Studying awareness

### Why I’m still on the forum {-}

Some friends suggest that everyone shouldn't blindly believe me. I still agree with this point. I once said in an article that I’m not some Master, nor do I want to be a Master. I’m not in need of any blind worshipping. I’m only an ordinary brother, a senior rebooter. I’m sharing my experiences only in hopes of helping everyone, nothing more. If you praise me, I will not be proud, if you yell at me, I will not feel anger. I will always keep a humbly dedicated heart, serving everyone. If you believe in me and come to consult me, I will definitely give you my best advice. If you don’t believe me, it doesn’t matter, there are a lot of distinguished people on the rebooting forums, you may go and consult them. But blind belief in anybody is unacceptable. If you want to believe then believe in righteousness, founded on correct knowing.

Good rebooting articles can give you a lot of inspiration and revelations, but the final path needs to be walked by you through independent thinking and summarizing. The Master leads you to the door, the rest is up to you. Once you have entered the door to rebooting, you need to rely on your own labor to cultivate realization and determination. Many brothers refuse to learn from the experience of their predecessors, they want to quit on their own. Their ideas make some sense, but the winners are almost all made up of people who are good at learning and reading. The experience of the seniors can make everyone avoid many detours, just like a direction guide, pointing you towards the right path from the start.

If you reject the experience of predecessors, it is undoubtedly a loss for yourself. It will be very difficult for you to explore on your own. The reason for my rebooting success is due to the absorption of experiences and lessons from many people, constantly learning from the knowledge and experiences of predecessors. This is followed by independent thinking through the integration of my own experiences and research, from there, the essence of rebooting success is discovered. Many people are not willing to learn, this is in fact due to agitation and inability to calm the mind, they are determined to reboot in the brute force way, the results should be apparent.

A veteran brother came back to the rebooting forums to have a look and found me still active, then he said: Soaring Eagle, why are you still here? Yes, many veteran brothers have left. Some have left after they have failed, some have done so after they have succeeded. Although some people have not been completely successful, they rarely relapse. Many such people have left as well, returning to the normal track of life and not bothered with rebooting anymore.

In reality, I may leave as well. What I’m doing is for public welfare, I’m not getting a penny of income from it, I take helping other people as a great cause, although it doesn’t give any income I’m very happy doing it. After having written so many articles and answered so many questions, from a normal point of view, I should have been tired of it a long time ago, but I stayed because I wish to help more people, that’s it.

If you are a senior brother, you will have noticed that many of the most popular advice seeking threads have sunk to the bottom, this is because the person answering the questions has left the rebooting forums. In the beginning, the responders will have a sense of accomplishment and freshness. After answering many questions there will be a feeling of weariness, thus one becomes resigned. The responders who are really able to stay behind are generally people of willpower, who are truly willing to give selfless devotion, not seeking fame and fortune, only to help more people. The reason for the good atmosphere of the rebooting forums is due to a group of such people, selflessly dedicating themselves. I hope that more friends can dedicate themselves. Having to take on such a role you will find more meaning in your life, you will become open-minded and full of positive energy.

**A final summary**:

Everyone may study my articles in order to gain experience. One may believe in me, but do not blindly believe in me or blindly put me on a pedestal, I’m only an ordinary brother. In addition, although I’m a Buddhist, I will not force my belief onto others. I believe in freedom and following fate. For brothers with Buddhist karmas, I will mention Buddhist teachings in my answers towards them. I have previously mentioned about life release but only towards believers of Buddhism. If you are not a believer, that is fine, you can take the road of professional rebooting, one may also reboot successfully in this way. My article is mainly elaborated from the perspective of professional rebooting, this is the road that I walk on.

I have conducted my research work based on a large number of real cases. Research topics include specific hazards in masturbation, the pattern of rebooting and relapsing, the path to recovery, the various problems that one encounters during the rebooting process. These are my main focus of research. Through the comparison and research of a large number of real cases, I have discovered a lot of principles. This is the reason why I write articles, in order to share these principles with everyone. I hope that they will bring useful inspiration for everyone and that everyone will be able to reboot more professionally and properly.

### Case studies {-}

Below, I will share 2 Q&A cases:

#### Case 1 {-}

> I have a  6 year history of masturbation, the frequency is relatively high  _(should be considered very high)_. In addition, I have an obsessive-compulsive disorder. Masturbation has brought me a lot of bad influences. I also deeply understand the danger of excessive masturbation. I’m determined to change but I still have some doubts. The aim of the rebooting forums is to achieve abstinence before marriage and then moderation post marriage. What I want to ask is that if both masturbation and sex damage the body and masturbation is addictive, isn’t it the same with sex? It should also be addictive. Why is it OK and possible to have moderation after marriage but not moderation in masturbation? Moderation is achievable in sex, while the same is difficult for masturbation?

**Answer:**

Both masturbation and making love damages kidney essence. Making love may also lead to addiction and kidney deficiency. Therefore, try to maintain moderation after marriage and learn the way of health cultivation. Do not let greed destroy the body.

I think that many brothers want to know the answer to the second question: Why abstinence before marriage and not moderation?

There are 3 reasons why the rebooting forums advocate abstinence before marriage.

**(1).**  From the moral point of view, it is in line with tradition values. Sex before marriage is considered as evil debauchery, evil debauchery injures the body and damages virtue. Sex after marriage is positive debauchery. This is in line with human relations, but one also needs to pay attention to moderation.

**(2).**  It is to avoid indulgence before marriage, in order to avoid being wasted before getting married. One should save the best of oneself for after marriage. During my long stay in the rebooting forums, I have seen a lot of unmarried brothers becoming wasted before marriage. The family is urging marriage, but their sexual function is no longer OK. They have premature ejaculation and erectile difficulties. It is inconvenient to communicate such issues with women. Once the word is out, the female will mention breaking up, making things very awkward. Some friends are not only sexually disabled, but their whole body is ridden with symptoms with discomforts all over. When entering marriage in such a state can also be very hard.

**(3).**  The third point is very important. In fact, rebooting is cultivation. Why do you want abstinence before marriage? This principle is actually similar to taming a wild horse, that is, to learn to conquer the temptation demons before marriage. The temptation demon is the wild horse, one can only direct this wild horse after marriage. The process is: first conquer and then direct! If you have never surpassed the demon, then you can’t talk about directing, one will be unable to truly achieve moderation after marriage.

In other words, when you are successful at rebooting before marriage, then there will be hope to truly achieve moderation after marriage. Otherwise, if you have never conquered the temptation demon, there is a high chance of becoming wasted after marriage. Remember: First conquer, then direct! If you are unable to conquer the temptation demon, then it is possible to become wasted both before and after marriage. We need to be masters of desires, not the slaves to desire. The consequences of being slaves to desire are very grave!

**Analysis:**

There are only two Chinese emperors who lived to be over 80 years old, Liang Wudi, a Buddhist. The other person is Qianlong, who advocated moderation in lust. The emperor generally does not need masturbation, there are so many women in the harem, but why are emperors lives short-lived? It’s because of too much lovemaking. The emperor has access to the best doctors in China, the food they eat and supplant themselves with are of the highest quality. But despite such conditions, many emperors die in their 20s, that is, they cannot pass the female threshold.

Many people are born with a weak constitution, but their desire is very strong. By damaging the kidneys under such circumstances, it won’t take more than a few years before symptoms come knocking on the door. So even after we get married, we must pay attention to moderation. Otherwise, many people get married and have sex very often and with ruined bodies as a result. For brothers who are already married, if you have a lot of symptoms, then you should learn to reboot and cultivate the health. You may have a good talk with your wife, cultivate yourself to a healthy state and then have sex in moderation. Don’t be tempted and waste yourself for a moment of fleeting pleasure.

I see a lot of Chinese medicine cases, those ancient doctors have all required one year of abstinence in combination with taking Chinese medicine, only in this way can one hope to make a full recovery. Otherwise, by supplementing from the above and leaking from the below, recovery will forever be difficult. Even if one is temporarily healed, relapse will be easy. 30% of treatment, 70% of maintenance. Rebooting and preserving the essences is covered by health cultivation. Married brothers must communicate this well with their wives in order to avoid misunderstanding and the resulting family conflicts. If your wife is fairly understanding, then things will be easier.

#### Case 2 {-}

> Continuing to ask Soaring Eagle brother, should you always put rebooting in the first place, should you have this attitude? During these three months, I have not stopped in studying your posts and your posts about cases, I have always put rebooting in the first place because I feel that my appearance, self-confidence, and life is affected by it. Every day when I come home for dinner, I must study rebooting articles. In 3 months I have made 3 notebooks of notes. But I don’t know if I’m overdoing, or should I have this attitude? Please answer this question.

**Answer:**

Yes, your question has been raised by somebody previously. We should take time to learn and review rebooting articles and notes every day, continue to raise the realization, and remain highly vigilant. But we shouldn’t spend too much time on rebooting so as to affect everyday life and studies. One may make an arrangement such as studying rebooting articles for 1-2 hours every day, arrange the time for it and reasonably allocate your energy. On the basis of not affecting everyday life and studies, we can read more articles and cases on rebooting but don’t make yourself too tired. You are progressing very fast. If you feel very tired and it is affecting your studies, you should pay attention to make adjustments. Fight on!

**Analysis:**

The distance between us and rebooting should not be too close nor should it be too far. When rebooting, it does not require one to spend a dozen hours each day in the rebooting forums. When sitting and gazing for a long time in that way, it is not favorable to the recovery anyway. But you should carry the rebooting forums in your heart. Every day, you should log on and feel the atmosphere of the forums, then read more cases, encourage more newcomers. While spreading positivity you are also strengthening your positive energy.

Of course, you don’t have to log on every day. If it’s inconvenient, you can also take out the rebooting notebook and review it, learning new things from reviewing old things. My current schedule is to normally use my phone to log onto the rebooting forums during the day, roughly about 10 times and a few minutes each time. I read a few cases and then answer a few questions. Then after arriving home during the evening, I answer questions for about an hour. Of course, I also make images and come up with ideas for articles. I don't make myself too tired. Once too tired, one will easily want to give up. Therefore, I pay great attention to striking a balance between work and rest as well as time management.

The third year of high school is very tough and important, more time and energy should be allocated to schoolwork. In addition, some brothers will opt for cutting out the cellphone and the internet, they put all the blame on computers and phones for breaking the reboot, never once having thought the reason is oneself. Even though many people have cut off the internet and cell phones, they still relapse. This is because relapsing sometimes does not require external temptations. One’s own fantasies and memories may lead to breaking the reboot. Other people relapse due to emotional reasons and not due to temptations.

My opinion is still: to successfully reboot, one must study more and raise the level of realization, otherwise, there is no way to conquer the temptation demon. In rebooting, we need to control the time we spend on the internet in order to avoid getting hooked to the internet. But if one chooses to cut out the mobile phone and the internet, one loses access to many first-hand rebooting articles and material, this is not favorable to raising the realization. Of course, there is also a compromise, that is download all the rebooting articles to the mobile phone and read them on the phone. In this way, one is staying away from pornographic material while still being able to continuously study rebooting articles.

Below we enter into the main topic.

There are 2 main topics in this season: talk about relapsing and the revealed profundities by the 21 points.

## About relapsing {-}

Right now, many posts in the rebooting forums are about relapses, they occupy a lot of room. Every day one sees these posts, in them, one may see encouragement and guidance from predecessors. Don’t be discouraged after relapsing, don’t smash the jar just because it is cracked. When you have learned to draw experiences and lessons from the failures, then your reboot will become better and better. Failure can be a springboard, it can also be an abyss. By treating failures correctly, failure can be the mother of success.

In the rebooting forums, you will generally find 2 types of people:

1.  Reboot better and better
2.  Reboot worse and worse, even giving up

Those who reboot better and better are generally good at studying and summarizing reasons for failure. These brothers have excellent studying habits, their realization is in the process of continuous improvement. Under such circumstances, when they relapse once it will raises their realization to the next level. They begin to pay attention to the reasons that led to relapsing and will be even more refined in rebooting.

For example, a brother had a relapse due to emotional reasons. Next time, he will realize the importance of emotional management, he will pay attention to adjusting his feelings in time. When he is in a bad mood, he will realize that it will be very easy to relapse from here on, and so he will immediately raise his vigilance and adjust his emotions. This is actually the harvest from breaking the reboot. The relapse may be negative but it can also be positive, one learns from one’s mistake.

Brothers in the second category generally rely on brute force, or they think that they are fine after having read a few rebooting articles. Actually, in order to be successful, one must continuously study and continuously raise the realization, reading a few articles does not make one successful. These brothers also rely on enthusiasm to quit. When relapse occurs, the enthusiasm for rebooting will fade, then the momentum will wear off, the original feeling towards rebooting is never to be found again.

Indeed, relapsing will cause a loss of morale and enthusiasm. But there is a saying: *Failure can make a person become discouraged, it can also make a person stronger*. What doesn’t kill you will only make you stronger. I advocate rationality in rebooting and not relying on impulsive enthusiasm to quit. Otherwise, the enthusiasm wears off quickly and confidence is immediately lost following a relapse. We should be sensible and develop good study habits that are as natural as brushing the teeth daily. Allowing realization to continuously rise is the key. Yao Ming didn’t become 2.26m overnight. If you want to reboot successfully, accumulation must be emphasized, constantly review, reflect, summarize and keep taking notes. With regards to my articles, some brothers have really understood them and then their realization rose very quickly and they were able to reply to many questions on my behalf.

In studying rebooting articles, we should pay more attention to the rate of absorption. Otherwise, if nothing is retained after reading an article then one has read in vain. Good articles and good books should be read repeatedly. When you read an article this month and then again the next month, the feeling will be completely different. I have deeply experienced this first-hand. When reading an article for the first time, the gain is very limited, but read it again after a while and there will be new insights and discoveries. When reviewing material after a period of time, you will acquire new knowledge. When you have repeatedly read an article many times, you will find that you have really absorbed the essence of the article.

For some friends, relapse is a springboard. Through this springboard, they jump to a higher rebooting level and become even better from then on. For some other friends, relapse is like an abyss, things get progressively worse after a relapse until finally, they give up altogether. They choose the route of escape, some brothers after having relapsed even come to the rebooting forums in an attempt to pull people down with them. They say that you can’t quit or even directly post pornographic images to tempt people to relapse. These brothers have actually become the traitor, they have become puppets to the temptation demon, they have become the microphone of the temptation demon. I understand their thinking very well; if I’m unable to quit, don’t you think that you can quit. If I’m to be wasted then everybody goes down with me. If I’m no good, don’t you think about being good. With regards to these brothers, normally I would immediately delete their posts so as not to affect other peoples’ rebooting process. These brothers should repent well, turn around and head towards the shore.

To be honest, before succeeding I relapsed countless times. Of course, I didn’t have any sense of learning awareness at that time. My level of realization was very shallow. At that time, I was rebooting the brute force way, my record streak was 28 days. Later, via studying and raising my awareness, I easily bypassed 1 month and then everything became better and better. I broke through half a year and then one year. Later on, I stopped counting the number of days, it was enough to remember which day I started to reboot.

We must constantly try, don’t be afraid of failure. Learn from failure and grow your experience, constantly improve ourselves. In this way, it is possible to finally approach success. When you have developed good study habits, there is no need to fail that many times. Once you have stepped inside the door of rebooting and obtained a certain level of realization, it is actually very easy to break through the half year barrier.

The reason for so many failed attempts during previous times is due to not having really stepped into the door of rebooting, I was still an outsider. When you really grasp the true essence of rebooting success, the realization will advance by leaps and bounds as will the number of days streak. There is indeed a group of brothers on the rebooting forums whose realization has increased surprisingly quickly, these brothers are good at studying and summarizing.

What is the feeling after the realization has been raised? I can tell you, for example, when you are still in the first grade of elementary school, you will find it difficult to do the math problem of the first grade. When you are in college, and you can go back to the math problem of the first-grade elementary school, the problem is simply child’s play. It is the direct result of having raised the level of realization. When the realization has been reached, and looking back at everything, one will feel that it is unusually simple and straightforward. However, if your level of realization is stagnating, then it will be difficult to reboot successfully.

For some veteran brothers, my advice is: don’t walk away from the rebooting articles, don’t relax your vigilance! When you have been rebooting for more than 1 year or more than 2 years, you should even be more careful to not relax your vigilance. The mistake many veteran brothers make is to think that they have been rebooting for so long that they will not relapse again. One scarcely realizes that as long as vigilance is relaxed, relapse will happen no matter how long one has been rebooting. The vigilant screws can’t be loosened, otherwise, the rebooting skyscraper will come crashing down!

After entering the reboot stabilizing period, many people relax their studies and their vigilance. The temptation demon is given a chance to avail itself, relapse will be inevitable. After the relapse, one then comes to their senses and regrets being careless. Generally, after entering the reboot stabilizing period, there are very few sexual fantasies, many people naturally relax their vigilance. The lack of sexual fantization does not mean that it is entirely gone. The temptation demon is constantly looking for a chance to counterattack. When your vigilance is slack, this is the opportunity for the temptation demon to avail itself. Therefore, we must be vigilant every day in our rebooting process, maintaining a state of having foresight. When the screws of vigilance appear loose, we should discover this immediately and tighten the screws of vigilance, the fruits from rebooting can be preserved in this way.

The power of rebooting comes from studying! Studying raises the realization, realization conquers the temptation demon! These three words are the true meaning of rebooting success!

The root of preserving the fruit of rebooting lies in vigilance! Strictly speaking, vigilance also belongs to the realization category. The reason why it is mentioned separately is to emphasize the importance of vigilance. When your realization has reached the mark, rebooting success will naturally follow. When the melon is ripe, it will fall off its stem. Please believe in my words. Fight on!

## The revealed profundities of blackjack {-}

Below let’s talk about the revealed profundities of blackjack

Everyone may be confused about this topic, what does blackjack mean? In fact, the 21 points that I’m referring to is a card game, abroad it is called blackjack. Needless to say, I believe that most brothers have played this card game. This card game is very easy to learn, it normally takes a few minutes to learn to play, it is extremely simple. But it is very difficult to become good at this game. I have realized the principles of rebooting from this card game. I will share it with everyone this season.

In the rules of blackjack, it is mentioned, if all the cards add up to more than 21 points, the player loses - called (Bust), also called the flop.

There are a lot of brothers who are busting, because they don’t know that there is such a point in the body, that is, the critical point of the symptoms. They are out of control, controlled by addiction, madly masturbating with the result of being wrapped in symptoms before long. People with a poor constitution will encounter symptoms relatively early. People with a good constitution will encounter symptoms a bit later. But as long as you are addicted to masturbation, the appearance of symptoms is inevitable.

But some people have hidden symptoms, they appear okay on the surface, but only they know within that the body has various discomforts. Some people belong to the category of hindsight. The body already has a lot of symptoms, but because of ignorance, never connect the dots to masturbation, thinking that the symptoms are caused by other reasons. Only after reading rebooting articles do they come to a sudden realization of the truth. The various discomforts of the body throughout the many years were caused by masturbation, only now does one wake up.

To win at blackjack, one must risk the bust, especially at 16 or 17 points, taking an additional card at this time will very likely lead to a bust. And in our rebooting process, the most clever method is not to masturbate a single time. This is because masturbation is addictive, doing it once will lead to doing it continuously, the result is tragic, that is: you masturbated to a bust! Entangled by symptoms.

It should be noted that the sexual fantization is also the same as requesting an additional card. Very many brothers encounter symptoms after sexual fantization. Brothers who have read my previous articles should know that sexual fantization is the invisible form of leakage. Therefore, when we reboot, we must overcome sexual fantization. When we have passed this level, rebooting will become a lot easier, basically halfway succeeding. Otherwise, even if you know all the dangers of masturbation being unable to overcome sexual fantization, will make it impossible to reboot successfully.

Back when I was still quite ignorant, I masturbated like crazy and went bust countless times. But at that time, no one was waking me up. Neither was there anybody telling me about rebooting knowledge. I was the frog sitting at the bottom of the well. Having raised my realization through ceaseless studies and then looking back at my ignorant self, I felt lots of sadness and pity. At that time, I was masturbating like crazy and rebooting blindly, the result was countless relapses and countless failures.

I was trying to find a dynamic balance at the time, I believe many brothers have had this idea, that is, hoping to find a balance between masturbation and the symptoms, being able to masturbate without encountering any symptoms. Later, I found that it is extremely difficult to find a balance because masturbation is highly addictive. It will cause you to continuously demand new cards, eventually leading to a bust. When you start rebooting after having gone bust, then you are only making up for it, there is no preventive power. Some brothers can indeed do it once a week, but they can’t overcome sexual fantization. They are leaking more via sexual fantization, and don’t know it because they are ignorant, they think that they have good control. Not long after, they will find that they are entangled in symptoms.

After playing lots of blackjack, there will naturally be experiences of busts. When one has been masturbating for a long time, one will naturally slide towards that critical point, resulting in bust through masturbation. When one often walks along the river, how can the shoes not get wet. I have seen many cases from brothers. In all cases, during the first few years there are no symptoms, then, from the third or fifth year, the symptoms will slowly appear. Some brothers were fine last year, this year, the symptoms suddenly broke out. Quantitative change produces qualitative changes. When the essences have been damaged to a certain degree, there will naturally be symptoms, no one can escape! Low essence precedes illness, commit the words of the medicine king Sun Simiao into memory, it is never wrong.

The process of busting via masturbation is very similar to that of the blackjack. When you continuously ask for new cards, the biggest possibility that awaits you is a bust. True masters of blackjack will count cards, memorize cards and calculate the probability of busting. But even then, they also lose sometimes. But it is different with masturbation, if you don’t masturbate, then you will not bust via masturbation. Just like if you refuse to play blackjack, you won’t bust. If you want to play, it is easy to bust. The most clever way is: refuse to play again, refuse to masturbate again! Never again bust because of masturbation!

Lastly, I have summarized 3 sentences:

1.  If you don’t masturbate, then you won’t bust as a result of masturbation.
2.  Once you start to masturbate, the possibility of a bust due to masturbation is extremely high.
3.  Refuse to masturbate again, consciously stay away from the critical point of the symptoms.

## Books recommendation {-}

In this season I will recommend a book:

[Tibetan Book of the Dead] Sogyal Rinpoche

I believe that some brothers know this book, I spent five days reading it. This book has deepened my understanding of Buddhism and deepened my understanding of life and death. It is indeed very inspiring. The book opened my horizon. After reading this book, I read [中阴闻教得度]. After reading these two books, I found out how superficial my understanding was on the topic of death. I used to avoid death as a taboo. After reading this book, it gave me a new understanding towards death and also on how to face its arrival. Interested brothers may take a look at it, it should bring you a lot of inspiration.
