# How to cope with the period of repeated symptoms

## Foreword

In the forewords of this season, I will share 2 cases:

Case 1:

I have been masturbating for 12 years, and now the whole body is hurting, the whole body is sick, I can’t even do heavy work. Prolonged masturbation has caused my penis to become very small. When I have sex with my wife, I can’t get it up, my wife will divorce me soon! Because of masturbation, I became very selfish and my appearance became very ugly. At the age of 24, I look like a 42-year-old, and my face was full of beards and freckles. I’m really going, my life and career is a mess, I cannot succeed in anything. Now my waist is aching as if someone is peeling me with a knife, it’s so uncomfortable! Now I still masturbate. I also did it twice last night. Today, my head is blown up. I feel like I’m dying, who will save me!

Additional comments:

This brother has been deeply injured, but his mental addiction is very strong. With back pain to such an extent, he is still inflicting self-harm like crazy, he simply does not want to live! The retribution from 12-years of masturbation is too fierce. The whole body is sick, completely impotent while still facing the blow of divorce. The sinister person will become ugly and wretched. This is already an open secret. It is a matter of the heart. When a person is often addicted to the content of evil debauchery, he will eventually become ugly and his appearance will quickly age, a sloppy and dirty image of a man. Many people have already turned themselves into a walking dead.

As the saying goes, tears only fall when the eyes behold the coffin, but some people have seen the coffin and still do not know repentance. They are still numbingly ruining themselves. This crazy state of self-destruction state is really horrible!

The penis of this brother has already shrunken. Several brothers have previously reported this issue where they mentioned that their penis used to be normal. After the kidney qi has become deficient, the length of the penis has been reduced, just like a deflated balloon. Not only will the penis shrink, but the testicles may also shrink or sag. (Translator’s note: the reader should not be too frightened upon reading about the shrinkage issue. It is entirely possible that when a person is weakened, his erection will weaken as well which makes the penis look smaller compared to normal. The penis does not permanently shrink as a result of masturbation.)

After ejaculation, many people will show signs of pain in the back of the head. TCM speaks of the kidneys are connected to the brain. The devastation on the body and the brain from masturbation is particularly powerful. After a long period of masturbation, headaches will surely emerge. The brother from this case should have countered neurosis by now. When one has neurosis, normally one is desperate, it really feels like you would prefer death to live, and you really have to call for help! The 24-year-old has become a 42-year-old, and his body is sick! Shout for help! Everyone should know the severe dangers of masturbation!!

Master Yinguang said:
> "Youth nowadays are aware of sexuality, one should promptly be told about the way of health cultivation and essence preservation. If one knows the good and the bad, one will not find joy in masturbation, to that extent that the life is forfeit, or to become disabled and forever be susceptible to all kinds of disasters. Little can be said for those who are not aware of sexuality. For those who are aware, if nothing is said, then 9 in 10 are guilty of this sickness, it is extremely horrible. > > Meng Wubo asks about filial piety, Confucius replies: parents are mainly worried about illnesses of their offsprings. Other illnesses are of little importance except for masturbation and greed for sex. Such has Confucius said about the topic. Most of the youngsters today masturbates, it’s like a big knife that’s cutting away at the body, one must face the pain and cut it out. Many youngsters have their desires aroused which finally leads to masturbation. This act has a great damaging effect on the body, one must not commit it at all cost. One who commits masturbation is robbing himself of the body and polluting his mind. He takes the useful body, either making it short-lived or weakening it until one becomes a wasted person.

Case 2:

I have always had wishful thinking, until yesterday afternoon when I masturbated 3 times in a row. The next day there was dizziness and headache, no appetite to eat, the food that was eaten was spat out. There was always nausea, now death is preferable to life, I really want to die but I’m not content.

I am only 20 years old. Before becoming depraved, I can be considered to be a person of talent, now I am really scared! I don’t dare to have wishful thinking anymore, the temptation demon is too scary! I must study hard, I don’t dare to masturbate anymore. I might have neurasthenia! I have masturbated for 6 years! I also stayed up late and masturbated several times 3 times in a row, I am going to die! It’s painful! What importance is turning ugly? Compared with neurosis, turning ugly is simply not a problem. Neurosis, dizziness, and headache are like a curse, every day is torture. When the symptoms appear, I want to die. It’s really painful. Can anyone tell me, will I die or not, I really don’t want to die! Who can save me!!

Additional comments:

Many people who masturbate have wishful thinking. They also know some of the dangers of masturbation, but they feel that this kind of thing will not befall themselves. When retribution is really present, then regret is too late. The wishful thinking mentality completely ignores the nature of the matter itself, it completely contradicts the nature of the development in things. Many people think that it is fine to masturbate. In fact, as long as masturbation begins, bad changes have already occurred quietly. An ant hole may cause the collapse of a great dike, quantitative change produces qualitative change. The result from indulging in masturbation is inevitably the outbreak of symptoms. It is a truth revealed by thousands of cases from victims.

Low essence precedes illnesses, it is the iron law! Masturbating once and again is to accumulate negative energy again and again, and finally, the whole person will be blasted by negative energy! It’s like pumping up the tires of a tire, keep pumping and finally the tires suddenly bursts. You think that it won’t explode. In fact, you will cross the critical point of the explosion without knowing it.

This brother is already suffering from neurasthenia, it’s as if he is wearing a curse over his head. The feeling is torture and very painful. Wishful thinking is really something that is to be cast away, as long as you masturbate, the symptoms will burst out sooner or later. This case ended with a call for help, it is quite shocking! Masturbation will eventually detonate the hardships of life. You think that you are having pleasure, in fact, you are losing out big time. Every time you masturbate you are taking a loss, small losses accumulate into a big loss, and at last big losses accumulates into a colossal loss, the end is quite bitter! Saving a drop of semen and you gain a drop of vitality. Those who excessively masturbates are self-destructing!!!

We will enter into the main top below:

## Repeated symptoms

### Almost everyone will experience repeated symptoms

Many newcomers are worse off after rebooting, and then he will have doubts and think that abstinence is not good. In fact, there will be withdrawal response within one month into rebooting, just like there will be withdrawal response when quitting smoking, it is the same with rebooting. The general withdrawal response from rebooting will be alleviated or even disappears for three weeks.

When rebooting, there will also be periods of symptom recurrence, it may occur at any time during the rebooting period. In order to distinguish it from the withdrawal reaction, if the symptom shows up a few months into the reboot, it is then considered as the period for repeated symptoms. If you run into symptoms after over a month of rebooting, it can also be considered as the period for recurrent symptoms.

Almost everyone will experience repeated symptoms because the process of healing is definitely not smooth. There are many factors that cause symptoms to be repeated, such as indulging in sexual fantization, staying up late, long periods of sitting, fatigue, anger, exposure toward cold, nocturnal emission and poor diet. Rebooting is a systematic process, same with recovery. We should strengthen the way of health cultivation and do well in all aspects. In doing so, the number of repeated symptoms will be greatly reduced, and finally tend towards stabilization.

Rebooting alone is not enough, we must work harder on health cultivation recovery. If your symptoms are serious, then I suggest you can take Chinese medicine in nursing the health. Please remember: quitting lust is not wrong, Confucius also advocated it, many senior monks of great virtue have lived to be over 80 and even 100 years of age.

The level of faith for many newcomers are often not firm enough. They have been constantly brainwashed by harmlessness theories in the past. Therefore, once the symptoms of the body are repeated, their rebooting foundation may immediately become shaken, they may even become suspicious of rebooting. In fact, repeated symptoms are generally always found in the process of recovery. Many people have a long history of damaging their essences. The degree of injury is quite serious, this ensures the process will be tortuous. But as long as we persist in it, the final victory will inevitably belong to us, one must have faith in this. Both rebooting and recovery rest on 3 cores: faith, determination, and perseverance. As long as the cores are firm, everything will come to fruition.

The pattern of healing shows that the disappearance of symptoms will undergo a process from unstable to stable. Just like practicing shooting, you can rarely hit the 10th ring at first. By sticking to practice, one will slowly stabilize at a higher level. The number of times you hit the 10th ring will increase. The process of physical recovery will also go through periods of repeated symptoms. Many brothers may not have obvious withdrawal response, but almost every brother will experience repeated symptoms. It can be said that the period of repeated symptoms is unavoidable. The key is to learn to take care of one’s health, so the number of repeated symptoms will be fewer and fewer, and then it will tend to be relatively stable.

Many brothers panic at the first sight of repeated symptoms. In fact, it is very normal to have recurring symptoms. After all, there are many factors which may cause repeated symptoms. Even healthy people may become sick from time to time, not to mention many friends have been masturbating for several years or even for more than ten years. After cutting out the vile habit of masturbation, the body will slowly recover, but the process of recovery is also torturous, and one must work harder in health cultivation.

If the degree of recovery is not ideal after rebooting, it will also easily lead to relapses. A while ago, there was a brother who relapsed after around 2 years of rebooting. The reason was that the recovery was not ideal, he felt frustrated and smashed the cracked pot. Although he has been persistent at rebooting, in terms of health cultivation, he was doing really poorly. Not only was he still staying up late, but he was also eating irregularly. When many people are busy they do not eat on time, some don’t even eat breakfast. When they sleep, they sleep until 11 am.

Chinese medicine practitioners have mentioned that long period of lying down injures the qi, rising up too late will also have a very negative impact on the recovery of the body. TCM practitioners have said to not make any rash labor, do not labor excessively, one should not work hard, that is, do not overwork.

“Long-term gazing damages the blood, long-term laying down damages the qi, long-term sitting damages the muscles, long-term standing damages the bones, long-term walking damages the tendons, these are the 5 damaging labors”. — [素问]

Vision, lying, sitting, standing, and walking are all indispensable behaviors in life, but excess can lead to injuring the blood, qi, muscles, bones, tendons, ..etc. Therefore, we must pay special attention to health cultivation while rebooting. We must learn more from health articles to improve our health cultivation awareness, the frequency of repeated symptoms may be greatly reduced in this way.

While rebooting, one should be mentally prepared for the recurrence of symptoms so that when the symptoms start to repeat themselves, the mind will no longer panic. One is able to face the symptoms with calmness and naturally being able to successfully overcome it. By grasping the pattern of recovery, one will be confident. Even if the symptoms are repeated, it will not be troublesome, because you know that this is temporary. As long as you pay attention to recuperation, exercising in moderation, repeated symptoms will soon ease.

### My experience with repeated symptoms

In my recovery process, I also experienced repeated symptoms many times. But every time it occurred I did not panic, because everything is within expectation. Let the wind rise, sit firmly on the fishing boat, be unaffected by the collapsing Taishan mountain, tread steadily while the fierce tiger lurks behind, the rebooting mentality must be steady! No matter what happens, you must calmly deal with it without a thread of panic. If your mind panics, the temptation demon will chance to take advantage of it. When your mind is unstable, the temptation demon will come and incite you, instantly demolishing your already shaky foundation. In fact, if you really grasp the pattern
of recovery, you will be unperturbed. This kind of calmness is like knowing the card of the other player when you are playing cards, everything is within your expectation and control.

The repeated symptoms I experienced previously were mainly symptoms found in prostatitis, hair loss, hives, neurosis, ..etc. Usually, when the weather is cold or following nocturnal emission, recurring symptoms of prostatitis easily occurs. Especially following consecutive nocturnal emissions, there is a high possibility of repeated symptoms at this time. In addition, staying up during the night and sitting for long durations is also very damaging, making it easier for recurring prostatitis symptoms to take place. It can be said that the most easily occurring repeated symptoms are those belonging to prostatitis.

The recovery of hair loss also easily undergoes a process of both good and bad periods. If the nursing of health is properly maintained, symptoms will then tend to move slowly towards stabilization. To recover from hair loss, one must be patient as well as doing a good job in all areas, especially towards health cultivation. I have experienced repeated symptoms of choline urticaria on multiple occasions during the first year of my reboot. Later, the number of recurring symptoms has become fewer and fewer. Today, those recurring symptoms have not occurred for a long time, it can be said that they are basically healed.

In addition, in my rebooting process, I have experienced recurring neurosis numerous times. But because I usually pay attention to health cultivation, I haven’t yet relapsed, this includes sexual fantization which I have able to sever as soon as the thought arises, so the recurrence of neurosis has not been very fierce. As long as I made sure to rest for a day or two, the body will greatly ease. Up until now, my neurosis has basically healed and it has not been repeated for a long time, it is in a relatively stable state of recovery.

In the rebooting forums, there are also many brothers who report that acne is often repeated. The acne is relatively easy to repeat. Rebooting alone is not enough. It is necessary to strengthen health cultivation. Being negligent and staying up late, eating improperly, nocturnal emission and other factors can lead to the recurrence of acne. One must pay more attention to all aspects.

## How to deal with repeated symptoms

It is very common to have symptoms repeated during the recovery process, almost every brother will experience it. This is normal. You don’t have to panic. You can make adjustments from the following five aspects:

### Stabilizing the morale through psychological suggestion

When the symptoms are being repeated, you have to tell yourself that this is temporary. You must understand the pattern of recovery.

The pattern is: more recurrences → fewer recurrences → gradually entering into a stable recovery state.

No matter how fierce the wind blows, it is like a stroll in the garden. When you master the pattern of healing, you will no longer panic. Otherwise, whenever the symptoms are repeated, many people’s mentality will immediately undergo subtle changes for the worse, the moral is immediately unstable. You should tell yourself that it is normal to have symptoms repeated. The repetition of symptoms is completely in line with the pattern of recovery. That being the case, there is no need to panic. When symptoms are being repeated again, you will be able to handle the situation calmly and bear hardships with equanimity.

### Ensure adequate and good sleep

When symptoms are recurring, one must pay attention to recuperation and must ensure a good sleep. Do not stay up during the night and sit for long durations at all cost, otherwise, it may aggravate the symptoms. Generally, when the symptoms due to essence damage repeat themselves, if one is paying attention to recuperation, relief will come very quickly.

Although some people are rebooting, the habit of staying up late is still going on. In this case, his recovery will not be very fast and he is prone to repeated symptoms. The harm of staying up late is very great. For example, it will lead to the ever-worsening condition of the skin. The problem of acne will also become more serious. In short, staying up late is very harmful to the skin. The best time to maintain the skin is from 10:00 to 2:00 in the evening. If there is no good sleep during this period, the endocrine and nervous system of the body will be adversely affected. Long-term staying up late will lead to allergies, decreased resistance, neurosis, ..etc. Good sleep can promote the body’s repair.

The student crowd is prone to staying up late, which is very unfavorable for the recovery of the body. Therefore, it is necessary to establish a good working habit so that the body can recover better. After repeated symptoms emerge, it is necessary to ensure adequate sleep, one must ensure the regularity in the activities of life. In the process of sleep, the human body is being charged and repaired. If good sleep can be ensured, normal repeated symptoms will quickly be relieved.

People who are sick are always particularly sleepy, because the body suppresses other physiological functions through sleep, thereby highlighting the immune function, so as to help the body recover as soon as possible, thus showing that sufficient sleep can enhance the body’s immunity. Medical experiments have also found that if people reduce sleep by 4 hours, the body’s immune cell activity is reduced by 28%; and after getting enough sleep, it can return to normal.

In the state of sleep, the various hormones secreted regularly play an active role. Taking growth hormone as an example, when you enter a deep sleep for 1 hour, its secretion enters a peak, which is more than three times that of the day. In addition to promoting growth, the hormone can also accelerate the burning of body fat. On the contrary, if there is insufficient sleep, internal secretion will be disordered, hormone secretion will lose its regularity. Not only the emotions will easily become excited, but fertility is also affected.

In addition, most of the internal organs of the human body such as the heart, stomach, ..etc are subject to autonomic nerves. The autonomic nerves are divided into sympathetic and parasympathetic nerves. During the day, the sympathetic nerves are active, the heartbeat and gastrointestinal motility are accelerated. When you fall asleep, the sympathetic nerves become suppressed, the parasympathetic nerves are active, and the internal organs are rested and relaxed. If you don’t sleep when you are tired, not only will the internal organs lose rest, but also the autonomic nerves will become disordered, thus laying a hidden danger for the outbreak of neurosis.

Many brothers combine masturbating with staying up late, and eventually, they have ruined themselves. Once the neurosis breaks out, the pain grows geometrically. At that time, it can be said that it is impossible to live, living becomes extremely painful and tormented.

### Establish good exercise habits

[吕氏春秋] records: “If the water is not rotting, the body will not be worm-eaten”. The famous doctor of the Tang Dynasty, Sun Simiao, realized that the movement can make “All diseases disappear, benefit and prolong the years, eyes are light and healthy, one is no longer fatigued.”

Moderate exercise can play a positive role in maintaining human health, dispelling disease and prolonging the lifespan. But excessive exercise is likely to be counterproductive and may even lead to a decline in immunity. When the symptoms are recurring, we can do some moderate aerobic exercise, such as jogging and walking, which can promote the recovery of the body. But one should not over-strain, profuse sweating should be avoided because it damages the Yang. The body tends to be weakened following profuse sweating.

In the winter, avoid illness by moving around a little; alternatively, be a little lazy during the winter and end up drinking an extra bowl of medicine. In fact, this not only applies to winter but also the other seasons. Active exercise can give you a better energy status. It allows you to face your daily study and life with increased vitality.

Conversely, insufficient exercise and overeating can cause weight gain. When obesity develops to a certain extent, the risk of heart disease, high blood pressure, and diabetes greatly increases. Aerobic exercise combined with proper diet control can most effectively remove excess body fat, allowing one to recover full energy and vitality, allowing one to live a young life. When a person lacks exercise, they often feel fatigued, depression, memory loss, and even lose their interest in work. Aerobic exercise can miraculously change this state, making people high spirited and mentally relaxed.

When we have repeated symptoms, we are able to obtain improvement and relief through moderate aerobic exercise. I used to go to the park for a walk. Upon returning home from the walk, I felt refreshed. We should feel the atmosphere and frequency of nature, let the body and mind return to a simple and harmonious state.

### Health practice and diet

When symptoms recur, we can also do some health cultivation exercises, such as Eight Brocade qigong, Six Healing Sounds Qigong and standing qigong, ..etc. In doing so, the symptoms may be alleviated. Health exercises are not just a kind of maintenance, but also a method of treatment, the effect of which is sometimes not subpar compared to drugs. When I had neurosis, I had taken a lot of drugs. The drugs were effective in the beginning, but after a long. While I became resistant, and the effect was not good after that. Later, I studied health cultivation practices on my own and read a lot of health cultivation books and watched lectures. Then I began to try moxibustion, standing qigong, meditation, Six Healing Sounds, ..etc. After more than a year of rebooting and health cultivation, my physical symptoms have basically disappeared.

Therefore, it is indeed very important to cultivate health. The reason why many brothers run into repeated symptoms so easily, the reason why the body has not noticeably improved despite rebooting for a long time is because he does not know how to cultivate health. While rebooting, he is still doing other things which damage the body. Because he lacks health cultivation awareness, he remains wholly ignorant.

The ancients said: “When food is ingested, the derived food essence is abundant. When food essence is abundant, the blood flourishes. Flourishing blood gives strength to the muscles. The spleen and stomach is the head of the 5 internal organs. The qi of the 4 organs all comes from the spleen. One should take care of the stomach during all seasons of the year.”

After symptoms are repeated, one should also strengthen therapy through diet. In order to keep up with nutrition. I have previously recommended treatment by porridge. Health porridge is quite good at strengthening the spleen and stomach, benefits the five internal organs and is especially suitable for children, elderly and those with weak constitutions. Gao Wei recorded 38 kinds of porridge foods in the “饮撰服食笺”, such as Gorgon fruit porridge, lotus porridge. Food may benefit the essence and qi, strengthen the intellect, sharpens the ears and the eyes. Yam porridge can cure deficiency weakness and asthenic hotness, ..etc.

In nursing the health via diet, it is also necessary to pay attention to keeping the diet light. Since ancient times, there is the saying of “Lightness must go hand in hand with heavy taste” in China. A light diet is one of the important principles of food and nutrition. Gao Wei believes that “People add many flavors to the food, nobody knows the natural taste of the food. The natural food is sweet and delicious by itself, it is not inferior to added flavors.”

The famous doctor Zhu Danxi also emphasizes very much on light diet, he lived to 87 years old, still physically fit, energetic and quick-thinking in old age. He pointed out: “The human diet consists of no more than 5 flavors. The taste is either natural or artificial. The natural flavors consist of grains, vegetables, and fruits. The original qi is found in the natural flavors. it supplements the Ying, the said comes from the [Inner Canons of the Yellow Emperor].”

It is said in the [素问]: “Essence gives birth to life”. The essence of the kidney includes “prenatal essence” and “postnatal essence”. Prenatal essence is given by the procreation of one’s parents, it comes through birth and is the original material that goes into embryonic development. Acquired essence refers to the food essence which is formed via the intake of food, transformed by the spleen and stomach into food essence, it resides in the kidneys. The kidneys mainly store the essences.

[素问] also mentions: “The kidneys, the main function is to store essence, here resides the essence”. A person will certainly experience the stages of life, old age, illness, death, and each stage in the growth or decline of the body depends on the ups and downs of kidney essence and kidney Qi. Nowadays, many harmless views are really ridiculous and completely contrary to the science of Chinese medicine, it is really a sinister fallacy.

It is indeed proposed in [景岳全书]: “He who is adept at health cultivation must preserve the essence. When essence is full, then qi is abundant. Abundant Qi leads to a complete spirit, a complete spirit leads to a healthy body, a healthy body leads to fewer illness.” While rebooting, we must learn the way to keep the essence. Essence is to a person as oil is to a lamp. And there are many ways to hurt the essences, such as staying up late, anger, consuming cold drinks, excessive force, frequent nocturnal emissions, and other factors, all will lead to damage to the kidney qi. Therefore, while rebooting, one must study health cultivation so that the number of symptoms repeated will be greatly reduced along with the improvement of health cultivation awareness.

### Active treatment, medicine conditioning

If the symptoms are more serious, you can go to the doctor. Through conditioning via medicine, symptoms will become relieved or even disappear. As long as there is relapses or frequent nocturnal emissions during the reboot, the repeated symptoms will not be very serious and will be relieved after 1-2 days of rest. But some brothers have a long history of sustaining essence injuries while doing a poor job at health cultivation, therefore, his repeated symptoms may be quite serious. At this time, he should seek active treatment.

30% treatment, 70% health cultivation, one must put more effort into health cultivation and research. When health cultivation awareness has increased, the number of repeated symptoms will be greatly reduced. This is because you know which factors are likely to lead to repeated symptoms. This allows you to learn to avoid these factors, thus keeping the possibility of symptom recurrence to a lower level.

When undergoing conditioning through medication, one must take care of to prescribe the right cure for an illness in order to get better results. In addition, one is to also pay attention to not relying on drugs, especially drug abuse. After many brothers run into symptoms, they would resort to buying medicines online. It is very likely that they have not made the correct diagnosis. Therefore, it is best to go to the Chinese medicine for conditioning and only taking medicine after that, this is the most secure approach.

Many people buy medicines through the Internet, the medicine they buy is completely aphrodisiac. Once ingested, the effect is likely to be counterproductive. Aphrodisiacs have been around since ancient times and have become more prevalent today. In this age of unchecked evil debauchery, the advertisements of various aphrodisiac drugs can be described as flying all over the sky. After taking this kind of drugs, one feels alive, as having had a boost of stimulants. After ejaculation, one is completed wilted. Many people have been completed withered away, unable to summon up their spirits. Therefore, aphrodisiac should be taken cautiously. If you rely on taking aphrodisiac to indulge, it is really self-destruction. Previously, there was a report that the use of aphrodisiac caused kidney failure. There was even a case of sudden death following the intake of aphrodisiac, isn’t it fearful.

## Final summary

When encountering the period for repeated symptoms, do not panic. One should learn to calmly deal with it. The process of recovery is inevitably tortuous, it is not smooth sailing. We must learn the way of health cultivation so that the frequency of repeated symptoms can be reduced and finally becoming stabilized.

Most of the modern people’s health concept is based on “supplement”. Many people do not have the concept of “guard”. They only think of supplementing health when the body is showing signs of deterioration. At this time, one has already lost a bit of the initiative. If one can avoid those kidney damaging causes and is truly able to guard (the essences), then you can fully grasp the initiative. For the factors that can lead to repeated symptoms, we must learn to avoid them.

[The Inner Canons of the Yellow Emperor] says: “The ancients used to teach; everyone speaks of the avoidance of external evil influences, one must avoid them”. When one is able to avoid the factors that cause symptoms to be repeated, then the number of iterations can be minimized. In the [Inner Canons of the Yellow Emperor], rest has been especially emphasized, “Do away with desire, righteousness will come, internalize the spirit, no illness will come”. It points out that the thoughts are quiet and pure, and there are no distracting thoughts, the harmony of the vital energies can be maintained in this way and illnesses avoided.

[灵枢] also puts forward the requirements of emotional health: “The wise person cultivates the health. One must adapt to the changes of the seasons, moderate between happiness and anger, restrain the Ying and the Yang. If this is maintained, then no evil can enter, there will be longevity”. When we encounter repeated symptoms, emotional management should be especially emphasized. Keeping calm and the speed of recovery can be quickened.

[Book of Rites] says: Wealth nourishes the house like virtue nourishes the body. Sun Simiao wrote in [千金要方]: “When the character already possesses kindness, illnesses from within and without will not arise, calamities will have nowhere to grow from”. The [寿世保元] of the Ming Dynasty says: “There is merit in accumulating virtue, the frequent accumulation of secret virtue is able to prolong the years”. Zhang Jingyue wrote in [先后天论]: “Only happiness is able to nurture health, the person who seeks happiness in desire might as well perform kindness”.

Shi Tianji, a health cultivation specialist in the Qing Dynasty, believed that “The person who is adept at health cultivation places virtue first, assisted by the nursing of the health”. Constantly quieting the mind has been proposed, along with the frequent practice of authentic wisdom, joyous mind, kind heart, friendly and optimistic mind, ..etc. The cultivation of virtue is treasured in health cultivation. While rebooting, we must do good deeds, helping others, doing more good deeds. In this manner, the number of repeated symptoms will be greatly reduced.

The highest state of health cultivation is the cultivation of the heart. The heart must be kind, broad and tolerant. The so-called: the one who is riding himself of lust is free and unfettered like the heavens and earth, his virtuous fragrance is being spread by the cool breeze!
