# Season 41  Controlling nocturnal emission examined in detail

## Foreword {-}

### Avoiding details when sharing your experiences {-}

Many brothers in the rebooting forums share their own experiences. Sharing experiences is a good thing, it can give others warning and enlightenment. However, when sharing the experiences of indulgence, we must pay attention to avoiding details, because those sensitive words can easily cause evil thoughts which lead to relapses. Some friends experience leaking upon reading the texts, others are unable to calm themselves for extended periods after reading them because it evokes their own memories of indulgence. Therefore, when we share our own experiences, we should dilute the specific process and details and we should aim to highlight the dangers of masturbation instead. This not only serves as a warning but also prevents the formation of evil thoughts with the readers.

### Relapses in winter holidays {-}

Winter holidays and Chinese New Year holidays are peak periods for relapses. The number of posts about relapses in the rebooting forums has increased significantly. Some friends relapse once a day and even several times a day, making themselves very helpless. They call for help in their posts and are like a plane that is out of control. Knowing that one is about to crash while being unable to overcome the temptation demon and the addiction. It was the same for me back when I was still a student. During school days, everything was fine. Whenever it was a weekend or a holiday, I would continuously relapse, I was no match for the temptation demon.

The temptation demon loves to test you when you are bored. If you are rebooting the brute force way, then you are surely defeated. This is because, for people who are brute force rebooting, their awareness has not yet been substantially improved, they are doomed to fail!  **Success in rebooting = high awareness + strong vigilance.**  This is the success formula that I have summarized. If you are blindly rebooting, then what awaits you is failure.

After relapsing, don’t be discouraged. The key is to learn from the relapse in order to do better next time. Some brothers have never taken the time to reflect, nor regretted after relapsing, nor have they learned from their experiences. This will only lead to worse and worse rebooting results with less and less confidence.

The consequences of relapsing during winter is doubled because winter is the season for storing essences. If storage under winter is poor, the physical condition of the coming year will be affected. And the probability of running into symptoms following relapse during the winter is quite high. If one carelessly relapses during winter, one must pay attention not to repeatedly do so as it is too damaging for the body.

Only when the realization is raised can the temptation demon be defeated. Everyone must remind themselves every day: Be sure to do everything possible to improve one’s realization! Raising the realization is like leveling. Only when a certain level is reached can one compete with the big BOSS. Don’t even think about it otherwise! Or there will only be room for abuse.

### Where to find rebooting articles {-}

Quite a few brothers have asked me where to find rebooting articles, they want me to recommend some rebooting articles every season. When I first started to reboot, I read the quality articles first. Therefore, I recommend rookies to read the category of quality articles several times, take more notes, think more and summarize, and then review more and learn from the old. By doing so, realization will slowly rise. If you have a strong learning ability and a high level of realization, then your realization will improve quickly.

With regards to good articles, one should read them repeatedly. Furthermore, try to remember key sentences and paragraphs, this is also very important. As to the experience threads created by the veterans, one should emphasize reading them. This is because they are the summaries of life battles and are not general discussions, they have a very strong sense of direction and guidance. While reading the articles, you can also read more books to enhance your realization. I’m now basically reading books to raise my realization. Realization is the king of the reboot.

### Time standard for successful rebooting {-}

Last season, I mentioned the time standard for successful rebooting, that it is half a year or one year. Some brothers mentioned that the standard is 3 years in order to be counted as a successful reboot and questioned whether half a year is considered to be short. In fact, half a year or three years, the two are not contradictory. The three-year standard of the rebooting forum is relatively safer and more reliable. The half-year standard I mentioned refers to those with a high level of realization. People with a medium level of realization need about a year or so, and those with a low level of realization will need more than 2 years.

For example, it takes the average person 3 years of mathematics in junior high. Some people with a high level of realization are unusually talented. They may be able to finish all 3 years of mathematics in half a year. They may even feel “hungry” after that and want to learn high school or even university level mathematics. This is actually the difference between the various levels of realization.

Some brothers increase their realization as if climbing stairs, for others it is like taking the elevator, increasing their realization super quickly. Veteran brothers should have noticed the existence of such brothers. The rebooting forums are like a big class, there will always be students who excel as well as students with low levels of realization. But as long as you keep learning, you will always succeed. Just like the race between the tortoise and the rabbit, don’t give up. Even people with low realization will be able to reach the finish line.

### The stabilized period of rebooting {-}

The most important sign of rebooting success is entering the period of stabilization in which sexual fantasizing is basically gone!

The stabilized period of rebooting is the ultimate state that many brothers dream of. It is like the top of the pyramid. When you have entered into the stabilization period, then you have basically succeeded. As long as you can maintain enough vigilance to hold on to the results, then it can be considered completely successful. Brothers with high realization can enter the stabilizing period in about half a year.

The biggest feature of the stabilization period is: the basic absence of sexual fantasies! Fantasies will not occur in for 10 days or more, one is in a very stable rebooting period. At this time, the feeling of suffering will disappear, and you will not care about the number of days. After entering the stabilized rebooting period, one doesn’t have to study rebooting articles daily, one should read the articles periodically and then pay attention to staying alert.

After many senior brothers have entered into the stabilized period, there is extremely little sexual fantization. At this time, one thinks that one will never relapse again and so the vigilance awareness is relaxed. Scarcely realized is that the relaxing of the vigilance consciousness will induce relapses, no matter how long one has been rebooting. When the vigilance is lost, the temptation demon will take advantage of the situation. Therefore, vigilance awareness cannot be emphasised enough. Be especially wary of the temptation demon’s instigations. Instigating you to try out your determination and test your sexual abilities.

Continuously learn to raise the realization, when realization reaches a certain degree, one naturally enters the stable period of the reboot. When conditions are right, success follows naturally. The reason why you enter the rebooting stabilization period is that your realization is already strong enough to defeat the temptation demon. The demon is like a wild horse. When you can tame this wild horse, it will become obedient, stable and not cause trouble, sexual fantasies will disappear or become very rare. But even a wild horse that has been tamed will occasionally throw a temper. So be alert everyday after having tamed the horse. By being careful the ship can be steered for ten thousand years!

The world is a family, the rebooting forums and its brothers are actually comrades in the same trench of battle. Everybody may have different views but the motivation is the same, that is to help more people wake up and help more people find their healthy and optimistic selves. On a macro level, society is made up of people, purifying the people is purifying the society, raising virtue and promoting harmony. When people from other forums come to this rebooting forum in order to make posts, I’m also supportive of it. Sometimes, I also go to other forums in order to study. Everyone is united and can accomplish the great work of rebooting better and better.

## Controlling nocturnal emissions {-}

We will enter into the main topic below. In this season we will talk about controlling nocturnal emissions in detail:

I have written a few seasons about the nocturnal emission problem, and I will talk about it thoroughly in this season. If you compare rebooting to a sport, it can be said to be a Triathlon. Putting a stop of sexual fantasies is one of the events, vigilance awareness is another one, how to control nocturnal emission another, as is emotional management, health awareness, and studying awareness. To be precise, they should be called  _“The 6 topics of rebooting”_. Just like the high school and university entrance exams are not about a single subject but several subjects, such as 3+2 or 3+ integration. 

These 6 rebooting topics can be summarized into one term and that is total realization! This is comparable to the total score of the college entrance examination.

This season, I will talk about this special topic of controlling nocturnal emissions in detail.

### Controlling nocturnal emissions is important {-}

To better recover the body, it is extremely important to control the frequency of nocturnal emissions. Although many brothers are persistently rebooting, they are unable to overcome nocturnal emissions which leads to a collapse of the health. I remember there was a brother who had been rebooting for the better half of a year, but he also had nocturnal emissions during that time. He didn’t have varicocele before and after half a year of nocturnal emissions, he was diagnosed with varicocele after visiting the hospital. TCM: *long term nocturnal emissions injures all of the eight extra meridians!*

Frequent nocturnal emissions are very harmful to the body, they are not conducive to the recovery of the body. Frequent nocturnal emissions easily give rise to repeated symptoms or the aggravation of symptoms. Therefore, we must strictly control the frequency of nocturnal emissions. Controlling nocturnal emissions can be made a separate topic of study. Brother Austin is specializing in frequent nocturnal emissions. I have been plagued by frequent nocturnal emissions in the past. When I first started to reboot, I didn’t have this problem, because I was so heavily over-drafted anyway, normal nocturnal emissions did not occur for a long time into the reboot. Because some brothers have been masturbating since puberty, they have never experienced nocturnal emissions, they have no idea what it’s like. Some brothers have weak constitutions, they may leak while they are not rebooting, the destruction is simply doubled, and health is greatly damaged. It won’t take long until the body cannot handle it any longer and for the symptoms to multiply.

### Factors lead to nocturnal emissions {-}

Before, I also spent a lot of effort in trying to control frequent nocturnal emissions. I searched for information online everyday and went through hundreds of pages of material. The focus of my research at that time was on two aspects. First, what caused nocturnal emissions? Second, was there any way to control nocturnal emissions? I kept a record of nocturnal emissions, the date and time for when I had a nocturnal emission, the days in between the nocturnal emissions along with the detailed specifics associated with each occurrence. Then I went on to study the cause for the nocturnal emission and listed the possible reasons. I then checked the Internet to see if there was a case like mine. Then I found the causes one by one. There are many reasons for nocturnal emissions, one must learn to avoid these cases, it is very important. I will list them in detail in this season.

The factors that lead to nocturnal emissions are as follows:

1.  Daytime sexual fantization
2.  Daytime tiredness
3.  Drinking wine
4.  Eating too much meat
5.  Taking tonic
6.  Sleeping facing down
7.  Sleeping naked
8.  Sun-baked blanket
9.  A blanket that is too thick and too heavy
10.  Meditating before going to bed  _(Translator’s note: brothers on this forum have questioned this point and it is a personal preference. Some people are able to meditate before going to bed without getting nocturnal emissions. For me, it is mixed; if I have been rebooting for a long time, meditating before bed tends to provide me with lots of extra energy which sometimes results in nocturnal emissions)_
11.  Underwear is too tight
12.  Bumping against or clasping the blanket
13.  Improper moxibustion
14.  Meditation and focusing on the lower Dantian
15.  Staying up late for a long time
16.  Drinking too much before going to bed
17.  Excessive exercise
18.  Illness
19.  Nocturnal emission (essence slippage) without dreams due to kidney deficiency
20.  A diet that is too spicy
21.  Stress  _(including nightmares)_
22.  Pressing or squeezing  _(including sleeping while facing down)_
23.  Anger  _(causing disorders in the vital essences)_
24.  Exposure to cold  _(including eating cold food)_
25.  Improper acupressure massage
26.  Nocturnal emissions caused by inflammation  _(belonging to the category of kidney deficiency in Chinese medicine)_
27.  Returning Yang lying pose  _(还阳卧, quite many reports on nocturnal emission)_
28.  Bathing feet before going to bed  _(water too hot)_
29.  Holding back urine  _(easy to induce nocturnal emission)_
30.  Using electric blankets or heaters while sleeping
31.  Intense exercise before going to bed
32.  Foreskin is too long
33.  Overthinking
34.  Unprotected sleep  _(going back to sleep after turning off the alarm)_
35.  Sleeping again after insomnia
36.  Profuse sweating
37.  Eating Chinese medicine  _(especially incorrectly prescribed medicine)_
38.  Doing a pedicure for a long time
39.  Eating too much black sesame

I have summarized 23 nocturnal emission inducing factors in season 16, in this season I have increased that number to 39. Many of them are based on my own experience and the conclusions from case studies. Others are based on feedback from brothers and following analysis and investigation.

### Nocturnal emission is complicated and varies {-}

The problem of nocturnal emissions is quite complicated and varies from person to person. For example, two people consume cold drinks. One of them may go home and have a nocturnal emission while the other doesn’t. This is the difference between physical fitness and state of health. Coldness damages Yang. Some people have OK constitutions and can afford to take on some damage and therefore they have yet to suffer from nocturnal emissions. But some people have weak constitutions and have already been weakened when they take in cold drinks, they immediately experience nocturnal emissions. Some people are fine after eating lots of meat, but some people suffer from nocturnal emissions right away after eating more than the regular amount of meat. Some people have nocturnal emissions if they soak their feet in hot water before going to bed while others are fine no matter how much heat they expose their feet to.

And I also found out that every year, people’s physique and health will undergo subtle changes. Last year, maybe you didn’t have nocturnal emissions after soaking feet in hot water, but this year you may have nocturnal emissions after doing the same. Last year, you would not have nocturnal emissions after exercising for a whole afternoon, this year, you may have nocturnal emissions after just a little bit of exercise.

In addition, nocturnal emissions and the seasons are also closely related. Many people have few nocturnal emissions in spring and summer. When autumn and winter arrives, they start to have them more frequently. When first starting to reboot, many people experience virtually no nocturnal emissions, but after a while of rebooting, they start to have frequent nocturnal emissions which greatly worries them.

### Stable frequency of nocturnal emissions {-}

If we want to recover better, we must have a stable frequency of nocturnal emissions, this will be very beneficial to the recovery process. The factors that causes nocturnal emissions listed by me may not leave a lasting impression with many brothers. Only after a nocturnal emission has already occurred will the impression become stronger, next time they can really avoid it.

Nocturnal emission is generally divided into 2 categories:

-   Physiological nocturnal emission
-   Pathological nocturnal emission

Generally, up to 3 times/month is considered to be normal, some articles mention about 3 times/month. If you have reached 6-8 times/month, or if you have nocturnal emission for several days in a row, it is not normal, this belongs to pathological nocturnal emission. If you can control the nocturnal emission frequency once every 15 or 20 days, it can be considered successful. If you want to recover better, it is best to limit nocturnal emissions to once in over a month.

After all, many brothers have been overdrafting their bodies for many years, huge deficits have arisen, one cannot afford to have a single nocturnal emission. One emission may make them uncomfortable for several days before they are able to recover.

### No such thing as fullness and overflow {-}

Now, let’s talk about the self-overflow of essence fullness. Strictly speaking, there is no such thing as fullness and self-overflow. It is mentioned in (圆运动的古中医学) that there is no such thing as fullness and self-overflow. The fact that there is such a saying is due to it being said by the common person. When lust moves within the mind of the common person, the original essence is transformed into turbid essence. People with a high level of cultivation are able to break through the obstacles of nocturnal emission.

While we are living in human society, full of temptations, achieving  _“no leaking”_  is extremely difficult. On the one hand, your heart must be properly cultivated. On the other hand, you need to be instructed by the enlightened Masters. Some brothers think that the turbid essence is not good. In fact, the turbid essence is very nutritious and is rich in various nutrients, it is not rubbish. Therefore, the turbid essence cannot be carelessly leaked, we need to learn to cherish it.

### Mentality adjustment after nocturnal emission {-}

The vast majority of brothers in the rebooting forums will be confronted with the troubles of a nocturnal emission. Maybe you have not yet encountered it and then encounter it next year. The psychological adjustment after having a nocturnal emission is also very important. Many people will relapse after having a nocturnal emission because it sways the mind, adverse emotions easily arise, and therefore, the peak period for relapses takes place after nocturnal emissions. After nocturnal emissions, we must pay attention to the adjustment of our mentality and mood. We must correctly view nocturnal emissions and maintain a high level of vigilance. Manage the emotions well and we will be in a good position to pass through the period that follows.

### Pathological nocturnal emission {-}

Traditional Chinese medicine generally classifies pathological nocturnal emission into the following 5 categories:  _(It is attributed under Western medicine as an expression of inflammation, such as prostatitis, ..etc.)_

1.  Heart and kidney not working in harmony: expressed as nocturnal emission during dreaming, dizziness, fatigue, and weakness. This is due to excessively vigorous heart Fire, vigorous Fire due to Water-deficiency, causing movement in the essence chamber.
    
2.  Kidney qi is not strong: expressed as frequent essence slippage  _(Translator’s note: the reader may recall that essence slippage refers to the involuntary emission of semen during the waking state)_, lacking splendor in the complexion, fear of cold and coldness in the limbs. This is due to long term unrecovered illness, the drying up of Yang essence, qi not functioning optimally, unsolid essence gate.
    
3.  Kidney yin deficiency type: manifested as nocturnal emission, dizziness, tinnitus, waist ache, insomnia and night sweats. This is due to excessive sexual intercourse, excessively draining the kidney Yin, interfering with the essence chamber, dereliction of the storage duty.
    
4.  Liver Fire prosperous type:  nocturnal emission during dreaming, irritability and easily angered, bitter mouth and dry throat. This is due to prosperous liver Fire, the disturbance of the essence chamber by Fire
    
5.  Downward flow of damp heat: manifested as frequent nocturnal emission, or semen appearing in the urine, bitter mouth or thirstiness. This is caused by the downward flow of damp heat, disturbing the essence chamber.
    

The ancients thought:  _“Nocturnal emission is associated with kidney illness, though the heart is also responsible”_  _(Translator’s notes: readers should keep in mind that it is the pathological form of nocturnal emission that is being referred to here)_. Dai Yuanli, a doctor of the Ming Dynasty, said in the [证治备要遗精篇]  _“When overthinking, the heart is unable to assist the kidneys, leading to the loss of essence; when lusting for something that is out of reach, essence is lost”_.

From the time of the Qing Dynasty, it was pointed out with regards to nocturnal emission that  _“Dreams are illness of the mind, the lack of dreams is an illness with the kidneys. He who has an emission while dreaming, has had a nocturnal emission; an emission without dreams is semen slippage”_. Nocturnal emissions are again being divided into emissions during dreams and semen slippage. Physicians of the later generation continue to use this distinction today.

### On medicine treatment {-}

Many brothers have grown to be afraid of nocturnal emissions, they are even afraid of sleeping. Some brothers on the other hand often encounter semen slippage. For brothers of this category, they should seek out treatment with a good Chinese medicine doctor. Medicinal conditioning is also an effective way to control the frequency of nocturnal emissions. Brothers who are deeply troubled by frequent nocturnal emissions should actively try out drug treatment.

It is important to find a good Chinese medicine practitioner. Nowadays there are many charlatans, many of the prescribed medicines are not matched to the symptoms, resulting in the opposite of the intended effects. I remember that some brother was eating Chinese medicine and he had 4 nocturnal emissions within 2 days and ended up like a deflated ball.

In addition, many brothers like to find medicines on their own, or listen to the recommendations of some people, thye then go to buy the medicine. By doing so, It is highly probable that the medicine will not match the symptoms. This is because what is suitable for others may not be suitable for you. For example, some brothers hear that eating Zhibai Dihuang Wan pills is good, so they go to buy it, but the result is aggravated nocturnal emission.

Therefore, brothers who are troubled by nocturnal emissions would do best to seek a Chinese medicine doctor if they want to take medicine. Specific diagnosis should be made before medicines are prescribed, this is the safer approach. Chinese medicine pays attention to investigation in connection with treatment, it is not to say that one medicine will be fully effective for treating nocturnal emissions. If the medicine is not right, it will only have the opposite effect. Some brothers enjoy good results from eating Jinsuo Gujing pills because they match their symptoms. But the same medicine is not suitable for others. The specific condition needs to be looked at before the medicine can be prescribed. And some brothers are able to control the frequency of nocturnal emissions by taking Fengsui Dan pills.

### How to control nocturnal emissions {-}

Below I will recommend several ways to control the frequency of nocturnal emissions:

-   Kidney strengthening exercises
-   The auspicious lying posture
-   PC muscle exercises
-   Sit-ups or leg raises while lying down
-   Iron plank bridge exercise
-   Standing Qigong

I will not talk too much about kidney strengthening exercises, this has been described in detail in season 3, I have even shot a video and shared it with everyone. If you are properly doing the kidney strengthening exercises and have found the correct sensation, then you can effectively reduce the frequency of nocturnal emissions. I remember there was a brother who used to have 8 nocturnal emissions a month. He persisted in doing kidney strengthening exercises and was able to reduce the frequency to once a month. Of course, it is also important to put an end to other factors that lead to nocturnal emission, especially the various factors listed above.

The auspicious lying pose is also very important, together with the kidney strengthening exercises, it is like  _“double safety”_. I saw that a brother was recommending the baby lying pose which is, in fact, similar to the auspicious lying pose. The only difference is that in the auspicious lying pose, one is facing the right and there are requirements to the placement of the hand.

The auspicious lying pose may be uncomfortable at first. For one, the hand support is uncomfortable, the other is that the leg is always nervously bent. I didn’t feel comfortable at first, but after persisting for a month, I slowly adapted and now it feels very comfortable to sleep in the auspicious lying posture. I would like to share my thoughts on the principle of auspicious lying posture because many people know that it is very good but few people who know the principle behind it.

The auspicious lying pose folds the human body, this folding is equivalent to the closing of the leaking passage below. Let me give an example in order to help everybody understand. It is like a straw, you pour water into the straw, if the lower section of the straw is folded, then water will not easily leak.

As to the specific angle of the fold, I recommend less than or equal to 90 degrees. If it is 135 degrees, it is still very easy to leak. I sleep at 90 degrees myself, less than 90 degrees is also very good but it is hard to achieve.

Great virtuous persons of the past have emphasized the auspicious lying pose, many of them have been working hard at the pose, even tying oneself into the posture and falling asleep that way. The fact that they are able to overcome nocturnal emissions is partly related to the auspicious lying pose. Generally, after a month of persisting in the auspicious lying pose, one is able to slowly adapt. In the beginning, one would definitely feel uncomfortable.

With the  _“double safety”_  from kidney strengthening exercises and the auspicious lying pose plus the other predisposing factors that lead to nocturnal emission, emission frequency can be controlled. There are many exercises for controlling the frequency of nocturnal emissions. On the internet, there should be no less than 10 different methods. The best method that I have found through my own trials is the kidney strengthening exercise. Naturally, the auspicious lying pose is very good but it belongs to the category of quiet exercise in sleep posture.

In addition, everyone may practice the PC muscle exercise, sit-ups and raising the legs while lying down as these can also play a role in strengthening the kidneys. Many friends have reported positively about the iron plank bridge exercise, but the hard part is doing it consistently. Standing Qigong can also effectively reduce the frequency of nocturnal emissions. A brother reported that he was able to greatly reduce the frequency of nocturnal by practicing standing Qigong.  _(Translator’s note: for brothers who are interested in knowing more about standing Qigong, they may search for the words “Zhan Zhuang”, there is a great Wikipedia article on it)._

## Summary {-}

I have shared my experience of controlling nocturnal emissions with everyone. Only when frequent nocturnal emissions have been controlled is there a hope for recovery. Otherwise, such frequent nocturnal emissions directly drain a person until his health collapses and the body is full of symptoms. When you have a low and stable frequency of nocturnal emissions in combination with health cultivation exercises, the body will enter into a positive cycle of recovery. Sunshine and confidence will return to you. A person is like a ball, inflated with vital essence. When the essence is vented, people are like deflated balls, listless, dispirited, wretched facial features with even a ghostly look. When you re-energize with vital essences, it is like an uncaged fierce tiger, mighty but without anger, sparks in the eyes, vigor in abundance, very strong self-confidence, no longer afraid of anything and full of enthusiasm. I hope everyone can reclaim this positive physical and mental state.

## Postscript {-}

Recently, a brother wrote in my thread that his mind is once again being swayed after having read harmlessness in moderation theories, his position is no longer firm. He wants to hear my opinion. Actually, with regards to harmlessness in moderation theories, I have talked about them many times in my articles. Harmlessness in moderation theories are fallacious, they  completely ignore the highly addictive nature of masturbation. After rookies have seen them, they want to  _“moderate”_. Now that they have found theoretical support, they masturbate even more with ease. In fact, they are completely fooling themselves and harming themselves. Who knows how many people have fallen victim to the harmlessness in moderation theories. Can one still be moderate once addicted? Can one still be in the control once addicted?

Regarding the frequency of sex, the medicine king Sun Simiao had this to say:

-   a people in his 20s may vent once every 4 days
-   a person in his 30s once every 8 days
-   a person in his 40s once every 16 days
-   a person in his 50s once every 20 days
-   a person in his 60s should close off the essences and not vent, and if he is strong, he may vent once every month

The frequency of sex that Dr. Peng Xin mentioned is quoted from the above saying from Sun Simiao.

But this passage is meant for people who lived in the past, people used to marry at an earlier age. Given that modern people exhaust their Spirit more seriously, Dr. Peng Xin recommends the frequency of sex to once per month. But when you see this number, don’t for a moment think that it goes for everybody. This standard is for healthy people, who knows how many times many people have overdrafted themselves, they are already ridden with symptoms. If they still want to reach the monthly  _“standard”_, it is nothing less than adding frost onto the snow. Many Chinese medicine practitioners have recommended abstinence for half a year or even a year or more in combination with medicinal treatment and health cultivation. Only in this way is their hope for the body to make a full recovery.

Another point that the medicine king Sun Simiao specially mentioned:  _“Men cannot do without women, women cannot do without men. If the intention moves without a woman being present, this leads to the laboring of the spirit, longevity is thus damaged”_. Masturbation is a one-sided sexual act, there is no mixing of the Yin and the Yang, this is actually very damaging to longevity. Therefore, we must quit the evil habit of masturbation and save the best of ourselves to be used moderately after marriage.

Articles which rationalize masturbation may go to hell, who knows how many youths have been harmed by it knows the truth. Young people lack ample experience and discernment. They are confused by the fallacious reasoning and harmful teachings, finally leading to a body ridden with symptoms. Their appearances likewise become ugly and wretched, their bodily development is also affected. In the end, many friends have come to such a phrase, truly a deeply meaningful phrase: I have been harmed by the harmlessness in moderation theory! What an ironic sentence.

If everyone wants to completely quit masturbation, the  _“moderation”_  level must be passed. Otherwise, your position on quitting will not be firm. The word moderation is very tempting, but I can see it clearly. For many brothers, moderation actually means once you pop you can’t stop. I will definitely not bargain with the temptation demon. Rebooting is not shopping, it is a very serious and cruel business. Because if one is unable to quit masturbation, one may be wasted by it. The actual situation is that before many people start to think about rebooting, they have already been wasted.
