# Regarding the recovery of symptoms

Recovery is a topic that a majority of brothers are concerned about. Many people start  rebooting only when they encounter physical problems. They just want to restore themselves to a healthy state through rebooting. Whether other people recover or not will affect their confidence in rebooting. If they see that many people have not recovered, they may naturally lose their confidence and motivation to reboot. Some brothers may even think that they can't recover and that therefore they should masturbate, and so they break the reboot and plant the seed for a further collapse of the body in the future.

I will share a case first:

>[Big Brother Soaring Eagle, I saw some people say that I can’t recover and I feel uncomfortable. I am not wavering now and I know I want to continue. I am 23 and have been abstaining for almost 1 year. Can I recover? 


**Answer**: There is no need to feel distressed. Some people recover in a certain amount of time, and some people's health takes longer or shorter. It's normal. Do well in all aspects and recovery will be guaranteed. Keep going! I suggest that you 
exercise actively and pay attention to health preservation. Work hard on health preservation, learn more through health articles and videos, and improve your health awareness. It is 
difficult to recover if abstaining only and not cultivating the health.

**Analysis**: Many people are discouraged when they feel that they can't recover, their confidence is shaken, but they don't want to quit. Posts that shake the confidence of brothers still appear from time to time. If you read them and are affected, it will be detrimental to your rebooting. Many people are not firm in rebooting, and the foundation is not stable, and it is easy to get upset when they read these articles. For example, if ten people reboot, one of them really recovers, but the other nine people have not yet recovered. You should learn from those that have recovered. Those who really recover have their own health regimen and recovery experience.

*A word to everyone*: To recover, you should ask the person who has truly recovered. Those who have not recovered will only tell you that you cannot recover. In the beginning of my reboot, my hair loss peaked, and I went to many hair loss forums. Most said, that it is difficult to recover, and that one would still have gray hair related issues. It is difficult to find cases of recovery, but everyone must know a truth. Just because you do not see something does not mean that it doesn't exist. Just like when you buy a lottery ticket and you don't win 5 million, it doesn't mean that no one wins 5 million. Of course, the probability of 
symptom recovery is not that low. As long as all aspects of health are maintained, especially health 
preservation, the possibility of recovery is still very high. Keeping complete recovery aside for a moment, at the very least health can be improved greatly. Some brothers are badly injured, over drafted or have poor physique. If they want to recover,
they will need to get rid of their illnesses and recover little by little. If a health regimen is not well maintained or
the frequency of spermatorrhea is uncontrollable, recovery will become unlikely. It will go backwards, and only 
by keeping patience can we hope to eventually recover.

Rehabilitation is a systematic project, and senior brothers should be aware that it is difficult to completely reboot, and it is also difficult to recover. It is not easy to overcome one difficulty but to overcome both difficulties, a high level of rebooting determination is required. General awareness and health awareness. 

When you feel that rebooting and/or recovery are difficult, you will definitely worry that you will not be able to do it. In fact, if you really master the method, it will not be difficult. You just need to know how to recover. There is always a way to succeed, it just that you haven’t found it yet. Just like when playing games, there are game cheats. I was always looking for recovery methods, and had also been trying recovery methods, which helped me a lot.  First of these was the kidney strengthening exercise, which allowed me to control the frequency of nocturnal emissions; Second, standing and meditation; third, 
aerobic exercise; fourth, moxibustion. Moxibustion is indispensable. Moxibustion cured my allergic rhinitis and hemorrhoids, and it had a positive effect on the 
improvement of my physical fitness. Moxibustion is inexpensive, but you must have a certain understanding and knowledge of moxibustion. Constantly accumulate practical experience, and 
continue to deepen your understanding.

## About the bottleneck period of recovery {-} 

Some brothers are cultivating health, but if they recover to a certain level, they will feel stagnant. In fact, they have encountered bottleneck period. It is normal to encounter a 
bottleneck period. To break through the bottleneck period, you need to find a way through. Just like any technical difficulty, to overcome it, you must further improve your health 
maintenance practices and health awareness. This is similar to running. When you work hard for a certain period of time, you can run 100 meters in 12 seconds. You will then find that you have been hovering around 12 second mark for some time and there has been no further improvement. At this time, it is convenient to have a senior coach. The coach will tell you how to break through the bottleneck period and how to further 
improve your exercise level, allowing you to cut down to 11 seconds or even 10 seconds. I once read an article by a track and field coach. He said that professional track and field athletes need at least three years of systematic and professional training to run 100 meters in 10 seconds, with the exception of 
certain talents of course. If we encounter a bottleneck in the recovery period, we should learn more through health articles. We can try many health maintenance methods, and then find a health maintenance method that suits us and persist in practicing. For example, if you can learn the essentials and 
persevere, many symptoms of your body will be greatly improved. There are also real life cases of people alleviating or eliminating diseases through Tai Chi and yoga practice. Medication is not as good as food, and food is not as good as movement. Many people know that aerobic exercise is good, and they sweat profusely every day when they run. It doesn't take them long to find out that their body has weakened and has entered a period of exercise fatigue. Always remember **Spirit**. 

Chinese medicine is not incorrect when it says that sweating hurts Yang. Some people are young and have good physiques and can afford to hurt them, but if they keep doing this, they will be prone to problems. At one time, the Ma Jiajun track and field team paid great attention to the recovery and conditioning of athletes after exercise and boiled Chinese medicine tonic soup for team members every day. I was able to recover and constantly break through the bottleneck period. At the time, I saw an article saying that heel-lifting can stimulate the Chengshan point of the calf, which is similar to Baduanjin’s "Seven Dilemma and Hundred Diseases Behind". So 
I did several hundred repetitions every day. One time, I even did a thousand repetitions. I walked with heels raised when
I walked. I found that raising heels not only improves physical fitness, but also improves jumping ability and makes calves go from strength to strength. But when we do a certain exercise, we must have a good grasp of the essentials, and we shouldn't blindly practice it. Just like how when some brothers discover that squatting is good, they practice it 500 times a day, and finally their knees are broken. When squatting up, the 
knees should not exceed the toes, and the knees and toes should be in the same direction, so as to avoid adverse effects on the knees. Otherwise, if the knees pass the toes for a long period of time, the pressure will be transferred to the knees, causing knee wear and tear or other knee related problems. We must practice in the correct way and avoid practicing blindly.

*Another Case:*
>"Sperm emission is used to strengthen the kidney, and recovery from prostatitis depends on taking medicine and 
nutrition. These two can help 80% of the recovery after persisting for more than half a year. However, based on my experience of staying in the forum for more than a year, no one can cure premature ejaculation. Some people have not cured premature ejaculation after a year of abstinence, and many people’s premature ejaculation has not changed at all. Facts have proved that, to a large extent, premature ejaculation is likely to be permanent once the second shot is achieved." This was sent by a brother. Teacher Feixiang, do you think this makes sense? It seems not be the case.

**Answer:**
This brother makes a good point in saying that restoration is a systematic project. In my experience, I have seen brothers post about improvements, and there are still cases of recovery, but many people are very damaged and suffer from severe injuries. In these cases the recovery of premature ejaculation and impotence is basically measured in years. And it must be a 
thorough abstinence + health maintenance, both of which must be in place, and strict control of dysplasia must be performed. Many people can't even quit completely, so how can we talk about recovery? If I don’t have health awareness, how can I talk about recovery? Lets be real.

**Analysis:** 
I emphasized the importance of health preservation in a very early article. Why do my answers emphasize rebooting and health preservation? Why don't I just talk about rebooting? 
Because I am deeply aware of the importance of keeping good health for recovery, just abstaining will not lead to an ideal recovery. Many brothers put all their hopes on rebooting, thinking that everything will be fine when you start rebooting. In fact, this understanding is wrong. rebooting is only one aspect, and health preservation is a very important facet. 30% treatment, 70% health preservation. Health preservation includes rebooting and maintaining essence, as well as acquiring various health preservation knowledge and health preservation techniques. 

The importance of health preservation is self-evident. There are still many brothers who place all their hopes on doctors and medicines. They have no awareness of health preservation at all. They think that kidney deficiency is the same as a cold and can be solved by taking a few pills. This understanding is also wrong. If the symptoms are severe or persistent, they should be treated actively, but don't put all hope on the doctor. For all 
kinds of symptoms caused by kidney deficiency, the most important thing is to pay attention to maintenance. Just like a after purchasing a new car, it can still be 90% new after one year of maintenance.

Maintenance is really important. As soon as professional athletes have finished training, they will receive ice, massage, infrared physiotherapy, and acupuncture. There are too many recovery 
methods, and the recovery and maintenance methods of NBA players are even more diverse. Many of them are high-tech, and the average person hasn't even heard of them. I was able to recover, and the efforts put into health preservation were superb. 

I was always learning knowledge related to health preservation in Chinese medicine, and I tried many health preservation techniques myself. I have seen rumors from some brothers that I 
had only indulged a few hundred times in more than ten years, which is why I could recover. How is this possible? At that time, I shot up to 6 times a day, and the last shot was water. It got so serious that there was nothing to left to ejaculate. At that time, my addiction was very strong, and it directly dragged me to 
the symptom hell. Brothers who have read my article "Rebooting as the Best Remedy" should know that my sperm injury was very serious, and I had severe neurosis. It was extremely painful to cure neurosis. Compared with neurosis, prostatitis is really 
insignificant. Neurosis a big witch. 

When I was neurotic, I wanted to commit suicide every day. I lived in a state of anxiety and panic every day, and people around me couldn't understand my feelings. I really broke down then. I became a medicine jar. Now there is a box of unfinished medicine at home. It has expired. It contains dozens of medicines. If I don’t throw it away, I just use it to remind myself, what happened when I stayed up late and indulged. Living in hell, I never want to return to the symptom hell, it is simply inhuman torture. There was a brother who joined an anxiety group out of curiosity. He was so scared that he quit because he found that the people inside were too gloomy, and the content of the chat was all painful symptoms, the atmosphere was very depressing, and many people thought about suicide. 
Thoughts of death. So I came up with a mantra, which was: "PMO is hell!"
Some brothers haven't recovered after a long time and they think that recovery is a lie. This is a bit like seeing only white swans, and narrow mindedly believing that black swans do not exist. This kind of argument will indeed give a blow to one's confidence. I once thought that prostatitis cannot be cured. I talked with many people who said that prostatitis relapses and medicine only works temporarily. Many people are severely injured, they are also not young anymore and recovery is very slow. Senior brothers have also concluded that the recovery period before the slowdown is more than one year. This year is a year of rebooting and health preservation. Particular attention should be paid to health preservation. Dao, active exercise and proper aerobic exercise can greatly relieve prostatitis. I have always advocated doing more aerobic exercise in order to recover from prostatitis faster. But you must pay attention to intensity and frequency. If you sweat profusely every time you perform an aerobic work out, it may have the opposite effect on recovery before the slowdown. Nowadays I mainly walk or walk briskly. When the body heats up and sweats, I slow down and try my best. Don't sweat. Sweating is a double-edged sword. On the one hand, body toxins are excreted from the body with sweat, but at the same time, the essence is also leaked out in the form of sweat. **TCM**: *sweat = essence*. Sweat is the fluid of the heart. There is a kind of energy in the human body. This energy can be converted into several forms. It can be converted into sweat, body fluid and essence. Just like water, it can be gaseous, solid ice, or liquid. In fact, it is a kind of energy. A human being is an energy body with an invisible energy value. All aspects of the body's operation need the support of this energy, just like the battery in an electric rabbit. When you get sick due to masturbation or bad lifestyle habits, your energy is actually decreased. Discharging will lead to a decline in the body's energy value. Staying up late will also cause you to get angry, 
sweat excessively and cause other discomforts such as being irritated by wind and feeling cold. Listening with earphones hurts the kidney too much, talking too much hurts the qi, in short, there are many ways to hurt energy, and long-term sitting for a long time and listening are regarded as leaking energy. What we have to do is to save energy and minimize energy loss. Energy leakage in life is impossible to prevent, and it leaks unconsciously. For example, too much thinking is also leaking energy, and because you don't have health awareness, you may not know it at all.

Qu Limin wrote in one of his books that women should not be exposed directly to wind after giving birth, nor should they read books, because women are weak after giving birth, that is, their 
energy level drops very low, their resistance is insufficient, and they are very likely to get sick when exposed to a windy environment. Reading books can cause liver damage and blood leakage. Their body is already weak and cannot withstand further leakage. Therefore, pregnant women are advised to rest after giving birth. Some brothers may say that the more you exercise, the stronger you are, because fitness usually follows the principle of *over recovery (extra compensation)*. Through exercise, you can recover to a higher level than before, but 
under the condition that your body is still healthy. If your energy value is already very low, you can't stand the fatigue. When you are in good health, the more you exercise, the better you get. Of course, I mean exercise in moderation; when you are weak, it is best to adopt a calming strategy, otherwise exercise is likely to be counterproductive. Just like I a bicycle  instructor I know about who took a class when he had a cold, and it caused myocarditis. He was only in his early 20s.

The reasons why there are few cases of recovery from premature ejaculation in rebooting forum are as follows:

1. The recovery of premature ejaculation and impotence is basically measured in years. Many people have not been rebooting for that long.
2. To recover, you must have a high level of awareness in health maintenance. If you give up, the effect of recovery will not be ideal.
3. The bottleneck period of recovery cannot be broken, and the proper recovery methods and means are not in place.
4. Unmarried forum members make up the majority, and many forum friends who have quit for more than half a year dare not try and find out (*which is the correct view to take*).
5. When there is no sex life for a long time. It is very likely that the first sexual encounter will lead to "newly married premature ejaculation" occurring.
6. Many brothers do not reboot completely. They are rebooting intermittently, which greatly affects recovery.
7. If you quit for the sole purpose of restoring sexual function, you are more likely to want to try and therefore relapse i.e. not reboting properly. This kind of motivation will easily break the reboot.

Sexual dysfunction can be expected to heal over time, and I have also seen cases of full recovery. Some time ago, a married brother said that he had premature ejaculation and impotence, and he could not get an erection. After six months of rebooting, he could get an erection and engage in sex life. There aren't many cases of recovery, but this does not mean that there are none. If all aspects of health cultivation are handled well, there is a high probability of recovery. At the very least there will be improvement which will be healthier version of you than in the past. If a brother posts the reboot forum saying that he has recovered from premature ejaculation and that he has half an hour or even more than an hour of activity, or that his girlfriend and him have spent a long time doing it, such posts are likely to be deleted. Because the rebooting forum does not promote pre-marital sex. In addition, a long duration sexual activity is not necessarily a good thing, it may be an ejaculation disorder, and erectile congestion is also very harmful to the prostate anyway. Too long and too short are both not good things. To recover from premature ejaculation and impotence, you should refer more to brothers who are married and have been rebooting for more than half a year. They have statements have more validity, but married people who reboot are in the minority, and there aren't many married people who are firmly vigilant. It is necessary to support and cooperate.

In fact, many unmarried brothers have their own unique experiences. For example, morning erections may have recovered and the quality of the morning erections may also have improved. Another point is that the morning erection is relatively stable. When the quality of your morning erection becomes good and stable, it is a sign of the recovery of the 
sexual function. Some brothers may say that their morning erection is not good, but their sex life is okay, this situation also exists, but you can be sure that this is not the optimal state their bodies could be in. There is a word for this: *impulse!* Many people are injured to the maximum, their semen is dripping, their ejaculation is weak, and the shooting distance is not what it used to be, much worse than it was in the past. This is the performance of an impulse that is gone and kidney qi that has been lost. Regarding the mystery of the distance, I once wrote about it in an article, and friends who are interested can take a 
look.

To recover better don’t stay up late or sit for a long period of time. Health preservation is a kind of knowledge. Only when you learn more, think and practice, can you find a way of health 
preservation that suits you, and you must constantly improve your awareness of health preservation so that you can learn more about health preservation and practice it. Keep improving, so the chances of recovery are greater. In particular, it is necessary to avoid a lifestyle that hurts the soul and the body,
and attention must be paid to emotional management. Prostatitis is also prone to recurrence, especially after spermatorrhea. Therefore, we must control the frequency of spermatorrhea and pay attention to all aspects, so that the repetition of symptoms can be greatly reduced, stabilize, and then finally heal. The law of healing is: We move from the negative cycle to an unstable positive cycle, and then, (provided  we pay attention to our health regimen) we move from the unstable positive cycle to the stable positive cycle.

**Negative cycle → unstable positive cycle → stable positive cycle!**

The recovery of other symptoms is basically the same. It is normal for symptoms to be repeated. Don't worry, taking good care of yourself and reducing the number of recurrences is key. It's like walking a tightrope. In the beginning, one will fall off, but after gaining more experience and lessons, one will gradually stabilize and will rarely fall off.

Regarding the *"irrecoverability theory"*, there is actually a certain truth, after all, it is the conclusion drawn by the brothers' own experience. When I experienced neurosis, *"irrecoverability theory"* was also popular among patients. Regarding irreversibility, there was a famous saying that went: *We are like 
broken vases, no matter how much we glue together, we cannot fully recover. After breaking a vase, no matter how it is glued, it will leave cracks.* There is a certain truth to this sentence. Can a person recover to the pre-development period through rebooting and health preservation? The human body is always aging. Even if you don’t take care of it, your body will go downhill, but indulgence accelerates this process, and even accelerates the pulse of a 60-year-old man to a 20-year-old young man, which further accelerates aging dozens of years. But irrecoverability is not absolute. Some brothers actively exercise after quitting and feel that their body is stronger and their spirits better than before. From this perspective, isn't the recovered state better than the state before?

Can various symptoms caused by the *elbow tube* be recovered? In fact, recovery can be interpreted in two ways:

1.  It is basically impossible to recover to a prior state because people naturally age.
2. It is possible to return to an asymptomatic state and recover one's full energy capabilities.

Even if you are a brother for whom full recovery is difficult, rebooting and keeping good health can at the very least relieve symptoms to such an extent that things won't get worse. One fact is certain. If you don't reboot or maintain health, your body will collapse faster and horrible symptoms will be waiting for you. If you have a deep understanding of health preservation, you will be more confident of recovering. I also encountered many pessimistic arguments at the time, but I never wavered because I believed that I could return to an asymptomatic state.

Seeing cases of recovery can motivate everyone to move forward. When you see cases that have not recovered, you don’t have to get discouraged. If someone doesn’t recover, it doesn’t mean you can’t recover either. What we need to do is to strengthen our rebooting confidence, and then do our health
maintenance routines. Do a good job, but realize that health preservation is the key to recovery. We must learn to work hard in health preservation. 
Health maintenance is divided into health cultivation and mind cultivation. We must pay attention to cultivating the mind, do more good deeds, accumulate more virtue, and donate more positive energy. When the heart is right, the body will follow. It is like a puzzle. *The front is the world map, and the back is It takes a long time to assemble a character avatar, and it only takes a few minutes to assemble a character avatar. If the avatar is spelled correctly, the world map will follow.* 

Cultivating the heart is like putting together the portrait of a character. Cultivating the heart is more important than self-cultivation.

Next season, I will recommend a secret of facial restoration. Mastering this secret will bring about changes in your appearance with each passing day. Please look forward to it. 

*A poem*

**"Tuguan is Hell"**

*I saw shells hit China one by one
The shells are filled with AV
China's young generation
Falling down by tens of millions
Flew over with the cannonball
There is also a leaflet about moderate harmlessness
After reading these leaflets, the youth
Feel more at ease
But the symptoms will never let them go
Symptoms will drag them back to reality
Warm water frogs will wake up sooner or later
In fact, they know that harmlessness is not reliable
Because the symptoms are obvious
After every indulgence
There was a trace of regret in their minds
Then came the harmless theory
Constantly anaesthetize yourself with a harmless view
Keep deceiving and comforting oneself
Get deeper and deeper in the trap
Can't control and extricate themselves
The once innocent eyes disappeared
The once clear and bright complexion is gone
The once sunny and cheerful mentality is lost
Man in the mirror
Became a double-faced person
In the eyes of parents, teachers and classmates
He or he
But only he knows
He is no longer the original pure self
What's more, walking dead appeared in the mirror
A monster appeared, a monster with pustules and acne,
Deep sunken cheeks or swollen face
Ghostly and wretched
Looks like a waste
I see
A certain young man took out a picture before the tube
He burst into tears
The child in the photo is handsome and handsome
And now he
It's just a trash that makes me feel sick
I saw a certain youth
Start to evade the mirror
Because the person in the mirror has become extremely ugly
He is different from the previous one
Now he sees the mirror and wants to smash it
To know
How much he liked looking in the mirror before
And now there is only infinite inferiority and helplessness
Shrouded him like a dark cloud
I see
A young man went to the doctor
The doctor's ruthless sentence
You have prostatitis
You gotta
You have premature ejaculation
I saw him at the toll office
Pay for your own indulgence
I see
A young man lying on the operating table
He asked himself
Why do I appear on the operating table
Then he cursed fiercely in his heart:
Damn it
Damn harmlessness
It hurt me!
He was lying helplessly on the operating table
Like a lamb to be slaughtered
Afterwards
You will find that your life has become a tragedy
Happiness is so short
But the pain is always there
Torturing you repeatedly
Afterwards
You will find that stubbornness can cause so many symptoms
And I only knew two or three
In fact, there are dozens or even hundreds of
You hit too much
But know too little
Tragedy of your life
The foreshadowing was laid when he first smashed the pipe
】】 is hell
All you have to do now is
Quit it completely
It's like an old smoking gun to quit cigarettes
Just like an old drunkard quitting alcohol
You have to quit fucking
No choice
Don't let arrogance ruin your health
Don't let arrogance ruin your appearance
Don't let arrogance ruin your whole life
When you finally crawl out of the hell of control
When you breathe the first pure air
You even howl and cry
The sun cares for you again
Then you will really understand
What is treasure*
