# On the secret technique of complexion and complexion restoration

## Foreword:

A brother said that it’s everyone's blessing to be able to come to rebooting. I agree with him very much indeed. Think about it, in today's world of harmlessness theories with the same views being spread through the internet. How many people can really understand the truth of rebooting? The vast majority of people are still desensitised & addicted under the control of the harmlessness/innocence doctrine. Brothers who can stay in the rebooting forum are definitely blessed and have good roots, otherwise even if they were to come to the rebooting forum, they would not stay. For example, some people come to reboot, but they misunderstand rebooting. They are still caught in a *"harmless in moderation'* trap and cannot extricate themselves. This kind of superficial and incorrect understanding is ridiculous and ignorant for senior brothers. Senior brothers already have a very deep and correct understanding. They will no longer be deceived by *"harmless in moderation'* theories. Lies provide one with a good excuse for indulgence. With this absurd 
excuse, you go farther and farther on the road of control until you are completely lost. When the symptoms erupt, you may wake up suddenly. The *not shedding tears till seeing the coffin* effect. 

We should cherish the pure land of the rebooting forum. The rebooting forum has a large number of victim cases 
for you to take heed from. There are also various predecessors’ experiences for you to learn from. In the rebooting forum, you can learn the truth about masturbation. Of course, the purpose of rebooting is not only to abstain from masturbation & adultery. We should learn how to be a person and what kind of person we 
should be. Through the study of traditional culture, you will change your outlook on life and your values, which is very helpful for your spiritual improvement. When we reboot, we must learn the way of health preservation, and more importantly, we must learn to do good and accumulate virtue, not to 
do all evil, to practice good deeds, to do more good deeds, and to help others more. Only in this way, will life become more meaningful. Helping others is great happiness, and helping others is also the foundation of happiness.

There are over one hundred million people in China. Very few people come to the rebooting forum due to destiny. Very few people really have the opportunity to hear the truth. You can 
observe classmates and friends around you, but many people don’t even realize it. Regardless of the harm, I am in a state of ignorance and misguidedness. Such a state of mind is very sad. In such a state of mind, what is waiting for them is undoubtedly the tragedy of life, and no one in life tells them the harm of masturbation. Some brothers say, why did no one tell me long ago! This sentence is a bit ironic. Some people, even if you tell them, will misunderstand your kindness, and think that you are too extreme. Their idea is to engage in enjoyment. At this time, they can't listen to truth. You may turn your head, when you have symptoms, or you may never look back, and you might never understand the truth until you die. Let us come to reboot. If we can understand the principles of rebooting, it is really everyone's blessing. Cherish this blessing, regain a sunny and
healthy self, and spread positive energy to more people.

Ten years ago, home computers were not as wide spread, and there was no place for you to understand the truth about sex. There was no place for you to learn to raise your awareness. It 
was a completely dark age of adultery. Now everyone can come to the rebooting forum. Nowadays the theory of rebooting has basically matured. The foundation of the rebooting forum is already very stable, and the road has been paved for a vast number of brothers. Like a tree, descendants take shade here. A rebooting career in China requires hard work and advancement of our group of people, as well as selfless dedication to provide the next batch of new brothers with valuable experience, so that they stay and reboot. So that they turn around and reboot successfully as soon as possible. Purify yourself, purify society.
A person with a very high level of enlightenment will never commit masturbation, because he knows that masturbation is very harmful and belongs to evil, so he must completely quit. The pleasure is short-lived, but the pain of symptoms is very long-lasting. If you stay on the path rebooting, you will know that there are many brothers with medical expenses in the thousands, and brothers with medical expenses of tens of thousands who have often undergone surgery. There are 
also many friends, and almost every brother has a history of blood and tears behind his back. When we first start rebooting, we must take the correct approach, that is, we must completely quit pornography. 

According to feedback from a large number of brothers, many brothers have completely quit, and some brothers have not yet reached the state of complete quitting. However, the frequency of masturbation has been greatly reduced. For example, some would masturbate nearly a hundred times in half a year, but now it has been reduced to less than ten times. This is not because 
they deliberately masturbates, but is a relapse caused by relaxation of vigilance or unconsciousness.

Confucius said: *"If you take it from above, you get from it; if you take it from it, you get it from below; if you take it from below, you get nothing."* Some brothers take the incorrect view from the beginning, and they still want to be moderate, rather than completely abstaining. This is actually an idea of compromising with the inner demon, and is defeat before quitting! This type of brother is 100% able to break the precept, his determination and stand are not strong at the beginning and as long as a 
little bit of trouble appears he will immediately waver and relapse. Only when a person has completely tamed the heart demon, can it be truly restrained after marriage. That is a very high state, and you must have strong control over your thoughts. Just like walking a tightrope at high altitude, only with strong physical and mental control can you walk a tightrope at an altitude of a few hundred meters. We reboot to reach this state. Even if you can’t reach it in the end, your initial motivation must be a complete abstinence, because *“get it from the top, get it from it; get it from it, get it from the bottom."* If you want to be moderate at the beginning you will certainly not succeed, it 
is just self-deception. If you have great determination, a certain degree of understanding, and keep learning to improve your consciousness, it is completely possible to quit completely. In the reboot forum, many senior brothers have entered the stable rebooting period. After entering the stable rebooting period, the feeling of suffering will disappear, and there is basically no intention of adultery, but you still need to maintain a high degree of vigilance in order to maintain the results of rebooting.

### 2 Q&A cases

**Case 1**: I’m the one that you mentioned has been around for 30 days. During this period of time, vigilance has been slackened, there has been a lot of masturbation, and it’s been 3 days since it’s been nocturnal. It’s painful suffering. The foundations laid before have all been wasted. It’s really a return to the pre-liberation period.

**Case 2**: In the beginning, the effect of strengthening the kidney was very good. I did not have spermatorrhea for 37 consecutive days. However, the following 10 days, I actually had spermatorrhea four times. What's wrong?

**Analysis**: The kidney has an ability, and this ability is called the ability to freeze. "Su Wen" says: 

>*"The kidney is responsible for the sting and the foundation of sealing."* 

Because the sealing and solidification of the kidney can prevent excessive excretion and loss of essence, qi, blood, and 
body fluid. The more the essence of the kidney, the more vigorous this function. Nocturnal emission, masturbation, and even sex will actually damage the ability to affix this energy. 

Some people have a good physical foundation, so they can still afford it. For the time being, there will be no continuous emission of sperm. However, some brothers are relatively weak and have an energy affixing instability, this will cause frequent emissions. There are many factors that can cause frequent loss, and one of the most significant factors is the inability to affix the energy. For example, when you were in elementary school, you could hold your pee in for an entire class and nothing happened. But after maturbation hurts the kidney, your ability to control your body declines, and you can’t hold back both urination and defecation. **Traditional Chinese Medicine**: *The kidney governs both stools, defecation and urination.* Everyone can observe what happens to the elderly. They can't hold back their bowels and urination. Maybe not even for ten seconds. If they want to urinate, they will have to urinate immediately, otherwise they will soil themselves. This is actually a manifestation of the weakening ability to *freeze*. With an increase in age and a weakening of the body, we will also come to this point. But for now many brothers are still young, yet they have the performance of the elderly. Imagine what will happen to them when they are old. What will they do?

In the first case, this brother was continuously self destructing with masturbation and hurting the kidney, resulting in a weakening of the ability to stabilize. Excessive damage took place. For the second brother, the effect of strengthening the kidney was achieved, and the effect was obvious. However, one spermatorrhea damaged the *freezing* ability of the body, and as a result, it malfunctioned 4 times in 10 days. When this happens,
you should pay extra attention after the first nocturnal emission, and you must be especially careful. After the first spermatorrhea, the kidney strengthening exercise should be increased. The 
kidney strengthening exercise increases the ability to *'freeze'* the body. The sleeping position should be *auspicious lying*. In addition, all kinds of factors that cause spermatorrhea should be avoided, so as to avoid continuous occurrences of spermatorrhea. Try to avoid strenuous exercise after spermatorrhea, because the body is relatively weak, you should pay attention to resting for a few days. You can still do health maintenance exercises, you can also take a walk.

After spermatorrhea is a very special period, it is a period of high incidence of relapse. At this time, it is easy to feel discouraged and disappointed, which can lead to an emotional relapse, and 
spermatorrhea will bring people back to a state of hyperactivity, so be extra vigilant. As long as it is not frequent, don't worry, just insist on rebooting and keeping in good health, and you persist in paying attention to emotional management. If you encounter frequent emissions, you should analyze the causes of spermatorrhea, and do well in all other health management aspects, kidney exercises, good sleeping habits, and avoid all 
kinds of negative factors, so that the frequency of spermatorrhea can be controlled. Once the frequency of spermatorrhea is effectively controlled, the foundation for recovery has been laid.

**The following is the main topic of discussion in this season:**

This season, I will share my experience with you on complexion and facial complexion restoration secret techniques.
Traditional Chinese physiognomy and face-to-face consultation of traditional Chinese medicine achieve similar goals. The highest state of Chinese medicine is what is known as *the god of sight!* 
The highest level is when you look at your face, you know what's wrong with your body. I believe everyone has heard the story of Bian Que. Bian Que was a master of face-to-face consultation, and he could diagnose accurately at a glance. Traditional Chinese medicine face consultation and Xiangshu can be described as two branches of the same tree. A deep understanding and comprehension of the theory of physiognomy can give us a better and deeper understanding of the hazards of masturbation. Basically every classic photo book has a chapter on complexion. The detailed information contained in complexion, whether in a Chinese medicine or photo book, is extremely valuable. Let me share with you more information and my personal experience in depth.

>Lack of qi, nothing can be done, strong qi, strong spirit, blessing in dialects, qi radiates color, and color will be prosperous and dry  
> -- Liu Zhuang Shenxiang

Qi refers to the qi of the internal organs, and the kidney contains the essence of the internal organs. The face is a mirror of the internal organs, so it will be reflected on the face when the kidney is injured. The complexion changes dramatically after masturbation. When the breath is insufficient, the complexion will also change. It will become darker, blue, dirty, and oily, which makes people feel disgusted. Seriously damaged brothers will also have a distinct facial appearance. Subtle changes are called deformations. The eyelids of some brothers have changed, double eyelids have become single, and after a period of abstinence, they have changed back to double eyelids. There are also occurences of edema, including swollen eyelids, swollen cheeks, and eye bags. The skin texture will also change, the skin 
becomes rough, and is no longer smooth and delicate to the touch. Some brothers have molting, enlarged pores, acne and pimples, etc., which will not heal for a long time, and will leave acne marks or stains. There are also brothers with sunken cheeks, prominent cheekbones, a ghostly look on their faces, and they look like zombies. They will also have deep dark circles under the eyes. 

These are typical manifestations of masturbation and kidney injury. In modern society, facing the computer for too long will cause *"screen face"*, and staying up late and sitting for a long time will also hurt the body and so the repercussions on a person's energy is even worse. Another point to be noted is that the fairness or darkness of complexion will also have a certain impact on the shape of the face. If you have studied photography, you will know that when brightness changes, the shape of the object will also undergo subtle changes. In the same way, when the brightness of a person's face changes, that is, after it becomes darker, the shape of his face will also undergo subtle changes.

When a person has kidney deficiency, it is easy to have a manifestation, that is: addiction to lying and moving. This is also specifically mentioned in Chinese medicine. Everyone should have had this experience. After masturbating, sleeping becomes very desirable. Waking up also becomes very difficult and almost impossible in some cases. One also like to lie around in bed, which can easily lead to relapse in itself, thus forming a vicious circle. 

It is relatively difficult for such a lazy person to succeed in any endeavour. It is not an exaggeration to say that everything becomes impossible. The actual experience of many brothers is indeed confirms this to be the case. Both schoolwork and work are in a messed up state and no success can be found anywhere. Let's imagine a person who has a strong personality, is full energy, and works in this state to learn and grow. The efficiency and efficacy of his efforts will be completely different, and  thus the final result will be very different.

>"If you are full of anger for a month, you will get color, and the color and hair will determine the good and the bad on the outside" 
-- Liu Zhuang Shenxiang

Many brothers have reported that after about a month of rebooting, their energy and spirit has improved, and others have said that they become handsome. In fact, this means that their 
complexion has improved, and their facial appearance has also changed subtly. With this change, the eyes and skin tone will be brightened ad evermore refreshed. The confidence is back. When you are in good spirits, you have a good physical and mental state in everything you do. It is easier to succeed in doing things. On the contrary, many people become inferior and have no confidence due to indulgence, become hesitant in doing things, and show social fear. Going out and doing things in this state, is already losing half, even thought nothing has been done as yet. If the injury reaches a certain level, people’s brain power will drop significantly, and their concentration, memory, and thinking power will drop to varying degrees. If things that could 
have been done well are not done well, it will affect academic performance. 

Without a good physical and mental state, whether studying or working, it is not easy to succeed. The complexion is the external manifestation of a person's energy. Only a good complexion, full of energy will result in a good state of study or work. And a person with *long-horse* spirit will also subtly infect others, make them feel that you are full of positive energy and be willing to be with you. The other feeling is like facing a dirty river, naturally you will feel disgust, and when facing a clear spring, you will naturally feel happy and calm.

>"The gas reservoir is inside the skin, and the color appears outside the skin. The roots are solid, and the branches and leaves are multiplied. When the roots are dry, the branches and leaves are weak." 

Color is a kind of complexion; if the qi is biased, the color is burnt, if the qi is stagnant the color is dry, and if the qi is obscured, then the color is haggard.
 
If you are in chaos, you are in chaos. Those who are full of color are like the autumn moon and the sky. Those who are obscure are like clouds that cover the sun. If you are calm, you will be lucky. If you are in chaos, you will be fierce!

The relationship between qi and form is the root and color seedlings, qi is the most fundamental, and the kidney is the root of the five internal organs, and contains the essence of the five internal organs, so the kidney qi is the most important thing, which is equivalent to the king of kings. With a deficiency of the kidneys, the internal organs are prone to disorders and various symptoms are prone to appear. Therefore, Chinese medicine has said that kidney deficiency is full of diseases. This is not untrue. The medicine king Sun Simiao said that "there are few diseases" which actually meant this. This hurts not only the complexion, but also the skin. According to my observation, I had the worst skin among my friends around me at that time. It became worse after being irritated. In fact, others also had irritated skin, but each person’s symptoms are different. Later, after studying Chinese medicine, I realized that this is a different area from personal physique. However, there is a close relationship. Traditional Chinese medicine divides people into nine types of physique. Each type of physique is different because of the problems that occur due to lack of control, and each has its own strengths. Some people have good skin no matter what they do, but some people have very bad skin after a few strokes. 
However, God is fair. There might be no problem with someone's skin but serious problems may occur in other areas, such as severe hair loss, or lower back pain, **insomnia**, and other symptoms. Also, even though this person's skin is okay, his complexion will still change, that is, because of stubbornness, his complexion will get worse no matter the physique, there is no doubt about this. When your kidney qi is sufficient, like a childs, the skin is delicate and smooth, it is bright, full and 
clear, making people naturally happy; when your skin is dull and dirty, like expired fruit or withered flowers, whether it is oneself or others,  it will cause the perceiver to feel sick. When you insist on rebooting and maintaining health, your skin and complexion will gradually improve. Regarding this point, countless brothers' experiences and before and after photos have fully confirmed this.
>"The husband wants his righteousness, his qi desires, and his sexual desires positive. If he is strong, he will be innocent, and he will be upright, and he will be the best in the world!" 
> -- Jade Guan Zhao Shen Ju

The most important thing for a man is to have a righteous spirit, a gentleman's heart is open and upright, but is not too rigid. If its too rigid it is easy to break.

The rigidity here refers to a combination of rigidity and flexibility, with an outer circle and an inner square. The aim here is not to show off everywhere. If you really have righteousness, you won't be addicted to masturbation, and if you have righteousness, you won't be insignificant anymore. To have this righteous energy, one should constantly instill positive energy into oneself, and the righteous energy should be stored in it. In this way evil cannot be done. People feel right when the heart is right, and people are clean when the heart is clean. When we reboot, we have to straighten our hearts, purify our hearts, wash away the toxic and dirty hearts, change our minds, regain the purity of the sun, and let ourselves be masculine and righteous. No matter where 
you go, take this righteous aura with you. The righteous aura is like a spring breeze. Wherever it blows, there will be a vibrant scene. If you have wretched air, no matter where you go, you will not be welcomed. You will even find that relationships with your parents will become tense and you will not be able to communicate normally with others. The root cause is that 
one has been poisoned with pornography, and being addicted to PMO hurts righteousness. 

Without righteousness, there will be no confidence, you will become inferior, be unwilling to communicate with others and fear that others are looking down on you. To change this disordered physical and mental state, the only way is to learn more about rebooting articles and traditional culture. To increase your awareness and positive energy, so that you can rebuild your self-confidence. Many brothers have reported that after rebooting for a period of time, their mood has improved, and they dare to look directly at others, and find it natural to communicate with others. This is actually a manifestation of 
physical and mental adjustment and a manifestation of recovery of righteousness. When you have enough righteousness, you will be able to do many things smoothly. Even if you have a small 
setback, you can face it optimistically and cheerfully. Your mood is completely different, and you become more aggressive, more optimistic.

>"If you are obliquely flawed, the color is dim, and the appearance is not good. Those who are white as jade, black as lacquer, yellow as steamed chestnut, and purple as crimson, are all lucky." 
 -- Shenxiang Complete Edition
 
This passage is actually about radiance, transparency and clarity of the complexion. Many brothers who masturbate will find that after masturbating, their complexion becomes darker, just like a flashlight that is about to run out of electricity. The skin color will also become very uneven. Friends who have studied makeup will know that there is a special brightening makeup, and the other is to make the skin tone even and detailed. When a person's complexion is brightened, a person's mental outlook will be completely new. Of course, makeup is false and a lie. Many 
women take off their makeup and immediately reveal their true shape, that is, their complexion is dull, oily and looks particularly lacklustre. The endocrine imbalance caused by masturbation 
reflects that there will indeed be many bad expressions on people’s faces. For example, some brothers’ skin will become greasy, and there will be a feeling, even after washing it that it is not clean. The more they wash, the more oil they get, and they feel dirty after washing it many times, and it's still very dull. In fact, this is because the inside is dirty and the endocrine system is disordered. When this happens, it is useless to wash it outside, even with disinfectant water. When you insist on rebooting and keeping good health, actively exercising, paying attention to a 
regular schedule of work and rest, eat lightly, and persist for a period of time, your skin will naturally become clean. Many brothers have personal experience, insisting on rebooting and 
keeping in good health, the skin becomes clear and radiant again. But after breaking the precepts, one will immediately return to the pre-liberation period, become ugly again, become insignificant again and lose keep losing confidence.

Because of genetics or sun exposure, everyone’s skin color is different, some are white, some are dark, some are yellow, and some are purple, but no matter what kind of skin color one has, it is meant to be radiant and bright, clear and transparent. On the other hand, uneven skin tone, dullness and a dusty face, are not good complexions. This type of complexion is actually an 
external manifestation of internal disorders. Complexion is a kind of mirror of the inside to the outside. Injury to the kidneys, dysfunction of the five internal organs, and endocrine disorders will definitely be reflected on the face. A discerning person will know at a glance. In addition, rebooting and maintaining health will also brighten a person’s eyes. People’s eyes are also divided into light and dark. Floating light is not a good sign. The best eyes are bright and subtle. This is the best. For  example, just like the light of a glass ball vs the light of jade, the glass ball 
is a floating and piercing light, without connotation, while the light of a jade is a restrained light, a divine light radiating from the inside out. After relapsing, the changes in appearance are 
subtle and obvious. When damaged to a certain extent, the complexion feels insignificant and lacks energy at first glance. After rebooting, the changes in a person's appearance are also subtle. Only by careful observation can we uncover the mystery. Others say that you have become handsome, have you done something to your face? Why are you handsome? Because after quitting, some subtle good changes have already taken place. Such subtly good changes are hard to pinpoint but obvious, and people can directly feel it at a glance. Everyone, look at the children, is there any child that is particularly ugly? Almost
none, because children have a good spirit, a good complexion, and bright and energetic eyes, which makes people happy. The most important thing for a man is not his facial features, but his energy, which is also reflected in his complexion. A man may not be handsome, but he must not lose his spirit. Losing his spirit is 
really foolish. Many brothers who used to be handsome will become ugly in the end. As soon as their spirit leaks, no matter how handsome they were, they will become uglier and uglier. This is the personal experience of many handsome guys. It is true that you will change from a handsome guy to an ugly guy and finally a wretched uncle!

Next, let’s talk about the secrets of facial and complexion restoration

Many brothers are relatively more concerned about the content of this season, because many brothers have become ugly after indulgence. It is a relatively common phenomenon to become ugly. I also talked about the various types of ugliness in a previous season. This season, I will talk about how to restore looks.

How to restore looks and complexion is a very deep science. The phenomenon of turning ugly will show up after some damage is done. After indulgence, the appearance and complexion of a
person will begin to decline. It is okay when you are a teenager, but it will start to become obvious after the age of 25. I started masturbating in adolescence, and so there was an endocrine disorder at the time. 

Although I was not that ugly at the time, I was not better looking than before masturbating. Then when I went to university, I started getting dark circles and bags under my eyes. I remember at the time, after I indulged during a summer vacation, I looked in the mirror and found that I had bags under my eyes. People 
with bags under their eyes look particularly sluggish and very old. I found that my wrinkles began to increase after I started to masturbate. After that crisis, I started running every day. Anyway, I had a lot of free time in university. I ran long distances every day and kept running for more than 20 days. Then I looked in the mirror and found that the bags under my eyes and dark 
circles were gone. I was looking and feeling energetic, but I was still in a state of strong ignorance and indulgence. Not long after I broke the positive cycle and went back to past indulgences, the bags under my eyes reappeared, so I started running again, and I struggled back and forth between running and relapsing. It was a very painful and helpless situation.

Through my own experience, I found that aerobic exercise has a positive effect on appearance recovery and alleviation of prostatitis, but if you don’t completely quit masturbation, you will still become ugly again after a relapse, so quitting masturbation completely is the most important thing. Pivotal. It is impossible for a person to exercise every day after masturbating. Masturbation is too exhaustive and one does not want to exercise. Exercise is a kind of balance to the harm of masturbation, but as you get older, you will find that it is more and more difficult for your body to recover after exercise and masturbation, because as people get older, their own recovery ability will decrease a lot.  By the age of 30, your recovery capacity has dropped by half compared to your capacity at the age of 20. No matter how good your health is, if you have a history of traumatic sperm injury, you will have symptoms by the age of 30. Overdraft when you are young, and when you get older, the evil consequences will slowly appear. Many people think that it's okay to indulge when they are young, but in fact its just because they are able to recover faster.

Generally ugliness can be divided into three categories:
1. Form changes
2. Changes in complexion
3. Changes in skin texture

Some people have good skin, but their complexion is dull, others have good skin and complexion, but their faces are deformed. 
Most people have negative consequences to all three, namely skin, complexion, and shape. I think everyone has atleast once thought of ways to restore appearance, such as facial cleanser, or Chinese medicine conditioning, or facial mask, etc. I remember a brother who went for laser treatment. After 
 a period of time, his skin quality improved, and so he continued. After he broke the reboot, his skin started deteriorating again. 
He then decided to go to the hospital for laser treatment again. 
He posted that he hated himself so much that he broke his reboot. Brothers with good exercise habits should understand the true meaning of the phrase *"exercise is the best cosmetic for 
men".* After a period of aerobic exercise, the complexion of the skin will improve. If you continue to persist, the problem of facial deformation will also gradually improve. But you must never break the reboot. Once you break the precepts, you will probably give up your previous efforts and return to the pre-liberation period.

Staying up late also hurts your appearance and can also cause dark circles. I believe many brothers have had the experience, so we must develop good work and rest habits, actively exercise, and have good sleep.  This is why its called *beauty sleep*. If you sleep well and  look at yourself in the mirror in the morning you will find that you look better. If you stay up late, you will 
feel tired in the morning and lose energy. But what I want to say is that it’s difficult to restore your appearance completely through sleep alone. Aerobic exercise can improve your appearance, but you need to persevere. In fact, the recovery of appearance can easily enter a bottleneck period, regardless. No matter how you do it, it is very difficult to have an obvious 
recovery. Even if you use the best skin care products, the effect is still very limited, and is usually so expensive that ordinary brothers can't afford it. Many skin care products are also apt to cause skin allergies.

The restoration of appearance and complexion is indeed a difficult task. It is extremely difficult to recover by rebooting alone. Unless you have been in a reboot state for quite some time, to truly recover, you will have to find an additional route.

This season I will share a secret technique for facial and complexion restoration. I have read countless health articles and books, and I have never seen anyone recommend this method. 

This method has been completely tested by myself through practice. It can be said to be an exclusive recovery secret technique. It has an amazing effect on the restoration of appearance and complexion, everyone. I should know as I have personally experience it. I am not exaggerating when I say this. It is an amazing recovery effect that exceeds the top skin care products. The best thing is that it is completely free and completely natural.

Read the following very carefully. Don't miss a word, otherwise it will be your own great loss.

As I said in a previous article, I used to have neurosis. Brothers with neurosis should know that taking medicine does not cure neurosis. Taking medicine can only relieve neurosis. If neurosis is to be cured, it must be through rebooting and cultiavting good health. In terms of making great efforts, you must improve your 
awareness of health preservation. At the time, I understood this truth, so I didn't put all hope of recovery on the doctor, but kept studying health articles to improve awareness around the topic of health. I often went to the park to wander, and saw many retired old people walking on the cobblestone path. I would
follow along, massaging the acupuncture points on the soles of the feet, but I didn't do this for long. Later, I saw some old people hit trees. Everyone who has been to the park may have seen people use their backs to hit the trees, which is equivalent to massaging the meridian points on the back. So I also followed along, hittin the trees with my back, completely oblivious to the effect. Yes, initially it felt uncomfortable on my back. I felt 
much more comfortable after hitting it for a few days, but I didn't stick to this tree hitting therapy. 

However, through the experience of hitting trees, I developed special affection for trees, so I started to check on the Internet to find out whether trees can cure diseases. I found exactly such information. 

Look at the following text:

>[Tree therapy refers to the use of trees to treat diseases. The use of trees to treat diseases is widely spread among the people. There are also examples in medicine. Indian yoga believes that trees can pass a substance obtained from the universe to people. Different tree species carry different energy. Some help restore energy, some reduce inflammation, and some prevent disease. Oak trees are refreshing, spruce can absorb bad energy, pine trees can transmit beneficial energy, and poplar bark 
can cure toothaches. A Russian dictionary reads: “When your feet hurt, put the aspen on your feet; when you get a headache, put it on your head.” Modern experts in the treatment of trees are biological localization experts. They believe that trees have a biological field, and the healing effect of trees on people is precisely the effect of the biological field. Experts from the British Institute of Health believe that trees have enough energy to cure diseases, and the effect is not necessarily lesser than medicine. People who often practice qigong in the forest may have this experience: If you practice qigong next to birch, oak, pine, cypress, and cedar trees, you will feel energetic and 
refreshed, and occasionally minor illnesses will disappear quickly. It has been known that trees can not only "supply energy", but also "absorb disease gas." 

I saw this text about three years ago. At time, I felt that tree therapy had a certain truth, but I also felt it was very mysterious. However, I had already started to practice it at that time. I went to the park to touch the trees for about half a month. At that 
time, I didn’t get any special feelings. Now that I think about it, I was actually too careless at the time, just like a pig. Eat ginseng fruit and swallow dates. When I went to touch the trees, I didn't have a very delicate experience. Therefore, I did not continue to persevere, but in close contact with nature, I can clearly feel that my mood is easier to relax, and it has a very good effect on regulating the mental state.

The following paragraph is key, everyone pay attention to it:

It has been three years since I really realized the relationship between tree therapy and facial expression. At the time, I was also unintentionally planting willows, and did not want to restore my appearance through tree therapy. I just wanted to get close to and embrace the trees in the park. It was an impulse and thought. Through the research of auras, I now know that everything has its own aura, and the auras can communicate and influence each other. 

People also cover a circle of auras, but it is invisible to the naked eye, and the trees also cover it. The circle aura is invisible to the human eye, but it does exist. I thought at the time, that I could purify my aura through the aura of the trees. It was an inkling and I didn’t know where it came from. In short, I went to embrace the trees and this idea. This posture can make people feel a kind of spiritual comfort, and can make the body and mind comfortable. At the moment of hugging, the aura of the trees is already affecting your aura. When I hug a tree, I recite the Buddha's name, because scientific research shows that plants also have emotions, sorrows and joys. We should be grateful for plants, because without plants, our air would be terrible. So I was chanting the Buddha's name while hugging the trees. I could feel the peaceful aura of the trees. 

That kind of aura can instantly calm my impetuous mind.
A voice in my mind told me that I should hug the tree with my hands, and the Yintang between my eyebrows should stick to the tree, and then visualize the energy of the tree entering my 
body through the Laogong and Yintang points of the palm, purifying my aura. At the same time, I must be extremely grateful for the trees. So that’s what I did. Three years ago, I got close 
to the trees. I just touched them with my hands. I didn’t get close with my face. When I got close to the trees with my face for three days, about 2 hours a day, a miracle happened. I can't think of a better word to describe my feelings. On the fourth day, I got up and washed my face in the morning. After washing and looking in the mirror, I found that my complexion had become particularly good, my face was much cleaner than before, and it 
became transparent and plump. When I got up, the feeling of fullness reminded me of my childhood. The face was very clean, and there was no need for facial cleanser and skin care products. Everyone knows how a child’s face is; very smooth and plump.
At the same time, I felt that my skin tone became more even, and my complexion had been visibly brightened. This gave me a lot of confidence in tree therapy and now I often go for it. After a week or so, the dirt in the pores began to drain out and the background color was still bright and moist. When the dirty stuff was almost exhausted, the complexion improved again many times over. I have personally experienced that the aura of the trees purified my aura and adjusted my endocrine, making my mood more peaceful and stable.

Let me share a few more experiences. I touched the tree with my hands for 2 hours, and an hour after I went home, I found that my palms became thicker. This was a very subtle feeling. My mother said that my hands became thicker. Thickening is mentioned in Xiangshu, but it is actually a manifestation of qi, ample and blessing. I remember that a farmer shook hands with President Xi, and then exclaimed: *"What a thick palm!"* I have persisted until now, and the palm of my hand has become nearly a quarter thicker than in the past, which is very obvious when seen. Also, the amount of hair loss decreased a lot. My hair loss and gray hair recovered well through rebooting and health maintenance. After tree therapy, I found that hair loss decreased further. I would lose about 5 hairs a day. Now this has decreased further to about 1-2 roots daily and some days none at all even. From the perspective of Traditional Chinese Medicine, it
makes sense that the tree is wood qi, and hair is the external manifestation of liver wood and kidney water. The hair is the kidney blossom, the liver stores blood, and the hair is blood. Through invigorating wood hair loss will be greatly reduced, this is all my personal experience. Trees are very special. It is not only wood air, but also the five airs of wood, water, fire, and earth. I believe that all the mysteries are in nature. Einstein said that a drop of water can be described for three days. The physical knowledge contained in a drop of water is beyond human imagination, the most common and the most profound.

Then, I found that different trees have different auras. If you touch them, you will find that their body temperature is different. Some trees have a low body temperature, and 
some feel warm to the touch. I have touched a lot of trees. I found that the aura of big trees is stronger. Among trees, ginkgo and camphor trees feel the best. In addition, trees with "aura" 
are also very effective. What is meant by "aura" "? The gas point is the growth point of the tree, the growth point of the branches, and the growth point is actually the qi rising out. If you put your hand on the growth point, you will absorb more qi and the effect will be more obvious. However, it is not easy to find trees with growth points, and some trees have high growth points and you can't reach them.

Below I summarize the important points of tree therapy:
1. Choose a tree. I recommend ginkgo or camphor. The tree should be more than ten years old and the trunk
should be relatively clean. Of course, you can also try other trees.
2. Hold the tree trunk with both hands, and the Yintang between the eyebrows sticks to the trunk, visualize that the purifying energy of the tree enters your body from the Laogong and Yintang points to purify your aura.
3. Use the cheeks on both sides to stick to the tree trunk and separate it from left to right. You can touch with the left cheek first and then the right cheek for about 20 minutes or more.
4. Pay attention to heart adjustment and be grateful. Brothers who believe in Buddha can recite the Buddha's name.
5. Try to practice during the day, as the sun is better.
6. Each practice should not be less than 2 hours. If it is very busy, keep at it for at least 1 hour.
7. After washing your face in the morning on the second day of each practice, you should pay attention to the effect and pay attention to the occurrence of any subtle and good changes.
8. The sun is key. Don't hug in the shade of trees. Choose a clean tree trunk that has direct sunlight.
9. Tree species are particular, eucalyptus and other trees are not suitable.
10. You can listen to songs if you are bored.

I had never associated tree therapy with the improvement of appearance and complexion before. 
By chance, I discovered the mystery, and the effect is really amazing! The reason why tree therapy is better than top skin care products is that it can purify your aura and adjust your endocrine, not just superficial appearance. No matter how good the cosmetics are, they cannot purify your aura, but trees can,
and the effect on skin tone and complexion is definitely amazing. It is also very effective in improving deformation. If you are a brother with keen awareness, you will definitely feel the 
tremendous effect of tree therapy on the restoration of your appearance. It really is powerful! 

It's not an exaggeration to say it has miraculous effects. After a few days of practice, you will immediately break through the bottleneck period of appearance and complexion recovery. But tree therapy has one disadvantage, that is, it is easy to make people feel weird. Ordinary people may think that one is weird and ask what on earth is that guy doing? There may be a curious and inquiring mindset, and you may feel there is something wrong with you. I have also experienced other people looking at me, but I don't care at all. Some things only need to be known to me, and I don't have to care about other people's thoughts.

I hope that brothers who have become ugly can practice actively. After practicing for a week, they will definitely be surprised. If it is fast, there will be a big change in three days. The change in 
appearance and complexion is subtle but perceptible, and it will be obvious if you look in the mirror.

I hope everyone will give me feedback on the effects and feelings of the exercises so that I can accumulate some cases. Finally, I want to thank the Buddhas and Bodhisattvas for their blessings. I believe it must be the blessings of the Buddhas and Bodhisattvas that I realized such a magical method of recovery and shared it with everyone. I hope that everyone can regain their looks, vitality, and self-confidence, but I don’t want everyone to be too obsessed with their looks. People will 
always grow old. Sometimes its best to let things go with the flow, help others, and keep improving.

The quality of your own soul is the most critical. Namo Amitabha! Buddha Shakyamuni, Master Nanwu! Nanwu Guanyin Bodhisattva!
