# In-depth talks about rebooting newcomers and emotional management

## Foreword:
In the preface to this season we will continue to share some tree therapy feedback from brothers:

**Case 1:** Haha, Brother Feixiang (Soaring Eagle), tree therapy is really amazing! I persisted with it for about a week, and I felt
that my face became obviously brighter. My friends said that I look like a child now, hehe, thank you! So happy! It would be great if I had been exposed to rebooting a few years earlier. Why?! Regret.

**Additional comment:** This brother has already experienced the magical effect of tree therapy. The change in brightness is obvious to him and his friends. Once it is turned on, the whole 
person's mental outlook will be lifted. In fact, there are other feelings, such as becoming cleaner, more delicate, and fuller, a series of subtle and good changes.

**Case 2:** Brother Feixiang, today I held a willow tree on the campus of the school for a while. This time it felt quite obvious. I kept changing my cheeks and pasting on it because there were too many people coming and going, and I persisted for a long time, i.e. more than ten seconds. In total I did it for more than half an hour. After this time, the palms of both hands did feel a lot thicker. When you make a fist with both hands, there will be a fleshy feeling in the palms of your hands, and there will be some feeling on your face, just that the facial muscles are relaxed a lot. Whenever someone comes over, I play with my mobile phone with my back leaning on the tree, and I continue to practice after they have left. I think I will be able to stick to it. Brother Feixiang gives me strength, I will stick to it, ha ha.

**Additional comment:** This feedback is from brother Yuanzhen. He felt the palm of his hand thicken, which happens after tree therapy. This thickening will be felt during tree therapy, but the most obvious feeling is a few hours after, especially at night. After washing one's hands, one can feel the thickness of one's palm. Thicker than right after the tree therapy, you can feel it when you feel it carefully.

**Case 3:** I tried the tree therapy method you mentioned. There are many trees around my school. I chose a big 
leaf banyan. I put my hand on the trunk. After a few minutes, I clenched my right hand into a fist and the strong feeling was actually great. Then I squeezed the fist of my left hand. I didn't touch my left hand. The power was obviously inferior to the right hand. I changed my left hand to just touching. After a few minutes, my left hand actually felt very powerful. I want to say that the power of nature is really infinite.

**Additional comment:** This brother's case is very interesting, he felt very delicate. In fact, it replenishes wood qi. Traditional Chinese Medicine: *The liver is strong for the grip.* The liver corresponds to wood. So touching the tree with your palm for a period of time can increase your grip strength. This is a very subtle feeling.

**Summary:** Tree therapy is very effective in improving appearance and complexion. Many brothers 
have provided positive feedback. I hope more people will be able try it out. Find a clean tree and choose a quiet place with 
few people. This is conducive to the practice. Usually, you should also pay attention to the way of health preservation. After nocturnal emission, after staying up late for a long time, after being tired, after looking at the computer for a long time, the skin complexion may appear to decline, so tree therapy should be done frequently, just like charging. Tree therapy has a miraculous effect on the restoration of appearance and complexion. The change is subtle yet obvious. When you really use your face to get close to trees, and hold on for a while, the miracle of recovery will take place. In addition, try not to do tree therapy too early or at night, because yin is very heavy during this time. It is best to wait for the sun to have risen and then to do tree therapy on the sunny side of the tree, that is, the side of the trunk that is directly exposed to the sun.

### 2 Q&A cases

>**Case 1:** Flying brother (Soaring Eagle), help! I have a six to seven year history of masturbation. Last year, I felt that I could still get an erection. Then I started working. After I started working, I suddenly couldn’t make love anymore. Am I really sick? I am worried about impotence!
>

**Answer:** When the damage reaches a certain level, the evil results will appear, and there will be a process of quantitative change to qualitative change. Since you are working, you may not be exercising enough and/or you are most probably sitting for a long time. Sitting for a long time can damage your kidneys and easily damage your sexual function. I suggest that you persist in rebooting and maintaining good health, and actively exercise, so that your sexual function gradually improves. In addition, it is recommended to avoid pre-marital sex, pre-marriage intercourse belongs to adultery. 

**Analysis:** The evil effects of masturbation have an accumulation and lag period, just like water will not boil 
until it reaches 100°. When the evil effects accumulate to a certain extent, they will appear. After the critical point, you will suffer. Once the symptoms come, you will suffer. In this case the trouble came. Some brothers were fine last year, but this year they collapsed. This collapse was not caused by one year. It was an overdraft for several years or even more than ten years. The evil effects of masturbation appear very quickly when the time has come. Even if some people have a good physique and love sports, their symptoms may not be obvious when they are young, but after the age of 40, various symptoms will 
become very obvious. I started to pay for my indulgence in youth in middle age. After reaching the age of 40, the speed of recovery will slow down a lot, making it more difficult to recover. Therefore, reboot as early as possible, wake up early, and quit early. Don't compromise with the demons. You must clear all kinds of misunderstandings in your brain and establish a righteous view of rebooting.

>**Case 2** [Teacher Feixiang (Soaring Eagle), the few times I broke the reboot, I reached climax in less than a minute, sometimes even less than ten seconds. I want to ask you if this is considered premature ejaculation. In addition, I saw a post saying that masturbation is different from making love. The poster said that he only ejaculates within ten seconds due to masturbation, but his making love time is completely normal, and that those making love ejaculations are psychological problems. I am really confused.

**Answer:** This question was mentioned in my previous article. There is a certain difference between masturbatory premature ejaculation and making love premature ejaculation. For example, if someone pursues strong stimulation and fast ejaculation during masturbation, then he may just have masturbatory premature ejaculation while making love is normal. But some people who have masturbatory premature ejaculation, have even worse premature ejaculation when they make love. If you are not pursuing rapid ejaculation when masturbating, and only a 
little stimulation leads to ejaculate, then the same is also likely to be the case when making love, and one will easily become nervous during this time. ML premature ejaculation is not always a psychological problem. Chinese medicine has talked about premature ejaculation and impotence caused by kidney deficiency. For example, some people don't have premature ejaculation at first, but if they indulge to a certain degree, they will have premature ejaculation. This kind of situation is very common among married rebooting friends. For example, it is OK for a few years after being married, but premature ejaculation 
occurs after a few years of indulgence. It is not a psychological problem. Of course, psychological problems can lead to premature ejaculation as well. For example, some people are very nervous and have a lot of psychological pressure on them, which can also cause premature ejaculation. How long can you be in control when you are in good health? It takes 10 minutes for some people and half an hour for others. But after a certain amount of indulgence, the time to orgasm becomes shorter, and the penis becomes very sensitive. It will ejaculate after ten seconds or even a touch, which means that the kidney qi is insufficient. Regarding whether ML premature ejaculation is equivalent to masturbation premature ejaculation, it depends on the specific situation. Some people have masturbatory premature ejaculation. ML premature ejaculation is more serious.

**Analysis:** When the injury reaches a certain level, weak erection, premature ejaculation and impotence will definitely occur. Regarding the injury of sexual function, there is no doubt, countless cases have fully confirmed this point. You can get energized right now, but it is actually your sexual function after overdraft. If you get an erection by taking medicine, it is using your last bit of kidney qi, and your body will break down faster in the future. Worrying about sexual dysfunction is a common among brothers, so we should take good care of rebooting and health, and avoid indulgence before marriage. This is very important. If you indulge too much before marriage, it will be embarrassing after marriage, so many people get divorced.

Now let’s move on to the main topic. This season we will talk about rebooting newcomers and emotional management in depth.

If 100 brothers come to reboot almost all 100 of these brothers have been brainwashed by the theory of moderate harmlessness. I had been living under the influence of the theory of harmlessness in moderation since childhood. The theory of harmlessness has been deeply rooted in our collective mind. Therefore, many newcomers come to reboot, and their posts still carry a lot of the remnants of the theory of harmlessness in moderation. It is difficult for newcomers to change their minds quickly, so we can only advise them to learn more about 
rebooting articles and constantly correct their knowledge and understanding. Otherwise, if one can't change their mind, one won't be able to quit completely. Even some older brothers still think about being moderate sometimes, and haven't completely climbed out of that *moderately harmless* thought trap, and thus haven't quit masturbation till now.

The first step in rebooting is to reform your ideology. Just like you go to jail to reform your mind, some people become better and reform, while some people still remain as they are and continue to commit crimes after serving time. When newcomers come to reboot, they are faced with just such a problem, because newcomers have a characteristic, that is, they are full of misunderstanding in their minds. You can tell whether they are newcomers by looking at the questions asked, and I can 
tell whether they are newcomers by looking at the content of their posts. If one can quit, one will know which reboot level the other is at.

Many brothers don't even understand the basic common sense that adultery is secretly leaking, and they still think that adultery is beautiful. If this is seen by senior brothers, they may shake their heads. The inability to quit is actually a misunderstanding in thinking and insufficient understanding. Newcomers come to reboot. If you really want to quit completely, you should calm 
down and study rebooting articles, improve your rebooting knowledge a little bit, and raise your rebooting awareness bit by bit. Otherwise, if still thinking that it is harmless in moderation, you won't be able to give up even after 10,000 years. The so-called *moderation theory* is basically self-deception. 

The one who believes in *harmless in moderation* theories does not know how many people have been harmed by this theory. They all thought that they could be moderate, but masturbation is highly addictive. Have you considered it? Do you know that adultery is a secret leak? Symptoms are prone to occur after adultery. Do you really understand this common sense?
As long as a newcomer is willing to persist in studying rebooting articles, his thinking will be easily transformed. Studying rebooting articles is a process of reforming your mind and raising your consciousness. If you don't reform your own thoughts well, 
or leave the moderate harmlessness of the past, then you don't want to give it up. What newcomers lack most is learning! What newcomers need most is learning! Otherwise, if one has a misunderstanding of and refuses to listen to reason and to learn, then seniors will have no choice but to let the symptoms tell one the truth. Someone who cannot climb out of the *moderately harmless* thought trap for the rest of their lives is sad. Once they fall in, they will be in it for the rest of their lives. Such a situation is really sad! He was captured by a wrong thought and 
became a puppet of this kind of thought, but he didn't feel that there was anything wrong with his thoughts, and that he was very self-righteous. This is the saddest thing about such a one.
Rebooting, many new people are wrong at the beginning, don't want to give up completely, are still compromising with the demons, and still thinking about being moderate, with wrong motives, they are doomed to fail. The theory of *moderate harmlessness* does not leave the brain by itself. Only 
rebooting can help you. If you don't recognize the true nature of the theory of *moderate harmlessness*, you will not be able to reboot successfully. We must reboot thoroughly, including 
adultery. Thorough rebooting is the path I choose to fly. I am a thorough person, and definitely not a compromiser. I hope that the newcomers will recognize the theory of *moderate 
harm* as soon as possible, and do not break down in the future, and complain about the theory of *moderate harm*. There will be no point in complaining at that time. Take a look at the real cases of the predecessors. How many people have been ruined by the theory of *moderate harmlessness*? 

Incalculable.

Do you know why some rebooting platforms do not allow newcomers to post? Because newcomers are full of misunderstandings in their minds, as soon as they come up without learning, they will be forced to quit. The mentality of rebooting is completely wrong, and they are still thinking about 
quitting with will power, the result is constant failure. Newcomers have a wide range of ideological misunderstandings, and they are seriously brainwashed by the harmless theory, and it is difficult to correct them for a while, and they must be corrected through a large number of studies on rebooting articles. If you don't have a correct understanding and knowledge of rebooting, you can't get rid of it successfully. For example, some brothers like to say "Eating is like sex also", and hold on to this sentence, thinking that they are very right, you know "Eating is like sex also", then I ask you, do you know about "Paying the bill" after eating food?, there is no free lunch in the world. 

Don’t think that masturbation is like eating, and then you indulge yourself and find an excuse for indulgence. In fact, it’s a big mistake. If you think like this you will go astray, you will go astray. The ancients said that sexuality is more about the need to pass on from generation to generation, it is righteousness after marriage, rather than asking you to indulge unscrupulously. 
The ancients were firmly opposed to premarital sex!

In addition, newcomers are asked not to think too simply about rebooting. I mean thorough rebooting, including quitting adultery and not breaking the reboot. Thinking too simplistically will only give rise to the thought of underestimating the enemy. In fact, there are quite a lot of brothers who have underestimated the enemy. Afterwards, they even become proud. The so-called arrogant soldier will be defeated. Of course, we shouldn't think about rebooting too hard. As long as we are 
willing to keep our feet on the ground and raise our consciousness through continuous learning
our consciousness can be raise our consciousness through continuous learning we can subdue the demons. Some brothers may have gained a certain level of enlightenment through learning, which is much higher than that of newcomers, but their enlightenment has not yet reached the perfect place, and there are still flaws in their understanding. Such brothers will still break the reboot. Everyone should be humble and cautious when rebooting, avoid being proud and complacent. The higher the level of consciousness, the more vigilance is required. Instead of becoming proud and complacent when the level of consciousness is high be extra vigilant. If not the inner demon will take advantage of your loopholes, and if you are too self-confident, you will become blind and conceited. In the end it will only lead to a tragic result.

We hope that the newcomers will learn more from the mistakes of their predecessors and not repeat the tragedy of their predecessors. Let me tell you this. Almost all the predecessors had the same idea as you in the beginning. They thought that they were being *moderate* and eventually became wasted. Now you are the blind and ignorant me in the past. When you start to 
study rebooting articles, you will continue to improve. 

Enlightenment, will change your mind and consciousness and you will become who I am now. The predecessor’s painstaking realisation is that newcomers can wake up as soon as possible and step into the right path of rebooting. Rebooting is a pure land. I hope everyone will cherish their blessings. Please consciously stay away from the theory of *moderate harm*. 

**Remember the bad times! Remember the damage!**

Let’s talk about emotional management:

**Case 1**
>[Teacher Feixiang, I am learning all about rebooting knowledge you mention every day, but I am embarrassed that I relapse as usual. I always feel very depressed before a relapse. I don’t break the reboot in vain. I clean up my room over and over again. My room used to be very messy and looked like a doghouse. Now I help my mother with the housework when I have time. My room is clean, I listen to light music when I have time, and smile from time to time. I think rebooting knowledge only treats the symptoms, not the root cause. Whats most important is one's state of mind, and calmness is the kingly way of rebooting.

**Analysis:** This is a message from brother lefty. Lefty is a senior brother and has a high level of consciousness, but please remember one thing: **if a person breaks the reboot, then there must be a lack of understanding or a misunderstanding somewhere. What we have to do is to discover this *"deficiency"* if the reboot is broken, and then strengthen our understanding. To be successful in rebooting, one must constantly improve one's understanding and bring it close to a perfect state. What is enlightenment? Enlightenment is to have a correct understanding and knowledge of rebooting. The deeper the understanding, the better it is and hence the greater the possibility of quitting. Otherwise, if you are full of misunderstandings or blind spots in your mind, you will definitely break the reboot. The shortcoming of brother  Lefty lies in failure to emotionally manage oneself. I have seen countless cases of
brothers. Many have lost due to lack of emotional management. There are always contradictions and dissatisfaction in life, such as quarrels with parents, or with colleagues and friends. 
Relationship tensions, things not going well, encountering great distress, etc., will affect a person's emotions. When negative emotions arise, you must learn to manage emotions. Just 
like a clock that goes too fast or too slow, one must adjust it to the correct time. This ability to adjust emotions is extremely critical for rebooting. Emotions can lead to relapse, especially bad emotions. Of course, carnal emotions can also lead to relapse. So it is best to maintain a stable emotional state.

Lefty separates rebooting knowledge and mentality adjustment. In fact, there is a misunderstanding here, because rebooting knowledge includes the adjustment of mentality. I have repeatedly emphasized the importance of emotional management in previous articles. You must immediately intervene when bad thoughts arise, otherwise these negative thoughts will distract you from yourself and control your behavior and lead to relapse. However, Lefty has realized the importance of emotional management, that is, the importance of mental adjustment through relapse, and hopes that
he can quit completely now. After passing the emotional management stage, rebooting will become very stable.

You don’t need to separate awareness from mentality or habits, because rebooting awareness includes developing good habits, such as not staying up late or loitering in bed after waking up. Enlightenment also includes adjusting your own mentality. Enlightenment is a general term, and all theories of successful rebooting can be included in this word, including vigilance awareness. **Successful rebooting = high awareness + strong vigilance**. The reason why I separate vigilance from is actually 
to emphasize the importance of vigilance awareness. In fact, vigilance awareness also belongs to the general category of awareness.
Emotional management is an important distinction between brothers. Too many brothers die on the emotional level. After passing the emotional level, they will enter a new level of rebooting, otherwise they will not be able to pass the emotional level. The possibility of relapse is still very strong. Some brothers may have to break the reboot many times before they realize the importance of emotional management. Mental adjustment and emotional management actually mean the same thing. The experience posts I wrote are all my thoughts and understanding. Many brothers do not have deep experience, so reading my article may not lead to realization. When such a brother sees the words "emotional management", he is not impressed. After being 
abused by the heart demon countless times, he might suddenly realize that emotional management is actually crucial. It turns out that emotions can really lead to relapse. Only then does one realise the importance of emotional management.

We must learn to manage emotions when rebooting. Some brothers may ask, how to manage emotions? If you talk about emotional management in detail, you can write a book, but the content of a book can be summarized in two words, i.e. psychological suggestions. For example, if you are very upset in your heart, you can suggest to yourself *stay calm* and *don't think too much about it*. You can also think of things that make you happy. I was neurotic at the time. I lived in depression and 
despair every day. I even had suicidal thoughts. Later, I learned emotional management, especially when I felt depressed, I immediately thought of some relaxing comedy clips. And then I adjusted my mood, and now I adjust my emotions in the same way. There are many ways and techniques of psychological suggestion. You can also visualize selflessness, where the emotions and troubles come from the selfishness. If you empty yourself, you can naturally calm down the troubles of bad 
emotions. You can also think in this way, using the theory of health preservation in Chinese medicine. 

>*Come to enlighten yourself, because anger hurts the liver, troubles cause yang, seven emotions cause illness, and bad emotions can lead to diseases*

So we must learn to keep calm and conform to the way of health preservation as much as possible. We should not suppress bad 
emotions. Strong pressure will damage our health. We can transform our emotions or make them empty so that we can pass the emotional barrier safely. Emotional management also includes motivating oneself like making oneself feel the emotion of forging ahead. Motivating oneself can effectively overcome the emotional laziness period of rebooting, and keep oneself in a state of courage and progress.

In addition, I want to emphasize that, try not to laugh excessively, because I have seen some brothers who say that they have to laugh every day. That is also not in line with the way of keeping good health. You can laugh knowingly, laugh in a restrained manner, and don't need to laugh everyday. Laughter can lead to extreme joy and sorrow, and it can cause sudden death. There are two real cases in my experience. One was in the community chess room. An old man was playing mahjong and 
caught a card, which made his hand the best possible hand. He then laughed and suddenly died on the spot. Another case was even worse. A 25-year-old young man who had just got married was in a state of laughing with his wife after eating. He died suddenly, and the ambulance came but they were helpless. 
These two real cases remind us to try not to laugh excessively, but to laugh in a restrained manner, so as not to cause happiness or sorrow.

Brothers with common sense of Chinese medicine will know that people who indulge in sexual desire are likely to have heart problems, because the kidney is the root of the five internal organs, and if the kidney is weak to a certain extent, premature heart palpitations and even cardiac neurosis may occur. Some brothers come to reboot, and they are likely to have such an idea: *How is it that all the symptoms apply to masturbation?!* In fact, if one has a deep understanding one would not think so. **Chinese medicine**: The kidney is the root of the five internal organs, and if the kidney is small, disease is possible. These are the truths of Chinese medicine. After thousands of years of 
verification, it is not a misunderstanding that we attribute all the mentioned symptoms to masturbation. If your understanding is limited, or experience is not deep, it is likely to be misunderstood. Of course, there are many pathogenic factors. Exogenous factors, dietary factors, emotional factors, bad living 
habits, such as staying up late for a long time, long gazing, overwork etc. can all cause symptoms, and poor congenital  physical fitness is also a factor. If multiple pathogenic factors work together, the sperm injury will be more serious. The 
way to hurt the essence is not just masturbation. Staying up late, getting angry, sitting for a long time, etc. will all deplete the essence of the kidney, so we must pay attention to the way of health preservation.

Based on my studies and understanding, I will share with you the specific methods of emotional management. We must do a good job in emotional management and be the master of our emotions. 

1. **Confirm the current emotions**: When you have negative emotions, such as anger, depression, decadence, despair, etc., you have to realize that the negative emotions have appeared. The first step is to discover and confirm the negative emotions, just like finding the enemy.
2. **Transfer the bad emotions:** When you realize that you are experiencing bad emotions, like being shrouded by dark clouds, you have to learn to transfer bad emotions. You can fold a paper ball, imagine that the bad emotions are wrapped in it, and then throw it into the trash can.
3. **Replace with good emotions:** When you realize that bad emotions have appeared, immediately think of happy things, such as a happy experience, a good memory, or a joke, so that you can get rid of the negative emotions immediately.
4. **Void yourself:** You can visualize that there is no self, where the emotions and troubles come from without self, everything is a mediocre self-disturbing, emptiness of yourself, so that negative emotions can not find a target.
5. **Vent negative emotions:** You can eliminate bad emotions through appropriate exercise, such as playing basketball, or going for a walk, or watching movies and listening to songs.
6. **Motivate yourself:** Affirm your progress, say words that motivate yourself, listen to motivational songs, watch motivational movies, and re-burn your fighting spirit.
7. **Do more charitable deeds:** helping others is the basis of happiness. When you are in a bad mood, you can try to do some small deeds, such as cheering for brothers online, and giving positive energyto them, so that you can also adjust your emotions.
8. **Health awareness:** Realizing that negative emotions can cause illness, why should we indulge in it? It's like slashing yourself with a knife, and immediately stopping the negative emotions means you stop hurting yourself.
9. **Keep smiling:** Smile, it is one of the most beautiful expressions. It implies that you are optimistic, keep smiling, and live every day positively and optimistically. There is no obstacle that can't be overcome, and the key lies in attitude.
10. **Relax yourself:** Don't be too hard on yourself, you will collapse if you are too hard, learn to relax yourself, take a hot bath, do health-preserving exercises, don't think too much, and get away from your worries.

## Summary
Emotional management means that we can choose emotions. Emotions are like supermarket goods. We can choose. When negative emotions appear, we should be aware of it immediately. Then we can choose good emotions instead of letting negative emotions take control. 
Negative emotions are actually negative thoughts. For those thoughts, we must also realize that when we think about them, we should not be controlled by negative emotions. 
Once controlled by negative emotions, it is easy to break the reboot. In the final analysis, to reboot is to learn to observe thoughts, recognize thoughts, and manage ideas. We study rebooting articles to improve our consciousness, the ultimate goal is to improve our ability to control thoughts. For example, if a person has 300 thoughts a day, which thoughts are likely to lead to relapse, you should be aware of, such as negative emotions, obscene thoughts, instigated thoughts, carnal thoughts, thoughts of doubts about rebooting, or future doubts etc. In short, we can see there are many thoughts that lead to relapse, and some thoughts are well-disguised, such as the thoughts of instigation. For thoughts, we should be an observer, and identify which thoughts are problematic and which thoughts are likely to lead to relapse. Once such thoughts appear, we must immediately intervene and cure them. It’s like setting up a checkpoint on the road to let thoughts pass one by one, but the problematic thoughts cannot pass. Once you let the problematic thought pass the checkpoint, it will dominate your behavior, because thoughts lead to behavior, **Thoughts → Behavior!** Once the problematic thought has passed, it will lead to relapse. Let us be a thought observer, let us be a thought master!

## Book recommendation

**"The Bardo, Hearing and Teaching"**, *written by Padmasambhava.* 
I highly recommend this book. If you get this book, it is a treasure. Of course, there are many people who are 
unfamiliar with these works, even if they see them, they will miss them. This book has a graphic version. The graphic version is more intuitive. What I recommend is the explanation version of the vowel old man, using Sun Jingfeng’s translation. There are several editions of this book. I prefer Sun Jingfeng’s edition. It is perfect with the explanation of the old man with vowels. The vowel old man's documents on the bardo teachings can be found on Baidu. After downloading, you can print them out and read them. There are also books to buy on the Internet. I hope those who are destined will not miss this precious text.
