## The health pile of the secrets of the body recovery

## Foreword {-}

### A tree therapy case {-}
>I’ve been doing tree therapy for about two weeks now, and for at least half an hour a day. I hug a ginkgo tree. It is indeed effective. The skin becomes smooth and fair after hug the tree, but it will reverts after a while. I used to use the computer for a long time every day. Is this why my skin doesn't look good? How can I keep the fairness and exquisiteness after tree therapy?
>
**Analysis**: This brother practiced tree therapy and chose ginkgo trees. I am work with camphor trees and ginkgo trees. Ginkgo trees are generally cleaner and warmer. The effect is better is usually better and more pronounced. Of course, the effect is more apparent right after finishing the procedure, but this brother's awareness of health maintenance is very poor. Long periods of time staring at the computer will result in "screen face", which will counteract the effect of tree 
therapy. Sitting for a long time also hurts the kidneys and the spleen, and long-term staring hurts the liver. If you stay up late playing games, the damage will be even worse. Staying up late will hurt your complexion and will lead to endocrine disorders, dark circles under the eyes or aggravation of acne. 
Therefore, when we are doing tree therapy, we must pay attention to the way of health, and strictly control the emission of spermatorrhea. The positive effects of doing tree therapy for 3 days is neutralized by a single occurence of spermatorrhea. Also, tree therapy should be a consistent practice. It is best to 
do it for atleast an hour, and more than 2 hours is even better. Of course, it is not necessary to stand for 2 hours at a time. You can have a tree therapy rest session and then continue. Be flexible. 

Brothers who don't have time can do it for at least half an hour each time, and they can listen to songs when they are bored. In addition, you should pay attention to safety when doing tree therapy. The surrounding wild life can be dangerous and could have snakes. Also don’t do it by the river, especially a river without guardrails as you may fall into the river accidentally. Choosing the right trees and the right environment is very important. Try not to go to uninhabited places. You can be in a relatively quiet place with a few people. Anyway, the people don't know you. After a long time, your skin will become thicker. It doesn't matter. Habits start to make things feel natural. The effect of tree therapy is good, but it also depends on whether you have the faith, the time, and a suitable environment. Those who insist on practising with faith will surely experience the magical effect of tree therapy. It is completely natural and completely free of artificial cosmetics.

### Rebooting couple {-}

> I could be considered as a long time rebooter, about 10 years ago, after reading your articles, I felt a lot of emotion. I agree with you very much. Quitting is a must, but I have a few questions to ask you. First, you said that you had prostatitis but you completely recovered after one year of abstinence. Did you get a result from an examination report that you have recovered or is it that you personally feel that your symptoms have recovered? If you go to get a check up, could you send your report to us to look at? Second, you said that you had premature
ejaculation and severe impotency before, and so, till now you have quit for 3 years. Your article "rebooting as the best remedy" also mentioned that you recovered in about a year. What 
verification is there for the recovery of this symptom? Since you haven't broken the reboot for more than 3 years, how do you know that the correct function is restored? Third, I would like to know under what conditions do I need to take medicine + reboot all the time, and in what situation can I just reboot + exercise + dietary supplements?

**Answer**
1. The symptoms of prostatitis have all disappeared after persisting in rebooting and keeping in good health for more than a year. After reviewing the prostatic fluid, the indicators have all become completely normal. Insist on rebooting and maintaining health, actively exercising, you will slowly recover. There are posts on alleviating recovery in the forum. You are a newcomer. If you read more to increase your experience, you will no longer have doubts.

2. The proof of recovery can be seen from the quality of morning erection, it is not necessary to try, if one's consciousness is not high, it is very likely to lead to going out of control and starting to indulge in masturbation again. I have talked about this in "Rebooting as a Good Medicine ". I have also talked about this issue in several quarters of articles. I suggest you take a closer look. In addition, there are also cases of recovery from premature ejaculation and impotence. Last season I took a screenshot of a real case of recovery from premature ejaculation. There are many cases of recovery from premature ejaculation and impotence. Brother Jiaxing has a lot of experience and he knows a lot. When a person has recovered, he himself has experience in recovery. If you insist on rebooting and keeping 
good health, premature ejaculation and impotence are expected to disappear. Some brothers will try it, but I will not try it because I don't want to break the vow just to try.

3. Severe symptoms or persistent symptoms require active medical treatment, 30% treatment, 70% health cultivation. Complete abstinence is necessary, otherwise it is easy to 
relapse. Keep on! It is normal for newcomers to have a lot of questions. If you have deep experience, there is no problem answering them.

**Analysis:** Newcomers will inevitably have many questions. In fact, I have answered these three questions countless times. Many newcomers feel that prostatitis is irreversible because they have limited experience and have not met people who have really recovered. How many of the pre-chronic patients really completely quit? It is all relieved or temporarily cured with medication that has to be used on a continued basis, and the patient keeps relapsing. Over time, it is concluded that prostatitis is lifelong and cannot be cured. In fact, this view is biased. There are people who have been cured, but you have not met them. If you haven't met these recovered people, saying that one can't heal, is a biased view point. Many people are abstaining from sex, but do not pay attention to health 
maintenance, and the frequency of spermatorrhea cannot be controlled. As a result, the recovery is not satisfactory. After more than a year, they still cannot recover. This is actually a poor recovery. 
Those who truly recovered completely abstained from sex, strictly control spermatorrhea and have their own systematic health and recovery methods, so that they can positively expect 
recovery. Both rebooting and health maintenance must be in place. Many brothers suffer from long-term injuries, and recovery is relatively slow. At this time, they need to be patient, be preparedfor a protracted battle, work hard to maintain their health, and be psychologically prepared to face the recurring period of symptoms. To be honest, many brothers are not completely abstaining from sex. They can't control adultery, and they don't have awareness of health preservation. In this 
way, talking about recovery is like a dream. There are many misunderstandings in rebooting and recovery thinking. If you don’t figure it out, the result will be like entering a maze, and you may not be able to stay with it for a lifetime.

The improvement of the quality of morning erection is a sign of recovery of premature ejaculation and impotence. However, some brothers have almost no morning erection, but at the same time they do not have premature ejaculation and impotence. This situation also exists. In fact, their kidney qi is already in an insufficient state if they do not have morning erection. If the overdraft continues, their sexual function is likely to encounter problems. The quality of morning erection fluctuates and is related to the season, diet, exercise and other factors. A relatively stable and high-quality morning erection is an indicator of the recovery of sexual function. You can refer to this indicator to observe the recovery. If you are always thinking about trying, it is the heart demon who is urging you. If you quit for recovery of sexual function only, then the reboot will not last long, because you will always want to try. Recovery of the body? Generally, brothers who insist on rebooting and keeping in good health for a period of time will find that their morning erection has disappeared. This is actually a manifestation of the 
recovery of kidney qi. At the beginning of rebooting, morning erection may disappear for a while. It is a withdrawal reaction. Some new people don’t understand, they are prone to panic and relapse, thinking that abstinence is harmful. In fact, this is a withdrawal reaction. It will slowly return to normal. When the quality of morning erection is very good, it means that your sexual function can be restored quite well. It is like a balloon, which is filled with kidney qi. From the quality of morning erection, you can see the recovery of your kidney qi, and sexual function. The recovery of kidney qi is closely related to sexual functions. Therefore, the recovery of sexual function can be seen from the quality of morning erection. High-quality morning erection is a good indicator of kidney qi recovery, and a high-quality morning erection that not short-lived, needs a 
certain degree of rebooting stability. Just like you hit 10 points (darts) by chance, is that your true level? Some people 
fired ten shots, and more than seven shots were all 10 points, while some people fired ten shots, only one shot had 10 rings, and the average was also not good.

Some people have good morning erection immediately after eating foods or drugs that promote sexual desire. It's like athlete doping. They run very fast when they are doping, but they 
slow down if they don't. It's not their real strength. Kidney Qi needs to be brought back slowly. It is not immediately replenished with a few Chinese medicines. Yao Ming did not grow to 2.26 meters in one night, it is a process of slow accumulation. Chinese medicine says: *It is better to lie alone when taking medicine*. Take a hundred Chinese medicines, it is still better to sleep all night by yourself. This means that you don't sleep with your wife, but if you share the same room, the effect of a hundred Chinese medicines is nullified. During the developmental period, many people have high-quality morning erections every day. As we age, the frequency and quality of 
morning erection will decrease to varying degrees, and will even disappear completely. Generally, if you insist on rebooting and keeping healthy for a period of time, morning erections will appear. When you get older, your kidney qi can't be as full as when you were a teenager, so you must take care of it.

Regarding the article I wrote before, I said that I fully recovered. Based on the principle of seeking truth from facts, there is no need to lie to you. For example, gray hair, alopecia etc have all returned to normal. Now there are only a few white hairs. Previously there were a lot of them. Excluding the back of the head, there are dozens of them on each side. The manifestation of symptoms. I still pay attention to maintenance, because after sitting for a long time, staying up late, tired or having spermatorrhea, there is still a possibility of relapse. It is not a 
*"one and done"* recovery, because there is more than one way to hurt the sperm. As far as I am concerned, the recovery situation is relatively stable. Until now, I have basically never relapsed, because I strictly control *suicide* and have not relapsed. In addition, I pay great attention to the way of keeping good health, so as to minimize the probability of recurrence. 
My rhinitis has recovered much more than before. I rarely suffer from rhinitis. This is inseparable from the work of moxibustion. Hemorrhoids have also been cured by moxibustion. All of these 
have recovered. Although the rhinitis has not been completely cured, it is already very good. It’s much better than before. Restoration is a systematic project. I have put a lot of effort into 
restoration. I can get back to what I am now, and I am relatively satisfied. I will share my experience with you, and hope that everyone will be able to return to a satisfactory state as soon as 
possible.

Some brothers may think that medical proof is needed to prove that health has been restored. In fact, this is a misunderstanding. Many functional problems cannot be detected at all. Just like it is with many neurotic patients, they are already dead and want to commit suicide every day. They have many physical symptoms, but when they go to the hospital for an examination nothing is found, and family members even suspect that one is pretending to be sick. Some brothers go to the hospital to check prostate fluid and the results are completely normal, but the symptoms of frequent urination and urgency are obvious. Some functional problems are just not detectable by examinations. Medical 
instrument examinations have certain limitations. For this reason, there have been many misunderstandings and contradictions between doctors and patients. The patient feels that he is sick,but the doctor says you are not sick because the examination report is normal. What can you say? After all, they are doctors, so you can't refute them. Later, many patients switch to Chinese medicine. Chinese medicine doctors know where your body is out of balance just by taking your pulse. With Chinese medicine conditioning and health maintenance, your body slowly returns to normal. Chinese and Western medicine have their own strengths. Don't blindly believe in inspection reports. Normal inspection does not mean complete health. Many problems cannot be detected.

Many newcomers are not firmly confident in rebooting, which has a lot to do with feeling that they have no hope of recovery. Because they can't see any hope of recovery, they give up on 
themselves. They doubt the recovery of others and feel weird. In fact, they are ignorant. Their experience is still shallow. Some brothers are shaken as soon as they experience recurring 
symptoms and think that they did not recover, as a result they relapse again. When this happens it means that on the one hand, their awareness/consciousness is insufficient, and on the other hand, the root of faith was not strong at the beginning. If the root is not strong, it is easy to retreat. Confidence is the 
source of success. If you don't believe that you can recover, how can you have the motivation to stick with it?

Many brothers have made a big fuss on the issue of "testing", including many senior brothers, when the idea of "testing" appears in their minds, such as testing concentration and sexual function. 

**!Remember!**
**Once this kind of thought arises, you must be extra vigilant, because it is the inner demon who is urging you to try, and the inner demon is very cunning and especially good at inciting.** 

Many brothers are not sufficiently enlightened or relax their vigilance. Once they get the idea of **"testing"**, they will try 
it immediately. Once they try, they will fall back into the trap.

### Premature ejaculation recovery case

> I started to pay attention around 2012. At that time, I could only last for 3 minutes. I was married. When I was the most serious, I started to pay attention (Don’t laugh at me). 
After a period of frustration, I came to this forum and found out that it was because I had used too much, so I started to stop. I broke the reboot three times in the middle, but the recovery was not bad, and now it is completely normal. Thank you predecessors of Benba, thank you for rebooting , I will
stick to it.

### Main topic

In this season I will share my recovery secrets from the "bottom of the box" as it were. These are very good for the physical recovery of patients with sperm injury, especially for neurosis brothers. I hope you will not miss the content of this season.

In a very early article, I suggested that you stand up or meditate, and you should combine dynamic and static health regimens, so that you can cultivate good health and stability of mind. Static power is very important. Light movement is not static, light movement still does not conform to the way of keeping good health. 

This season I will talk about the importance of static exercises, mainly about standing piles. The health piles I recommend are high-position piles, not Siping horses, or wall squatting. What I 
recommended before was Wu Guozhong's health-preserving pile. 

Here is a quote from Wu Guozhong:

>I practiced Chinese traditional martial arts since I was a child, specifically Dachengquan. There are no tricks and routines in this type of boxing. It's just **'hold your hands in front of your chest and stand quietly'**. This action is called **'Zhan Zhuang'** in martial arts. Application of this method, which is derived from martial arts, to health maintenance and curing diseases is called the **"holding health"** health maintenance method. So far, I have found that this health care method that integrates health 
maintenance, traditional Chinese medicine, and martial arts is actually all the current physical and mental exercises. The simplest and most effective of the methods. The founder of Dachengquan, Mr. Wang Xiangzhai, was extremely weak at the age of seven or eight, and suffered from intractable asthma. There was no good way to cure this disease at the time. In desperation, the famous Xingyiquan master, Mr. Guo Yunshen, who had the reputation of *"Half-step collapse fist 
hits the world"* in the martial arts, taught him the secret of Xingyiquan-standing and keeping health. Mr. Wang Xiangzhai used this kind of health cultivation technique to restore his body. Not only did he heal his illness, but he also unknowingly gained a lot of strength in his body. There is no need to guard the dantian when practicing the 'Holding Health' regimen, and there is no need to get rid of all distracting thoughts. Think of more pleasant things because this makes the heart happy and a slight joy is 
better than any other medicine to nourish the heart. At this time, we are relaxed and carefree. Look, before long, you will You will taste the joy of the body."
---Wu Guozhong "Living to the End"

The effect of Wu Guozhong’s health-preserving pile is very good. In fact, it is a martial art exercise,which has both health-preserving and martial arts functions. Many people in the health-preserving world are also practicing this pile. The essence of Chinese traditional martial arts lies in the 
standing stance. 

**"To wash the bone marrow, start with the standing stance."** 

A hundred trainings are not as good as one station. Zhan Zhuang is highly valued in the martial arts world, and it is not an exaggeration to describe it as extremely important. My previous articles have always recommended this practice to brothers, and many brothers have received good results. But there is a tiring part of this pile of work, which is, holding your hands, it feels like holding a balloon. Feeling loose. Wu Guozhong’s method is of course very good, but this season I want to recommend another health-preserving pile, and the effect is also very good, that is, the Ziwu health-preserving pile. Read the following:

**Standing in the Zi Meridian Gate**: Raise the two forearms at the waist, 90 degrees to the upper arm, parallel to the two forearms, straddle one step to the left with the left leg shoulder-width apart, sink the shoulders and drop the elbows, with chest drawn back, head straight, Baihui and perineum are in a straight line, the lower jaw is slightly retracted, the tongue is topped with the upper palate, the lips are slightly closed, the whole body relaxes, intends to guard the pubic area, and breathes against the abdomen to gradually achieve a long and uniform breathing. Standing time depends on age and physical condition. It depends, from short to long, strive to reach more than 30 minutes each time. First of all, the Laogong acupoint starts to heat up, numbs and beats to the dantian fever, that is, there is a sense of qi. As long as the practitioner has good physical fitness and the practice time is long, the whole body's meridians can be opened up in a short time. After practicing Zi-meridian exercises for 3 days, I felt a sense of qi. After 10 days, I felt my energy 
doubled. After a hundred days, I can release my internal qi and reduce my external qi.

The health-preserving pile belongs to internal cultivation and belongs to the internal strengthening. Strength training belongs to external strength. Many people who practice bodybuilding are actually strong from the outside. The muscles look scary from the outside. In fact, they are weak inside. Being strong does not mean being healthy. Recently, there was news that the former 
national bodybuilding champion Long Yunlei has leukemia. Originally, he had a stroke and then leukemia. Although he was only 35 years old, his fate was really miserable. Can you imagine a person who is as strong as a cow and has a stroke? Can you imagine people who are several times stronger than you get leukemia? I remember that a few years ago, a bodybuilding champion in Beijing, named Bao Pucheng, died suddenly at the age of 36 years. So being strong does not mean being 
healthy, but being strong does make you feel healthy. This is a superficial feeling, just like some apples look good on the surface, but after biting them, they are all rotten inside. The superficial phenomenon is deceptive. A strong body may not necessarily lead to a long life. 

Another example, Paul Anderson, the sun god in the power world, squatted more than 1,200 pounds, and only lived to 62 years old. Only lived to be 62 years old. Many old men squat no more than 50 kilograms and easily live past 80 years old. Therefore, keeping in good health is really the key, and exercise should be done in moderation. There are three levels of 
exercise: **nourishment, exhaustion, and injury**. Health-preserving exercises belong to nourishment, sweating aerobic exercises and even strength training belong to exhaustion. Excessive exhaustion is an injury. Traditional Chinese Medicine: **Sweating and hurting Yang! Sweat and hurt!** 

Young people can afford to get hurt a bit, they don't feel it. If your body is relatively weak however, you should choose to walk without sweating or slightly sweating, and practice more health maintenance techniques. When the body is almost recovered, you can do some strength training appropriately.

Speaking of my connection with the Ziwu Health Pillar, it was relatively early in my school days when I first discovered it. I remember I saw an introduction to the Ziwu Health Pillar in a magazine in the second year of the junior high. I read that it belongs to the category of Liangshan Kungfu. At that time, I used to be very angry and by doing this practice my energy doubled. Hence, I was very interested. Then I got the book "Liangshan Kungfu" through mail order. There is still a lot of content in the book, but I didn't practice anything else, so it was a bit rushed.
 
This posture does not require the arms to be held up. Instead, the palms of the hands are facing upwards, and the empty fists are closed at the waist. It is a relatively simple posture, and it is also a high post. Squatting is fine, but be careful not to exceed your toes over your knees. At that time, I got angry very fast during practice, especially the feeling on my hands was obvious, and the energy really became very good, and the doubling of energy is definitely not a false statement.

Everyone may think, is the health-preserving pile is really so magical? In fact, the human body hasits own drugs, but unfortunately many people don't even know it. This season I will talk about this great medicine carefully with you.

>After knocking the teeth, saliva is produced, and saliva is kidney fluid. Saliva, swallow 30 times. A mouthful of saliva is equivalent to a box of Liuwei Dihuang Wan.
>-- **Qu Limin**

The human body's own medicine is the saliva in our mouth, but not ordinary saliva. It is the saliva secreted after knocking the teeth. The saliva secreted after knocking the teeth is very beneficial to the human body. 

Qu Limin said it is equivalent to a box of Liuwei Dihuang pills. And the big medicine I'm talking about is not the saliva secreted after tapping the teeth, but an upgraded version of the tapping saliva, which is the saliva secreted by the tongue against the upper palate, and the tongue against the upper palate means that the tongue is against the upper palate. In qigong studies, this is considered to be a bridge between the two channels of the governor, commonly known as *"the bridge of magpies".* 

Traditional Chinese medicine believes that the Governing Vessel runs through the back,and the Governor’s body is surrounded by Yang Vessels, which is the sea of Yang Vessels; Ren Vessel runs along the abdomen, always has any Body Yin Vessel, which is the Sea of Yin Vessels. 

The tongue can reach the upper palate to communicate with the two channels of Ren and Du, so that the meridians of the whole body are connected, and the upper and lower air flow is unblocked. Frequent practice of this exercise can clear the blood, strengthen the meridian, refresh the mind, and strengthen the physique.

The two points of Jinjin and Yuye, and the multiple fluids of Zangjin are well known by doctors. The two acupoints, commonly known as "Hua Chi Water", are tied to the lungs and rooted in the kidneys. The acupoints are on the left and right under the tongue, the tongue is the seedling of the heart, the foot Shaoyin kidney meridian holds the tongue, and the spleen meridian of the foot Taiyin disperses under the tongue, so the two acupoints are not only related to the lung and kidney, but can nourish the spleen and yin. Mutual aid with the kidney water, inducing the kidney water to suppress the heart and fire, and combining the spleen and soil to nourish the lung.

Cheng Guopeng said that this "water of Huachi" can be used to treat the loss of true yin and the symptoms of yin deficiency and fire, and praised it as "the perfect prescription for curing yin 
deficiency." 

Fang Zai "Medical Mind Enlightenment", the method is: 

> Often use the tongue to touch the palate, fill the mouth with the water from the Huachi, so that the body is soothed, and send it to the dantian with the mind and eyes, and the mouth will be repeated. Three times, this is called the "swallowing body fluid" method. This is to divert the water from the Huachi Lake to delay the execution of the fire. 

"Su Wen" says: 

>"All people with chronic kidney disease can face south at the 
same time, clean the mind without chaos, and stop breathing without breathing seven times, so as to induce the throat and breathe smoothly, such as a hard pharynx. After seven times, There are countless energies under the bait's tongue." 

This is the method of drawing water from Huachi to nourish kidney yin, and regenerating through gold and water. The above-mentioned tongue touches the upper palate and draws the fluid under the tongue and swallows, namely, the two points of Jinjin
and Yuye are hidden. This method of inducing pharyngeal fluids originated from the Dan family. The original intent was to maintain health, and later to use it to treat diseases. It conforms to medical theory and conforms to nature. The method is simple and effective. I pay attention and observe that in healthy infants and young children, the tongue often touches the palate and the 
scrotum is often tightened. This is the mutual growth of yin and yang. The tongue is the seedling of the heart, and it stores the golden fluid and jade liquid; the front yin is the orifice of the kidney and embodies the true Qi and Yuanyang.

The power of this "Hua Chi Water" is really extraordinary. It is a great medicine for the human body. It is very good for the recovery of the body and the recovery of neurosis. The effect is very fast and energy is improved significantly

Taoism often refers to body fluid as jade liquid, jade jelly, liquan, spiritual liquid, etc. It is believed that this liquid is produced by refining qi and is the essence of the five internal organs, sweet and fragrant. If people practice diligently and rinse their throat fluids, they can prevent diseases and strengthen their bodies. The "Huang Ting Jing" says: Yuchi's clear water is filled with spiritual roots, and the spiritual roots are strong and old. The "External Scene Jing" also attaches great importance to the role of body fluids, such as "Yuchi clear water can irrigate spiritual roots, and the repair can last forever." Open both ears up and down, peek into the heaven and the earth to save the boy, blend the essence and treat the hair and teeth, the color and luster will not be white."

Regarding rebooting and health preservation, the "Tai Ping Sutra" advocates that "If you want to live a long life, you should respect the spirit.

"The "External Scene Jing" also emphasizes the meaning of solid essence and precious essence. Go old and rejuvenate".

When I meditate or stand, I usually touch my tongue to my palate. Within 5 minutes, the Huachi water will come down. It tastes different from ordinary saliva and has a sweet and delicate 
fragrance. Then I swallow it, which is equivalent to "eating elixir". This is really a free elixir produced by the human body. It is a pity that many people don't know it at all, and they are still seeking medicine. In fact, they have a treasure, but they don't know. When you stand or meditate, you will have delusional thoughts at the beginning of the practice. You can use the counting-breath 
method to contemplate. Regarding the problem of keeping the orifice, the Ziwu health-preserving pile means keeping the pubic area, while I myself keep the pubic area, that is, the position of the eyebrows. One is prone to nocturnal emission in the pubic area, and one is also prone to nocturnal emission if meditating before going to bed. Moreover, there is also a law-abiding method. You can't keep it strong, but "know but not keep, save first and forget." Don't keep strong. Strong defense is easy to go wrong. Or you can keep nothing, just focus on counting your breath. A mouthful of Huachi water can be swallowed in several mouthfuls, but there is also a knack for swallowing it, and it is perfect with the sixteen-character ingot gold.

What is sixteen-character ingot gold?

Taoist Qigong Health Preserving 16-character Ingot Gold:

>When you inhale, you lift up, the qi returns to the navel, and when you lift it, you swallow. The fire and water meet each other.

This is the Taoist sixteen-character ingot gold produced during the Song and Yuan dynasties.

It was first seen in Leng Qian's *"Xiuling Must Refer to the 16-character Jue for Longevity"* in the early Ming Dynasty. From the emergence of Taoism at the end of the Eastern Han Dynasty to the appearance of the sixteen-character ingot gold, it took more than a thousand years.

Sixteen gold ingots, also known as Li Zhenren's 16-character Jue for Longevity, is a representative exercise of Taoist health preservation. The sixteen-character words are "lifting when inhaling, returning qi to the umbilical cord, swallowing when lifting, meeting water and fire". This method was first recorded in Leng Qian's "The Essentials of Xiu Ling" in the Ming Dynasty, and he praised it as a most simple and easy trick. Later, "RedPhoenix Marrow", "Eight Notes of Zunsheng", 
"Maiwang", "Secret Records of Health Preservation", "Medical Prescriptions" etc. all introduced this method.

The Ming Dynasty health regiment Leng Qian's explanation of this in *"Xiu Ling Yao Zhi"* is different, calling this sixteen-character ingot gold *"long life 16-character magic 
formula"* and *"simple and easy magic formula"*. He pointed out that this trick is more practical, feasible everywhere, and everyone can practice it and introduced the cultivation method in a popular way. This is recorded below: 

>You must rinse your mouth three or five times with your 
tongue. The tongue stirs the upper and lower palate, and the tongue is still on the palate. The mouth is full of fluid, swallowed again and again, and there is a murmur. Take a breath in the nose to express yourself. Reaching the heart, silently send it straight to the three-inch Dantian Yuanhai below the belly button, and save a little, which is called a suck. With the lower part gently like a poop, lift it with will force to return to the umbilicus, even And Jiaji Shuangguan Kidney Gate is lifted all the way to the back of the jade pillow pass, penetrates into the top of the mud pill, it rises up, and does not feel the qi comes out, it is called a breath. The qi rises, and then swallows as if it was a murmur, inhales the clear breath, and sends it to the dantian for a while, and then gently lifts it up from the bottom as before, and connects with the umbilicus, the so-called qi Return to the umbilical cord, longevity and heaven are together.

In addition, Zhan Zhuang can treat frequent dysfunction. Brothers who are troubled by frequent dysfunction can also try Zhan Zhuang and eat more "Elixir". The human body has its own medicine, so do the practice. Taoist Tian Chengyang said that standing upright can strengthen the body and replenish qi.

Regarding the role of Huachi Water, some texts are excerpted below for your reference:

> Pharyngeal fluid function: Yanjin health preservation has a long history in our country. The ancients called it "fetal eclipse", which refers to throat fluid. "Han Wu Nei Chuan" said: "Xi gushes the tongue under the spring and swallows it, the name is fetal food." The doctors of the past have realized that the body fluid in the mouth is a precious substance that is beneficial to human health 
and longevity and should be swallowed.

>Sun Simiao, a great medical practitioner of the Tang Dynasty, said in "Qianjin Yaofang Volume 27": "Yuquan people have saliva in their mouths. Before the dynasty, gargle early to make the 
mouth full and swallow it." Traditional medicine is about pharyngeal fluid health. "Lingshu Tiannian", "Suwen Needle Method", etc. all talk about the important role of 
"blood fluid" and "bait swallowing fluid" on human health and the method of pharyngeal fluid. The pre-Qin "Zihuazi" said: "The journey of Rongwei and Wei will not fail, the six fu organs will 
transform the valley, and the liquid will be spread, so it can last for a long time without harm." Unearthed at the end of 1973, "Tian Xia Zhi" "Tao Tan", which explains the "eight benefits" of 
health preservation in the house, talks about the health preservation function of "swallowing body fluid". All these show that the ancients of our country discovered the function of saliva in the human body very early, which is consistent with the research and discussion of modern science.

>Taoist health practitioners call the saliva produced in the process of practicing the "gold liquid to 
return to the dantian" (see "Golden Pills"). This kind of saliva has many nice names: Jinjiangyuli, 
Lingye, Shenshui, Liquan, Jinjin, Yuye, Jinli, Yujin, Yuchi Qingshui, Yuxi, Sublingual Spring and 
so on. The ancients believed that swallowing this body fluid is good for health preservation. Ming 
Dynasty medical scientist Li Shizhen, in his book "Compendium of Materia Medica Volume 52", 
made the following explanation of "Kou Jin saliva": "There are four orifices under the tongue. 
Liquid. The heart air flows into the tongue as the divine water, and the kidney juice flows into the 
sublingual as the spiritual liquid. Taoists call it golden jade liquor, overflowing as Liquan, gathering
into Huachi, dispersing as body fluid, and reducing to nectar, so it irrigates the viscera and 
moisturizes the limbs. Therefore, to cultivate the family’s throat and qi, it is called clear water to 
irrigate the spirit root. If people can not saliva all day long, the essence will always stay, and the 
color will not be haunted; Saliva is not as good as near saliva, and it is better not to saliva as near 
saliva."

> Yanjin health preservation not only has a long history, but also conforms to modern science. 
Modern medicine believes that, in addition to water, human saliva also contains amylase, lysozyme,
mucus protein, amino acids, and a small amount of sodium, calcium and other substances. It has 
various physiological functions and is beneficial to digestion, health preservation, and body 
strengthening. . In recent years, scientists have also discovered that saliva can disinfect, detoxify, 
fight cancer and kill HIV.


>Chinese ancient health preservationists attached great importance to pharyngeal fluid health 
preservation. Taoists noticed the health-preserving function of pharyngeal fluid earlier. The "Huang
Ting Inner Jing Jing" of the Jin Dynasty talked about the function of saliva in many places. The 
"Huang Ting Inner Jing Jing" mentioned that "the mouth is the Yuchi Taihe Palace. Evil jade 
refines the face, and examines the cultivable Deng Guanghan". These five sentences mean that the 
mouth is the place where saliva is produced, and swallowing saliva can prevent diseases, prevent 
diseases, and achieve the purpose of prolonging life.

>Regarding the specific methods of pharyngeal health maintenance, there are descriptions in some 
health-preserving guide books of the past dynasties. The "Ba Duan Jin Daoyin Method" in  "Zunsheng Bajian Yannian but Disease Jian" records the method of pharyngeal fluid: "Chilong stirs 
the water and rinses the fluid for thirty-eight. After waiting against the water, rinse and swallow the 
body fluid again. After three times, the spirit water is swallowed nine times. The swallowing 
gurgles and the pulses are adjusted by themselves.” According to the Qing Dynasty Youcheng 
"Shou Shi Qing Bian", Yan Jin "lipped the tongue." The upper palate will be filled with fluid for a 
long time, and it will be swallowed, and the swallowing will make a sound, so that the five internal 
organs can be irrigated and the fire can be reduced quickly. The number of swallows is better."

## Conclusion

I hope everyone use their naturally occuring "Elixir". The human body has its own medicine. I eat "Elixir" every day. I attach great importance to the "Hua Chi Water" in my mouth. The elixir has a good recovery effect on all kinds of symptoms of sperm injury. It is also very effective in improving neurosis and brain power. Energy is doubled, but the cost is persistence. One typically starts at 15 minutes initially, it then slowly extends to each time. It then reaches half an hour and finally 45 minutes per session. I was able to recover from neurosis at that time, and it was inseparable from eating elixir. I was completely desperate for 
medicine and it was very expensive. In the end, I relied on "eating elixir" and other health regimens.After more than half a year, I felt recovered. After more than a year, neurosis disappeared.
