# Cultivation of good rebooting habits & time management

## Foreword {-}

### 1 feedback and 2 Q&A cases

> On lunch break, I lay on my bed and read the 46th season updated by Teacher Feixiang. After reading it, I started practicing, and the stand was more than 45 minutes. Previously I was doing doing round piles and tree therapy. I had never meditated before because I have delusional thoughts, and it is difficult to contemplate with the counting breath method. I get tired after standing for a long time in the full-round pile position, and I can’t persist longer. I am only motivated to do tree therapy 3 minutes at a time. When I go to the station, I love this method (not an exaggeration, the biggest feature of this station is that it is not tired, but the skill is very powerful! And it does not need to be completely contemplated, I will still use it when I stand. Counting breaths or reciting the Buddha, and grateful to Teacher Flying from the heart), and then a miracle happened to me quietly. 
During the standing process, Teacher Flying said, "First, Laogong acupoint started to become feverish, and the numbness began to throb to Dantian. "Fever", I can feel it. I instantly opened up 
the Rendu Meridian and the meridians of the whole body. After a few months, the blood blockage in the body was instantly dredged, and a fresh and hearty feeling that I had never experienced before suddenly came to my heart! After standing, my palms were sweaty, and my back was all wet,and the haze in my heart was swept away, and I saw the sky again! Being sluggish and wretched, I can suddenly smile and be alive and kicking! Teacher Feixiang, I salute you from the bottom of my 
heart! You have saved me high psychological and medical expenses, so that I can continue to fight against the demons with confidence! And what's interesting is that after standing on the pile, I went to the park to hug the tree for more than an hour in high spirits. The effect was the same as this pile,and it was immediate! After I came back, I looked in the mirror and found that the places on the cheeks that have been pasted are different from those that have not been pasted. The pasted areas have become delicate and white. I am very happy! ----Pure Heart]

**Additional comment:** The Ziwu health pile I recommended in season 46 is easier to use, simple, not exhausting, easy to persist in, and the effect is very obvious. I stand on this pile every day now, and this pile acts faster, especially with respect to hand sensations. I remember that I used to be very concerned about the breath before. If I could sense my breath, I felt very happy. If there was no sense of breath, I felt that the effect was not good. In fact, it was falling into the mortar of the sense of air. Later, I realized that the most important thing is not the sense of breath, but the tongue. The sip of Huachi water that comes down from the palate is the precious medicinal material for replenishing vitality, that is, the great medicine for the human body. Now I don’t care about the sense of breath, but pay 
more attention to the Huachi water in my mouth. I swallow more than ten times on average every time I stand. Huachi water has a sweet and fragrant taste, which is completely different from 
ordinary saliva. It is especially secreted during exercises. In normal times, the tongue can also be pressed against the palate, but it does not secrete as much as it does during practice. What I recommend are health-preserving exercises, which are not supernatural powers. I have never objected to seeing a 
doctor. Illness should be actively treated, but 30% treatment, 70% health preservation, and health preservation should be the focus. Don't put all your hope on the doctor. After all, the symptom of sperm injury is not a small cold, and it can't 
be cured by taking a few pills. Patients with kidney deficiency must pay attention to rebooting and preserving essence, otherwise what is taken for healing from above is leaked from below, and it will be difficult to heal in this way. I remember a few brothers who had problematic spermatic cords went for surgery. They didn't pay attention to maintenance after their operations, and they broke the reboot again. As a result, the spermatic cord relapsed again. Who can one blame this on? Therefore, we must pay attention to rebooting and health preservation, and we must pay attention to maintenance. It is
very wrong to put all hope of recovery on doctors and surgery. We must remember 30% treatment and 70% health preservation, which is lighter and heavier, so that it is clear at a glance. If the symptoms are severe or persistent, they should be actively treated, and then supported with rebooting and maintaining good health, so that recovery will be faster.

> Have been abstaining for 200 days. Recently, after a spermatorrhea, the heart demon launched a fierce attack. At that time, I was a little hesitant. Then it was difficult to recover the original feeling of rebooting. Until now, YY is serious, like suffering. Self-analysis is related to the enhancement of self-awareness after rebooting is stabilized and the initial lack of solid awareness ofrebooting. I don’t know how to get out of the sea of suffering?

**Answer:** After the spermatorrhea is a period of high incidence of relapse. Confidence is bound to be shaken, and moods will also change for the worse. Therefore, we must be aware that it is easy to relapse after spermatorrhea, we must be vigilant, strengthen study, and pay attention to adjusting emotions. Additionally we must do a good job of interrupting the culprit thoughts, so that we can smoothly pass this period of high incidence of relapse. Fight on!

**Additional comment:** After spermatorrhea is a special period, the reason it is special is because this period is a period of high incidence of relapse, and it is very easy to relapse if you are not vigilant after spermatorrhea. After nocturnal emissions, people's emotions are no longer stable, just like when an airplane encounters airflow and experiences turbulence, confusion is prone to occur at this time, so after spermatorrhea, you must pay attention to emotional management to restore stability to
the emotions. I believe that senior brothers will attach great importance to the ability to manage one's emotions, because many people lose the emotional battle. Emotional management is related to emotional intelligence, and emotional intelligence can be learned. It is through learning that you canimprove emotional intelligence. Read more books on emotional management for yourself to improve your understanding and awareness in this area. Rebooting will be more stable if you 
manage your emotions well. Successful rebooting requires a stable psychological environment. I once compared rebooting to walking a tightrope. You should maintain a high degree of vigilance and maintain a stable mental state. If you are in a confused state, you will definitely fall off. Some brothers heard me say that they should be highly vigilant, and then they become afraid when they see women, they walk on the street very nervously, thereby making themselves nervous all day which affects their normal life. In fact, they misunderstood what I meant. Maintaining a high level of vigilance does not mean excessive vigilance. It is like walking a tightrope. Excessive tension will also cause one to fall off. Our rebooting is like a string. It cannot be too tight or broken, nor too loose. Maintain a high degree of vigilance, whether it needs to be tightened or loosened needs to be grasped by yourself.

> Big Brother Feixiang, you said that as long as you learn the mantra for severing YY, you can completely subdue YY, and all masturbation begins as YY first, so what should we do to improve our consciousness? Is it enough to recite mantras like chanting Buddha every day? You never elaborated this point in your article. I hope you can get rid of my doubts. I am going to add four kinds of pure and clear teachings. I wonder if they will be useful?

**Answer:** After passing the obscenity stage, rebooting is half done. Judging sexual obscenity also belongs to the category of enlightenment, and rebooting enlightenment also includes emotional management, nocturnal emission control, and health regimen. It is necessary to memorize the mantras to cut out obscene thoughts, and it is also very important to improve one's overall consciousness, otherwise relapse is still possible. It is very good to recite the four kinds of pure and clear teachings. If you have a relationship with the Buddha and have this confidence, it is recommended to recite the four pure and clear teachings every day. This can help you to purify your mind. If you are pious enough, you will naturally get blessings. Keep on!

**Analysis:** I suggest that you usually recite more of the mantras of judging the meaninglessness. If you think the four sentences are a bit long, you can recite two sentences or one sentence. Just recite one sentence and break it down when you recite it. The reason why many brothers are not able to 
let go of fornication is because they *grind their guns* and hold Buddha's feet temporarily. When the fornication thoughts appear, they remember to recite the mantra of fornication and find that it doesn't work very well. In fact, if you want to use this formula well, you must recite it a lot in normal times. Just like reciting the Buddha's name, you can recite it hundreds of times a day until a conditioned reflex is formed. If the evil thoughts come, they will be immediately cut off. It is completely automated. There is no need to struggle at all. If you 
still struggle or hesitate, it means you haven't reached home. When this mantra is profusely recited, it will subconsciously stop fornication, which runs like a computer's automatic anti-virus software. When the time comes, it will be effective, and there will be no thought struggle at all. In fact, the same is true for reciting the Buddha's name. If you repeat the Buddha's name a lot, if you have delusional thoughts, you will immediately turn into Buddha's name. It is completely automatic and completely subconscious. There is no need for thought struggle or hesitation. To reach this state, only a lot of repetition is required, and it must reach the point of conditioned reflex which will achieve automatic elimination of evil thoughts. Repeat all the time. When you are attacked by obscenity, remember to use it again. If it is not recited frequently it is a blunt knife and it is not powerful! The mantra for judging obscenity is like a knife. You must always sharpen it. When the obscenity comes, you will be able to use its sharpness. Otherwise, when you hesitate, you 
will have to go through a fierce thought struggle. If you don't get it right, you will end up breaking the reboot and then you will be very passive. 

### Main topic:

This season, I will share with you the development of good rebooting habits and efficient time management.

Many brothers have mentioned the importance of habit, because they have seen the great power of habit. Both good habits and bad habits have great momentum, just like a boulder rolling down from a height. Habits lead you forward or carry you along with them. Bad habits cause you to self-destruct. It is accurate when brothers blame relapses on habits. Indeed, some habits can easily lead to relapse, and some bad habits are not conducive to the recovery of the body. The development of 
good rebooting habits is an essential part of raising one's conciousness. Here are some examples of bad habits:

1. **Lying in bed:** Laying in bed after you have woken up is a very bad habit. Laying in bed can easily lead to relapse. I have 
specifically summarized the types of relapses in bed. It’s easy to start fantasizing when you lie in bed, and it’s not good for your health. Chinese medicine says that prolonged lying in bed hurts the qi and staying out of bed will affect the growth of the body’s vital energy. Some brothers don’t even eat breakfast which is even worse. The habit of staying in bed must be changed. When you wake up, you should get out of bed immediately. Don't think about things in bed, let alone indulge in obsession. To overcome the habit of lying in bed, you must say to yourself: 

*From tomorrow on, I will never sleep in bed again.* 

Secondly, you can learn from the hotel’s morning call service. Anyone who has stayed in a hotel knows that most hotels have a morning call service. Set the alarm clock and place it out of reach. 

2. **Masturbation before going to bed**: There are so many brothers who masturbate before going to bed. If they don't they can't go to sleep and hence a bad habit is formed. Once the evil habit of masturbation is carried out one will feel tired and yawn. **Chinese medicine:** *The kidneys are responsible for sneezing*. At the moment of ejaculation, some brothers may even feel that the brain is emptied instantaneously. **Traditional Chinese Medicine:** *The kidney connects to the brain*. In fact, the kidney and the brain are connected. After masturbation, brain power will decrease, and brain power decline is also very common among brothers. This is not necessary for me to repeat  anymore, just look at the cases. After ejaculation, people are prone to tiredness, and they fall asleep. It is also easy to sleep-in the morning after masturbation, i.e., one can’t wake up. **Traditional Chinese Medicine:** *Kidney deficiency is connected to lying and moving.* 

Therefore, if you masturbate at night, it will easily lead to sleeplessness or sleeping in the next day. In the beginning, it was impossible to fall asleep, so people become accustomed to it, but the evil consequences are behind, and neurosis occurs after a certain degree of injury. The common one is neurasthenia. When the time comes, the more you masturbate, the more you can’t fall asleep, and you remain suffering and uncomfortable. It is really hard. And once a nerve is injured, the recovery time is measured in years, and in severe cases, it takes at least one year.

3. **Laziness, procrastination, and lack of patience**: People with kidney deficiency tend to become lazy, but regular people are also prone to laziness. If we want to reboot better, we must overcome laziness and develop good study habits. Laziness and procrastination seem to be a pair of brothers. 
Lazy people basically have the habit of procrastination, always saying that they will do it tomorrow, and always feel that they have time. When tomorrow arrives, they say that  they will do it the day after tomorrow, and this continues until the year of the monkey. We have to accomplish one thing, we need to act 
immediately after due consideration has been carried out, the execution must be strong, and the action must be decisive. The divine power of rebooting comes from learning, learning to improve consciousness, and defeating inner demons with consciousness. Many brothers are too lazy to study, they
procrastinate, have no goals, and lack patience. For brothers who are still in control, as soon as the kidney essence is lost, they tend to become impetuous, upset and irritable, and their brain 
power drops again, and they cannot learn at ease. If you realize this problem, you must learn to adjust and get back to a good learning state as soon as possible. My suggestion is to learn a little bit. Don’t put too much pressure on yourself at the beginning. Let your enlightenment accumulate a bit by bit. Prepare a rebooting notebook. When you see a good rebooting sentence note it down. You can extract 10 sentences a day and 300 sentences a month. Often review the excerpted sentences, so that consciousness increases almost unconsciously.

Regarding the habit of procrastination, I suggest that you set a time for yourself, you must complete the learning task before a certain time, give yourself a time limit, give yourself a little pressure, and mobilize your enthusiasm. When you develop good study habits, you can overcome laziness and procrastination. After you slowly enter the state, you will become patient in 
learning. I have to reflect every day. Whether I have learned new content or gained a new understanding today, I must continue to improve my awareness and accumulate little by little. The problem with many brothers is that they study irregularly. When they are not enthusiastic, they don't read rebooting articles for more than ten days. Awareness cannot be continuously improved in such fashion. Some brothers make progress every day. Although it is a small improvement, they have not stopped
making progress. They pay much attention to daily accumulation. If they persist for a period of time, their awareness will rise. Small quantitative improvements produce qualitative results, which eventually usher in a big turnaround.

4. Sitting for long periods of time and staying up late: Many brothers are rebooting, but their awareness of health preservation is very bad, which is very detrimental to the recovery of the body. Sitting for a long time can hurt the spleen and the kidneys, and staying up late is even more damaging. Staying up late and sitting for a long time are also a boiling frog-like injury, and they will waste you unknowingly. If we want our body to recover better and faster, we must pay attention to the way of health preservation and establish the awareness of health preservation. Especially weak brothers cannot afford to stay up all night. They can't afford to anymore damage. Staying up late will slow down the progress of the body's recovery. I mentioned the harm of staying up late and sitting for a long time. These two habits must be changed. In addition, maintaining good eating habits is also very important. Eat on time and rest on time. Don't eat when you think of it, don't wait until you're tired before going to bed. It's very important to maintain a regular diet and rest. Putting aside indulgence for a moment, just staying up late and sitting for a long time can cause many diseases by themselves, which are lifestyle diseases. Realize that we have to learn to change. If you sit for a long time, get up every 40 minutes and exercise, stretch the body, walk around, let the body and mind relax. Students usually have the problem of staying up all night, we should try our best to improve the efficiency of learning to avoid staying up late. Turn off wall lights at 10:30, and turn on the lamps if you don’t sleep. Don’t make noise that will affect others’ rest. It’s more difficult to stay up late at work. Many brothers I’ve talked about have to go to
night shifts, which hurts their bodies. They can only pay more attention to maintenance, strengthen diet, and avoid fatigue. I remember a brother who couldn't afford the night shift and resigned later. If you take control again but stay up late or sit for a long time, you will lose your progress quickly, which is 
equivalent to cutting a tree with three axes. The tree will fall in a short time.

It is very important to develop good rebooting habits. We should pay more attention to moral cultivation when rebooting. Brothers who reboot should be a group of qualified and educated people, a group of people who truly possess positive energy. Many brothers, especially new ones, are still narrow-minded and full of jealousy. They gloat when they see others breaking their reboot, and laugh and be sarcastic when they see others breaking their reboot. These brothers have a gloomy mentality. They don’t like to see that others are better than them. They laugh and humiliate people who are worse than them. This is actually a manifestation of inferiority and insecurity. Brothers should encourage each other, exchange experience, and motivate each other. If others quit better 
than themselves, they should be happy for them. If others quit worse than themselves, they should try their best to help each other and share their good experiences with each other. It is a gentleman'swish to hope that the other party is better than himself. A gentleman is open and upright and full of positive energy. Let us eliminate jealousy, let us be a selflessly dedicated person.

It is very important to learn traditional culture. I have studied the content of the traditional culture forum, and I have listened to a lot of related lectures. It really benefited me a lot. Traditional culture and traditional values are declining. Nowadays many young people engage in indulgence. What they compare 
with each other is food and clothing, and even compare their own experience of indulgences. In fact, they hurt themselves in the end, and because of their ignorance, they don’t know this at all. What's wrong with doing it yourself. The people around him are doing this, and he is doing the same. The environment is indulgent, and he is naturally assimilated. I have watched Wang Shuangli’s lecture in the Traditional Culture Forum many times. The title of his lecture is "Drunken Life and Dream of
the Prodigal Son Returning". Before learning traditional culture, he was able to eat, drink, prostitute and smoke. After learning traditional culture, he was completely awakened. He really changed. The traditional culture forum promotes the "Disciple 
Guidance". I have also recommended the Disciple Guidance to my brothers. It is extremely important to cultivate a correct outlook on life. Otherwise, blindly comparing materials and 
satisfying one's senses will only make one's own spirit decline. More emptiness, because desire is a bottomless pit, which can never be completely satisfied, and your indulgence is to consume kidney essence, which is the most precious substance of the human body. Many people do not have any knowledge of traditional Chinese medicine and think that eating a few eggs will be enough. They will make it up, but can it really be made up? Or will things turn symptomatic? If one could really make up for it, why did those emperors die at a young age? Do you eat better than the emperors? The best food and the best doctors are not good enough. The key is to learn to reboot and preserve essence. Many famous Chinese medicine practitioners in ancient times ordered patients to abstain from sex. Hua Tuo and Dun 
Zixian have good medical records, you can search and see for yourself. It is an absolute truth in order to be less diseased. 
After thousands of years of verification, ancestors will not deceive their children and grandchildren.

In traditional culture, filial piety is also emphasized, and filial piety is the first of all virtues, and filial piety is also emphasized in the disciples. Traditional Chinese medicine teaches that the three Yangs will promote the Tai, Activity will raise the yang, the good will raise the yang, and joy will raise the yang. And Baishan’s filial piety is the first. If you are very filial to your parents, your mood will be better. If your mood is better, your physical discomforts will also get better. Body and mind influence each other. Try not to make your parents angry. If you have to do something, you can communicate it well. If communication fails, you can remain quiet. Be filial and obedient. You must know how to be submissive and don't contradict your parents. It is not good to make your parents angry, because anger can cause illness. Pay attention to the tone of your speech, and learn to communicate well even if there is something wrong with your parents. We should also pay attentionto filial piety in rebooting. Many rebooting articles have emphasized filial piety. Filial piety belongs to positive energy. If you respect your parents and elders more, you are also increasing your positive energy. With positive energy, it is easier to succeed in rebooting.

### Time management {-}

We all have an extremely precious resource and this is the time we have. How do we make good use of time and how do we maximize efficiency in a limited time. This is a science. I have studied time management and efficiency management. In everything, you must learn to use time, manage time, and strive to improve your own efficiency. Efficiency!  This is crucial.
The purpose of rebooting is to improve the efficiency of learning rebooting articles and increase the absorption rate of rebooting articles. If you can’t read, forget it. It's no good. Many people read rebooting articles like watching a movie. The absorption rate is significantly different between watching once and watching ten times. If you read once, a lot of knowledge has 
not been absorbed. Higher consciousness is the same as long height. On the one hand, you have to eat, and on 
the other hand, you have to be able to absorb what you eat. Otherwise, if you just eat without absorbing, it will be for naught.
A brother read "Rebooting as the Best Remedy" 11 times, and it hasn't broken the reboot till now. Those who can read one article 11 times are by no means ordinary people. For good books, I will read them over and over again. Every time I read them, I gain a new harvest. If I read only once, I will miss many essential things. Regarding rebooting, you should adopt a deliberate attitude, keep understanding and comprehending, and truly master the laws and principles of rebooting. When you truly master them, 
successful rebooting will become possible. I have said in a previous article that there are indeed a group of highly talented brothers in the rebooting forum. These brothers have improved their consciousness very quickly, and you should learn more from them.

Let me share with you some points about improving time management:
**1. Strong rebooting motivation, strong motivational thoughts:** Everyone who reboots basically desires to restore health and appearance. This is a common rebooting need, and some brothers are forced to go to Liangshan because of their symptoms and have to break the reboot. The rebooting is over, and some brothers even start to reboot after they have been demolished. Some brothers have super strong motivation to reboot, and they are very strict with themselves. They have shown twelve points of enthusiasm and courage, and they are relatively long-lasting. They are very eager to learn about rebooting articles and are always hungry to learn more. My state was similar. I was too eager to learn. I was like a sponge frantically absorbing rebooting and health maintenance knowledge. I wanted to know more and understand deeply, rather than just taste it. I also have strict requirements from myself, which is to reboot thoroughly, including quitting adultery, because I have learned through Chinese medicine that adultery is also very harmful, so rebooting must be thorough. At the time, my thought was that I had to quit. I had no choice, because I couldn't afford it anymore. I had become a frequent visitor at the hospital, but I found that the hospital could not save me, only I could save myself. My way out was to destroy the boat. This was my determination and motivation to reboot. Rebooting requires a strong motivation, otherwise your potential will not come out, and you will be forced out. Many brothers have read up on many cases and have rebooted out of fear, because they don’t want to wait until they are wasted. Then it will be very difficult to recover. Fear is also a very strong motivator, because you have already seen the end. With a strong motivation to reboot, efficiency is easily achieved, because you want to keep  learning, just like a fan of online games, a state of being fully engaged, tirelessly, not getting bored, just that state. My state of study at the time was like that. Obtaining a piece of health knowledge was like a treasure, and I wrote it down immediately, for fear of forgetting it. I felt like a treasure hunter, not digging for treasures in mountains, but digging for treasures from books, digging for treasures of knowledge. Now I don’t advocate being obsessed with rebooting like that, but advocate paying attention to recuperation and finding a balance between study and health maintenance. I used to read a book a day, but now I usually take a few days, so as not to overwork and hurt my body. If you can transfer your interest and enthusiasm for watching H to rebooting, then rebooting will surely be successful. I'm afraid that if you don't quit resolutely, it will be difficult. **Do you want to reboot successfully? Think very hard about this!** From the degree of your desire and urgency for rebooting, I know the probability of your rebooting success.

**2. Take notes:** The best way to learn from rebooting articles is to take more notes. I was reading books and taking notes every day. In fact, I still read books and take notes every day, but I have shifted my focus to mainly Buddhist content. Taking notes is absorption of information. Reading is only a micro-absorption. The absorption rate of looking is very low. There are very few people who can really remember. When you pick up a pen and start to take notes, you will have a deeper understanding of the article as you are taking notes. It becomes easier to have your own thoughts and insights. Everyone has been a student at one point. I am sure every teacher emphasized the importance of taking notes. Keep taking notes, and keep reviewing the contents of the notes, reviewing the past and learning the new, and trying to memorize key sentences, so that your consciousness can be steadily improved. Taking notes and reviewing notes is the best way to improve your consciousness. The content of the notes can also be flexibly mastered, as long as you write down important sentences.

**3. Encourage warm-up exercise:** Before you start learning, you should learn to motivate yourself, you can say something to motivate yourself, or you can do a little activity to get yourself excited, so that it is easier to enter the state. Before they play, NBA players will excite themselves by listening to songs, they will shout to each other to encourage them, and then put their heart and soul into the game. When we study rebooting articles, we must also learn to find the state. Like broadcast gymnastics in school at morning time. It is actually a kind of stimulating warm-up exercise. Through proper physical exercise, the mind will quickly find the required feeling. Once the body is invigorated and active, the mind will be very fast. Enter the state, and bid farewell to the bad mental state of grogginess. Make it easier to concentrate, so that learning efficiency will be improved. What I want to remind everyone about is not to exercise too intensely. Just a little activity, don't get exhausted as this will not be conducive to learning.

**4. Study plan:** A brother once asked me to make a rebooting plan for him. Actually, I don’t have a detailed plan myself. **Plans cannot keep up with changes**. I only have a vague plan. I need to make adjustments when encountering specific situations. You have to ensure that you read one page every day, at least one page. When you are in good condition, you can read more, but
when you are in poor condition, you can not read less than one page. It is to ensure that you are learning every day without interruption. If you persist in this way for a period of time, you will really see it, and then set the number of pages to 5 pages, not less than 5 pages. Of course, you need to make notes, not just forget it after reading it. Keep reading, keep reviewing, so that your consciousness can continuously improve. Like the race between the tortoise and the hare, you are not afraid to run slowly. As long as you are running, you will improve. In the end, small habits will lead to a big result. In practice, many brothers have no plans to learn, and rely solely on enthusiasm to reboot. Once the enthusiasm fades, they are no longer interested in rebooting articles. They can no longer find the requisite motivation. The more they give up, the worse their health gets. If you can develop a habit of learning every day, there will be no embarrassment of fading enthusiasm. Continuously raising your consciousness is the kingly way of successful rebooting. You should maintain good study habits and do not rely solely on enthusiasm for rebooting. Once you have a study plan, you 
can study according to a schedule, and you won’t be exposed to the cold. Don’t speculate how long you can reboot successfully. Do a good job every day. If you do well every day, you will 
naturally receive rebooting success. Put slight pressure on yourself, but not too much pressure, too much pressure may cause loss of confidence. My study plan is to study every day, not necessarily a lot, but consistently.

**5. Complete isolation**: It's like putting yourself in jail, disconnecting the Internet, disconnecting the TV, disconnecting the phone, banning, and only giving yourself reboot articles, pen and paper. You can't do anything else, you can only do this one thing, and that is to study rebooting articles. Total isolation is 
actually to eliminate interference. In real life, there are too many distractions. This can easily affect the efficiency of learning. One reads a book for a while and then immediately plays a game on their phone. This is not quality learning, and you are unable to concentrate on one thing. What if someone orders you to read a 100-page book today and tells you can't eat or sleep until you have completed this task? You will definitely be very engaged in reading books. When you eliminate all interference, you will find that your potential is fully revealed. It turns out that you can really read 100 pages a day, even 200 or 300 pages, sometimes even an entire book. Some brothers are completely fascinated by rebooting articles and want to learn and read them eagerly. The degree of their devotion determines the speed of their progress. If you reject learning, or learn half-heartedly, progress will be slow and inefficient.

**6. Minimize rest:** 1-2 days per week can be arranged for rest during the week. Minimized rest is to maintain the continuity of learning, that is, try not to interrupt the overall flow. Look at it all in one go. If you stops, the original momentum will be weakened a lot. It's like playing basketball, if you suddenly get off the court, you may not *"be in it"* when you play again. Try to spend more time studying, save time for chatting, save time for coffee, save time for shopping, save time for playing ball, and devote more time to studying so that you can study in 8 hours one day or 10 hours, this day is specially designed for efficient learning. Just like athletes have high-intensity training days, coaches will generally arrange low-to-medium-intensity training days first. When the desired state comes about, coaches will arrange high-intensity training days, so that progress will be more apparent. 
Rebooting learning and levelling in online games are one and the same. Is putting in 8 hours a day to make progress 
faster or is devoting 1 hour a day faster? Of course, I do not recommend that you study for 8 hours a day, but you should ensure that one day of the week is a state of high-input learning.

**7. Fast forward acceleration:** Turn on the fast forward button for all activities, just like the fast forward button on videos. You can walk faster, you can eat faster, don’t chat while eating, you can brush your teeth a little faster etc. Speeding up is all about squeezing time out for learning. Don't be lazy. That way, you won't be able to enter the best learning state. With a certain sense of urgency, the energy of the whole body will be activated, and it will be easier to concentrate when doing things. In fact, this is to give yourself a little pressure. If there is no pressure, there is no motivation. When there is pressure, you can get oil. Give yourself a little pressure, so that efficiency will come out. However, everyone should be careful not to put too much pressure on yourself, it may be counterproductive.

**8. Cutting time:**  Cutting time means to divide time into segments, and then try to achieve the maximum efficiency in each period of time. For example, let's say you make blocks of 45 minutes each. Then, in each 45 minute block, you have to try and achieve the highest efficiency possible. For example, lets say you can only read 10 pages in 45 minutes. If you have time management awareness you can motivate yourself to do a little better. Therefore if you end up reading 15 pages instead, this would be an increase in efficiency. After an efficient 45 minutes, you can rest for 15 minutes, and then start the next efficient 45 minutes.

**9. Frequent review:** I have always believed that review is the mother of learning. Learn the new by reviewing the past, and each review will bring new gains. Each review reconsolidates and deepens understanding. Everyone should review their reboot notebook from time to time. Your reboot notebook is the essence of the article. You have to review the essence of rebooting knowledge and merge it with your own consciousness. It would be better if you could have your own thinking and understanding. Some brothers can’t go online every day, but don’t leave the rebooting articles. When your concentration is still low, you should take time out every day to review your rebooting notebook. I suggest to set aside at least 10 
minutes a day. Look at the reboot notebook, and then remain highly vigilant. Constant review is the best way to increase the absorption rate, and everyone must pay attention to reviewing.

**10. Learn to relax:** Teachers at school should tell their students to combine work with rest. The same is true when we study rebooting articles. There are effective days with minimal rest, but there is no need to be super effective every day. Ma Fang Nanshan is to replenish energy. Sharp, efficient days can be arranged 1-2 days a week. You can adjust yourself at other times. When you are tired, you can read less, and when you are in a good condition, you can read a few more pages, but try not to break the chain, at least read 1 page. It is important to develop good study habits.

**11. Finish as early as possible:** To complete the task as early as possible is to avoid procrastination. Many people like to procrastinate, and they only want to do a task when they can’t put it off any longer. This is a very passive approach. For example, when tasks that can be completed in the afternoon are delayed until night time and thus one stays up late. Time passes quickly and passes without our being aware of it. Therefore, we 
must hurry up. Time management divides tasks into important, unimportant, urgent, and not urgent. We must first complete urgent tasks and important tasks, take the initiative, and avoid delay. The more delay, the more passive we will get, which will eventually lead to a hasty completion, low efficiency, and even failure to complete. For the tasks that need to be completed, I just want to say four words: **Act now! Stop procrastinating, please be decisive.**

**12. Enjoy learning:** This means make things interesting. Don't treat learning as a painful and difficult thing, but treat learning as a natural thing. It is important to make learning interesting. This is true for learning rebooting articles as well. Active learners are always a hundred times better than passive 
learners. Active learners are like cows eating grass by themselves and eating happily. And passive learners want  other people to eat according their grass. If you don't read rebooting articles yourself, no one can help you. We have to learn to correct our misunderstandings. Learning is not painful. It is just the act of letting ourselves know more. Only with awareness can we overcome the demons. Every time you learn a piece of rebooting knowledge, you should feel happy and learn more. The thirst for more knowledge is good. A strong thirst for knowledge determines your speed of progress. Why do people get bored after reading rebooting articles? They think they have understood, but in fact they were just looking at the flowers. Other people read one article more than ten times, and 
each time they read it, they gain a new and deeper understanding. Which of these two kinds of people do you feel is more likely to reboot successfully? It speaks for itself.

**13. Set up a dedicated time:** Setting up a dedicated time is easy to understand. Just like regular eating times and sleeping times, it is best for us to study reboot articles regularly and at specific times. The time to study rebooting articles each day is set first, then you study hard at that time. During the dedicated time slot, try to maximize your efficiency and keep everything else aside. This period of time is exclusive to rebooting, and you should concentrate on only studying.

**14. Decompose big goals:** To complete a big goal, you should break it down into several small goals. For example, for a 600-page reboot book, you can read 10 pages a day, and you can finish it in 60 days.It is important to ensure that progress is not interrupted. If you read 20 pages a day, you can finish it in 30 days. If you read 50 pages a day, you can finish it in 12 days. It’s very important to break down big goals into small goals that can be easily accomplished every day. Many people look at the 600-page book and sigh, can you finish reading this year of the monkey? In fact, if you master the method, even a 1,000-page book can be read quickly. It's like building a house, guaranteeing the progress, and building a high-rise building on the ground. I'm afraid that if you can't guarantee progress, so you will fish for three days but hang out on the net for two of those days.

## Summary

This season I shared my knowledge of time management, and I shared my experience with you. Efficient time management is an entire domain of knowledge. Those who are interested can buy some relevant books for themselves. When you master the relevant methods your efficiency will increase several times, and the efficiency of your study and work will enable you to better organize your life.
