# Body recovery methods: moxibustion and stretching 

## Foreword: {-}

Go to a doctor and mention the problem of masturbation, the answers you are likely to get will generally fall into two categories. One is that you will be advised to masturbate regularly or masturbate moderately, and do not practice restraint. Second, would be that you are recommended to quit completely. I have seen feedback from many brothers. Among them, 3 Chinese doctors suggested that patients must give up masturbation completely, and several other doctors suggested moderate masturbation. Many doctors are actually poisoned by theory of 'moderation' with regards to masturbation. Moderate masturbation seems absolutely correct at first glance, no problem at all. But if you have seen many cases of victims and have a deep experience yourself, you will know that is not the case at all. Moderation, 
moderation, where is the degree? Some people say once a week, nothing will happen. However, some brothers do it once a week, but after three years, they break down. How do you explain this? The constitution of each body is different. Some people have a strong foundation and can endure damage for a few years. Some people are born weak and don't like sports, they will suffer from symptoms within two years. Almost every brother has thought about moderation, but when his desire comes forth, it can be described thus: **once you pop you cant stop!** Once an ejaculation occurs through mastrubation, one wants to come again, or even 2 times, or even masturbate for several days in a row. Do you think this is moderation? Do you really think you will be the one in control? Another point is that adultery is also breaking the reboot. 
Some brothers do it once a week, but they can't control adultery at all, and thus damages themselves even more, because of ignorance, because they don't know the precepts at all. *"I think I can do it in moderation."* But actually all they do is end up either masturbating or thinking about sex all day. I also mentioned in a previous article that the time to relapse is usually very consistent. When the level of yang is weak, the probability of symptoms is high. Symptoms can be caused just once.

Moderation, moderation, but the water is too deep! How many predecessors are giving a moderate effort to get rid of it completely! But some doctors still advise patients to be moderate. People who masturbate are 
basically addicted and you may not become addicted if you take drugs once, but almost all 
people who do get addicted at least once. Do think that the addiction is strong? If you learn to control adultery, then abstinence is harmless. I have talked about this issue many times in previous articles. If you can't control adultery, then practising abstinence may backfire. Because you do not reign it in after lusting, it is very likely that there will be an inflammatory reaction. If you can resolutely do it when you think about it, then there is no problem. If you believe the doctor's so-called "regular tube management" is right, then wait for the relapse and reemergence of the symptoms. This is not alarmism, this is the truth that countless predecessors have personally experienced. There is nothing new in the world of management, what you have experienced, the predecessors have experienced. So please don't take a chance and try tobe moderate. It's totally self-deception, and it's harming yourself after all!

Masturbation is evil, and it really is impossible to do it just once for the vast majority! I hope that everyone can continue to learn to improve their awareness and strengthen their ability to control desires, so that they can be
as restrained as possible after entering marriage, otherwise they will easily be wasted after marriage. I have seen a few cases of sexual indulgence after marriage, recurrence of prostatitis, impotence and premature ejaculation, and return to hospitals. Many people still masturbate after marriage. This is the *"double axe to kill the kidney"!* In the end, I really broke myself down. I've seen several brothers end up with impotence and divorces. It really is a miserable experience!

Recently, some brothers have said that since rebooting, they don't look at the *"yellow"* ones, but see the pure ones. They believe that seeing pure ones is always harmless. I remember this kind of argument mentioned by a brother a year ago. He collected a lot of *"pure"* photos, which were not yellow, but he looked at them and wanted to be crooked. Then he relapsed. As long as you face the female sex, whether seductive or innocent, it is possible to have evil thoughts. In addition, *"pure"* 's lethality is stronger, and it is more concealed. It is easy to lose vigilance, allowing the inner demon to take advantage of loopholes. Innocence is another bait of the Inner Demon. It just catches you with a 
different taste. **The Inner Demon's bait has two flavors, one is seductive and the other is pure.**

## A few Q&A cases {-}
>Big Brother Feixiang, I saw someone posting on our school’s forum a link to a pornographic picture, so I went to the thread and angrily accused the OP, but I was banned... This is really bad, brother, How should I deal with this? Moreover, a promotional post for rebooting has also been deleted, which is really depressing!.
>
**Answer:** Well, it’s normal for promotional posts to be deleted. I generally suggest one post and move on. It is common for rebooting promotions to be deleted and misunderstood. Many brothers are very experienced in promotion. After the promotional post is written, they leave instead of looking at other posts.  You got angry with the OP. I understand your emotions, but next time you have to pay attention to controlling your emotions. Some people don't wake up, so you can post
a picture to promote rebooting, and then leave. Leave them alone, just plant the seeds. In the future, if they have a physical problem, they will immediately think of your post, regret they didn't pay heed, and then they will start to reboot. Keep going! We always take the long-term view.

**Additional comment:** Promotion is about strategy. There are a lot of people doing promotional work in the forum. You can also exchange promotional experiences. Promotion generally meets two kinds of people, one is someone who is awake, and another is someone who is not awake, and misunderstands you or even scolds you. According to my observations, there are still many misconceptions, because the current environment is all about the "harmless" view, and many people have grown up under the influence of "harmlessness". Maybe they couldn't accept it at one point in time, and they couldn't think it over in great detail. Those who can transform at once are definitely those with good roots and those who have experience. Some people don't wake up until they hit rock bottom. If someone can wake a brother up when he is at rock bottom, he might do a u-turn right away. Therefore, when saving people also remember probability. When the situation is right, the probability will be high as well. If the situation is not right, don't get angry and don't start a quarrel. I have seen several brothers who went to promote but their emotions got out of control and they quarrelled with others. They ended up making themselves very angry and only harming themselves. We must avoid this. If we can save a brother, great, we will save them. If we can't save him, we plant the seeds of enlightenment for him. One day in the future, he may really repent and regret not listening to you. Some people don't wake up all at once and need to go through a process. Ten people may see your promotional content, and one of them may start rebooting. In fact, you have already succeeded. Even if ten people misunderstand you, it doesn't matter. The seeds have been planted, and will mature in the future. They will sprout and grow.

> Hello Brother Flying Eagle, do you encounter this situation: First thing in the morning you try and feel better, but the more you think about it, the more uncomfortable you feel, and you can't shift my attention at all. I don’t know what to do if I continue this way. I pay attention to my body every day. My mind is confused and can't remember anything. In addition, I especially want to stab myself when I see a knife in the kitchen. I always think about these terrible things, and I am afraid to make stupid mistakes. Why do I feel so uncomfortable? I don’t know if you have experienced this kind of thing before. It’s a very tiring 
journey. I don’t know if I should resume antidepressants. I haven’t eaten taken them for a long time.

**Answer:** When I had neurosis, I felt tired when I woke up, like I had stayed up all night. I was very sensitive at the time and was on the verge of a collapse. Traditional Chinese Medicine: **Liver and kidney deficiency, always scared.** At the time, I was in a state of fear every day, and I was in a state of anxiety 
all day long, like being chased. Death was better than life. I suggest that you don’t think about it too much. I recommend the Ziwu health pile as a regular practice, it will greatly improve the neurosis. Keep going!

**Additional comment:** Staying up late hurts the liver and kidneys, and sitting for a long time also hurts the kidneys. 
Over time, neurosis will come knocking at your door. The kidneys govern fear. The emotion of fear will in turn hurt the kidneys further, so it is very important to pay attention to 
emotional management. Once a person enters a psychological state of fear, they will be trapped in it, just like entering a maze. Ordinary people cannot understand this at all. It is generally believed that you have mental problems, which are mental illnesses. In fact, mental illnesses have a physical basis. It is very torturous. It's hard for ordinary people to imagine. They can't 
imagine having to live with that all day long. One thinks about bad things and about the worst results. One lives in fear and despair every day. In this state of mind, they want to commit suicide. There were a lot of people, and I also had suicidal thoughts at that time, but fortunately, I didn’t go through with them. The mental state of neurotic patients is not imaginable by ordinary people. Doctors also have little knowledge and even misunderstand patients. Only people who have experienced it can truly understand it.

If you go to a doctor and take western medicine, it will not be cured at all. Your symptoms may be relieved at first, but it will get more painful as you take more medicine until you eventually rely on it completely. In my case, I insisted on rebooting and keeping good health. It took a long time to get out of that vicious psychological circle, because I knew that liver and kidney deficiency were the root cause of the fear. The body and mind influence each other. **After the body is adjusted, the mind will also improve.** If you only focus on the psychological, you may not get out of it for the rest of your life. Some people are full of kidney qi and courage, and they are full of vigor wherever they go. When they get older, you will find that their aura is completely gone. On the one hand, it is the decline caused by age, on the other hand, it is the indulgence that hurts the liver and kidneys, and they no longer have the original essence, as it has wilted. The healing process of sperm injury patients is cyclical. After some brothers quit, their symptoms are relieved compared to the past, but they often return. At this time, it is necessary to stick to rebooting and health maintenance, and 
work hard on health maintenance, so that the number of repetitions gradually decreases and then stabilizes, thereby gradually healing. The recurring period of symptoms is normal, and there is no need to worry. Just stick to the precepts, and look after all aspects of your health.

> I feel that whenever I get desire I should just vent through push ups. Is this the correct approach?
>

**Additional comment:** I have seen this kind of argument many times before. This reminds me of the West Point Military Academy, they immediately get down and do push-ups whenever they make a mistake. Doing push-ups is strength training and requires explosive power. When the body is weak, pay attention to resting and avoid using explosive force. Zhao Benshan suffered a stroke while doing push-ups. Don't force yourself when your body is weak, you must pay attention to rest. If you are in good health, you can do some push-ups appropriately, whether desire appears or not. This approach is okay when at home, but if you are in school or on the 
road, this becomes problematic. You can't be on the road, have a desire appear and then do push-ups right away. Similarly you can't get up during class, fall down and start doing push-ups. I think it is more reliable to memorize the mantra for desire elimination mentioned in previous articles. It is not limited by time and space, and it is easier to implement. I used to want to vent my desires by doing push-ups. That was my idea when I was in high school. At the time, I was relatively ignorant and naive, and no one guided me. Hence when I was weak, I did a lot of push-ups. The next day my submandibular gland became inflamed and immediately swole up. I ended up going to the hospital. They couldn't find the cause, and it was not until 2 years later that I found out that the submandibular glands were swollen . Therefore, in the state of physical weakness, we must be careful in doing explosive training, otherwise it is likely to cause illness. 
Remember! Traditional Chinese medicine talks about excessive exertion, which can damage the kidneys. You don't feel it at a young age. If you use explosive force when you are older or weak, it will easily lead to the occurrence of diseases.

> I want to ask a question: I had been abstaining for nearly 70 days when I relapsed. Why do I feel that my body feels more smooth and comfortable?

**Answer:** This means that your body is recovering well. Spermatorrhea hurts your body and your kidneys.  You are recovering well, but remember there is a delay between symptoms emerging and the actual time of injury. You may feel unwell after a few days. Keep going!

**Additional comment:** I experienced the phenomenon of delayed injury myself very early on. I remember when I was a teenager, I felt fine, the day after masturbation, and I would feel okay for the next two weeks as well, but the bad results appeared in the third week. The portion of your body that houses the kidneys would beat fiercely. Some brothers call it "kidney beating." It is a very strange feeling. It is as if the kidneys are beating like a heart, and it is accompanied by swelling. You may even feel pain in severe cases. This is actually the phenomenon of delayed injury. The human body has a cycle. **When you damage yourself at the beginning of a cycle, the evil effects may only appear at the end of the cycle.** If you damage yourself in spring, your winter may be very bad, for example. I remember a brother who went to see a Chinese medicine doctor, he looked very strong on the outside, but the doctor said his pulse exposed that his body was weakened. Don’t look at strong appearances, it’s all an expression of youth. Obviously, he was already feeling unwell, otherwise he would not have gone to the Chinese medicine doctor. Indulgence in youth becomes obvious after middle age as the body starts to collapse. The reality is that many people suffer from symptoms when they are young. 20-year-olds have pulses of 40 or 
even 60 year olds, and they have severe premature aging. Their bodies are completely wasted. **If you feel okay after you masturbate, I advise you not get happy too early, because there is a phenomenon of injury delay** in the trauma world, which is more common in many fields, such as fitness. Many people have had an experience where they didn’t feel much soreness on the day of exercise, but their whole body became sore the next day, even having to support themselves with the wall when they walked. **In the field of fitness, this is called delayed muscle soreness**. Therefore, people who indulge in lust, don't be happy too early, there is a saying: **Settle the accounts after the autumn.** Don't be too happy at the time!

> Flying brother I ask for help! I have frequent spermatorrhea, once every two or three days! Let me tell you a bit about my situation: I have been masturbating for ten years, and now my condition is very serious, premature ejaculation, lack of energy, frequent urination, yellow hair, but no hair loss, and an inability to focus my vision. In March this year, I went to the hospital for treatment. The doctor said that I had prostatitis, my foreskin was too long, and my glans was too sensitive, so I had prostate detoxification, cut the foreskin and had dorsal nerve surgery! A total of more than 10,000! 
Unfortunately, it didn't work! I went to see a Chinese medicine doctor again, and he said that I have kidney deficiency and prescribed me some medicine. However I have seen no effect after having taken it!

**Additional comment:** If you go to a men's hospital they won't let you go until they have squeezed you out of at least a few thousand. Go to a regular hospital to check for prostatitis, it will only cost a few hundred yuan. At the male hospital, they treat the patient like a cash machine, it is a scam operation, but since the money is in your pocket, and they can't steal from you in broad daylight, it becomes necessary to do some advanced analysis or surgery, so that you fork over whatever is in your pocket. In the past, a brother paid 10,000 for therapy which usually costs 2,000, and on top of that he didn't even get any better! Don't you think that's robbery? Then there is also surgery. The most common one is dorsal nerve surgery. This operation is very problematic. Many brothers have reported that they have performed this operation. Not only did it not improve their sexual function, they ended up experiencing complete impotence! Therefore this surgery should be approached with caution, otherwise you will probably regret it in the future. Patients walk into an andrology hospital, like lambs to 
the slaughter. These patients are also relatively ignorant and completely trust the doctor's words. The media has exposed some male hospitals. Even if you are not sick, you will be treated 
as serious case. If you are sick, you will be considered very serious. Even if there is nothing wrong with you, you will be pushed to get on the operating table. Why do these doctors with no medical ethics want to do this? For money. The wool comes from the sheep. The doctor asks you to perform instrumental treatment and even surgery. He gets a commission. If one gets cured then there is no blame. But in reality almost all patients are not cured at all. 

Do you know why men's hospitals are opened all over the country? The indulgence crowd is the foundation, and the *"harmless"* theory is the catalyst. Andrology hospitals absolutely support the harmless theory, and the harmless theory is their free advertising. As we all know, prostatitis and sexual dysfunction are the bulk of the income of male hospitals. And masturbation can cause prostatitis, masturbation is also very harmful to sexual function, but they say it is harmless, why? I 
can only say that many patients have been deceived and believe in harmlessness. These patients are also relatively ignorant, thinking that the symptoms of injury to the sperm can be cured. In fact they can be cured, but only through 30% treatment and 70% health maintenance. A brother I know was devastated by prostatitis for decades, treated countless times, and took many detours. Finally, he realized a truth: **Prostatitis is can be cured**. Treatment can only temporarily relieve symptoms, and it is very easy to relapse with only one masturbation session. Many patients don't understand this principle at all, and treat prostatitis like a cold, thinking that it can be cured by taking a few pills. In fact, this is a very ignorant idea. Rebooting and 
maintaining vitality and health are the major prerequisites for healing. Without this prerequisite, without this foundation, no matter how effective the treatment, it is like building a house on sand, it will fall apart. Still the same sentence: **To heal, understand first! If you don't understand the truth and blindly treat it, you will only lose money and people!** I remember a brother who was working abroad. His family thought he made good money. In actuality, all the money he earned was sent to
the men’s hospital, and he didn’t know how to reboot and keep in good health. In the end, he was left empty. It is common to spend a few thousand, and it is also common to spend tens of thousands. Some time ago, a brother who had spent 100,000 was still not cured and was not optimistic about his prospects either. Do you think this is wrong?

> Flying brother, thank you so much! I saw your tree therapy post last night and found it very interesting, so I tried it this afternoon. The result can only be described as a miracle! After coming back inside, I suddenly found my face smooth! Like a child's! I asked my mother and she too felt that there had been a change. Nature is indeed very powerful!

**Additional comment:** Tree therapy improves appearance and complexion, but this therapy also requires that one be a good match with trees. Many brothers are unwilling to do tree therapy, and some brothers can't stick to it, but I believe that there will definitely be some brothers who will stick to it, and these brothers are more predestined to do tree therapy. Tree therapy can improve not only your appearance and complexion, but also your psychological condition. If you are impatient, you will be able to calm down immediately and your mind will become very relaxed and close to nature. It can give you a peaceful and calm state of mind. I hope that you will actively do tree therapy, which will accelerate the recovery of your appearance and complexion, and also promote good mental health.

> Teacher Feixiang, I had dreams this morning. I initially woke up having had no dreams. Then I went to the bathroom. Afterwards, I went back to bed and slept and that's when the dreams came. I don't know what's going on? I dare not go to bed a second time, I have deeply reflected on it.

**Answer:** After urinating, the fine pass may become loose. It is recommended that you do more kidney strengthening exercises, so as to avoid this kind of situation in the future. Keep going!

**Comment:** The TCM intercourse regimen specifically mentioned: 

> "Exhaustion of energy after urination, at this time the same intercourse conception, the meridians are obstructed, at this time the conception, the child born is prone to congenital deficiency and incompleteness." 

So, generally after fresh urination, it is not recommended to have intercourse, also after urination, the essence is very easily lost, it is easy to have nocturnal emission. The problem of nocturnal emission after urination has been reported by several brothers. If a person's semen is not stable, only one urination will cause looseness, and a nocturnal emission will occur.
If a person's Jingguan is still strong, a single urination will not cause much impact, and there will be no spermatorrhea. In general, the situation of spermatorrhea after urination can be avoided by doing more kidney strengthening exercises. Some brothers also asked me why they had continuous nocturnal 
emissions, up to 3 consecutive days in some cases. Generally, after the first nocturnal emission, the ability to "fix" the semen has been injured, i.e. the essence level has been loosened, and it is very easy to have continuous emission after this happens. The phenomenon of spermatorrhea is analogous to the faucet that cannot be closed tightly. Therefore after the first spermatorrhea, you must be extra vigilant and careful, and kidney strengthening exercises should be prioritised. Additionally, one's sleeping posture should be the auspicious pose, and other factors that 
cause spermatorrhea should also be avoided. Continuous spermatorrhea is too harmful to the body, so we must try to avoid such situations. Controlling the frequency of spermatorrhea is a major prerequisite for complete physical recovery. This level must be passed. Controlling spermatorrhea is also a matter of knowledge. You should learn more, analyze reasons, and sum up experience and lessons, so as to control the frequency of spermatorrhea. 

### Further Notes {-}
Some brothers think that knowledge of TCM regimens is good, so they only read up on TCM regimens, and in so doing ignore other rebooting articles. In actuality, knowledge of TCM health 
preservation is only part of our total rebooting knowledge. We still have to walk the path of professional rebooting. I have spoken about several brothers who study TCM, and yet have relapsed. They learn TCM theories every day and know the harm that is done by masturbation. There are more knowledgeable than others, but still can't exercise control when the urges come up. Knowing about Chinese medicine is very beneficial to 
rebooting, because it allows you to get answers to many questions, and it can also improve your awareness of health preservation. However, it is far from enough to rely on knowledge of Chinese medicine alone. We must learn more about the principles and laws of rebooting. Understand the rules of abstinence, understand all aspects of rebooting, and various details, such as emotional management, types of abstinence, ways of controlling survivors, periods of dormancy of desire, periods of recurrence of symptoms, peak periods of abstinence, Obscenity control, psychological adjustment after relapse, psychological adjustment during the tired period of rebooting, etc. We must have a comprehensive and profound understanding of the various phenomena during rebooting. We must reboot professionally and systematically to raise our 
comprehensive consciousness. In this way, the possibility of successful rebooting will be higher. **Know thyself and be ever-victorious!** I have been following the path of professional rebooting, studying the principles and laws of rebooting, and thoroughly clarifying these principles and laws, and the success of rebooting is no longer out of reach.

I don't want anyone to look up to me or admire me. I am equal to everyone else, but the level of awareness is higher in my case. Through continuous learning and comprehension, everyone 
can reach the same level of consciousness as me, and even surpass me. I view rebooting as the **"the ladder of enlightenment"**. I am willing to be a ladder for others. I hope everyone can improve their enlightenment through my experience. I hope that everyone can quit and reboot better.
I hope that successful old brothers share more of their experiences with newcomers and bring in more newcomers. There are many misconceptions in the thinking of newcomers, many of which are still blindly damaging their bodies and have not yet started rebooting. Therefore the guidance of our more experienced brothers is extremely critical. I am a volunteer of the reboot forum. Pureness, selflessness, humility, and dedication are the code of conduct that I abide by. I don't want to be high, and I don't want to feel powerful. I will always remain humble, because I think humility is the greatest virtue. Not for fame or fortune, just to help more people. Your happiness is my happiness, and I am willing to share your pain with you. I hope 
you can get out of the swamp and restore the pure aura of sunshine as soon as possible.

Some brothers may not believe that there are selfless people in this world, because all they see are fights for fame and/or fortune, and these values advocate competition and hedonism. I didn't believe in the existence of selfless people in this world either, and I thought even if they did exist, I can not understand why they would be like that. Later, I came into Buddhism, and I fully understood it. My current ideal is to be a selfless and dedicated person and help others as much as I can. All good things are done, no evil is done, and **saving others means saving oneself.**

## Main Topic

In this season, I will share with you my experience of moxibustion and of stretching the muscles of the body for recovery. The details are as follows:

When I was neurotic, I took medicine until I despaired, because the medicine could not save me. I took a medicine, and would eventually become drug-resistant. Then I would change to another medicine. Western medicine has good effects on the body but many side effects and is not suitable for long-term consumption. Traditional Chinese medicine is good, but the effect is slower. Later, I completely stopped the medication. Now there is still a box of expired medicine at home that I haven't finished. I don't throw it away, to remind myself that I used to live in symptom hell every day. The feeling was horrible, it was definitely a breakdown!

Since I have stopped taking the drugs, I have lost confidence in hospitals and doctors. It’s not that I think it’s not good to see a doctor and take medicine. It’s just that I’ve seen many doctors and they were unable to recover me. I think I can only rely on myself, even if you meet a national treasure. You can pursue Chinese medicine, but you still have to rely on yourself. 30% treatment, 70% health maintenance. It is not enough to rely entirely on doctors. For example, if you take Chinese medicine and then masturbate, you will not heal, and it will be easy to relapse. I talked about a lot of neurotic patients that I met at the time who had been taking medicine for a period of time. Their symptoms were relieved to a significant degree, but then after indulgence they relapsed immediately. The foundation for the recovery from neurosis are rebooting and health preservation. Without this foundation, it is really difficult to heal. Even if one is temporarily cured, upon indulgence, you will get the symptoms again. It will also be very easy to relapse. At that time, I started a health regimen, I practiced many health regimens. Among these, I tried moxibustion therapy. Moxibustion therapy played a significant role in the recovery of my body. I will now speak with you about my experience with moxibustion, and I hope it will give you some enlightenment and help you out.

My encounter with moxibustion was a very organic process, because at the time I was already studying Chinese medicine and had a certain understanding of acupuncture points. For example, "I stay for three miles in the belly, ask for the lower back, look for missing items, and reap the benefits of my face." I started trying moxibustion therapy at the time, with almost zero experience, 
so I read a few articles and saw a few moxibustion videos, and then I started to do it myself. I would then go on to learn more about moxibustion articles while practicing at the same time.

The first acupoint I used for moxibustion at the time was the large acupuncture point Zusanli. 

Zusanli is one of the main acupoints in the "Fooyangming Stomach Meridian". It is a large acupoint that strengthens the body and mind. Traditional Chinese medicine believes that massaging the Zusanli point can regulate the body’s immunity, enhance disease resistance, regulate the spleen and stomach, 
invigorate the middle and nourish qi, and relieve the body. It has the function of activating collaterals, dredging wind and dampness, strengthening the body and eliminating evil. It is popular among the folks that “the Zusanli is often pressed to better eat the old hen.” This is because stimulating the Zusanli acupoint can promote the spleen and stomach and the biochemical qi and blood of the whole body. Frequent stimulation of Zusanli can invigorate qi and blood, and nourish 
the kidney. The function of a fine and strong body can make people's skin white and tender and rich in blood. Because I didn’t understand it, I chose direct moxibustion. If it is not done well, it can easily lead to foaming. Almost everyone who uses moxibustion has the experience of blistering. There is also a 
possibility of burns. Therefore, try not to choose facial moxibustion, because it may leave scars if not properly carried out. I usually choose the legs, abdomen and back. Later on, I rarely used moxibustion directly, but choose moxibustion box, which is gentle moxibustion. In fact, the effect of direct moxibustion is also very good. There is a small technique to avoid blistering, that is, doing moxibustion for about ten seconds and then rubbing it with the side of the little finger, so that the heat is evenly distributed thereby avoiding blistering. Keep rubbing during moxibustion. The effect of mild moxibustion is also very good, but there may still be blistering. Don't be afraid of blistering. Use water and let it go. After a few days, the scabs will gradually heal. I have had blisters at least a few dozen times now, and I have blistered more than a dozen times in three sessions alone. Later, as I got more experience, the blistering became less.

**About the benefits of moxibustion (excerpt):**

> Moxibustion is an ancient Chinese medicine method with a long history. Mencius once stated that "Seven years of disease should be treated by three years of moxibustion". Moxibustion is the practice of burning moxa sticks on acupoints or specific parts of the body for fumigation. Moxa heat stimulates warming and 
clearing of the meridians, promoting blood circulation and removing blood stasis, dispelling blood stasis, preventing disease, unblocking qi and blood, and strengthening the body. 
Moxibustion can adjust the functions of the viscera and promote the body's metabolism. At the same time, moxibustion can enhance human immunity, enhance the functions of red blood cells andwhite blood cells, as well as the phagocytic ability of phagocytes, and enhance human functions. A large number of research studies show that moxibustion mainly uses acupoint moxibustion to promote and regulate the body's immune, blood circulation, nerve, endocrine, respiratory, digestive, and reproductive systems.

Dou Cai, a well-known medical scientist in the Song Dynasty, described himself as the third generation of Bianque. His medical book "Bianque Heart Book" advocated health preservation and 
treatment of diseases, which is Fuyang. He believed that since ancient times, Fuyang has three methods: the first is burning moxa, the second is pill, and the third is aconite. Burning moxa is 
moxibustion. "Yellow Emperor's Internal Classic" said: "If the sun is in harmony with the sun, if the sun loses its place, the life will be lost." Yang qi has the effect of warming the internal organs and nourishing the bones and muscles, just like the sun shines on all things. Plants can photosynthesize and thrive. Yang Qi is the energy necessary to maintain the normal metabolism of human life. Yang Qi in a person's life is a process of changing from weak to strong and then gradually attenuating and
depleting. The body is healthy if the yang qi is foot, the body is weak if the yang qi is weak, and the body is killed if the yang qi is exhausted. Therefore, Yang Qi determines people's health and life.

What is Yang Qi? Yang Qi is actually the energy that each of us needs to survive. Regardless of our age, we are losing energy every day. The lack of energy makes the body occupy a sub-healthy state. Especially in the stressful lives of modern people. If we want to replenish Yang Qi, the best and most natural method is to use moxibustion. Because wormwood is a pure yang plant, it is known as the king of herbs. Moxibustion has a special nature of pure yang, which can quickly enhance the body's yang qi, strengthen the body and eliminate evil, 
activate and improve the function of the immune system, promote metabolism, strengthen internal and external communication, enhance the body's stress ability, and improve digestion, circulation, and excretion. When the yang qi is full, the qi and blood will be full, the functions of the viscera and meridian will be normal, and the body's defense ability 
will be strengthened. As the "Inner Classics" says, "the righteous qi is stored, evil cannot be done, and the evil is combined, the qi must be empty". It seems that a strong house has no gaps, so 
no matter how heavy the wind and rain are, it is not afraid. Therefore, Aizhi can play a role in disease prevention and regulation, health care, and anti-aging, and can make people healthy and longevity.

### My moxibustion experience {-} 

Moxibustion cured my rhinitis and hemorrhoids, and improved my digestive function. These three effects are very obvious and were immediate. Moxibustion feels obvious within a few days. I turned out to have allergic rhinitis. I did have 3 surgeries, but it became more serious after masturbation. Often my nose was not ventilated and my resistance was extremely low. Later, after moxibustion, I was basically ventilated for a year, and my
nose was rarely blocked. Even if it was blocked by the external cold, the moxibustion immediately returned it to normal. **Therefore, for brothers who are troubled by rhinitis, I suggest you try moxibustion at Zusanli and Hegu points.** I also had laser and hormone spray treatments for rhinitis at that time, but their effect was not good, and they couldn't keep up with the magical effect of moxibustion. Regarding moxibustion, I recommend you to read Aunt Shan Guimin's 39 blog and 
book "Moxibustion to Eliminate All Diseases", as well as her lecture video. Many chronic diseases that have not been cured for a long time have achieved very good effects through moxibustion. 
Moxibustion therapy is a therapy worth trying for chronic patients. During the healing process of hemorrhoids, I first soaked my feet with moxa leaf for three days, and then the hemorrhoids became swollen and I couldn’t sit down, just like a soy bean. From the fourth day on, I did moxibustion at 
Shenque acupoint and moxibustion 2 God, the hemorrhoids fell off, and since then, hemorrhoids have completely healed, and I have never suffered from them again. Aunt Shan Guimin also talked about the moxibustion case of hemorrhoids, but she recommended direct moxibustion of hemorrhoids, which is a little bit painful and requires a certain endurance. In the end, the 
hemorrhoids fell off and then healed. Regarding the improvement of digestive function, I used to have unformed stools for about 2 years, and diarrhea was also commonplace. Later, I also improveda lot by moxibustion at Zusanli. At the beginning of moxibustion, there was an excretion reaction. 
Diarrhea continued for 3 days. After all of them were drained, the stool began to form, and the gastrointestinal absorption capacity also improved a lot. Here I have to give credit to the moxibustion therapy, because I have been to the hospital many times just to get the stomach and intestines checked out. I 
have done colonoscopy and gastroscopy. It would just show inflammation, but the symptoms were very obvious. The effect of taking a lot of medicine is not good. Finally, it was greatly improved through moxibustion therapy.

**Adverse reactions:** In the process of moxibustion, most patients will have various uncomfortable reactions. Such as chills, cold sweats, odor, spitting and salivation, abdominal pain, diarrhea, etc. 
Even symptoms that were experienced many years ago will appear repeatedly. Because these uncomfortable reactions are related to the patient's condition, we call these uncomfortable 
reactions collectively _"excretion reactions"_. These "disease-removal" reactions are the result of the struggle between good and evil. Because the formation and development of the disease is a struggle between the righteous and evil, and the righteous qi is overcome by the evil, many uncomfortable reactions occur collectively during the onset of a disease. The patient, when he 
receives moxibustion, and the "Yuanyang" attacks the evil in his body, the disease in the "viscera meridian Evils" are expelled, and the process of expelling pathogens is a disease-removing reaction. Therefore, the disease elimination response in the treatment process is a prelude and a sign of the treatment effect. 
Generally, the stronger the disease-removal response, the more significant the treatment effect will be.

3. **Whether moxibustion can be used for yin deficiency:** Some people will say that using moxibustion to treat yin deficiency is equivalent to adding wood to the fire. In fact, regardless of yin or yang deficiency, moxibustion can improve the body and can treat all kinds of deficiency. 
Moxibustion has the dual regulating effect of preventing and curing diseases. The "Lingshu Jing" has a clear record of the treatment scope and principles of moxibustion: "Acupuncture is not used, moxibustion is suitable; both yin and yang are deficient, and the fire is self-defeating. When the meridian is sinking, the fire will take it; the meridian is firm, and the fire will cure it, and the sinking will be moxibustion. The meridian is full of collaterals, puncturing yin and moxibusting the yang. Our ancestors used this method to treat people with yin and yang deficiency.

4. **The choice of moxa sticks:** When I started moxibustion I bought a lot of moxa sticks. Some moxa sticks are very good, with pure taste, few impurities, and are very delicate. Some moxa sticks are very poor and have a lot of impurities. Generally, **Chen Ai** is better for moxa sticks, which are aged moxa sticks. There are one-year-old, two-year-old, three-year-old, and five-year-old. Of course, the merchants may falsely advertise Chen Ai, because Chen Ai's firepower is mild, not dry, and has better penetration, while Xin Ai is more aggressive, and the firepower is very strong, but the effect is not as good as Chen Ai. Buy a few more moxa sticks, and then learn more about moxa sticks, and gradually you will understand the difference between good and bad moxa sticks. The moxa sticks and moxibustion appliances I use are all bought on Taobao, and I have bought many of them. Once you have more experience and make comparisons, you will be able to tell the quality of the moxa sticks. When we do moxibustion, we should try to buy high-quality moxa sticks to ensure the efficacy.

5. **Smoke control:** Moxibustion therapy is very good, but there are 2 main disadvantages. One is that it is easy to get blisters, and the other is the problem of the smoke. The blistering phenomenon has been mentioned above. Many people are not comfortable with moxa and may find it harmful. Regarding moxa smoke, I have also specifically investigated that moxa smoke is toxic to a certain extent, and it is identified as slightly toxic. But moxa smoke also has medicinal properties and curative effects, because there are many sterilizing substances in it. If you inhale moxa smoke, a cold can be cured immediately, and your resistance levels will immediately rise. In the past, hospital wards were also disinfected with moxa smoke. My advice is, it’s okay to inhale a small amount but don’t inhale too much. Inhaling too much may also cause physical discomfort. If you don’t like moxibustion, you can choose outdoor moxibustion or moxibustion on the balcony

6. **Excessive moxibustion:** Many people feel the effect of moxibustion as magical when they first try it. Then they wish to do moxibustion every day, wishing that they could live 
to 120 years old through moxibustion. In fact, this kind of thinking is also wrong. Excessive moxibustion can easily cause physical discomfort, such as inability to beat the spirit and physical weakness. If you have a chronic disease, you can try moxibustion every day in the beginning, but when you are mostly cured, you don't need to do moxibustion every day, just do general health moxibustion regularly. Moxibustion is not only a treatment method, but also a health care method. There are moxibustion rooms in many Chinese hospitals, and many cities now have moxibustion health centers, but they are too expensive and not suitable for ordinary consumer groups. It is better to buy moxa by yourself and do moxibustion at home. I also made the mistake of excessive moxibustion when I first started. Later I found out that moxibustion every day was not as effective as moxibustion at intervals. After I got a feeling for the pattern, I stopped moxibustion every day and changed to 
moxibustion once a week or every few weeks. I am doing health moxibustion now. Iusually only use a few acupoints, such as Zusanli, Hegu, Shenshu, etc. I have tried many acupuncture points on my feet, hands, chest and abdomen. I probably tried dozens of acupuncture points, but later decided on these three acupoints as regular moxibustion points. It feels good to do health moxibustion.

7. **Improper moxibustion causes nocturnal emission:** Moxibustion on certain acupoints may cause nocturnal emissions. This is rarely mentioned in many moxibustion articles. After all, some of the articles are written by women and they have no experience in this area. My personal experience is that 
moxibustion at the Yongquan acupoint and the acupoints on the inner side of the calf can easily lead to nocturnal emission. You should avoid moxibustion at the sensitive acupoints at night. You 
should pay special attention to this.

8. **Moxibustion taboos:** Moxibustion is good, but there are also many taboos. You should also learn more about them and avoid blind sessions.

>Taboo 1: Do not directly do moxibustion on any exposed parts, such as the face, neck, arms, etc., to prevent scar formation.

>Taboo 2: Do not apply moxibustion on areas where the skin is thin, or where there are few muscles. The joints should also not be exposed to moxibustion directly. In addition, do not do moxibustion on large blood vessels and the heart, and do not do moxibustion on the eyeballs.

>Taboo 3: Do not wash your hands or bathe with cold water for at least half an hour after moxibustion. After moxibustion, drink a large amount of warm water (never drink cold or ice water) to help expel toxins from the body.

>Taboo 4: Pay attention when applying moxibustion, don't do moxibustion in a distracting environment, lest the moxa stick move and it is not on acupoints.

>Taboo 5: Pay attention to the accuracy of the acupoints and maintain a comfortable moxibustion posture to ensure the effect of moxibustion.

>Taboo 6: When applying moxibustion pay attention to prevent falling fire. After moxibustion, put moxa sticks into a bottle with a slightly larger diameter to facilitate extinguishing.

>Taboo 7: Because part of the body surface is exposed when applying moxibustion, keep warm in winter to avoid curing old diseases and adding new ones.

>Taboo 8: It is necessary to proceed slowly. When using moxibustion for the first time, pay attention to the amount. First, use small doses, then gradually increase the dose. Do not use large doses at the beginning.

>Taboo 9: For people with dull skin or children, you can place your index finger and middle finger on both sides of the moxibustion site to sense the temperature of the moxibustion site, so as not to burn the skin.

>Taboo 10: Do not do moxibustion in conditions of extreme fatigue, hunger, oversatisfaction, drunkenness, sweating, emotional instability, having infectious diseases, high fever, coma, convulsions, or extreme exhaustion, low self-control etc. Mental patients should avoid moxibustion.

**Aiye foot bath:** This is actually a pedicure. Aiye foot bath is very cheap. You can buy a few large bags for ten yuan, and you can soak for a whole year. There are more than 60 acupuncture 
points on human feet. Aiye foot bath has a certain therapeutic effect and can also effectively improve physical fitness. At that time, I not only took Aiye foot baths, but also bought a foot 
massager and put it in a wooden barrel. Soaking your feet can also massage and stimulate acupuncture points on the soles of your feet. However, if you soak your feet in Mugwort, you 
should not soak your feet too much. If you sweat too much, you will lose your essence. You must pay attention to controlling water temperature and try to avoid sweating. If you sweat continuously, you will easily become weak and collapse. Soak your feet 1-2 times a week.

**Summary:** This season I shared my experience of moxibustion. I hope my fellow brothers will try it. Of course, don’t try it blindly. You should do some research first. After having read relevant books and seen some lecture videos you will have a some understanding. Moxibustion therapy can achieve miraculous effects if used well. Many chronic diseases, 
especially those that have not healed for a long time, can be greatly improved by moxibustion. Moxibustion therapy can also improve sperm quality and treat infertility. In this regard, there are also many feedback cases. You can read more of Shan Guimin’s 39 blog to increase your knowledge of moxibustion.

Let's now talk about the experience of pulling down the tendons

It is said that "if muscles grow by one inch, life will be extended by ten years". People shrink when they get older.

So what is the specific principle of lajin?

First of all, the direction of the Twelve Tendon Meridians is the same as the Twelve Meridians, so the meridians at the contraction of the tendons will not work. During the stretching process, there will be pain in the crotch, inner thigh, popliteal fossa, etc., indicating that the muscles in these areas 
shrink, and the corresponding meridians are not smooth. Stretching the tendons softens the tendons 
and resets the misalignment of the spine. As a result, "the bones are normal and the tendons are soft, and the blood flows spontaneously." The pain, numbness, and swelling of the waist, knees, limbs and all over the body are eliminated and slowed down.

Secondly, Lajin can open up the Du Channel and bladder meridian on the back, which is of great significance to health, because the Du Channel is the meeting of all yangs and the channel of vitality. The passage of this pulse can strengthen the kidney function, and the kidney is the innate essence and qi. The source, people's energy and sexual abilities all depend on the strong kidney function. The Governor Vessel is on the spine, and the spinal cord is directly connected to the brain, so the spine is inextricably linked with brain diseases. The Ren Du Meridian is a cyclical circle on the human body, and the Ren Du Meridian, which must be opened up by various exercises, is the meaning of this. The bladder meridian is the body's largest detoxification system and an important barrier against wind and cold. When  the bladder meridian is unobstructed, the wind and cold are resisted well and the internal toxins are discharged easily. Obesity, constipation, acne, stains and other symptoms are naturally eliminated and alleviated. The bladder meridian is 
where the Shu points of the zang-fu organs are located, that is, every acupuncture point on the bladder meridian on both sides of the spine with the same name as the zang-fu organs. Unblocking the bladder meridian is naturally beneficial to all the zang-fu organs.

Third, Lajin can improve the three meridians of the liver, spleen and kidney on the inner thigh. Lajin is both treatment and diagnosis. For example, when the knee is in pain and not straightening when pulling the tendons, there must be muscular contraction. Muscle contraction firstly shows that the liver meridian is not functioning smoothly, because the liver is responsible for the tendons, and the spleen and stomach will not be in good condition either because the liver is the wood, and the spleen is the soil. Mu Ketu. Pain in the crotch and popliteal (back of the knee) indicates that the bladder is blocked and there is a problem with the waist. The bladder and the kidney are the outer and inner sides of each other, and they share water. Anyone with a poor bladder will not have a smooth kidney meridian. Edema, obesity, frequent urination, diabetes, etc. are all related to this. After lying down, the raised arm cannot be 
attached to the surface of the stool, which indicates that there is frozen shoulder. Some people lie down on a lajin stool, the raised leg cannot be straightened, and the fallen leg cannot fall in the air, indicating that the muscle contraction is serious, not only does one have low back pain, but may also have many internal organ problems. The process from life to death is a process from soft to hard. Babies have the smoothest qi and blood, so they are the softest. Lao Tzu uses the term baby to describe softness. When people grow up, their qi and blood gradually become poor and their  body gradually hardens. When a person dies, he becomes a zombie.

Lajin is indeed effective in improving health. I have learned a lot about lajin, but I didn't know enough about it at the time. At that time, there was no lajin stool, so I did positive leg presses at home, and the effect was ok, but not very significant. Later, I started to practice single-disc, and I really found that the effect of lajin was not in vain. Since I did moxibustion, my digestive function has improved a lot, and stool can basically be formed, but it is still not stable enough, but after practicing single-disc, digestive function got better. After the effect was obtained,
I persisted with the single set. At first, it was painful enough, and it was a painful and difficult process, but after gradually adapting, it became more and more comfortable, the physique also improved a lot, the endocrine was adjusted, and the skin texture also improved.

For lajin, there are usually lajin stools, which cost a few hundred yuan each. Those who are unqualified can also choose to lean against the door frame to pull the ribs. I only do single-pan and 
single-pan warm-up exercises. I don’t do leg-up stretches, because that’s a little troublesome. Of course, some people like that kind of stretch, depending on personal preferences and feelings. Lajin is not just a posture with one leg facing up. Know more about yourself, choosing the posture that suits you is the best.

Summary: I have no objection to seeking medical treatment. If you are sick, you should actively seek out professional medical advice. I generally recommend Chinese medicine for conditioning, but it is hard to find good Chinese medicine practitioners. If you have mild symptoms, you don’t have to seek medical treatment.
If you insist on rebooting and keeping in good health, you will hopefully heal. The reason why I gave up going to the doctor and  taking medicine was because I had seen many doctors and took a lot of medicine. I was disappointed in the results, and lost confidence, so I turned to health maintenance methods. I had to rely on myself. I realized that any hope of recovery lay in my own hands. 30% treatment, 70% health preservation. Rebooting 
and health preservation are the foundation for healing. Otherwise, eating and at the same time leaking has no merit. I do moxibustion, I stand up, I stretch muscles, but I am actually treating myself. It is said that this is a method of *health maintenance*, but it is actually a *treatment* method. To a certain 
extent, it is even better than taking medicine. I am a strong example of this. I don't rely on medicines to get better, but I rely on rebooting to maintain good health. Modern medicine has also proven that many diseases are actually lifestyle diseases. Diseases caused by bad habits such as staying up late, indulging in lust, sitting for a long time, etc. These must be given up first and only then can one actively treat and maintain health, so that it may be cured. The healing process of each person is slightly 
different. Some people rely on more medicine, and some people rely on more health-preserving exercises. But if you don’t pay attention to rebooting and health-preservation, you will easily relapse sooner or later.

## Book recommendation

**Ksitigarbha Sutra**:

Bodhisattva's original vow sutra, also known as "Ksitigarbha 
Bodhisattva Sutra",  and referred to as "Ksitigarbha Sutra". I recommend this book to brothers who have a buddha relationship. I hope that the brothers who have buddha destiny will not miss it. It is recorded in the scriptures that Buddha Shakyamuni was in the Keli Tiangong (the second heaven of 
the six days of the world of desire), speaking for his mother, Mrs. Maya. The Buddha praised Ksitigarbha’s grand vow  that "until hell is not empty, I vow not to become a Buddha, all beings are 
saved, and Fangzheng Bodhi", and introduced the typical examples of Ksitigarbha in the process of practicing according to the land, such as Brahman women, The story of the light-eyed woman saving her mother. When I first studied Buddhism, I watched the cartoons of the Ksitigarbha scripture, and I also watched the disguised picture of hell. Later, after I gained a certain experience through continuous study of Buddhism, my belief roots became deeper. When I looked back at the Ksitigarbha scripture, I was amazed by the power of this scripture. Ksitigarbha scripture is the Buddhist sutra of filial piety, and it is really the great filial piety. Brothers who wish to 
learn Buddhism should not miss this sutra. In addition, I recommend you to watch the cartoons of Hua Zang Guangming Ksitigarbha scriptures, which are very good. I have downloaded them and put them on my phone, so I can check them out from time to time. Learning Buddhism requires more edification. I hope that all of you brothers can be brave and diligent on the road of spiritual practice! Nan Wu Ji Zang King Bodhisattva!
