# A-grade sperm, about establishing correct sexual conceptions

## Foreword:

Regarding the term brainwashing, many brothers may think that brainwashing is not good. It seems to be a evil term, such as MLM brainwashing. In fact, this word is a neutral word, which can be used as a positive or negative word. Of every 100 people in China, almost al 100 have been brainwashed by the harmless theory, but they don't know it, and think that the harmless theory 
is right. The innocence theory is widespread in magazines and on the Internet. An advertisement that is broadcast dozens of times a day is also brainwashing the audience. Now that we have come to reboot and we know the truth about masturbation, we must continue to brainwash ourselves with rebooting articles, purify our own minds, and constantly improve our consciousness through learning, so that we can finally subdue the demons and at the same time remove harmlessness from the brain completely. In particular, newcomers must refrain from seeing harmlessness theory, because newcomers have a lot of ideological misconceptions, their consciousness is still low, and they don't have the ability to discriminate. If newcomers look at harmlessness theories, their rebooting determination will be shaken immediately.

Brainwashing is divided into good brainwashing and bad brainwashing. MLM is bad brainwashing and is harming you. And the indoctrination of rebooting articles is good brainwashing and is saving you. The well-known Chinese medicine doctor Li Ke also mentioned the term brainwashing, and used it as a commendatory term. For example, he said, 

>“For three generations of Chinese medicine practitioners, especially the modern practitioners who have been deeply influenced by Westernization, it is necessary to thoroughly brainwash them to live up to their destiny. The mission of the great cause of revival of Chinese medicine!” 

Therefore, everyone should not misunderstand the term brainwashing, thinking that brainwashing is not good. In fact, the phenomenon of brainwashing can be seen everywhere in our lives. Good brainwashing is saving us, not harming us. This must be made clear. Brainwashing is like washing dirty clothes. You must repeatedly delve into rebooting articles to achieve the effect of purifying your mind and consciousness. At the same time, we must also see our own progress. For example, you used to have 50 lustful thoughts a day, but now through learning, your lustful thoughts have been reduced to less than 10. This is progress, and then through continuous learning when thought arises, it is cut off. If thought starts, it is not followed. When thought starts, it is felt. With this skill of decisiveness, the level of rebooting will rise. After passing the obscenity barrier, half the battle is over. You don’t need to avoid using the term brainwashing, you can say brainwashing, you can also say purifying the mind and consciousness, these are two expressions with the same meaning. For example, going to jail, is to reform your mind, but it is also brainwashing. There are several sayings about brainwashing, but the meaning is actually one, which is to purify and 
transform your mind. Rebooting and brainwashing is to wash away the color and dirt, to wash away even the whiteness, and to return the mind to a pure state.

Several brothers have asked how they can control the amount of exercise they do, because they understand that sweating can damage the yang and qi. 
They are afraid that sweating profusely will not be conducive to the recovery of their bodies. Sweating is actually a double-edged sword. Sweating through exercise will consume a part of the essence. At the same time, the body's toxins will also be excreted through sweat. In addition, the cardiopulmonary
system and muscles will be exercised. For example, if you drive from A to B, you will reach your destination, but at the same time, part of the gasoline will be consumed. This principle is the same as the principle of exercise. Exercise sweat consumes a part of the essence, but the body has been exercised accordingly. Active exercise is a must. Movement produces yang, and stillness 
produces yin. One does not conform to the way of keeping good health if one is not moving. The key is understanding how to move and how to control the amount of exercise. Look at the movement of cheetahs and turtles. Cheetahs sweat profusely and have a short lifespan. The tortoise also moves, but it 
moves very slowly. In this way, the body is exercised without injury. 

We must control the degree of exercise, and this degree must be controlled in a flexible manner not rigidly. Because everyone’s body constitution and physical fitness levels are different, the method I teach you is to carefully observe your body’s reaction after exercise. If your body recovers quickly after exercise and there is no discomfort and you are full of energy the next day, the degree to which you have exercised is appropriate. If you feel tired after exercising and it is difficult to recover, it means that you need to adjust. Just like the customary practice of some sports teams, once an athlete enters a period of exercise fatigue, the body feels very tired and the training intensity cannot be kept up. At this time, the coach needs to adjust, either to reduce the amount of training or to strengthen the recovery, such as through massage, physical therapy, enhanced nutrition and so on. There is nothing wrong with sweating inherently. The key is to figure out whether you can afford to. Just like when you have 5,000 yuan and spend 500, it’s nothing at all, but if you only have 1,000 yuan and spend 500 the you've spent an entire half. If you feel good physically and sweat a little, there is no problem. If your body is very weak and you feel bad after exercise and find it is difficult to recover, you should pay attention to rest for some time. You can change to walking or health-preserving exercises, such as Baduanjin, Liuzi Jue, etc. Rest for a while, wait until the body is almost recovered then slowly increase the amount of exercise. There is a saying that one hundred exercises are worse than one walk. The way one exercises and the amount of exercise is very important. We should not blindly aim for more and more exercise. The key is to find our own levels. If we sweat profusely every day for a long time, then that is not conducive to health. Just like many professional athletes, who generally have the problem of over-exercising. They have a few injuries after retiring, and their health may not be as good as ordinary people's.

## Q & A

>Big Brother Feixiang, I am a newcomer. I rebooted a total of eight times, and all failed. Last time I rebooted for 47 days (my most). In the end, I accidentally saw Huang and broke. Looking back on the eight relapses, I found that I watched Huang, which means that Huang will break my reboot. After 
breaking this time, I felt sad and regretful, and there was an urge to die. Why do I always fail to break through? I was depressed, confused, and full of doubt. Is it because my perseverance is really so fragile? I sincerely hope that my eldest brother will show me a clear road !

**Answer:** Don’t think about suicide. Many people will experience failure when beginning rebooting. Don’t be discouraged. The key is to keep learning and raise your awareness. You are still a newcomer. Don’t force it. You must learn more and raise your awareness. Keep learning more lessons. Rebooting does not depend solely on perseverance. Remember this!

**Additional comment:** We must learn to draw lessons from our failures, so that we can quit better next time. **Failure is a blow, making the weak weaker, and making the strong stronger, because the strong know how to learn from failure**. Just like the Wright brothers, who invented the air plane, did not know how many failures there would be before the air plane would fly in the sky. They were not discouraged, instead, they kept summing up their experiences and lessons and making continuous improvements. Finally, they succeeded. When the White brothers invented the air plane, the first test air plane was shorter than the wing of a Boeing 747, but in the end they succeeded. Success comes from persistence, and success comes from continuous learning and continuous improvement.

> Brother Feixiang, I feel very bad and desperate now. I lost in 15 days and then again after 4 days. I had nocturnal emission for the next 3 days afterwards. Now I feel very ugly and in a very bad state. I am also doing kidney strengthening exercises, why are nocturnal emissions still occuring?

**Answer:** There are many factors that cause nocturnal emission. You have to learn to analyze it yourself. You can check out the season about controlling nocturnal emissions. The first spermatorrhea hurts the ability to "affix", therefore it becomes easy to have continuous spermatorrhea afterwards, so be extra vigilant and careful after the first spermatorrhea. The kidney strengthening exercise must also be in place, the auspicious lying position must be maintained, and many other factors that cause nocturnal emission must also be avoided. Keep going!

**Additional comment:** The problem of frequent emissions is a test that most brothers have to pass. After this test, there will be a foundation for better physical recovery. If frequent emissions cannot be overcome, it will be extremely difficult to recover. I have written about the issue of spermatorrhea in several seasons to help everyone control the frequency of 
spermatorrhea. If the control is successful, there will be a foundation for recovery. Otherwise, even the iron man will have weak legs. After the first spermatorrhea, the ability to affix will weaken, and then the phenomenon of continuous spermatorrhea is prone to appear, just as if the faucet is not 
closed tightly. At this time, the kidney strengthening function should be in place. In addition, the auspicious lying position should be fixed. Many brothers are really afraid of death. Once a nocturnal emission occurs, the spirit and energy will decrease, the legs will be weakened, and other symptoms may recur. Therefore, the control of dysplasia is the top priority for recovery.

> You are introducing more and more health-preserving exercises. I had a misconception before, and finally practiced miscellaneous, but the results were not good. Everyone knows that the health-preserving exercises are slow kung fu! So choose one or two practice that you are interested in!

**Additional comment:*** This is the suggestion of the pure heart, I think he said it very well. There are many methods of health maintenance. I once saw a brother who practiced a dozen of them a day. You cant do everything you need to do every day, such as standing and meditating, and other health-preserving methods. For example, tree therapy can be done 2-3 times a week, moxibustion 1-3 times a week, and kidney strengthening exercises before going to bed every day. There are also many other health maintenance methods, such as Baduanjin, Liuzi 
Jue, Lajin, Teeth tapping, Tiangu, Acupoint massage, Meridian tapping, Ear massage, Yijinjing, Taijiquan, Wrist rotation, Abdomen rubbing, Waist eye rubbing and so on. You can make flexible arrangements according to your own time. The main items must be determined, that is, they must be practiced every day, and the auxiliary items can be arranged in turns.

>Teacher, SOS! Is there any cure for hair loss? I have been masturbating for 11 years. I started severe hair loss half a year ago. I am only in my 20s now! Looking at the hair that keeps falling, I really want to die!

**Answer:** The recovery of hair loss is relatively slow, and the recovery is measured in years. Keep rebooting and keep in good health and it will improve. Keep on going! You are still young, so 
quickly quit, otherwise you might really be bald in the future.

**Additional comment:** Hair loss brothers are more distressed than other brothers. If hair loss is very serious, it will cause inferiority, even panic, and fear that you will be bald, especially at a young age. What an embarrassment! The recovery from hair loss is also relatively slow. You can only insist on rebooting and maintaining good health. The kidney qi must be maintained. Hair is the essence of the kidneys, and hair recovery is a slow process. All aspects must be done well, especially the control of dysplasia, health-preserving diet and so on. According to my personal 
experience and research, hair loss also occurs after a critical point. Some brothers have been fine with masturbation for ten years, but they have been accumulating chronically, they just don’t know it and think they are okay. When masturbation reaches the 11th year the evil results will appear. After the critical point, it will be very slow to reverse the situation. Therefore, with hair loss, the goal is to prevent it before it happens. When hair loss is really serious, it can only recover 
slowly. One thing to add is that many people want to die after hair loss. Hair loss is a cruel blow to appearance and self-confidence. 

> I really want to quit, and I understand the truth, but I can't quit. I have 20 days to take the college entrance examination, but I have been very tired from reviewing recently. I also played a plane, which has become more serious these days. I used to do it once or twice a week, but I don't know what happened recently, almost once a day, and I feel so tired during the day. Is there any good way to help me quit, I lack perseverance.

**Answer:** High pressure can lead to relapse. You may know the truth, but if you don’t know it deeply enough, you will still have to learn more to increase your awareness. Awareness subdues the mind demon. The reason why you break the precept is that your awareness is still shallow. Facing the mind demon, you have a lapse in judgement. Thus, learning is the kingly way of rebooting. You are about to take a college entrance examination, don't think too much, prepare for the college entrance examination. Keep going! It is not a matter of perseverance or willpower, the key is learning.

**Additional comment:** There are senior high school entrance examinations in life, college entrance examinations, and rebooting is the magic test. I wrote about the magic test in a season. The heart demon asks questions. Can you answer them correctly? The result of a wrong answer is breaking the reboot, and the heart demon is the chief examiner. This brother still didn't master the correct method of rebooting. He thought it was because of his lack of perseverance. In fact, the fundamental reason why he couldn't quit was because his awareness was not high enough, and he had to study hard to improve his understanding. As for perseverance, let me make an analogy. For 
example, if I give you a car to drive and you are unable to even start it because you haven't learned how to drive. Would you come to me and say "I don't have the perseverance". Wouldn't this be ridiculous? The key is to learn to drive, not to rely on preserverence alone. The same is true in rebooting. If we 
don't study and we rely on will power instead, how can this lead to the goal? Abstaining from studying is the road to failure, and learning to increase your awareness is a continuous process. 
Just like you can’t finish three years of high school mathematics in two days, don't have the misconception that reading two or three rebooting articles will be all you need. That level of understanding is actually very superficial and not deep enough. You must continue to study rebooting articles, take more notes, 
and face the magic exam like you are facing the college entrance examination.

> Teacher Feixiang, how can I restrain my dreams? I read a lot of rebooting articles every day and make a lot of notes every day, but my heart addiction is still very serious. I have all the symptoms, and I was so miserable when I was masturbating, but I still feel like a demon. I can’t help but read more when I encounter temptation. Close both eyes again. I barely restrained myself during the day, and felt a sense of powerlessness towards the demons at night. After suffering from depression, the 
quality of sleep has been very poor, the dreams are not reliable, the weather is hot, and I am half awake in the middle of the night. I always get used to doing masturbatory movements. Sometimes I can wake up and get away with it. I am worried that sooner or later I will break the precepts. This situation has occurred in the last three days. I feel like I am about to be killed by my subconscious mind. Brother Qiu Feixiang Help!

**Answer:** Repent and make up your mind to quit. If you are addicted, confession is necessary every day, and sincere confession from the heart is very important. Then you must increase the intensity of studying rebooting articles and repeatedly input positive energy, so that perseverance can purify the subconscious mind. You are stealing your heart and want to see it. You must overcome this kind of behavior. Keep going! It is necessary to turn a blind eye and not move like a mountain. Practice hard!

**Additional comment:** At the beginning of rebooting, my consciousness was still low and I had no concentration. When you see temptation, you can’t help yourself, and there are too many subconscious pornographic images. It is easy to subconsciously control when you are half-dreaming and 
half-awake, and you can’t control yourself at all. When this happens, you must increase brainwashing and continuously input positive energy to purify your mind. The dream will 
disappear. Many brothers have become accustomed to the action of masturbation, and they like to touch the crotch when there is nothing to do. You must correct this behavior. Except for urinating and bathing and cleaning, try not to touch in other situations. In addition, it is necessary to express more repentance. Brothers who believe in Buddha can confess to the Buddha statue. Brothers who do not believe in Buddha can confess in their hearts. More confession can affect the 
subconscious. It is best to be in your heart before going to bed. Repent.

> Brother Feixiang, why do I always insist until later that I don’t have the motivation to start? I couldn't help it as soon as the demons came, especially in the 60-plus days period. I am also learning aboutrebooting and I also know all the evil consequences, but I just don’t have the initial strength, what 
should I do?

**Answer:** It is normal. The tiredness of rebooting period is coming. As I mentioned in the previous article, it is very common to have tiredness of rebooting. You must adjust your mentality in time and develop good study habits. Don't just rely on enthusiasm to reboot. Rebooting should rely on longer-lasting rationality, so that the consciousness can be continuously improved, and more refreshing notebooks should be used. Slowly you will pass through the tiredness of rebooting, and 
then you will be more stable in rebooting. Keep on going!

**Additional comment:** I have also experienced the tiredness of rebooting, but I have developed good study habits. Even if I feel bored, I am not afraid. When I feel bored, I will read less rebooting articles and make an adjustment. When the condition is good, I continue to make efforts! Rebooting is like fighting a war. As time goes on, the morale of the army will drop or even decline. At this time, the officer will motivate the soldiers. We must learn to motivate ourselves and make ourselves full of energy. Don’t go fishing for three days and hang on the net for two days. We have to learn how to keep the water flowing and stick to it every day. Don’t read reboot articles for 3 days and then refrain from reading them for the next 10 days. Don’t break consistency. A reboot notebook is a must. It is also necessary to review the reboot notebook from time to time to learn the 
new through reviewing the past. As long as you can continue to persevere, it is difficult not to succeed. The key is persistence! Rebooting is also like climbing a mountain. Climb a little every 
day and don't stop, instead of rushing hard and then stopping halfway up the mountain. The race is between the tortoise and the hare, learn more about the tortoise!

>Flying, I think the rebooting regimen you mentioned is only suitable for those who are lightly injured. The human body’s ability to heal itself is limited. Most of our brothers are injured too severely, beyond limit. Those methods can only be used to assist in recovery, it is best to see a doctor! 

**Answer:** This is incorrect. I was injured very badly. Medicines were no longer working and I was already becoming resistant to them. In my case, I chose to stop the medicine and rely on 
health preservation to recover. I am not opposed to seeking medical treatment. The treatment should be active treatment, but health preservation is also extremely important. 30% treatment and 70% health preservation. Some health-preserving methods are no less effective than taking medicine. For example, moxibustion can cure many chronic diseases that have not been 
cured for a long time. Keep going!

**Additional comment:** Some brothers think that I have recommended a lot of health-preserving exercises, so they don’t want to take medicine. This kind of understanding is also wrong. In many Q&As, I suggest to actively seek medical treatment, and I never say not to see a doctor. Health-preserving exercises are a means or method for body recovery, and seeing a doctor and taking medicine is also a method. If your symptoms are severe and persistent, you should actively seek medical treatment. At that time, I was disappointed in the hospital and taking 
medicine, and so I turned to studying and practicing health-preserving exercises. I didn’t rely on medicine. I wascured by the health-preserving exercises. There are many ways to restore the body. We must not underestimate a good health regimen and focus only on taking medicine. Even if you take medicine for 
treatment, you still have to pay attention to the way of health preservation. Health-preserving exercises are not just to maintain the body, but are actually a treatment method. Many people have chronic diseases and the effect of taking medicine is very limited. An example is my rhinitis. Three surgeries and laser treatment were not enough, but through moxibustion, my rhinitis has improved a lot, and I rarely encounter it now. Taking medicine is a choice. Treatment should be actively sought, but I hope that everyone will not rely only on medicine. Firstly, medicines have side effects, especially western medicines. Secondly, if you take too much, you will become resistant.

## Main Topic {-}

This season I will share with you information on sperm quality and the establishment of correct sexual views.

There are three, six or nine grades of people, and their quality is good or bad, and the same is true for sperm. The quality of sperm is also good or bad. It is generally divided into four levels: A, B, C, and D. A has the best vitality and is of the highest quality. It is characterized by fast forward movement, B slow forward movement, and C non-forward movement. Class D does not move. There are also such things as defective sperm or abnormal sperm. In routine semen examinations, it 
can often be seen that more than half of the sperm of some patients are deformed, such as conical head, double head, double tail, curled tail, etc. This is called teratozoospermia. The increase in the rate of sperm deformity often indirectly reflects the impediment of the spermatogenesis of the testis, and it will inevitably affect the vitality and fertilization ability of the sperm.

**[Class A Sperm]:** Class A sperm refers to the sperm that moves forward in a fast straight line in the semen parameters. If less than 25% of Class A sperm is detected twice in a row, then it is considered asthenospermia, and the chance of natural conception is very low. However, asthenospermia has causes, such as inflammation of the reproductive tract, prostatitis, varicocele, obstructed testicular development, low semen volume, chromosomal abnormalities, and the production of anti-sperm antibodies in the body.

**Let’s start with 2 real cases:**
> Case 1: My lover had a fetal bud without fetal heart rate after pregnancy in 2010, and miscarried 3 months later. In 2011, there was no gestational sac after two months of pregnancy, it was a biochemical pregnancy. I am 31 years old this year. My semen was found to be of low quality after a miscarriage by my lover. B-ultrasound showed varicocele on the left side and hydrocele on the right side. In order to improve the quality of semen, the operation was performed at the People's Hospital of the prefecture-level city. It has been more than five months since the operation and there is no discomfort. Three months after surgery, the internal diameter of the spermatic vein was 
normal and there was no regurgitation. The testes, epididymis, seminal vesicle glands, etc. are all normal. However, the effect of re-examination of semen is not satisfactory. Except for the reduction of deformity rate, the improvement of weak sperm symptoms is not obvious.
2012.5.11 I went to the Municipal People's Hospital for a semen examination. The results are as 
follows:
>1. Semen volume 2ml, liquefaction time: 20 minutes to completely liquefy; pH 7.4; color: off-
white; viscosity: moderate.
>2. Dynamic analysis report
Sperm classification, number of sperm tested, sperm density 106/ml, 106 percentage of total sperm
A total of 831 332.8 665.29 100%
A-level 26 10.42 20.83 3.13%
Class B 183 7.31 146.62 22.02%
Class C 152 60.89 121.78 18.29%
Class D 470 188.28 376.56 56.56%
A+B grade sperm 209 83.72 167.45 25.15%
A+B+C sperm 361 144.61 289.23 43.44% (activity rate)
>3. Sperm morphology analysis report
Count the number of sperm: 200
Normal sperm count: 44, accounting for 22%
Number of defective sperm: 156, accounting for 78%
Number of sperm with head defect: 152, 76%
Number of sperm with neck and mid-end defect: 4 accounts for 2%
Number of sperm with tail defect: 16 accounted for 8%
Reference value for normal sperm morphology: >4%


>Case 2: Today I got my husband's semen examination report. Results as follows: 
liquefaction time 16 minutes, PH 7.5, survival rate 79%, motion analysis: A level (fast forward movement) 25.15%, B level (slow forward movement) 20.76%, C level (non- Forward movement) 
21.78%, D-class (immobility) 32.31%, and deformed sperm 80%. Because there is no specialist on duty today, the doctor will not be available until next Monday. I was very anxious after seeing this result, why is the deformity rate so high? Husband is a university teacher, usually does not like sports, often sits in front of the computer all day, especially this winter vacation. In addition, he doesn't drink alcohol, but he smokes a few cigarettes every day. Is it caused by his inactivity and smoking? Is there any good way to improve sperm quality? 

A recent news article has been shared below:

**The quality of Chinese men's semen has declined.**

According to a report by the "Yangcheng Evening News", a study by the National Population and Family Planning Commission showed that the quality of Chinese men’s semen is declining at a rate of 1% per year. There are more than 100 million of them, which has dropped to 60 to 70 million; meanwhile, the quality of men’s sperm is also declining. To this end, general medical textbooks must also be revised. Yang Dongzi, director of the Obstetrics and Gynecology Department of the Second Affiliated Hospital of Sun Yat-sen University, told reporters: "When I was in college, medical textbooks used the standards of the 1980s: the normal value of human sperm count is 40 million/ml, which is now the normal value. It has been revised to 20 million pieces/ml."

The "2012 Chinese Male Sperm Quality Survey White Paper" released a few days ago pointed out that the quality of male semen in my country is declining at a rate of 1% per year, and two of the male infertility patients are caused by poor semen quality. According to Zheng Xinmin, Professor of Urology and Andrology, Zhongnan Hospital, the Reproductive Medicine Center of the hospital used mice as the research object and found that electromagnetic radiation from mobile phones can cause damage to the germ cells in the testicles of mice and hinder the energy metabolism of spermatogenic cells (especially sperm). Reproductive toxicity. Zheng Xinmin pointed out that in 
addition to electromagnetic radiation generated by household appliances, mobile phones, computers, etc., environmental pollution, noise, excessive hot springs, irregular life, and high work pressure are also important reasons for the decline in male sperm quality.

The sperm quality of Jiangsu men is lower than the national level. Compared with 50 years ago, the sperm density of Jiangsu men has dropped by more than 40%. This is the latest data recently disclosed by the first sperm bank in Jiangsu Province. In the year since the bank was established, 86% of the sperm collected were of substandard quality.

"The vast majority of volunteers were eliminated because of poor sperm quality." Among the more than 600 volunteers, college students accounted for 90%, and the other 10% were mainly white-collar workers. Judging from the preliminary screening results in the past, the quality of male sperm is declining year by year, especially the younger generation is being affected by various factors such as environmental pollution. In the 1980s, 7-8 of the 10 sperm donors in Jiangsu were qualified. By the 1990s, only half of them were qualified, and now it has dropped to about 14%. "Nevertheless, men who fail to reach the preliminary screening results are also fertile, but the quality of their spermis relatively low." said the person in charge of the sperm bank.

**Analysis**

This news article summarized many reasons that lead to the decline of sperm quality, but did not mention that indulgence would lead to the decline of sperm quality. In modern society, there is serious prostitution, and the factor of indulgence cannot be ignored. Traditional Chinese medicine science realized long ago that indulgence would have a bad effect on sperm. Indulgence will lead to thinness and weakness, and it will cause the quality of semen to decrease. In fact, Western medicine has also confirmed that masturbation can cause prostatitis and spermatic cord and these two diseases will affect the quality of sperm. Recall that some brothers have their sperm 
quality checked, and some show complete infertility, and some have reproductive function, but have a lot of abnormal sperm. This will still affect the eugenics and fertility. In the 1980s, people's thinking and concepts were relatively traditional and conservative. At that time, it was an illegal act to watch
police arresting people. It was quite difficult to be able to see an H film at that time, and it was not easy to see it casually. It's completely different now, it's simply a dark age of adultery, full of pornography, and it's impossible to prevent it.

The young people of this generation are "sex-blessed", but they are also tragically cursed, because ejaculation hurts the kidneys, the reproductive function and the five internal organs. The kidney is the root of the five internal organs. If the root is injured, will not the body fall sick? Kidney deficiency can lead to hundreds of diseases, which is by no means an exaggeration. It's a pity that the younger generation doesn't know this and doesn't understand this! Blindly and foolishly, I thought I was awesome, but in fact I really harmed myself without knowing it, and I regretted it when I got sick with symptoms. Since the 1980s were relatively conservative and there were no computers and mobile phones, the sperm quality of men was relatively high at that time, but now it has declined a lot. Electromagnetic radiation is one reason, but indulgence is absolutely more relevant. Human fertility and kidney qi are closely related, 
and stubborn masturbation hurts the kidney extremely, it will inevitably affect the quality of sperm, and the decline of sperm quality is inevitable. Facts have shown that if you persist in rebooting and keeping in good health, and actively exercise, sperm quality will improve a lot.

Speaking of poor quality of sperm, a friend of mine is a good example. He has masturbated for more than ten years. He has gray hair and a wretched body. At first glance, he lacks energy. Later, he got married and his wife was pregnant, but every time she became pregnant for a few months, it would not work out. There was a problem after a checkup, and he had to abort. Although he didn't say it explicitly, I think it must be just like the first case. After pregnancy, there was a fetal bud without a fetal heart. Sperm quality is not good, just like a bad seed. No matter how fertile the soil is, it won’t work if your seed is poor. Even if you successfully conceive and give birth, your child's physique may be very poor in the future, and it will be easy to get sick.

The younger generation of China is misled with respect to sex, and is also lacking in sex education. There is no correct and systematic sex education in schools. The so-called sexologists who pick up outdated foreign rubbish theories are simply wrong, They are fallacies and heresy fabricated to cater to sexual liberation. Many young people don’t have any discernment, they just blindly act and don’t understand anything, just like a person who doesn’t know that there is a minefield in front of him. The ignorant are fearless. Seeing that there is temptation inside, they will rush in without any consideration. The result is a tragedy. NS. It's like moths fighting fire, their sexual function is 
also abolished. There are too many brothers with premature ejaculation and impotence, and there are similar posts every day. The so-called moderate masturbation theory is simply nonsense, and it is absurd to talk about moderation after being addicted. Fuguan is an out-and-out minefield, with symptomatic mines buried everywhere, but it's a pity that young people don't know, don't understand! Sooner or later, the enthusiasts will pay a heavy price for their ignorance.

>One theory can harm many people, and that is harmlessness.
>One theory can save countless people, and that is harmful theory.
Harmfulness is an absolute truth,
It is the experience and lessons of countless predecessors crying blood,
It is also the good-hearted advice of countless Chinese medicine practitioners.

We insist on rebooting and health preservation, in fact, we are strengthening the cultivation of the country. Rebooting is not only a personal matter, but also related to the destiny of the country. Sperm is the seed, which is to make the next generation of China. Poor quality of sperm will inevitably affect the physical fitness and even the brain power of the next generation. The quality of Chinese men’s sperm has fallen too much compared to the 1980s. This is mainly caused by the proliferation of adultery, electromagnetic radiation, and dietary pollution. The proliferation of adultery is absolutely inextricable, and it is the most direct and most direct cause of kidney damage. Our rebooting regimen is a positive factor for improving the quality of sperm. We are responsible for ourselves and our offspring. Think about it, in the 1980s, 7-8 of the 10 sperm donors in Jiangsu were qualified. By the 1990s, only half of them were qualified, and now it has dropped to about 14%. The decline in sperm quality being so marked, is it not worth our vigilance? The
aggression of the adulterous culture is an absolutely sinister conspiracy. It corrupts the younger generation of China making us inferior to the next generation. In the end, we become the sick man of East Asia again and fall to the point of being ravaged by other countries. This is by no means alarmist. If the culture of adultery continues to proliferate, the quality of sperm will be further reduced. The younger generation will have worse physical and mental skills, and it will get worse for each generation.

Regarding eugenics and education, Master Yinguang’s words are very good, and I recommend them to everyone:

>"Husbands are born males and females, and the law of the saints is the rule that makes males and females living in the house, thinking that the relationship between men and women is the greatest. The above-mentioned relationship is good, and the next is the inheritance of the ancestors. It is weak and weak, and it is difficult to grow if it consumes seeds and cannot produce buds. It is to grow, and most of them are not grown up. Fortunately, they will also be weak and cowardly, without great establishment. If you can maintain your spirit and abstinence After half a year, after his wife’s Tiangui hair, she chooses a good night and auspicious period, meets with her, and decides
to conceive. From then on, the child born will not only have a good sexual behavior, but also have a frivolous desire. Acne disease and other diseases. Tiangui means menstrual fluid. After the fluid is exhausted, you will get pregnant, and you will not be pregnant for the rest of the time. If the menstrual fluid is not exhausted, you will not be able to cross. Dalun's affairs, how can it be evil days and bad times, so you must choose a good night." 
-- Master Yinguang

Chinese medicine also talks about eugenics and childbearing. The following is an excerpt from "Secret Seed Golden Pill", written by famous doctor Ye Tianshi. The Secret Seed Golden Pill is very instructive for prenatal and postnatal care. It is not only for fertility, but also talks about health preservation and essence preservation.

**Summary of Seeds**
The way to live a life begins with asking for a child. The method of seeking a child does not dependon the two key points of nourishing men's essence and women's blood.

*Seed Vein Jue*
Seek the pulse of the child, dedicated to the ruler. The right foot is prosperous, and the fire is lustful; the left foot is prosperous, and the yin deficiency is not a blessing. However, it is easy to 
produce interest if it is heavy and smooth. Slightly astringent, clear, and extremely cold; if you see aslight cowardice, you will be unable to enter the room; if a female is not able to give birth, it will also have astringent pulse.

Regardless of whether young or old, strong or weak, they must have spiritual feet, which are based on few desires. The young people who have children tend to have weak ones, who want to be diligent and thin; in the old age, there are more strong ones, with fewer desires and perfect ones. When handing over again, don't go in and out arbitrarily. If you go in and out wildly, the tyre wind is inevitable. In that year, the old people have children, and most of them are not affected by the wind. After conception, you must not have sex with them again, for fear of injury to the fetus, or forfear of fetal poisoning. It is that the man must first self-government, and then the woman is a little different.

**Seeds must first nourish essence**
In the method of seed, the man must first nourish the essence and the woman must first nourish the blood. The childless people of today are often diligent in lust. No one knows that the yang essence will be thin if venting without restraint; if indulgence is indulgence, true qi is hurt. If you want to get a child, can you get pregnant? The husband and the male lead the giving, and the female lead the receiving. One giving and one receiving, pregnancy is the result. What is being administered 
today is not innately strong, but the dregs of the day after tomorrow, even if the yin can be transformed, there is no use for the yang. Therefore, heir seekers should not hurt their thoughts, 
consume their minds, do not want to go outside and be empty inside, do not want to hurt the inside and refute, do not use wine as a color medium, and do not use medicine to help the fire. Purity of the heart and little desires, tranquility and cherishing of essence, calmness for a long time, qi and 
fullness, moving according to the time, its innate true essence and vitality, overflowing with the dysfunction of the sun, self-defeating and undying. "Nei Jing" says: Yin and Yang secret, the spirit is the cure; Yin and Yang are separated, the essence is absolute. Lao Tzu said: You must be clear and quiet, and don't shake your spirit. The "Ren Jingjing" says: If the spirit is strong, two boys will be born. Cover that also.

】Nourishing Essence, Needing Few Desires】
Few desires don’t confuse arrogantly, concentrate on being attentive, and wait for the moment to move, so why ask for nothing? However, a few desires must first clear the heart, the heart governs the blood and hides the spirit, and the heart is moved, the spirit is out, although the outside has not vented, the essence has left the palace, that is, the kidney qi will also be internally disturbed, and thelight can range from dreams and turbidity. Then bayberry, knot poison. Fortunately, he was 
exempted. At the time of the meeting, there was no true energy of tranquility and tranquility, and the things that were leaked were all rotten. The heart is the master of the whole body, sincerely able to sweep away evil thoughts, and also use quiet work to preserve and support, without making fire, Tong Yang is full of essence, harmony in time, and achieved in one fell swoop. Therefore, if you have few desires, you will end your life. Not only do you have more children, but you also live longer.

】Nourishing Essence and Reducing Labor】
Husband’s essence is made in blood, not alone in the room, and it hurts my essence. There are manypeople who hurt my essence among daily things: if the eyes work on seeing, the blood is used for sight; the ears work on hearing, then the blood is used for hearing. ; The heart is labored by thinking, and the blood is consumed by thinking. I keep it at any time, but the blood is nourished and accumulates with each passing day.

】Nourishing Essence and Relieving Anger】

The kidney governs the occlusion, the liver governs the venting, and the two internal organs have mutual fire, and the tie belongs to the heart. Heart, Jun Huo. Anger hurts the liver and causes 
irritation, while anger is used to relieve people, and those who hide themselves cannot do their jobs.Although they don’t mate, they are undercurrent and exhausting.

】Nourishing spirits and abstaining from alcohol】
People's viscera and viscera are suitable for food and drink. It seems that you don't need to be too stubborn, but alcohol is not suitable. To cover the congenital aura of the fetus, it is very suitable to be clear, very suitable to be full, and alcoholic sex is not only chaotic, but also chaotic. Essence is wine chaos, and it is half hot and humid, and half ears are true essence. If the essence is not full, the fetus is not solid; if the essence is more humid and hot, the other day's acne rash, convulsion, and spleen failure, the rate has been based on this. Therefore, heirs must be strictly guarded, rather than drinking more, it is better to drink less; rather than drinking less, it is better not to drink, this is the 
great opportunity of the birth. If you enter the room after being drunk, you will be vigorous and follow the thin.

】Nourish the essence and taste carefully】
The scripture said: Those who lack the essence, make up for it with flavor. However, the fat and thick taste cannot produce sperm; but the thin taste can replenish the ears. Everything has a true taste, and if you reconcile it, you lose the true taste. Regardless of the meat and vegetables, if you cook well, you will have a kind of calming and calming air, and eating can nourish the essence. There are a lot of foods, but grains are the right flavors. Therefore, after the porridge and rice are cooked, there is thick juice on the top, which is gathered by the semen of the rice, and the sperm can be produced by the sudden eating, and the trial is effective. A person who can do counts is not specifically a recipe for heirs, but it can also be a magical technique for conserving one's life.

[Men have three to three]
When men and women have not met, there are three to men, which means: those who are vigorous and vigorous, the liver is strong; those who are strong and hot, the heart is strong; those who are strong and long, the kidney qi is also strong. If the dysfunction is not lifted, the liver qi is not reached, and the liver qi is not reached but strong, then the muscles will be injured, and the essence will drip without shooting. If it hurts its blood, its essence is cold and not warm; if it is firm and soon, the kidney qi has not yet reached, and the kidney qi has not yet reached and is strong, it will hurt its bones, and its essence will not come out, although it will be too little. Heir-seekers want to clean up the heart and nourish the vitality of the liver, heart and kidney.

】Intercourse avoidance】
When men and women intercourse, the ancient law should avoid Bingding Day, Xianhui Day, and Synoptic Day. However, if you are a difficult heir, it seems to be unrestrained. If there is strong 
wind, heavy rain, heavy thunder, heavy fog, severe cold, scorching heat, and the world is dark, the sun and the moon are eclipsed, and the Hongni earthquake, the anger of the world will be unrighteous. Qi, offense will damage a man a hundred times, and make a woman more ill. Even if you have a child, you will be idiotic, stubborn, dumb, deaf, lame, blind, multiple illnesses, short-lived, unfilial, and should be avoided. One too. Under the sun, moon and stars, among temples and Buddhist temples, on the side of the well-soiled toilets, by the tombs of the tombs, and in the dark and dangerous places, it is not to be committed. Husbands get together and avoid them, then there ismerit, great wisdom, and good gods to come into the house. It is to make the sexual behavior harmonious, the family will grow day by day, not only for less illness, but also for smart, handsomeand longevity; if you don't avoid taboos, you will be foolish and evil Coming to the house is dangerous and dangerous, and the family is dying. Not only the disabled, but also the disaster. But the answer to misfortune and good fortune is in vain, and the experience is like an impact.

## Establishing correct sexual conceptions

The goal of China's reformation was to absorb and learn from the strengths and advantages of other countries. It was to take the essence and discard the dross, instead of throwing away its own traditional culture and blindly admiring foreigners. In the reformation, both the good and the bad have come in. It is not clear what is good and what is bad. 
The ideas of indulgence and sexual liberation have also floated into China. It seems that Chinese people have been suppressed by sex for thousands of years. It is time to indulge and enjoy, so many people began to advocate sexual liberation and sexual openness, and regarded the conservative ideas of the ancestors as a feudal tyranny that suppressed human nature. In fact, the ancestors’ conservative attitude towards sex was not wrong. Even if we do not go back all the way to ancient times, we can dicover how even inthe 1970s and 1980s the attitude towards sex was still very conservative and cautious. Nowadays, the culture of adultery is extremely prevalent. Many young people worship AV actresses and call them "teachers", which is ridiculous and shocking! The human heart is drowning, and morals are degraded to the point of inferiority. The state of etiquette is about to become a state of adultery. It is really sad and lamentable! The children of China have fallen this way, how can they have the face to face their ancestors!

The harm of sexual openness is too great. Sexual openness can cause many evil results. There are 13 million abortions in China every year. This is a shocking number. This is legal killing. 
Abortion can cause harm to women's bodies. Some women have abortions many times, suffer from serious gynecological diseases and some cannot get pregnant. This is a tragedy. After sexual 
liberalization, the divorce rate has also risen sharply. Because now there is nothingwrong with it. The sense of family responsibility and moral ethics are completely forgotten. Many 
people are really reduced to beasts.

Sexual liberalization abroad is in the early stages. Still they have realized the evil consequences of sexual liberalization and have begun to advocate abstinence. Many young people abroad have 
religious beliefs, and religious beliefs have a binding effect on adultery. However, the vast majority of the younger generation in China are atheists. Because they do not understand cause and effect and lack faith, they've become more unscrupulous and rampant. This is the tragedy of the younger generation in China. Other countries have realized the evil consequences of sexual openness, but our country is still continuing to engage in sexual openness, going further and further down the wrong path. Because of sexual openness and obsessive sex, many young people in China have problems with their bodies. There are always old Chinese doctors who sigh, what is wrong with young people now? The pulse of 60 years old appears at the age of 20, and what happens to the liver and kidneys even though they are not married yet? Is it all imaginary? I had premature ejaculation and impotence before getting married, and I had fallen very sick before marriage. This was actually the evil result of adultery. The media promotes adultery heavily, which makes young people think that wrong is right and right is wrong. Ultimately they harm themselves. I used to be a victim. I used to think that there is nothing wrong with sexual openness. People around me also thought so. The media promotes this heavily. The environment is indulgent. It wasn't until my body collapsed that I discovered the harm of adultery was very tragic. At the beginning, the frog was boiled in warm water. Before I knew it, my body slowly faded away.

The most important thing for young people is to establish the correct conception of sex, what can be done and what can not be done. They must have a understanding of right and wrong, and must adhere to their own principles. Our ancestors said that adultery will cause evil results, and we have to listen to them. If we don’t listen to the old people, we will suffer. Many people like to follow the crowd. One sees everyone doing something like this, and he does it too. He has never thought about right or wrong. Everyone is does what they want, and he also wants to do what he wants. Are the kidneys not hurt because everyone is doing what they want? Would it be less harmful for everyone to control it? However, everyone is arrogant, and personal 
guilt will be reduced a lot, because he will think that everyone does this, and I do it, there is nothing wrong with it. In fact, everyone is wrong, and the truth is in the hands of a few sober people. There is a famous saying in the stock market: 

**The masses are always wrong!**

 This sentence also applies to the world of masturbation. The person who masturbates is always wrong, but he himself does not know that he is wrong. The symptoms keep slapping him awake, even if he can’t wake himself up. The symptoms are physical warnings. He was warned that he could not masturbate again, but because of ignorance and stupidity, he didn't know at all. It's really sad!

The younger generation is captured by the wrong ideas of indulgence, and become a flesh machine just for indulgence, and their desires can never be completely satisfied. It is said: *"Lust 
indulgence, such as drinking salt water, drinking more and more thirst, until the death."* After a short period of pleasure, there is a huge emptiness. **The pleasure is like a deception, an illusion**. You don't get anything. Finally, your body begins to show signs of collapse, gradually becoming sick with symptoms, and it is better to die! Let’s talk about four types of adultery:

1. **Pre-marital sex:** Rebooting forum advocates abstinence before marriage and temperance after marriage. This is not only an ideological concept, but it is also protecting yourself. Because there are too many brothers who are already wasted before marriage, I have seen countless brothers who are still unmarried, but serious problems have occurred in their sexual function, and some even have complete impotence, on the verge of collapse. Yes, the suicidal heart is gone. Premarital sex is a kind of overdraft of the body, and many people are still relatively ignorant and naive, it is easy to experience sexual indulgence. For example, some brothers indulge 6 times a night, with such 
indulgence, the body will show symptoms soon . Premarital sex also impairs fertility, and many brothers are weak and even unable to have children. Some brothers are not too old, but they have had their girlfriends aborted. According to Buddhism, this is all killing karma, and it will be rewarded with evil, and the end will be tragic. For some younger brothers, I advise you to avoid 
premarital sex as much as possible. You should raise your body before marriage, and then control your sex life after marriage. Having a good body is the most important thing. Don’t be unmarried. Give up first, it will be embarrassing and life will become very gloomy. Premarital sex is not responsible behavior, many people live purely to satisfy their own desires. Others want to talk about love and marriage at first, but they are completely lost in the quagmire of desire, and they are tired of abandoning others. We still have to be extra cautious when we fall in love. We can’t have relationships casually. Please be a truly responsible man.

2. **Extramarital sex:** I have always thought that although extramarital sex is full of temptations, it is poisonous. Just like a beautiful poison, it not only hurts the body by indulgence, but also seriously undermines the stability of the family. It is easy to get bored of sex. Studies have shown that it takes only about 18 months for a man to get tired of a woman, that is, the passion is gone in about 18 months, sometimes it doesn't even need 18 months, and there may be no passion in a few months. If you 
choose to enter a marriage, you must focus on your sense of responsibility. Otherwise, once the passion fades, your life will fall into a dull life, and you will be prone to quarrels and even cheating. Cheating is also addictive, always looking for fresh stimuli, always looking for prey, from one body to the next, from freshness to boredom to freshness. Being controlled by desire and kidnapped by a heart demon is actually being a slave to desire. If there are children, divorce is a great blow to them, and it will hurt the children’s young hearts, especially the kind of children with a very sensitive heart. The divorce of parents will cause great damage to the children. The adverse effects. Therefore, a married man must take responsibility as the most important duty, and must not try extramarital sex, which will only lead to life tragedy.

3. **One-night stands:** There are too many one-night stands in this era. It seems okay to break up after dawn as one is unburdened and unrestrained in anyway, but such indulgence is very dangerous, and once you become obsessed with one-night stands, it is likely to lay evil groundwork for the future when you start family life. People who have one-night stands are more likely to cheat after marriage, and the excitement of one-
night stand will only make people feel more empty and bored. Pursuing the momentary pleasure of the flesh will only make people live like the walking dead. One-night stands generally have a characteristic, that is, indulgence multiple times a night. Such continuous indulgence is extremely harmful to the body, the essence is completely hollowed out, and one will soon be ridden with symptoms. The proliferation of one-night stands makes people degenerate into beasts, completely losing their courtesy, justice and shame. Even animals are better in the regard. Animals at least pay attention to the estrus period. 
People have no restriction on the estrus period and can engage in it at any time. Not as good as dogs. There are also many other harmful effects of one-night stands. If you don’t manage to do so, you will get venereal diseases. Engaging in one-night stands will also affect your work status. The focus is on indulgence, which makes the legs weak, gives low back pain and frequent urination, hence work is also very affected. Brain power also drops drastically, and what you do is forgotten after doing it. If you are already married and have a one-night stand, your wife could find out and that will lead to a family battle or even a divorce, crying, making trouble and hanging yourself. Enough for you to drink a bottle just to forget.

4. **Prostitution:** In the process of answering my questions, many brothers confessed to methe experience of prostitution, and some brothers were even addicted to prostitution, and they did not listen to their own legs. Said, it’s okay to go to the scene to see it, even though the erection is dysfunctional, it’s okay to touch it, it’s already degenerated to such an unbearable level. Some brothers even contracted AIDS because of their experience of prostitution. They were in fear and panic all day long. Even if they were tested repeatedly, it would be of no avail. They were always worried that they would have AIDS. Some people don't have AIDS, but they have gonorrhea, genital warts, and syphilis. There was once a brother who had condyloma acuminata. He did not spend a lot of money to see a doctor, and he also suffered a lot. It was really regretful. A misfortune 
becomes an eternal hate. I often walk by the river without wet shoes. I can't make it easy to get a venereal disease after prostitution. Some venereal diseases have an incubation period, even more than ten years, and people don’t get sick until middle age. Syphilis may cause dementia later, and the consequences are really terrifying. So be sure not to go to prostitution, prostitution hurts one's morals, and the harm is too great.

## Summary:
I hope that the younger generation in China can establish a correct view of sex. Don’t be greedy to indulge yourself for a while. Please save your best self until after marriage. Sexual indulgence will bring evil rewards. Others will be chaotic because of ignorance. We are reasonable people, we can't mess around, we must hold ourselves firmly, and be a man with a sense of responsibility and positive energy. Such a man can give the goddess a sense of security. Let us stay away from the
life of adultery. Don't be inferior to beasts, go around fooling around, and finally destroy the family and destroy the body. Such an indulgent life is destined to be a great tragedy.

## Book Recommendations:
The old man with vowel "Dharma Cultivation of the Heart", this book (upper and lower two volumes) is sold in all major online bookstores. Although I have read a lot of the teachings of the 
great virtues, the one which is most destined for me is Yuan The old man's teachings. It was the vowel old man who gave me the right knowledge and right view of the Dharma. I often watch his "Nianhualu" teaching video. It is a rare kind of good knowledge. I am also being held to recite the Guang Mantra of Going to Life. The old man with vowels emphasized the understanding of the 
mind. He witnessed his true colors, so what he said was particularly powerful. Of course, there are many great virtues in Buddhism. Brothers who want to learn Buddhism can choose to get close to their masters who are predestined. I am also watching Master Yinguang’s teachings, and I also feel that I am too late to meet.


