# Ten Songs to the Heart of Rebooting

## Foreword

I applied for the forum master role. Although there were some twists and turns, I got the role in the end. In terms of experience, I am not the oldest. I re-checked my earliest posting records. Reboot Forum was established on October 25, 2010, and the date of my first post in Reboot Forum was March 23, 2011. I remember when I first started to reboot, Tudou and the others 
just finished their struggle with the "75 Party". It seems that the gunpowder had not completely dissipated. However, 75 Party was like a grasshopper after the fall. It would not be a few days after the fall, before 75 Party gradually disappeared. 75th Party has spread countless harmless theories on the Internet, and the goal of poisoning young people has been achieved.

At the time, rebooting forums were still in the "naive period," and they were very irregular in many aspects. There were only a few hundred members, and there was a lack of answering talents. 
Everyone was basically quitting, and there was very little experience to learn from. I came to reboot at that time, and I also posted casually, just reprinted a few ancient couplets about rebooting. I paid attention to rebooting for the first time, and it lasted for about 2 months. At that time, the popularity 
of rebooting was very low, and it was a common phenomenon that no one posted a reply. After paying attention for about 2 months, I left rebooting. I ran back to the group to help 
neurotic patients, because I had been helping the neurotic patients before. From the experience of helping the neurotic patients, I accumulated a lot of rehabilitation experience 
and accumulated a lot of knowledge about Chinese medicine health through continuous learning. I acquired the ability to answer questions and solve doubts. Moreover, I am a recovered person and can answer questions in a more targeted manner and have a deeper understanding of nerves. The real situation 
of the patient. At that time, compared to rebooting, I felt that the neurosis needed my help more, so I just left rebooting.

When I returned to the rebooting forum again, it was probably more than half a year later. Maybe it was fate. I decided to stay rebooting. Of course, there were also other reasons behind it, because I think it is very costly to help patients one-on-one on QQ. The energy and coverage are very narrow. I need a bigger platform to help more people. I found that rebooting forum was just such a platform, and then I went to reboot forum to answer questions, and QQ group basically stopped. At that time, rebooting forums were short of question-answering talents. It was very common that no one answered the questions. Even if they answered, they were very unprofessional. At that time, my 
goal was to eliminate zero-response posts. In addition to answering questions, I also posted some rebooting pictures, which were immediately refined by Tudou. It was also Tudou’s grace. I am still very grateful for Tudou’s support. He saw that I did a good job in pictures, and he asked me to do picture editing and video editing, and then he asked me to do a forum magazine, and then he asked me to become a minor forum master.

In the process of constantly answering questions, I realized that if I could write articles in seasons to introduce successful experiences, this would better guide brothers to reboot. At that time, rebootingalso lacked the guiding ideology it has now. There were a lot of posts about blind rebooting and relapse, and very few posts about successful rebooting. At that time, I almost never saw one who could reboot for 100 days. So, I started to write articles, and the response was very good at the time. The atmosphere in the form was uplifted, and the brothers seemed to see the hope of success. I remember that I followed more than 7,600 of that post, and then it began to be released in seasons. After a few seasons, some brothers suggested that I continue to publish. It is best to write a book in the future to help more brothers. So I persevered, and I have never left rebooting. I have completed 50 seasons. Of course I will continue to publish more. However, the main body of "Rebooting as the Best Medicine" has been completed, and the content that continues to be published is only supplements and improvements. After abosrbing these 50 seasons, you can reboot successfully, it depends on how much you have absorbed and understood. In fact, many brothers have read my experience post and have successfully rebooted. I hope that more and more brothers can benefit, and find the lost beauty and purity.

Regarding the position of the big forum, I have let Xian go twice. For the first time, Potato wanted me to be big. I was very busy at that time, so I politely declined. Later, there was a vacancy for the big forum master again. Many brothers suggested that I apply for the big forum master, so I applied. At this time, suddenly "no excuses" came back. He had helped many brothers with me before. He really wanted to be the master, so I took the initiative to let the virtuous. My character has never liked
fighting since I was a child. If you want to be a master, I will give it to you. After that, I stayed silently as the master of the small forum until "no excuses" recently resigned , and some brothers 
suggested that I apply for the master of the large forum, and Ba Ling and Tudou have said that if I become a big forum master, reboot the development of the forum will be better, and the rebooting forum will be more appealing. I thought about it, too. The time is ripe, I should stand up and bear this banner. I am definitely not jealous of the virtuous. On the contrary, I hope that someone can surpass me, and even hope that everyone can surpass me, because I am not for myself, I am serving 
everyone, all living beings are big bodhisattvas, and I am the only one. Ordinary people, I am the servant of sentient beings. I hope that the majority of brothers can reboot as soon as possible, and 
regain their sunny, pure, healthy, and fresh selves.

As appointed master, I strongly welcome all rebooting talents in the world and recruiting people with lofty ideals in rebooting all over the world. The rebooting forum will give you a platform to 
develop. Let us create a great rebooting cause. I hope you can help more brothers. The rebooting forumneeds talents to promote its development. The first generations of the legendary Maya were the predecessors of the legendary Maya. They fought bravely with the 75th party, and they have the pure sky of rebooting forum now. They are equivalent to the founding fathers, really. It's not easy. Rebooting requires a variety of talents, mainly divided into three categories: management talents, propaganda talents, and question answering talents. Management is to make the rebooting forum run more systematically, and publicity is to promote rebooting. Publicity is also extremely important. Many brothers are doing voluntary publicity. Even if they are misunderstood or scolded, they have 
no regrets. In the practice of propaganda, I have explored a set of my own experiences. If you have ideas for propaganda, you should communicate with them more and learn from their 
successful propaganda experience. Perhaps a piece of your propaganda can change the destiny of a person's life. Many new people come to rebooting and are very grateful to the person who let them know about rebooting. That person is an unknown warrior who silently propagates. Propaganda requires courage and strategy. Pay tribute to the propaganda staff of the reboot forum!

Question answering talents are also indispensable for rebooting bars. I was questioning answering talents from the beginning. The most indispensable thing for rebooting forums are questions. Various questions are posted every day. To successfully reboot, it is necessary to clear the misunderstandings and various questions in the minds of newcomers, and only when the doubts in the heart are answered, can the confidence and determination of rebooting be strengthened. Therefore, answering talents are also very important. I hope that there will be more question-answering talents in the rebooting forum, and resident rebooting forums. The members of the rebooting forum are increasing. More 
and more question-answering talents are needed to answer questions and correct new people’s thoughts in a timely manner. Clearing misunderstandings encourages newcomers and give them confidence to reboot. Old brothers bring new people, and as time goes by, new people will become seniors, and then 
bring a group of new people, so that a positive cycle can be formed. When we help others, we are actually helping ourselves. When we save others, we are actually saving ourselves. While donating positive energy, we are also strengthening our own positive energy. Come on, everybody!

## Q&A
>Brother Feixiang, I don't know why the effect of Kidney strengthening exercises on me is getting weaker and weaker. At first, I did the exercise for more than 30 days without a nocturnal emission, and then it became a 15-day nocturnal emission, then a week or so, and recentlyit became a 3-4 day nocturnal emission. The invigorating kidney function has no effect, which makes me less and less confident in it. I am trying my best to find the tension, but the effect is not obvious. I am doing 400 reps a day, in sets of 100, standing on more than 10 centimeters of books, and touching the ground with my palms. Brother Feixiang, you have been rebooting for so long, and your ligaments have become looser and weaker. So how high do you have to step on for kidney strengthening? Do I still want to continue to strengthen, ask for answers, thank you!

**Answer:** The answer is simple, because you have adapted to that intensity and can't find the tension. I push my limit. I do it on a 30cm stool. The key is the sense of tension. If there is no sense of tension, even if your hands touch the ground, it is useless. Keep going! In addition, it is recommended to use auspicious sleeping position.

**Additional comment:** Some brothers have just started to do kidney strengthening. Because they have a certain physical talent, they can quickly find the right feeling. They can limit nocturnal emissions to once in more than a month. Some brothers even give feedback that they have done kidney 
strengthening. Spring dreams will not have spermatorrhea, and they can be controlled when they are about to have spermatorrhea, and the spermatorrhea is extremely strong. However, if the kidney exercise is done for a long time, the ligaments will be loosened and the tension will be difficult to 
find. Then the frequency of spermatorrhea will become more frequent, so you must hit your limit and keep the tension at the limit. I used to touch the ground very easily with my palms, so I stood on a small stool to do kidney strengthening, but I didn’t always hit the limit. What I mean is, I just hit the limit and stop. This is a very tricky part. Every time I hit the limit, I just hit it a few times and then stop. For example, when a rubber band is newly bought, you can feel the limit when you pull it, but when you keep pulling it up to the limit, it will become looser and looser, and finally it will relax completely. Therefore, we cannot hit the limit many times. If we hit the limit many times, 
the ligaments will become looser and looser, and then it will be difficult to find the tension. My suggestion is to stop after a few impacts when the impact reaches the limit, so as not to completely loosen the ligament, and then it will be difficult to find the tension. In fact, I have already closed tightly the few times I hit the limit. I usually do not exceed the limit 
more than 5 times. The limit times cannot be done too much, otherwise it will relax and the tension will not be found. At the beginning of the kidney strengthening exercise, you can do more, you can do more than 10 times, but if you progress to a certain level, then you should lower the limit times and try to control it to about 5 times. This is very important. If you want to make kidney strengthening work effective for a long time, we must seriously understand this point.

>2. Flying brother, why do I always feel dirty on my face and have large pores? How long does it take to recover?

**Answer:** Considering the endocrine disorder, many people who are irritated are oily, dull, and have enlarged pores, and then they are not clean, and find it useless to wash many times. Generally, stay rebooting and keep healthy, take active exercise, and keep yourself clean and clear after three months. In addition, 
the frequency of spermatorrhea also needs to be strictly controlled. Keep going!

**Additional comment:** People who masturbate will have different symptoms depending on their physique. There are some brothers who have dirty faces, large pores, and oily faces. They can't be cleaned no matter how they are washed, and their faces are very prone to allergies. There are brothers who do 
not suffer from bad pores and skin, but their complexion is severely degraded, their temperament is wretched and their eyes are dull, they look like zombies, their eyes will be deformed, and their face will even change. The face is not clean, the pores are enlarged, and there are usually acne problems. It can cause endocrine disorders. My face was not cleaned and I had acne. At that time, I thought it was a normal phenomenon in puberty, but later found out that it was not because many middle-aged
men also have acne on their faces, which is actually caused by indulgence. Endocrine disorders. In general, if you can keep rebooting and stay healthy and do active exercise, you can improve a lot in about three months. The face will become clear again, brighten again, the eyes will become more energetic, and the spirit will be restored. This is a very subtle feeling. If you observe carefully, you will find that masturbation will make people degenerate and decay, and abstaining from it will make you fresh again! This kind of freshness is just like fresh fruit, fresh fruit has a clear and full aura that can make people feel comfortable and happy. But the masturbator is like a fruit that has gone bad and expired. His face is dull, and it looks like a layer of gray from a distance.

>Brother Feixiang, viewing white bones and viewing impurity is horrible and disgusting. I suddenly became disinterested in women. These two tricks are indeed effective for rebooting, but I just can't accept it.

**Answer:** The viewing of bones and the viewing of impurity can be imagined at ordinary times, and you don't need to look at overly disgusting pictures. It may have adverse psychological effects, or you may be unable to eat, etc. Keep going!

**Additional comment:** There are indeed a lot of super disgusting pictures of bones and impurity. Of course, brothers with stronger psychological endurance can see them, but they 
shouldn't be watched more. **It's not that you can't bear it, but if you watch too much, you will become numb**. Like a medical school student, who is a little uncomfortable with dead bodies at first, and then becomes numb to it after repeated exposure. I also use bone viewing and impure viewing, but I just imagine it, and I don't usually look at disgusting pictures. The viewing of these things is meant to help deal with your own evil thoughts, not to vilify or attack or disrespect women. Everyone should 
recognize that the weapon is aimed at their own evil thoughts, not at women. In addition to the view of bones and impurity, I suggest that you can also use "thinking of oneself", which is to treat a woman as one's own close relative, as a mother, as a relative or sister. This generally prevents evil thoughts. You don't even let your close relatives go, that's really a beast. Regarding the view of white bones and impurity, women can also use them, but they use the other way around, and view the man’s body as white bones and impurity.

> Hello Brother Flying! I am 23 years old and have 8 years of masturbation history. After masturbation last month, I suddenly experienced a lot of symptoms, such as left abdomen swelling, 
general weakness, frequent urination (this was a bit earlier actually), light sleep, early waking, and so on. 
However, I went to the top three hospitals for a lot of checkups and the did not find any problems. Unforunately, the symptoms still existed (deep pain, I always feel the body is weird), and my life is completely messed up. I also discovered rebooting because of my illness this time. I read all your articles and I am deeply educated. I have been rebooting for more than a month, and I usually pay attention to it. However, no spermatorrhea does not occur, and morning erection is sometimes absent. I am 
struggling now, wanting to try masturbation to see if it is normal, but I am afraid of aggravating the condition. I wonder if you can help me analyze what to do?

**Answer:** I think you may have prostatitis. Have you had your prostate fluid checked? If your prostatic fluid examination is also normal, then it should be considered a functional problem. If you stick to rebooting, the frequency of spermatorrhea will return to normal. DO NOT TRY MASTURBATION! You will get out of control after you try it. I suggest you take care of recuperation and exercise actively, so that the discomfort will gradually alleviate or even disappear. Keep going!

**Additional comment:** The outbreak of symptoms has a chronic accumulation process, just like boiling water which reaches the boiling point only at the end. If one continues to masturbate, they will reach the critical point of symptoms, and then the symptoms will burst out in a concentrated manner. Many people are very happy. They feel that they are asymptomatic or have no obvious symptoms, and they think they are okay. In fact, they are wrong. At the critical point, the symptoms will suddenly appear, and you will have to suffer. Many people already have a dark illness. They have already had a lot of discomfort, and the symptoms have worsened, so they will converge, and they will get better after a period of time. When the scars are healed, they forget the pain, and then they start to recover. When the symptoms really affect one and after waking up completely, one will really make up his mind to completely abstain from sex. Many brothers go on to say, "I'm really afraid, I really don't dare." If the symptoms are not severe enough or cruel enough, they don't stick in memory. Of course, some brothers are particularly addicted. For a very serious illness, it’s really sad that it’s still not changing. One should still take the path of professional rebooting. Do not force or blindly 
reboot. It is impossible to succeed. Even if the symptoms are severe, if you are still forcefully rebooting, then you are doomed to fail. 

The warm water frog has a comfortable and happy life before being scalded. He was swimming comfortably in warm water. He thought he was in a hot spring, but he didn't know that the 
temperature below was slowly heating up. A tragedy was about to happen soon. Therefore, when you say rebooting to a warm water frog, you are playing the piano to a cow. He doesn’t 
listen. For this kind of person, he can only be taught by symptoms. Symptoms are the best teacher. Symptoms will slap him a few times. Those with good roots can be awakened. A lot of people who are in charge seem to be okay on the surface, but in fact, only they know that their body is not as good as before, and only they knows that there has been a decline in brain power. Many of the symptoms caused by masturbation are hidden diseases. So let's not just look at superficial phenomena, it is difficult to know the truth from the superficial, unless you are an expert in Taoism and can see the little things. Just like Bian Que who saw Cai Huangong, Bian Que was an expert in face-to-face consultation, and he knew that Cai Huangong had a physical problem at a glance, but how can a mortal know? Only a person with a high level of Taoism can do it.

## Main Topic

In this season I will summarize and share my rebooting thoughts with you, so that everyone can better understand my rebooting thoughts. I took the path of professional rebooting, studying variousproblems in the rebooting process, studying the laws and principles of rebooting, studying the psychology of rebooting, and studying the laws of abstinence. My article also talks about harm, but more importantly, let everyone clearly and deeply understand the nature of the various phenomena in rebooting. When your consciousness reaches a certain level, complete rebooting will become possible. Some brothers have been learning, but still can’t get rid of it. Don’t be discouraged in this 
situation. Don’t be discouraged. Keep learning, focus on accumulation, take more notes, review the past and learn the new, keep learning and improve your consciousness, let your consciousness continue to improve, and you will eventually meet it. Come to the "turn around" point.

I really like the word "interpreter". I learned it while watching a show. The show was about the learning process of teaching somersaults in a circus. No matter how you teach a bear at the 
beginning, it just can't learn somersaults. Do you know how the trainer does it? It is to train the bearrepeatedly until one day six months later, the bear suddenly learns to turn somersaults, and after that, it completely "turns on the body", which is what people call "opens the body", and then opens up all at once. I'll have somersaults all my life, and I've mastered it completely. The same is true for our rebooting. As long as we keep learning and improving our consciousness, we will eventually usher in the "recovering one's body". Some brothers reported that they have been studying rebooting articles repeatedly, and suddenly they understood all of them one day, and they really understood deeply, and they went up as soon as they realized it.

Many brothers are reading and studying the reboot articles I wrote. The key is how much can you absorb? Many people look at the flowers, read them and forget them. They seem to understand all of them, but they can’t say a word. If they only focus on the superficial understanding, it will not work. If you are good at rebooting articles, you should take more notes and refine them yourself. Summarize the essence of the sentence. No one can replace you in this process, only you can think 
and understand.

I summarized my rebooting thoughts into ten points. The so-called ten chants are ten key points. 

The details are as follows:

### Ten Songs to the Marrow of Rebooting

>1. The first step in rebooting
Is to just recognize the harmlessness theory,
Establish determination and confidence in rebooting,
Thoroughly understand the truth of rebooting,
The mind is no longer obscured by harmlessness,
Suddenly awakened.

**Marrow explanation:** harmless theory, moderate harmless theory, normal theory, universal theory, and even beneficial theory. All these views on sex and masturbation are extremely harmful, among which the theory of moderate harmlessness is the most cunning, deceptive and misleading. Some brothers still 
don't believe it when they are told that masturbation and sex are completely harmless, but when they are told that it is moderately harmless, they are more convinced. In fact, they simply think of masturbation, the water is too deep, masturbation is highly addictive, and the one sentence I see most is: **It’s out of 
control**. When evil thoughts come together, what moderate discomfort is completely forgotten. Some people are only satisfied after a few consecutive times, even for several days in a row. Is this called moderation? Some people have relatively strong self-control and can try their best to do it once a week, but a few years later, they have physical problems and are also entangled in symptoms. The harm of masturbation is cumulative and delayed, and obscenity is a secret leak, and it is missed without knowing it. Although many people are trying to restrain themselves, they miss more of their obscenities, and they don't know it at all. When the symptoms come out, it will be too 
late to regret!

The water in the pipe is too deep, and one doesn't know much. For example, the time of relapse is also very mysterious. Noon is when Yin Qi is weakest, and Zi Shi is when Yang Qi is weakest. 
Therefore, the rest of these two hours is important for health preservation. The most critical. If you break the vows when your body is at its weakest, the damage caused by masturbation is doubled, and it is difficult for your body to recover. Every day the body has a strong and weak movement pattern, and the same is true every month. If you break the vows when you are weak, the probability of developing symptoms will increase a lot. It means that you will be in charge once a month. If you catch up with the time of frailty, it is very likely that you will have symptoms. Another point is that everybody's constitution is different. Some people have different talents, strong foundations, and can afford to be injured a little. If the frequency is the same however, they will have symptoms later. And some people are born with poor physique, even weak and sick, and don't like sports. Such a body will experiencevarious discomforts within two years. Human physiques are very different, but no matter how good your physique is, if you don’t pay attention to rebooting and keeping your essence, problems will occur sooner or later. Just like the rich, if you don't pay attention to increasing income and reducing 
expenditure, sooner or later they will sit back and eat.

It is an iron fact that it is harmful to masturbate. If you look at the victim's case more, you will understand the truth of masturbation. If you only look at the harmlessness theory, then the truth will be obscured by the harmlessness theory. In particular, many young people do not have any discerning ability. Whenever they look at the harmlessness theory, it will shake their rebooting determination. The harmlessness theory is really harmful! Many brothers will come up with a sentence like "I was so badly harmed by the harmlessness theory" when they break down afterwards. This sentence is very ironic. Countless people. If we do not keep our eyes open, we will be deceived and misled by harmlessness! Practice leads to truth, and practice is the 
standard for testing truth. If it is harmful or harmless, please see the real case. The truth is not in the mouth of the brick family, but the truth is in the victim's case. Listening to the fallacies of the brick family will only lead oneself astray.

The addictive nature of PMO is extremely high. If you divide it according to the addiction level, PMO will not lose to drugs. It is basically a one-time addiction, and it is out of control. Some people take drugs, it is not necessarily an addiction, it may take several years to become addicted. However, over 99% of addictions are an addiction. If your heart addiction is more serious, your lust will fly all over the sky, even once every few minutes. In fact, fantasizing is a chronic drug. Comparing fantasizing to drugs is a profound experience of people who have passed by. If we want to quit sex, we must do it completely, don't compromise with the inner demon, don't let the harmless theory remain in our brains, and completely eliminate the harmless theory from our brains. When you release the inner 
demon, the inner demon controls you, and you become a puppet at its mercy! Masturbation belongs to adultery, and it hurts one's body and morals. It is really impossible to commit it just once. Many people, especially young people, are still very little conscious and even full of misunderstandings in their minds. In this case, talking about moderation is simply pushing people into the fire pit.

Regarding the theory of harmlessness, I suggest that everyone should be familiar with basic TCM health knowledge, such as the kidney storing essence and the vitality of the essence of the five 
internal organs; for example, the kidneys dominate the bones, and kidney weakness will cause weakness in the waist and knees, and soft legs are more common; The kidney is connected to the brain, it is more brain-damaging to use a masturbation than to the kidney; and the waist is the home of the kidney, and it is common to have low back pain after masturbation injures the kidney. In addition, the kidney is the blossom, the kidney is the root of the five internal organs, the kidney is the root of the five internal organs, and the kidneys protect from all kinds of diseases.  The kidney is a powerful official. Chinese medicine should be known. The children of a person must know the doctor, the ignorant is fearless, because ignorance is unscrupulous, and because of ignorance, he dares to chaos. Regarding the harm of indulgence to the kidney, our traditional 
Chinese medicine has already explained it very clearly. If you have a certain degree of knowledge and understanding of Chinese medicine, it is very helpful to get rid of masturbation. The medical theory of Chinese medicine can improve your understanding and make you understand the reasons 
for many discomforts in your body. This can strengthen your rebooting determination and confidence.

When we reboot, we must thoroughly understand the harmlessness theory. The hurdle of harmlessness must be passed, and this is also the first hurdle. If you don’t understand clearly about harmlessness, then you won’t be able to reboot successfully, because you always want to engage in moderation. And the moderate water is too deep, the best way is to completely quit masturbation and go directly ashore! The sea is boundless, and the shore is turning back! Only going ashore is an 
absolutely wise choice. In addition, I suggest that brothers must stay away from the harmless theory. Seeing the harmless theory means that we are not the enemy. Many people immediately 
waver when they see the harmless theory. As I now have a very high level of consciousness, I don't know how to look at harmlessness. If I look at harmlessness, I will be brainwashed, and I will be brainwashed by fallacies and heresies. Unless you have a high level of consciousness to resist brainwashing, you will be led into the ditch. When I was a teenager, I looked at harmlessness theory and felt that harmlessness theory was quite right, because at that time I didn’t have the ability to 
distinguish and lacked correct guidance, but now I feel that harmlessness theory is full of loopholes,completely inconsistent with the actual situation, and completely unsuitable. In line with the facts, harmlessness can only deceive children, as well as adults with low consciousness like children!

>2.The correct motivation for rebooting
It is extremely critical for successful rebooting,
If you quit for better indulgence,
Or just quit for sexual function,
It is extremely easy to fail,
Because the motivation was wrong from the beginning,
The result must be failure!

**Marrow explanation:** I specifically pointed out the issue of rebooting motivation in a very early article of mine, because I found that many brothers only started rebooting after premature ejaculation and impotence. They were very concerned about sexual function, which is not difficult to understand. Understand, 
because most of the brothers will choose to live in marriage. If they are abandoned before they get married, it will be very embarrassing after marriage. This is the case in many actual cases I have come into contact with. Because of years of abuse, sexual function has been severely damaged. In severe cases, it is basically impotence. In addition, it is more common to have weak erections, difficult erections, and soft erections without stamina. Brothers of premature ejaculation are also very common. A lot of people’s time for arguing is getting shorter and shorter. It could have been ten minutes at first, but it didn’t work after ten seconds. What I want to say is that masturbation can 
hurt sexual function. This is a conclusive fact, which can be understood by looking at more cases.

Many brothers have been wasted, or become half-wasted, and their family is urging to get married, which makes them very distressed. How do you know that today? Because of being young and ignorant, sooner or later there will be a painful price. Some brothers have already divorced because their sex life is not good. Disharmony in sex life is also a factor leading to divorce. Once you have premature ejaculation and impotence, your wife may also be derailed. Disharmony in sex life will also affect the relationship between husband and wife. Some brothers found that they were not working, and they immediately started to make up. The concept in their mind was to make up if you 
lost it, especially if you were taking tonics and even taking Viagra. Originally, premature ejaculation and impotence were a warning to your body. Indulge in indulgence, it is time to stop, 
and because of ignorance, some brothers can't understand the signals given by the body at all. Instead, they use drugs to mobilize the last bit of kidney qi for them to indulge. It doesn't take long for the body to have serious problems. Yuan Shikai was indulging in lust, wives and concubines were in groups, and antler and ginseng were eaten as a meal. Soon after, he became seriously ill and died!

Tonics should be taken with caution. Taking many tonics will encourage desire. If you do not have a high level of consciousness, you are likely to relapse. For example, some brothers become more likely to relapse after taking Chinese medicine. The most taboo of seeing Chinese medicine 
for taking medicine is to leak while eating. Good Chinese medicine will advise you to abstain from sex for a period of time, but these types of good Chinese medicine are becoming fewer and fewer now. I remember a case where the patient asked the Chinese medicine doctor why the gray hair increased after taking Chinese medicine, and the body did not improve much. The Chinese doctor asked, don’t you know that three-point treatment and seven-point health preservation? Can I get 
better while indulging in Chinese medicine? The question of this Chinese medicine doctor can explain the problem. Many patients now have too poor awareness of health preservation. In fact, the
biggest supplement is not leaking. The bottom is not leaking. The effect can be guaranteed by taking medicine and conditioning. Just like a water tank, there is no leakage from the bottom and 
water on the top. The water tank can be full, otherwise the body will never heal. Some Chinese medicines promote desire. If you don't make it right, you will leak more. After taking Chinese 
medicines, you must strengthen your mind. My suggestion is that if you are sick, you can see a Chinese medicine for treatment, but while taking Chinese medicine, you must be vigilant, do a good job of ideological work of abstinence, and avoid leakage of sperm during the medicine. This is very important.
